import { useCallback,useEffect,useMemo,useState } from 'react'
import { useNavigate,useParams } from 'react-router-dom'
import { Award,BookOpenCheck,CalendarClock,CheckCircle2,ClipboardCheck,Clock3,FileText,Mail,Pencil,Plus,RefreshCw,Send,Star,Trash2,Users } from 'lucide-react'
import { Page } from '../../design-system/Page'
import { EntityRecordShell } from '../../design-system/EntityRecordShell'
import { Button } from '../../design-system/Button'
import { SaveButton } from '../../design-system/SaveButton'
import { ObserverDialog,DialogActions } from '../../design-system/ObserverDialog'
import { AttachmentField } from '../../design-system/AttachmentField'
import { FilterBar,FilterSelect } from '../../design-system/FilterBar'
import { MetricCard } from '../../design-system/MetricCard'
import { RecordActions } from '../../design-system/RecordActions'
import { RegistryPagination } from '../../design-system/RegistryPagination'
import { RouteLoading } from '../../design-system/RouteLoading'
import { UI_ACTIONS } from '../../core/actions/actionPolicy'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useTenant } from '../../core/tenant/TenantContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { useRegistryMemory } from '../../core/navigation/useRegistryMemory'
import { useEmployeesData } from '../employees/useEmployeesData'
import { loadDepartments } from '../management/departmentsService'
import { CAPABILITIES,ROLES,can } from '../../core/permissions/roles'
import { computedAssignmentStatus } from './trainingData'
import { deleteTrainingRecordAsync,loadTrainingStateAsync,saveManagedTrainingStateAsync } from './trainingService'
import { processTrainingOutboxAsync,queueTrainingInvitationAsync } from './trainingInvitationService'
import { TrainingProgramForm,trainingProgramIsValid,trainingCategoryLabel,trainingMethodLabel } from './TrainingProgramForm'

const fmt=v=>{if(!v)return '—';const d=new Date(`${String(v).slice(0,10)}T12:00:00`);return d.toLocaleDateString('el-GR',{day:'2-digit',month:'2-digit',year:'numeric'})}
const labels={active:['Ενεργό','Active'],planned:['Προγραμματισμένο','Planned'],completed:['Ολοκληρωμένο','Completed'],assigned:['Ανατέθηκε','Assigned'],in_progress:['Σε εξέλιξη','In progress'],overdue:['Εκπρόθεσμο','Overdue'],cancelled:['Ακυρώθηκε','Cancelled']}
const blankState={programs:[],assignments:[],certificates:[],emailOutbox:[],history:[]}

export function TrainingProductionPage(){
 const {programId}=useParams(),navigate=useNavigate(),registry=useRegistryMemory('training-programs'),{language}=useLanguage(),en=language==='en',{tenant,role,membership}=useTenant(),{notify,notifyError,confirm}=useFeedback(),{data:employees}=useEmployeesData()
 const [state,setState]=useState(blankState),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[category,setCategory]=useState('all'),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(15),[departments,setDepartments]=useState([])
 const canManage=can(role,CAPABILITIES.MANAGE_TRAINING,membership?.capabilities??[],membership?.customCapabilities??[]),managerView=role===ROLES.DEPARTMENT_MANAGER&&!canManage,employeeView=!canManage&&!managerView
 const reload=useCallback(async()=>{if(!tenant?.id)return;setLoading(true);try{setState(await loadTrainingStateAsync(tenant.id))}catch(error){notifyError(error,'load',{operation:'training_load'})}finally{setLoading(false)}},[tenant?.id,notifyError])
 useEffect(()=>{void reload()},[reload])
 useEffect(()=>{let active=true;if(!tenant?.id)return;loadDepartments(tenant.id).then(rows=>{if(active)setDepartments((rows||[]).filter(x=>x.is_active!==false))}).catch(()=>{if(active)setDepartments([])});return()=>{active=false}},[tenant?.id])
 async function persist(next,success){if(!canManage)return false;setBusy(true);try{const saved=await saveManagedTrainingStateAsync(tenant.id,next);setState(saved);if(success)notify(success,'success');return true}catch(error){notifyError(error,'save',{operation:'training_save'});return false}finally{setBusy(false)}}
 const assignments=useMemo(()=>state.assignments.map(x=>({...x,computedStatus:computedAssignmentStatus(x)})),[state.assignments])
 const programs=state.programs.filter(x=>(status==='all'||x.status===status)&&(category==='all'||x.category===category)&&`${x.id} ${x.title} ${x.owner} ${x.trainer} ${x.audience}`.toLowerCase().includes(query.toLowerCase())),categories=[...new Set(state.programs.map(x=>x.category).filter(Boolean))]
 useEffect(()=>setPage(1),[query,status,category,pageSize])
 const totalPages=Math.max(1,Math.ceil(programs.length/pageSize)),safePage=Math.min(page,totalPages),pagedPrograms=programs.slice((safePage-1)*pageSize,safePage*pageSize)
 const selected=state.programs.find(x=>x.id===programId),selectedAssignments=selected?assignments.filter(x=>x.programId===selected.id):[]
 const completed=assignments.filter(x=>x.computedStatus==='completed').length,overdue=assignments.filter(x=>x.computedStatus==='overdue').length,dueSoon=assignments.filter(x=>['assigned','in_progress'].includes(x.computedStatus)&&x.dueDate&&daysUntil(x.dueDate)>=0&&daysUntil(x.dueDate)<=14).length,completionRate=assignments.length?Math.round(completed/assignments.length*100):0
 if(loading)return <RouteLoading/>
 if(selected&&canManage)return <ProgramRecord en={en} language={language} organizationId={tenant.id} program={selected} assignments={selectedAssignments} state={state} employees={employees||[]} departments={departments} busy={busy} notify={notify} notifyError={notifyError} confirm={confirm} reload={reload} onBack={()=>navigate('/training')} onPersist={persist} onDelete={async()=>{if(selectedAssignments.length){notify(en?'The program has participants and cannot be deleted.':'Το πρόγραμμα έχει συμμετέχοντες και δεν μπορεί να διαγραφεί.','warning');return}if(!await confirm({title:en?'Delete program':'Διαγραφή προγράμματος',message:en?'Delete this training program?':'Να διαγραφεί το πρόγραμμα εκπαίδευσης;',danger:true}))return;await deleteTrainingRecordAsync(tenant.id,selected.id);navigate('/training');await reload()}}/>
 function pageAction(action){if(action===UI_ACTIONS.CREATE)navigate('/training/new')}
 function openProgram(id){registry.openRecord(navigate,`/training/${id}`,id,programs.map(x=>x.id))}
 return <Page fill title={en?'Training':'Εκπαίδευση'} subtitle={employeeView?(en?'Your assigned training and completion evidence.':'Οι ανατεθειμένες εκπαιδεύσεις και τα τεκμήρια ολοκλήρωσής σας.'):(en?'Training programs, participation and competency monitoring.':'Προγράμματα εκπαίδευσης, συμμετοχές και παρακολούθηση επάρκειας.')} actions={<RecordActions actions={canManage?[UI_ACTIONS.CREATE]:[]} resourceCapability={CAPABILITIES.VIEW_TRAINING} actionCapabilities={{[UI_ACTIONS.CREATE]:CAPABILITIES.MANAGE_TRAINING}} onAction={pageAction}/> }>
  <div className="module-summary-strip">{employeeView?<><MetricCard icon={BookOpenCheck} value={assignments.filter(x=>x.computedStatus!=='completed').length} label={en?'Assigned':'Ανατεθειμένες'}/><MetricCard icon={CheckCircle2} value={completed} label={en?'Completed':'Ολοκληρωμένες'}/><MetricCard icon={Award} value={state.certificates.length} label={en?'Certificates':'Πιστοποιητικά'}/></>:<><MetricCard icon={Users} value={assignments.length} label={en?'Assignments':'Αναθέσεις'}/><MetricCard icon={CheckCircle2} value={`${completionRate}%`} label={en?'Completion':'Ολοκλήρωση'}/><MetricCard icon={CalendarClock} value={dueSoon} label={en?'Due soon':'Λήγουν σύντομα'}/><MetricCard icon={Clock3} value={overdue} label={en?'Overdue':'Εκπρόθεσμες'}/></>}</div>
  <section className="surface registry-workspace training-registry workspace-column workspace-fill">{canManage?<><FilterBar query={query} onQueryChange={setQuery} placeholder={en?'Search training program...':'Αναζήτηση προγράμματος εκπαίδευσης...'} activeAdvancedCount={(status==='all'?0:1)+(category==='all'?0:1)} onClear={()=>{setQuery('');setStatus('all');setCategory('all')}}><FilterSelect label={en?'Status':'Κατάσταση'} value={status} onChange={setStatus}><option value="all">{en?'All':'Όλα'}</option><option value="active">{en?'Active':'Ενεργά'}</option><option value="planned">{en?'Planned':'Προγραμματισμένα'}</option><option value="completed">{en?'Completed':'Ολοκληρωμένα'}</option></FilterSelect><FilterSelect label={en?'Category':'Κατηγορία'} value={category} onChange={setCategory}><option value="all">{en?'All':'Όλες'}</option>{categories.map(x=><option key={x} value={x}>{trainingCategoryLabel(x,language)}</option>)}</FilterSelect></FilterBar><Programs rows={pagedPrograms} en={en} language={language} onOpen={openProgram} registry={registry}/><RegistryPagination language={language} page={safePage} totalPages={totalPages} totalItems={programs.length} pageSize={pageSize} onPageChange={setPage} onPageSizeChange={setPageSize}/></>:<Assignments rows={assignments} state={state} en={en} employeeView={employeeView}/>}</section>
 </Page>
}

function ProgramRecord({en,language,organizationId,program,assignments,state,employees,departments,busy,notify,notifyError,confirm,reload,onBack,onPersist,onDelete}){
 const [tab,setTab]=useState('overview'),[dialog,setDialog]=useState(null),[mailBusy,setMailBusy]=useState(''),[editing,setEditing]=useState(false),[draft,setDraft]=useState(program)
 useEffect(()=>{setDraft(program);setEditing(false)},[program])
 const tabs=[{id:'overview',label:en?'Overview':'Σύνοψη',icon:CheckCircle2},{id:'participants',label:en?'Participants':'Συμμετέχοντες',icon:Users},{id:'materials',label:en?'Material':'Υλικό',icon:FileText},{id:'assessment',label:en?'Assessment':'Αξιολόγηση',icon:ClipboardCheck},{id:'results',label:en?'Results':'Αποτελέσματα',icon:Award}]
 async function sendInvitation(row){setMailBusy(row.id);try{await queueTrainingInvitationAsync(row.id,language);await processTrainingOutboxAsync(organizationId);notify(en?'Invitation email sent.':'Το email πρόσκλησης στάλθηκε.','success');await reload()}catch(error){notifyError(error,'send',{operation:'training_invitation_send'})}finally{setMailBusy('')}}
 async function saveProgram(){if(!trainingProgramIsValid(draft)||busy)return;const next={...draft,id:program.id,dbId:program.dbId,materials:program.materials||[],assessmentQuestions:program.assessmentQuestions||[],feedbackResponses:program.feedbackResponses||[],createdAt:program.createdAt,updatedAt:new Date().toISOString()};if(await onPersist({...state,programs:state.programs.map(x=>x.id===program.id?next:x)},en?'Training program updated.':'Το πρόγραμμα εκπαίδευσης ενημερώθηκε.'))setEditing(false)}
 async function removeParticipant(row){if(row.status==='completed'){notify(en?'Completed training records are retained for traceability.':'Οι ολοκληρωμένες εκπαιδεύσεις διατηρούνται για ιχνηλασιμότητα.','warning');return}if(!await confirm({title:en?'Remove participant':'Αφαίρεση συμμετέχοντα',message:en?'Remove this participant from the training program?':'Να αφαιρεθεί ο συμμετέχων από το πρόγραμμα εκπαίδευσης;',danger:true}))return;try{await deleteTrainingRecordAsync(organizationId,row.id);notify(en?'Participant removed.':'Ο συμμετέχων αφαιρέθηκε.','success');await reload()}catch(error){notifyError(error,'delete',{operation:'training_participant_delete'})}}
 const headerActions=!editing?<><button type="button" className="lo-icon-button lo-icon-button-edit" onClick={()=>setEditing(true)} title={en?'Edit':'Επεξεργασία'} aria-label={en?'Edit':'Επεξεργασία'}><Pencil size={16}/></button>{assignments.length===0&&<button type="button" className="lo-icon-button lo-icon-button-danger" onClick={onDelete} disabled={busy} title={en?'Delete':'Διαγραφή'} aria-label={en?'Delete':'Διαγραφή'}><Trash2 size={16}/></button>}</>:null
 return <Page fill><EntityRecordShell className="workspace-fill" avatar={<BookOpenCheck size={19}/>} eyebrow={program.id} title={program.title} subtitle={`${trainingCategoryLabel(program.category,language)} · ${trainingMethodLabel(program.method,language)} · ${en?'Trainer':'Εκπαιδευτής'}: ${program.trainer||program.owner||'—'}`} status={<Badge status={program.status}/>} headerActions={headerActions} tabs={tabs} activeTab={tab} onTabChange={setTab} onBack={onBack} backLabel={en?'Back to programs':'Πίσω στα προγράμματα'}>
  <div className="workspace-column workspace-fill">
   {tab==='overview'&&<section className="record-section"><div className="record-section-header"><div><span className="eyebrow">{en?'Training program':'Πρόγραμμα εκπαίδευσης'}</span><h3>{en?'Program details':'Στοιχεία προγράμματος'}</h3><p>{en?'Program metadata, audience, dates and competency requirements.':'Στοιχεία προγράμματος, κοινό, ημερομηνίες και απαιτήσεις επάρκειας.'}</p></div></div><TrainingProgramForm value={draft} onChange={setDraft} language={language} readOnly={!editing} employees={employees} departments={departments}/>{editing&&<div className="inline-edit-footer"><Button variant="secondary" onClick={()=>{setDraft(program);setEditing(false)}} disabled={busy}>{en?'Cancel':'Ακύρωση'}</Button><SaveButton loading={busy} disabled={!trainingProgramIsValid(draft)||busy} onClick={saveProgram}>{en?'Save':'Αποθήκευση'}</SaveButton></div>}</section>}
   {tab==='participants'&&<Participants rows={assignments} en={en} busy={busy} mailBusy={mailBusy} onInvite={sendInvitation} onRemove={removeParticipant} onAdd={()=>setDialog({type:'participants'})}/>} 
   {tab==='materials'&&<section className="record-section"><div className="record-section-header"><div><span className="eyebrow">{en?'Training material':'Εκπαιδευτικό υλικό'}</span><h3>{en?'Files & attachments':'Αρχεία & συνημμένα'}</h3><p>{en?'Upload presentations, procedures, attendance sheets or supporting material.':'Ανεβάστε παρουσιάσεις, διαδικασίες, παρουσιολόγια ή άλλο υποστηρικτικό υλικό.'}</p></div></div><AttachmentField organizationId={organizationId} entityType="training_program" entityId={program.dbId||program.id} value={[]} onChange={()=>{}}/></section>}
   {tab==='assessment'&&<Questions program={program} en={en}/>} {tab==='results'&&<Results rows={assignments} en={en}/>} 
  </div>
  {dialog?.type==='participants'&&<ParticipantsDialog en={en} departments={departments} employees={employees.filter(e=>e.employmentStatus==='active'&&!assignments.some(a=>a.employeeId===e.id||a.employeeId===e.employeeCode))} busy={busy} onClose={()=>setDialog(null)} onSave={async({selected,manual})=>{const now=new Date().toISOString(),fromEmployees=selected.map(e=>({id:`TRA-${Date.now()}-${e.id}`,programId:program.id,employeeId:e.employeeCode||e.id,employeeName:`${e.firstName||''} ${e.lastName||''}`.trim(),department:e.department||'',departmentId:e.departmentId||null,email:e.email||'',assignedDate:now.slice(0,10),dueDate:program.dueDate,status:'assigned',attendanceResponse:'not_sent',attendance:null,completionConfirmedAt:null,score:null,competent:null,certificateId:null,createdAt:now})),fromManual=manual?.name?.trim()?[{id:`TRA-MAN-${Date.now()}`,programId:program.id,employeeId:'',employeeName:manual.name.trim(),department:manual.department.trim(),email:manual.email.trim(),assignedDate:now.slice(0,10),dueDate:program.dueDate,status:'assigned',attendanceResponse:'not_sent',attendance:null,completionConfirmedAt:null,score:null,competent:null,certificateId:null,createdAt:now,manualEntry:true}]:[];if(await onPersist({...state,assignments:[...state.assignments,...fromEmployees,...fromManual]},en?'Participants added.':'Οι συμμετέχοντες προστέθηκαν.'))setDialog(null)}}/>}
 </EntityRecordShell></Page>
}

function Participants({rows,en,onAdd,busy,mailBusy,onInvite,onRemove}){const sent=rows.filter(x=>x.invitationSentAt).length,confirmed=rows.filter(x=>x.attendanceResponse==='confirmed').length,completed=rows.filter(x=>x.status==='completed').length;return <div className="workspace-column workspace-fill"><div className="module-summary-strip"><MetricCard icon={Mail} value={`${sent}/${rows.length}`} label={en?'Invitations':'Προσκλήσεις'}/><MetricCard icon={CheckCircle2} value={`${confirmed}/${rows.length}`} label={en?'Attendance':'Παρουσία'}/><MetricCard icon={ClipboardCheck} value={`${completed}/${rows.length}`} label={en?'Completed':'Ολοκλήρωση'}/></div><div className="section-toolbar"><div><strong>{en?'Participants':'Συμμετέχοντες'}</strong><small>{en?'Select employees from the registry or add an external/manual participant.':'Επιλέξτε εργαζομένους από το μητρώο ή προσθέστε εξωτερικό/χειροκίνητο συμμετέχοντα.'}</small></div><Button disabled={busy} onClick={onAdd}><Plus size={15}/> {en?'Add participants':'Προσθήκη συμμετεχόντων'}</Button></div><div className="scroll-table"><table className="data-table sticky-table"><thead><tr><th>{en?'Participant':'Συμμετέχων'}</th><th>{en?'Department':'Τμήμα'}</th><th>Email</th><th>{en?'Invitation':'Πρόσκληση'}</th><th>{en?'Attendance':'Παρουσία'}</th><th>{en?'Evaluation':'Αξιολόγηση'}</th><th></th></tr></thead><tbody>{rows.map(x=>{const linked=Boolean(x.userId||x.accountLinked),sent=Boolean(x.invitationSentAt),done=x.status==='completed';return <tr key={x.id}><td><strong>{x.employeeName||'—'}</strong><small>{x.manualEntry?(en?'Manual entry':'Χειροκίνητη καταχώρηση'):(x.employeeId||'—')}</small></td><td>{x.department||'—'}</td><td>{x.email||'—'}<small>{linked?(en?'Account linked':'Συνδεδεμένος λογαριασμός'):(en?'No account linked':'Χωρίς συνδεδεμένο λογαριασμό')}</small></td><td>{sent?<><span className="status-badge active">{en?'Sent':'Στάλθηκε'}</span><small>{fmt(x.invitationSentAt)}</small></>:<span className="status-badge">{en?'Not sent':'Δεν στάλθηκε'}</span>}</td><td>{x.attendanceResponse==='confirmed'?<span className="status-badge active">{en?'Confirmed':'Επιβεβαιώθηκε'}</span>:<span className="status-badge">{en?'Pending':'Εκκρεμεί'}</span>}</td><td>{done?<span className="status-badge active">{x.score!=null?`${x.score}%`:(en?'Completed':'Ολοκληρώθηκε')}</span>:<span className="status-badge">{en?'Pending':'Εκκρεμεί'}</span>}</td><td className="open-record-cell"><div className="record-actions">{linked&&x.email&&!done&&<Button variant="secondary" disabled={mailBusy===x.id} onClick={()=>onInvite(x)}>{sent?<RefreshCw size={14}/>:<Send size={14}/>} {sent?(en?'Resend':'Επαναποστολή'):(en?'Send':'Αποστολή')}</Button>}{!done&&<button type="button" className="lo-icon-button lo-icon-button-danger lo-icon-button-sm" onClick={()=>onRemove(x)} title={en?'Remove':'Αφαίρεση'} aria-label={en?'Remove':'Αφαίρεση'}><Trash2 size={14}/></button>}</div></td></tr>})}</tbody></table></div></div>}
function Programs({rows,en,language,onOpen,registry}){return <div className="scroll-table" ref={registry.scrollRef}><table className="data-table sticky-table"><thead><tr><th>{en?'Program':'Πρόγραμμα'}</th><th>{en?'Trainer':'Εκπαιδευτής'}</th><th>{en?'Audience':'Κοινό'}</th><th>{en?'Period':'Περίοδος'}</th><th>{en?'Assessment':'Αξιολόγηση'}</th><th>{en?'Status':'Κατάσταση'}</th></tr></thead><tbody>{rows.map(x=><tr key={x.id} {...registry.rowProps(x.id,()=>onOpen(x.id))}><td><strong>{x.title}</strong><small>{trainingCategoryLabel(x.category,language)} · {trainingMethodLabel(x.method,language)}</small></td><td>{x.trainer||x.owner||'—'}</td><td>{x.audience||'—'}</td><td>{fmt(x.startDate)} → {fmt(x.dueDate)}</td><td>{x.requiresAssessment?`≥ ${x.passScore}%`:(en?'Not required':'Δεν απαιτείται')}</td><td><Badge status={x.status}/></td></tr>)}</tbody></table>{!rows.length&&<div className="registry-empty-state"><strong>{en?'No training programs':'Δεν υπάρχουν προγράμματα εκπαίδευσης'}</strong></div>}</div>}
function Assignments({rows,state,en,employeeView=false}){return <div className="scroll-table"><table className="data-table sticky-table"><thead><tr>{!employeeView&&<><th>{en?'Employee':'Εργαζόμενος'}</th><th>{en?'Department':'Τμήμα'}</th></>}<th>{en?'Training':'Εκπαίδευση'}</th><th>{en?'Due':'Προθεσμία'}</th><th>{en?'Result':'Αποτέλεσμα'}</th><th>{en?'Status':'Κατάσταση'}</th></tr></thead><tbody>{rows.map(x=>{const p=state.programs.find(v=>v.id===x.programId);return <tr key={x.id}>{!employeeView&&<><td><strong>{x.employeeName||'—'}</strong></td><td>{x.department||'—'}</td></>}<td><strong>{p?.title||x.programId}</strong></td><td>{fmt(x.dueDate)}</td><td>{x.score!=null?`${x.score}%`:x.status==='completed'?(en?'Completed':'Ολοκληρώθηκε'):'—'}</td><td><Badge status={x.computedStatus}/></td></tr>})}</tbody></table></div>}
function Questions({program,en}){const rows=program.assessmentQuestions||[];return <section className="record-section"><div className="record-section-header"><div><h3>{en?'Knowledge assessment':'Αξιολόγηση γνώσεων'}</h3><p>{en?'Questions are configured for this training program.':'Οι ερωτήσεις ορίζονται για το συγκεκριμένο πρόγραμμα εκπαίδευσης.'}</p></div></div>{rows.length?<div className="scroll-table"><table className="data-table"><thead><tr><th>#</th><th>{en?'Question':'Ερώτηση'}</th><th>{en?'Points':'Βαθμοί'}</th></tr></thead><tbody>{rows.map((q,i)=><tr key={q.id}><td>{i+1}</td><td><strong>{q.text}</strong></td><td>{q.points||1}</td></tr>)}</tbody></table></div>:<div className="inline-empty">{en?'No assessment questions yet.':'Δεν έχουν προστεθεί ακόμη ερωτήσεις αξιολόγησης.'}</div>}</section>}
function Results({rows,en}){const completed=rows.filter(x=>x.status==='completed').length,scored=rows.filter(x=>x.score!=null),avg=scored.length?Math.round(scored.reduce((a,b)=>a+Number(b.score||0),0)/scored.length):0;return <div className="module-summary-strip"><MetricCard icon={CheckCircle2} value={completed} label={en?'Completed':'Ολοκληρώσεις'}/><MetricCard icon={ClipboardCheck} value={scored.length?`${avg}%`:'—'} label={en?'Average score':'Μέση επίδοση'}/><MetricCard icon={Star} value={rows.filter(x=>x.competent===true).length} label={en?'Competent':'Επαρκείς'}/></div>}
function ParticipantsDialog({employees,departments,onClose,onSave,busy,en}){const [ids,setIds]=useState([]),[manual,setManual]=useState({name:'',department:'',email:''});const selected=employees.filter(x=>ids.includes(x.id)),valid=selected.length>0||manual.name.trim();return <ObserverDialog width="wide" title={en?'Add participants':'Προσθήκη συμμετεχόντων'} onClose={onClose} footer={<DialogActions onCancel={onClose} disabled={busy||!valid} onSave={()=>onSave({selected,manual})}/>}><div className="workspace-column"><div><span className="eyebrow">{en?'Employee registry':'Μητρώο εργαζομένων'}</span><h3>{en?'Select employees':'Επιλογή εργαζομένων'}</h3></div><div className="scroll-table"><table className="data-table"><thead><tr><th></th><th>{en?'Employee':'Εργαζόμενος'}</th><th>{en?'Department':'Τμήμα'}</th><th>Email</th></tr></thead><tbody>{employees.map(x=><tr key={x.id}><td><input type="checkbox" checked={ids.includes(x.id)} onChange={()=>setIds(s=>s.includes(x.id)?s.filter(v=>v!==x.id):[...s,x.id])}/></td><td><strong>{x.firstName} {x.lastName}</strong></td><td>{x.department||'—'}</td><td>{x.email||'—'}</td></tr>)}</tbody></table></div><div className="record-section"><div className="record-section-header"><div><span className="eyebrow">{en?'Manual entry':'Χειροκίνητη καταχώρηση'}</span><h3>{en?'External or unregistered participant':'Εξωτερικός ή μη καταχωρημένος συμμετέχων'}</h3></div></div><div className="entry-grid"><label><span>{en?'Full name':'Ονοματεπώνυμο'}</span><input value={manual.name} onChange={e=>setManual(x=>({...x,name:e.target.value}))}/></label><label><span>{en?'Department / organization':'Τμήμα / φορέας'}</span><input list="training-manual-departments" value={manual.department} onChange={e=>setManual(x=>({...x,department:e.target.value}))}/><datalist id="training-manual-departments">{departments.map(x=><option key={x.id||x.name} value={x.name||x.label||''}/>)}</datalist></label><label><span>Email</span><input type="email" value={manual.email} onChange={e=>setManual(x=>({...x,email:e.target.value}))}/></label></div></div></div></ObserverDialog>}
function Badge({status}){const {language}=useLanguage(),en=language==='en';return <span className={`status-badge ${status==='active'||status==='completed'?'active':''} ${status==='overdue'||status==='cancelled'?'danger':''}`.trim()}>{labels[status]?.[en?1:0]||status||'—'}</span>}
function daysUntil(iso){return Math.ceil((new Date(`${iso}T12:00:00`)-new Date())/86400000)}
