import { useMemo,useState } from 'react'
import { Plus,Search,Trash2,UserRoundPlus,Users } from 'lucide-react'
import { ObserverDialog,DialogActions } from '../../design-system/ObserverDialog'
import { Button } from '../../design-system/Button'

const emptyManual={name:'',department:'',email:''}
const makeManualId=()=>`MAN-${Date.now()}-${Math.random().toString(36).slice(2,7)}`

export function TrainingParticipantsDialog({employees=[],departments=[],onClose,onSave,busy=false,en=false}){
 const [mode,setMode]=useState(employees.length?'registry':'manual'),[ids,setIds]=useState([]),[query,setQuery]=useState(''),[department,setDepartment]=useState('all'),[manualDraft,setManualDraft]=useState(emptyManual),[manualEntries,setManualEntries]=useState([])
 const departmentNames=useMemo(()=>[...new Set(employees.map(x=>x.department).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'el')),[employees])
 const visible=useMemo(()=>employees.filter(x=>(department==='all'||x.department===department)&&`${x.firstName||''} ${x.lastName||''} ${x.employeeCode||''} ${x.email||''} ${x.department||''}`.toLowerCase().includes(query.toLowerCase())),[employees,department,query])
 const selected=useMemo(()=>employees.filter(x=>ids.includes(x.id)),[employees,ids])
 const total=selected.length+manualEntries.length,allVisibleSelected=visible.length>0&&visible.every(x=>ids.includes(x.id))
 function toggleAll(){const visibleIds=visible.map(x=>x.id);setIds(current=>allVisibleSelected?current.filter(id=>!visibleIds.includes(id)):[...new Set([...current,...visibleIds])])}
 function addManual(){const name=manualDraft.name.trim();if(!name)return;setManualEntries(rows=>[...rows,{...manualDraft,id:makeManualId(),name,department:manualDraft.department.trim(),email:manualDraft.email.trim()}]);setManualDraft(emptyManual)}
 return <ObserverDialog width="wide" title={en?'Add participants':'Προσθήκη συμμετεχόντων'} onClose={onClose} footer={<DialogActions onCancel={onClose} disabled={busy||!total} onSave={()=>onSave({selected,manualEntries})}/>}>
  <div className="training-participant-dialog">
   <div className="training-participant-mode" role="tablist" aria-label={en?'Participant source':'Πηγή συμμετεχόντων'}>
    <button type="button" className={mode==='registry'?'active':''} onClick={()=>setMode('registry')}><Users size={17}/><span><strong>{en?'From staff registry':'Από το προσωπικό'}</strong><small>{selected.length} {en?'selected':'επιλεγμένοι'}</small></span></button>
    <button type="button" className={mode==='manual'?'active':''} onClick={()=>setMode('manual')}><UserRoundPlus size={17}/><span><strong>{en?'Manual entry':'Χειροκίνητη καταχώρηση'}</strong><small>{manualEntries.length} {en?'staged':'σε αναμονή'}</small></span></button>
   </div>
   <div className="training-participant-basket-summary"><strong>{en?'Ready to save':'Έτοιμοι για αποθήκευση'}: {total}</strong><span>{selected.length} {en?'from staff':'από προσωπικό'} · {manualEntries.length} {en?'manual':'χειροκίνητοι'}</span></div>
   {mode==='registry'&&<section className="training-participant-panel">
    <div className="training-participant-panel-heading"><div><span className="eyebrow">{en?'Employee registry':'Μητρώο εργαζομένων'}</span><h3>{en?'Select participants':'Επιλογή συμμετεχόντων'}</h3><p>{en?'Select one or more employees. Selections remain in the basket while you switch tabs.':'Επιλέξτε έναν ή περισσότερους εργαζομένους. Οι επιλογές παραμένουν στο καλάθι όταν αλλάζετε καρτέλα.'}</p></div><span className="training-selection-count">{selected.length} {en?'selected':'επιλεγμένοι'}</span></div>
    {employees.length?<><div className="training-participant-filters"><label className="training-participant-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={en?'Search name, code, email...':'Αναζήτηση ονόματος, κωδικού, email...'}/></label><select value={department} onChange={e=>setDepartment(e.target.value)}><option value="all">{en?'All departments':'Όλα τα τμήματα'}</option>{departmentNames.map(name=><option key={name} value={name}>{name}</option>)}</select></div><div className="training-participant-list-head"><button type="button" onClick={toggleAll}>{allVisibleSelected?(en?'Clear visible':'Αποεπιλογή ορατών'):(en?'Select visible':'Επιλογή ορατών')}</button><span>{visible.length} {en?'results':'αποτελέσματα'}</span></div><div className="scroll-table training-participant-table-wrap"><table className="data-table sticky-table training-participant-table"><thead><tr><th className="training-check-col"></th><th>{en?'Employee':'Εργαζόμενος'}</th><th>{en?'Code':'Κωδικός'}</th><th>{en?'Department':'Τμήμα'}</th><th>Email</th></tr></thead><tbody>{visible.map(x=>{const checked=ids.includes(x.id);return <tr key={x.id} className={checked?'training-row-selected':''} onClick={()=>setIds(s=>s.includes(x.id)?s.filter(v=>v!==x.id):[...s,x.id])}><td className="training-check-col"><input type="checkbox" checked={checked} onClick={e=>e.stopPropagation()} onChange={()=>setIds(s=>s.includes(x.id)?s.filter(v=>v!==x.id):[...s,x.id])}/></td><td><strong>{`${x.firstName||''} ${x.lastName||''}`.trim()||'—'}</strong></td><td>{x.employeeCode||'—'}</td><td>{x.department||'—'}</td><td>{x.email||'—'}</td></tr>})}</tbody></table>{visible.length===0&&<div className="inline-empty">{en?'No employees match the current filters.':'Δεν βρέθηκαν εργαζόμενοι με τα συγκεκριμένα φίλτρα.'}</div>}</div></>:<div className="training-participant-empty"><Users size={24}/><strong>{en?'The staff registry is empty.':'Το μητρώο εργαζομένων είναι κενό.'}</strong><span>{en?'Use manual entry or populate the hospital staff registry.':'Χρησιμοποιήστε χειροκίνητη καταχώρηση ή συμπληρώστε το μητρώο προσωπικού.'}</span><Button variant="secondary" onClick={()=>setMode('manual')}>{en?'Use manual entry':'Χειροκίνητη καταχώρηση'}</Button></div>}
   </section>}
   {mode==='manual'&&<section className="training-participant-panel training-participant-manual"><div className="training-participant-panel-heading"><div><span className="eyebrow">{en?'Manual entry':'Χειροκίνητη καταχώρηση'}</span><h3>{en?'Add multiple participants':'Προσθήκη πολλών συμμετεχόντων'}</h3><p>{en?'Add each person to the temporary list. Nothing is saved until the final Save action.':'Προσθέστε κάθε άτομο στην προσωρινή λίστα. Τίποτα δεν αποθηκεύεται πριν την τελική Αποθήκευση.'}</p></div></div><div className="entry-grid"><label className="entry-span-2"><span>{en?'Full name *':'Ονοματεπώνυμο *'}</span><input value={manualDraft.name} onChange={e=>setManualDraft(x=>({...x,name:e.target.value}))}/></label><label><span>{en?'Department / organization':'Τμήμα / φορέας'}</span><input list="training-manual-departments" value={manualDraft.department} onChange={e=>setManualDraft(x=>({...x,department:e.target.value}))}/><datalist id="training-manual-departments">{departments.map(x=><option key={x.id||x.name} value={x.name||x.label||''}/>)}</datalist></label><label><span>Email</span><input type="email" value={manualDraft.email} onChange={e=>setManualDraft(x=>({...x,email:e.target.value}))}/></label></div><div className="training-manual-add-row"><Button type="button" variant="secondary" disabled={!manualDraft.name.trim()} onClick={addManual}><Plus size={15}/>{en?'Add to list':'Προσθήκη στη λίστα'}</Button></div>{manualEntries.length>0&&<div className="scroll-table training-manual-table-wrap"><table className="data-table"><thead><tr><th>{en?'Participant':'Συμμετέχων'}</th><th>{en?'Department / organization':'Τμήμα / φορέας'}</th><th>Email</th><th></th></tr></thead><tbody>{manualEntries.map(item=><tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.department||'—'}</td><td>{item.email||'—'}</td><td className="open-record-cell"><button type="button" className="lo-icon-button lo-icon-button-danger lo-icon-button-sm" onClick={()=>setManualEntries(rows=>rows.filter(x=>x.id!==item.id))} aria-label={en?'Remove':'Αφαίρεση'}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>}</section>}
  </div>
 </ObserverDialog>
}
