import { useMemo,useState } from 'react'
import { Plus,Search,Trash2,UserRoundPlus,Users } from 'lucide-react'
import { Page } from '../../design-system/Page'
import { BackButton } from '../../design-system/BackButton'
import { Button } from '../../design-system/Button'
import { SaveButton } from '../../design-system/SaveButton'

const emptyManual={name:'',department:'',email:''}
const makeManualId=()=>`MAN-${Date.now()}-${Math.random().toString(36).slice(2,7)}`

export function TrainingParticipantsDialog({employees=[],alreadyAssignedIds=[],departments=[],onClose,onSave,busy=false,en=false}){
 const [mode,setMode]=useState(employees.length?'registry':'manual'),[ids,setIds]=useState([]),[query,setQuery]=useState(''),[department,setDepartment]=useState('all'),[manualDraft,setManualDraft]=useState(emptyManual),[manualEntries,setManualEntries]=useState([])
 const assignedSet=useMemo(()=>new Set((alreadyAssignedIds||[]).map(String)),[alreadyAssignedIds])
 const departmentNames=useMemo(()=>[...new Set(employees.map(x=>x.department).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'el')),[employees])
 const visible=useMemo(()=>employees.filter(x=>(department==='all'||x.department===department)&&`${x.firstName||''} ${x.lastName||''} ${x.id||''} ${x.employeeCode||''} ${x.email||''} ${x.department||''}`.toLowerCase().includes(query.toLowerCase())),[employees,department,query])
 const selectableVisible=useMemo(()=>visible.filter(x=>!assignedSet.has(String(x.id||x.employeeCode||''))),[visible,assignedSet])
 const selected=useMemo(()=>employees.filter(x=>ids.includes(x.id)&&!assignedSet.has(String(x.id||x.employeeCode||''))),[employees,ids,assignedSet])
 const availableCount=useMemo(()=>employees.filter(x=>!assignedSet.has(String(x.id||x.employeeCode||''))).length,[employees,assignedSet])
 const total=selected.length+manualEntries.length,allVisibleSelected=selectableVisible.length>0&&selectableVisible.every(x=>ids.includes(x.id))
 function toggleAll(){const visibleIds=selectableVisible.map(x=>x.id);setIds(current=>allVisibleSelected?current.filter(id=>!visibleIds.includes(id)):[...new Set([...current,...visibleIds])])}
 function addManual(){const name=manualDraft.name.trim();if(!name)return;setManualEntries(rows=>[...rows,{...manualDraft,id:makeManualId(),name,department:manualDraft.department.trim(),email:manualDraft.email.trim()}]);setManualDraft(emptyManual)}
 return <Page fill className="training-participant-page" navigation={<BackButton onClick={onClose} label={en?'Back to participants':'Πίσω στους συμμετέχοντες'}/>} title={en?'Add participants':'Προσθήκη συμμετεχόντων'} subtitle={en?'Select staff or add external participants manually.':'Επιλέξτε εργαζομένους ή προσθέστε χειροκίνητα εξωτερικούς συμμετέχοντες.'} actions={<div className="training-participant-page-actions"><span className="training-selection-count">{total} {en?'ready':'έτοιμοι'}</span><SaveButton loading={busy} disabled={busy||!total} onClick={()=>onSave({selected,manualEntries})}>{en?'Save participants':'Αποθήκευση συμμετεχόντων'}</SaveButton></div>}>
  <section className="surface training-participant-page-shell workspace-column workspace-fill">
   <div className="training-participant-mode" role="tablist" aria-label={en?'Participant source':'Πηγή συμμετεχόντων'}>
    <button type="button" className={mode==='registry'?'active':''} onClick={()=>setMode('registry')}><Users size={18}/><span><strong>{en?'From staff registry':'Από το προσωπικό'}</strong><small>{availableCount} {en?'available':'διαθέσιμοι'}</small></span></button>
    <button type="button" className={mode==='manual'?'active':''} onClick={()=>setMode('manual')}><UserRoundPlus size={18}/><span><strong>{en?'Manual entry':'Χειροκίνητη καταχώρηση'}</strong><small>{manualEntries.length} {en?'staged':'σε αναμονή'}</small></span></button>
   </div>
   <div className="training-participant-basket-summary"><strong>{en?'Ready to save':'Έτοιμοι για αποθήκευση'}: {total}</strong><span>{selected.length} {en?'from staff':'από προσωπικό'} · {manualEntries.length} {en?'manual':'χειροκίνητοι'}</span></div>
   <div className="training-participant-stage">
   {mode==='registry'&&<section className="training-participant-panel">
    <div className="training-participant-panel-heading"><div><span className="eyebrow">{en?'Employee registry':'Μητρώο εργαζομένων'}</span><h3>{en?'Select participants':'Επιλογή συμμετεχόντων'}</h3></div><span className="training-selection-count">{selected.length} {en?'selected':'επιλεγμένοι'}</span></div>
    {employees.length?<><div className="training-participant-filters"><label className="training-participant-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={en?'Search name, code, email...':'Αναζήτηση ονόματος, κωδικού, email...'}/></label><select value={department} onChange={e=>setDepartment(e.target.value)}><option value="all">{en?'All departments':'Όλα τα τμήματα'}</option>{departmentNames.map(name=><option key={name} value={name}>{name}</option>)}</select></div><div className="training-participant-list-head"><button type="button" disabled={!selectableVisible.length} onClick={toggleAll}>{allVisibleSelected?(en?'Clear available':'Αποεπιλογή διαθέσιμων'):(en?'Select available':'Επιλογή διαθέσιμων')}</button><span>{visible.length} {en?'results':'αποτελέσματα'} · {selectableVisible.length} {en?'available':'διαθέσιμοι'}</span></div><div className="scroll-table training-participant-table-wrap"><table className="data-table sticky-table training-participant-table"><thead><tr><th className="training-check-col"></th><th>{en?'Employee':'Εργαζόμενος'}</th><th>{en?'Code / status':'Κωδικός / κατάσταση'}</th><th>{en?'Department':'Τμήμα'}</th><th>Email</th></tr></thead><tbody>{visible.map(x=>{const key=String(x.id||x.employeeCode||''),alreadyAssigned=assignedSet.has(key),checked=!alreadyAssigned&&ids.includes(x.id);return <tr key={x.dbId||x.id} aria-disabled={alreadyAssigned?'true':undefined} className={checked?'training-row-selected':''} onClick={()=>{if(alreadyAssigned)return;setIds(s=>s.includes(x.id)?s.filter(v=>v!==x.id):[...s,x.id])}}><td className="training-check-col"><input type="checkbox" disabled={alreadyAssigned} checked={checked} onClick={e=>e.stopPropagation()} onChange={()=>{if(alreadyAssigned)return;setIds(s=>s.includes(x.id)?s.filter(v=>v!==x.id):[...s,x.id])}}/></td><td><strong>{`${x.firstName||''} ${x.lastName||''}`.trim()||'—'}</strong><small>{x.profession||'—'}</small></td><td>{alreadyAssigned?<span className="status-badge active">{en?'Already participating':'Ήδη συμμετέχει'}</span>:(x.id||x.employeeCode||'—')}</td><td>{x.department||'—'}</td><td>{x.email||'—'}</td></tr>})}</tbody></table>{visible.length===0&&<div className="registry-empty-state"><strong>{en?'No staff match the current filters.':'Δεν βρέθηκαν εργαζόμενοι με τα συγκεκριμένα φίλτρα.'}</strong></div>}</div></>:<div className="registry-empty-state"><Users size={24}/><strong>{en?'No staff records are available.':'Δεν υπάρχουν διαθέσιμες καρτέλες εργαζομένων.'}</strong><Button variant="secondary" onClick={()=>setMode('manual')}>{en?'Use manual entry':'Χειροκίνητη καταχώρηση'}</Button></div>}
   </section>}
   {mode==='manual'&&<section className="training-participant-panel training-participant-manual">
    <div className="training-participant-panel-heading"><div><span className="eyebrow">{en?'Manual entry':'Χειροκίνητη καταχώρηση'}</span><h3>{en?'Add participants':'Προσθήκη συμμετεχόντων'}</h3></div></div>
    <div className="training-manual-form-row"><label><span>{en?'Full name *':'Ονοματεπώνυμο *'}</span><input value={manualDraft.name} onChange={e=>setManualDraft(x=>({...x,name:e.target.value}))}/></label><label><span>{en?'Department / organization':'Τμήμα / φορέας'}</span><input list="training-manual-departments" value={manualDraft.department} onChange={e=>setManualDraft(x=>({...x,department:e.target.value}))}/><datalist id="training-manual-departments">{departments.map(x=><option key={x.id||x.name} value={x.name||x.label||''}/>)}</datalist></label><label><span>Email</span><input type="email" value={manualDraft.email} onChange={e=>setManualDraft(x=>({...x,email:e.target.value}))}/></label><div className="training-manual-add-cell"><Button type="button" variant="secondary" disabled={!manualDraft.name.trim()} onClick={addManual}><Plus size={15}/>{en?'Add to list':'Προσθήκη στη λίστα'}</Button></div></div>
    <div className="training-manual-list-slot">{manualEntries.length>0?<div className="scroll-table training-manual-table-wrap"><table className="data-table sticky-table"><thead><tr><th>{en?'Participant':'Συμμετέχων'}</th><th>{en?'Department / organization':'Τμήμα / φορέας'}</th><th>Email</th><th></th></tr></thead><tbody>{manualEntries.map(item=><tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.department||'—'}</td><td>{item.email||'—'}</td><td className="open-record-cell"><button type="button" className="lo-icon-button lo-icon-button-danger lo-icon-button-sm" onClick={()=>setManualEntries(rows=>rows.filter(x=>x.id!==item.id))} aria-label={en?'Remove':'Αφαίρεση'}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>:<div className="registry-empty-state"><UserRoundPlus size={24}/><strong>{en?'No manual participants yet.':'Δεν έχουν προστεθεί χειροκίνητοι συμμετέχοντες.'}</strong><span>{en?'Complete the fields above and add participants to the list.':'Συμπληρώστε τα πεδία και προσθέστε συμμετέχοντες στη λίστα.'}</span></div>}</div>
   </section>}
   </div>
  </section>
 </Page>
}
