import { useMemo, useState } from 'react'
import { Award, CheckCircle2, ClipboardCheck, FileText, ShieldCheck } from 'lucide-react'
import { useParams } from 'react-router-dom'
import { Button } from '../../design-system/Button'
import { findTrainingAccess, loadTrainingState, saveTrainingState, trainerFeedbackTemplate, validityUntil } from './trainingData'

export function TrainingAccessPage(){
 const {token}=useParams();const [state,setState]=useState(loadTrainingState);const access=useMemo(()=>findTrainingAccess(state,token),[state,token])
 const [employeeCode,setEmployeeCode]=useState('');const [assignmentId,setAssignmentId]=useState(null);const [message,setMessage]=useState('')
 const assignment=state.assignments.find(x=>x.id===assignmentId)
 function identify(e){e.preventDefault();if(!access)return;const code=employeeCode.trim().toUpperCase();const row=state.assignments.find(x=>x.programId===access.program.id&&String(x.employeeId).toUpperCase()===code);if(!row){setMessage('Ο κωδικός εργαζομένου δεν είναι στη λίστα συμμετεχόντων αυτής της εκπαίδευσης.');return}setAssignmentId(row.id);setMessage('')}
 function persist(next){setState(saveTrainingState(next))}
 if(!access)return <PublicFrame><Status title="Ο σύνδεσμος δεν είναι ενεργός" text="Το QR έχει λήξει ή αντικατασταθεί. Ζητήστε από τον εκπαιδευτή το τρέχον QR."/></PublicFrame>
 if(!assignment)return <PublicFrame><div className="public-flow-card"><span className="eyebrow">Limoxis Observer · Training</span><h1>{access.program.title}</h1><p>{access.mode==='checkin'?'Καταγραφή προσέλευσης':'Ολοκλήρωση εκπαίδευσης & αξιολόγηση'}</p><form onSubmit={identify} className="public-flow-form"><label className="field"><span>Κωδικός εργαζομένου</span><input className="input" value={employeeCode} onChange={e=>setEmployeeCode(e.target.value)} placeholder="π.χ. EMP-001" autoCapitalize="characters" autoComplete="off"/></label>{message&&<div className="form-error">{message}</div>}<Button type="submit" disabled={!employeeCode.trim()}>Συνέχεια</Button></form><div className="source-truth-note"><ShieldCheck size={16}/> Η ενέργεια συνδέεται με τον κωδικό εργαζομένου, τη συγκεκριμένη εκπαίδευση και το timestamp. Σε production η ταυτοποίηση θα γίνεται με authenticated identity/SSO.</div></div></PublicFrame>
 return access.mode==='checkin'?<CheckInFlow state={state} access={access} assignment={assignment} persist={persist}/>:<CompletionFlow state={state} access={access} assignment={assignment} persist={persist}/>
}

function CheckInFlow({state,access,assignment,persist}){const [done,setDone]=useState(Boolean(assignment.checkInAt));function confirm(){const now=new Date().toISOString();persist({...state,assignments:state.assignments.map(x=>x.id===assignment.id?{...x,attendance:true,attendanceResponse:'confirmed',checkInAt:x.checkInAt||now,status:x.status==='assigned'?'in_progress':x.status}:x),history:[{at:now,actor:assignment.employeeId,action:`QR check-in · ${access.program.title}`},...(state.history||[])]});setDone(true)}return <PublicFrame>{done?<Status title="Η παρουσία καταγράφηκε" text={`${assignment.employeeName} · ${access.program.title}`} icon={CheckCircle2}/>:<div className="public-flow-card"><span className="eyebrow">QR check-in</span><h1>{access.program.title}</h1><p><strong>{assignment.employeeName}</strong><br/>{assignment.department}</p><div className="source-truth-note">Με την επιβεβαίωση δηλώνετε ότι προσήλθατε στη συγκεκριμένη εκπαιδευτική δράση.</div><Button onClick={confirm}><CheckCircle2 size={16}/> Επιβεβαίωση παρουσίας</Button></div>}</PublicFrame>}

function CompletionFlow({state,access,assignment,persist}){
 const program=access.program;const [scores,setScores]=useState(()=>Object.fromEntries(trainerFeedbackTemplate.map(q=>[q.id,5])));const [comment,setComment]=useState('');const [answers,setAnswers]=useState({});const [confirmed,setConfirmed]=useState(false);const [done,setDone]=useState(Boolean(assignment.completionConfirmedAt));const questions=program.assessmentQuestions||[]
 function submit(e){e.preventDefault();if(!confirmed)return;const now=new Date().toISOString();let score=null,competent=true;if(program.requiresAssessment){const total=questions.reduce((a,q)=>a+Number(q.points||1),0);const earned=questions.reduce((a,q,i)=>a+(Number(answers[q.id]??-1)===Number(q.correctIndex)?Number(q.points||1):0),0);score=total?Math.round(earned/total*100):0;competent=score>=Number(program.passScore||0)}const feedbackResponse={employeeId:assignment.employeeId,submittedAt:now,scores,comment};const nextPrograms=state.programs.map(p=>p.id===program.id?{...p,feedbackResponses:[...(p.feedbackResponses||[]).filter(r=>r.employeeId!==assignment.employeeId),feedbackResponse]}:p);const nextAssignments=state.assignments.map(x=>x.id===assignment.id?{...x,attendance:true,attendanceResponse:'confirmed',checkInAt:x.checkInAt||now,completionConfirmedAt:now,feedbackSubmittedAt:now,assessmentSubmittedAt:program.requiresAssessment?now:null,status:'completed',completedDate:now.slice(0,10),score,competent}:x);const certExists=state.certificates.some(c=>c.assignmentId===assignment.id);const cert=competent&&!certExists?{id:`CERT-TR-${Date.now()}`,assignmentId:assignment.id,employeeId:assignment.employeeId,title:program.title,issuedDate:now.slice(0,10),validUntil:validityUntil(now.slice(0,10),program.validMonths),issuer:'Limoxis Observer · Demo Hospital'}:null;persist({...state,programs:nextPrograms,assignments:nextAssignments,certificates:cert?[cert,...state.certificates]:state.certificates,history:[{at:now,actor:assignment.employeeId,action:`QR ολοκλήρωση · ${program.title} · ${score==null?'χωρίς quiz':`${score}%`}`},...(state.history||[])]});setDone(true)}
 if(done){const latest=state.assignments.find(x=>x.id===assignment.id)||assignment;return <PublicFrame><Status title="Η διαδικασία ολοκληρώθηκε" text={latest.score==null?program.title:`Αποτέλεσμα αξιολόγησης: ${latest.score}% · ${latest.competent?'Επιτυχής':'Απαιτείται επανεκπαίδευση'}`} icon={latest.competent===false?ClipboardCheck:Award}/></PublicFrame>}
 return <PublicFrame><form className="public-flow-card public-flow-wide" onSubmit={submit}><span className="eyebrow">QR completion</span><h1>{program.title}</h1><p>{assignment.employeeName} · {assignment.department}</p>{(program.materials||[]).length>0&&<section className="public-flow-section"><h2><FileText size={17}/> Εκπαιδευτικό υλικό</h2>{program.materials.map(m=><div key={m.id} className="public-flow-row"><strong>{m.title}</strong><span>{m.type}</span></div>)}</section>}<section className="public-flow-section"><h2>Αξιολόγηση εκπαίδευσης</h2><p>Βαθμολογήστε από 1 έως 5. Η αξιολόγηση της εκπαίδευσης δεν επηρεάζει το αποτέλεσμα γνώσεων.</p>{trainerFeedbackTemplate.map(q=><label className="field" key={q.id}><span>{q.label}</span><select value={scores[q.id]} onChange={e=>setScores({...scores,[q.id]:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}</option>)}</select></label>)}<label className="field"><span>Σχόλιο (προαιρετικό)</span><textarea rows="3" value={comment} onChange={e=>setComment(e.target.value)}/></label></section>{program.requiresAssessment&&<section className="public-flow-section"><h2>Αξιολόγηση γνώσεων</h2><p>Απαιτούμενη επίδοση: {program.passScore}%</p>{questions.length?questions.map((q,i)=><fieldset key={q.id} className="public-flow-question"><legend>{i+1}. {q.text}</legend>{q.options.map((opt,idx)=><label key={idx} className="check-option"><input type="radio" name={q.id} checked={Number(answers[q.id])===idx} onChange={()=>setAnswers({...answers,[q.id]:idx})}/><span>{opt}</span></label>)}</fieldset>):<div className="setup-note">Δεν έχουν οριστεί ακόμη ερωτήσεις. Η ολοκλήρωση θα καταγραφεί με αποτέλεσμα 0% έως να προστεθεί quiz.</div>}</section>}<label className="check-option"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>Επιβεβαιώνω ότι παρακολούθησα την εκπαίδευση και υποβάλλω προσωπικά τις παραπάνω απαντήσεις.</span></label><Button type="submit" disabled={!confirmed||(program.requiresAssessment&&questions.some(q=>answers[q.id]===undefined))}>Υποβολή & ολοκλήρωση</Button></form></PublicFrame>
}

function PublicFrame({children}){return <main className="public-flow-page"><div className="public-flow-shell">{children}</div></main>}
function Status({title,text,icon:Icon=CheckCircle2}){return <div className="public-flow-card public-flow-status"><Icon size={34}/><h1>{title}</h1><p>{text}</p></div>}
