import { useEffect,useMemo,useState } from 'react'
import { ArrowDown,ArrowUp,CheckCircle2,ClipboardCheck,Pencil,Plus,Trash2 } from 'lucide-react'
import { Button } from '../../design-system/Button'
import { MetricCard } from '../../design-system/MetricCard'
import { ObserverDialog,DialogActions } from '../../design-system/ObserverDialog'
import { RegistryPagination } from '../../design-system/RegistryPagination'
import { TRAINING_ASSESSMENT_TYPES,addTrainingQuestionOption,createTrainingQuestion,normalizeTrainingQuestion,removeTrainingQuestionOption,trainingAssessmentMaxScore,trainingAssessmentTypeLabel,trainingQuestionIsValid } from './trainingAssessment'

export function TrainingAssessmentEditor({program,state,onPersist,busy=false,en=false,language='el'}){
 const questions=Array.isArray(program.assessmentQuestions)?program.assessmentQuestions:[],[dialog,setDialog]=useState(null),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(15)
 const scored=useMemo(()=>questions.filter(q=>TRAINING_ASSESSMENT_TYPES[q.type]?.scored).length,[questions]),maxScore=trainingAssessmentMaxScore(questions)
 const totalPages=Math.max(1,Math.ceil(questions.length/pageSize)),safePage=Math.min(page,totalPages),pagedQuestions=questions.slice((safePage-1)*pageSize,safePage*pageSize)
 useEffect(()=>{if(page>totalPages)setPage(totalPages)},[page,totalPages]);useEffect(()=>setPage(1),[pageSize])
 async function saveQuestions(next,message){const nextProgram={...program,assessmentQuestions:next,updatedAt:new Date().toISOString()};return onPersist({...state,programs:state.programs.map(x=>x.id===program.id?nextProgram:x)},message)}
 async function removeQuestion(question){await saveQuestions(questions.filter(x=>x.id!==question.id),en?'Question removed.':'Η ερώτηση αφαιρέθηκε.')}
 async function moveQuestion(index,direction){const target=index+direction;if(target<0||target>=questions.length)return;const next=[...questions];[next[index],next[target]]=[next[target],next[index]];await saveQuestions(next,en?'Question order updated.':'Η σειρά των ερωτήσεων ενημερώθηκε.')}
 return <div className="training-assessment-view workspace-column workspace-fill">
  <div className="section-toolbar"><div><span className="eyebrow">{en?'Assessment builder':'Δημιουργία αξιολόγησης'}</span><strong>{en?'Knowledge assessment':'Αξιολόγηση γνώσεων'}</strong></div><Button disabled={busy} onClick={()=>setDialog({mode:'new',question:createTrainingQuestion()})}><Plus size={15}/>{en?'Add question':'Νέα ερώτηση'}</Button></div>
  <div className="module-summary-strip"><MetricCard icon={ClipboardCheck} value={questions.length} label={en?'Questions':'Ερωτήσεις'}/><MetricCard icon={CheckCircle2} value={scored} label={en?'Auto-scored':'Αυτόματη βαθμολόγηση'}/><MetricCard icon={ClipboardCheck} value={maxScore||'—'} label={en?'Total points':'Σύνολο βαθμών'}/><MetricCard icon={CheckCircle2} value={program.requiresAssessment?`≥ ${program.passScore||0}%`:'—'} label={en?'Pass threshold':'Όριο επιτυχίας'}/></div>
  <section className="surface registry-workspace workspace-column workspace-fill training-assessment-registry">
   <div className="scroll-table"><table className="data-table sticky-table"><thead><tr><th>#</th><th>{en?'Question':'Ερώτηση'}</th><th>{en?'Type':'Τύπος'}</th><th>{en?'Points':'Βαθμοί'}</th><th>{en?'Required':'Υποχρεωτική'}</th><th>{en?'Correct answer / guidance':'Σωστή απάντηση / οδηγία'}</th><th></th></tr></thead><tbody>{pagedQuestions.map((raw,pageIndex)=>{const q=normalizeTrainingQuestion(raw),index=(safePage-1)*pageSize+pageIndex;let answer='—';if(q.type==='single_choice'||q.type==='multiple_choice')answer=q.options.filter(option=>option.correct).map(option=>option.text).filter(Boolean).join(', ')||'—';else if(q.type==='true_false')answer=q.correctBoolean?(en?'True':'Σωστό'):(en?'False':'Λάθος');else if(q.type==='free_text')answer=q.modelAnswer||(en?'Manual review':'Χειροκίνητος έλεγχος');return <tr key={q.id}><td><strong>{index+1}</strong></td><td><strong>{q.text||'—'}</strong></td><td>{trainingAssessmentTypeLabel(q.type,language)}</td><td>{q.points}</td><td>{q.required?(en?'Yes':'Ναι'):(en?'No':'Όχι')}</td><td>{answer}</td><td className="open-record-cell"><div className="record-actions"><button className="lo-icon-button lo-icon-button-sm" type="button" disabled={index===0||busy} onClick={()=>moveQuestion(index,-1)} aria-label={en?'Move up':'Μετακίνηση πάνω'}><ArrowUp size={14}/></button><button className="lo-icon-button lo-icon-button-sm" type="button" disabled={index===questions.length-1||busy} onClick={()=>moveQuestion(index,1)} aria-label={en?'Move down':'Μετακίνηση κάτω'}><ArrowDown size={14}/></button><button className="lo-icon-button lo-icon-button-edit lo-icon-button-sm" type="button" disabled={busy} onClick={()=>setDialog({mode:'edit',question:q})} aria-label={en?'Edit':'Επεξεργασία'}><Pencil size={14}/></button><button className="lo-icon-button lo-icon-button-danger lo-icon-button-sm" type="button" disabled={busy} onClick={()=>removeQuestion(q)} aria-label={en?'Delete':'Διαγραφή'}><Trash2 size={14}/></button></div></td></tr>})}</tbody></table>{!questions.length&&<div className="registry-empty-state"><strong>{en?'No assessment questions yet.':'Δεν υπάρχουν ακόμη ερωτήσεις αξιολόγησης.'}</strong><span>{en?'Add the first question to build the assessment.':'Προσθέστε την πρώτη ερώτηση για να δημιουργηθεί η αξιολόγηση.'}</span></div>}</div>
   <RegistryPagination language={language} page={safePage} totalPages={totalPages} totalItems={questions.length} pageSize={pageSize} onPageChange={setPage} onPageSizeChange={setPageSize}/>
  </section>
  {dialog&&<TrainingQuestionDialog en={en} language={language} value={dialog.question} mode={dialog.mode} busy={busy} onClose={()=>setDialog(null)} onSave={async question=>{const normalized=normalizeTrainingQuestion(question),next=dialog.mode==='edit'?questions.map(x=>x.id===normalized.id?normalized:x):[...questions,normalized];if(await saveQuestions(next,en?'Assessment saved.':'Η αξιολόγηση αποθηκεύτηκε.'))setDialog(null)}}/>}
 </div>
}

function TrainingQuestionDialog({en,language,value,mode,busy,onClose,onSave}){
 const [question,setQuestion]=useState(()=>normalizeTrainingQuestion(value));useEffect(()=>setQuestion(normalizeTrainingQuestion(value)),[value])
 const valid=trainingQuestionIsValid(question),choiceType=question.type==='single_choice'||question.type==='multiple_choice'
 function changeType(type){const fresh=createTrainingQuestion(type);setQuestion({...fresh,id:question.id,text:question.text,points:question.points,required:question.required})}
 function updateOption(id,patch){setQuestion(q=>({...q,options:q.options.map(option=>option.id===id?{...option,...patch}:q.type==='single_choice'&&patch.correct?{...option,correct:false}:option)}))}
 return <ObserverDialog width="wide" title={mode==='edit'?(en?'Edit question':'Επεξεργασία ερώτησης'):(en?'New question':'Νέα ερώτηση')} onClose={onClose} footer={<DialogActions onCancel={onClose} disabled={busy||!valid} onSave={()=>onSave(question)}/>}><div className="training-question-dialog"><div className="entry-grid"><label className="entry-span-2"><span>{en?'Question *':'Ερώτηση *'}</span><textarea rows="3" autoFocus value={question.text} onChange={e=>setQuestion(q=>({...q,text:e.target.value}))}/></label><label><span>{en?'Type':'Τύπος'}</span><select value={question.type} onChange={e=>changeType(e.target.value)}>{Object.keys(TRAINING_ASSESSMENT_TYPES).map(type=><option key={type} value={type}>{trainingAssessmentTypeLabel(type,language)}</option>)}</select></label><label><span>{en?'Points':'Βαθμοί'}</span><input type="number" min="0" step="1" value={question.points} onChange={e=>setQuestion(q=>({...q,points:e.target.value}))}/></label><label className="check-option"><input type="checkbox" checked={question.required!==false} onChange={e=>setQuestion(q=>({...q,required:e.target.checked}))}/><span>{en?'Required question':'Υποχρεωτική ερώτηση'}</span></label></div>
  {choiceType&&<div className="training-question-options-editor"><div className="training-question-options-title"><strong>{en?'Answer options':'Επιλογές απάντησης'}</strong><Button variant="secondary" type="button" onClick={()=>setQuestion(addTrainingQuestionOption(question))}><Plus size={14}/>{en?'Option':'Επιλογή'}</Button></div>{question.options.map((option,index)=><div key={option.id} className="training-question-option-row"><input type={question.type==='single_choice'?'radio':'checkbox'} name="correct-answer" checked={option.correct} onChange={e=>updateOption(option.id,{correct:e.target.checked})} aria-label={en?'Correct answer':'Σωστή απάντηση'}/><input value={option.text} onChange={e=>updateOption(option.id,{text:e.target.value})} placeholder={`${en?'Option':'Επιλογή'} ${index+1}`}/><button type="button" className="lo-icon-button lo-icon-button-danger lo-icon-button-sm" disabled={question.options.length<=2} onClick={()=>setQuestion(removeTrainingQuestionOption(question,option.id))}><Trash2 size={14}/></button></div>)}</div>}
  {question.type==='true_false'&&<div className="training-true-false"><span>{en?'Correct answer':'Σωστή απάντηση'}</span><label><input type="radio" checked={question.correctBoolean===true} onChange={()=>setQuestion(q=>({...q,correctBoolean:true}))}/>{en?'True':'Σωστό'}</label><label><input type="radio" checked={question.correctBoolean===false} onChange={()=>setQuestion(q=>({...q,correctBoolean:false}))}/>{en?'False':'Λάθος'}</label></div>}
  {question.type==='free_text'&&<div className="entry-grid"><label className="entry-span-2"><span>{en?'Model answer / reviewer guidance':'Ενδεικτική απάντηση / οδηγία αξιολογητή'}</span><textarea rows="3" value={question.modelAnswer||''} onChange={e=>setQuestion(q=>({...q,modelAnswer:e.target.value,manualReview:true}))}/></label><div className="source-truth-note entry-span-2">{en?'This question requires manual review and does not contribute to automatic scoring.':'Η ερώτηση απαιτεί χειροκίνητη αξιολόγηση και δεν προσμετράται στην αυτόματη βαθμολογία.'}</div></div>}
 </div></ObserverDialog>
}
