import { useCallback,useEffect,useMemo,useState } from 'react'
import { useNavigate,useParams } from 'react-router-dom'
import { Award,BookOpenCheck,CalendarClock,CheckCircle2,ClipboardCheck,Clock3,FileText,Mail,Plus,RefreshCw,Send,Star,Users } from 'lucide-react'
import { Page } from '../../design-system/Page'
import { EntityRecordShell } from '../../design-system/EntityRecordShell'
import { Button } from '../../design-system/Button'
import { ObserverDialog,DialogActions } from '../../design-system/ObserverDialog'
import { ManualDateField } from '../../design-system/ManualDateField'
import { FilterBar,FilterSelect } from '../../design-system/FilterBar'
import { MetricCard } from '../../design-system/MetricCard'
import { PrintExportActions } from '../../design-system/PrintExportActions'
import { RecordActions } from '../../design-system/RecordActions'
import { RouteLoading } from '../../design-system/RouteLoading'
import { UI_ACTIONS } from '../../core/actions/actionPolicy'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useTenant } from '../../core/tenant/TenantContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { useEmployeesData } from '../employees/useEmployeesData'
import { CAPABILITIES,ROLES,can } from '../../core/permissions/roles'
import { computedAssignmentStatus } from './trainingData'
import { deleteTrainingRecordAsync,loadTrainingStateAsync,saveManagedTrainingStateAsync } from './trainingService'
import { processTrainingOutboxAsync,queueTrainingInvitationAsync } from './trainingInvitationService'

const fmt=v=>v?new Date(`${String(v).slice(0,10)}T12:00:00`).toLocaleDateString('el-GR'):'—'
const labels={active:['Ενεργό','Active'],planned:['Προγραμματισμένο','Planned'],completed:['Ολοκληρωμένο','Completed'],assigned:['Ανατέθηκε','Assigned'],in_progress:['Σε εξέλιξη','In progress'],overdue:['Εκπρόθεσμο','Overdue'],cancelled:['Ακυρώθηκε','Cancelled']}
const blankState={programs:[],assignments:[],certificates:[],emailOutbox:[],history:[]}

export function TrainingProductionPage(){
 const {programId}=useParams(),navigate=useNavigate(),{language}=useLanguage(),en=language==='en', {tenant,role,membership}=useTenant(),{notify,notifyError,confirm}=useFeedback(),{data:employees}=useEmployeesData()
 const [state,setState]=useState(blankState),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[dialog,setDialog]=useState(null),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[category,setCategory]=useState('all')
 const canManage=can(role,CAPABILITIES.MANAGE_TRAINING,membership?.capabilities??[],membership?.customCapabilities??[]),managerView=role===ROLES.DEPARTMENT_MANAGER&&!canManage,employeeView=!canManage&&!managerView
 const reload=useCallback(async()=>{if(!tenant?.id)return;setLoading(true);try{setState(await loadTrainingStateAsync(tenant.id))}catch(error){notifyError(error,'load',{operation:'training_load'})}finally{setLoading(false)}},[tenant?.id,notifyError])
 useEffect(()=>{void reload()},[reload])
 async function persist(next,success){if(!canManage)return false;setBusy(true);try{const saved=await saveManagedTrainingStateAsync(tenant.id,next);setState(saved);if(success)notify(success,'success');return true}catch(error){notifyError(error,'save',{operation:'training_save'});return false}finally{setBusy(false)}}
 const assignments=useMemo(()=>state.assignments.map(x=>({...x,computedStatus:computedAssignmentStatus(x)})),[state.assignments]),programs=state.programs.filter(x=>(status==='all'||x.status===status)&&(category==='all'||x.category===category)&&`${x.id} ${x.title} ${x.owner} ${x.trainer} ${x.audience}`.toLowerCase().includes(query.toLowerCase())),categories=[...new Set(state.programs.map(x=>x.category).filter(Boolean))]
 const selected=state.programs.find(x=>x.id===programId),selectedAssignments=selected?assignments.filter(x=>x.programId===selected.id):[]
 const completed=assignments.filter(x=>x.computedStatus==='completed').length,overdue=assignments.filter(x=>x.computedStatus==='overdue').length,dueSoon=assignments.filter(x=>['assigned','in_progress'].includes(x.computedStatus)&&x.dueDate&&daysUntil(x.dueDate)>=0&&daysUntil(x.dueDate)<=14).length,completionRate=assignments.length?Math.round(completed/assignments.length*100):0
 if(loading)return <RouteLoading/>
 if(selected&&canManage)return <ProgramRecord en={en} language={language} organizationId={tenant.id} program={selected} assignments={selectedAssignments} state={state} employees={employees} busy={busy} notify={notify} notifyError={notifyError} reload={reload} onBack={()=>navigate('/training')} onPersist={persist} onDelete={async()=>{if(selectedAssignments.length){notify(en?'The program has participants and cannot be deleted.':'Το πρόγραμμα έχει συμμετέχοντες και δεν μπορεί να διαγραφεί.','warning');return}if(!await confirm({title:en?'Delete program':'Διαγραφή προγράμματος',message:en?'Delete this training program?':'Να διαγραφεί το πρόγραμμα εκπαίδευσης;',danger:true}))return;await deleteTrainingRecordAsync(tenant.id,selected.id);navigate('/training');await reload()}}/>
 function exportCsv(){const text=[[(en?'Program':'Πρόγραμμα'),(en?'Trainer':'Εκπαιδευτής'),(en?'Audience':'Κοινό'),(en?'Start':'Έναρξη'),(en?'Due':'Προθεσμία'),(en?'Status':'Κατάσταση')],...programs.map(x=>[x.title,x.trainer||x.owner||'',x.audience||'',x.startDate||'',x.dueDate||'',x.status||''])].map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv'}));a.download='training-programs.csv';a.click();URL.revokeObjectURL(a.href)}
 function pageAction(action){if(action===UI_ACTIONS.CREATE){setDialog({type:'program'});return}if(action===UI_ACTIONS.PRINT){window.print();return}if(action===UI_ACTIONS.EXPORT){exportCsv()}}
 return <Page fill title={en?'Training':'Εκπαίδευση'} subtitle={employeeView?(en?'Your assigned training and completion evidence.':'Οι ανατεθειμένες εκπαιδεύσεις και τα τεκμήρια ολοκλήρωσής σας.'):(en?'Training programs, participation and competency monitoring.':'Προγράμματα εκπαίδευσης, συμμετοχές και παρακολούθηση επάρκειας.')}
  actions={<RecordActions actions={[...(canManage?[UI_ACTIONS.CREATE]:[]),UI_ACTIONS.PRINT,UI_ACTIONS.EXPORT]} resourceCapability={CAPABILITIES.VIEW_TRAINING} actionCapabilities={{[UI_ACTIONS.CREATE]:CAPABILITIES.MANAGE_TRAINING,[UI_ACTIONS.PRINT]:CAPABILITIES.PRINT_RECORDS,[UI_ACTIONS.EXPORT]:CAPABILITIES.EXPORT_RECORDS}} onAction={pageAction}/>}
 >
  <div className="module-summary-strip">{employeeView?<><MetricCard icon={BookOpenCheck} value={assignments.filter(x=>x.computedStatus!=='completed').length} label={en?'Assigned':'Ανατεθειμένες'}/><MetricCard icon={CheckCircle2} value={completed} label={en?'Completed':'Ολοκληρωμένες'}/><MetricCard icon={Award} value={state.certificates.length} label={en?'Certificates':'Πιστοποιητικά'}/></>:<><MetricCard icon={Users} value={assignments.length} label={en?'Assignments':'Αναθέσεις'}/><MetricCard icon={CheckCircle2} value={`${completionRate}%`} label={en?'Completion':'Ολοκλήρωση'}/><MetricCard icon={CalendarClock} value={dueSoon} label={en?'Due soon':'Λήγουν σύντομα'}/><MetricCard icon={Clock3} value={overdue} label={en?'Overdue':'Εκπρόθεσμες'}/></>}</div>
  <section className="surface registry-workspace training-registry workspace-column workspace-fill">{canManage?<><FilterBar query={query} onQueryChange={setQuery} placeholder={en?'Search training program...':'Αναζήτηση προγράμματος εκπαίδευσης...'} activeAdvancedCount={(status==='all'?0:1)+(category==='all'?0:1)} onClear={()=>{setQuery('');setStatus('all');setCategory('all')}}><FilterSelect label={en?'Status':'Κατάσταση'} value={status} onChange={setStatus}><option value="all">{en?'All':'Όλα'}</option><option value="active">{en?'Active':'Ενεργά'}</option><option value="planned">{en?'Planned':'Προγραμματισμένα'}</option><option value="completed">{en?'Completed':'Ολοκληρωμένα'}</option></FilterSelect><FilterSelect label={en?'Category':'Κατηγορία'} value={category} onChange={setCategory}><option value="all">{en?'All':'Όλες'}</option>{categories.map(x=><option key={x}>{x}</option>)}</FilterSelect></FilterBar><Programs rows={programs} en={en} onOpen={id=>navigate(`/training/${id}`)}/></>:<Assignments rows={assignments} state={state} en={en} employeeView={employeeView}/>}</section>
  {dialog?.type==='program'&&<ProgramDialog en={en} busy={busy} onClose={()=>setDialog(null)} onSave={async program=>{const now=new Date().toISOString();if(await persist({...state,programs:[{...program,id:`TRN-${Date.now()}`,status:'active',materials:[],assessmentQuestions:[],feedbackResponses:[],createdAt:now},...state.programs]},en?'Training program created.':'Το πρόγραμμα εκπαίδευσης δημιουργήθηκε.'))setDialog(null)}}/>}
 </Page>
}

function ProgramRecord({en,language,organizationId,program,assignments,state,employees,busy,notify,notifyError,reload,onBack,onPersist,onDelete}){
 const [tab,setTab]=useState('overview'),[dialog,setDialog]=useState(null),[mailBusy,setMailBusy]=useState('')
 const tabs=[{id:'overview',label:en?'Overview':'Σύνοψη',icon:CheckCircle2},{id:'participants',label:en?'Participants':'Συμμετέχοντες',icon:Users},{id:'materials',label:en?'Material':'Υλικό',icon:FileText},{id:'assessment',label:en?'Assessment':'Αξιολόγηση',icon:ClipboardCheck},{id:'results',label:en?'Results':'Αποτελέσματα',icon:Award}]
 async function sendInvitation(row){setMailBusy(row.id);try{await queueTrainingInvitationAsync(row.id,language);await processTrainingOutboxAsync(organizationId);notify(en?'Invitation email sent.':'Το email πρόσκλησης στάλθηκε.','success');await reload()}catch(error){notifyError(error,'send',{operation:'training_invitation_send'})}finally{setMailBusy('')}}
 return <Page fill><EntityRecordShell className="workspace-fill" avatar={<BookOpenCheck size={19}/>} eyebrow={program.id} title={program.title} subtitle={`${program.category||''} · ${program.method||''} · ${en?'Trainer':'Εκπαιδευτής'}: ${program.trainer||program.owner||'—'}`} status={<Badge status={program.status}/>} headerActions={<PrintExportActions onExport={()=>downloadJson({program,assignments},program.id)}/>} tabs={tabs} activeTab={tab} onTabChange={setTab} onBack={onBack} backLabel={en?'Back to programs':'Πίσω στα προγράμματα'}>
 <div className="workspace-column workspace-fill">{tab==='overview'&&<Overview program={program} assignments={assignments} en={en} onDelete={onDelete}/>} {tab==='participants'&&<Participants rows={assignments} en={en} busy={busy} mailBusy={mailBusy} onInvite={sendInvitation} onAdd={()=>setDialog({type:'participants'})}/>} {tab==='materials'&&<EmbeddedList title={en?'Training material':'Εκπαιδευτικό υλικό'} rows={program.materials||[]} empty={en?'No material yet.':'Δεν έχει προστεθεί υλικό.'}/>} {tab==='assessment'&&<Questions program={program} en={en}/>} {tab==='results'&&<Results rows={assignments} en={en}/>}</div>
 {dialog?.type==='participants'&&<ParticipantsDialog en={en} employees={employees.filter(e=>e.employmentStatus==='active'&&!assignments.some(a=>a.employeeId===e.id))} busy={busy} onClose={()=>setDialog(null)} onSave={async selected=>{const now=new Date().toISOString(),next=selected.map(e=>({id:`TRA-${Date.now()}-${e.id}`,programId:program.id,employeeId:e.id,employeeName:`${e.firstName} ${e.lastName}`,department:e.department,email:e.email,assignedDate:now.slice(0,10),dueDate:program.dueDate,status:'assigned',attendanceResponse:'not_sent',attendance:null,completionConfirmedAt:null,score:null,competent:null,certificateId:null,createdAt:now}));if(await onPersist({...state,assignments:[...state.assignments,...next]},en?'Participants added.':'Οι συμμετέχοντες προστέθηκαν.'))setDialog(null)}}/>}
 </EntityRecordShell></Page>
}

function Participants({rows,en,onAdd,busy,mailBusy,onInvite}){const sent=rows.filter(x=>x.invitationSentAt).length,confirmed=rows.filter(x=>x.attendanceResponse==='confirmed').length,completed=rows.filter(x=>x.status==='completed').length;return <div className="workspace-column workspace-fill"><div className="module-summary-strip"><MetricCard icon={Mail} value={`${sent}/${rows.length}`} label={en?'Invitations':'Προσκλήσεις'}/><MetricCard icon={CheckCircle2} value={`${confirmed}/${rows.length}`} label={en?'Attendance':'Παρουσία'}/><MetricCard icon={ClipboardCheck} value={`${completed}/${rows.length}`} label={en?'Completed':'Ολοκλήρωση'}/></div><div className="section-toolbar"><div><strong>{en?'Participants & email workflow':'Συμμετέχοντες & ροή email'}</strong><small>{en?'Each participant receives a personal secure link. Opening the email does not record attendance; explicit confirmation is required.':'Κάθε συμμετέχων λαμβάνει προσωπικό ασφαλή σύνδεσμο. Το άνοιγμα του email δεν καταγράφει παρουσία· απαιτείται ρητή επιβεβαίωση.'}</small></div><Button disabled={busy} onClick={onAdd}><Plus size={15}/> {en?'Add participants':'Προσθήκη συμμετεχόντων'}</Button></div><div className="scroll-table"><table className="data-table sticky-table"><thead><tr><th>{en?'Participant':'Συμμετέχων'}</th><th>{en?'Department':'Τμήμα'}</th><th>Email</th><th>{en?'Invitation':'Πρόσκληση'}</th><th>{en?'Attendance':'Παρουσία'}</th><th>{en?'Evaluation':'Αξιολόγηση'}</th><th></th></tr></thead><tbody>{rows.map(x=>{const linked=Boolean(x.userId||x.accountLinked),sent=Boolean(x.invitationSentAt),done=x.status==='completed';return <tr key={x.id}><td><strong>{x.employeeName||'—'}</strong><small>{x.employeeId}</small></td><td>{x.department||'—'}</td><td>{x.email||'—'}<small>{linked?(en?'Account linked':'Συνδεδεμένος λογαριασμός'):(en?'No account linked':'Χωρίς συνδεδεμένο λογαριασμό')}</small></td><td>{sent?<><span className="status-badge active">{en?'Sent':'Στάλθηκε'}</span><small>{fmt(x.invitationSentAt)}</small></>:<span className="status-badge">{en?'Not sent':'Δεν στάλθηκε'}</span>}</td><td>{x.attendanceResponse==='confirmed'?<span className="status-badge active">{en?'Confirmed':'Επιβεβαιώθηκε'}</span>:<span className="status-badge">{en?'Pending':'Εκκρεμεί'}</span>}</td><td>{done?<span className="status-badge active">{x.score!=null?`${x.score}%`:(en?'Completed':'Ολοκληρώθηκε')}</span>:<span className="status-badge">{en?'Pending':'Εκκρεμεί'}</span>}</td><td className="open-record-cell"><Button variant="secondary" disabled={!linked||!x.email||mailBusy===x.id||done} onClick={()=>onInvite(x)}>{sent?<RefreshCw size={14}/>:<Send size={14}/>} {sent?(en?'Resend':'Επαναποστολή'):(en?'Send':'Αποστολή')}</Button></td></tr>})}</tbody></table></div></div>}
function Programs({rows,en,onOpen}){return <div className="scroll-table"><table className="data-table sticky-table"><thead><tr><th>{en?'Program':'Πρόγραμμα'}</th><th>{en?'Trainer':'Εκπαιδευτής'}</th><th>{en?'Audience':'Κοινό'}</th><th>{en?'Period':'Περίοδος'}</th><th>{en?'Assessment':'Αξιολόγηση'}</th><th>{en?'Status':'Κατάσταση'}</th></tr></thead><tbody>{rows.map(x=><tr key={x.id} className="clickable-row" tabIndex={0} onClick={()=>onOpen(x.id)} onKeyDown={e=>e.key==='Enter'&&onOpen(x.id)}><td><strong>{x.title}</strong><small>{x.category} · {x.method}</small></td><td>{x.trainer||x.owner||'—'}</td><td>{x.audience||'—'}</td><td>{fmt(x.startDate)} → {fmt(x.dueDate)}</td><td>{x.requiresAssessment?`≥ ${x.passScore}%`:(en?'Not required':'Δεν απαιτείται')}</td><td><Badge status={x.status}/></td></tr>)}</tbody></table></div>}
function Assignments({rows,state,en,employeeView=false}){return <div className="scroll-table"><table className="data-table sticky-table"><thead><tr>{!employeeView&&<><th>{en?'Employee':'Εργαζόμενος'}</th><th>{en?'Department':'Τμήμα'}</th></>}<th>{en?'Training':'Εκπαίδευση'}</th><th>{en?'Due':'Προθεσμία'}</th><th>{en?'Result':'Αποτέλεσμα'}</th><th>{en?'Status':'Κατάσταση'}</th></tr></thead><tbody>{rows.map(x=>{const p=state.programs.find(v=>v.id===x.programId);return <tr key={x.id}>{!employeeView&&<><td><strong>{x.employeeName||'—'}</strong></td><td>{x.department||'—'}</td></>}<td><strong>{p?.title||x.programId}</strong></td><td>{fmt(x.dueDate)}</td><td>{x.score!=null?`${x.score}%`:x.status==='completed'?(en?'Completed':'Ολοκληρώθηκε'):'—'}</td><td><Badge status={x.computedStatus}/></td></tr>})}</tbody></table></div>}
function Overview({program,assignments,en,onDelete}){return <section className="record-section"><div className="record-section-header"><div><span className="eyebrow">{en?'Training program':'Πρόγραμμα εκπαίδευσης'}</span><h3>{en?'Basic details':'Βασικά στοιχεία'}</h3><p>{program.description||'—'}</p></div></div><div className="details-grid"><div><span>{en?'Category':'Κατηγορία'}</span><strong>{program.category||'—'}</strong></div><div><span>{en?'Method':'Τρόπος'}</span><strong>{program.method||'—'}</strong></div><div><span>{en?'Trainer':'Εκπαιδευτής'}</span><strong>{program.trainer||'—'}</strong></div><div><span>{en?'Due':'Προθεσμία'}</span><strong>{fmt(program.dueDate)}</strong></div><div><span>{en?'Participants':'Συμμετέχοντες'}</span><strong>{assignments.length}</strong></div><div><span>{en?'Assessment':'Αξιολόγηση'}</span><strong>{program.requiresAssessment?`≥ ${program.passScore}%`:(en?'Not required':'Δεν απαιτείται')}</strong></div></div><Button variant="secondary" onClick={onDelete}>{en?'Delete program':'Διαγραφή προγράμματος'}</Button></section>}
function EmbeddedList({title,rows,empty}){return <section className="record-section"><div className="record-section-header"><h3>{title}</h3></div>{rows.length?<div className="scroll-table"><table className="data-table"><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.title}</strong></td><td>{x.type||'—'}</td></tr>)}</tbody></table></div>:<div className="inline-empty">{empty}</div>}</section>}
function Questions({program,en}){const rows=program.assessmentQuestions||[];return <section className="record-section"><div className="record-section-header"><div><h3>{en?'Knowledge assessment':'Αξιολόγηση γνώσεων'}</h3><p>{en?'Questions are configured by the trainer and scored on the server.':'Οι ερωτήσεις ορίζονται από τον εκπαιδευτή και βαθμολογούνται στον server.'}</p></div></div><div className="scroll-table"><table className="data-table"><thead><tr><th>#</th><th>{en?'Question':'Ερώτηση'}</th><th>{en?'Points':'Βαθμοί'}</th></tr></thead><tbody>{rows.map((q,i)=><tr key={q.id}><td>{i+1}</td><td><strong>{q.text}</strong></td><td>{q.points||1}</td></tr>)}</tbody></table></div></section>}
function Results({rows,en}){const completed=rows.filter(x=>x.status==='completed').length,scored=rows.filter(x=>x.score!=null),avg=scored.length?Math.round(scored.reduce((a,b)=>a+Number(b.score||0),0)/scored.length):0;return <div className="module-summary-strip"><MetricCard icon={CheckCircle2} value={completed} label={en?'Completed':'Ολοκληρώσεις'}/><MetricCard icon={ClipboardCheck} value={scored.length?`${avg}%`:'—'} label={en?'Average score':'Μέση επίδοση'}/><MetricCard icon={Star} value={rows.filter(x=>x.competent===true).length} label={en?'Competent':'Επαρκείς'}/></div>}
function ProgramDialog({initial,onClose,onSave,busy,en}){const [v,setV]=useState(initial||{title:'',category:'IPC',method:'Δια ζώσης',owner:'',trainer:'',audience:'',startDate:'',dueDate:'',validMonths:'12',requiresAssessment:true,passScore:'80',description:''});const set=(k,x)=>setV(s=>({...s,[k]:x}));return <ObserverDialog width="wide" title={initial?(en?'Edit program':'Επεξεργασία προγράμματος'):(en?'New training program':'Νέο πρόγραμμα εκπαίδευσης')} onClose={onClose} footer={<DialogActions onCancel={onClose} disabled={busy||!v.title||!v.owner||!v.trainer||!v.audience||!v.dueDate} onSave={()=>onSave({...v,validMonths:Number(v.validMonths)||null,passScore:v.requiresAssessment?Number(v.passScore)||0:null})}/>}><div className="entry-grid compact"><label className="field"><span>{en?'Title':'Τίτλος'} *</span><input value={v.title} onChange={e=>set('title',e.target.value)}/></label><label className="field"><span>{en?'Category':'Κατηγορία'}</span><input value={v.category} onChange={e=>set('category',e.target.value)}/></label><label className="field"><span>{en?'Method':'Τρόπος'}</span><input value={v.method} onChange={e=>set('method',e.target.value)}/></label><label className="field"><span>{en?'Owner':'Υπεύθυνος'} *</span><input value={v.owner} onChange={e=>set('owner',e.target.value)}/></label><label className="field"><span>{en?'Trainer':'Εκπαιδευτής'} *</span><input value={v.trainer} onChange={e=>set('trainer',e.target.value)}/></label><label className="field"><span>{en?'Audience':'Κοινό'} *</span><input value={v.audience} onChange={e=>set('audience',e.target.value)}/></label><ManualDateField className="field" label={en?'Start':'Έναρξη'} value={v.startDate} onChange={x=>set('startDate',x)} optional/><ManualDateField className="field" label={en?'Due date':'Προθεσμία'} value={v.dueDate} onChange={x=>set('dueDate',x)}/><label className="check-option"><input type="checkbox" checked={v.requiresAssessment} onChange={e=>set('requiresAssessment',e.target.checked)}/><span>{en?'Knowledge assessment required':'Απαιτείται αξιολόγηση γνώσεων'}</span></label>{v.requiresAssessment&&<label className="field"><span>{en?'Pass score':'Όριο επιτυχίας'}</span><input type="number" min="0" max="100" value={v.passScore} onChange={e=>set('passScore',e.target.value)}/></label>}<label className="field entry-span-2"><span>{en?'Description':'Περιγραφή'}</span><textarea rows="3" value={v.description} onChange={e=>set('description',e.target.value)}/></label></div></ObserverDialog>}
function ParticipantsDialog({employees,onClose,onSave,busy,en}){const [ids,setIds]=useState([]);return <ObserverDialog width="wide" title={en?'Add participants':'Προσθήκη συμμετεχόντων'} onClose={onClose} footer={<DialogActions onCancel={onClose} disabled={busy||!ids.length} onSave={()=>onSave(employees.filter(x=>ids.includes(x.id)))}/>}><div className="scroll-table"><table className="data-table"><thead><tr><th></th><th>{en?'Employee':'Εργαζόμενος'}</th><th>{en?'Department':'Τμήμα'}</th><th>Email</th></tr></thead><tbody>{employees.map(x=><tr key={x.id}><td><input type="checkbox" checked={ids.includes(x.id)} onChange={()=>setIds(s=>s.includes(x.id)?s.filter(v=>v!==x.id):[...s,x.id])}/></td><td><strong>{x.firstName} {x.lastName}</strong></td><td>{x.department||'—'}</td><td>{x.email||'—'}</td></tr>)}</tbody></table></div></ObserverDialog>}
function Badge({status}){const {language}=useLanguage();const en=language==='en';return <span className={`status-badge ${status==='active'||status==='completed'?'active':''} ${status==='overdue'||status==='cancelled'?'danger':''}`.trim()}>{labels[status]?.[en?1:0]||status||'—'}</span>}
function daysUntil(iso){return Math.ceil((new Date(`${iso}T12:00:00`)-new Date())/86400000)}
function downloadJson(value,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.download=`${name}.json`;a.click();URL.revokeObjectURL(a.href)}