// Guided-tour stops per Demo scenario (see demoScenarios.js and demoTours.js).
// Each stop: { step, target: { sel, text?: [el, en] }, titleEl, titleEn, textEl, textEn, advance? }
// `text` picks, among the elements matching `sel`, the first whose visible text
// (or aria-label) contains it in the current language. `advance: 'click'`
// moves on when the user clicks the target; without it the stop shows "Next".
// Walked stop by stop on the sample Demo, in Greek and English.
export const DEMO_TOUR_STOPS = Object.freeze({
  patient_admission: [
    { step: null, target: { sel: 'main button.lo-action-button', text: ['Δημιουργία', 'Create'] },
      titleEl: 'Νέος ασθενής', titleEn: 'New patient',
      textEl: 'Πατήστε «Δημιουργία» για να καταχωρίσετε νέο ασθενή στο μητρώο.',
      textEn: 'Press "Create" to add a new patient to the registry.', advance: 'click' },
    { step: null, target: { sel: '[role=dialog] label', text: ['Τμήμα', 'Department'] },
      titleEl: 'Στοιχεία και τμήμα εισαγωγής', titleEn: 'Details and admitting department',
      textEl: 'Συμπληρώστε κωδικό, όνομα, επώνυμο και ημερομηνία εισαγωγής και επιλέξτε το τμήμα εισαγωγής.',
      textEn: 'Fill in the code, first and last name and admission date, and choose the admitting department.' },
    { step: null, target: { sel: '[role=dialog] button.button-primary', text: ['Αποθήκευση', 'Save'] },
      titleEl: 'Αποθήκευση', titleEn: 'Save',
      textEl: 'Πατήστε «Αποθήκευση»· ανοίγει αμέσως η ενιαία κλινική καρτέλα του ασθενούς.',
      textEn: 'Press "Save"; the patient\'s clinical record opens straight away.', advance: 'click' },
  ],

  clabsi_classification: [
    { step: 'open', target: { sel: 'tbody tr.registry-row-clickable', text: ['ΜΕΘ', 'ICU'] },
      titleEl: 'Ασθενής της ΜΕΘ', titleEn: 'An ICU patient',
      textEl: 'Πατήστε έναν ασθενή της ΜΕΘ με ενεργή επιτήρηση για να ανοίξετε την καρτέλα του.',
      textEn: 'Press an ICU patient with active surveillance to open their record.', advance: 'click' },
    { step: 'hai', target: { sel: '[role=tab]', text: ['Επιτήρηση & Δείγματα', 'Surveillance & Samples'] },
      titleEl: 'Επιτήρηση & Δείγματα', titleEn: 'Surveillance & Samples',
      textEl: 'Πατήστε την καρτέλα «Επιτήρηση & Δείγματα» για να δείτε τα περιστατικά επιτήρησης.',
      textEn: 'Press the "Surveillance & Samples" tab to see the surveillance episodes.', advance: 'click' },
    { step: 'hai', target: { sel: 'button.sv-episode-head' },
      titleEl: 'Περιστατικό επιτήρησης', titleEn: 'Surveillance episode',
      textEl: 'Πατήστε το περιστατικό (λοίμωξη αιματικής ροής) για να ανοίξει η πορεία του.',
      textEn: 'Press the episode (bloodstream infection) to open its clinical journey.', advance: 'click' },
    { step: 'hai', target: { sel: '[data-demo-step="clabsi_classification:hai"]' },
      titleEl: 'Ταξινόμηση HAI / AMR', titleEn: 'HAI / AMR classification',
      textEl: 'Πατήστε «HAI / AMR» για να δείτε την ταξινόμηση της λοίμωξης με τα κριτήρια ECDC.',
      textEn: 'Press "HAI / AMR" to review the infection classification against the ECDC criteria.', advance: 'click' },
    { step: 'reassessment', target: { sel: '[data-demo-step="clabsi_classification:reassessment"]' },
      titleEl: 'Επανεκτίμηση', titleEn: 'Reassessment',
      textEl: 'Πατήστε «Επανεκτίμηση» για να δείτε την πορεία του περιστατικού με τις επανεκτιμήσεις.',
      textEn: 'Press "Reassessment" to review how the case evolved across its reassessments.', advance: 'click' },
  ],

  microbiology_mdro: [
    // Only this sample is a positive culture whose workflow reaches AST / AMR / communication.
    { step: 'open', target: { sel: 'tbody tr.registry-row-clickable', text: ['LAB-260827-001', 'LAB-260827-001'] },
      titleEl: 'Θετική καλλιέργεια', titleEn: 'Positive culture',
      textEl: 'Πατήστε το δείγμα LAB-260827-001 (θετική αιμοκαλλιέργεια) για να ανοίξει.',
      textEn: 'Press sample LAB-260827-001 (a positive blood culture) to open it.', advance: 'click' },
    { step: 'ast', target: { sel: '.lab-workflow-next button', text: ['Προσθήκη αντιβιογράμματος', 'Add susceptibility test'] },
      titleEl: 'Επόμενο βήμα: αντιβιόγραμμα', titleEn: 'Next step: susceptibility test',
      textEl: 'Πατήστε «Προσθήκη αντιβιογράμματος» για να καταχωρίσετε το αντιβιόγραμμα του μικροοργανισμού.',
      textEn: 'Press "Add susceptibility test" to record the organism\'s susceptibility result.', advance: 'click' },
    { step: 'ast', target: { sel: '[role=dialog] button.button-primary', text: ['Αποθήκευση', 'Save'] },
      titleEl: 'Αποθήκευση αντιβιογράμματος', titleEn: 'Save the test',
      textEl: 'Επιλέξτε αντιβιοτικό, S/I/R και έκδοση προτύπου και πατήστε «Αποθήκευση».',
      textEn: 'Choose the antibiotic, S/I/R and the standard version, then press "Save".', advance: 'click' },
    { step: 'amr', target: { sel: '.lab-isolate-card button[aria-label]', text: ['Περισσότερες ενέργειες', 'More actions'] },
      titleEl: 'Ταξινόμηση AMR', titleEn: 'AMR classification',
      textEl: 'Πατήστε το μενού του μικροοργανισμού και επιλέξτε «Ταξινόμηση AMR» (MDR / XDR / PDR).',
      textEn: 'Press the organism\'s menu and choose "AMR classification" (MDR / XDR / PDR).', advance: 'click' },
    { step: 'amr', target: { sel: '[role=dialog] button.button-primary', text: ['Αποθήκευση', 'Save'] },
      titleEl: 'Αποθήκευση ταξινόμησης', titleEn: 'Save the classification',
      textEl: 'Επιλέξτε κατηγορία, πηγή και έκδοση ορισμού και πατήστε «Αποθήκευση».',
      textEn: 'Choose the category, definition source and version, then press "Save".', advance: 'click' },
    { step: 'communication', target: { sel: '.lab-communication-card button[aria-label]', text: ['Περισσότερες ενέργειες', 'More actions'] },
      titleEl: 'Επικοινωνία κρίσιμου αποτελέσματος', titleEn: 'Critical-result communication',
      textEl: 'Πατήστε το μενού, επιλέξτε «Καταγραφή επικοινωνίας», συμπληρώστε παραλήπτη και ρόλο και αποθηκεύστε.',
      textEn: 'Press the menu, choose "Record communication", fill in the recipient and role and save.', advance: 'click' },
  ],

  hand_hygiene: [
    { step: null, target: { sel: 'section.who-session-panel' },
      titleEl: 'Στοιχεία συνεδρίας', titleEn: 'Session details',
      textEl: 'Ορίστε ημερομηνία και τμήμα της παρατήρησης.',
      textEn: 'Set the date and department of the observation.' },
    { step: null, target: { sel: 'button.who-moment-option' },
      titleEl: 'Στιγμή του ΠΟΥ', titleEn: 'WHO moment',
      textEl: 'Πατήστε τη στιγμή (ένδειξη) που παρατηρήσατε, π.χ. «Πριν την επαφή με τον ασθενή».',
      textEn: 'Press the moment (indication) you observed, e.g. "Before touching a patient".', advance: 'click' },
    { step: null, target: { sel: 'button.who-action-option' },
      titleEl: 'Ενέργεια', titleEn: 'Action',
      textEl: 'Πατήστε τι έγινε: αντισηπτικό, πλύσιμο ή παράλειψη.',
      textEn: 'Press what happened: hand rub, hand wash or missed.', advance: 'click' },
    { step: null, target: { sel: 'button.lo-action-button', text: ['Προσθήκη ευκαιρίας', 'Add opportunity'] },
      titleEl: 'Προσθήκη ευκαιρίας', titleEn: 'Add the opportunity',
      textEl: 'Πατήστε «Προσθήκη ευκαιρίας»· η ζωντανή σύνοψη υπολογίζει τη συμμόρφωση.',
      textEn: 'Press "Add opportunity"; the live summary calculates compliance.', advance: 'click' },
    { step: null, target: { sel: 'button.lo-action-button', text: ['Αποθήκευση συνεδρίας', 'Save session'] },
      titleEl: 'Αποθήκευση συνεδρίας', titleEn: 'Save the session',
      textEl: 'Πατήστε «Αποθήκευση συνεδρίας». Η συμμόρφωση ανά τμήμα ενημερώνεται στην Πρόληψη.',
      textEn: 'Press "Save session". Compliance per department updates in Prevention.', advance: 'click' },
  ],

  incident_capa: [
    { step: null, target: { sel: 'main label', text: ['Τίτλος', 'Title'] },
      titleEl: 'Στοιχεία συμβάντος', titleEn: 'Incident details',
      textEl: 'Συμπληρώστε τίτλο, τμήμα, τύπο και σοβαρότητα του συμβάντος.',
      textEn: 'Fill in the title, department, type and severity of the incident.' },
    { step: null, target: { sel: 'main button.button-primary', text: ['Αποθήκευση', 'Save'] },
      titleEl: 'Αποθήκευση συμβάντος', titleEn: 'Save the incident',
      textEl: 'Πατήστε «Αποθήκευση»· το συμβάν καταχωρίζεται και ανοίγει η καρτέλα του.',
      textEn: 'Press "Save"; the incident is reported and its record opens.', advance: 'click' },
    { step: null, target: { sel: 'main button.button-primary', text: ['Δημιουργία συνδεδεμένης CAPA', 'Create linked CAPA'] },
      titleEl: 'Διορθωτική ενέργεια', titleEn: 'Corrective action',
      textEl: 'Πατήστε «Δημιουργία συνδεδεμένης CAPA» για να ανοίξει νέα CAPA συνδεδεμένη με το συμβάν.',
      textEn: 'Press "Create linked CAPA" to open a new CAPA linked to the incident.', advance: 'click' },
    { step: null, target: { sel: 'main button.button-primary', text: ['Αποθήκευση', 'Save'] },
      titleEl: 'Αποθήκευση CAPA', titleEn: 'Save the CAPA',
      textEl: 'Ορίστε τμήμα, προτεραιότητα, υπεύθυνο και προθεσμία και πατήστε «Αποθήκευση».',
      textEn: 'Set the department, priority, owner and deadline, then press "Save".', advance: 'click' },
  ],

  analysis_export: [
    { step: null, target: { sel: 'button.analysis-filter-toggle', text: ['Φίλτρα', 'Filters'] },
      titleEl: 'Φίλτρα', titleEn: 'Filters',
      textEl: 'Πατήστε «Φίλτρα» για να επιλέξετε περίοδο και τμήμα.',
      textEn: 'Press "Filters" to choose the period and department.', advance: 'click' },
    { step: null, target: { sel: 'label.analysis-filter-field', text: ['Τμήμα', 'Department'] },
      titleEl: 'Περίοδος και τμήματα', titleEn: 'Period and departments',
      textEl: 'Επιλέξτε έτος, ανάλυση (μήνας, τρίμηνο…) και τμήμα· οι δείκτες ενημερώνονται αμέσως.',
      textEn: 'Choose the year, breakdown (month, quarter…) and department; the indicators update at once.' },
    { step: null, target: { sel: '[role=tab]', text: ['Επιτήρηση & μικροβιολογία', 'Surveillance & microbiology'] },
      titleEl: 'Δείκτες', titleEn: 'Indicators',
      textEl: 'Πατήστε μια ενότητα, π.χ. «Επιτήρηση & μικροβιολογία», για να δείτε τους δείκτες της.',
      textEn: 'Press a section, e.g. "Surveillance & microbiology", to review its indicators.', advance: 'click' },
    { step: null, target: { sel: 'button.analysis-print-trigger' },
      titleEl: 'Εξαγωγή αναφοράς', titleEn: 'Export the report',
      textEl: 'Πατήστε «Εκτύπωση» για να δείτε τις αναφορές ανά ενότητα.',
      textEn: 'Press "Print" to see the reports per section.', advance: 'click' },
    { step: null, target: { sel: 'button.analysis-print-option-pdf' },
      titleEl: 'Λήψη PDF', titleEn: 'Download PDF',
      textEl: 'Πατήστε το εικονίδιο PDF δίπλα σε μια ενότητα για να κατεβάσετε την αναφορά.',
      textEn: 'Press the PDF icon next to a section to download its report.', advance: 'click' },
  ],

  employee_record: [
    { step: 'open', target: { sel: 'tbody tr.registry-row-clickable' },
      titleEl: 'Εργαζόμενος', titleEn: 'Employee',
      textEl: 'Πατήστε έναν εργαζόμενο για να ανοίξει η καρτέλα του.',
      textEn: 'Press an employee to open their record.', advance: 'click' },
    { step: 'training', target: { sel: '[role=tab]', text: ['Εκπαίδευση', 'Training'] },
      titleEl: 'Εκπαίδευση', titleEn: 'Training',
      textEl: 'Πατήστε την καρτέλα «Εκπαίδευση» για να δείτε τα προγράμματα και την πρόοδό του.',
      textEn: 'Press the "Training" tab to see their programmes and progress.', advance: 'click' },
    { step: 'documents', target: { sel: '[role=tab]', text: ['Έγγραφα', 'Documents'] },
      titleEl: 'Έγγραφα', titleEn: 'Documents',
      textEl: 'Πατήστε την καρτέλα «Έγγραφα» για να δείτε πιστοποιητικά και έγγραφα.',
      textEn: 'Press the "Documents" tab to see certificates and documents.', advance: 'click' },
  ],

  performance_evaluation: [
    { step: 'open', target: { sel: 'tbody tr.registry-row-clickable' },
      titleEl: 'Εργαζόμενος', titleEn: 'Employee',
      textEl: 'Πατήστε έναν εργαζόμενο για να ανοίξει η καρτέλα του.',
      textEn: 'Press an employee to open their record.', advance: 'click' },
    { step: 'evaluations', target: { sel: '[role=tab]', text: ['Αξιολογήσεις', 'Evaluations'] },
      titleEl: 'Αξιολογήσεις', titleEn: 'Evaluations',
      textEl: 'Πατήστε την καρτέλα «Αξιολογήσεις».',
      textEn: 'Press the "Evaluations" tab.', advance: 'click' },
    { step: 'create', target: { sel: 'main button.lo-action-button', text: ['Νέα αξιολόγηση', 'New evaluation'] },
      titleEl: 'Νέα αξιολόγηση', titleEn: 'New evaluation',
      textEl: 'Πατήστε «Νέα αξιολόγηση».',
      textEn: 'Press "New evaluation".', advance: 'click' },
    { step: 'create', target: { sel: 'button.button-primary', text: ['Αποθήκευση', 'Save'] },
      titleEl: 'Αποθήκευση αξιολόγησης', titleEn: 'Save the evaluation',
      textEl: 'Επιλέξτε την περίοδο αξιολόγησης, προσθέστε σχόλια και πατήστε «Αποθήκευση».',
      textEn: 'Choose the evaluation period, add comments and press "Save".', advance: 'click' },
  ],

  occupational_visit: [
    { step: 'visit', target: { sel: 'main button.lo-action-button-primary', text: ['Νέα επίσκεψη', 'New Occupational Health visit'] },
      titleEl: 'Νέα επίσκεψη', titleEn: 'New visit',
      textEl: 'Πατήστε «Νέα επίσκεψη Ιατρού Εργασίας».',
      textEn: 'Press "New Occupational Health visit".', advance: 'click' },
    { step: 'visit', target: { sel: '[role=dialog] label', text: ['Τύπος επίσκεψης', 'Visit type'] },
      titleEl: 'Είδος και συμπέρασμα', titleEn: 'Type and outcome',
      textEl: 'Επιλέξτε εργαζόμενο, κατάσταση, ημερομηνία και τύπο επίσκεψης και γράψτε τις κλινικές σημειώσεις.',
      textEn: 'Choose the employee, status, date and visit type and write the clinical notes.' },
    { step: 'visit', target: { sel: '[role=dialog] button.button-primary', text: ['Αποθήκευση', 'Save'] },
      titleEl: 'Αποθήκευση', titleEn: 'Save',
      textEl: 'Πατήστε «Αποθήκευση» για να καταχωριστεί η επίσκεψη.',
      textEn: 'Press "Save" to record the visit.', advance: 'click' },
  ],

  occupational_exposure: [
    { step: 'record', target: { sel: '[role=tab]', text: ['Περιστατικά έκθεσης', 'Exposure incidents'] },
      titleEl: 'Περιστατικά έκθεσης', titleEn: 'Exposure incidents',
      textEl: 'Πατήστε την καρτέλα «Περιστατικά έκθεσης».',
      textEn: 'Press the "Exposure incidents" tab.', advance: 'click' },
    { step: 'record', target: { sel: 'main button.lo-action-button-primary', text: ['Νέο περιστατικό έκθεσης', 'New exposure incident'] },
      titleEl: 'Νέο περιστατικό', titleEn: 'New incident',
      textEl: 'Πατήστε «Νέο περιστατικό έκθεσης».',
      textEn: 'Press "New exposure incident".', advance: 'click' },
    { step: 'record', target: { sel: '[role=dialog] label', text: ['Τύπος έκθεσης', 'Exposure type'] },
      titleEl: 'Έκθεση και παρακολούθηση', titleEn: 'Exposure and follow-up',
      textEl: 'Επιλέξτε εργαζόμενο, ημερομηνία και τύπο έκθεσης (π.χ. τρύπημα βελόνας), την κατάσταση της πηγής, την PEP και την παρακολούθηση.',
      textEn: 'Choose the employee, date and exposure type (e.g. needlestick), the source status, PEP and the follow-up.' },
    { step: 'record', target: { sel: '[role=dialog] button.button-primary', text: ['Αποθήκευση περιστατικού', 'Save incident'] },
      titleEl: 'Αποθήκευση', titleEn: 'Save',
      textEl: 'Πατήστε «Αποθήκευση περιστατικού».',
      textEn: 'Press "Save incident".', advance: 'click' },
  ],

  quality_audit: [
    { step: 'create', target: { sel: 'main label', text: ['Τίτλος', 'Title'] },
      titleEl: 'Στοιχεία επιθεώρησης', titleEn: 'Audit details',
      textEl: 'Συμπληρώστε τίτλο, τμήμα, τύπο, ημερομηνία και το εύρος της επιθεώρησης.',
      textEn: 'Fill in the title, department, type, date and scope of the audit.' },
    { step: 'create', target: { sel: 'main button.button-primary', text: ['Αποθήκευση', 'Save'] },
      titleEl: 'Αποθήκευση', titleEn: 'Save',
      textEl: 'Πατήστε «Αποθήκευση» για να καταχωριστεί η επιθεώρηση.',
      textEn: 'Press "Save" to record the audit.', advance: 'click' },
  ],

  antimicrobial_consumption: [
    { step: 'save', target: { sel: 'main button.button-primary', text: ['Περίοδος χορήγησης', 'Dispensing period'] },
      titleEl: 'Νέα χορήγηση', titleEn: 'New dispensing',
      textEl: 'Πατήστε «Περίοδος χορήγησης» για να καταχωρίσετε μηνιαία ποσότητα αντιβιοτικού.',
      textEn: 'Press "Dispensing period" to record a monthly antibiotic quantity.', advance: 'click' },
    { step: 'save', target: { sel: '[role=dialog] label', text: ['Ποσότητα', 'Quantity'] },
      titleEl: 'Τμήμα, αντιβιοτικό, ποσότητα', titleEn: 'Department, antibiotic, quantity',
      textEl: 'Επιλέξτε μήνα, τμήμα και αντιβιοτικό και συμπληρώστε την ποσότητα σε γραμμάρια.',
      textEn: 'Choose the month, department and antibiotic and enter the quantity in grams.' },
    { step: 'save', target: { sel: '[role=dialog] button.button-primary', text: ['Αποθήκευση', 'Save'] },
      titleEl: 'Αποθήκευση', titleEn: 'Save',
      textEl: 'Πατήστε «Αποθήκευση»· η κατανάλωση ανά τμήμα ενημερώνεται.',
      textEn: 'Press "Save"; consumption per department updates.', advance: 'click' },
  ],

  committee_minutes: [
    { step: 'open', target: { sel: 'tbody tr.registry-row-clickable' },
      titleEl: 'Επιτροπή', titleEn: 'Committee',
      textEl: 'Πατήστε μια επιτροπή για να ανοίξει η καρτέλα της.',
      textEn: 'Press a committee to open its record.', advance: 'click' },
    { step: 'meeting', target: { sel: '[role=tab]', text: ['Συνεδριάσεις', 'Meetings'] },
      titleEl: 'Συνεδριάσεις', titleEn: 'Meetings',
      textEl: 'Πατήστε την καρτέλα «Συνεδριάσεις».',
      textEn: 'Press the "Meetings" tab.', advance: 'click' },
    { step: 'meeting', target: { sel: 'main button.lo-action-button-primary', text: ['Νέα συνεδρίαση', 'New meeting'] },
      titleEl: 'Νέα συνεδρίαση', titleEn: 'New meeting',
      textEl: 'Πατήστε «Νέα συνεδρίαση».',
      textEn: 'Press "New meeting".', advance: 'click' },
    { step: 'meeting', target: { sel: '[role=dialog] button.button-primary', text: ['Δημιουργία & συνέχεια', 'Create & continue'] },
      titleEl: 'Προγραμματισμός', titleEn: 'Schedule',
      textEl: 'Συμπληρώστε τίτλο και ημερομηνία και πατήστε «Δημιουργία & συνέχεια».',
      textEn: 'Fill in the title and date and press "Create & continue".', advance: 'click' },
    { step: 'minutes', target: { sel: '.committee-meeting-dialog button.button-secondary', text: ['Αποθήκευση', 'Save'] },
      titleEl: 'Πρακτικά', titleEn: 'Minutes',
      textEl: 'Καταγράψτε παρουσίες και θέματα με τις αποφάσεις τους και πατήστε «Αποθήκευση».',
      textEn: 'Record attendance and the topics with their conclusions, then press "Save".', advance: 'click' },
  ],

  users_roles: [
    { step: 'create', target: { sel: 'main button.button-primary', text: ['Νέος χρήστης', 'New user'] },
      titleEl: 'Νέος χρήστης', titleEn: 'New user',
      textEl: 'Πατήστε «Νέος χρήστης».',
      textEn: 'Press "New user".', advance: 'click' },
    { step: 'create', target: { sel: '[role=dialog] label', text: ['Ρόλος', 'Role'] },
      titleEl: 'Στοιχεία και ρόλος', titleEn: 'Details and role',
      textEl: 'Συνδέστε τον χρήστη με εργαζόμενο (ή δημιουργήστε νέο), συμπληρώστε email και επιλέξτε ρόλο.',
      textEn: 'Link the user to an employee (or create one), fill in the email and choose a role.' },
    { step: 'create', target: { sel: '[role=dialog] button.button-primary' },
      titleEl: 'Δημιουργία', titleEn: 'Create',
      textEl: 'Πατήστε το κουμπί δημιουργίας του χρήστη.',
      textEn: 'Press the button that creates the user.', advance: 'click' },
    { step: 'role', target: { sel: 'tbody tr button.text-button', text: ['Διαχείριση', 'Manage'] },
      titleEl: 'Διαχείριση χρήστη', titleEn: 'Manage a user',
      textEl: 'Πατήστε «Διαχείριση» σε έναν χρήστη για να αλλάξετε την πρόσβασή του.',
      textEn: 'Press "Manage" on a user to change their access.', advance: 'click' },
    // The user-access dialog is Greek-only even in English, so no text filter:
    // its first primary button is the role save.
    { step: 'role', target: { sel: '[role=dialog] button.button-primary' },
      titleEl: 'Αλλαγή ρόλου', titleEn: 'Change the role',
      textEl: 'Επιλέξτε άλλο ρόλο και πατήστε «Αποθήκευση ρόλου».',
      textEn: 'Choose another role and press the role save button.', advance: 'click' },
  ],

  custom_roles: [
    { step: 'save', target: { sel: 'main button.button-primary', text: ['Νέος ρόλος', 'New role'] },
      titleEl: 'Νέος ρόλος', titleEn: 'New role',
      textEl: 'Πατήστε «Νέος ρόλος».',
      textEn: 'Press "New role".', advance: 'click' },
    { step: 'save', target: { sel: 'label.management-role-name-field' },
      titleEl: 'Όνομα ρόλου', titleEn: 'Role name',
      textEl: 'Δώστε ένα όνομα στον ρόλο.',
      textEn: 'Give the role a name.' },
    { step: 'save', target: { sel: 'label.management-role-capability' },
      titleEl: 'Δικαιώματα', titleEn: 'Permissions',
      textEl: 'Επιλέξτε τα δικαιώματα που θα έχει ο ρόλος (τουλάχιστον ένα).',
      textEn: 'Tick the permissions the role will have (at least one).' },
    { step: 'save', target: { sel: 'main button.button-primary', text: ['Αποθήκευση ρόλου', 'Save role'] },
      titleEl: 'Αποθήκευση', titleEn: 'Save',
      textEl: 'Πατήστε «Αποθήκευση ρόλου».',
      textEn: 'Press "Save role".', advance: 'click' },
  ],

  department_overview: [
    { step: 'control', target: { sel: 'button.task-row' },
      titleEl: 'Εκκρεμότητες τμήματος', titleEn: 'Department work',
      textEl: 'Εδώ βλέπετε τις εκκρεμότητες και τις ανακοινώσεις του τμήματός σας.',
      textEn: 'Here you see your department\'s pending work and announcements.' },
    { step: 'control', target: { sel: 'a.nav-item[href*="/controls"]' },
      titleEl: 'Έλεγχοι', titleEn: 'Controls',
      textEl: 'Πατήστε «Έλεγχοι» στο μενού.',
      textEn: 'Press "Controls" in the menu.', advance: 'click' },
    { step: 'control', target: { sel: 'tbody tr.registry-row-clickable' },
      titleEl: 'Έλεγχος', titleEn: 'Inspection',
      textEl: 'Πατήστε έναν έλεγχο του τμήματος για να τον ανοίξετε.',
      textEn: 'Press one of the department\'s inspections to open it.', advance: 'click' },
  ],

  staff_training: [
    { step: 'open', target: { sel: 'tbody tr.registry-row-clickable' },
      titleEl: 'Εκπαιδευτικό πρόγραμμα', titleEn: 'Training programme',
      textEl: 'Πατήστε ένα πρόγραμμα για να ανοίξει.',
      textEn: 'Press a programme to open it.', advance: 'click' },
  ],
})
