import { useEffect,useMemo,useState } from 'react'
import { Archive,BookOpenCheck,FileClock,Paperclip,Pencil,RotateCcw,Trash2 } from 'lucide-react'
import { useNavigate,useParams } from 'react-router-dom'
import { Page } from '../../design-system/Page'
import { EntityRecordShell } from '../../design-system/EntityRecordShell'
import { Button } from '../../design-system/Button'
import { SaveButton } from '../../design-system/SaveButton'
import { AttachmentField } from '../../design-system/AttachmentField'
import { useTenant } from '../../core/tenant/TenantContext'
import { can,CAPABILITIES } from '../../core/permissions/roles'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { useAuditActor } from '../../core/audit/useAuditActor'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useDocumentsData } from './useDocumentsData'
import { updateDocumentAsync,submitDocumentReviewAsync,approveDocumentAsync,returnDocumentToDraftAsync,publishDocumentAsync,archiveDocumentAsync,createDocumentRevisionAsync,deleteDocumentDraftAsync,loadDocumentOwnerProfile,getDocumentFamily } from './documentService'
import { DocumentForm,DOCUMENT_TYPES,documentDraftIsValid } from './DocumentForm'
import { loadDepartments } from '../management/departmentsService'
import { RouteLoading } from '../../design-system/RouteLoading'

const labels={el:{types:DOCUMENT_TYPES.el,statuses:{draft:'Πρόχειρο',review:'Σε έλεγχο',approved:'Εγκεκριμένο',published:'Δημοσιευμένο',superseded:'Αντικαταστάθηκε',archived:'Αρχειοθετημένο'}},en:{types:DOCUMENT_TYPES.en,statuses:{draft:'Draft',review:'In review',approved:'Approved',published:'Published',superseded:'Superseded',archived:'Archived'}}}
const toDraft=record=>({title:record?.title||'',type:record?.type||'policy',version:record?.version||'0.1',departmentId:record?.departmentId||null,audience:record?.audience||'organization',effectiveDate:record?.effectiveDate||'',reviewDate:record?.reviewDate||'',description:record?.description||''})
function formatHistoryAction(item,en,statusLabels){if(item.action==='created')return en?'Created':'Δημιουργία';if(item.action==='updated')return en?'Updated':'Ενημέρωση';if(item.action==='deleted')return en?'Deleted':'Διαγραφή';if(item.action?.startsWith('status:')){const transition=item.action.slice(7);if(transition.includes('->')){const [from,to]=transition.split('->');return `${statusLabels[from]||from} → ${statusLabels[to]||to}`}return `${en?'Current state':'Τρέχουσα κατάσταση'}: ${statusLabels[transition]||transition}`}return item.action||'—'}
function formatDateTime(value,en){if(!value)return '—';const date=new Date(value);if(Number.isNaN(date.getTime()))return value;return date.toLocaleString(en?'en-GB':'el-GR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})}

export function DocumentRecordPage(){
 const {documentId}=useParams(),navigate=useNavigate(),actor=useAuditActor(),{notify,confirm}=useFeedback(),{role,membership,tenant,isDemo}=useTenant(),{language}=useLanguage();const en=language==='en',typeLabels=labels[language].types,statusLabels=labels[language].statuses
 const {data:rows,loading,error,reload}=useDocumentsData();const [tab,setTab]=useState('overview'),[editing,setEditing]=useState(false),[draft,setDraft]=useState(null),[busy,setBusy]=useState(false),[departments,setDepartments]=useState([]),[ownerName,setOwnerName]=useState('')
 const record=useMemo(()=>rows.find(x=>x.id===documentId)||null,[rows,documentId]);const family=useMemo(()=>getDocumentFamily(rows,record),[rows,record]);const addOns=membership?.capabilities??[],custom=membership?.customCapabilities??[]
 const canManage=can(role,CAPABILITIES.MANAGE_DOCUMENTS,addOns,custom),canSubmitReview=can(role,CAPABILITIES.SUBMIT_DOCUMENT_REVIEW,addOns,custom),canApprove=can(role,CAPABILITIES.APPROVE_DOCUMENT,addOns,custom),canPublish=can(role,CAPABILITIES.PUBLISH_DOCUMENT,addOns,custom),canSupersede=can(role,CAPABILITIES.SUPERSEDE_DOCUMENT,addOns,custom),canArchive=can(role,CAPABILITIES.ARCHIVE_DOCUMENT,addOns,custom),organizationId=tenant?.id||null
 useEffect(()=>{let active=true;if(!organizationId)return;loadDepartments(organizationId).then(data=>{if(active)setDepartments((data||[]).filter(x=>x.is_active!==false))}).catch(()=>{if(active)setDepartments([])});return()=>{active=false}},[organizationId])
 useEffect(()=>{if(record){setDraft(toDraft(record));setEditing(false)}},[record])
 useEffect(()=>{let active=true;if(!record?.ownerId){setOwnerName('');return()=>{active=false}};if(record.ownerId===actor?.id){setOwnerName(actor?.name||'');return()=>{active=false}};loadDocumentOwnerProfile(record.ownerId).then(profile=>{if(active)setOwnerName(profile?.full_name||profile?.username||'')}).catch(()=>{if(active)setOwnerName('')});return()=>{active=false}},[record?.ownerId,actor?.id,actor?.name])
 if(loading)return <RouteLoading/>;if(error)return <Page title={en?'Documents':'Έγγραφα'}><div className="data-access-state error" role="alert"><span>{en?'Could not load the document.':'Δεν ήταν δυνατή η φόρτωση του εγγράφου.'}</span><button type="button" onClick={()=>reload().catch(()=>{})}>{en?'Retry':'Επανάληψη'}</button></div></Page>;if(!record||!draft)return <Page title={en?'Documents':'Έγγραφα'}><div className="inline-empty">{en?'Document not found.':'Το έγγραφο δεν βρέθηκε.'}</div></Page>
 async function run(operation,successMessage){if(busy)return null;setBusy(true);try{const result=await operation();await reload();if(successMessage)notify(successMessage,'success');return result}catch(error){notify(error?.message||(en?'The action could not be completed.':'Η ενέργεια δεν ήταν δυνατό να ολοκληρωθεί.'),'danger');return null}finally{setBusy(false)}}
 async function saveEdit(){if(!documentDraftIsValid(draft)||busy)return;const result=await run(()=>updateDocumentAsync(organizationId,record,draft,actor),en?'Document updated.':'Το έγγραφο ενημερώθηκε.');if(result)setEditing(false)}
 async function submitReview(){if(record.status!=='draft'||!canSubmitReview)return;const ok=await confirm({title:en?'Submit for review':'Υποβολή για έλεγχο',message:en?'Editing will be locked while the document is reviewed. Continue?':'Η επεξεργασία θα κλειδώσει όσο το έγγραφο βρίσκεται σε έλεγχο. Θέλετε να συνεχίσετε;',confirmLabel:en?'Submit':'Υποβολή'});if(ok)await run(()=>submitDocumentReviewAsync(organizationId,record,actor),en?'Document submitted for review.':'Το έγγραφο υποβλήθηκε για έλεγχο.')}
 async function approve(){if(record.status!=='review'||!canApprove)return;const ok=await confirm({title:en?'Approve document':'Έγκριση εγγράφου',message:en?'The reviewed version will be approved for publication. Continue?':'Η ελεγμένη έκδοση θα εγκριθεί για δημοσίευση. Θέλετε να συνεχίσετε;',confirmLabel:en?'Approve':'Έγκριση'});if(ok)await run(()=>approveDocumentAsync(organizationId,record,actor),en?'Document approved.':'Το έγγραφο εγκρίθηκε.')}
 async function returnToDraft(){if(!['review','approved'].includes(record.status)||!(canManage||canApprove))return;const ok=await confirm({title:en?'Return to draft':'Επιστροφή σε πρόχειρο',message:en?'The current revision will become editable again. Its audit history will be preserved. Continue?':'Η τρέχουσα έκδοση θα γίνει ξανά επεξεργάσιμη. Το ιστορικό της θα διατηρηθεί. Θέλετε να συνεχίσετε;',confirmLabel:en?'Return to draft':'Επιστροφή σε πρόχειρο'});if(ok)await run(()=>returnDocumentToDraftAsync(organizationId,record,actor),en?'Document returned to draft.':'Το έγγραφο επέστρεψε σε πρόχειρο.')}
 async function publish(){if(record.status!=='approved'||!canPublish)return;const ok=await confirm({title:en?'Publish document':'Δημοσίευση εγγράφου',message:en?'The approved version will become active for use. Continue?':'Η εγκεκριμένη έκδοση θα γίνει ενεργή για χρήση. Θέλετε να συνεχίσετε;',confirmLabel:en?'Publish':'Δημοσίευση'});if(ok)await run(()=>publishDocumentAsync(organizationId,record,actor),en?'Document published.':'Το έγγραφο δημοσιεύτηκε.')}
 async function archive(){if(record.status!=='published'||!canArchive)return;const ok=await confirm({title:en?'Archive document':'Αρχειοθέτηση εγγράφου',message:en?'The document will no longer be active for current use. History will be preserved.':'Το έγγραφο θα πάψει να θεωρείται ενεργό για τρέχουσα χρήση. Το ιστορικό θα διατηρηθεί.',confirmLabel:en?'Archive':'Αρχειοθέτηση',danger:true});if(ok)await run(()=>archiveDocumentAsync(organizationId,record,actor),en?'Document archived.':'Το έγγραφο αρχειοθετήθηκε.')}
 async function createRevision(){if(record.status!=='published'||!canSupersede)return;const ok=await confirm({title:en?'Create new revision':'Νέα αναθεώρηση',message:en?'A new draft version will be created. The published version stays active until the revision is published.':'Θα δημιουργηθεί νέα πρόχειρη έκδοση. Η δημοσιευμένη έκδοση παραμένει ενεργή μέχρι να δημοσιευτεί η αναθεώρηση.',confirmLabel:en?'Create revision':'Δημιουργία αναθεώρησης'});if(!ok)return;const next=await run(()=>createDocumentRevisionAsync(organizationId,record,actor,rows),en?'New draft revision created.':'Δημιουργήθηκε νέα πρόχειρη αναθεώρηση.');if(next)navigate(`/documents/${next.id}`)}
 async function removeDraft(){if(record.status!=='draft'||!canManage)return;const ok=await confirm({title:en?'Delete draft':'Διαγραφή πρόχειρου',message:en?'This draft document will be permanently deleted. Continue?':'Το πρόχειρο έγγραφο θα διαγραφεί οριστικά. Θέλετε να συνεχίσετε;',confirmLabel:en?'Delete':'Διαγραφή',danger:true});if(!ok)return;setBusy(true);try{await deleteDocumentDraftAsync(organizationId,record);notify(en?'Draft deleted.':'Το πρόχειρο διαγράφηκε.','success');navigate('/documents',{replace:true})}catch(error){notify(error?.message||(en?'Could not delete draft.':'Δεν ήταν δυνατή η διαγραφή του πρόχειρου.'),'danger')}finally{setBusy(false)}}
 async function attachments(next){if(!isDemo)return;await run(()=>updateDocumentAsync(organizationId,record,{attachments:next},actor),en?'Attachments updated.':'Τα συνημμένα ενημερώθηκαν.')};function cancelEdit(){setDraft(toDraft(record));setEditing(false)}
 const tabs=[{id:'overview',label:en?'Overview':'Σύνοψη',icon:BookOpenCheck},{id:'files',label:en?'Files':'Αρχεία',icon:Paperclip},{id:'history',label:en?'History':'Ιστορικό',icon:FileClock}],headerActions=canManage&&!editing&&record.status==='draft'?<><button type="button" className="lo-icon-button lo-icon-button-edit" onClick={()=>setEditing(true)} title={en?'Edit':'Επεξεργασία'} aria-label={en?'Edit':'Επεξεργασία'}><Pencil size={16}/></button><button type="button" className="lo-icon-button lo-icon-button-danger" onClick={removeDraft} disabled={busy} title={en?'Delete':'Διαγραφή'} aria-label={en?'Delete':'Διαγραφή'}><Trash2 size={16}/></button></>:null
 return <Page fill><EntityRecordShell avatar={<BookOpenCheck size={19}/>} eyebrow={record.id} title={record.title} subtitle={`${typeLabels[record.type]||record.type} · ${en?'Version':'Έκδοση'} ${record.version||'—'}`} status={<span className={`status-badge ${record.status==='published'?'active':record.status==='draft'?'temporary':''}`}>{statusLabels[record.status]||record.status}</span>} onBack={()=>navigate('/documents')} headerActions={headerActions} tabs={tabs} activeTab={tab} onTabChange={setTab}>
 {tab==='overview'&&<div className="document-record-workspace"><section className="record-section"><div className="record-section-header"><div><span className="eyebrow">{en?'Document':'Έγγραφο'}</span><h3>{en?'Document details':'Στοιχεία εγγράφου'}</h3><p>{en?'Core metadata and scope for this controlled document.':'Βασικά στοιχεία και πεδίο εφαρμογής του ελεγχόμενου εγγράφου.'}</p></div></div><DocumentForm value={draft} onChange={setDraft} language={language} departments={departments} ownerName={ownerName} readOnly={!editing}/>{editing&&<div className="inline-edit-footer"><Button variant="secondary" onClick={cancelEdit} disabled={busy}>{en?'Cancel':'Ακύρωση'}</Button><SaveButton loading={busy} disabled={!documentDraftIsValid(draft)||busy} onClick={saveEdit}>{en?'Save':'Αποθήκευση'}</SaveButton></div>}</section>
 {!editing&&<section className="record-section document-lifecycle-section"><div className="record-section-header"><div><span className="eyebrow">{en?'Workflow':'Ροή έγκρισης'}</span><h3>{en?'Next action':'Επόμενη ενέργεια'}</h3><p>{record.status==='draft'?(en?'The document is editable and can be submitted for review.':'Το έγγραφο είναι επεξεργάσιμο και μπορεί να υποβληθεί για έλεγχο.'):record.status==='review'?(en?'The document is under review. It may be approved or returned to draft for corrections.':'Το έγγραφο βρίσκεται σε έλεγχο. Μπορεί να εγκριθεί ή να επιστρέψει σε πρόχειρο για διορθώσεις.'):record.status==='approved'?(en?'The document is approved. It may be published or returned to draft before publication.':'Το έγγραφο έχει εγκριθεί. Μπορεί να δημοσιευτεί ή να επιστρέψει σε πρόχειρο πριν τη δημοσίευση.'):record.status==='published'?(en?'The published document is locked. Create a revision for changes.':'Το δημοσιευμένο έγγραφο είναι κλειδωμένο. Για αλλαγές δημιουργήστε νέα αναθεώρηση.'):(en?'No further workflow action is available.':'Δεν υπάρχει διαθέσιμη επόμενη ενέργεια.')}</p></div></div><div className="record-actions">{record.status==='draft'&&canSubmitReview&&<Button onClick={submitReview} disabled={busy}>{en?'Submit for review':'Υποβολή για έλεγχο'}</Button>}{record.status==='review'&&canApprove&&<Button onClick={approve} disabled={busy}>{en?'Approve':'Έγκριση'}</Button>}{['review','approved'].includes(record.status)&&(canManage||canApprove)&&<Button variant="secondary" onClick={returnToDraft} disabled={busy}><RotateCcw size={15}/>{en?'Return to draft':'Επιστροφή σε πρόχειρο'}</Button>}{record.status==='approved'&&canPublish&&<Button onClick={publish} disabled={busy}>{en?'Publish':'Δημοσίευση'}</Button>}{record.status==='published'&&canSupersede&&<Button onClick={createRevision} disabled={busy}><Pencil size={15}/>{en?'New revision':'Νέα αναθεώρηση'}</Button>}{record.status==='published'&&canArchive&&<button type="button" className="lo-icon-button lo-icon-button-danger" onClick={archive} disabled={busy} title={en?'Archive':'Αρχειοθέτηση'} aria-label={en?'Archive':'Αρχειοθέτηση'}><Archive size={16}/></button>}</div></section>}</div>}
 {tab==='files'&&<section className="record-section"><div className="record-section-header"><div><span className="eyebrow">{en?'Documents':'Έγγραφα'}</span><h3>{en?'Files & attachments':'Αρχεία & συνημμένα'}</h3><p>{record.status==='draft'?(en?'Draft attachments can be added, corrected or removed.':'Στο πρόχειρο μπορείτε να προσθέσετε, να διορθώσετε ή να αφαιρέσετε συνημμένα.'):(en?'Attachments are locked for this lifecycle state. Return to draft or create a revision to change them.':'Τα συνημμένα είναι κλειδωμένα σε αυτή την κατάσταση. Επιστρέψτε σε πρόχειρο ή δημιουργήστε αναθεώρηση για αλλαγές.')}</p></div></div><AttachmentField disabled={!canManage||record.status!=='draft'} value={record.attachments||[]} onChange={attachments} organizationId={organizationId} entityType="controlled_document" entityId={record.dbId||record.id}/></section>}
 {tab==='history'&&<section className="record-section"><div className="record-section-header"><div><span className="eyebrow">{en?'Governance':'Διακυβέρνηση'}</span><h3>{en?'Version & lifecycle history':'Ιστορικό εκδόσεων & κύκλου ζωής'}</h3><p>{en?'Each revision keeps its own canonical audit trail.':'Κάθε έκδοση διατηρεί τη δική της πραγματική ροή από το κεντρικό audit trail.'}</p></div></div>{family.length===0?<div className="inline-empty">{en?'No lifecycle audit events are available yet.':'Δεν υπάρχουν ακόμη καταγεγραμμένα audit events για τον κύκλο ζωής.'}</div>:<div className="document-version-history">{family.map(version=><details key={version.dbId||version.id} className="record-section" open={version.dbId===record.dbId}><summary><strong>{en?'Version':'Έκδοση'} {version.version||'—'}</strong> · {statusLabels[version.status]||version.status} · {version.id}</summary><div className="document-version-history-events">{(version.history||[]).length===0?<div className="inline-empty">{en?'No audit events for this revision.':'Δεν υπάρχουν audit events για αυτή την έκδοση.'}</div>:(version.history||[]).map((item,index)=><div key={`${item.at}-${index}`} className="timeline-line"><strong>{formatHistoryAction(item,en,statusLabels)}</strong><span>{formatDateTime(item.at,en)} · {item.actor}</span></div>)}</div></details>)}</div>}</section>}
 </EntityRecordShell></Page>
}
