import { useEffect,useMemo,useRef,useState } from 'react'
import { Activity,BookOpen,BriefcaseMedical,Check,ChevronDown,ChevronUp,SlidersHorizontal,ClipboardCheck,Download,FileWarning,FlaskConical,GraduationCap,Hand,Microscope,Pill,Printer,ShieldAlert,ShieldCheck,Stethoscope,Users } from 'lucide-react'
import { useLocation,useNavigate } from 'react-router-dom'
import { useTenant } from '../../core/tenant/TenantContext'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { ROLES } from '../../core/permissions/roles'
import { BackButton } from '../../design-system/BackButton'
import { IconButton } from '../../design-system/IconButton'
import { RegistryTable } from '../../design-system/RegistryTable'
import { loadAnalysisSnapshot } from '../platform/platformService'
import { collectAnalysisDemoSnapshot } from './analysisDemoSnapshot'
import { buildSectionModel,collectDemoDomainMetrics } from './analysisDomains'
import { exportElementAsPdf } from '../../core/export/pdfReportExport'
import { downloadCsv } from '../../core/export/csvExport'
import { BarList,ChartCard,DonutChart,TrendChart,numericRows } from './AnalysisCharts'
import { ReportingPanel } from '../reporting/ReportingPanel'

const EMPTY_ORGANIZATIONS=Object.freeze([])
const COMPACT_QUERY='(max-height: 900px) and (min-width: 981px)'
const CLINICAL_SITES=['bloodCulture','urineCulture','respiratorySample','woundCulture']
const SITE_LABELS={bloodCulture:['Αιμοκαλλιέργεια','Blood culture'],urineCulture:['Καλλιέργεια ούρων','Urine culture'],respiratorySample:['Αναπνευστικό δείγμα','Respiratory sample'],woundCulture:['Καλλιέργεια τραύματος','Wound culture'],environmental:['Περιβαλλοντικό δείγμα','Environmental sample'],surveillance:['Επιτήρηση προσωπικού','Staff surveillance'],surface:['Περιβαλλοντικό δείγμα (επιφάνεια)','Environmental sample (surface)'],equipment:['Περιβαλλοντικό δείγμα (εξοπλισμός)','Environmental sample (equipment)'],water:['Περιβαλλοντικό δείγμα (νερό)','Environmental sample (water)'],air:['Περιβαλλοντικό δείγμα (αέρας)','Environmental sample (air)']}
// A sample_type an infection-control clinician can't place (an unrecognized
// code, or a non-clinical environmental/surveillance swab that has no real
// "infection site") must never echo verbatim — that reads as duplicated
// garbage next to the specimen-detail column, which is exactly what it is.
function siteLabel(value,tx){const pair=SITE_LABELS[value];return pair?tx(pair[0],pair[1]):tx('Λοιπό δείγμα','Other sample')}
// Same (organism, resistance, department, source, site) line list every
// chart on this page summarizes — cross-referencing organism with infection
// site (blood/urine/respiratory/wound) directly, instead of the two only
// being joinable by scanning the full line list by eye. Restricted to the
// four clinical culture types: environmental/surveillance swabs have no
// clinical "infection site" and would just dilute this breakdown.
function organismBySiteRows(rows,tx,limit=12){
 const grouped=new Map()
 for(const [organism,,,,count,,sampleType] of rows||[]){
  if(!CLINICAL_SITES.includes(sampleType))continue
  const label=`${organism} · ${siteLabel(sampleType,tx)}`
  grouped.set(label,(grouped.get(label)||0)+(Number(count)||0))
 }
 return [...grouped.entries()].sort((a,b)=>b[1]-a[1]).slice(0,limit)
}
const TABS=[['overview','Σύνοψη','Overview',Activity],['national','Εθνική Επιτήρηση','National surveillance',Microscope],['surveillance','Επιτήρηση & HAI','Surveillance & HAI',Stethoscope],['laboratory','Μικροβιολογία','Microbiology',FlaskConical],['amr','AMR / MDR-XDR','AMR / MDR-XDR',ShieldAlert],['antimicrobials','Αντιμικροβιακά','Antimicrobials',Pill],['prevention','Πρόληψη','Prevention',ShieldCheck],['hand','Υγιεινή Χεριών','Hand hygiene',Hand],['controls','Έλεγχοι','Controls',ClipboardCheck],['occupational','Εργαζόμενοι','Employees',Users],['quality','Ποιότητα','Quality',BriefcaseMedical],['training','Εκπαίδευση','Training',GraduationCap],['governance','Διακυβέρνηση','Governance',BookOpen]]
// Organization-level only: data quality, ΕΟΔΥ notifications and EARS-Net export work on sample-level laboratory data.
const REPORTING_TAB=['reporting','Αναφορές & ποιότητα δεδομένων','Reporting & data quality',FileWarning]
const MONTHS_EL=['Ιανουάριος','Φεβρουάριος','Μάρτιος','Απρίλιος','Μάιος','Ιούνιος','Ιούλιος','Αύγουστος','Σεπτέμβριος','Οκτώβριος','Νοέμβριος','Δεκέμβριος']
const MONTHS_EN=['January','February','March','April','May','June','July','August','September','October','November','December']

function hashOrganization(hash=''){const query=hash.includes('?')?hash.split('?')[1]:'';return new URLSearchParams(query).get('organization')||'all'}
function fmtDate(value){if(!value)return '—';const [y,m,d]=String(value).slice(0,10).split('-');return y&&m&&d?`${d}/${m}/${y}`:value}
// An AMR row's value can be a "resistant/tested" ratio string (e.g. '3/12');
// stripping the '/' without splitting first would concatenate both numbers
// into one (numberValue('1/1') -> 11). Take the resistant count (numerator).
function numberValue(value){const raw=String(value??'');const primary=raw.includes('/')?raw.split('/')[0]:raw;const normalized=primary.replaceAll('.','').replace(',','.').replace(/[^0-9.-]/g,'');const n=Number(normalized);return Number.isFinite(n)?n:0}
function isoDate(year,month,day){return `${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`}
function daysInMonth(year,month){return new Date(Number(year),Number(month),0).getDate()}
function calendarRange(year,periodType,slot){const y=Number(year);if(periodType==='month'){const m=Number(slot)||1;return {from:isoDate(y,m,1),to:isoDate(y,m,daysInMonth(y,m))}}if(periodType==='quarter'){const q=Number(slot)||1,start=(q-1)*3+1,end=start+2;return {from:isoDate(y,start,1),to:isoDate(y,end,daysInMonth(y,end))}}if(periodType==='half'){const h=Number(slot)||1,start=h===1?1:7,end=h===1?6:12;return {from:isoDate(y,start,1),to:isoDate(y,end,daysInMonth(y,end))}}return {from:isoDate(y,1,1),to:isoDate(y,12,31)}}
function periodSlotOptions(type,en){if(type==='month')return (en?MONTHS_EN:MONTHS_EL).map((label,index)=>[String(index+1),label]);if(type==='quarter')return [['1','Q1'],['2','Q2'],['3','Q3'],['4','Q4']];if(type==='half')return [['1',en?'1st half':'Α΄ εξάμηνο'],['2',en?'2nd half':'Β΄ εξάμηνο']];return []}

function AnalysisSelect({label,value,onChange,children}){return <label className="analysis-filter-field"><span>{label}</span><select value={value} onChange={onChange}>{children}</select></label>}
// KPI tile: [label, value, hint, tone] — tone is good / warning / danger.
const KPI_TONES=new Set(['good','warning','danger'])
function KpiStrip({rows}){return <div className="analysis-kpis">{rows.map(([label,value,hint,tone])=><article key={label} className={KPI_TONES.has(tone)?`kpi-${tone}`:''}><span>{label}</span><strong>{value}</strong>{hint&&hint!=='—'&&<small>{hint}</small>}</article>)}</div>}
// Months without records are shown as 0 so the time axis stays evenly spaced.
function continuousMonths(points=[]){if(points.length<2)return points;const values=new Map(points);const [fy,fm]=points[0][0].split('-').map(Number),[ly,lm]=points[points.length-1][0].split('-').map(Number);const out=[];for(let y=fy,m=fm;y<ly||(y===ly&&m<=lm);m===12?(y++,m=1):m++){const key=`${y}-${String(m).padStart(2,'0')}`;out.push([key,values.get(key)??0])}return out}
function SectionCharts({charts,en}){return <div className="analysis-chart-grid">{charts.map(chart=><ChartCard key={chart.title} wide={chart.wide} title={chart.title} subtitle={chart.subtitle}>{chart.type==='trend'?<TrendChart points={continuousMonths(chart.points)} en={en} label={chart.title}/>:chart.type==='donut'?<DonutChart rows={chart.rows} en={en} centerLabel={chart.center}/>:chart.type==='rate'?<BarList rows={chart.rows} en={en} scale={100} suffix="%" max={12}/>:<BarList rows={chart.rows} en={en} max={12}/>}</ChartCard>)}</div>}
const chartLanguage=tx=>tx('el','en')==='en'
function MetricBars({rows,tx}){return <BarList rows={rows} en={chartLanguage(tx)} max={12}/>}
function MicrobiologyDistribution({details,tx}){const en=chartLanguage(tx);return <div className="analysis-chart-grid"><ChartCard wide title={tx('Τάση θετικών αποτελεσμάτων','Positive-results trend')} subtitle={tx('Θετικά μικροβιολογικά αποτελέσματα ανά μήνα · περάστε το ποντίκι για τιμές.','Positive microbiology results by month · hover for values.')}><TrendChart points={details?.monthly||[]} en={en} label={tx('Τάση θετικών αποτελεσμάτων','Positive-results trend')}/></ChartCard><ChartCard title={tx('Κατανομή ανά τμήμα','Distribution by department')} subtitle={tx('Θετικά μικροβιολογικά αποτελέσματα','Positive microbiology results')}><BarList rows={details?.byDepartment||[]} en={en}/></ChartCard><ChartCard title={tx('Κατηγορίες αντοχής','Resistance classes')} subtitle={tx('Μερίδιο MDR / XDR / PDR στα θετικά αποτελέσματα.','Share of MDR / XDR / PDR among positive results.')}><DonutChart rows={details?.resistance||[]} en={en} centerLabel={tx('στελέχη','isolates')}/></ChartCard></div>}
// The detailed line list every other microbiology chart on this page only
// summarizes: one row per distinct (organism, resistance, department,
// source, infection site) combination actually seen — this is what answers
// "which microbe, in which department, from which specimen and infection
// site" rather than independent one-dimensional breakdowns that can't be
// cross-referenced.
function NationalRowsTable({rows,tx,emptyText}){
  const columns=[
    {key:'organism',label:tx('Μικροοργανισμός','Organism')},
    {key:'resistance',label:tx('Ανθεκτικότητα','Resistance')},
    {key:'department',label:tx('Τμήμα','Department')},
    {key:'site',label:tx('Σημείο λοίμωξης','Infection site')},
    {key:'source',label:tx('Λεπτομέρεια δείγματος','Specimen detail')},
    {key:'count',label:tx('Πλήθος','Count')},
    {key:'lastDate',label:tx('Τελευταία καταγραφή','Last recorded')},
  ]
  return <RegistryTable columns={columns} rows={rows||[]} rowKey={(row,index)=>row.join('|')||index} emptyTitle={emptyText} renderRow={([organism,resistanceClass,department,source,count,lastDate,sampleType])=><>
    <td>{organism}</td>
    <td>{resistanceClass&&resistanceClass!=='—'?<span className="status-badge danger">{resistanceClass}</span>:'—'}</td>
    <td>{department}</td>
    <td>{siteLabel(sampleType,tx)}</td>
    <td>{source}</td>
    <td>{count}</td>
    <td>{fmtDate(lastDate)}</td>
  </>}/>
}
function exportNationalRowsCsv(rows,tx,filename){
  const headers=[tx('Μικροοργανισμός','Organism'),tx('Ανθεκτικότητα','Resistance'),tx('Τμήμα','Department'),tx('Σημείο λοίμωξης','Infection site'),tx('Λεπτομέρεια δείγματος','Specimen detail'),tx('Πλήθος','Count'),tx('Τελευταία καταγραφή','Last recorded')]
  const csvRows=(rows||[]).map(([organism,resistanceClass,department,source,count,lastDate,sampleType])=>[organism,resistanceClass,department,siteLabel(sampleType,tx),source,count,fmtDate(lastDate)])
  downloadCsv(`${filename}.csv`,headers,csvRows)
}
function ExportCsvButton({rows,tx,filename}){return <IconButton size="sm" disabled={!rows?.length} label={tx('Λήψη CSV','Download CSV')} onClick={()=>exportNationalRowsCsv(rows,tx,filename)}><Download size={14}/></IconButton>}
// Outbreak/cluster early-warning signal (platform review roadmap, P2):
// same organism, same department, within a rolling window — reuses the
// analysis-signal-card/analysis-signal-grid styling the load-error card
// already established for this page, so a cluster reads as an alert
// rather than another neutral chart.
function ClusterAlerts({clusters,tx}){
  if(!clusters?.length)return null
  return <article className="analysis-signal-card"><header><div><ShieldAlert size={18}/><div><strong>{tx('Πιθανές συρροές λοιμώξεων','Possible infection clusters')}</strong><span>{tx('Ίδιος μικροοργανισμός στο ίδιο τμήμα μέσα σε στενό χρονικό διάστημα — ενδεικτικό σήμα επιτήρησης, δεν αποτελεί επιβεβαιωμένη επιδημική έξαρση.','Same organism in the same department within a short time span — a surveillance signal, not a confirmed outbreak.')}</span></div></div></header><div className="analysis-signal-grid">{clusters.slice(0,6).map((cluster,index)=><div key={index} className={cluster.resistanceLabels?.length?'critical':'warning'}><strong>{cluster.organism}</strong><span>{cluster.department} · {cluster.count} {tx('περιστατικά σε','cases in')} {cluster.windowDays} {tx('ημέρες','days')}{cluster.resistanceLabels?.length?` · ${cluster.resistanceLabels.join(', ')}`:''}</span><small>{fmtDate(cluster.firstDate)} → {fmtDate(cluster.lastDate)}</small></div>)}</div></article>
}
function NationalSurveillance({details,clusters,tx}){const nationalRows=details?.nationalRows||[];return <><ClusterAlerts clusters={clusters} tx={tx}/><MicrobiologyDistribution details={details} tx={tx}/><div className="analysis-chart-grid"><article className="analysis-chart-card analysis-wide-card"><header><div><strong>{tx('Μικροοργανισμοί','Microorganisms')}</strong><span>{tx('Συχνότερα θετικά ευρήματα','Most frequent positive findings')}</span></div></header><MetricBars rows={details?.microorganisms||[]} tx={tx}/></article></div><div className="analysis-chart-grid"><article className="analysis-chart-card"><header><div><strong>{tx('Σημείο λοίμωξης','Infection site')}</strong><span>{tx('Κατανομή ανά τύπο δείγματος','Distribution by specimen type')}</span></div></header><DonutChart rows={(details?.bySite||[]).filter(([value])=>CLINICAL_SITES.includes(value)).map(([value,count])=>[siteLabel(value,tx),count])} en={chartLanguage(tx)} centerLabel={tx('δείγματα','samples')}/></article><article className="analysis-chart-card"><header><div><strong>{tx('Λεπτομέρεια δείγματος','Specimen detail')}</strong><span>{tx('Κατανομή των θετικών ευρημάτων','Distribution of positive findings')}</span></div></header><MetricBars rows={details?.bySource||[]} tx={tx}/></article></div><article className="analysis-chart-card analysis-wide-card"><header><div><strong>{tx('Μικροοργανισμοί ανά σημείο λοίμωξης','Organisms by infection site')}</strong><span>{tx('Ποιος μικροοργανισμός εμφανίζεται σε ποιο σημείο λοίμωξης.','Which organism appears at which infection site.')}</span></div></header><MetricBars rows={organismBySiteRows(nationalRows,tx)} tx={tx}/></article><article className="analysis-chart-card analysis-wide-card"><header><div><strong>{tx('Μικροοργανισμοί ανά τμήμα και σημείο λοίμωξης','Organisms by department and infection site')}</strong><span>{tx('Αναλυτική καταγραφή ανά μικροοργανισμό, τμήμα, σημείο λοίμωξης και δείγμα.','Detailed line list by organism, department, infection site and specimen.')}</span></div><ExportCsvButton rows={nationalRows} tx={tx} filename={tx('μικροοργανισμοί_εθνική_επιτήρηση','organisms_national_surveillance')}/></header><NationalRowsTable rows={nationalRows} tx={tx} emptyText={tx('Δεν υπάρχουν καταγραφές για το ενεργό εύρος.','No records for the active scope.')}/></article></>}
// AMR tab: the resistant subset of the same line list, alongside the
// per-organism tested/resistant KPI rows already shown above it.
function AmrRegister({details,tx}){const resistantRows=(details?.nationalRows||[]).filter(([,resistanceClass])=>['MDR','XDR','PDR'].includes(resistanceClass));return <article className="analysis-chart-card analysis-wide-card"><header><div><strong>{tx('Ανθεκτικά ευρήματα ανά τμήμα και σημείο λοίμωξης','Resistant findings by department and infection site')}</strong><span>{tx('MDR/XDR/PDR απομονώματα του ενεργού εύρους.','MDR/XDR/PDR isolates in the active scope.')}</span></div><ExportCsvButton rows={resistantRows} tx={tx} filename={tx('ανθεκτικά_ευρήματα_amr','amr_resistant_findings')}/></header><NationalRowsTable rows={resistantRows} tx={tx} emptyText={tx('Δεν υπάρχουν ανθεκτικά ευρήματα για το ενεργό εύρος.','No resistant findings for the active scope.')}/></article>}
function DomainView({rows,micro,tab,tx,en}){
 const share=numericRows(rows).filter(([,value])=>value>0)
 const monthly=micro?.monthly||[]
 return <div className="analysis-chart-grid">
  {tab==='overview'&&monthly.length>1&&<ChartCard wide title={tx('Θετικές καλλιέργειες ανά μήνα','Positive cultures by month')} subtitle={tx('Επικυρωμένα θετικά αποτελέσματα του ενεργού εύρους · περάστε το ποντίκι πάνω από το γράφημα για τιμές.','Validated positive results in the active scope · hover the chart for values.')}><TrendChart points={monthly} en={en} label={tx('Θετικές καλλιέργειες ανά μήνα','Positive cultures by month')}/></ChartCard>}
  <ChartCard title={tx('Κατανομή τρέχουσας περιόδου','Current-period distribution')} subtitle={tx('Καταγραφές της επιλεγμένης ενότητας.','Records from the selected area.')}><BarList rows={rows} en={en}/></ChartCard>
  {share.length>1&&<ChartCard title={tx('Μερίδιο επί του συνόλου','Share of total')} subtitle={tx('Πώς μοιράζονται οι καταγραφές της ενότητας.','How the section’s records are split.')}><DonutChart rows={share} en={en} centerLabel={tx('σύνολο','total')}/></ChartCard>}
 </div>}
function ScopeComparison({title,subtitle,currentRows,compareRows,currentLabel,compareLabel,tx}){if(!compareRows?.length)return null;const comparison=new Map(compareRows.map(row=>[row[0],row[1]]));return <article className="analysis-chart-card analysis-wide-card"><header><div><strong>{title}</strong><span>{subtitle}</span></div></header><div className="analysis-comparison-table"><div className="head"><span>{tx('Δείκτης','Indicator')}</span><span>{currentLabel}</span><span>{compareLabel}</span><span>{tx('Διαφορά','Difference')}</span></div>{currentRows.map(([label,current])=>{const previous=comparison.get(label)??0;const diff=current==='—'||previous==='—'?'—':numberValue(current)-numberValue(previous);return <div key={label}><span>{label}</span><span>{current}</span><span>{previous}</span><span>{typeof diff==='number'&&diff>0?'+':''}{diff}</span></div>})}</div></article>}

function buildProductionRows(tab,snapshot,tx){const summary=snapshot?.summary||{},micro=snapshot?.microbiology||{};const antimicrobial=summary.antimicrobial&&typeof summary.antimicrobial==='object'?summary.antimicrobial:null;const antimicrobialRows=antimicrobial?[[tx('Αντιμικροβιακές αγωγές','Antimicrobial therapies'),antimicrobial.total??0,'—','up'],[tx('Σε αναμονή έγκρισης','Pending approval'),antimicrobial.pending??0,'—','up'],[tx('Χορηγήσεις','Administrations recorded'),antimicrobial.administrations??0,'—','up']]:[[tx('Αντιμικροβιακές αγωγές','Antimicrobial therapies'),'—','—','up']];const amrRows=(snapshot?.amrSusceptibility||[]).length?snapshot.amrSusceptibility.map(([organism,tested,resistant])=>[organism,`${resistant}/${tested}`,'—','down']):[[tx('Δεν υπάρχουν δεδομένα ευαισθησίας','No susceptibility data'),'—','—','up']];const map={overview:[[tx('Επιτήρηση','Surveillance'),summary.surveillance??0,'—','up'],[tx('Εργαστήριο','Laboratory'),summary.laboratory??0,'—','up'],[tx('Πρόληψη','Prevention'),summary.prevention??0,'—','up'],[tx('Έλεγχοι','Controls'),summary.controls??0,'—','up'],[tx('Ποιότητα','Quality'),summary.quality??0,'—','up'],[tx('Εκπαίδευση','Training'),summary.training??0,'—','up']],national:[[tx('Θετικές καλλιέργειες','Positive cultures'),micro.totalPositive??0,'—','up'],['MDR/XDR/PDR',(micro.resistance||[]).reduce((sum,row)=>sum+Number(row[1]||0),0),'—','down'],[tx('Τμήματα με ≥1 εύρημα','Departments with ≥1 finding'),micro.departmentCount??0,'—','up'],[tx('Κρίσιμα αποτελέσματα','Critical results'),micro.totalCritical??0,'—','down']],surveillance:[[tx('Καταγραφές επιτήρησης','Surveillance records'),summary.surveillance??0,'—','up']],laboratory:[[tx('Εργαστηριακές καταγραφές','Laboratory records'),summary.laboratory??0,'—','up'],[tx('Θετικές καλλιέργειες','Positive cultures'),micro.totalPositive??0,'—','up'],[tx('Κρίσιμα αποτελέσματα','Critical results'),micro.totalCritical??0,'—','down']],amr:amrRows,antimicrobials:antimicrobialRows,prevention:[[tx('Πρόληψη','Prevention'),summary.prevention??0,'—','up'],[tx('Υγιεινή χεριών','Hand hygiene'),summary.handHygiene??0,'—','up'],[tx('Απόβλητα','Waste'),summary.waste??0,'—','up']],hand:[[tx('Υγιεινή χεριών','Hand hygiene'),summary.handHygiene??0,'—','up']],controls:[[tx('Έλεγχοι','Controls'),summary.controls??0,'—','up']],occupational:[[tx('Επισκέψεις εργαζομένων','Employee visits'),summary.occupationalHealth??'—','—','up']],quality:[[tx('Ποιότητα','Quality'),summary.quality??0,'—','up']],training:[[tx('Εκπαίδευση','Training'),summary.training??0,'—','up']],governance:[[tx('Έγγραφα','Documents'),summary.documents??0,'—','up'],[tx('Επιτροπές','Committees'),summary.committees??'—','—','up']]};return map[tab]||map.overview}

export function AnalysisPage({platform=false,organizations=EMPTY_ORGANIZATIONS,forceDemo=false}){
 const {tenant,role,isDemo:contextIsDemo}=useTenant();const isDemo=contextIsDemo||forceDemo;const {language,t}=useLanguage();const {notifyError}=useFeedback();const location=useLocation();const navigate=useNavigate();const en=language==='en';const tx=(elText,enText)=>en?enText:elText
 const requestRef=useRef(0);const reportRef=useRef(null);const currentYear=new Date().getFullYear();const yearOptions=useMemo(()=>Array.from({length:7},(_,i)=>currentYear-i),[currentYear])
 const [tab,setTab]=useState('overview'),[printOpen,setPrintOpen]=useState(false),[printTarget,setPrintTarget]=useState(''),[printMode,setPrintMode]=useState('print'),[exportingPdf,setExportingPdf]=useState(false),[year,setYear]=useState(String(currentYear)),[periodType,setPeriodType]=useState('year'),[periodSlot,setPeriodSlot]=useState('1'),[compareYear,setCompareYear]=useState(''),[org,setOrg]=useState(platform?hashOrganization(location.hash):'all'),[region,setRegion]=useState('all'),[department,setDepartment]=useState('all'),[ownerCompareMode,setOwnerCompareMode]=useState('none'),[compareHospital,setCompareHospital]=useState(''),[compareRegion,setCompareRegion]=useState(''),[snapshot,setSnapshot]=useState(null),[yearSnapshot,setYearSnapshot]=useState(null),[ownerSnapshot,setOwnerSnapshot]=useState(null),[loading,setLoading]=useState(false),[loadError,setLoadError]=useState('')
 // Short screens (13" notebooks): filters collapse to a one-line summary so the results keep the height.
 const [compactFilters,setCompactFilters]=useState(()=>typeof window!=='undefined'&&Boolean(window.matchMedia?.(COMPACT_QUERY).matches)),[filtersOpen,setFiltersOpen]=useState(false)
 useEffect(()=>{const media=window.matchMedia?.(COMPACT_QUERY);if(!media)return;const update=()=>setCompactFilters(media.matches);media.addEventListener?.('change',update);return()=>media.removeEventListener?.('change',update)},[])
 const allowed=[ROLES.PLATFORM_OWNER,ROLES.HOSPITAL_ADMIN,ROLES.INFECTION_CONTROL_LEAD,ROLES.DEMO].includes(role)
 const range=useMemo(()=>calendarRange(year,periodType,periodSlot),[year,periodType,periodSlot]);const comparisonRange=useMemo(()=>compareYear?calendarRange(compareYear,periodType,periodSlot):null,[compareYear,periodType,periodSlot]);const returnTo=location.state?.returnTo;const productionScope=!isDemo&&(platform||Boolean(tenant?.id))
 const regions=useMemo(()=>[...new Set(organizations.map(item=>item.region).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'el')),[organizations]);const regionOrganizationIds=useMemo(()=>region==='all'?EMPTY_ORGANIZATIONS:organizations.filter(item=>item.region===region).map(item=>item.id),[organizations,region]);const mainScope=useMemo(()=>platform?(org!=='all'?{organizationId:org}:region!=='all'?{organizationIds:regionOrganizationIds}:{organizationId:''}):{organizationId:tenant?.id||''},[platform,org,region,regionOrganizationIds,tenant?.id]);const canFilterDepartment=!platform||org!=='all';const effectiveDepartment=canFilterDepartment&&department!=='all'?department:''
 const demoSnapshot=isDemo?{...collectAnalysisDemoSnapshot(),domains:collectDemoDomainMetrics(range,en)}:null
 const micro=isDemo?(demoSnapshot?.microbiology||{}):(snapshot?.microbiology||{});const clusters=isDemo?(demoSnapshot?.clusters||[]):(snapshot?.clusters||[]);const departmentOptions=(micro.departments||[]).map(item=>typeof item==='string'?{id:item,name:item}:item).filter(item=>!platform||org==='all'||!item.organizationId||item.organizationId===org)
 const ownerCompareScope=useMemo(()=>{if(!platform||ownerCompareMode==='none')return null;if(ownerCompareMode==='hospital'&&compareHospital)return {organizationId:compareHospital,label:organizations.find(item=>item.id===compareHospital)?.name||(en?'Hospital':'Νοσοκομείο')};if(ownerCompareMode==='region'&&compareRegion){const ids=organizations.filter(item=>item.region===compareRegion).map(item=>item.id);return ids.length?{organizationIds:ids,label:compareRegion}:null}return null},[platform,ownerCompareMode,compareHospital,compareRegion,organizations,en])
 useEffect(()=>{if(periodType==='year')setPeriodSlot('1');else if(periodType==='month'&&Number(periodSlot)>12)setPeriodSlot('1');else if(periodType==='quarter'&&Number(periodSlot)>4)setPeriodSlot('1');else if(periodType==='half'&&Number(periodSlot)>2)setPeriodSlot('1')},[periodType,periodSlot])
 useEffect(()=>{if(org!=='all'){const selected=organizations.find(item=>item.id===org);if(selected?.region)setRegion(selected.region)}setDepartment('all')},[org,organizations])
 useEffect(()=>{if(!productionScope)return;const request=++requestRef.current;setLoading(true);setLoadError('');const args={...mainScope,...range,departmentId:effectiveDepartment};const yearArgs=compareYear?{...mainScope,...comparisonRange,departmentId:effectiveDepartment}:null;const ownerArgs=ownerCompareScope?{...ownerCompareScope,...range,departmentId:''}:null;Promise.all([loadAnalysisSnapshot(args),yearArgs?loadAnalysisSnapshot(yearArgs):Promise.resolve(null),ownerArgs?loadAnalysisSnapshot(ownerArgs):Promise.resolve(null)]).then(([main,yearCompare,ownerCompare])=>{if(request===requestRef.current){setSnapshot(main);setYearSnapshot(yearCompare);setOwnerSnapshot(ownerCompare)}}).catch(error=>{if(request===requestRef.current){setSnapshot(null);setYearSnapshot(null);setOwnerSnapshot(null);setLoadError(error?.message||'ANALYTICS_LOAD_FAILED')}}).finally(()=>{if(request===requestRef.current)setLoading(false)});return()=>{if(request===requestRef.current)requestRef.current+=1}},[productionScope,mainScope,range,comparisonRange,compareYear,effectiveDepartment,ownerCompareScope])
 const activeSnapshot=isDemo?demoSnapshot:snapshot;const model=tab==='national'||tab==='amr'?null:buildSectionModel(tab,activeSnapshot,tx,t);const rowsFor=snap=>{const m=tab==='national'||tab==='amr'?null:buildSectionModel(tab,snap,tx,t);return m?m.kpis:buildProductionRows(tab,snap,tx)};const rows=model?model.kpis:buildProductionRows(tab,activeSnapshot,tx);const yearRows=compareYear&&!isDemo&&yearSnapshot?rowsFor(yearSnapshot):[];const ownerRows=ownerSnapshot?rowsFor(ownerSnapshot):[];const currentTitle=[...TABS,REPORTING_TAB].find(x=>x[0]===tab)?.[en?2:1];const slotOptions=periodSlotOptions(periodType,en);const currentScopeLabel=platform?(org!=='all'?(organizations.find(item=>item.id===org)?.name||tx('Νοσοκομείο','Hospital')):region!=='all'?region:tx('Όλη η πλατφόρμα','Whole platform')):(tenant?.name||tx('Οργανισμός','Organization'))
 function printSection(sectionId){
  setPrintOpen(false)
  setPrintMode('print')
  setPrintTarget(sectionId)
  if(sectionId!==tab)setTab(sectionId)
 }
 function exportSectionPdf(sectionId){
  setPrintOpen(false)
  setPrintMode('pdf')
  setPrintTarget(sectionId)
  if(sectionId!==tab)setTab(sectionId)
 }
 useEffect(()=>{
  if(!printTarget||printTarget!==tab||loading||!reportRef.current)return
  if(printMode==='pdf'){
   const timer=window.setTimeout(()=>{
    const sectionTitle=TABS.find(x=>x[0]===printTarget)?.[en?2:1]||printTarget
    setExportingPdf(true)
    exportElementAsPdf({element:reportRef.current,filename:`${tx('Ανάλυση','Analysis')}_${sectionTitle}_${currentScopeLabel}_${range.from}_${range.to}`})
     .catch(error=>notifyError(error,'export',{operation:'analysis_pdf_export'}))
     .finally(()=>{setExportingPdf(false);setPrintTarget('')})
   },250)
   return()=>window.clearTimeout(timer)
  }
  const timer=window.setTimeout(()=>{
   const report=reportRef.current
   const frame=document.createElement('iframe')
   frame.setAttribute('aria-hidden','true')
   frame.style.position='fixed';frame.style.left='-10000px';frame.style.top='0';frame.style.width='1200px';frame.style.height='900px';frame.style.border='0';frame.style.visibility='hidden'
   document.body.appendChild(frame)
   const doc=frame.contentDocument
   const styleLinks=[...document.querySelectorAll('link[rel="stylesheet"]')].map(link=>'<link rel="stylesheet" href="'+link.href+'">').join('')
   const inlineStyles=[...document.querySelectorAll('style')].map(style=>style.outerHTML).join('')
   doc.open()
   doc.write('<!doctype html><html><head><meta charset="utf-8"><title>'+tx('Αναφορά Limoxis Observer','Limoxis Observer Report')+'</title>'+styleLinks+inlineStyles+'<style>@page{size:A4 landscape;margin:10mm}html,body{height:auto!important;overflow:visible!important;background:#fff!important}body{margin:0!important;padding:0!important}.analysis-report{display:block!important;position:static!important;width:100%!important;max-width:none!important;height:auto!important;overflow:visible!important;margin:0!important;padding:0!important;background:#fff!important}.analysis-kpis{grid-template-columns:repeat(3,minmax(0,1fr))!important}.analysis-chart-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.analysis-chart-card,.analysis-kpis article{break-inside:avoid!important;page-break-inside:avoid!important}</style></head><body><main class="platform-analysis-page analysis-print-frame">'+report.outerHTML+'</main></body></html>')
   doc.close()
   const printFrame=()=>{try{frame.contentWindow.focus();frame.contentWindow.print()}finally{window.setTimeout(()=>frame.remove(),1500);setPrintTarget('')}}
   const waitForPrintAssets=async()=>{const links=[...doc.querySelectorAll('link[rel="stylesheet"]')];await Promise.all(links.map(link=>link.sheet?Promise.resolve():new Promise(resolve=>{link.onload=resolve;link.onerror=resolve})));if(doc.fonts?.ready)await doc.fonts.ready;await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));printFrame()}
   window.setTimeout(waitForPrintAssets,120)
  },250)
  return()=>window.clearTimeout(timer)
 },[printTarget,printMode,tab,loading,snapshot,yearSnapshot,ownerSnapshot])
 const filterSummary=[year,periodType==='year'?tx('Ολόκληρο έτος','Full year'):(slotOptions.find(([value])=>value===periodSlot)?.[1]||''),platform&&(region==='all'?tx('Όλες οι περιφέρειες','All regions'):region),platform&&(org==='all'?tx('Όλα τα νοσοκομεία','All hospitals'):organizations.find(item=>item.id===org)?.name),canFilterDepartment&&(department==='all'?tx('Όλα τα τμήματα','All departments'):departmentOptions.find(item=>item.id===department)?.name),compareYear&&`${tx('Σύγκριση με','Compared with')} ${compareYear}`].filter(Boolean)
 if(!allowed)return <div className="empty-state"><strong>{tx('Δεν υπάρχει πρόσβαση στην Ανάλυση.','Analytics access is not available.')}</strong></div>
 return <div className={`analysis-workspace${platform?' platform-analysis-page':''}`} style={{'--lo-layout-page-top':'10px'}}>
  <div className="analysis-header" style={{minHeight:'72px'}}><div className="analysis-heading-row">{returnTo&&!platform&&<BackButton onClick={()=>navigate(returnTo)} label={tx('Πίσω','Back')}/>}<div><span className="eyebrow">{tx('ΑΝΑΛΥΣΗ & ΑΝΑΦΟΡΕΣ','ANALYTICS & REPORTING')}</span><h1>{tx('Ανάλυση','Analytics')}</h1><p>{platform?tx('Συγκεντρωτική εικόνα και συγκρίσεις ανά νοσοκομείο ή περιφέρεια.','Aggregate view and comparisons by hospital or region.'):(tenant?.name||tx('Οργανισμός','Organization'))}</p></div></div><div className="analysis-actions"><div className="analysis-print-menu"><button type="button" className="analysis-print-trigger" aria-haspopup="menu" aria-expanded={printOpen} onClick={()=>setPrintOpen(value=>!value)}><Printer size={16}/><span>{tx('Εκτύπωση','Print')}</span><ChevronDown size={14}/></button>{printOpen&&<div className="analysis-print-popover" role="menu"><div className="analysis-print-popover-head"><strong>{tx('Επιλογή αναφοράς','Choose report')}</strong><span>{exportingPdf?tx('Δημιουργία PDF…','Generating PDF…'):tx('Εκτύπωση ή λήψη PDF με τα ενεργά φίλτρα.','Print or download a PDF with the active filters.')}</span></div><div className="analysis-print-options">{TABS.map(([id,elLabel,enLabel,Icon])=><div className="analysis-print-option-row" key={id}><button type="button" role="menuitem" disabled={exportingPdf} onClick={()=>printSection(id)}><span className="analysis-print-option-label"><Icon size={15}/>{en?enLabel:elLabel}</span>{tab===id&&<Check size={14}/>}</button><button type="button" role="menuitem" className="analysis-print-option-pdf" disabled={exportingPdf} title={tx('Λήψη PDF','Download PDF')} aria-label={tx('Λήψη PDF','Download PDF')} onClick={event=>{event.stopPropagation();exportSectionPdf(id)}}><Download size={14}/></button></div>)}</div></div>}</div></div></div>
  <div className="analysis-sticky">{compactFilters&&!filtersOpen?<div className="analysis-filter-summary"><div className="analysis-filter-chips">{filterSummary.map(item=><span key={item}>{item}</span>)}</div><button type="button" className="analysis-filter-toggle" onClick={()=>setFiltersOpen(true)} aria-expanded="false"><SlidersHorizontal size={15}/>{tx('Φίλτρα','Filters')}</button></div>:<div className="analysis-filter-toolbar">
   <section className="analysis-filter-group analysis-filter-time"><div className="analysis-filter-group-title">{tx('Χρονικό διάστημα','Time period')}</div><div className="analysis-filter-group-fields"><AnalysisSelect label={tx('Έτος','Year')} value={year} onChange={e=>setYear(e.target.value)}>{yearOptions.map(item=><option key={item} value={item}>{item}</option>)}</AnalysisSelect><AnalysisSelect label={tx('Ανάλυση','Breakdown')} value={periodType} onChange={e=>setPeriodType(e.target.value)}><option value="year">{tx('Ολόκληρο έτος','Full year')}</option><option value="month">{tx('Ανά μήνα','By month')}</option><option value="quarter">{tx('Ανά τρίμηνο','By quarter')}</option><option value="half">{tx('Ανά εξάμηνο','By half-year')}</option></AnalysisSelect>{periodType!=='year'&&<AnalysisSelect label={tx('Επιλογή περιόδου','Period')} value={periodSlot} onChange={e=>setPeriodSlot(e.target.value)}>{slotOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</AnalysisSelect>}</div></section>
   <section className="analysis-filter-group analysis-filter-scope"><div className="analysis-filter-group-title">{tx('Εύρος','Scope')}</div><div className="analysis-filter-group-fields">{platform&&<AnalysisSelect label={tx('Περιφέρεια','Region')} value={region} onChange={e=>{setRegion(e.target.value);setOrg('all')}}><option value="all">{tx('Όλες οι περιφέρειες','All regions')}</option>{regions.map(item=><option key={item} value={item}>{item}</option>)}</AnalysisSelect>}{platform&&<AnalysisSelect label={tx('Νοσοκομείο','Hospital')} value={org} onChange={e=>setOrg(e.target.value)}><option value="all">{region==='all'?tx('Όλα τα νοσοκομεία','All hospitals'):tx('Όλη η περιφέρεια','Whole region')}</option>{organizations.filter(item=>region==='all'||item.region===region).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</AnalysisSelect>}{canFilterDepartment&&<AnalysisSelect label={tx('Τμήμα','Department')} value={department} onChange={e=>setDepartment(e.target.value)}><option value="all">{tx('Όλα τα τμήματα','All departments')}</option>{departmentOptions.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</AnalysisSelect>}</div></section>
   <section className={`analysis-filter-group analysis-filter-compare${isDemo?' analysis-filter-group-placeholder':''}`}>{!isDemo&&<><div className="analysis-filter-group-title">{tx('Σύγκριση','Comparison')}</div><div className="analysis-filter-group-fields"><AnalysisSelect label={tx('Με έτος','Compare year')} value={compareYear} onChange={e=>setCompareYear(e.target.value)}><option value="">{tx('Χωρίς σύγκριση','No comparison')}</option>{yearOptions.filter(item=>String(item)!==year).map(item=><option key={item} value={item}>{item}</option>)}</AnalysisSelect>{platform&&<AnalysisSelect label={tx('Τύπος σύγκρισης','Comparison type')} value={ownerCompareMode} onChange={e=>{setOwnerCompareMode(e.target.value);setCompareHospital('');setCompareRegion('')}}><option value="none">{tx('Καμία πρόσθετη','None')}</option><option value="hospital">{tx('Νοσοκομείο','Hospital')}</option><option value="region">{tx('Περιφέρεια','Region')}</option></AnalysisSelect>}{platform&&ownerCompareMode==='hospital'&&<AnalysisSelect label={tx('Με νοσοκομείο','Compare with')} value={compareHospital} onChange={e=>setCompareHospital(e.target.value)}><option value="">{tx('Επιλέξτε','Select')}</option>{organizations.filter(item=>item.id!==org).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</AnalysisSelect>}{platform&&ownerCompareMode==='region'&&<AnalysisSelect label={tx('Με περιφέρεια','Compare with')} value={compareRegion} onChange={e=>setCompareRegion(e.target.value)}><option value="">{tx('Επιλέξτε','Select')}</option>{regions.filter(item=>item!==region).map(item=><option key={item} value={item}>{item}</option>)}</AnalysisSelect>}</div></>}</section>
   {compactFilters&&<button type="button" className="analysis-filter-toggle analysis-filter-close" onClick={()=>setFiltersOpen(false)} aria-expanded="true"><ChevronUp size={15}/>{tx('Σύμπτυξη','Collapse')}</button>}
  </div>}</div>
  <div className="analysis-tabs entity-record-tabs surface" role="tablist" aria-label={tx('Ενότητες ανάλυσης','Analytics sections')}>{(platform?TABS:[...TABS,REPORTING_TAB]).map(([id,elLabel,enLabel,Icon])=><button type="button" role="tab" aria-selected={tab===id} key={id} title={en?enLabel:elLabel} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={15}/><span>{en?enLabel:elLabel}</span></button>)}</div>
  <div className="analysis-scroll" tabIndex={0} role="region" aria-label={currentTitle}><section ref={reportRef} className="analysis-report"><div className="analysis-section-title"><div><h2>{currentTitle}</h2><p>{isDemo?tx('Συνθετικά δεδομένα αποκλειστικά για το Demo περιβάλλον.','Synthetic data for the Demo environment only.'):tx('Πραγματικά δεδομένα του επιλεγμένου ημερολογιακού εύρους.','Real data from the selected calendar scope.')}</p></div><div className="analysis-report-badges">{platform&&<span className="status-badge info">{tx('ΕΥΡΟΣ ΠΛΑΤΦΟΡΜΑΣ','OWNER SCOPE')}</span>}{isDemo&&<span className="status-badge temporary">{tx('ΔΕΔΟΜΕΝΑ DEMO','DEMO DATA')}</span>}</div></div>
   {tab==='reporting'&&!platform?<ReportingPanel tenant={tenant} isDemo={isDemo} year={year} tx={tx} en={en}/>:loading?<div className="analysis-chart-empty">{tx('Φόρτωση ανάλυσης…','Loading analytics…')}</div>:loadError?<div className="analysis-signal-card"><header><div><ShieldAlert size={18}/><div><strong>{tx('Δεν ήταν δυνατή η φόρτωση της ανάλυσης.','Analytics could not be loaded.')}</strong><span>{loadError}</span></div></div></header></div>:<><KpiStrip rows={rows}/>{compareYear&&yearRows.length>0&&<ScopeComparison title={tx('Σύγκριση ετών','Year comparison')} subtitle={tx('Ίδια ακριβώς περίοδος και ίδιο εύρος.','Exactly the same period and scope.')} currentRows={rows} compareRows={yearRows} currentLabel={year} compareLabel={compareYear} tx={tx}/>} {platform&&ownerSnapshot&&ownerCompareScope&&<ScopeComparison title={ownerCompareMode==='region'?tx('Σύγκριση περιφερειών','Region comparison'):tx('Σύγκριση νοσοκομείων','Hospital comparison')} subtitle={tx('Ίδια περίοδος και ίδια ενότητα ανάλυσης.','Same period and analytics section.')} currentRows={rows} compareRows={ownerRows} currentLabel={currentScopeLabel} compareLabel={ownerCompareScope.label} tx={tx}/>} {tab==='national'?<NationalSurveillance details={micro} clusters={clusters} tx={tx}/>:tab==='amr'?<AmrRegister details={micro} tx={tx}/>:tab==='laboratory'?<MicrobiologyDistribution details={micro} tx={tx}/>:model?.charts?<SectionCharts charts={model.charts} en={en}/>:<DomainView rows={rows} micro={micro} tab={tab} tx={tx} en={en}/>}<article className="analysis-chart-card analysis-wide-card"><header><div><strong>{tx('Πλαίσιο αναφοράς','Report scope')}</strong><span>{tx('Τα φίλτρα εφαρμόζονται σε όλες τις ενότητες της Ανάλυσης.','Filters apply to every Analytics section.')}</span></div></header><div className="analysis-summary-grid"><div><span>{tx('Εύρος','Scope')}</span><strong>{currentScopeLabel}</strong></div><div><span>{tx('Περίοδος','Period')}</span><strong>{fmtDate(range.from)} → {fmtDate(range.to)}</strong></div><div><span>{tx('Τμήμα','Department')}</span><strong>{canFilterDepartment&&department!=='all'?(departmentOptions.find(item=>item.id===department)?.name||department):tx('Όλα τα τμήματα','All departments')}</strong></div><div><span>{tx('Σύγκριση έτους','Year comparison')}</span><strong>{compareYear||'—'}</strong></div></div></article></>}
  </section></div>
 </div>
}
