import { useMemo, useState } from 'react'
import { Download, Printer, TrendingDown, TrendingUp, GitCompareArrows } from 'lucide-react'
import { Button } from '../../design-system/Button'
import { useTenant } from '../../core/tenant/TenantContext'
import { ROLES } from '../../core/permissions/roles'

const TABS=[['overview','Σύνοψη'],['surveillance','Επιτήρηση & HAI'],['laboratory','Μικροβιολογία'],['amr','AMR / MDR-XDR'],['antimicrobials','Αντιμικροβιακά'],['prevention','Πρόληψη'],['hand','Υγιεινή Χεριών'],['controls','Έλεγχοι'],['occupational','Εργαζόμενοι'],['quality','Ποιότητα'],['training','Εκπαίδευση'],['governance','Governance']]
const COLORS=['#2878d0','#28a36a','#7a56c2','#e58a2b','#d95757','#1b9aaa','#d16ba5','#6f8f3d']
const MONTHS=['Ιαν','Φεβ','Μαρ','Απρ','Μάι','Ιουν','Ιουλ','Αυγ','Σεπ','Οκτ','Νοε','Δεκ']
const DEPARTMENTS=['Όλα τα τμήματα','ΜΕΘ','Παθολογική','Χειρουργική','ΤΕΠ','Αιμοκάθαρση']
const KPI={
 overview:[['HAI / 1.000 κλινοημέρες','3,5','-8,2%','down'],['MDR/XDR rate','12,4%','-2,1%','down'],['Υγιεινή χεριών','88%','+4,3%','up'],['DDD / 1.000 κλινοημέρες','58','-5,6%','down'],['Bundle compliance','91%','+3,8%','up'],['Έλεγχοι στην ώρα τους','95%','+2,4%','up']],
 surveillance:[['HAI / 1.000 κλινοημέρες','3,5','-8,2%','down'],['CLABSI / 1.000 CVC-days','1,7','-12,0%','down'],['CAUTI / 1.000 catheter-days','2,1','-5,1%','down'],['SSI','3,5%','-0,7%','down']],
 laboratory:[['Θετικές καλλιέργειες','184','+6,4%','up'],['Critical ≤30′','94%','+3,2%','up'],['MDR/XDR isolates','42','-4,5%','down'],['Median TAT','16 h','-2,0 h','down']],
 amr:[['MDR/XDR rate','12,4%','-2,1%','down'],['Carbapenem resistance','21%','-3,4%','down'],['MRSA','8,2%','-1,2%','down'],['VRE','5,6%','+0,4%','up']],
 antimicrobials:[['DDD / 1.000 κλιν/ρες','58','-5,6%','down'],['Carbapenem DDD','12','-8,3%','down'],['Reserve share','7,4%','-1,1%','down'],['Reviews ≤72h','91%','+4,8%','up']],
 prevention:[['Bundle compliance','91%','+3,8%','up'],['Έγκαιρη απομόνωση','96%','+2,1%','up'],['Waste segregation','93%','+1,7%','up'],['Antiseptic target','89%','+4,0%','up']],
 hand:[['Compliance','88%','+4,3%','up'],['Παρατηρήσεις','1.248','+118','up'],['Glove misuse','7%','-2,0%','down'],['Training coverage','94%','+5,2%','up']],
 controls:[['On-time','95%','+2,4%','up'],['Open deviations','12','-3','down'],['Overdue','5','-4','down'],['Completion','97%','+2,8%','up']],
 occupational:[['Vaccination coverage','86%','+5,1%','up'],['Ιατρικές επισκέψεις','312','+22','up'],['Overdue visits','24','-8','down'],['Follow-up','98%','+1,4%','up']],
 quality:[['CAPA ≤30d','89%','+6,2%','up'],['Open findings','18','-5','down'],['Audits','31','+4','up'],['Docs in-date','96%','+2,2%','up']],
 training:[['Coverage','92%','+7,4%','up'],['Completions','1.034','+126','up'],['Overdue','44','-19','down'],['Pass rate','94%','+3,1%','up']],
 governance:[['Committees active','94%','+2,0%','up'],['Actions closed','87%','+6,3%','up'],['Policies in-date','96%','+1,9%','up'],['Audit completeness','99%','+1,0%','up']]
}
const TRENDS={overview:[4.8,4.6,4.5,4.3,4.2,4.0,4.1,3.9,3.8,3.7,3.6,3.5],surveillance:[4.8,4.2,5.1,4.7,4.4,4.1,3.9,4.0,3.7,3.5,3.4,3.2],laboratory:[48,55,61,58,67,63,70,74,71,78,82,86],amr:[16.8,16.2,15.9,15.4,14.8,14.5,14.2,13.8,13.6,13.1,12.8,12.4],antimicrobials:[68,66,65,63,62,61,60,59,60,58,57,56],prevention:[76,78,79,82,84,85,86,88,89,90,91,93],hand:[71,74,76,79,81,80,83,84,86,85,87,88],controls:[78,82,84,86,85,88,90,91,92,94,95,95],occupational:[70,72,74,76,78,80,82,82,84,84,85,86],quality:[72,75,78,79,81,84,83,87,88,90,91,92],training:[62,65,68,72,75,79,82,84,86,88,90,92],governance:[80,81,82,84,85,86,88,89,90,91,93,94]}
const COMPARE=[['IASO Θεσσαλίας','3,2','88%','58','91%'],['Νοσοκομείο Α','3,8','84%','63','87%'],['Νοσοκομείο Β','4,1','81%','67','85%'],['Νοσοκομείο Γ','3,5','90%','55','93%']]

function LineChart({values}){const max=Math.max(...values),min=Math.min(...values),w=680,h=210,p=24;const pts=values.map((v,i)=>`${p+i*((w-p*2)/(values.length-1))},${h-p-(v-min)/(max-min||1)*(h-p*2)}`).join(' ');return <div className="analysis-line-wrap"><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Τάση περιόδου"><defs><linearGradient id="analysisFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={COLORS[0]} stopOpacity=".24"/><stop offset="1" stopColor={COLORS[0]} stopOpacity=".02"/></linearGradient></defs>{[0,1,2,3].map(i=><line key={i} x1={p} x2={w-p} y1={p+i*(h-p*2)/3} y2={p+i*(h-p*2)/3} className="analysis-grid-line"/>)}<polygon points={`${p},${h-p} ${pts} ${w-p},${h-p}`} fill="url(#analysisFill)"/><polyline points={pts} fill="none" stroke={COLORS[0]} strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/>{values.map((v,i)=>{const [x,y]=pts.split(' ')[i].split(',');return <circle key={i} cx={x} cy={y} r="4" fill="#fff" stroke={COLORS[0]} strokeWidth="3"/>})}</svg><div className="analysis-axis-labels">{MONTHS.map(x=><small key={x}>{x}</small>)}</div></div>}
function GroupBars(){const rows=[['ΜΕΘ',72,58],['Παθολογική',54,47],['Χειρουργική',41,35],['ΤΕΠ',29,24],['Αιμοκάθαρση',22,19]];return <div className="analysis-group-bars">{rows.map(([label,a,b])=><div className="analysis-group-row" key={label}><span>{label}</span><div><i style={{width:`${a}%`,background:COLORS[0]}}/><i style={{width:`${b}%`,background:COLORS[1]}}/></div><strong>{a}</strong></div>)}</div>}
function Comparison({organizations}){const rows=organizations?.length?organizations.slice(0,6).map((o,i)=>[o.name,(3.1+i*.3).toFixed(1),`${88-i*2}%`,String(56+i*3),`${92-i}%`]):COMPARE;return <article className="analysis-compare-card"><header><div><strong>Συγκριτική εικόνα οργανισμών</strong><span>HAI · Υγιεινή χεριών · DDD · Bundle compliance</span></div><span className="analysis-legend"><i style={{background:COLORS[0]}}/>τρέχουσα περίοδος</span></header><div className="analysis-comparison-table"><div className="head"><span>Οργανισμός</span><span>HAI /1.000</span><span>Hand hygiene</span><span>DDD/1.000</span><span>Bundles</span></div>{rows.map((r,i)=><div key={r[0]}><strong>{r[0]}</strong>{r.slice(1).map((x,j)=><span key={j} className={j===0&&Number(x)>3.7?'warn':''}>{x}</span>)}</div>)}</div></article>}

export function AnalysisPage({platform=false,organizations=[]}){
 const {tenant,role,isDemo}=useTenant();const [tab,setTab]=useState('overview');const [period,setPeriod]=useState('year');const [org,setOrg]=useState('all');const [region,setRegion]=useState('all');const [healthRegion,setHealthRegion]=useState('all');const [department,setDepartment]=useState('all');const [comparison,setComparison]=useState(platform?'hospitals':'year');
 const allowed=[ROLES.PLATFORM_OWNER,ROLES.HOSPITAL_ADMIN,ROLES.INFECTION_CONTROL_LEAD,ROLES.DEMO].includes(role);if(!allowed)return <div className="empty-state"><strong>Δεν υπάρχει πρόσβαση στην Ανάλυση.</strong></div>;
 const rows=KPI[tab]||KPI.overview;const trend=TRENDS[tab]||TRENDS.overview;const regions=useMemo(()=>[...new Set(organizations.map(o=>o.region).filter(Boolean))],[organizations]);const healthRegions=useMemo(()=>[...new Set(organizations.map(o=>o.health_region).filter(Boolean))],[organizations]);
 return <div className="analysis-workspace"><div className="analysis-header"><div><span className="eyebrow">ANALYTICS & REPORTING</span><h1>Ανάλυση</h1><p>{platform?'Συγκεντρωτική και συγκριτική εικόνα πλατφόρμας':tenant?.name||'Οργανισμός'} · δείκτες, τάσεις, benchmarks και reports.</p></div><div className="analysis-actions"><Button variant="secondary" onClick={()=>window.print()}><Printer size={15}/> Εκτύπωση</Button><Button variant="secondary" onClick={()=>window.print()}><Download size={15}/> Export</Button></div></div>
 <div className="analysis-sticky"><div className="analysis-filters">{platform&&<><label><span>Νοσοκομείο</span><select value={org} onChange={e=>setOrg(e.target.value)}><option value="all">Όλα τα νοσοκομεία</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label><span>Περιφέρεια</span><select value={region} onChange={e=>setRegion(e.target.value)}><option value="all">Όλες οι Περιφέρειες</option>{regions.length?regions.map(x=><option key={x}>{x}</option>):<><option>Θεσσαλία</option><option>Αττική</option><option>Κεντρική Μακεδονία</option></>}</select></label><label><span>ΥΠΕ</span><select value={healthRegion} onChange={e=>setHealthRegion(e.target.value)}><option value="all">Όλες οι ΥΠΕ</option>{healthRegions.map(x=><option key={x}>{x}</option>)}</select></label></>}<label><span>Τμήμα</span><select value={department} onChange={e=>setDepartment(e.target.value)}>{DEPARTMENTS.map((x,i)=><option key={x} value={i?x:'all'}>{x}</option>)}</select></label><label><span>Περίοδος</span><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="month">Μήνας</option><option value="quarter">Τρίμηνο</option><option value="half">Εξάμηνο</option><option value="year">Έτος</option><option value="compare">Σύγκριση ετών</option></select></label>{platform&&<label><span>Σύγκριση</span><select value={comparison} onChange={e=>setComparison(e.target.value)}><option value="hospitals">Νοσοκομείο ↔ Νοσοκομείο</option><option value="region">Νοσοκομείο ↔ Περιφέρεια</option><option value="regions">Περιφέρεια ↔ Περιφέρεια</option><option value="platform">Νοσοκομείο ↔ Platform benchmark</option><option value="year">Έτος ↔ Έτος</option></select></label>}</div><div className="analysis-tabs">{TABS.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div></div>
 <div className="analysis-scroll"><section className="analysis-report"><div className="analysis-section-title"><div><h2>{TABS.find(x=>x[0]===tab)?.[1]}</h2><p>{isDemo?'Πλούσιο demo dataset αποκλειστικά για το Demo environment.':platform?'Τα φίλτρα εφαρμόζονται σε οργανισμούς, Περιφέρειες, ΥΠΕ και συγκριτικά.':'Δεδομένα αποκλειστικά του οργανισμού και της επιλεγμένης περιόδου.'}</p></div><div className="analysis-report-badges">{platform&&<span className="status-badge info"><GitCompareArrows size={12}/> COMPARISON</span>}{isDemo&&<span className="status-badge temporary">DEMO DATA</span>}</div></div>
 <div className="analysis-kpis">{rows.map(([label,value,delta,direction],i)=><article key={label} style={{'--kpi-accent':COLORS[i%COLORS.length]}}><span>{label}</span><strong>{value}</strong><small className={direction==='down'?'good-down':'good-up'}>{direction==='down'?<TrendingDown size={13}/>:<TrendingUp size={13}/>} {delta} <em>vs προηγ. περίοδο</em></small></article>)}</div>
 <div className="analysis-chart-grid"><article className="analysis-chart-card analysis-trend-card"><header><div><strong>Τάση 12 μηνών</strong><span>Εξέλιξη του βασικού δείκτη της κατηγορίας</span></div><span className="analysis-legend"><i style={{background:COLORS[0]}}/>2026</span></header><LineChart values={trend}/></article><article className="analysis-chart-card"><header><div><strong>Κατανομή ανά τμήμα</strong><span>Τρέχουσα περίοδος έναντι προηγούμενης</span></div></header><GroupBars/><div className="analysis-mini-legend"><span><i style={{background:COLORS[0]}}/>Τρέχουσα</span><span><i style={{background:COLORS[1]}}/>Προηγούμενη</span></div></article></div>
 {platform&&<Comparison organizations={organizations}/>}<article className="analysis-chart-card analysis-wide-card"><header><div><strong>Report governance</strong><span>Το export διατηρεί ακριβώς το ενεργό scope και τα φίλτρα.</span></div></header><div className="analysis-summary-grid"><div><span>Scope</span><strong>{platform?(org==='all'?'Platform / επιλεγμένη γεωγραφία':'Επιλεγμένος οργανισμός'):(tenant?.name||'Οργανισμός')}</strong></div><div><span>Περίοδος</span><strong>{period==='year'?'2026':period==='compare'?'2025 ↔ 2026':period}</strong></div><div><span>Data completeness</span><strong>97%</strong></div><div><span>Τελευταία ενημέρωση</span><strong>Σήμερα</strong></div></div></article></section></div></div>
}
