import { useEffect,useMemo,useState } from 'react'
import { useNavigate,useSearchParams } from 'react-router-dom'
import { CalendarClock, HeartPulse, Syringe, UserRoundCheck, Users } from 'lucide-react'
import { Page } from '../../design-system/Page'
import { FilterBar, FilterSelect } from '../../design-system/FilterBar'
import { RecordActions } from '../../design-system/RecordActions'
import { ObserverDialog,DialogActions } from '../../design-system/ObserverDialog'
import { ManualDateField } from '../../design-system/ManualDateField'
import { Button } from '../../design-system/Button'
import { UI_ACTIONS } from '../../core/actions/actionPolicy'
import { CAPABILITIES } from '../../core/permissions/roles'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { useTenant } from '../../core/tenant/TenantContext'
import { useEmployeesData } from '../employees/useEmployeesData'
import { loadOccupationalVisits } from '../employees/employeeRecordsService'
import { createVaccinationsBulkAsync,loadAllVaccinationsAsync } from './vaccinationService'
import { downloadCsv } from '../../core/export/csvExport'
import { MetricCard } from '../../design-system/MetricCard'
import './OccupationalHealthPage.css'

const VACCINES=['Εποχική γρίπη','Ηπατίτιδα Β','COVID-19','MMR','Ανεμευλογιά','Td/Tdap','Ηπατίτιδα Α','Μηνιγγιτιδόκοκκος','Άλλο']
const emptyVaccination={vaccine:'',dose:'',date:'',lotNumber:'',validUntil:'',status:'complete',clinicalNotes:''}

export function OccupationalHealthPage(){
 const {t,language,locale}=useLanguage();const {notify,notifyError}=useFeedback();const navigate=useNavigate();const [searchParams,setSearchParams]=useSearchParams();const {canAccessRecord,tenant}=useTenant();const [tab,setTab]=useState(()=>searchParams.get('tab')==='vaccinations'?'vaccinations':'visits');const [query,setQuery]=useState('');const [status,setStatus]=useState('all');const [department,setDepartment]=useState('all')
 const {data:employeeRows}=useEmployeesData()
 const occupationalVisits=useMemo(loadOccupationalVisits,[])
 const [employeeVaccinations,setEmployeeVaccinations]=useState([]),[vaccinationLoading,setVaccinationLoading]=useState(false)
 const [vaccinationEditor,setVaccinationEditor]=useState(null)
 const departments=useMemo(()=>[...new Set(employeeRows.map(x=>language==='el'?x.department:x.departmentEn).filter(Boolean))],[employeeRows,language])
 const employeeMap=useMemo(()=>{const out={};for(const x of employeeRows){out[x.id]=x;if(x.dbId)out[x.dbId]=x}return out},[employeeRows])
 const source=tab==='visits'?occupationalVisits:employeeVaccinations
 const rows=useMemo(()=>source.filter(x=>Boolean(employeeMap[x.employeeId])).filter(x=>{const e=employeeMap[x.employeeId];return canAccessRecord(e)}).filter(x=>{const e=employeeMap[x.employeeId];const hay=`${e?.id??''} ${e?.firstName??''} ${e?.firstNameEn??''} ${e?.lastName??''} ${e?.lastNameEn??''} ${x.vaccine??''}`.toLowerCase();return hay.includes(query.toLowerCase())}).filter(x=>{const e=employeeMap[x.employeeId];return department==='all'||(language==='el'?e?.department:e?.departmentEn)===department}).filter(x=>status==='all'||x.status===status),[source,query,department,status,language,employeeMap,canAccessRecord])
 const fmt=v=>v?new Intl.DateTimeFormat(locale).format(new Date(`${v}T12:00:00`)):'—'; const name=e=>!e?'—':language==='el'?`${e.lastName} ${e.firstName}`:`${e.firstNameEn} ${e.lastNameEn}`
 const due=employeeVaccinations.filter(x=>x.status==='renewSoon').length;const scheduled=occupationalVisits.filter(x=>x.status==='scheduled').length

 async function reloadVaccinations(){if(!tenant?.id)return;setVaccinationLoading(true);try{setEmployeeVaccinations(await loadAllVaccinationsAsync(tenant.id))}catch(error){notifyError(error,'load',{operation:'occupational_vaccinations_load'})}finally{setVaccinationLoading(false)}}
 useEffect(()=>{void reloadVaccinations()},[tenant?.id])
 function changeTab(next){setTab(next);setStatus('all');setSearchParams({tab:next},{replace:true})}
 function action(a){if(a===UI_ACTIONS.PRINT){window.print();return}if(a===UI_ACTIONS.EXPORT){if(tab==='visits')downloadCsv('limoxis-occupational-visits.csv',[t('date'),t('employee'),t('visitType'),t('status'),t('fitnessStatus'),t('followUp')],rows.map(x=>{const e=employeeMap[x.employeeId];return [x.date,name(e),t(x.type),t(x.status),t(x.fitStatus),x.followUpDate||'']}));else downloadCsv('limoxis-occupational-vaccinations.csv',[t('employee'),t('vaccine'),t('dose'),t('date'),t('validUntil'),t('status')],rows.map(x=>{const e=employeeMap[x.employeeId];return [name(e),x.vaccine,x.dose,x.date,x.validUntil||'',t(x.status)]}));notify(t('currentListExported'),'success');return}if(a===UI_ACTIONS.CREATE&&tab==='vaccinations'){setVaccinationEditor({mode:'individual',draft:{...emptyVaccination},selectedEmployeeIds:[]});return}notify(t(a===UI_ACTIONS.CREATE?'newOccupationalVisit':'actionCompleted'),'info')}
 async function saveVaccinationEditor(payload){try{const selected=employeeRows.filter(x=>payload.selectedEmployeeIds.includes(x.id));await createVaccinationsBulkAsync(tenant.id,selected,payload.draft);notify(language==='en'?`${selected.length} vaccination record${selected.length===1?'':'s'} saved.`:`Αποθηκεύτηκαν ${selected.length} ${selected.length===1?'εμβολιασμός':'εμβολιασμοί'}.`,'success');setVaccinationEditor(null);await reloadVaccinations()}catch(error){notifyError(error,'save',{operation:'occupational_vaccinations_create'})}}
 return <Page fill title={t('occupationalHealth')} subtitle={t('occupationalHealthSubtitle')} actions={<RecordActions actions={[UI_ACTIONS.CREATE,UI_ACTIONS.ATTACH,UI_ACTIONS.PRINT,UI_ACTIONS.EXPORT]} actionCapabilities={{[UI_ACTIONS.CREATE]:CAPABILITIES.MANAGE_OCCUPATIONAL_HEALTH,[UI_ACTIONS.ATTACH]:CAPABILITIES.MANAGE_OCCUPATIONAL_HEALTH}} actionLabels={{[UI_ACTIONS.CREATE]:tab==='vaccinations'?(language==='en'?'Vaccination entry':'Καταχώρηση εμβολιασμού'):t('newOccupationalVisit')}} onAction={action}/> }>
  <div className="workspace-summary"><div className="employee-kpis"><Kpi icon={CalendarClock} value={scheduled} label={t('scheduledVisits')}/><Kpi icon={Syringe} value={due} label={t('vaccinationsDue')}/><Kpi icon={UserRoundCheck} value={occupationalVisits.filter(x=>x.fitStatus==='fit').length} label={t('fitForWork')}/></div><div className="governance-banner"><HeartPulse size={17}/><span>{t('occupationalHealthGovernance')}</span></div></div>
  <div className="surface registry-workspace occupational-workspace workspace-fill"><nav className="tabs occupational-tabs canonical-module-tabs"><button className={`tab ${tab==='visits'?'active':''}`} onClick={()=>changeTab('visits')}>{t('visits')}</button><button className={`tab ${tab==='vaccinations'?'active':''}`} onClick={()=>changeTab('vaccinations')}>{t('vaccinations')}</button></nav><FilterBar query={query} onQueryChange={setQuery} placeholder={t('searchEmployees')} activeAdvancedCount={(department!=='all'?1:0)+(status!=='all'?1:0)} onClear={()=>{setQuery('');setDepartment('all');setStatus('all')}}><FilterSelect label={t('department')} value={department} onChange={setDepartment}><option value="all">{t('allDepartments')}</option>{departments.map(x=><option key={x}>{x}</option>)}</FilterSelect><FilterSelect label={t('status')} value={status} onChange={setStatus}><option value="all">{t('all')}</option>{tab==='visits'?<><option value="scheduled">{t('scheduled')}</option><option value="completed">{t('completed')}</option></>:<><option value="complete">{t('complete')}</option><option value="renewSoon">{t('renewSoon')}</option></>}</FilterSelect></FilterBar><div className="occupational-content single"><div className="scroll-table">{tab==='visits'?<Visits rows={rows} employeeMap={employeeMap} name={name} t={t} fmt={fmt} openEmployee={id=>navigate(`/employees/${id}`)}/>:vaccinationLoading?<div className="inline-empty">{language==='en'?'Loading vaccinations…':'Φόρτωση εμβολιασμών…'}</div>:<Vaccinations rows={rows} employeeMap={employeeMap} name={name} t={t} fmt={fmt} openEmployee={id=>navigate(`/employees/${id}`)}/>}</div></div></div>
  {vaccinationEditor&&<VaccinationEditor language={language} employees={employeeRows.filter(x=>x.employmentStatus==='active'&&canAccessRecord(x))} value={vaccinationEditor} onChange={setVaccinationEditor} onClose={()=>setVaccinationEditor(null)} onSave={saveVaccinationEditor}/>} 
 </Page>
}
function Kpi({icon:Icon,value,label}){return <MetricCard icon={Icon} value={value} label={label}/>}
function Visits({rows,employeeMap,name,t,fmt,openEmployee}){return <table className="data-table sticky-table"><thead><tr><th>{t('date')}</th><th>{t('employee')}</th><th>{t('visitType')}</th><th>{t('status')}</th><th>{t('fitnessStatus')}</th><th>{t('followUp')}</th></tr></thead><tbody>{rows.map(x=>{const e=employeeMap[x.employeeId];return <tr key={x.id} className="clickable-row" tabIndex={0} onClick={()=>openEmployee(e.id)} onKeyDown={ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();openEmployee(e.id)}}}><td>{fmt(x.date)}</td><td><strong>{name(e)}</strong><small>{e.id}</small></td><td>{t(x.type)}</td><td><span className="status-badge active">{t(x.status)}</span></td><td>{t(x.fitStatus)}</td><td>{fmt(x.followUpDate)}</td></tr>})}</tbody></table>}
function Vaccinations({rows,employeeMap,name,t,fmt,openEmployee}){return <table className="data-table sticky-table"><thead><tr><th>{t('employee')}</th><th>{t('vaccine')}</th><th>{t('dose')}</th><th>{t('date')}</th><th>{t('validUntil')}</th><th>{t('status')}</th></tr></thead><tbody>{rows.map(x=>{const e=employeeMap[x.employeeId];return <tr key={x.id} className="clickable-row" tabIndex={0} onClick={()=>openEmployee(e.id)} onKeyDown={ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();openEmployee(e.id)}}}><td><strong>{name(e)}</strong><small>{e.id}</small></td><td>{x.vaccine}</td><td>{x.dose||'—'}</td><td>{fmt(x.date)}</td><td>{fmt(x.validUntil)}</td><td><span className={`status-badge ${x.status==='complete'?'active':''}`}>{t(x.status)}</span></td></tr>})}</tbody></table>}

function VaccinationEditor({language,employees,value,onChange,onClose,onSave}){
 const en=language==='en';const {mode,draft,selectedEmployeeIds}=value;const [search,setSearch]=useState('');const [dept,setDept]=useState('all');const departments=[...new Set(employees.map(x=>en?x.departmentEn:x.department).filter(Boolean))];const filtered=employees.filter(x=>{const label=`${x.id} ${x.firstName} ${x.lastName} ${x.firstNameEn} ${x.lastNameEn}`.toLowerCase();const d=en?x.departmentEn:x.department;return label.includes(search.toLowerCase())&&(dept==='all'||d===dept)});const valid=selectedEmployeeIds.length>0&&draft.vaccine.trim()&&draft.date
 const patchDraft=patch=>onChange({...value,draft:{...draft,...patch}});const setMode=next=>onChange({...value,mode:next,selectedEmployeeIds:[]});const toggle=id=>onChange({...value,selectedEmployeeIds:selectedEmployeeIds.includes(id)?selectedEmployeeIds.filter(x=>x!==id):[...selectedEmployeeIds,id]});const selectVisible=()=>onChange({...value,selectedEmployeeIds:[...new Set([...selectedEmployeeIds,...filtered.map(x=>x.id)])]});const clearVisible=()=>onChange({...value,selectedEmployeeIds:selectedEmployeeIds.filter(id=>!filtered.some(x=>x.id===id))})
 return <ObserverDialog width="workspace" eyebrow={en?'Staff vaccination':'Εμβολιασμός προσωπικού'} title={en?'Vaccination entry':'Καταχώρηση εμβολιασμού'} subtitle={en?'Choose one employee or register the same vaccine for several selected employees.':'Επιλέξτε έναν εργαζόμενο ή καταχωρήστε το ίδιο εμβόλιο σε πολλούς επιλεγμένους εργαζομένους.'} onClose={onClose} footer={<DialogActions showCancel onCancel={onClose} onSave={()=>onSave(value)} disabled={!valid} saveLabel={en?(mode==='bulk'?`Save ${selectedEmployeeIds.length} vaccinations`:'Save vaccination'):(mode==='bulk'?`Αποθήκευση ${selectedEmployeeIds.length} εμβολιασμών`:'Αποθήκευση εμβολιασμού')}/>}>
  <div className="vaccination-editor">
   <div className="vaccination-entry-mode" role="group" aria-label={en?'Entry mode':'Τρόπος καταχώρησης'}><Button variant={mode==='individual'?'primary':'secondary'} onClick={()=>setMode('individual')}><UserRoundCheck size={17}/>{en?'Individual':'Μεμονωμένα'}</Button><Button variant={mode==='bulk'?'primary':'secondary'} onClick={()=>setMode('bulk')}><Users size={17}/>{en?'Bulk vaccination':'Μαζικός εμβολιασμός'}</Button></div>
   <section className="vaccination-editor-card"><h4>{en?'Vaccine details':'Στοιχεία εμβολίου'}</h4><div className="vaccination-fields"><label><span>{en?'Vaccine':'Εμβόλιο'} *</span><select value={draft.vaccine} onChange={e=>patchDraft({vaccine:e.target.value})}><option value="">{en?'Select vaccine':'Επιλέξτε εμβόλιο'}</option>{VACCINES.map(v=><option key={v} value={v}>{v}</option>)}</select></label><label><span>{en?'Dose':'Δόση'}</span><input value={draft.dose} onChange={e=>patchDraft({dose:e.target.value})} placeholder={en?'e.g. 1, 2, booster':'π.χ. 1, 2, αναμνηστική'}/></label><ManualDateField label={en?'Vaccination date *':'Ημερομηνία εμβολιασμού *'} value={draft.date} onChange={date=>patchDraft({date})}/><label><span>{en?'Lot number':'Παρτίδα'}</span><input value={draft.lotNumber} onChange={e=>patchDraft({lotNumber:e.target.value})}/></label><ManualDateField label={en?'Valid until':'Ισχύει έως'} value={draft.validUntil} onChange={validUntil=>patchDraft({validUntil})} optional/><label className="vaccination-notes"><span>{en?'Notes':'Σημειώσεις'}</span><input value={draft.clinicalNotes} onChange={e=>patchDraft({clinicalNotes:e.target.value})}/></label></div></section>
   <section className="vaccination-editor-card vaccination-employee-picker"><div className="vaccination-picker-heading"><div><h4>{mode==='bulk'?(en?'Employees to vaccinate':'Εργαζόμενοι προς εμβολιασμό'):(en?'Employee':'Εργαζόμενος')}</h4><small>{en?`${selectedEmployeeIds.length} selected`:`${selectedEmployeeIds.length} επιλεγμένοι`}</small></div>{mode==='bulk'&&<div className="vaccination-picker-actions"><Button variant="secondary" onClick={selectVisible}>{en?'Select visible':'Επιλογή εμφανιζόμενων'}</Button><Button variant="secondary" onClick={clearVisible}>{en?'Clear visible':'Καθαρισμός εμφανιζόμενων'}</Button></div>}</div>
    {mode==='individual'?<label><span>{en?'Select employee':'Επιλέξτε εργαζόμενο'}</span><select value={selectedEmployeeIds[0]||''} onChange={e=>onChange({...value,selectedEmployeeIds:e.target.value?[e.target.value]:[]})}><option value="">{en?'Select employee':'Επιλέξτε εργαζόμενο'}</option>{employees.map(e=><option key={e.id} value={e.id}>{en?`${e.firstNameEn} ${e.lastNameEn}`:`${e.lastName} ${e.firstName}`} · {en?e.departmentEn:e.department}</option>)}</select></label>:<><div className="vaccination-picker-filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={en?'Search employees…':'Αναζήτηση εργαζομένων…'}/><select value={dept} onChange={e=>setDept(e.target.value)}><option value="all">{en?'All departments':'Όλα τα τμήματα'}</option>{departments.map(d=><option key={d}>{d}</option>)}</select></div><div className="vaccination-employee-list">{filtered.map(e=><label key={e.id} className={selectedEmployeeIds.includes(e.id)?'selected':''}><input type="checkbox" checked={selectedEmployeeIds.includes(e.id)} onChange={()=>toggle(e.id)}/><span><strong>{en?`${e.firstNameEn} ${e.lastNameEn}`:`${e.lastName} ${e.firstName}`}</strong><small>{e.id} · {en?e.departmentEn:e.department} · {en?e.professionEn:e.profession}</small></span></label>)}</div></>}
   </section>
  </div>
 </ObserverDialog>
}
