import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { CalendarClock, HeartPulse, Syringe, UserRoundCheck } from 'lucide-react'
import { Page } from '../../design-system/Page'
import { FilterBar, FilterSelect } from '../../design-system/FilterBar'
import { RecordActions } from '../../design-system/RecordActions'
import { UI_ACTIONS } from '../../core/actions/actionPolicy'
import { CAPABILITIES } from '../../core/permissions/roles'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { useTenant } from '../../core/tenant/TenantContext'
import { employeeRows, employeeVaccinations, occupationalVisits } from '../employees/employeeDemoData'
import { downloadCsv } from '../../core/export/csvExport'
import { MetricCard } from '../../design-system/MetricCard'

export function OccupationalHealthPage(){
 const {t,language,locale}=useLanguage();const {notify}=useFeedback();const navigate=useNavigate();const {canAccessRecord}=useTenant();const [tab,setTab]=useState('visits');const [query,setQuery]=useState('');const [status,setStatus]=useState('all');const [department,setDepartment]=useState('all')
 const departments=useMemo(()=>[...new Set(employeeRows.map(x=>language==='el'?x.department:x.departmentEn))],[language]);const employeeMap=useMemo(()=>Object.fromEntries(employeeRows.map(x=>[x.id,x])),[]);const source=tab==='visits'?occupationalVisits:employeeVaccinations
 const rows=useMemo(()=>source.filter(x=>{const e=employeeMap[x.employeeId];return canAccessRecord(e)}).filter(x=>{const e=employeeMap[x.employeeId];const hay=`${e?.id??''} ${e?.firstName??''} ${e?.firstNameEn??''} ${e?.lastName??''} ${e?.lastNameEn??''}`.toLowerCase();return hay.includes(query.toLowerCase())}).filter(x=>{const e=employeeMap[x.employeeId];return department==='all'||(language==='el'?e?.department:e?.departmentEn)===department}).filter(x=>status==='all'||x.status===status),[source,query,department,status,language,employeeMap,canAccessRecord])
 const fmt=v=>v?new Intl.DateTimeFormat(locale).format(new Date(`${v}T12:00:00`)):'—'; const name=e=>language==='el'?`${e.lastName} ${e.firstName}`:`${e.firstNameEn} ${e.lastNameEn}`
 const due=employeeVaccinations.filter(x=>x.status==='renewSoon').length;const scheduled=occupationalVisits.filter(x=>x.status==='scheduled').length
 function action(a){if(a===UI_ACTIONS.PRINT){window.print();return}if(a===UI_ACTIONS.EXPORT){if(tab==='visits')downloadCsv('limoxis-occupational-visits.csv',[t('date'),t('employee'),t('visitType'),t('status'),t('fitnessStatus'),t('followUp')],rows.map(x=>{const e=employeeMap[x.employeeId];return [x.date,name(e),t(x.type),t(x.status),t(x.fitStatus),x.followUpDate||'']}));else downloadCsv('limoxis-occupational-vaccinations.csv',[t('employee'),t('vaccine'),t('dose'),t('date'),t('validUntil'),t('status')],rows.map(x=>{const e=employeeMap[x.employeeId];return [name(e),x.vaccine,x.dose,x.date,x.validUntil||'',t(x.status)]}));notify(t('currentListExported'),'success');return}notify(t(a===UI_ACTIONS.CREATE?(tab==='visits'?'newOccupationalVisit':'newVaccinationRecord'):'actionCompleted'),'info')}
 return <Page fill title={t('occupationalHealth')} subtitle={t('occupationalHealthSubtitle')} actions={<RecordActions actions={[UI_ACTIONS.CREATE,UI_ACTIONS.ATTACH,UI_ACTIONS.PRINT,UI_ACTIONS.EXPORT]} actionCapabilities={{[UI_ACTIONS.CREATE]:CAPABILITIES.MANAGE_OCCUPATIONAL_HEALTH,[UI_ACTIONS.ATTACH]:CAPABILITIES.MANAGE_OCCUPATIONAL_HEALTH}} onAction={action}/> }>
  <div className="workspace-summary"><div className="employee-kpis"><Kpi icon={CalendarClock} value={scheduled} label={t('scheduledVisits')}/><Kpi icon={Syringe} value={due} label={t('vaccinationsDue')}/><Kpi icon={UserRoundCheck} value={occupationalVisits.filter(x=>x.fitStatus==='fit').length} label={t('fitForWork')}/></div><div className="governance-banner"><HeartPulse size={17}/><span>{t('occupationalHealthGovernance')}</span></div></div>
  <div className="surface registry-workspace occupational-workspace workspace-fill"><div className="tabs prevention-tabs"><button className={`tab ${tab==='visits'?'active':''}`} onClick={()=>{setTab('visits');setStatus('all')}}>{t('visits')}</button><button className={`tab ${tab==='vaccinations'?'active':''}`} onClick={()=>{setTab('vaccinations');setStatus('all')}}>{t('vaccinations')}</button></div><FilterBar query={query} onQueryChange={setQuery} placeholder={t('searchEmployees')} activeAdvancedCount={(department!=='all'?1:0)+(status!=='all'?1:0)} onClear={()=>{setQuery('');setDepartment('all');setStatus('all')}}><FilterSelect label={t('department')} value={department} onChange={setDepartment}><option value="all">{t('allDepartments')}</option>{departments.map(x=><option key={x}>{x}</option>)}</FilterSelect><FilterSelect label={t('status')} value={status} onChange={setStatus}><option value="all">{t('all')}</option>{tab==='visits'?<><option value="scheduled">{t('scheduled')}</option><option value="completed">{t('completed')}</option></>:<><option value="complete">{t('complete')}</option><option value="renewSoon">{t('renewSoon')}</option></>}</FilterSelect></FilterBar><div className="occupational-content single"><div className="scroll-table">{tab==='visits'?<Visits rows={rows} employeeMap={employeeMap} name={name} t={t} fmt={fmt} openEmployee={id=>navigate(`/employees/${id}`)}/>:<Vaccinations rows={rows} employeeMap={employeeMap} name={name} t={t} fmt={fmt} openEmployee={id=>navigate(`/employees/${id}`)}/>}</div></div></div>
 </Page>
}
function Kpi({icon:Icon,value,label}){return <MetricCard icon={Icon} value={value} label={label}/>}
function Visits({rows,employeeMap,name,t,fmt,openEmployee}){return <table className="data-table sticky-table"><thead><tr><th>{t('date')}</th><th>{t('employee')}</th><th>{t('visitType')}</th><th>{t('status')}</th><th>{t('fitnessStatus')}</th><th>{t('followUp')}</th><th></th></tr></thead><tbody>{rows.map(x=>{const e=employeeMap[x.employeeId];return <tr key={x.id} onDoubleClick={()=>openEmployee(x.employeeId)}><td>{fmt(x.date)}</td><td><strong>{name(e)}</strong><small>{e.id}</small></td><td>{t(x.type)}</td><td><span className="status-badge active">{t(x.status)}</span></td><td>{t(x.fitStatus)}</td><td>{fmt(x.followUpDate)}</td><td className="open-record-cell"><button className="open-record-button" onClick={()=>openEmployee(x.employeeId)}>{t('openEmployee')}</button></td></tr>})}</tbody></table>}
function Vaccinations({rows,employeeMap,name,t,fmt,openEmployee}){return <table className="data-table sticky-table"><thead><tr><th>{t('employee')}</th><th>{t('vaccine')}</th><th>{t('dose')}</th><th>{t('date')}</th><th>{t('validUntil')}</th><th>{t('status')}</th><th></th></tr></thead><tbody>{rows.map(x=>{const e=employeeMap[x.employeeId];return <tr key={x.id} onDoubleClick={()=>openEmployee(x.employeeId)}><td><strong>{name(e)}</strong><small>{e.id}</small></td><td>{x.vaccine}</td><td>{x.dose}</td><td>{fmt(x.date)}</td><td>{fmt(x.validUntil)}</td><td><span className={`status-badge ${x.status==='complete'?'active':''}`}>{t(x.status)}</span></td><td className="open-record-cell"><button className="open-record-button" onClick={()=>openEmployee(x.employeeId)}>{t('openEmployee')}</button></td></tr>})}</tbody></table>}
