function esc(value:unknown){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]||ch))}

export function committeeMinutesApprovalEmail({committeeName='',meetingTitle='',scheduledAt=null,actionUrl='',language='el'}:{committeeName?:string,meetingTitle?:string,scheduledAt?:string|null,actionUrl:string,language?:'el'|'en'}){
  const en=language==='en'
  const date=scheduledAt?new Date(scheduledAt).toLocaleDateString(en?'en-GB':'el-GR',{day:'2-digit',month:'2-digit',year:'numeric'}):''
  const title=en?'Minutes approval required':'Απαιτείται έγκριση πρακτικών'
  const intro=en?'Minutes have been submitted and require your review.':'Έχουν υποβληθεί πρακτικά συνεδρίασης και απαιτείται η έγκρισή σας.'
  const committeeLabel=en?'Committee':'Επιτροπή',meetingLabel=en?'Meeting':'Συνεδρίαση',dateLabel=en?'Date':'Ημερομηνία',button=en?'Review minutes':'Προβολή πρακτικών'
  const security=en?'For security, approval or rejection is completed only after you sign in to Limoxis Observer.':'Για λόγους ασφάλειας, η έγκριση ή η απόρριψη ολοκληρώνεται μόνο αφού συνδεθείτε στο Limoxis Observer.'
  const html=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><style>@media only screen and (max-width:640px){.lo-wrap{padding:12px 8px!important}.lo-card{border-radius:12px!important}.lo-head{padding:20px 18px!important}.lo-body{padding:22px 18px!important}.lo-title{font-size:21px!important;line-height:1.3!important}.lo-btn{display:block!important;width:100%!important;box-sizing:border-box!important;text-align:center!important;padding:14px 16px!important}.lo-info{padding:14px!important}}</style></head><body style="margin:0;background:#f4f7fa;font-family:Arial,Helvetica,sans-serif;color:#172033;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" class="lo-wrap" style="width:100%;padding:28px 12px;background:#f4f7fa"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" class="lo-card" style="width:100%;max-width:620px;background:#fff;border-radius:14px;border:1px solid #dfe6ee;overflow:hidden"><tr><td class="lo-head" style="padding:24px 28px;background:#0f3557;color:#fff"><div style="font-size:12px;letter-spacing:.08em;text-transform:uppercase;opacity:.82">Limoxis Observer</div><h1 class="lo-title" style="margin:8px 0 0;font-size:22px;line-height:1.3">${esc(title)}</h1></td></tr><tr><td class="lo-body" style="padding:28px;word-break:break-word"><p style="margin:0 0 20px;line-height:1.6">${esc(intro)}</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:#f7f9fb;border-radius:10px"><tr><td class="lo-info" style="padding:16px 18px;line-height:1.7;word-break:break-word"><strong>${esc(committeeLabel)}:</strong> ${esc(committeeName||'—')}<br><strong>${esc(meetingLabel)}:</strong> ${esc(meetingTitle||'—')}${date?`<br><strong>${esc(dateLabel)}:</strong> ${esc(date)}`:''}</td></tr></table><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin:24px 0"><tr><td><a href="${esc(actionUrl)}" class="lo-btn" style="display:inline-block;background:#1565a8;color:#fff;text-decoration:none;font-weight:700;padding:12px 18px;border-radius:8px;line-height:1.25">${esc(button)}</a></td></tr></table><p style="margin:0;color:#596579;font-size:13px;line-height:1.55">${esc(security)}</p></td></tr></table></td></tr></table></body></html>`
  const text=[title,intro,`${committeeLabel}: ${committeeName||'—'}`,`${meetingLabel}: ${meetingTitle||'—'}`,date?`${dateLabel}: ${date}`:'',`${button}: ${actionUrl}`,security].filter(Boolean).join('\n')
  return {subject:title,html,text}
}
