function esc(value:unknown){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]||ch))}

export function committeeMinutesApprovalEmail({committeeName='',meetingTitle='',scheduledAt=null,actionUrl='',language='el'}:{committeeName?:string,meetingTitle?:string,scheduledAt?:string|null,actionUrl:string,language?:'el'|'en'}){
  const en=language==='en'
  const date=scheduledAt?new Date(scheduledAt).toLocaleDateString(en?'en-GB':'el-GR',{day:'2-digit',month:'2-digit',year:'numeric'}):''
  const title=en?'Minutes approval required':'Απαιτείται έγκριση πρακτικών'
  const intro=en?'Minutes have been submitted and require your review.':'Έχουν υποβληθεί πρακτικά συνεδρίασης και απαιτείται η έγκρισή σας.'
  const committeeLabel=en?'Committee':'Επιτροπή',meetingLabel=en?'Meeting':'Συνεδρίαση',dateLabel=en?'Date':'Ημερομηνία',button=en?'Review minutes':'Προβολή πρακτικών'
  const security=en?'For security, approval or rejection is completed only after you sign in to Limoxis Observer.':'Για λόγους ασφάλειας, η έγκριση ή η απόρριψη ολοκληρώνεται μόνο αφού συνδεθείτε στο Limoxis Observer.'
  const html=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><style>@media only screen and (max-width:640px){.lo-wrap{padding:12px 8px!important}.lo-card{border-radius:12px!important}.lo-head{padding:20px 18px!important}.lo-body{padding:22px 18px!important}.lo-title{font-size:21px!important;line-height:1.3!important}.lo-btn{display:block!important;width:100%!important;box-sizing:border-box!important;text-align:center!important;padding:14px 16px!important}.lo-info{padding:14px!important}}</style></head><body style="margin:0;background:#f4f7fa;font-family:Arial,Helvetica,sans-serif;color:#172033;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" class="lo-wrap" style="width:100%;padding:28px 12px;background:#f4f7fa"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" class="lo-card" style="width:100%;max-width:620px;background:#fff;border-radius:14px;border:1px solid #dfe6ee;overflow:hidden"><tr><td class="lo-head" style="padding:24px 28px;background:#0f3557;color:#fff"><div style="font-size:12px;letter-spacing:.08em;text-transform:uppercase;opacity:.82">Limoxis Observer</div><h1 class="lo-title" style="margin:8px 0 0;font-size:22px;line-height:1.3">${esc(title)}</h1></td></tr><tr><td class="lo-body" style="padding:28px;word-break:break-word"><p style="margin:0 0 20px;line-height:1.6">${esc(intro)}</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:#f7f9fb;border-radius:10px"><tr><td class="lo-info" style="padding:16px 18px;line-height:1.7;word-break:break-word"><strong>${esc(committeeLabel)}:</strong> ${esc(committeeName||'—')}<br><strong>${esc(meetingLabel)}:</strong> ${esc(meetingTitle||'—')}${date?`<br><strong>${esc(dateLabel)}:</strong> ${esc(date)}`:''}</td></tr></table><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin:24px 0"><tr><td><a href="${esc(actionUrl)}" class="lo-btn" style="display:inline-block;background:#1565a8;color:#fff;text-decoration:none;font-weight:700;padding:12px 18px;border-radius:8px;line-height:1.25">${esc(button)}</a></td></tr></table><p style="margin:0;color:#596579;font-size:13px;line-height:1.55">${esc(security)}</p></td></tr></table></td></tr></table></body></html>`
  const text=[title,intro,`${committeeLabel}: ${committeeName||'—'}`,`${meetingLabel}: ${meetingTitle||'—'}`,date?`${dateLabel}: ${date}`:'',`${button}: ${actionUrl}`,security].filter(Boolean).join('\n')
  return {subject:title,html,text}
}

// A member without a Limoxis account: the summary of the minutes and a
// personal single-use link (approve / request changes) that needs no sign-in.
export function committeeMinutesExternalApprovalEmail({memberName='',organizationName='',committeeName='',meetingTitle='',scheduledAt=null,minutesNumber='',topics=[],expiresAt=null,actionUrl='',language='el'}:{memberName?:string,organizationName?:string,committeeName?:string,meetingTitle?:string,scheduledAt?:string|null,minutesNumber?:string,topics?:Array<{subject?:string,decision?:string}>,expiresAt?:string|null,actionUrl:string,language?:'el'|'en'}){
  const en=language==='en'
  const day=(value:string|null)=>value?new Date(value).toLocaleDateString(en?'en-GB':'el-GR',{day:'2-digit',month:'2-digit',year:'numeric'}):''
  const date=day(scheduledAt),expires=day(expiresAt)
  const title=en?'Minutes for your approval':'Πρακτικά για έγκριση'
  const greeting=memberName?(en?`Dear ${memberName},`:`Αγαπητέ/ή ${memberName},`):''
  const intro=en?`The minutes of the meeting you attended${organizationName?` at ${organizationName}`:''} have been submitted for approval.`:`Τα πρακτικά της συνεδρίασης στην οποία συμμετείχατε${organizationName?` (${organizationName})`:''} υποβλήθηκαν για έγκριση.`
  const labels=en?{committee:'Committee',meeting:'Meeting',date:'Date',number:'Minutes no.',topics:'Topics and decisions',approve:'I approve',changes:'Request changes'}:{committee:'Επιτροπή',meeting:'Συνεδρίαση',date:'Ημερομηνία',number:'Αρ. πρακτικού',topics:'Θέματα και αποφάσεις',approve:'Εγκρίνω',changes:'Ζητώ διορθώσεις'}
  const note=en?`This personal link needs no account, can be used once${expires?` and expires on ${expires}`:''}. Do not forward it.`:`Ο σύνδεσμος είναι προσωπικός, δεν χρειάζεται λογαριασμό και χρησιμοποιείται μία φορά${expires?` (ισχύει έως ${expires})`:''}. Μην τον προωθήσετε.`
  const link=(decision:string)=>`${actionUrl}${actionUrl.includes('?')?'&':'?'}decision=${decision}`
  const topicRows=(topics||[]).filter(t=>t?.subject).slice(0,12).map((t,i)=>`<tr><td style="padding:9px 0;border-top:1px solid #e4ebf0;vertical-align:top;width:26px;color:#596579;font-weight:700">${i+1}.</td><td style="padding:9px 0;border-top:1px solid #e4ebf0;line-height:1.5"><strong>${esc(t.subject)}</strong>${t.decision?`<br><span style="color:#3b4a5c">${esc(t.decision)}</span>`:''}</td></tr>`).join('')
  const html=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><style>@media only screen and (max-width:640px){.lo-wrap{padding:12px 8px!important}.lo-card{border-radius:12px!important}.lo-head{padding:20px 18px!important}.lo-body{padding:22px 18px!important}.lo-btn{display:block!important;width:100%!important;box-sizing:border-box!important;text-align:center!important;margin:0 0 10px!important}}</style></head><body style="margin:0;background:#f4f7fa;font-family:Arial,Helvetica,sans-serif;color:#172033"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" class="lo-wrap" style="width:100%;padding:28px 12px;background:#f4f7fa"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" class="lo-card" style="width:100%;max-width:620px;background:#fff;border-radius:14px;border:1px solid #dfe6ee;overflow:hidden"><tr><td class="lo-head" style="padding:24px 28px;background:#0f3557;color:#fff"><div style="font-size:12px;letter-spacing:.08em;text-transform:uppercase;opacity:.82">Limoxis Observer</div><h1 style="margin:8px 0 0;font-size:22px;line-height:1.3">${esc(title)}</h1></td></tr><tr><td class="lo-body" style="padding:28px;word-break:break-word">${greeting?`<p style="margin:0 0 12px;font-size:16px">${esc(greeting)}</p>`:''}<p style="margin:0 0 20px;line-height:1.6">${esc(intro)}</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:#f7f9fb;border-radius:10px"><tr><td style="padding:16px 18px;line-height:1.7"><strong>${esc(labels.committee)}:</strong> ${esc(committeeName||'—')}<br><strong>${esc(labels.meeting)}:</strong> ${esc(meetingTitle||'—')}${date?`<br><strong>${esc(labels.date)}:</strong> ${esc(date)}`:''}${minutesNumber?`<br><strong>${esc(labels.number)}:</strong> ${esc(minutesNumber)}`:''}</td></tr></table>${topicRows?`<h2 style="font-size:15px;margin:24px 0 4px">${esc(labels.topics)}</h2><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0">${topicRows}</table>`:''}<table role="presentation" cellspacing="0" cellpadding="0" border="0" style="margin:26px 0 18px"><tr><td><a href="${esc(link('approve'))}" class="lo-btn" style="display:inline-block;background:#0f6f7c;color:#fff;text-decoration:none;font-weight:700;padding:12px 20px;border-radius:8px;margin-right:10px">${esc(labels.approve)}</a><a href="${esc(link('changes'))}" class="lo-btn" style="display:inline-block;background:#fff;color:#0f3557;text-decoration:none;font-weight:700;padding:11px 19px;border-radius:8px;border:1px solid #b9c7d5">${esc(labels.changes)}</a></td></tr></table><p style="margin:0;color:#596579;font-size:13px;line-height:1.55">${esc(note)}</p></td></tr></table></td></tr></table></body></html>`
  const text=[title,greeting,intro,`${labels.committee}: ${committeeName||'—'}`,`${labels.meeting}: ${meetingTitle||'—'}`,date?`${labels.date}: ${date}`:'',minutesNumber?`${labels.number}: ${minutesNumber}`:'',...(topics||[]).filter(t=>t?.subject).map((t,i)=>`${i+1}. ${t.subject}${t.decision?` — ${t.decision}`:''}`),`${labels.approve}: ${link('approve')}`,`${labels.changes}: ${link('changes')}`,note].filter(Boolean).join('\n')
  return {subject:`${title}: ${committeeName||meetingTitle}`,html,text}
}
