function esc(value:unknown){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]||ch))}
export function trainingInvitationEmail({programTitle='',employeeName='',dueDate=null,requiresAssessment=false,questionCount=0,externalAccess=false,actionUrl='',language='el'}:{programTitle?:string,employeeName?:string,dueDate?:string|null,requiresAssessment?:boolean,questionCount?:number,externalAccess?:boolean,actionUrl:string,language?:'el'|'en'}){
 const en=language==='en';const date=dueDate?new Date(`${dueDate}T12:00:00`).toLocaleDateString(en?'en-GB':'el-GR'):''
 const subject=en?`Training confirmation & evaluation: ${programTitle}`:`Επιβεβαίωση συμμετοχής & αξιολόγηση: ${programTitle}`
 const hello=en?`Hello ${employeeName||''},`:`Αγαπητέ/ή ${employeeName||''},`
 const intro=en?'Please complete your attendance confirmation and training evaluation for the following program.':'Παρακαλούμε ολοκληρώστε την επιβεβαίωση συμμετοχής και την αξιολόγηση για το παρακάτω πρόγραμμα εκπαίδευσης.'
 const action=en?'Open confirmation form':'Άνοιγμα φόρμας επιβεβαίωσης'
 const assessmentText=requiresAssessment?(en?`The form includes the trainer evaluation and ${questionCount||0} knowledge question${questionCount===1?'':'s'}.`:`Η φόρμα περιλαμβάνει την αξιολόγηση εκπαιδευτή και ${questionCount||0} ${questionCount===1?'ερώτηση':'ερωτήσεις'} γνώσεων.`):(en?'The form includes attendance confirmation and trainer evaluation.':'Η φόρμα περιλαμβάνει επιβεβαίωση συμμετοχής και αξιολόγηση εκπαιδευτή.')
 const security=externalAccess?(en?'This is a personal secure link. Do not forward it to another person.':'Ο σύνδεσμος είναι προσωπικός και ασφαλής. Μην τον προωθείτε σε άλλο άτομο.'):(en?'This link is personal. Sign in with the Limoxis Observer account linked to your employee record before submitting.':'Ο σύνδεσμος είναι προσωπικός. Συνδεθείτε με τον λογαριασμό Limoxis Observer που είναι συνδεδεμένος με την καρτέλα εργαζομένου πριν την υποβολή.')
 const html=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><style>@media only screen and (max-width:640px){.lo-wrap{padding:12px 8px!important}.lo-card{border-radius:12px!important}.lo-head{padding:20px 18px!important}.lo-body{padding:22px 18px!important}.lo-title{font-size:21px!important;line-height:1.25!important}.lo-btn{display:block!important;width:100%!important;box-sizing:border-box!important;text-align:center!important;padding:14px 16px!important}.lo-detail{font-size:15px!important;line-height:1.6!important}}</style></head><body style="margin:0;background:#f4f7fa;font-family:Arial,Helvetica,sans-serif;color:#172033;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" class="lo-wrap" style="width:100%;background:#f4f7fa;padding:28px 12px"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" class="lo-card" style="width:100%;max-width:620px;background:#fff;border:1px solid #dfe6ee;border-radius:14px;overflow:hidden"><tr><td class="lo-head" style="padding:22px 28px;background:#0f3557;color:#fff"><div style="font-size:12px;letter-spacing:.08em;text-transform:uppercase;opacity:.85">Limoxis Observer · Training</div><h1 class="lo-title" style="margin:8px 0 0;font-size:24px;line-height:1.3;word-break:break-word">${esc(programTitle)}</h1></td></tr><tr><td class="lo-body" style="padding:28px"><p class="lo-detail" style="margin:0 0 16px;line-height:1.6">${esc(hello)}</p><p class="lo-detail" style="margin:0 0 18px;line-height:1.6">${esc(intro)}</p>${date?`<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin:0 0 18px;background:#f7f9fb;border-radius:10px"><tr><td style="padding:14px 16px;line-height:1.6"><strong>${en?'Due date':'Προθεσμία'}:</strong> ${esc(date)}</td></tr></table>`:''}<p class="lo-detail" style="margin:0 0 22px;line-height:1.6">${esc(assessmentText)}</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td><a class="lo-btn" href="${esc(actionUrl)}" style="display:inline-block;background:#1565a8;color:#fff;text-decoration:none;font-weight:700;padding:13px 20px;border-radius:8px;line-height:1.25">${esc(action)}</a></td></tr></table><p style="margin:24px 0 0;font-size:13px;line-height:1.55;color:#596579;word-break:break-word">${esc(security)}</p></td></tr></table></td></tr></table></body></html>`
 return {subject,html,text:[hello,intro,programTitle,date?`${en?'Due date':'Προθεσμία'}: ${date}`:'',assessmentText,`${action}: ${actionUrl}`,security].filter(Boolean).join('\n')}
}
