import { useEffect, useMemo, useState } from 'react'
import { useLocation, useNavigate, useParams } from 'react-router-dom'
import { ShieldCheck, Microscope, Pill, BedDouble, RefreshCcw, CircleCheckBig, FileClock, UserRound, Activity, Printer, Pencil, Trash2, FolderOpen, ListTree, ChevronRight, AlertTriangle, CheckCircle2, X } from 'lucide-react'
import { Page } from '../../design-system/Page'
import { EntityRecordShell } from '../../design-system/EntityRecordShell'
import { PrintExportActions } from '../../design-system/PrintExportActions'
import { Button } from '../../design-system/Button'
import { SaveButton } from '../../design-system/SaveButton'
import { AttachmentField } from '../../design-system/AttachmentField'
import { ManualDateField } from '../../design-system/ManualDateField'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { EmptyState } from '../../design-system/EmptyState'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useTenant } from '../../core/tenant/TenantContext'
import { can, CAPABILITIES } from '../../core/permissions/roles'
import { createClinicalSurveillance, deleteClinicalSurveillance, findCaseByPatient, findCasesByPatient, getClinicalCase } from './clinicalDemoData'
import { loadPatients, loadAdmissions, createAdmission } from '../patients/patientsService'
import { createDemoSurveillanceListItem, deleteDemoSurveillanceListItem, syncDemoSurveillanceListItem } from './surveillanceDemoData'
import { NewSurveillanceFlow } from './NewSurveillanceFlow'
import { laboratorySamples } from '../laboratory/laboratoryDemoData'
import { demoLibrarySeed } from '../management/managementData'
import { useContextualNavigation } from '../../core/navigation/useContextualNavigation'
import { useRecordSequenceNavigation } from '../../core/navigation/useRecordSequenceNavigation'
import { useAuditActor } from '../../core/audit/useAuditActor'
import { downloadRecordJson } from '../../core/export/recordExport'

export function PatientClinicalRecordPage({patientMode=false}){
  const actor=useAuditActor()
  const { caseId, patientId } = useParams()
  const sequenceId=patientMode?patientId:caseId
  const recordNavigation=useRecordSequenceNavigation({registry:patientMode?'patients':'surveillance',currentId:sequenceId,pathForId:id=>patientMode?`/patients/${id}`:`/surveillance/${id}`})
  const location=useLocation()
  const {goBack,restored}=useContextualNavigation(patientMode?'/patients':'/surveillance')
  const { t, language, locale } = useLanguage()
  const [tab,setTab] = useState(()=>location.state?.openTab||restored?.tab||'summary')
  const { notify, confirm } = useFeedback()
  const {role,membership,tenant,isDemo,canAccessRecord}=useTenant()
  const [patients,setPatients] = useState([])
  useEffect(()=>{let alive=true;loadPatients(tenant?.id,{isDemo}).then(list=>{if(alive)setPatients(list)}).catch(()=>{});return ()=>{alive=false}},[tenant?.id,isDemo])
  const patient = patients.find(x=>x.id===patientId) ?? null
  const [episodeVersion,setEpisodeVersion]=useState(0);void episodeVersion
  const [newSurveillanceOpen,setNewSurveillanceOpen]=useState(false)
  const patientEpisodes = patientMode ? findCasesByPatient(patientId) : []
  const defaultRecord = patientMode ? findCaseByPatient(patientId) : getClinicalCase(caseId)
  const [selectedEpisodeId,setSelectedEpisodeId]=useState(defaultRecord?.id||'')
  const record = patientMode ? (patientEpisodes.find(x=>x.id===selectedEpisodeId) || defaultRecord) : defaultRecord
  const fmtDate=(value)=>value ? new Intl.DateTimeFormat(locale).format(new Date(`${value.slice(0,10)}T12:00:00`)) : '—'
  const fmtDateTime=(value)=>value ? new Intl.DateTimeFormat(locale,{dateStyle:'short',timeStyle:'short'}).format(new Date(value)) : '—'
  const age=useMemo(()=>record?.dateOfBirth?Math.floor((new Date(record.admissionDate)-new Date(record.dateOfBirth))/(365.2425*24*60*60*1000)):null,[record])
  const scopedSubject=record||patient
  const subjectInScope=!scopedSubject||canAccessRecord({...scopedSubject,department:scopedSubject.department})
  if(!record && !patient) return <Page title={t('clinicalRecords.patientRecord')}><EmptyState title={t('noData')} description={t('clinicalRecords.noClinicalData')}/></Page>
  if(!subjectInScope)return <Page title={t('clinicalRecords.patientRecord')}><EmptyState title={t('scopeAccessDeniedTitle')} description={t('scopeAccessDeniedDescription')}/></Page>
  const patientName=language==='el'?(record?.patient||patient?.name):(record?.patientEn||patient?.nameEn)
  const department=language==='el'?(record?.department||patient?.department):(record?.departmentEn||patient?.departmentEn)
  const patientCode=record?.patientId||patient?.id
  const admissionDate=record?.admissionDate||patient?.admissionDate
  const has=(cap)=>can(role,cap,membership?.capabilities??[],membership?.customCapabilities??[])
  const canSurveillance=Boolean(record)&&has(CAPABILITIES.VIEW_SURVEILLANCE)
  const canLab=Boolean(record)&&(has(CAPABILITIES.VIEW_LAB)||has(CAPABILITIES.VIEW_SURVEILLANCE))
  const canTherapy=Boolean(record)&&(has(CAPABILITIES.VIEW_PHARMACY)||has(CAPABILITIES.VIEW_SURVEILLANCE))
  const canClinical=canSurveillance||canLab||canTherapy
  const canReopenSurveillance=has(CAPABILITIES.REOPEN_SURVEILLANCE)
  const canDeleteSurveillance=has(CAPABILITIES.DELETE_SURVEILLANCE)
  const tabDefinitions=[{id:'summary',label:t('summary'),icon:UserRound,show:true},{id:'admissions',label:t('clinicalRecords.admissions'),icon:BedDouble,show:patientMode&&Boolean(patient)},{id:'surveillanceJourney',label:t('surveillance'),icon:ListTree,show:has(CAPABILITIES.VIEW_SURVEILLANCE)||has(CAPABILITIES.CREATE_SURVEILLANCE)||canLab||canTherapy},{id:'clinicalData',label:t('clinicalRecords.clinicalData'),icon:Activity,show:canClinical},{id:'documents',label:t('documents'),icon:FolderOpen,show:true},{id:'history',label:t('history'),icon:FileClock,show:canSurveillance}].filter(x=>x.show)
  const activeTab=tabDefinitions.some(x=>x.id===tab)?tab:(tabDefinitions[0]?.id||'summary')
  function createSurveillance(draft,selectedPatient=null){const targetPatient=selectedPatient||patient||{id:record?.patientId,name:record?.patient,nameEn:record?.patientEn,department:record?.department,departmentEn:record?.departmentEn,admissionDate:record?.admissionDate,dateOfBirth:record?.dateOfBirth};if(!targetPatient?.id)return;const created=createClinicalSurveillance({patientId:targetPatient.id,patient:targetPatient.name,patientEn:targetPatient.nameEn,dateOfBirth:targetPatient.dateOfBirth,department:targetPatient.department,departmentEn:targetPatient.departmentEn,admissionDate:targetPatient.admissionDate,...draft,createdBy:actor.name,createdById:actor.id});createDemoSurveillanceListItem(created);setSelectedEpisodeId(created.id);setEpisodeVersion(v=>v+1);setTab('surveillanceJourney');notify(t('surveillanceCreated'),'success');return created}
  return <Page fill title={patientName} subtitle={record?`${patientCode} · ${record.id}`:patientCode}><EntityRecordShell className="patient-record-shell workspace-fill" avatar={patientName?.split(' ').map(x=>x?.[0]).slice(0,2).join('')} eyebrow={patientCode} title={patientName} subtitle={`${department||'—'} · ${t('clinicalRecords.admission')}: ${fmtDate(admissionDate)}`} status={<><span className={`status-badge ${(record?.status||patient?.status)==='active'?'active':''}`}>{t(record?.status||patient?.status||'active')}</span>{(canLab||canSurveillance)&&record?.resistance&&<span className="status-badge danger">{record.resistance}</span>}</>} recordNavigation={recordNavigation} headerActions={<PrintExportActions onExport={()=>downloadRecordJson({patient,record},{filename:record?.id||patientCode})}/>} tabs={tabDefinitions} activeTab={activeTab} onTabChange={setTab} onBack={goBack} backLabel={patientMode?t('clinicalRecords.backToPatients'):t('clinicalRecords.backToSurveillance')}>
    {activeTab==='summary'&&<PatientSummary patient={patient} record={record} t={t} language={language} fmtDate={fmtDate} age={age} has={has} notify={notify} confirm={confirm}/>} 
    {activeTab==='admissions'&&patient&&<PatientAdmissions patient={patient} t={t} language={language} fmtDate={fmtDate} notify={notify} tenant={tenant} isDemo={isDemo} canEdit={has(CAPABILITIES.EDIT_PATIENT)}/>} 
    {activeTab==='surveillanceJourney'&&<SurveillanceWorkspace episodes={patientMode?patientEpisodes:(record?[record]:[])} onSelect={setSelectedEpisodeId} onNewSurveillance={()=>setNewSurveillanceOpen(true)} canCreateSurveillance={has(CAPABILITIES.CREATE_SURVEILLANCE)} t={t} language={language} fmtDate={fmtDate} fmtDateTime={fmtDateTime} canSurveillance={canSurveillance} canLab={canLab} canTherapy={canTherapy} patientName={patientName} patientCode={patientCode} department={department} organizationName={tenant?.name||membership?.organization?.name||t('clinicalRecords.hospital')} canReopenSurveillance={canReopenSurveillance} actor={actor} canDeleteSurveillance={canDeleteSurveillance} onDeleteSurveillance={(episodeId,reason)=>{const removed=deleteClinicalSurveillance(episodeId,{actor:actor.name,actorId:actor.id,reason});if(removed){deleteDemoSurveillanceListItem(episodeId);setEpisodeVersion(v=>v+1);if(selectedEpisodeId===episodeId)setSelectedEpisodeId('');notify(t('clinicalRecords.surveillanceDeleted'),'success')}return removed}}/>}
    {activeTab==='clinicalData'&&record&&<ClinicalDataHub record={record} t={t} language={language} fmtDate={fmtDate} fmtDateTime={fmtDateTime} canSurveillance={canSurveillance} canLab={canLab} canTherapy={canTherapy}/>} 
    {activeTab==='documents'&&<PatientDocuments t={t} record={record}/>} {activeTab==='history'&&record&&<Timeline record={record} t={t} language={language} fmtDateTime={fmtDateTime}/>} 
    {newSurveillanceOpen&&<NewSurveillanceFlow patient={patient||{id:record?.patientId,name:record?.patient,nameEn:record?.patientEn,department:record?.department,departmentEn:record?.departmentEn,admissionDate:record?.admissionDate,dateOfBirth:record?.dateOfBirth,status:'active'}} patients={patients} onPatientsChange={setPatients} onClose={()=>setNewSurveillanceOpen(false)} onCreate={createSurveillance} onRecordChange={()=>setEpisodeVersion(v=>v+1)}/>} 
  </EntityRecordShell></Page>
}

function PatientSummary({patient,record,t,language,fmtDate,age,has,notify,confirm}){const latestSample=record?.samples?.[0];return <div className="patient-summary-layout"><PatientDetails patient={patient} record={record} t={t} language={language} fmtDate={fmtDate} age={age} has={has} notify={notify} confirm={confirm}/>{record&&<section className="patient-summary-strip"><SummaryItem label={t('surveillance')} value={`${record.id} · ${t(record.status)}`} tone="info"/><SummaryItem label={t('clinicalRecords.haiClassification')} value={record.haiClassification?t(record.haiClassification.status):'—'} tone={record.haiClassification?.status==='confirmed'?'warning':'neutral'}/><SummaryItem label={t('clinicalRecords.latestFinding')} value={latestSample?.organism||t(latestSample?.result||'pending')} tone={latestSample?.result==='positive'?'warning':'neutral'}/><SummaryItem label={t('isolation')} value={record.isolation?t(record.isolation.status):t('no')} tone={record.isolation?'info':'neutral'}/><SummaryItem label={t('therapy')} value={record.therapy?.length?`${record.therapy.length} · ${record.therapy.map(x=>x.antimicrobial).join(', ')}`:t('clinicalRecords.none')} tone={record.therapy?.length?'info':'neutral'}/><SummaryItem label={t('nextReview')} value={fmtDate(record.reviewDue)} tone="neutral"/></section>}</div>}
function SummaryItem({label,value,tone='neutral'}){return <div className={`patient-summary-item ${tone}`}><span>{label}</span><strong>{value}</strong></div>}

function PatientAdmissions({patient,t,language,fmtDate,notify,tenant,isDemo,canEdit}){const [admissions,setAdmissions]=useState([]);const [open,setOpen]=useState(false);useEffect(()=>{let alive=true;if(patient?.recordId)loadAdmissions(patient.recordId).then(rows=>{if(alive)setAdmissions(rows)}).catch(error=>{if(alive)notify(error?.message||t('clinicalRecords.admissionSaveFailed'),'danger')});return ()=>{alive=false}},[patient?.recordId,notify,t]);async function addAdmission(draft){try{const admission=await createAdmission(tenant?.id,patient,draft,{isDemo});setAdmissions(rows=>[admission,...rows]);setOpen(false);notify(t('clinicalRecords.admissionAdded'),'success')}catch(error){notify(error?.message||t('clinicalRecords.admissionSaveFailed'),'danger')}}return <div className="record-section"><div className="record-section-header"><div><span className="eyebrow">{t('clinicalRecords.patientRecord')}</span><h3>{t('clinicalRecords.admissions')}</h3></div>{canEdit&&<Button onClick={()=>setOpen(true)}>+ {t('clinicalRecords.newAdmission')}</Button>}</div>{admissions.length?<div className="record-table-wrap"><table className="record-table"><thead><tr><th>{t('admissionDate')}</th><th>{t('department')}</th><th>{t('clinicalRecords.dischargeDate')}</th><th>{t('status')}</th></tr></thead><tbody>{admissions.map(a=><tr key={a.id}><td>{fmtDate(a.admissionDate)}</td><td>{a.department||'—'}</td><td>{fmtDate(a.dischargeDate)}</td><td><span className={`status-badge ${a.status==='active'?'active':''}`}>{t(a.status)}</span></td></tr>)}</tbody></table></div>:<div className="inline-empty">{t('clinicalRecords.noAdmissions')}</div>}{open&&<NewAdmissionCard t={t} language={language} onClose={()=>setOpen(false)} onSave={addAdmission}/>}</div>}
function NewAdmissionCard({t,language,onClose,onSave}){const firstDepartment=demoLibrarySeed.departments?.[0]||['',''];const [draft,setDraft]=useState({department:firstDepartment[0],admissionDate:new Date().toISOString().slice(0,10),dischargeDate:'',status:'active',notes:''});const set=(key,value)=>setDraft(d=>({...d,[key]:value}));function setDepartment(el){const pair=demoLibrarySeed.departments.find(([value])=>value===el)||[el,el];setDraft(d=>({...d,department:pair[0]}))}function save(){if(!draft.admissionDate)return;onSave(draft)}return <div className="modal-backdrop"><div className="entry-card"><header><div><span className="eyebrow">{t('clinicalRecords.admissions')}</span><h3>{t('clinicalRecords.newAdmission')}</h3></div><button className="icon-close" onClick={onClose}>×</button></header><div className="entry-grid"><label><span>{t('department')}</span><select value={draft.department} onChange={e=>setDepartment(e.target.value)}>{demoLibrarySeed.departments.map(([el,en])=><option key={el} value={el}>{language==='el'?el:en}</option>)}</select></label><ManualDateField label={t('admissionDate')} value={draft.admissionDate} onChange={v=>set('admissionDate',v)}/><ManualDateField label={t('clinicalRecords.dischargeDate')} value={draft.dischargeDate} onChange={v=>set('dischargeDate',v)} optional/><label><span>{t('status')}</span><select value={draft.status} onChange={e=>set('status',e.target.value)}><option value="active">{t('active')}</option><option value="discharged">{t('discharged')}</option></select></label><label className="entry-span-2"><span>{t('notes')}</span><textarea rows={3} value={draft.notes} onChange={e=>set('notes',e.target.value)}/></label></div><footer><Button variant="secondary" onClick={onClose}>{t('cancel')}</Button><SaveButton disabled={!draft.admissionDate} onClick={save}>{t('save')}</SaveButton></footer></div></div>}

function SurveillanceWorkspace({episodes,onSelect,onNewSurveillance,canCreateSurveillance,t,language,fmtDate,fmtDateTime,canSurveillance,canLab,canTherapy,patientName,patientCode,department,organizationName,canReopenSurveillance,actor,canDeleteSurveillance,onDeleteSurveillance}){const [episodeRows,setEpisodeRows]=useState(episodes);useEffect(()=>setEpisodeRows(episodes),[episodes]);const active=episodeRows.filter(x=>x.status==='active'),completed=episodeRows.filter(x=>x.status!=='active');const [openEpisodeId,setOpenEpisodeId]=useState(null);const openEpisode=episodeRows.find(x=>x.id===openEpisodeId)||null;const selectAndOpen=id=>{onSelect(id);setOpenEpisodeId(id)};return <div className="surveillance-workspace"><div className="surveillance-workspace-toolbar"><div><span className="eyebrow">{t('surveillance')}</span><h3>{t('clinicalRecords.surveillanceEpisodes')}</h3><p>{t('clinicalRecords.surveillanceEpisodesHelp')}</p></div>{canCreateSurveillance&&<Button onClick={onNewSurveillance}>+ {t('newSurveillance')}</Button>}</div><div className="episode-list-columns"><EpisodeList title={t('clinicalRecords.activeSurveillanceEpisodes')} tone="active" episodes={active} onOpen={selectAndOpen} t={t} fmtDate={fmtDate}/><EpisodeList title={t('clinicalRecords.completedSurveillanceEpisodes')} tone="completed" episodes={completed} onOpen={selectAndOpen} t={t} fmtDate={fmtDate}/></div>{!episodes.length&&<SurveillanceStartGuide t={t}/>} {openEpisode&&<EpisodeDetailOverlay record={openEpisode} onClose={()=>setOpenEpisodeId(null)} t={t} language={language} fmtDate={fmtDate} fmtDateTime={fmtDateTime} canSurveillance={canSurveillance} canLab={canLab} canTherapy={canTherapy} patientName={patientName} patientCode={patientCode} department={department} organizationName={organizationName} canReopenSurveillance={canReopenSurveillance} actor={actor} canDeleteSurveillance={canDeleteSurveillance} onDeleteSurveillance={onDeleteSurveillance}/>}</div>}
function SurveillanceStartGuide({t}){return <section className="surveillance-start-guide"><h3>{t('clinicalRecords.howSurveillanceWorks')}</h3></section>}
function EpisodeList({title,tone,episodes,onOpen,t,fmtDate}){return <section className={`episode-list-panel ${tone}`}><header><strong>{title}</strong><span>{episodes.length}</span></header>{episodes.length?<table className="episode-table"><tbody>{episodes.map(ep=><tr key={ep.id} onClick={()=>onOpen(ep.id)}><td><strong>{ep.id}</strong></td><td>{fmtDate(ep.startedAt)}</td><td>{t(ep.status)}</td></tr>)}</tbody></table>:<div className="episode-empty">{t('noData')}</div>}</section>}
function EpisodeDetailOverlay({record,onClose,t,language,fmtDate,fmtDateTime,canSurveillance,canLab,canTherapy,patientName,patientCode,department,organizationName}){return <div className="episode-overlay"><section className="episode-detail-card"><header className="episode-detail-header"><div><h2>{record.id}</h2><p>{patientName} · {patientCode} · {department}</p></div><button onClick={onClose}><X size={16}/></button></header><div className="episode-detail-scroll"><ActiveSurveillanceReport record={record} t={t} language={language} fmtDate={fmtDate} fmtDateTime={fmtDateTime} canSurveillance={canSurveillance} canLab={canLab} canTherapy={canTherapy} patientName={patientName} patientCode={patientCode} department={department} organizationName={organizationName}/></div></section></div>}
function ActiveSurveillanceReport({record,t,language,fmtDate,fmtDateTime,canSurveillance,canLab,canTherapy}){return <SurveillanceJourney record={record} t={t} language={language} fmtDate={fmtDate} fmtDateTime={fmtDateTime} canSurveillance={canSurveillance} canLab={canLab} canTherapy={canTherapy}/>}
function SurveillanceJourney({record,t,language,fmtDate,fmtDateTime,canSurveillance,canLab,canTherapy}){return <ClinicalDataHub record={record} t={t} language={language} fmtDate={fmtDate} fmtDateTime={fmtDateTime} canSurveillance={canSurveillance} canLab={canLab} canTherapy={canTherapy}/>}
function ClinicalDataHub({record,t,language,fmtDate,fmtDateTime,canSurveillance,canLab,canTherapy}){return <div className="clinical-data-hub"><div className="clinical-data-grid">{canSurveillance&&<Assessment record={record} t={t} language={language} fmtDate={fmtDate}/>} {canLab&&<Samples record={record} t={t} fmtDateTime={fmtDateTime}/>} {canTherapy&&<Therapy record={record} t={t} fmtDate={fmtDate}/>} {canSurveillance&&<DevicesRisk record={record} t={t} language={language} fmtDate={fmtDate}/>}</div></div>}
function PatientDocuments({t,record}){const [attachments,setAttachments]=useState(()=>record?.attachments||[]);return <div className="record-section"><h3>{t('documents')}</h3><AttachmentField value={attachments} onChange={setAttachments}/></div>}
function PatientDetails({patient,record,t,language,fmtDate,age,has,notify,confirm}){const source=patient||{id:record?.patientId,name:record?.patient,nameEn:record?.patientEn,department:record?.department,departmentEn:record?.departmentEn,admissionDate:record?.admissionDate,status:record?.status};const canEdit=has(CAPABILITIES.EDIT_PATIENT),canDelete=has(CAPABILITIES.DELETE_PATIENT);async function remove(){const ok=await confirm({title:t('confirmAction'),message:t('deleteConfirm'),danger:true,confirmLabel:t('delete')});if(ok)notify(t('actionCompleted'),'warning')}return <section className="clinical-panel full-panel patient-details-panel"><div className="record-section-header"><h3>{t('clinicalRecords.patientDetails')}</h3><div>{canEdit&&<Pencil size={16}/>} {canDelete&&<button onClick={remove}><Trash2 size={16}/></button>}</div></div><div className="detail-grid"><Detail label={t('patientId')} value={source.id}/><Detail label={t('name')} value={language==='el'?source.name:source.nameEn}/><Detail label={t('department')} value={language==='el'?source.department:source.departmentEn}/><Detail label={t('admissionDate')} value={fmtDate(source.admissionDate)}/><Detail label={t('clinicalRecords.age')} value={age??'—'}/></div></section>}
function Assessment({record,t,language,fmtDate}){const a=record.assessment;return <section className="clinical-panel full-panel"><PanelTitle icon={ShieldCheck} title={t('clinicalAssessment')}/>{a&&<><Detail label={t('assessmentDate')} value={fmtDate(a.date)}/><p>{language==='el'?a.summary:a.summaryEn}</p></>}</section>}
function Samples({record,t,fmtDateTime}){const navigate=useNavigate();const {role,membership}=useTenant();const canOpen=can(role,CAPABILITIES.VIEW_LAB,membership?.capabilities??[],membership?.customCapabilities??[]);return <section className="clinical-panel full-panel"><PanelTitle icon={Microscope} title={t('samples')}/><table className="data-table clinical-table"><tbody>{(record.samples||[]).map(s=><tr key={s.id} onClick={()=>canOpen&&navigate(`/laboratory/${s.id}`)}><td>{s.id}</td><td>{t(s.type)}</td><td>{fmtDateTime(s.collectedAt)}</td><td>{t(s.result)}</td><td>{s.organism||'—'}</td></tr>)}</tbody></table></section>}
function Therapy({record,t,fmtDate}){return <section className="clinical-panel full-panel"><PanelTitle icon={Pill} title={t('therapy')}/>{(record.therapy||[]).map(x=><article key={x.id}><strong>{x.antimicrobial}</strong><Detail label={t('clinicalRecords.startedOn')} value={fmtDate(x.startedAt)}/></article>)}</section>}
function Timeline({record,t,language,fmtDateTime}){return <section className="clinical-panel full-panel"><PanelTitle icon={FileClock} title={t('clinicalRecords.timeline')}/>{(record.timeline||[]).map((item,i)=><article key={`${item.at}-${i}`}><strong>{t(item.type)}</strong> · {fmtDateTime(item.at)} · {(language==='en'&&item.actorEn)?item.actorEn:item.actor}</article>)}</section>}
function DevicesRisk({record,t,language,fmtDate}){return <section className="clinical-panel full-panel"><PanelTitle icon={FileClock} title={t('clinicalRecords.devicesRisk')}/>{(record.devices||[]).map(x=><article key={x.id}><strong>{language==='el'?x.name:x.nameEn}</strong><Detail label={t('clinicalRecords.insertedOn')} value={fmtDate(x.insertedAt)}/></article>)}</section>}
function PanelTitle({icon:Icon,title}){return <div className="panel-title"><Icon size={17}/><strong>{title}</strong></div>}
function Detail({label,value}){return <div className="detail-item"><span>{label}</span><strong>{value||'—'}</strong></div>}
