import { useEffect,useMemo,useState } from 'react'
import { Activity,AlertTriangle,BedDouble,FileClock,FolderOpen,ListTree,Microscope,Pill,RefreshCcw,ShieldCheck,Syringe,UserRound } from 'lucide-react'
import { useLocation,useNavigate,useParams } from 'react-router-dom'
import { Page } from '../../design-system/Page'
import { EntityRecordShell } from '../../design-system/EntityRecordShell'
import { PrintExportActions } from '../../design-system/PrintExportActions'
import { Button } from '../../design-system/Button'
import { SaveButton } from '../../design-system/SaveButton'
import { ManualDateField } from '../../design-system/ManualDateField'
import { ObserverDialog } from '../../design-system/ObserverDialog'
import { EmptyState } from '../../design-system/EmptyState'
import { EntityAttachmentsPanel } from '../../design-system/EntityAttachmentsPanel'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { useTenant } from '../../core/tenant/TenantContext'
import { useAuditActor } from '../../core/audit/useAuditActor'
import { useContextualNavigation } from '../../core/navigation/useContextualNavigation'
import { useRecordSequenceNavigation } from '../../core/navigation/useRecordSequenceNavigation'
import { downloadRecordJson } from '../../core/export/recordExport'
import { can,CAPABILITIES } from '../../core/permissions/roles'
import { createAdmission,loadAdmissions,loadPatients } from '../patients/patientsService'
import { loadDepartments } from '../management/departmentsService'
import { NewSurveillanceFlow } from './NewSurveillanceFlow'
import { SurveillanceJourneyGuidance,SurveillanceJourneyMap } from './SurveillanceJourneyMap'
import { createClinicalRepository } from './clinicalRepository'

export function PatientClinicalCanonicalPage({patientMode=false}){
  const actor=useAuditActor()
  const {caseId,patientId}=useParams()
  const navigate=useNavigate(),location=useLocation()
  const {t,language,locale}=useLanguage()
  const {notify}=useFeedback()
  const {tenant,isDemo,role,membership,canAccessRecord}=useTenant()
  const {goBack,restored}=useContextualNavigation(patientMode?'/patients':'/surveillance')
  const repository=useMemo(()=>createClinicalRepository({isDemo,organizationId:tenant?.id,actor}),[isDemo,tenant?.id,actor.id,actor.name])
  const [patients,setPatients]=useState([]),[episodes,setEpisodes]=useState([]),[admissions,setAdmissions]=useState([]),[departments,setDepartments]=useState([])
  const [selectedEpisodeId,setSelectedEpisodeId]=useState(caseId||''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[createOpen,setCreateOpen]=useState(false)
  const [tab,setTab]=useState(()=>location.state?.openTab||restored?.tab||'summary')
  const has=cap=>can(role,cap,membership?.capabilities??[],membership?.customCapabilities??[])
  const patient=useMemo(()=>patientMode?patients.find(row=>String(row.id)===String(patientId))||null:patients.find(row=>episodes.some(ep=>ep.patientRecordId===row.recordId||String(ep.patientId)===String(row.id)))||null,[patients,patientMode,patientId,episodes])
  const record=episodes.find(row=>String(row.id)===String(selectedEpisodeId))||episodes[0]||null
  const sequenceId=patientMode?patientId:caseId
  const recordNavigation=useRecordSequenceNavigation({registry:patientMode?'patients':'surveillance',currentId:sequenceId,pathForId:id=>patientMode?`/patients/${id}`:`/surveillance/${id}`})

  async function load(preferred=''){
    setLoading(true);setError('')
    try{
      const roster=await loadPatients(tenant?.id,{isDemo})
      setPatients(roster)
      const selectedPatient=patientMode?roster.find(row=>String(row.id)===String(patientId)):null
      let rows=[]
      if(patientMode&&selectedPatient)rows=await repository.loadForPatient(selectedPatient)
      else if(caseId){const one=await repository.loadCase(caseId);rows=one?[one]:[]}
      setEpisodes(rows)
      const current=preferred||selectedEpisodeId||caseId||rows[0]?.id||''
      setSelectedEpisodeId(rows.some(row=>String(row.id)===String(current))?current:(rows[0]?.id||''))
      const patientForAdmissions=selectedPatient||roster.find(row=>rows.some(ep=>ep.patientRecordId===row.recordId||String(ep.patientId)===String(row.id)))
      if(patientForAdmissions?.recordId)try{setAdmissions(await loadAdmissions(patientForAdmissions.recordId))}catch{setAdmissions([])}
      else setAdmissions([])
      if(!isDemo&&tenant?.id)try{setDepartments((await loadDepartments(tenant.id)).filter(row=>row.is_active!==false))}catch{setDepartments([])}
    }catch(err){setError(err?.message||t('actionFailed'))}
    finally{setLoading(false)}
  }
  useEffect(()=>{void load()},[tenant?.id,isDemo,patientMode,patientId,caseId])

  if(loading)return <Page title={t('clinicalRecords.patientRecord')}><div className="surface clinical-surface"><p>{t('loading')}</p></div></Page>
  if(error)return <Page title={t('clinicalRecords.patientRecord')}><EmptyState title={t('actionFailed')} description={error}/></Page>
  if(!patient&&!record)return <Page title={t('clinicalRecords.patientRecord')}><EmptyState title={t('noData')} description={t('clinicalRecords.noClinicalData')}/></Page>
  const subject=record||patient
  if(subject&&!canAccessRecord(subject))return <Page title={t('clinicalRecords.patientRecord')}><EmptyState title={t('scopeAccessDeniedTitle')} description={t('scopeAccessDeniedDescription')}/></Page>

  const name=language==='el'?(patient?.name||record?.patient):(patient?.nameEn||record?.patientEn||patient?.name||record?.patient)
  const code=patient?.id||record?.patientId
  const department=language==='el'?(record?.department||patient?.department):(record?.departmentEn||patient?.departmentEn||record?.department||patient?.department)
  const fmtDate=value=>value?new Intl.DateTimeFormat(locale).format(new Date(`${String(value).slice(0,10)}T12:00:00`)):'—'
  const fmtDateTime=value=>value?new Intl.DateTimeFormat(locale,{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'—'
  const canSurveillance=has(CAPABILITIES.VIEW_SURVEILLANCE)
  const canLab=has(CAPABILITIES.VIEW_LAB)||canSurveillance
  const canTherapy=has(CAPABILITIES.VIEW_PHARMACY)||canSurveillance
  const tabs=[
    {id:'summary',label:t('summary'),icon:UserRound},
    ...(patientMode?[{id:'admissions',label:t('clinicalRecords.admissions'),icon:BedDouble}]:[]),
    {id:'surveillanceJourney',label:t('surveillance'),icon:ListTree},
    ...(record?[{id:'clinicalData',label:t('clinicalRecords.clinicalData'),icon:Activity},{id:'documents',label:t('documents'),icon:FolderOpen},{id:'history',label:t('history'),icon:FileClock}]:[]),
  ]
  const activeTab=tabs.some(item=>item.id===tab)?tab:'summary'

  async function createEpisode(draft,targetPatient){
    const created=await repository.createCase(targetPatient||patient,draft)
    await load(created.id);setSelectedEpisodeId(created.id);setTab('surveillanceJourney');notify(t('surveillanceCreated'),'success');return created
  }

  return <Page fill title={name} subtitle={record?`${code} · ${record.id}`:code}>
    <EntityRecordShell className="patient-record-shell workspace-fill" avatar={name?.split(' ').map(x=>x?.[0]).slice(0,2).join('')} eyebrow={code} title={name} subtitle={`${department||'—'} · ${t('clinicalRecords.admission')}: ${fmtDate(record?.admissionDate||patient?.admissionDate)}`} status={<><span className={`status-badge ${(record?.status||patient?.status)==='active'?'active':''}`}>{t(record?.status||patient?.status||'active')}</span>{record?.resistance&&<span className="status-badge danger">{record.resistance}</span>}</>} recordNavigation={recordNavigation} headerActions={<PrintExportActions onExport={()=>downloadRecordJson({patient,record,episodes,admissions},{filename:record?.id||code})}/>} tabs={tabs} activeTab={activeTab} onTabChange={setTab} onBack={goBack} backLabel={patientMode?t('clinicalRecords.backToPatients'):t('clinicalRecords.backToSurveillance')}>
      {activeTab==='summary'&&<CanonicalSummary patient={patient} record={record} t={t} language={language} fmtDate={fmtDate}/>} 
      {activeTab==='admissions'&&patient&&<AdmissionsPanel rows={admissions} patient={patient} tenantId={tenant?.id} isDemo={isDemo} departments={departments} canEdit={has(CAPABILITIES.EDIT_PATIENT)} t={t} fmtDate={fmtDate} onAdded={row=>setAdmissions(current=>[row,...current])}/>} 
      {activeTab==='surveillanceJourney'&&<SurveillanceWorkspace episodes={episodes} selectedId={record?.id} onSelect={setSelectedEpisodeId} onCreate={()=>setCreateOpen(true)} canCreate={has(CAPABILITIES.CREATE_SURVEILLANCE)} record={record} repository={repository} onReload={()=>load(record?.id)} t={t} language={language} fmtDate={fmtDate} fmtDateTime={fmtDateTime} permissions={{canAssess:has(CAPABILITIES.RECORD_CLINICAL_ASSESSMENT),canLab,canEdit:has(CAPABILITIES.EDIT_SURVEILLANCE),canClassifyResistance:has(CAPABILITIES.CLASSIFY_RESISTANCE),canIsolation:has(CAPABILITIES.MANAGE_ISOLATION),canTherapy:has(CAPABILITIES.MANAGE_ANTIMICROBIAL_THERAPY),canReassess:has(CAPABILITIES.REASSESS_SURVEILLANCE),canOutcome:has(CAPABILITIES.RECORD_SURVEILLANCE_OUTCOME)||has(CAPABILITIES.CLOSE_SURVEILLANCE),canDelete:has(CAPABILITIES.DELETE_SURVEILLANCE),canReopen:has(CAPABILITIES.REOPEN_SURVEILLANCE)}}/>}
      {activeTab==='clinicalData'&&record&&<ClinicalSnapshot record={record} t={t} fmtDate={fmtDate}/>} 
      {activeTab==='documents'&&record&&(!isDemo&&record.recordId?<EntityAttachmentsPanel organizationId={tenant?.id} entityType="clinical_case" entityRecordId={record.recordId} category="clinical_documentation" canManage={has(CAPABILITIES.RECORD_CLINICAL_ASSESSMENT)} t={t} notify={notify}/>:<div className="inline-empty">{t('clinicalRecords.noAttachments')}</div>)}
      {activeTab==='history'&&record&&<Timeline record={record} t={t} fmtDateTime={fmtDateTime}/>} 
      {createOpen&&<NewSurveillanceFlow patient={patient} patients={patients} departments={departments} onPatientsChange={setPatients} onClose={()=>setCreateOpen(false)} onCreate={createEpisode} onSaveAssessment={(caseRecord,draft)=>repository.saveAssessment(caseRecord,draft)} onRequestSample={(caseRecord,draft)=>repository.requestSample(caseRecord,draft)} onSaveIsolation={(caseRecord,draft)=>draft.required===false?repository.setIsolationNotRequired(caseRecord):repository.beginIsolation(caseRecord,draft)} onRecordChange={updated=>{setEpisodes(current=>current.map(row=>row.id===updated.id?updated:row));setSelectedEpisodeId(updated.id)}}/>}
    </EntityRecordShell>
  </Page>
}

function CanonicalSummary({patient,record,t,language,fmtDate}){
  const latest=record?.samples?.find(x=>x.organism)||record?.samples?.[0]
  const details=[
    [t('patient'),language==='el'?(patient?.name||record?.patient):(patient?.nameEn||record?.patientEn||patient?.name||record?.patient)],
    [t('department'),language==='el'?(record?.department||patient?.department):(record?.departmentEn||patient?.departmentEn||record?.department||patient?.department)],
    [t('admissionDate'),fmtDate(patient?.admissionDate||record?.admissionDate)],
    [t('status'),t(record?.status||patient?.status||'active')],
  ]
  return <div className="patient-summary-layout clean-patient-summary"><section className="clinical-panel full-panel"><div className="record-section-header"><div><span className="eyebrow">{t('clinicalRecords.patientRecord')}</span><h3>{t('clinicalRecords.patientDetails')}</h3></div></div><div className="detail-grid patient-detail-grid">{details.map(([label,value])=><Detail key={label} label={label} value={value}/>)}</div></section>{record&&<section className="patient-summary-strip clinical-snapshot-strip"><Summary label={t('surveillance')} value={`${record.id} · ${t(record.status)}`} tone="info"/><Summary label={t('clinicalRecords.haiClassification')} value={record.haiClassification?t(record.haiClassification.status):'—'} tone={record.haiClassification?.status==='confirmed'?'warning':'neutral'}/><Summary label={t('clinicalRecords.latestFinding')} value={latest?.organism||t(latest?.result||'pending')} tone={latest?.result==='positive'?'warning':'neutral'}/><Summary label={t('therapy')} value={record.therapy?.length?record.therapy.map(x=>x.antimicrobial).join(', '):t('clinicalRecords.none')}/><Summary label={t('isolation')} value={record.isolation?t(record.isolation.status):t('no')}/><Summary label={t('nextReview')} value={fmtDate(record.reviewDue)}/></section>}</div>
}
function Summary({label,value,tone='neutral'}){return <div className={`patient-summary-item ${tone}`}><span>{label}</span><strong>{value}</strong></div>}
function Detail({label,value}){return <div className="detail-item"><span>{label}</span><strong>{value||'—'}</strong></div>}

function AdmissionsPanel({rows,patient,tenantId,isDemo,departments,canEdit,t,fmtDate,onAdded}){
  const [open,setOpen]=useState(false),[draft,setDraft]=useState({departmentId:patient?.departmentId||'',department:patient?.department||'',admissionDate:new Date().toISOString().slice(0,10),dischargeDate:'',status:'active',notes:''})
  async function save(){if(!draft.admissionDate)return;const dept=departments.find(x=>x.id===draft.departmentId);const row=await createAdmission(tenantId,patient,{...draft,department:dept?.name||draft.department},{isDemo});onAdded(row);setOpen(false)}
  return <section className="record-section"><div className="record-section-header"><div><span className="eyebrow">{t('clinicalRecords.patientRecord')}</span><h3>{t('clinicalRecords.admissions')}</h3></div>{canEdit&&<Button onClick={()=>setOpen(true)}>+ {t('clinicalRecords.newAdmission')}</Button>}</div>{rows.length?<div className="record-table-wrap"><table className="record-table"><thead><tr><th>{t('admissionDate')}</th><th>{t('department')}</th><th>{t('clinicalRecords.dischargeDate')}</th><th>{t('status')}</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{fmtDate(row.admissionDate)}</td><td>{row.department||'—'}</td><td>{fmtDate(row.dischargeDate)}</td><td>{t(row.status)}</td></tr>)}</tbody></table></div>:<div className="inline-empty">{t('clinicalRecords.noAdmissions')}</div>}{open&&<SimpleDialog title={t('clinicalRecords.newAdmission')} t={t} onClose={()=>setOpen(false)} onSave={save}><label><span>{t('department')}</span>{departments.length?<select value={draft.departmentId} onChange={e=>setDraft(d=>({...d,departmentId:e.target.value}))}><option value="">{t('select')}</option>{departments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>:<input value={draft.department} onChange={e=>setDraft(d=>({...d,department:e.target.value}))}/>}</label><ManualDateField label={t('admissionDate')} value={draft.admissionDate} onChange={v=>setDraft(d=>({...d,admissionDate:v}))}/><ManualDateField label={t('clinicalRecords.dischargeDate')} optional value={draft.dischargeDate} onChange={v=>setDraft(d=>({...d,dischargeDate:v}))}/></SimpleDialog>}</section>
}

function SurveillanceWorkspace({episodes,selectedId,onSelect,onCreate,canCreate,record,repository,onReload,t,language,fmtDate,fmtDateTime,permissions}){
  return <div className="workspace-column workspace-fill"><section className="record-section"><div className="record-section-header"><div><span className="eyebrow">{t('surveillance')}</span><h3>{t('clinicalRecords.surveillanceEpisodes')}</h3><p>{t('clinicalRecords.surveillanceEpisodesHelp')}</p></div>{canCreate&&<Button onClick={onCreate}>+ {t('newSurveillance')}</Button>}</div>{episodes.length?<div className="record-table-wrap"><table className="record-table episode-registry"><thead><tr><th>{t('startDate')}</th><th>{t('status')}</th><th>{t('clinicalRecords.haiClassification')}</th><th>{t('organism')}</th><th>AMR</th><th>{t('nextReview')}</th></tr></thead><tbody>{episodes.map(ep=><tr key={ep.id} className={ep.id===selectedId?'is-selected':''} tabIndex={0} onClick={()=>onSelect(ep.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(ep.id)}}><td>{fmtDate(ep.startedAt)}</td><td><span className={`status-badge ${ep.status==='active'?'active':''}`}>{t(ep.status)}</span></td><td>{ep.haiClassification?.type||ep.haiClassification?.status||'—'}</td><td>{ep.samples?.find(x=>x.organism)?.organism||ep.organism||'—'}</td><td>{ep.resistance||ep.samples?.find(x=>x.resistance)?.resistance||'—'}</td><td>{fmtDate(ep.reviewDue)}</td></tr>)}</tbody></table></div>:<SurveillanceStartGuide t={t}/>}</section>{record&&<CanonicalJourney record={record} repository={repository} onReload={onReload} t={t} language={language} fmtDate={fmtDate} fmtDateTime={fmtDateTime} permissions={permissions}/>}</div>
}

function CanonicalJourney({record,repository,onReload,t,fmtDate,fmtDateTime,permissions}){
  const {notify}=useFeedback();const [stage,setStage]=useState('assessment'),[dialog,setDialog]=useState(null),[reason,setReason]=useState('')
  const active=record.status==='active'
  const microbiology=(record.samples||[]).flatMap(sample=>(sample.microbiologyResults||[]).map(result=>({...result,sampleCode:sample.id})))
  const resultForAmr=microbiology.find(x=>x.organism&&!x.amr)||microbiology.find(x=>x.organism)
  async function run(work,message){try{await work();setDialog(null);setReason('');await onReload();notify(message||t('actionCompleted'),'success')}catch(error){notify(error?.message||t('actionFailed'),'danger')}}
  if(!active)return <div className="clinical-data-hub"><div className="clinical-data-heading"><div><span className="eyebrow">{t('surveillance')}</span><h3>{t('clinicalRecords.completedSurveillance')}</h3></div>{permissions.canReopen&&<Button variant="secondary" onClick={()=>setDialog('reopen')}><RefreshCcw size={15}/>{t('clinicalRecords.reopenSurveillance')}</Button>}</div><CompletedReport record={record} t={t} fmtDate={fmtDate} fmtDateTime={fmtDateTime}/>{dialog==='reopen'&&<ReasonDialog title={t('clinicalRecords.reopenSurveillance')} t={t} reason={reason} setReason={setReason} onClose={()=>setDialog(null)} onSave={()=>run(()=>repository.reopen(record,reason),t('clinicalRecords.surveillanceUpdated'))}/>}</div>
  return <div className="clinical-data-hub"><div className="journey-heading"><div><span className="eyebrow">{t('surveillanceJourney')}</span><h3>{record.id}</h3><p>{t('clinicalRecords.strictActiveJourneyHelp')}</p></div>{permissions.canDelete&&<Button variant="danger" onClick={()=>setDialog('void')}>{t('delete')}</Button>}</div><SurveillanceJourneyGuidance record={record} t={t} canAssess={permissions.canAssess} canLab={permissions.canLab} canIsolation={permissions.canIsolation} canTherapy={permissions.canTherapy} canReassess={permissions.canReassess} onSelect={setStage}/><SurveillanceJourneyMap record={record} t={t} fmtDate={fmtDate} activeStage={stage} onSelect={setStage}/><div className="clinical-data-grid">
    {stage==='assessment'&&<StagePanel icon={ShieldCheck} title={t('clinicalAssessment')} action={permissions.canAssess?<Button variant="secondary" onClick={()=>setDialog('assessment')}>{record.assessment?t('edit'):t('add')}</Button>:null}>{record.assessment?<><div className="detail-grid"><Detail label={t('assessmentDate')} value={fmtDate(record.assessment.date)}/><Detail label={t('classification')} value={t(record.assessment.classification||'undetermined')}/></div><p className="clinical-summary">{record.assessment.summary||record.assessment.notes||'—'}</p><TagList title={t('signsSymptoms')} items={record.assessment.signsSymptoms||record.assessment.symptoms}/><TagList title={t('riskFactors')} items={record.assessment.riskFactors}/></>:<div className="inline-empty">{t('clinicalRecords.assessmentPending')}</div>}</StagePanel>}
    {stage==='samples'&&<StagePanel icon={Microscope} title={t('samples')} action={permissions.canLab?<Button variant="secondary" onClick={()=>setDialog('sample')}>+ {t('add')}</Button>:null}>{record.samples?.length?<div className="record-table-wrap"><table className="record-table"><thead><tr><th>{t('sampleType')}</th><th>{t('status')}</th><th>{t('organism')}</th><th>AMR</th></tr></thead><tbody>{record.samples.map(x=><tr key={x.id}><td>{t(x.type)||x.type}</td><td>{t(x.result||x.status||'pending')}</td><td>{x.organism||'—'}</td><td>{x.resistance||'—'}</td></tr>)}</tbody></table></div>:<div className="inline-empty">{t('clinicalRecords.noSamplesRecorded')}</div>}</StagePanel>}
    {stage==='hai'&&<StagePanel icon={AlertTriangle} title={t('haiAmr')} action={<div className="button-row">{permissions.canAssess&&<Button variant="secondary" onClick={()=>setDialog('hai')}>+ HAI</Button>}{permissions.canClassifyResistance&&resultForAmr&&<Button variant="secondary" onClick={()=>setDialog('amr')}>+ AMR</Button>}</div>}>{record.haiClassification?<div className="evidence-box"><strong>{record.haiClassification.type||'—'} · {t(record.haiClassification.status)}</strong><span>{record.haiClassification.rationale||record.haiClassification.definitionSet||'—'}</span></div>:<div className="inline-empty">{t('clinicalRecords.notDocumented')}</div>}{record.resistance&&<div className="evidence-box"><strong>{record.resistance}</strong></div>}</StagePanel>}
    {stage==='therapy'&&<StagePanel icon={Pill} title={t('therapy')} action={permissions.canTherapy?<Button variant="secondary" onClick={()=>setDialog('therapy')}>+ {t('add')}</Button>:null}>{record.therapy?.length?<div className="record-table-wrap"><table className="record-table"><tbody>{record.therapy.map(x=><tr key={x.id}><td><strong>{x.antimicrobial}</strong></td><td>{x.dose||'—'} · {x.route||'—'}</td><td>{fmtDate(x.startedAt)}</td><td>{t(x.status||'active')}</td></tr>)}</tbody></table></div>:<div className="inline-empty">{t('clinicalRecords.noTherapyRecorded')}</div>}</StagePanel>}
    {stage==='isolation'&&<StagePanel icon={BedDouble} title={t('isolation')} action={permissions.canIsolation?<div className="button-row">{record.isolation?.status==='active'?<Button variant="secondary" onClick={()=>setDialog('endIsolation')}>{t('end')}</Button>:<Button variant="secondary" onClick={()=>setDialog('isolation')}>+ {t('add')}</Button>}{!record.isolation&&<Button variant="ghost" onClick={()=>run(()=>repository.setIsolationNotRequired(record),t('actionCompleted'))}>{t('notRequired')}</Button>}</div>:null}>{record.isolation?<div className="detail-grid"><Detail label={t('status')} value={t(record.isolation.status)}/><Detail label={t('startDate')} value={fmtDate(record.isolation.startedAt)}/><Detail label={t('reason')} value={record.isolation.reason}/><Detail label={t('room')} value={record.isolation.room}/></div>:<div className="inline-empty">{record.isolationDecision?.required===false?t('notRequired'):t('clinicalRecords.noIsolationRecorded')}</div>}</StagePanel>}
    {stage==='reassessment'&&<StagePanel icon={RefreshCcw} title={t('reassessment')} action={permissions.canReassess?<Button variant="secondary" onClick={()=>setDialog('reassessment')}>+ {t('add')}</Button>:null}>{record.reassessments?.length?<div className="clinical-timeline">{record.reassessments.map(x=><article key={x.id}><div><header><strong>{t(x.status)}</strong><time>{fmtDate(x.date)}</time></header><p>{x.notes||'—'}</p></div></article>)}</div>:<div className="inline-empty">{t('clinicalRecords.noReassessmentRecorded')}</div>}{permissions.canOutcome&&<div className="record-section-footer"><Button onClick={()=>setDialog('outcome')}>{t('outcome')}</Button></div>}</StagePanel>}
  </div>
  {dialog==='assessment'&&<AssessmentDialog t={t} record={record} onClose={()=>setDialog(null)} onSave={draft=>run(()=>repository.saveAssessment(record,draft),t('actionCompleted'))}/>} 
  {dialog==='sample'&&<SampleDialog t={t} onClose={()=>setDialog(null)} onSave={draft=>run(()=>repository.requestSample(record,draft),t('actionCompleted'))}/>} 
  {dialog==='hai'&&<HaiDialog t={t} onClose={()=>setDialog(null)} onSave={draft=>run(()=>repository.saveHai(record,draft),t('actionCompleted'))}/>} 
  {dialog==='amr'&&<AmrDialog t={t} onClose={()=>setDialog(null)} onSave={draft=>run(()=>repository.saveAmr(record,resultForAmr?.id,draft),t('actionCompleted'))}/>} 
  {dialog==='therapy'&&<TherapyDialog t={t} onClose={()=>setDialog(null)} onSave={draft=>run(()=>repository.addTherapy(record,draft),t('actionCompleted'))}/>} 
  {dialog==='isolation'&&<IsolationDialog t={t} onClose={()=>setDialog(null)} onSave={draft=>run(()=>repository.beginIsolation(record,draft),t('actionCompleted'))}/>} 
  {dialog==='endIsolation'&&<EndDialog title={t('isolation')} t={t} onClose={()=>setDialog(null)} onSave={draft=>run(()=>repository.finishIsolation(record,draft),t('actionCompleted'))}/>} 
  {dialog==='reassessment'&&<ReassessmentDialog t={t} onClose={()=>setDialog(null)} onSave={draft=>run(()=>repository.reassess(record,draft),t('actionCompleted'))}/>} 
  {dialog==='outcome'&&<OutcomeDialog t={t} onClose={()=>setDialog(null)} onSave={draft=>run(()=>repository.complete(record,draft),t('clinicalRecords.outcomeSaved'))}/>} 
  {dialog==='void'&&<ReasonDialog title={t('clinicalRecords.deleteSurveillance')} t={t} reason={reason} setReason={setReason} onClose={()=>setDialog(null)} onSave={()=>run(()=>repository.voidCase(record,reason),t('clinicalRecords.surveillanceDeleted'))}/>} 
  </div>
}

function StagePanel({icon:Icon,title,action,children}){return <section className="clinical-panel full-panel"><div className="record-section-header"><div>{Icon&&<Icon size={17}/>}<strong>{title}</strong></div>{action}</div>{children}</section>}
function TagList({title,items=[]}){if(!items?.length)return null;return <><h4>{title}</h4><div className="tag-row">{items.map(x=><span className="clinical-tag" key={x}>{x}</span>)}</div></>}
function ClinicalSnapshot({record,t,fmtDate}){return <div className="clinical-data-grid"><StagePanel icon={ShieldCheck} title={t('clinicalAssessment')}><p>{record.assessment?.summary||t('clinicalRecords.notDocumented')}</p></StagePanel><StagePanel icon={Microscope} title={t('microbiology')}><p>{record.samples?.map(x=>x.organism).filter(Boolean).join(', ')||t('clinicalRecords.noSamplesRecorded')}</p></StagePanel><StagePanel icon={Pill} title={t('therapy')}><p>{record.therapy?.map(x=>x.antimicrobial).join(', ')||t('clinicalRecords.noTherapyRecorded')}</p></StagePanel><StagePanel icon={RefreshCcw} title={t('nextReview')}><p>{fmtDate(record.reviewDue)}</p></StagePanel></div>}
function Timeline({record,t,fmtDateTime}){return <section className="clinical-panel full-panel"><div className="record-section-header"><div><FileClock size={17}/><strong>{t('clinicalRecords.timeline')}</strong></div></div><div className="clinical-timeline">{(record.timeline||[]).map((x,i)=><article key={`${x.at}-${i}`}><div><header><strong>{t(x.type)||x.type}</strong><time>{fmtDateTime(x.at)}</time></header><p>{x.detail||'—'}</p><small>{x.actor||x.actorId||'—'}</small></div></article>)}</div></section>}
function CompletedReport({record,t,fmtDate,fmtDateTime}){const positive=(record.samples||[]).filter(x=>x.result==='positive');return <article className="surveillance-final-report"><header className="final-report-title"><div><span>{t('clinicalRecords.finalSurveillanceReport')}</span><h2>{record.patient}</h2><p>{record.id} · {fmtDate(record.startedAt)} → {fmtDate(record.completedAt||record.outcome?.date)}</p></div></header><Narrative number="01" title={t('clinicalAssessment')} text={record.assessment?.summary||t('clinicalRecords.notDocumented')}/><Narrative number="02" title={t('haiAmr')} text={record.haiClassification?`${record.haiClassification.type||''} · ${t(record.haiClassification.status)}`:t('clinicalRecords.notDocumented')}/><Narrative number="03" title={t('microbiology')} text={positive.map(x=>x.organism).filter(Boolean).join(', ')||t('clinicalRecords.noPositiveFindings')}/><Narrative number="04" title={t('therapy')} text={(record.therapy||[]).map(x=>x.antimicrobial).join(', ')||t('clinicalRecords.noTherapyRecorded')}/><Narrative number="05" title={t('isolation')} text={record.isolation?t(record.isolation.status):t('clinicalRecords.noIsolationRecorded')}/><Narrative number="06" title={t('reassessment')} text={(record.reassessments||[]).map(x=>`${fmtDate(x.date)}: ${t(x.status)}`).join(' · ')||t('clinicalRecords.noReassessmentRecorded')}/><Narrative number="07" title={t('outcome')} text={record.outcome?`${t(record.outcome.status)} · ${fmtDate(record.outcome.date)}`:t('clinicalRecords.notDocumented')}/><section className="final-report-course"><div className="final-report-section-heading"><span>08</span><h3>{t('clinicalRecords.courseSummary')}</h3></div><div className="course-timeline">{(record.timeline||[]).map((x,i)=><div key={`${x.at}-${i}`} className="course-event"><time>{fmtDateTime(x.at)}</time><span>{t(x.type)||x.type}</span><strong>{x.actor||x.actorId||'—'}</strong><p>{x.detail||'—'}</p></div>)}</div></section></article>}
function Narrative({number,title,text}){return <section className="final-report-narrative"><div className="final-report-section-heading"><span>{number}</span><h3>{title}</h3></div><p>{text}</p></section>}
function SurveillanceStartGuide({t}){const steps=[t('clinicalAssessment'),t('microbiology'),t('haiAmr'),t('therapy'),t('isolation'),t('reassessment'),t('outcome')];return <section className="surveillance-start-guide"><div className="start-guide-heading"><div><span className="eyebrow">{t('surveillanceJourney')}</span><h3>{t('clinicalRecords.howSurveillanceWorks')}</h3></div></div><div className="start-guide-flow">{steps.map((label,i)=><div key={label} className="start-guide-step"><span className="step-number">{String(i+1).padStart(2,'0')}</span><div><strong>{label}</strong></div>{i<steps.length-1&&<span className="step-arrow">→</span>}</div>)}</div></section>}

function SimpleDialog({title,t,onClose,onSave,children,disabled=false}){return <ObserverDialog title={title} width="wide" onClose={onClose}><div className="entry-grid">{children}</div><div className="dialog-actions"><Button variant="secondary" onClick={onClose}>{t('cancel')}</Button><SaveButton disabled={disabled} onClick={onSave}>{t('save')}</SaveButton></div></ObserverDialog>}
function AssessmentDialog({t,record,onClose,onSave}){const a=record.assessment||{};const [d,setD]=useState({date:String(a.date||new Date().toISOString()).slice(0,10),assessmentType:a.assessmentType||a.type||'suspected',classification:a.classification||'undetermined',summary:a.summary||'',signsSymptoms:(a.signsSymptoms||a.symptoms||[]).join(', '),riskFactors:(a.riskFactors||[]).join(', ')});const list=v=>v.split(',').map(x=>x.trim()).filter(Boolean);return <SimpleDialog title={t('clinicalAssessment')} t={t} onClose={onClose} onSave={()=>onSave({...d,signsSymptoms:list(d.signsSymptoms),riskFactors:list(d.riskFactors)})}><ManualDateField label={t('assessmentDate')} value={d.date} onChange={v=>setD(x=>({...x,date:v}))}/><label><span>{t('classification')}</span><select value={d.classification} onChange={e=>setD(x=>({...x,classification:e.target.value}))}><option value="infection">{t('infection')}</option><option value="colonization">{t('colonization')}</option><option value="no_infection">{t('noInfection')}</option><option value="undetermined">{t('undetermined')}</option></select></label><label className="entry-span-2"><span>{t('signsSymptoms')}</span><input value={d.signsSymptoms} onChange={e=>setD(x=>({...x,signsSymptoms:e.target.value}))}/></label><label className="entry-span-2"><span>{t('riskFactors')}</span><input value={d.riskFactors} onChange={e=>setD(x=>({...x,riskFactors:e.target.value}))}/></label><label className="entry-span-2"><span>{t('clinicalSummary')}</span><textarea rows={4} value={d.summary} onChange={e=>setD(x=>({...x,summary:e.target.value}))}/></label></SimpleDialog>}
function SampleDialog({t,onClose,onSave}){const [d,setD]=useState({type:'bloodCulture',source:'',priority:'routine'});return <SimpleDialog title={t('laboratoryRecords.newSample')} t={t} onClose={onClose} onSave={()=>onSave(d)}><label><span>{t('sampleType')}</span><select value={d.type} onChange={e=>setD(x=>({...x,type:e.target.value}))}><option value="bloodCulture">{t('bloodCulture')}</option><option value="urineCulture">{t('urineCulture')}</option><option value="respiratorySample">{t('respiratorySample')}</option><option value="woundCulture">{t('woundCulture')}</option><option value="other">{t('other')}</option></select></label><label><span>{t('clinicalSource')}</span><input value={d.source} onChange={e=>setD(x=>({...x,source:e.target.value}))}/></label><label><span>{t('priority')}</span><select value={d.priority} onChange={e=>setD(x=>({...x,priority:e.target.value}))}><option value="routine">{t('routine')}</option><option value="urgent">{t('urgent')}</option><option value="critical">{t('critical')}</option></select></label></SimpleDialog>}
function HaiDialog({t,onClose,onSave}){const [d,setD]=useState({status:'suspected',type:'',definitionSet:'ECDC',definitionVersion:'',rationale:''});return <SimpleDialog title={t('clinicalRecords.haiClassification')} t={t} onClose={onClose} onSave={()=>onSave(d)} disabled={!d.type}><label><span>{t('type')}</span><input value={d.type} onChange={e=>setD(x=>({...x,type:e.target.value}))}/></label><label><span>{t('status')}</span><select value={d.status} onChange={e=>setD(x=>({...x,status:e.target.value}))}><option value="suspected">{t('suspected')}</option><option value="probable">{t('probable')}</option><option value="confirmed">{t('confirmed')}</option><option value="excluded">{t('excluded')}</option></select></label><label><span>{t('source')}</span><input value={d.definitionSet} onChange={e=>setD(x=>({...x,definitionSet:e.target.value}))}/></label><label className="entry-span-2"><span>{t('rationale')}</span><textarea rows={3} value={d.rationale} onChange={e=>setD(x=>({...x,rationale:e.target.value}))}/></label></SimpleDialog>}
function AmrDialog({t,onClose,onSave}){const [d,setD]=useState({classification:'MDR',definitionSource:'ECDC',definitionVersion:'current',status:'proposed',rationale:''});return <SimpleDialog title={t('classifyResistance')} t={t} onClose={onClose} onSave={()=>onSave(d)}><label><span>{t('classification')}</span><select value={d.classification} onChange={e=>setD(x=>({...x,classification:e.target.value}))}><option>MDR</option><option>XDR</option><option>PDR</option></select></label><label><span>{t('source')}</span><input value={d.definitionSource} onChange={e=>setD(x=>({...x,definitionSource:e.target.value}))}/></label><label className="entry-span-2"><span>{t('rationale')}</span><textarea value={d.rationale} onChange={e=>setD(x=>({...x,rationale:e.target.value}))}/></label></SimpleDialog>}
function TherapyDialog({t,onClose,onSave}){const [d,setD]=useState({antimicrobial:'',dose:'',route:'IV',indication:'',startedAt:new Date().toISOString().slice(0,10),plannedEndAt:'',approvalStatus:'not_required'});return <SimpleDialog title={t('therapy')} t={t} onClose={onClose} onSave={()=>onSave(d)} disabled={!d.antimicrobial}><label><span>{t('antibiotic')}</span><input value={d.antimicrobial} onChange={e=>setD(x=>({...x,antimicrobial:e.target.value}))}/></label><label><span>{t('dose')}</span><input value={d.dose} onChange={e=>setD(x=>({...x,dose:e.target.value}))}/></label><label><span>{t('route')}</span><input value={d.route} onChange={e=>setD(x=>({...x,route:e.target.value}))}/></label><label><span>{t('indication')}</span><input value={d.indication} onChange={e=>setD(x=>({...x,indication:e.target.value}))}/></label><ManualDateField label={t('startDate')} value={d.startedAt} onChange={v=>setD(x=>({...x,startedAt:v}))}/><ManualDateField label={t('plannedEndDate')} optional value={d.plannedEndAt} onChange={v=>setD(x=>({...x,plannedEndAt:v}))}/></SimpleDialog>}
function IsolationDialog({t,onClose,onSave}){const [d,setD]=useState({precautions:['contact'],room:'',reason:'',startedAt:new Date().toISOString().slice(0,10),reviewDue:''});return <SimpleDialog title={t('isolation')} t={t} onClose={onClose} onSave={()=>onSave(d)} disabled={!d.reason}><label><span>{t('precautions')}</span><select value={d.precautions[0]} onChange={e=>setD(x=>({...x,precautions:[e.target.value]}))}><option value="contact">{t('contact')}</option><option value="droplet">{t('droplet')}</option><option value="airborne">{t('airborne')}</option></select></label><label><span>{t('room')}</span><input value={d.room} onChange={e=>setD(x=>({...x,room:e.target.value}))}/></label><ManualDateField label={t('startDate')} value={d.startedAt} onChange={v=>setD(x=>({...x,startedAt:v}))}/><ManualDateField label={t('nextReview')} optional value={d.reviewDue} onChange={v=>setD(x=>({...x,reviewDue:v}))}/><label className="entry-span-2"><span>{t('reason')}</span><textarea value={d.reason} onChange={e=>setD(x=>({...x,reason:e.target.value}))}/></label></SimpleDialog>}
function EndDialog({title,t,onClose,onSave}){const [d,setD]=useState({endedAt:new Date().toISOString().slice(0,10),reason:''});return <SimpleDialog title={title} t={t} onClose={onClose} onSave={()=>onSave(d)}><ManualDateField label={t('endDate')} value={d.endedAt} onChange={v=>setD(x=>({...x,endedAt:v}))}/><label className="entry-span-2"><span>{t('reason')}</span><textarea value={d.reason} onChange={e=>setD(x=>({...x,reason:e.target.value}))}/></label></SimpleDialog>}
function ReassessmentDialog({t,onClose,onSave}){const [d,setD]=useState({date:new Date().toISOString().slice(0,10),status:'stable',decision:'continueTreatment',notes:'',nextReviewDue:''});return <SimpleDialog title={t('reassessment')} t={t} onClose={onClose} onSave={()=>onSave(d)}><ManualDateField label={t('date')} value={d.date} onChange={v=>setD(x=>({...x,date:v}))}/><label><span>{t('status')}</span><select value={d.status} onChange={e=>setD(x=>({...x,status:e.target.value}))}><option value="clinicalImprovement">{t('clinicalImprovement')}</option><option value="stable">{t('stable')}</option><option value="deterioration">{t('deterioration')}</option></select></label><ManualDateField label={t('nextReview')} optional value={d.nextReviewDue} onChange={v=>setD(x=>({...x,nextReviewDue:v}))}/><label className="entry-span-2"><span>{t('notes')}</span><textarea value={d.notes} onChange={e=>setD(x=>({...x,notes:e.target.value}))}/></label></SimpleDialog>}
function OutcomeDialog({t,onClose,onSave}){const [d,setD]=useState({status:'resolved',date:new Date().toISOString().slice(0,10),notes:''});return <SimpleDialog title={t('outcome')} t={t} onClose={onClose} onSave={()=>onSave(d)}><label><span>{t('status')}</span><select value={d.status} onChange={e=>setD(x=>({...x,status:e.target.value}))}><option value="resolved">{t('resolved')}</option><option value="improved">{t('improved')}</option><option value="transferred">{t('transferred')}</option><option value="deceased">{t('deceased')}</option></select></label><ManualDateField label={t('date')} value={d.date} onChange={v=>setD(x=>({...x,date:v}))}/><label className="entry-span-2"><span>{t('notes')}</span><textarea value={d.notes} onChange={e=>setD(x=>({...x,notes:e.target.value}))}/></label></SimpleDialog>}
function ReasonDialog({title,t,reason,setReason,onClose,onSave}){return <SimpleDialog title={title} t={t} onClose={onClose} onSave={onSave} disabled={!reason.trim()}><label className="entry-span-2"><span>{t('reasonRequired')}</span><textarea rows={4} value={reason} onChange={e=>setReason(e.target.value)} autoFocus/></label></SimpleDialog>}
