import { useMemo, useState } from 'react'
import { BookOpen, Search, X } from 'lucide-react'
import { APP_VERSION, BUILD_ID } from '../version'
import { useLocation } from 'react-router-dom'
import { helpSections, glossary } from './helpContent'
import { useLanguage } from '../i18n/LanguageContext'
import { useTenant } from '../tenant/TenantContext'
import { navigationFor } from '../../app/navigation'

export function HelpCenter({ open, onClose }) {
  const { pathname } = useLocation(); const { language, t } = useLanguage(); const { role, membership } = useTenant(); const [tab, setTab] = useState('context'); const [query, setQuery] = useState('')
  const item = helpSections[pathname] ?? helpSections[Object.keys(helpSections).find((key) => key !== '/' && pathname.startsWith(key))] ?? helpSections['/']
  const nav = navigationFor({ role, addOns: membership?.capabilities ?? [], customCapabilities: membership?.customCapabilities ?? [], hasAssignments: Boolean(membership?.assignments?.length) })
  const visibleHelp = nav.map((entry) => ({ ...entry, help: helpSections[entry.to] })).filter((entry) => entry.help)
  const terms = useMemo(() => glossary.filter((g) => `${g.term} ${g.el} ${g.en}`.toLowerCase().includes(query.toLowerCase())), [query])
  if (!open) return null
  return <div className="help-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><aside className="help-drawer"><header><div><BookOpen size={19}/><strong>{t('helpCenter')}</strong></div><button onClick={onClose}><X size={18}/></button></header><div className="tabs"><button className={`tab ${tab==='context'?'active':''}`} onClick={() => setTab('context')}>{t('thisSection')}</button><button className={`tab ${tab==='guide'?'active':''}`} onClick={() => setTab('guide')}>{t('myGuide')}</button><button className={`tab ${tab==='glossary'?'active':''}`} onClick={() => setTab('glossary')}>{t('glossary')}</button><button className={`tab ${tab==='info'?'active':''}`} onClick={() => setTab('info')}>Info</button></div>{tab==='context' && <div className="help-content"><h2>{item.title[language==='el'?0:1]}</h2><p>{item.body[language==='el'?0:1]}</p><div className="help-tip">{t('helpPermissionTip')}</div></div>}{tab==='guide' && <div className="help-content"><p>{t('roleGuideIntro')}</p>{visibleHelp.map((entry) => <section key={entry.to}><h3>{entry.help.title[language==='el'?0:1]}</h3><p>{entry.help.body[language==='el'?0:1]}</p></section>)}</div>}{tab==='glossary' && <div className="help-content"><label className="clinical-search"><Search size={15}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder={t('searchGlossary')}/></label><div className="glossary-list">{terms.map((g)=><div key={g.term}><strong>{g.term}</strong><span>{language==='el'?g.el:g.en}</span></div>)}</div></div>}{tab==='info' && <div className="help-content help-info-content">
  <section className="help-info-hero"><span>LIMOXIS OBSERVER</span><h2>Hospital Infection Prevention & Surveillance</h2><p>Ενιαίο περιβάλλον για επιτήρηση λοιμώξεων, πρόληψη, εργαστήριο, εργαζομένους, ποιότητα, εκπαίδευση, επιτροπές και διοικητική διακυβέρνηση.</p><div className="help-info-version"><strong>Έκδοση {APP_VERSION}</strong><span>Build {BUILD_ID}</span></div></section>
  <section className="help-info-block"><h3>Τι είναι το Limoxis Observer</h3><p>Το Limoxis Observer οργανώνει την καθημερινή εργασία πρόληψης και ελέγχου λοιμώξεων σε ένα role-aware σύστημα. Κάθε χρήστης βλέπει τις ενότητες, τις εκκρεμότητες, τις ανακοινώσεις και τα δεδομένα που αντιστοιχούν στον ρόλο και το scope του.</p></section>
  <section className="help-info-columns"><div><h3>Κύριες δυνατότητες</h3><ul><li>Κλινική επιτήρηση και απομόνωση</li><li>Εργαστηριακά αποτελέσματα και μικροβιακή αντοχή</li><li>Πρόληψη, Hand Hygiene και prevention bundles</li><li>Δείκτες, ποιότητα και traceability</li><li>Εκπαίδευση, επιτροπές και εργαζόμενοι</li><li>LIRA operational intelligence</li></ul></div><div><h3>Αρχές λειτουργίας</h3><ul><li>Role-based access και scope</li><li>Audit trail και ελεγχόμενες διορθώσεις</li><li>Κεντρικές βιβλιοθήκες και governed content</li><li>Σταθερά UI patterns σε όλη την εφαρμογή</li><li>Ειδοποιήσεις και στοχευμένες ανακοινώσεις</li><li>EL / EN περιβάλλον</li></ul></div></section>
  <section className="help-info-block"><h3>Η εφαρμογή στην πράξη</h3><p>Εδώ θα ενσωματωθούν πραγματικές εικόνες από την παραγωγική εγκατάσταση του Limoxis Observer μόλις το νέο Netlify deployment είναι διαθέσιμο. Δεν χρησιμοποιούνται mockups ως εικόνες του προϊόντος.</p><div className="help-info-screens"><div><strong>Dashboard</strong><span>Role-aware αρχική εικόνα</span></div><div><strong>Surveillance</strong><span>Κλινική επιτήρηση & follow-up</span></div><div><strong>Prevention</strong><span>Bundles και καταγραφές πρόληψης</span></div></div></section>
  <section className="help-info-footer"><strong>Limoxis Observer</strong><span>Designed for hospital infection prevention, surveillance and governance.</span></section>
</div>}</aside></div>
}
