export const helpSections={
  '/':{title:['Αρχική εικόνα','Home workspace'],body:['Η αρχική οθόνη προσαρμόζεται στον ρόλο, το τμήμα, τις πρόσθετες αρμοδιότητες και τις αναθέσεις σας. Εμφανίζει μόνο όσα χρειάζονται προσοχή και όσα δικαιούστε να γνωρίζετε.','Your home workspace adapts to your role, department scope, additional responsibilities and assignments. It shows only what needs attention and what you are authorized to know.']},
  '/my-department':{title:['Το τμήμα μου','My department'],body:['Τμηματική εικόνα με τις δικές σας εκκρεμότητες, εργασίες και επιτρεπόμενες πληροφορίες. Ο προϊστάμενος βλέπει ευρύτερη λειτουργική εικόνα από τον απλό χρήστη.','A department workspace for your tasks, assignments and permitted information. Department managers see a broader operational view than standard users.']},
  '/my-profile':{title:['Η καρτέλα μου','My profile'],body:['Προσωπική καρτέλα εργαζομένου με στοιχεία, εκπαιδεύσεις και όσα δεδομένα επιτρέπεται να βλέπετε. Διοικητικά ή ιατρικά στοιχεία δεν αλλάζουν χωρίς το κατάλληλο δικαίωμα.','Your employee record with personal details, training and information you are permitted to view. Administrative or occupational-health data cannot be changed without the appropriate permission.']},
  '/patients':{title:['Ασθενείς','Patients'],body:['Μητρώο ασθενών για αναζήτηση, δημιουργία και πρόσβαση στο ιστορικό επιτήρησης. Δημιουργία, επεξεργασία, διαγραφή, επισυνάψεις, εκτύπωση και export ελέγχονται από τον ρόλο και το scope.','Patient registry for search, creation and access to surveillance history. Create, edit, delete, attachments, print and export are controlled by role and scope.']},
  '/surveillance':{title:['Επιτήρηση','Surveillance'],body:['Κάθε επεισόδιο είναι ένας ενιαίος φάκελος. Κλινική αξιολόγηση, HAI classification, μικροβιολογία/AMR, αγωγή, isolation, συσκευές και επανεκτιμήσεις εξελίσσονται παράλληλα και καταγράφονται στο timeline.','Each episode is one coordinated record. Clinical assessment, HAI classification, microbiology/AMR, therapy, isolation, devices and reassessments progress in parallel and are recorded on the timeline.']},
  '/laboratory':{title:['Εργαστήριο','Laboratory'],body:['Το Εργαστήριο είναι η πηγή αλήθειας για δείγματα, αποτελέσματα, AST και επικοινωνία κρίσιμων αποτελεσμάτων. Η Επιτήρηση χρησιμοποιεί τα ίδια δεδομένα χωρίς διπλοκαταχώρηση.','The Laboratory is the source of truth for samples, results, AST and critical-result communication. Surveillance reuses the same data without duplicate entry.']},
  '/prevention':{title:['Πρόληψη','Prevention'],body:['Περιλαμβάνει λειτουργίες όπως WHO υγιεινή χεριών, bundles, αντισηπτικά, απόβλητα και άλλες δράσεις πρόληψης. Οι υποενότητες εμφανίζονται μόνο όταν ο ρόλος ή capability το επιτρέπει.','Includes WHO hand hygiene, bundles, antiseptics, waste and other prevention activities. Subareas appear only when the user role or capability permits them.']},
  '/controls':{title:['Έλεγχοι','Controls'],body:['Εδώ εκτελείτε ελέγχους που έχουν ανατεθεί σε εσάς ή στο τμήμα σας. Συμπληρώνετε αποτέλεσμα και τεκμηρίωση, αλλά δεν αλλάζετε πρόγραμμα, συχνότητα ή governance χωρίς διαχειριστικό δικαίωμα.','Execute controls assigned to you or your department. You record results and evidence, but cannot change schedule, frequency or governance without management permission.']},
  '/quality':{title:['Κέντρο Ποιότητας','Quality Center'],body:['Συμβάντα, audits, findings, CAPA και δείκτες ποιότητας συνδέονται σε ελεγχόμενη ροή. Οι κρίσιμες αλλαγές και εγκρίσεις διατηρούν ιχνηλασιμότητα.','Incidents, audits, findings, CAPA and quality indicators are connected in a governed workflow. Critical changes and approvals retain traceability.']},
  '/indicators':{title:['Δείκτες','Indicators'],body:['Οι δείκτες έχουν versioned ορισμό, αριθμητή, παρονομαστή, περίοδο και drill-down. Οι κλινοημέρες και αργότερα device-days αποτελούν κοινές πηγές denominator όπου απαιτείται.','Indicators use versioned definitions with numerator, denominator, period and drill-down. Patient-days and later device-days provide shared denominator sources where required.']},
  '/training':{title:['Εκπαίδευση','Training'],body:['Οι διαχειριστές οργανώνουν προγράμματα, συμμετέχοντες και ολοκληρώσεις. Ο εργαζόμενος βλέπει μόνο τις δικές του ανατεθειμένες/ολοκληρωμένες εκπαιδεύσεις και πιστοποιητικά.','Managers organize programs, participants and completion. Employees see only their own assigned/completed training and certificates.']},
  '/committees':{title:['Επιτροπές','Committees'],body:['Διαχείριση συνεδριάσεων, θεμάτων, πρακτικών, αποφάσεων και παρακολούθησης ενεργειών. Η πρόσβαση σε κλινικά δεδομένα δεν παρέχεται αυτόματα λόγω συμμετοχής σε επιτροπή.','Manage meetings, agenda items, minutes, decisions and action follow-up. Committee participation does not automatically grant clinical data access.']},
  '/documents':{title:['Έγγραφα','Documents'],body:['Προβάλλονται τα έγγραφα που έχουν κοινοποιηθεί στον χρήστη ή στο τμήμα του. Δημιουργία, αλλαγή και controlled copies απαιτούν αντίστοιχα δικαιώματα.','Shows documents shared with the user or department. Creation, modification and controlled copies require the corresponding permissions.']},
  '/employees':{title:['Εργαζόμενοι','Employees'],body:['Διοικητικό μητρώο εργαζομένων με αυστηρό διαχωρισμό από τα ευαίσθητα δεδομένα Ιατρού Εργασίας. Το HR δεν αποκτά πρόσβαση σε ιατρικές επισκέψεις επειδή διαχειρίζεται προσωπικό.','Administrative employee registry strictly separated from Occupational Health data. HR does not gain access to medical visits simply because it manages staff records.']},
  '/pharmacy':{title:['Φαρμακείο','Pharmacy'],body:['Αντιμικροβιακή επιτήρηση, προωθημένα αντιβιοτικά, εγκρίσεις και κατανάλωση. Η αγωγή συνδέεται με την κλινική επιτήρηση χωρίς διπλοκαταχώρηση.','Antimicrobial stewardship, restricted antibiotics, approvals and consumption. Therapy is linked to clinical surveillance without duplicate entry.']},
  '/occupational-health':{title:['Ιατρός Εργασίας','Occupational Health'],body:['Επισκέψεις, εμβολιασμοί και follow-up εργαζομένων με πρόσβαση μόνο σε εξουσιοδοτημένους ρόλους. Τα κλινικά δεδομένα παραμένουν διαχωρισμένα από το HR.','Employee visits, vaccination and follow-up restricted to authorized roles. Clinical occupational-health data remains separated from HR.']},
  '/lira':{title:['LIRA AI','LIRA AI'],body:['Η LIRA λειτουργεί μόνο πάνω σε δεδομένα που ο συγκεκριμένος χρήστης ήδη δικαιούται να δει. Δεν αλλάζει κλινικό ή διοικητικό record χωρίς ρητή ενέργεια εξουσιοδοτημένου χρήστη.','LIRA operates only on data the current user is already authorized to view. It never changes a clinical or administrative record without an explicit authorized user action.']},
  '/management':{title:['Κέντρο Διαχείρισης','Management Center'],body:['Διαχείριση οργανισμού, χρηστών, custom ρόλων/capabilities, τμημάτων, βιβλιοθηκών, κλινοημερών, δεικτών και εξωτερικών πηγών. Οι κρίσιμες αλλαγές είναι auditable.','Manage organization, users, custom roles/capabilities, departments, libraries, patient-days, indicators and external references. Critical changes are auditable.']},
}

export const glossary=[
  {term:'HAI',el:'Λοίμωξη σχετιζόμενη με την παροχή φροντίδας υγείας.',en:'Healthcare-associated infection.'},{term:'IPC',el:'Πρόληψη και έλεγχος λοιμώξεων.',en:'Infection prevention and control.'},{term:'AMR',el:'Αντιμικροβιακή αντοχή.',en:'Antimicrobial resistance.'},{term:'AST',el:'Έλεγχος ευαισθησίας μικροοργανισμού σε αντιμικροβιακούς παράγοντες.',en:'Antimicrobial susceptibility testing.'},{term:'MDR',el:'Πολυανθεκτικός μικροοργανισμός σύμφωνα με τον ενεργό, εκδοσιοποιημένο ορισμό.',en:'Multidrug-resistant organism according to the active versioned definition.'},{term:'XDR',el:'Εκτεταμένη αντοχή σύμφωνα με τον ενεργό, εκδοσιοποιημένο ορισμό.',en:'Extensively drug-resistant according to the active versioned definition.'},{term:'PDR',el:'Παν-ανθεκτικός μικροοργανισμός σύμφωνα με τον ενεργό, εκδοσιοποιημένο ορισμό.',en:'Pandrug-resistant organism according to the active versioned definition.'},{term:'DDD',el:'Καθορισμένη ημερήσια δόση· χρησιμοποιείται σε δείκτες κατανάλωσης αντιμικροβιακών.',en:'Defined daily dose; used in antimicrobial consumption indicators.'},{term:'PPS',el:'Μελέτη σημειακού επιπολασμού.',en:'Point prevalence survey.'},{term:'BSI',el:'Λοίμωξη αιματικής ροής / βακτηριαιμία ανάλογα με τον εφαρμοζόμενο ορισμό.',en:'Bloodstream infection, according to the applicable definition.'},{term:'CLABSI',el:'Λοίμωξη αιματικής ροής σχετιζόμενη με κεντρικό φλεβικό καθετήρα.',en:'Central line-associated bloodstream infection.'},{term:'CAUTI',el:'Λοίμωξη ουροποιητικού σχετιζόμενη με ουροκαθετήρα.',en:'Catheter-associated urinary tract infection.'},{term:'VAP',el:'Πνευμονία σχετιζόμενη με μηχανικό αερισμό.',en:'Ventilator-associated pneumonia.'},{term:'Patient-days',el:'Κλινοημέρες: άθροισμα ημερήσιων νοσηλευόμενων ασθενών για συγκεκριμένη περίοδο/τμήμα.',en:'Patient-days: sum of daily admitted-patient counts for a defined period/department.'},{term:'Device-days',el:'Ημέρες έκθεσης σε συγκεκριμένη συσκευή, ως denominator για device-associated δείκτες.',en:'Days of exposure to a specific device, used as denominator for device-associated indicators.'},
]
