import { useEffect,useMemo,useState } from 'react'
import { BarChart3,Building2,CalendarClock,ChevronRight,Plus,ShieldCheck,Users } from 'lucide-react'
import { Page } from '../../design-system/Page'
import { Card,CardHeader } from '../../design-system/Card'
import { Button } from '../../design-system/Button'
import { ManualDateField } from '../../design-system/ManualDateField'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { createOrganization,loadPlatformSnapshot,saveDemoEntitlement } from './platformService'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { useNavigate } from 'react-router-dom'

const text={
 el:{subtitle:'Διαχείριση οργανισμών, Hospital Admins, Demo πρόσβασης και συνολικής εικόνας της πλατφόρμας.',orgs:'Οργανισμοί',users:'Χρήστες',demo:'Demo πρόσβαση',reports:'Global Reports',newOrg:'Νέο νοσοκομείο',name:'Επωνυμία',code:'Κωδικός',region:'Περιφέρεια',city:'Πόλη',adminEmail:'Email αρχικού Hospital Admin',adminName:'Όνομα Admin',save:'Δημιουργία',validFrom:'Έναρξη',validUntil:'Λήξη',enableDemo:'Ενεργοποίηση Demo',active:'Ενεργό',inactive:'Ανενεργό',open:'Άνοιγμα',admins:'Hospital Admins',noAdmins:'Δεν υπάρχουν συνδεδεμένοι admins.',platformGovernance:'Οι platform ενέργειες είναι διαθέσιμες μόνο στον Platform Owner και καταγράφονται στο audit trail.'},
 en:{subtitle:'Manage organizations, Hospital Admins, Demo access and the platform-wide overview.',orgs:'Organizations',users:'Users',demo:'Demo access',reports:'Global Reports',newOrg:'New hospital',name:'Name',code:'Code',region:'Region',city:'City',adminEmail:'Initial Hospital Admin email',adminName:'Admin name',save:'Create',validFrom:'Valid from',validUntil:'Valid until',enableDemo:'Enable Demo',active:'Active',inactive:'Inactive',open:'Open',admins:'Hospital Admins',noAdmins:'No connected admins.',platformGovernance:'Platform actions are available only to the Platform Owner and are recorded in the audit trail.'}
}
export function PlatformCenterPage(){
 const {language}=useLanguage(),x=text[language];const {notify}=useFeedback();const navigate=useNavigate();const [data,setData]=useState({organizations:[],members:[],entitlements:[]});const [loading,setLoading]=useState(true);const [showOrg,setShowOrg]=useState(false);const [draft,setDraft]=useState({name:'',code:'',type:'hospital',region:'',city:'',adminEmail:'',adminName:''});const [demoDraft,setDemoDraft]=useState({organization_id:'',valid_from:new Date().toISOString().slice(0,10),valid_until:'',status:'active',scope_type:'organization'})
 async function refresh(){setLoading(true);try{setData(await loadPlatformSnapshot())}finally{setLoading(false)}}
 useEffect(()=>{refresh()},[])
 const activeDemo=useMemo(()=>data.entitlements.filter(e=>e.status==='active'&&(!e.valid_until||e.valid_until>=new Date().toISOString().slice(0,10))).length,[data])
 async function addOrg(e){e.preventDefault();await createOrganization(draft);setDraft({name:'',code:'',type:'hospital',region:'',city:'',adminEmail:'',adminName:''});setShowOrg(false);notify(language==='el'?'Ο οργανισμός δημιουργήθηκε.':'Organization created.','success');refresh()}
 async function addDemo(e){e.preventDefault();if(!demoDraft.organization_id)return;await saveDemoEntitlement({...demoDraft,scope_id:demoDraft.organization_id});notify(language==='el'?'Η Demo πρόσβαση ενεργοποιήθηκε.':'Demo access enabled.','success');refresh()}
 return <Page title={language==='el'?'Κέντρο Πλατφόρμας':'Platform Center'} subtitle={x.subtitle} actions={<Button onClick={()=>setShowOrg(v=>!v)}><Plus size={16}/>{x.newOrg}</Button>}>
  <div className="platform-kpi-grid"><Card><CardHeader icon={Building2} title={x.orgs}/><div className="platform-kpi-value">{data.organizations.length}</div></Card><Card><CardHeader icon={Users} title={x.users}/><div className="platform-kpi-value">{data.members.length}</div></Card><Card><CardHeader icon={CalendarClock} title={x.demo}/><div className="platform-kpi-value">{activeDemo}</div></Card><Card className="platform-kpi-action" onClick={()=>navigate('/platform/reports')}><CardHeader icon={BarChart3} title={x.reports}/><div className="platform-open-report">{x.open}<ChevronRight size={16}/></div></Card></div>
  <div className="platform-governance"><ShieldCheck size={17}/>{x.platformGovernance}</div>
  {showOrg&&<Card className="platform-form-card"><CardHeader title={x.newOrg}/><form className="platform-form-grid" onSubmit={addOrg}><label>{x.name}<input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>{x.code}<input required value={draft.code} onChange={e=>setDraft({...draft,code:e.target.value.toUpperCase()})}/></label><label>{x.region}<input value={draft.region} onChange={e=>setDraft({...draft,region:e.target.value})}/></label><label>{x.city}<input value={draft.city} onChange={e=>setDraft({...draft,city:e.target.value})}/></label><label>{x.adminName}<input value={draft.adminName} onChange={e=>setDraft({...draft,adminName:e.target.value})}/></label><label>{x.adminEmail}<input type="email" value={draft.adminEmail} onChange={e=>setDraft({...draft,adminEmail:e.target.value})}/></label><div className="platform-form-actions"><Button type="submit">{x.save}</Button></div></form></Card>}
  <Card><CardHeader title={x.orgs}/><div className="platform-table-wrap"><table className="platform-table"><thead><tr><th>{x.name}</th><th>{x.code}</th><th>{x.region}</th><th>{x.admins}</th><th>{x.demo}</th></tr></thead><tbody>{data.organizations.map(org=>{const members=data.members.filter(m=>m.organization_id===org.id);const ent=data.entitlements.find(e=>e.organization_id===org.id&&e.status==='active');return <tr key={org.id}><td><strong>{org.name}</strong><small>{org.city||'—'}</small></td><td>{org.code}</td><td>{org.region||'—'}</td><td>{members.filter(m=>m.role==='hospital_admin').length}</td><td><span className={`platform-status ${ent?'active':'inactive'}`}>{ent?x.active:x.inactive}</span></td></tr>})}</tbody></table></div></Card>
  <Card className="platform-demo-card"><CardHeader icon={CalendarClock} title={x.demo}/><form className="platform-form-grid" onSubmit={addDemo}><label>{x.orgs}<select required value={demoDraft.organization_id} onChange={e=>setDemoDraft({...demoDraft,organization_id:e.target.value})}><option value="">—</option>{data.organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><ManualDateField label={x.validFrom} value={demoDraft.valid_from} onChange={value=>setDemoDraft({...demoDraft,valid_from:value})}/><ManualDateField label={x.validUntil} value={demoDraft.valid_until} onChange={value=>setDemoDraft({...demoDraft,valid_until:value})}/><div className="platform-form-actions"><Button type="submit">{x.enableDemo}</Button></div></form></Card>
  {loading&&<div className="platform-loading">…</div>}
 </Page>
}
