import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
function esc(v:string){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c] as string))}
function shell(title:string,body:string,preheader='Limoxis Observer notification'){
 return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>${esc(title)}</title></head><body style="margin:0;background:#edf3f7;font-family:Arial,Helvetica,sans-serif;color:#17324a"><div style="display:none;max-height:0;overflow:hidden">${esc(preheader)}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#edf3f7;padding:24px 12px"><tr><td align="center"><table role="presentation" width="620" cellspacing="0" cellpadding="0" style="width:100%;max-width:620px;background:#fff;border:1px solid #dbe5ec;border-radius:16px;overflow:hidden"><tr><td style="background:#123f68;padding:28px 34px;color:#fff"><div style="font-size:26px;font-weight:800;letter-spacing:-.3px">Limoxis Observer</div><div style="font-size:14px;margin-top:7px;opacity:.88">Πρόληψη λοιμώξεων · Επιτήρηση · Ποιότητα</div></td></tr><tr><td style="padding:32px 34px">${body}<div style="border-top:1px solid #e4ebf0;margin-top:30px;padding-top:18px;font-size:12px;line-height:1.55;color:#718295">Το μήνυμα δημιουργήθηκε αυτόματα από το Limoxis Observer. Μην προωθείτε προσωπικούς συνδέσμους ενεργοποίησης ή ανάκτησης πρόσβασης.</div></td></tr></table></td></tr></table></body></html>`
}
const button=(label:string,url:string)=>`<p style="margin:28px 0"><a href="${esc(url)}" style="display:inline-block;background:#0f6f7c;color:#fff;text-decoration:none;padding:13px 22px;border-radius:9px;font-weight:700">${esc(label)}</a></p>`
const info=(rows:Array<[string,string]>)=>`<div style="background:#f3f8fa;border:1px solid #dce8ed;border-radius:12px;padding:17px 19px;margin:22px 0">${rows.map(([a,b])=>`<div style="margin:5px 0"><strong>${esc(a)}:</strong> ${esc(b)}</div>`).join('')}</div>`
function invitationEmail({fullName,orgName,username,role='Hospital Admin',activationUrl,resend=false}:{fullName:string,orgName:string,username:string,role?:string,activationUrl:string,resend?:boolean}){
 const body=`<p style="font-size:20px;margin-top:0">Καλησπέρα ${esc(fullName||'')},</p><p style="font-size:16px;line-height:1.65">${resend?'Η πρόσκλησή σας επαναποστάλθηκε.':'Έχετε προσκληθεί να δημιουργήσετε λογαριασμό'} στο Limoxis Observer για το <strong>${esc(orgName)}</strong>.</p>${info([['Όνομα χρήστη',username],['Ρόλος',role]])}<p style="font-size:15px;line-height:1.6">Πατήστε το ασφαλές κουμπί για να ορίσετε τον προσωπικό σας κωδικό πρόσβασης και να ενεργοποιήσετε τον λογαριασμό σας.</p>${button('Αποδοχή πρόσκλησης',activationUrl)}<p style="font-size:12px;color:#718295">Ο σύνδεσμος είναι προσωπικός και λήγει σε 72 ώρες.${resend?' Προηγούμενοι σύνδεσμοι έχουν ακυρωθεί.':''}</p>`
 return shell('Πρόσκληση στο Limoxis Observer',body,'Πρόσκληση ενεργοποίησης λογαριασμού')
}
function passwordResetEmail({fullName,actionUrl}:{fullName?:string,actionUrl:string}){return shell('Επαναφορά κωδικού',`<p style="font-size:20px;margin-top:0">${fullName?`Καλησπέρα ${esc(fullName)},`:'Επαναφορά κωδικού πρόσβασης'}</p><p style="font-size:16px;line-height:1.65">Λάβαμε αίτημα για ορισμό νέου κωδικού πρόσβασης. Αν το ζητήσατε εσείς, συνεχίστε από το ασφαλές κουμπί.</p>${button('Ορισμός νέου κωδικού',actionUrl)}<p style="font-size:12px;color:#718295">Αν δεν ζητήσατε αλλαγή κωδικού, αγνοήστε αυτό το μήνυμα.</p>`)}
function usernameReminderEmail({fullName,username}:{fullName?:string,username:string}){return shell('Υπενθύμιση username',`<p style="font-size:20px;margin-top:0">${fullName?`Καλησπέρα ${esc(fullName)},`:'Στοιχεία λογαριασμού'}</p><p style="font-size:16px">Το username του λογαριασμού σας είναι:</p>${info([['Username',username]])}<p style="font-size:13px;color:#718295">Για λόγους ασφαλείας δεν αποστέλλουμε ποτέ τον κωδικό πρόσβασής σας μέσω email.</p>`)}
function demoAccessEmail({contactName,label,username,validFrom,validUntil,actionUrl}:{contactName?:string,label:string,username:string,validFrom:string,validUntil:string,actionUrl:string}){return shell('Demo πρόσβαση Limoxis Observer',`<p style="font-size:20px;margin-top:0">${contactName?`Καλησπέρα ${esc(contactName)},`:'Demo πρόσβαση'}</p><p style="font-size:16px;line-height:1.65">Ενεργοποιήθηκε απομονωμένο Demo περιβάλλον για <strong>${esc(label)}</strong>.</p>${info([['Username',username],['Ισχύς',`${validFrom} έως ${validUntil}`]])}<p style="font-size:15px;line-height:1.6">Τα δεδομένα του Demo είναι συνθετικά και δεν συνδέονται με πραγματικά δεδομένα νοσοκομείων.</p>${button('Ενεργοποίηση Demo',actionUrl)}`)}

const cors={'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'}
const reply=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:cors})
const ascii=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Za-z]/g,'').toUpperCase()
Deno.serve(async(req)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return reply({error:'Method not allowed'},405)
 const url=Deno.env.get('SUPABASE_URL')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,jwt=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'')
 const caller=createClient(url,anon,{global:{headers:{Authorization:`Bearer ${jwt}`}}}),admin=createClient(url,service)
 const {data:cu}=await caller.auth.getUser();if(!cu?.user)return reply({error:'Unauthorized'},401)
 const {data:owner}=await admin.from('profiles').select('is_platform_owner').eq('id',cu.user.id).maybeSingle();if(!owner?.is_platform_owner)return reply({error:'Forbidden'},403)
 const b=await req.json();const label=String(b.label||'').trim(),contactName=String(b.contactName||'').trim(),contactEmail=String(b.contactEmail||'').trim().toLowerCase(),validFrom=String(b.validFrom||''),validUntil=String(b.validUntil||'')
 if(!label||!contactEmail||!validFrom||!validUntil)return reply({error:'Missing demo fields.'},400)
 const parts=contactName.split(/\s+/).filter(Boolean),prefix=((ascii(parts[0]||'D')[0]||'D')+(ascii(parts.at(-1)||'U')[0]||'U'))
 let username='';for(let i=0;i<20;i++){const candidate=`${prefix}${Math.floor(10000+Math.random()*90000)}`;const {data:exists}=await admin.from('profiles').select('id').eq('username',candidate).maybeSingle();if(!exists){username=candidate;break}}
 if(!username)return reply({error:'Could not allocate username.'},500)
 const internalEmail=`${username.toLowerCase()}@users.limoxis.local`;const temporary=crypto.randomUUID()+crypto.randomUUID()
 const {data:created,error:createError}=await admin.auth.admin.createUser({email:internalEmail,password:temporary,email_confirm:true,user_metadata:{full_name:contactName||label}});if(createError||!created.user)return reply({error:createError?.message||'User creation failed'},500)
 const {data:ent,error:entError}=await admin.from('platform_demo_entitlements').insert({label,contact_name:contactName||null,contact_email:contactEmail,valid_from:validFrom,valid_until:validUntil,status:'active',created_by:cu.user.id,demo_user_id:created.user.id}).select().single();if(entError){await admin.auth.admin.deleteUser(created.user.id);return reply({error:entError.message},500)}
 await admin.from('profiles').update({full_name:contactName||label,username,contact_email:contactEmail,is_demo:true,demo_entitlement_id:ent.id}).eq('id',created.user.id)
 const app=(Deno.env.get('APP_URL')||req.headers.get('origin')||'').replace(/\/$/,'');const {data:link}=await admin.auth.admin.generateLink({type:'recovery',email:internalEmail,options:{redirectTo:`${app}/reset-password`}});const actionLink=(link as any)?.properties?.action_link||''
 const resend=Deno.env.get('RESEND_API_KEY');let emailSent=false
 if(resend&&actionLink){const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${resend}`,'Content-Type':'application/json'},body:JSON.stringify({from:Deno.env.get('INVITE_FROM_EMAIL')||'Limoxis Observer <noreply@limoxis.com>',to:[contactEmail],subject:'Πρόσβαση Demo — Limoxis Observer',html:demoAccessEmail({contactName,label,username,validFrom,validUntil,actionUrl:actionLink})})});emailSent=r.ok}
 return reply({ok:true,entitlement:ent,username,emailSent})
})
