// Labels and option lists shared by the laboratory sample record and its dialogs.
export const copy = {
  el: {
    reject: 'Απόρριψη δείγματος',
    rejectReason: 'Αιτιολογία απόρριψης',
    rejectHelp:
      'Το δείγμα δεν θα διαγραφεί. Θα σημανθεί ως απορριφθέν και η αιτιολογία θα παραμείνει στο ιστορικό.',
    rejected: 'Το δείγμα απορρίφθηκε και η αιτιολογία καταγράφηκε.',
    process: 'Έναρξη επεξεργασίας',
    processing: 'Η επεξεργασία του δείγματος ξεκίνησε.',
    correction: 'Διόρθωση',
    correctionHelp:
      'Η εγγραφή είναι οριστικοποιημένη. Η διόρθωση την ξεκλειδώνει και καταγράφεται στο ιστορικό.',
    finalize: 'Οριστικοποίηση',
    finalizeRecord: 'Οριστικοποίηση εγγραφής',
    finalized: 'Η εργαστηριακή καταχώριση οριστικοποιήθηκε',
    finalizedReadOnly: 'Οριστικοποιημένη εργαστηριακή καταχώριση · μόνο για ανάγνωση',
    rejectedReadOnly: 'Απορριφθέν δείγμα · μόνο για ανάγνωση',
    method: 'Μέθοδος',
    status: 'Κατάσταση',
    draft: 'Πρόχειρο',
    validated: 'Επικυρωμένο',
    amended: 'Διορθωμένο',
    organisms: 'Μικροοργανισμοί',
    organism: 'Μικροοργανισμός',
    chooseOrganism: 'Επιλέξτε από τη Βιβλιοθήκη Μικροοργανισμών',
    antibiotic: 'Αντιβιοτικό',
    chooseAntibiotic: 'Επιλέξτε από τη Βιβλιοθήκη Αντιβιοτικών',
    critical: 'Κρίσιμο αποτέλεσμα',
    cfu: 'CFU',
    assessment: 'Αξιολόγηση',
    within: 'Εντός ορίων',
    outside: 'Εκτός ορίων',
    noLimit: 'Δεν υπάρχει ρυθμισμένο όριο',
    protocol: 'Το όριο εφαρμόζεται αυτόματα από το κεντρικά ρυθμισμένο πρωτόκολλο.',
    noProtocol: 'Δεν βρέθηκε πρωτόκολλο',
    documents: 'Ολοκλήρωση ελέγχου εγγράφων',
    documentsDone: 'Τα έγγραφα ελέγχθηκαν.',
    documentsHint: 'Ελέγξτε τα συνημμένα του δείγματος και επιβεβαιώστε ότι είναι πλήρη.',
    saveDraft: 'Αποθήκευση προχείρου',
    validate: 'Επικύρωση αποτελέσματος',
    enterResult: 'Καταχώριση αποτελέσματος',
    editResult: 'Επεξεργασία αποτελέσματος',
    addAst: 'Προσθήκη αντιβιογράμματος',
    classifyAmr: 'Ταξινόμηση AMR',
    changeAmr: 'Αλλαγή ταξινόμησης AMR',
    addCommunication: 'Καταγραφή επικοινωνίας',
    print: 'Εκτύπωση',
    export: 'Εξαγωγή JSON',
    stepReceive: 'Παραλαβή',
    stepResult: 'Αποτέλεσμα',
    stepAst: 'Αντιβιόγραμμα',
    stepCommunication: 'Επικοινωνία κρίσιμου',
    stepDocuments: 'Έλεγχος εγγράφων',
    stepFinalize: 'Οριστικοποίηση',
    hintReceive: 'Παραλάβετε το δείγμα και ξεκινήστε την επεξεργασία',
    hintResult: 'Καταχωρίστε και επικυρώστε το μικροβιολογικό αποτέλεσμα',
    hintAst: 'Καταχωρίστε αντιβιόγραμμα για κάθε μικροοργανισμό',
    hintCommunication: 'Τεκμηριώστε την ενημέρωση του κλινικού αποδέκτη',
    hintDocuments: 'Ελέγξτε τα συνημμένα του δείγματος',
    hintFinalize: 'Όλα τα βήματα ολοκληρώθηκαν — οριστικοποιήστε την εγγραφή',
    awaitingPermission: 'Αναμένεται ενέργεια από χρήστη με το αντίστοιχο δικαίωμα.',
    organismRequired:
      'Για επικύρωση θετικού αποτελέσματος απαιτείται τουλάχιστον ένας μικροοργανισμός.',
    noAst: 'Δεν έχει καταχωριστεί αντιβιόγραμμα.',
    noCommunication: 'Δεν έχει καταγραφεί ακόμη επικοινωνία.',
    noResult: 'Δεν έχει καταχωριστεί αποτέλεσμα.',
    standard: 'Πρότυπο',
    version: 'Έκδοση',
    notes: 'Σημειώσεις',
    recipient: 'Παραλήπτης',
    role: 'Ρόλος / ιδιότητα',
    department: 'Τμήμα',
    channel: 'Τρόπος επικοινωνίας',
    date: 'Ημερομηνία επικοινωνίας',
    time: 'Ώρα επικοινωνίας',
    readBack: 'Επιβεβαίωση ορθής επανάληψης (read-back)',
    classification: 'Κατηγορία',
    definitionSource: 'Πηγή ορισμού',
    definitionVersion: 'Έκδοση ορισμού',
    rationale: 'Τεκμηρίωση / αιτιολόγηση',
    amrTitle: 'Ταξινόμηση AMR',
    astTitle: 'Νέο αντιβιόγραμμα',
    communicationTitle: 'Επικοινωνία κρίσιμου αποτελέσματος',
    resultHelp: 'Ο μικροοργανισμός εμφανίζεται μόνο όταν το αποτέλεσμα είναι θετικό.',
  },
  en: {
    reject: 'Reject sample',
    rejectReason: 'Rejection reason',
    rejectHelp:
      'The sample will not be deleted. It will be marked as rejected and the reason kept in history.',
    rejected: 'The sample was rejected and the reason was recorded.',
    process: 'Start processing',
    processing: 'Sample processing has started.',
    correction: 'Correction',
    correctionHelp: 'This record is finalized. A correction unlocks it and is recorded in history.',
    finalize: 'Finalization',
    finalizeRecord: 'Finalize record',
    finalized: 'The laboratory record has been finalized',
    finalizedReadOnly: 'Finalized laboratory record · read only',
    rejectedReadOnly: 'Rejected sample · read only',
    method: 'Method',
    status: 'Status',
    draft: 'Draft',
    validated: 'Validated',
    amended: 'Amended',
    organisms: 'Microorganisms',
    organism: 'Microorganism',
    chooseOrganism: 'Select from the Microorganism Library',
    antibiotic: 'Antibiotic',
    chooseAntibiotic: 'Select from the Antibiotic Library',
    critical: 'Critical result',
    cfu: 'CFU',
    assessment: 'Assessment',
    within: 'Within limits',
    outside: 'Outside limits',
    noLimit: 'No configured limit',
    protocol: 'The limit is applied automatically from the centrally configured protocol.',
    noProtocol: 'No protocol configured',
    documents: 'Complete document review',
    documentsDone: 'Documents have been reviewed.',
    documentsHint: 'Review the sample attachments and confirm they are complete.',
    saveDraft: 'Save draft',
    validate: 'Validate result',
    enterResult: 'Enter result',
    editResult: 'Edit result',
    addAst: 'Add susceptibility test',
    classifyAmr: 'AMR classification',
    changeAmr: 'Change AMR classification',
    addCommunication: 'Record communication',
    print: 'Print',
    export: 'Export JSON',
    stepReceive: 'Receipt',
    stepResult: 'Result',
    stepAst: 'Susceptibility',
    stepCommunication: 'Critical communication',
    stepDocuments: 'Document review',
    stepFinalize: 'Finalization',
    hintReceive: 'Receive the sample and start processing',
    hintResult: 'Enter and validate the microbiology result',
    hintAst: 'Record susceptibility testing for every organism',
    hintCommunication: 'Document notification of the clinical recipient',
    hintDocuments: 'Review the sample attachments',
    hintFinalize: 'All steps are complete — finalize the record',
    awaitingPermission: 'Awaiting action by a user with the required permission.',
    organismRequired: 'A positive result needs at least one organism before validation.',
    noAst: 'No susceptibility testing recorded.',
    noCommunication: 'No communication recorded yet.',
    noResult: 'No result recorded.',
    standard: 'Standard',
    version: 'Version',
    notes: 'Notes',
    recipient: 'Recipient',
    role: 'Role / capacity',
    department: 'Department',
    channel: 'Communication method',
    date: 'Communication date',
    time: 'Communication time',
    readBack: 'Read-back confirmation',
    classification: 'Classification',
    definitionSource: 'Definition source',
    definitionVersion: 'Definition version',
    rationale: 'Rationale',
    amrTitle: 'AMR classification',
    astTitle: 'New susceptibility test',
    communicationTitle: 'Critical result communication',
    resultHelp: 'Organism entry appears only when the result is positive.',
  },
}
export const METHODS = [
  ['culture', 'Καλλιέργεια', 'Culture'],
  ['automated_culture', 'Αυτοματοποιημένη καλλιέργεια', 'Automated culture'],
  ['maldi_tof', 'MALDI-TOF', 'MALDI-TOF'],
  ['pcr', 'PCR', 'PCR'],
  ['microscopy', 'Μικροσκόπηση', 'Microscopy'],
  ['other', 'Άλλη μέθοδος', 'Other method'],
]
export const methodLabel = (value, language) => {
  const row = METHODS.find(x => x[0] === value)
  return row ? row[language === 'el' ? 1 : 2] : value || '—'
}
export const rows = (libraries, key, language) =>
  (libraries?.[key] || []).map(row => ({
    value: row[0],
    label: row[language === 'el' ? 0 : 1] || row[0],
    code: row[2]?.code || '',
  }))
