import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, CheckCircle2, Clock3, FlaskConical, Microscope, ShieldAlert } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Page } from '../../design-system/Page'
import { RecordActions } from '../../design-system/RecordActions'
import { Button } from '../../design-system/Button'
import { SaveButton } from '../../design-system/SaveButton'
import { FilterBar, FilterSelect } from '../../design-system/FilterBar'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { UI_ACTIONS } from '../../core/actions/actionPolicy'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { useTenant } from '../../core/tenant/TenantContext'
import { CAPABILITIES } from '../../core/permissions/roles'
import { useRegistryMemory } from '../../core/navigation/useRegistryMemory'
import { sampleSourceCatalog } from './laboratoryReferenceData'
import { createPatient, loadPatients } from '../patients/patientsService'
import { useEmployeesData } from '../employees/useEmployeesData'
import { demoLibrarySeed } from '../management/managementData'
import { loadDepartments } from '../management/departmentsService'
import { MetricCard } from '../../design-system/MetricCard'
import { getLaboratoryKpis } from './laboratoryCloudService'
import { useLaboratoryRegistry } from './hooks/useLaboratoryRegistry'

const sourceOptions={bloodCulture:[['peripheral','peripheralBlood'],['centralLine','centralLine'],['arterialLine','arterialLine'],['other','other']],urineCulture:[['midstream','midstreamUrine'],['urinaryCatheter','urinaryCatheter'],['nephrostomy','nephrostomy'],['suprapubicCatheter','suprapubicCatheter'],['other','other']],respiratorySample:[['sputum','sputum'],['trachealAspirate','trachealAspirate'],['bal','bal'],['other','other']],woundCulture:[['woundSwab','woundSwab'],['deepTissue','deepTissue'],['drainage','drainage'],['other','other']]}
const environmentalTypes=[['surface','Επιφάνεια','Surface'],['equipment','Εξοπλισμός','Equipment'],['water','Νερό','Water'],['air','Αέρας','Air'],['other','Άλλο','Other']]

export function LaboratoryWorkspace(){
 const {t,language,locale}=useLanguage(),{notify}=useFeedback(),{canAccessRecord,tenant,isDemo}=useTenant(),{rows:repositoryRows,createSample:createRepositorySample}=useLaboratoryRegistry(),{data:employees=[]}=useEmployeesData(),navigate=useNavigate(),registry=useRegistryMemory('laboratory')
 const saved=registry.loadViewState({query:'',status:'all',result:'all',department:'all'}),[query,setQuery]=useState(saved.query),[status,setStatus]=useState(saved.status),[result,setResult]=useState(saved.result),[department,setDepartment]=useState(saved.department),[newOpen,setNewOpen]=useState(false),[patients,setPatients]=useState([]),[departmentOptions,setDepartmentOptions]=useState([])
 useEffect(()=>{let alive=true;Promise.all([loadPatients(tenant?.id,{isDemo}),isDemo?Promise.resolve(demoLibrarySeed.departments.map(([name,nameEn])=>({id:name,name,nameEn}))):loadDepartments(tenant?.id)]).then(([p,d])=>{if(alive){setPatients(p);setDepartmentOptions(d)}}).catch(()=>{});return()=>{alive=false}},[tenant?.id,isDemo])
 const k=getLaboratoryKpis(repositoryRows),fmt=v=>v?new Intl.DateTimeFormat(locale,{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—',departments=[...new Set(repositoryRows.map(s=>language==='el'?s.department:s.departmentEn).filter(Boolean))]
 const rows=useMemo(()=>repositoryRows.filter(s=>canAccessRecord(s)).filter(s=>`${s.id} ${s.patient} ${s.patientEn} ${s.patientId} ${s.organism??''} ${s.surveillanceCase??''}`.toLowerCase().includes(query.toLowerCase())).filter(s=>status==='all'||s.status===status).filter(s=>result==='all'||(result==='critical'?s.critical:s.result===result)).filter(s=>department==='all'||(language==='el'?s.department:s.departmentEn)===department),[query,status,result,department,language,repositoryRows,canAccessRecord])
 async function createSample(draft){try{let patient=null;if(draft.subjectType==='patient'){patient=patients.find(x=>x.id===draft.subjectCode);if(draft.newPatient&&!isDemo){const names=String(draft.subjectName||draft.subjectNameEn||'').trim().split(/\s+/),created=await createPatient(tenant?.id,patients,{patientCode:draft.subjectCode,firstName:names.shift()||'',lastName:names.join(' ')||'',departmentId:draft.departmentId||null,department:draft.department,departmentEn:draft.departmentEn,admissionDate:new Date().toISOString().slice(0,10),status:'active'},{isDemo:false});patient=created.record;setPatients(created.list)}}await createRepositorySample({patientRecordId:patient?.recordId||null,draft:{...draft,patient:draft.subjectName,patientEn:draft.subjectNameEn,patientId:draft.subjectCode}});setNewOpen(false);notify(t('laboratoryRecords.sampleCreated'),'success')}catch(error){notify(error?.message||t('actionFailed'),'error')}}
 function openSample(sample){registry.saveViewState({query,status,result,department});registry.openRecord(navigate,`/laboratory/${sample.id}`,sample.id,rows.map(x=>x.id))}
 return <Page fill title={t('laboratory')} subtitle={t('laboratoryRecords.labSubtitle')} actions={<RecordActions actions={[UI_ACTIONS.CREATE]} actionCapabilities={{[UI_ACTIONS.CREATE]:CAPABILITIES.MANAGE_LAB_SAMPLES}} onAction={a=>a===UI_ACTIONS.CREATE&&setNewOpen(true)}/>}><div className="workspace-summary"><div className="lab-kpis"><LabKpi icon={FlaskConical} label={t('laboratoryRecords.newSamplesToday')} value={k.today}/><LabKpi icon={Clock3} label={t('laboratoryRecords.pendingResults')} value={k.pending}/><LabKpi icon={Microscope} label={t('laboratoryRecords.positiveResults')} value={k.positive}/><LabKpi icon={ShieldAlert} label={t('laboratoryRecords.amrFindings')} value={k.amr}/><LabKpi icon={AlertTriangle} label={t('laboratoryRecords.uncommunicatedCritical')} value={k.critical} danger={k.critical>0}/></div><div className="governance-banner"><CheckCircle2 size={17}/><span>{t('laboratoryRecords.labGovernanceNote')}</span></div></div>
 <section className="surface workspace-fill registry-workspace canonical-paginated-registry"><FilterBar query={query} onQueryChange={setQuery} placeholder={t('laboratoryRecords.searchLab')} activeAdvancedCount={(status!=='all'?1:0)+(department!=='all'?1:0)+(result!=='all'?1:0)} onClear={()=>{setQuery('');setStatus('all');setResult('all');setDepartment('all')}}><FilterSelect label={t('status')} value={status} onChange={setStatus}><option value="all">{t('all')}</option><option value="requested">{t('requested')}</option><option value="received">{t('received')}</option><option value="processing">{t('processing')}</option><option value="completed">{t('completed')}</option><option value="rejected">{t('rejected')}</option></FilterSelect><FilterSelect label={t('department')} value={department} onChange={setDepartment}><option value="all">{t('allDepartments')}</option>{departments.map(x=><option key={x}>{x}</option>)}</FilterSelect><FilterSelect label={t('result')} value={result} onChange={setResult}><option value="all">{t('all')}</option><option value="positive">{t('positive')}</option><option value="negative">{t('negative')}</option><option value="critical">{t('criticalResult')}</option></FilterSelect></FilterBar><div className="scroll-table" ref={registry.scrollRef}><table className="data-table lab-table sticky-table"><thead><tr><th>{t('sampleCode')}</th><th>{t('laboratoryRecords.subject')}</th><th>{t('sampleType')}</th><th>{t('clinicalSource')}</th><th>{t('status')}</th><th>{t('result')}</th><th>{t('surveillance')}</th></tr></thead><tbody>{rows.map(sample=><tr key={sample.id} {...registry.rowProps(sample.id)} onClick={()=>openSample(sample)}><td><strong>{sample.id}</strong><small>{fmt(sample.collectedAt)}</small></td><td><strong>{language==='el'?sample.patient:sample.patientEn}</strong><small>{sample.patientId} · {language==='el'?sample.department:sample.departmentEn}</small></td><td>{t(sample.type)}</td><td>{language==='el'?sample.source:sample.sourceEn}{sample.anatomicalSite&&<small>{sample.anatomicalSite}</small>}</td><td><Status text={t(sample.status)} kind={sample.status}/></td><td>{sample.result?<Status text={t(sample.result)} kind={sample.result}/>:<span>—</span>}</td><td>{sample.surveillanceCase||sample.employeeSurveillanceCase||sample.environmentalSurveillanceCase?<span className="linked-case-chip">{sample.surveillanceCase||sample.employeeSurveillanceCase||sample.environmentalSurveillanceCase}</span>:'—'}</td></tr>)}</tbody></table></div></section>{newOpen&&<NewSampleCard t={t} language={language} patients={patients} employees={employees} departments={departmentOptions} onClose={()=>setNewOpen(false)} onSave={createSample}/>}</Page>
}
function LabKpi({icon:Icon,label,value,danger}){return <MetricCard icon={Icon} value={value} label={label} tone={danger?'danger':'neutral'}/>}
export function Status({text,kind}){return <span className={`lab-status ${kind}`}>{text}</span>}

function NewSampleCard({t,language,patients,employees,departments,onClose,onSave}){
 const en=language==='en',firstPatient=patients.find(x=>x.status==='active')||patients[0],firstEmployee=employees.find(x=>x.employmentStatus==='active')||employees[0]
 const [subjectType,setSubjectType]=useState('patient'),[patientMode,setPatientMode]=useState('existing'),[draft,setDraft]=useState({subjectType:'patient',subjectName:firstPatient?.name||'',subjectNameEn:firstPatient?.nameEn||'',subjectCode:firstPatient?.id||'',newPatient:false,departmentId:firstPatient?.departmentId||null,department:firstPatient?.department||'',departmentEn:firstPatient?.departmentEn||'',type:'bloodCulture',source:sampleSourceCatalog.peripheral.el,sourceEn:sampleSourceCatalog.peripheral.en,sourceCode:'peripheral',environmentType:'surface',anatomicalSite:'',collectedAt:new Date().toISOString().slice(0,16),priority:'routine'})
 const set=(k,v)=>setDraft(x=>({...x,[k]:v})),setDepartment=id=>{const d=departments.find(x=>x.id===id);setDraft(x=>({...x,departmentId:id,department:d?.name||'',departmentEn:d?.nameEn||d?.name||''}))}
 function switchSubject(type){setSubjectType(type);if(type==='patient'){setDraft(d=>({...d,subjectType:type,subjectName:firstPatient?.name||'',subjectNameEn:firstPatient?.nameEn||'',subjectCode:firstPatient?.id||'',departmentId:firstPatient?.departmentId||null,department:firstPatient?.department||'',departmentEn:firstPatient?.departmentEn||'',type:'bloodCulture',newPatient:false}))}else if(type==='employee'){setDraft(d=>({...d,subjectType:type,subjectName:firstEmployee?`${firstEmployee.lastName} ${firstEmployee.firstName}`:'',subjectNameEn:firstEmployee?`${firstEmployee.firstNameEn||firstEmployee.firstName} ${firstEmployee.lastNameEn||firstEmployee.lastName}`:'',subjectCode:firstEmployee?.id||'',departmentId:firstEmployee?.departmentId||null,department:firstEmployee?.department||'',departmentEn:firstEmployee?.departmentEn||'',type:'surveillance',source:'Ρινικό επίχρισμα',sourceEn:'Nasal swab',newPatient:false}))}else setDraft(d=>({...d,subjectType:type,subjectName:'',subjectNameEn:'',subjectCode:'',newPatient:false,type:'environmental',environmentType:'surface',source:'Επιφάνεια',sourceEn:'Surface'}))}
 function choosePatient(id){const p=patients.find(x=>x.id===id);if(p)setDraft(d=>({...d,subjectName:p.name,subjectNameEn:p.nameEn,subjectCode:p.id,departmentId:p.departmentId||null,department:p.department,departmentEn:p.departmentEn,newPatient:false}))}
 function chooseEmployee(id){const e=employees.find(x=>x.id===id);if(e)setDraft(d=>({...d,subjectName:`${e.lastName} ${e.firstName}`,subjectNameEn:`${e.firstNameEn||e.firstName} ${e.lastNameEn||e.lastName}`,subjectCode:e.id,departmentId:e.departmentId||null,department:e.department||'',departmentEn:e.departmentEn||''}))}
 function setEnvType(code){const item=environmentalTypes.find(x=>x[0]===code);setDraft(d=>({...d,environmentType:code,source:item?.[1]||code,sourceEn:item?.[2]||code}))}
 const valid=subjectType==='environment'?Boolean(draft.departmentId&&draft.subjectName):Boolean(draft.subjectCode&&draft.subjectName)
 return <div className="modal-backdrop"><div className="entry-card lab-entry-card"><header><div><span className="eyebrow">{en?'NEW LABORATORY SAMPLE':'ΝΕΟ ΕΡΓΑΣΤΗΡΙΑΚΟ ΔΕΙΓΜΑ'}</span><h3>{en?'Sample details':'Στοιχεία δείγματος'}</h3></div><button className="icon-close" onClick={onClose}>×</button></header>
 <div className="entry-mode-switch"><button className={subjectType==='patient'?'active':''} onClick={()=>switchSubject('patient')}>{en?'Patient':'Ασθενής'}</button><button className={subjectType==='employee'?'active':''} onClick={()=>switchSubject('employee')}>{en?'Employee':'Εργαζόμενος'}</button><button className={subjectType==='environment'?'active':''} onClick={()=>switchSubject('environment')}>{en?'Environment':'Περιβάλλον'}</button></div>
 {subjectType==='patient'&&<div className="entry-mode-switch"><button className={patientMode==='existing'?'active':''} onClick={()=>{setPatientMode('existing');choosePatient(firstPatient?.id||'')}}>{t('existingPatient')}</button><button className={patientMode==='new'?'active':''} onClick={()=>{setPatientMode('new');setDraft(d=>({...d,subjectName:'',subjectNameEn:'',subjectCode:'',newPatient:true}))}}>{t('laboratoryRecords.newPatientInline')}</button></div>}
 <div className="entry-grid">{subjectType==='patient'&&(patientMode==='existing'?<label className="entry-span-2"><span>{t('patient')}</span><select value={draft.subjectCode} onChange={e=>choosePatient(e.target.value)}>{patients.filter(x=>x.status==='active').map(p=><option key={p.id} value={p.id}>{language==='el'?p.name:p.nameEn} · {p.id}</option>)}</select></label>:<><label><span>{t('patient')}</span><input value={draft.subjectName} onChange={e=>set('subjectName',e.target.value)}/></label><label><span>{t('patientId')}</span><input value={draft.subjectCode} onChange={e=>set('subjectCode',e.target.value)}/></label></>)}
 {subjectType==='employee'&&<label className="entry-span-2"><span>{en?'Employee':'Εργαζόμενος'}</span><select value={draft.subjectCode} onChange={e=>chooseEmployee(e.target.value)}>{employees.filter(x=>x.employmentStatus==='active').map(e=><option key={e.id} value={e.id}>{language==='el'?`${e.lastName} ${e.firstName}`:`${e.firstNameEn||e.firstName} ${e.lastNameEn||e.lastName}`} · {e.id}</option>)}</select></label>}
 {subjectType==='environment'&&<><label><span>{en?'Environmental sample type':'Τύπος περιβαλλοντικού δείγματος'}</span><select value={draft.environmentType} onChange={e=>setEnvType(e.target.value)}>{environmentalTypes.map(([id,el,enLabel])=><option key={id} value={id}>{en?enLabel:el}</option>)}</select></label><label><span>{draft.environmentType==='water'?(en?'Sampling point':'Σημείο υδροληψίας'):(en?'Sampling point / location':'Σημείο / χώρος δειγματοληψίας')}</span><input value={draft.subjectName} onChange={e=>{set('subjectName',e.target.value);set('subjectNameEn',e.target.value)}} placeholder={draft.environmentType==='water'?(en?'e.g. ICU tap 2':'π.χ. Βρύση ΜΕΘ 2'):(en?'e.g. Bed rail 12':'π.χ. Κουπαστή κλίνης 12')}/></label></>}
 <label><span>{t('department')}</span><select value={draft.departmentId||''} onChange={e=>setDepartment(e.target.value)}><option value="">—</option>{departments.map(d=><option key={d.id} value={d.id}>{language==='el'?d.name:(d.nameEn||d.name)}</option>)}</select></label>
 {subjectType==='patient'&&<><label><span>{t('sampleType')}</span><select value={draft.type} onChange={e=>set('type',e.target.value)}><option value="bloodCulture">{t('bloodCulture')}</option><option value="urineCulture">{t('urineCulture')}</option><option value="respiratorySample">{t('respiratorySample')}</option><option value="woundCulture">{t('woundCulture')}</option></select></label><label><span>{t('anatomicalSite')}</span><input value={draft.anatomicalSite} onChange={e=>set('anatomicalSite',e.target.value)}/></label></>}
 {subjectType==='employee'&&<label><span>{en?'Screening type':'Τύπος ελέγχου'}</span><select value={draft.sourceEn} onChange={e=>setDraft(d=>({...d,sourceEn:e.target.value,source:e.target.options[e.target.selectedIndex].dataset.el}))}><option data-el="Ρινικό επίχρισμα">Nasal swab</option><option data-el="Επίχρισμα χεριών">Hand swab</option><option data-el="Φαρυγγικό επίχρισμα">Throat swab</option></select></label>}
 <label><span>{t('collectedLabel')}</span><input type="datetime-local" value={draft.collectedAt} onChange={e=>set('collectedAt',e.target.value)}/></label><label><span>{t('priority')}</span><select value={draft.priority} onChange={e=>set('priority',e.target.value)}><option value="routine">{t('routine')}</option><option value="urgent">{t('urgent')}</option><option value="critical">{t('critical')}</option></select></label></div>
 <footer><Button variant="secondary" onClick={onClose}>{t('cancel')}</Button><SaveButton disabled={!valid} onClick={()=>onSave(draft)}>{t('save')}</SaveButton></footer></div></div>
}
