import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, FileClock, FlaskConical, Microscope, PhoneCall, ShieldAlert } from 'lucide-react'
import { useParams } from 'react-router-dom'
import { Page } from '../../design-system/Page'
import { EntityRecordShell } from '../../design-system/EntityRecordShell'
import { PrintExportActions } from '../../design-system/PrintExportActions'
import { Button } from '../../design-system/Button'
import { SaveButton } from '../../design-system/SaveButton'
import { EmptyState } from '../../design-system/EmptyState'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { useTenant } from '../../core/tenant/TenantContext'
import { can, CAPABILITIES } from '../../core/permissions/roles'
import { useContextualNavigation } from '../../core/navigation/useContextualNavigation'
import { useRecordSequenceNavigation } from '../../core/navigation/useRecordSequenceNavigation'
import { downloadRecordJson } from '../../core/export/recordExport'
import { addAstResult, communicateCriticalResult, loadLaboratorySample, saveMicrobiologyResult, updateLaboratorySampleStatus } from './laboratoryCloudService'
import { Status } from './LaboratoryPage'

export function LaboratorySampleCloudRecordPage(){
  const {sampleId}=useParams()
  const {t,locale}=useLanguage()
  const {notify}=useFeedback()
  const {role,membership,tenant,canAccessRecord}=useTenant()
  const {goBack}=useContextualNavigation('/laboratory')
  const recordNavigation=useRecordSequenceNavigation({registry:'laboratory',currentId:sampleId,pathForId:id=>`/laboratory/${id}`})
  const [sample,setSample]=useState(null)
  const [loading,setLoading]=useState(true)
  const [error,setError]=useState('')
  const [tab,setTab]=useState('summary')
  const [dialog,setDialog]=useState(null)
  const has=cap=>can(role,cap,membership?.capabilities??[],membership?.customCapabilities??[])
  const canManage=has(CAPABILITIES.MANAGE_LAB_SAMPLES)
  const canValidate=has(CAPABILITIES.VALIDATE_LAB_RESULTS)
  const canCommunicate=has(CAPABILITIES.COMMUNICATE_CRITICAL_RESULTS)
  const fmt=value=>value?new Intl.DateTimeFormat(locale,{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'—'

  async function reload(){setLoading(true);setError('');try{setSample(await loadLaboratorySample(tenant?.id,sampleId))}catch(err){setError(err?.message||t('actionFailed'))}finally{setLoading(false)}}
  useEffect(()=>{reload()},[tenant?.id,sampleId]) // eslint-disable-line react-hooks/exhaustive-deps
  const result=sample?.microbiologyResults?.[0]||null
  const ast=result?.ast||[]
  const communications=result?.communications||[]
  const tabs=useMemo(()=>[
    {id:'summary',label:t('summary'),icon:FlaskConical},
    {id:'result',label:t('laboratoryRecords.microbiologyResult'),icon:Microscope},
    {id:'ast',label:t('laboratoryRecords.antimicrobialSusceptibility'),icon:ShieldAlert},
    {id:'communication',label:t('laboratoryRecords.criticalCommunication'),icon:PhoneCall},
    {id:'history',label:t('history'),icon:FileClock},
  ],[t])
  async function saveAndReload(work,message){await work();setDialog(null);await reload();notify(message,'success')}

  if(loading)return <Page title={t('laboratoryRecords.sample')}><div className="inline-empty">{t('loading')}</div></Page>
  if(error)return <Page title={t('laboratoryRecords.sample')}><EmptyState title={t('actionFailed')} description={error}/></Page>
  if(!sample)return <Page title={t('laboratoryRecords.sample')}><EmptyState title={t('noData')} description={t('laboratoryRecords.sample')}/></Page>
  if(!canAccessRecord(sample))return <Page title={t('laboratoryRecords.sample')}><EmptyState title={t('scopeAccessDeniedTitle')} description={t('scopeAccessDeniedDescription')}/></Page>

  return <Page fill><EntityRecordShell className="laboratory-record-shell workspace-fill" recordNavigation={recordNavigation} avatar={<FlaskConical size={20}/>} eyebrow={sample.id} title={t(sample.type)} subtitle={`${sample.patient} · ${sample.patientId} · ${sample.department||'—'}`} status={<><Status text={t(sample.status)} kind={sample.status}/>{sample.resistance&&<b className="amr-chip">{sample.resistance}</b>}</>} headerActions={<PrintExportActions onExport={()=>downloadRecordJson(sample,{filename:sample.id})}/>} tabs={tabs} activeTab={tab} onTabChange={setTab} onBack={goBack} backLabel={t('backToLaboratory')}>
    {!canManage&&tab==='summary'&&<div className="permission-info-banner"><AlertTriangle size={16}/><span>{t('laboratoryRecords.laboratoryReadOnlyRole')}</span></div>}
    {tab==='summary'&&<section className="clinical-panel full-panel"><div className="record-section-header"><div><strong>{t('sampleDetails')}</strong><small>{sample.id}</small></div><div className="record-section-actions">{canManage&&sample.status==='requested'&&<Button onClick={()=>saveAndReload(()=>updateLaboratorySampleStatus(tenant?.id,sample.recordId,'received',{receivedAt:new Date()}),t('laboratoryRecords.sampleReceivedMessage'))}>{t('received')}</Button>}{canManage&&['received','collected'].includes(sample.status)&&<Button onClick={()=>saveAndReload(()=>updateLaboratorySampleStatus(tenant?.id,sample.recordId,'processing'),t('laboratoryRecords.sampleProcessingStartedMessage'))}>{t('processing')}</Button>}</div></div><div className="detail-grid patient-detail-grid"><Detail label={t('patient')} value={sample.patient}/><Detail label={t('department')} value={sample.department}/><Detail label={t('sampleType')} value={t(sample.type)}/><Detail label={t('clinicalSource')} value={sample.source}/><Detail label={t('priority')} value={t(sample.priority)}/><Detail label={t('collectedLabel')} value={fmt(sample.collectedAt)}/><Detail label={t('received')} value={fmt(sample.receivedAt)}/><Detail label={t('surveillance')} value={sample.surveillanceCase||'—'}/></div></section>}
    {tab==='result'&&<section className="clinical-panel full-panel"><div className="record-section-header"><div><strong>{t('laboratoryRecords.microbiologyResult')}</strong><small>{result?t(result.resultStatus):t('pending')}</small></div>{canManage&&<Button variant="secondary" onClick={()=>setDialog('result')}>{result?t('edit'):t('clinicalRecords.add')}</Button>}</div>{result?<div className="detail-grid patient-detail-grid"><Detail label={t('result')} value={t(result.result)}/><Detail label={t('exportOrganism')} value={result.organism}/><Detail label={t('classification')} value={result.resistance}/><Detail label={t('criticalResult')} value={result.critical?t('yes'):t('no')}/><Detail label={t('method')} value={result.method}/><Detail label={t('status')} value={t(result.resultStatus)}/></div>:<div className="inline-empty">{t('clinicalRecords.notDocumented')}</div>}</section>}
    {tab==='ast'&&<section className="clinical-panel full-panel"><div className="record-section-header"><div><strong>{t('laboratoryRecords.antimicrobialSusceptibility')}</strong><small>{ast.length}</small></div>{canManage&&result&&<Button variant="secondary" onClick={()=>setDialog('ast')}>+ {t('clinicalRecords.add')}</Button>}</div>{ast.length?<div className="record-table-wrap"><table className="record-table"><thead><tr><th>{t('antibiotic')}</th><th>S/I/R</th><th>{t('method')}</th><th>{t('version')}</th></tr></thead><tbody>{ast.map(row=><tr key={row.id}><td>{row.drug}</td><td><strong>{row.sir}</strong></td><td>{row.method}</td><td>{row.standard} {row.version}</td></tr>)}</tbody></table></div>:<div className="inline-empty">{t('clinicalRecords.notDocumented')}</div>}</section>}
    {tab==='communication'&&<section className="clinical-panel full-panel"><div className="record-section-header"><div><strong>{t('laboratoryRecords.criticalCommunication')}</strong><small>{communications.length}</small></div>{canCommunicate&&result?.critical&&<Button variant="secondary" onClick={()=>setDialog('communication')}>+ {t('clinicalRecords.add')}</Button>}</div>{result?.critical?communications.length?communications.map(row=><article className="evidence-box" key={row.id}><strong>{row.to} · {fmt(row.at)}</strong><span>{t(row.method)}{row.readBack?` · ${t('confirmed')}`:''}</span></article>):<div className="inline-empty">{t('laboratoryRecords.uncommunicatedCritical')}</div>:<div className="inline-empty">{t('clinicalRecords.notDocumented')}</div>}</section>}
    {tab==='history'&&<section className="clinical-panel full-panel"><div className="record-section-header"><div><FileClock size={17}/><strong>{t('history')}</strong></div></div><div className="clinical-timeline"><Timeline at={sample.requestedAt} title={t('requested')} fmt={fmt}/>{sample.receivedAt&&<Timeline at={sample.receivedAt} title={t('received')} fmt={fmt}/>} {result&&<Timeline at={result.resultedAt} title={t('laboratoryRecords.microbiologyResult')} fmt={fmt}/>} {result?.validatedAt&&<Timeline at={result.validatedAt} title={t('validated')} fmt={fmt}/>} {communications.map(row=><Timeline key={row.id} at={row.at} title={t('laboratoryRecords.criticalCommunication')} fmt={fmt}/>)}</div></section>}
  </EntityRecordShell>
  {dialog==='result'&&<ResultDialog t={t} current={result} canValidate={canValidate} onClose={()=>setDialog(null)} onSave={draft=>saveAndReload(()=>saveMicrobiologyResult(tenant?.id,sample.recordId,draft),t('saved'))}/>} 
  {dialog==='ast'&&<AstDialog t={t} onClose={()=>setDialog(null)} onSave={draft=>saveAndReload(()=>addAstResult(tenant?.id,result.id,draft),t('saved'))}/>} 
  {dialog==='communication'&&<CommunicationDialog t={t} onClose={()=>setDialog(null)} onSave={draft=>saveAndReload(()=>communicateCriticalResult(tenant?.id,result.id,draft),t('saved'))}/>} 
  </Page>
}

function ResultDialog({t,current,canValidate,onClose,onSave}){const [draft,setDraft]=useState({id:current?.id||null,result:current?.result||'negative',organism:current?.organism||'',resistance:current?.resistance||'',critical:Boolean(current?.critical),method:current?.method||'',preliminary:Boolean(current?.preliminary),validationStatus:current?.resultStatus||'draft',interpretationStandard:current?.interpretationStandard||'EUCAST',interpretationVersion:current?.interpretationVersion||''});return <SimpleDialog title={t('laboratoryRecords.microbiologyResult')} t={t} onClose={onClose} onSave={()=>onSave(draft)} disabled={!draft.result}><label><span>{t('result')}</span><select value={draft.result} onChange={e=>setDraft(d=>({...d,result:e.target.value}))}><option value="positive">{t('positive')}</option><option value="negative">{t('negative')}</option><option value="inconclusive">{t('inconclusive')}</option><option value="contaminated">{t('contaminated')}</option></select></label><label><span>{t('exportOrganism')}</span><input value={draft.organism} onChange={e=>setDraft(d=>({...d,organism:e.target.value}))}/></label><label><span>{t('classification')}</span><select value={draft.resistance} onChange={e=>setDraft(d=>({...d,resistance:e.target.value}))}><option value="">—</option><option value="MDR">MDR</option><option value="XDR">XDR</option><option value="PDR">PDR</option></select></label><label><span>{t('method')}</span><input value={draft.method} onChange={e=>setDraft(d=>({...d,method:e.target.value}))}/></label><label><span>{t('criticalResult')}</span><select value={draft.critical?'yes':'no'} onChange={e=>setDraft(d=>({...d,critical:e.target.value==='yes'}))}><option value="no">{t('no')}</option><option value="yes">{t('yes')}</option></select></label><label><span>{t('status')}</span><select disabled={!canValidate} value={draft.validationStatus} onChange={e=>setDraft(d=>({...d,validationStatus:e.target.value}))}><option value="draft">{t('draft')}</option>{canValidate&&<option value="validated">{t('validated')}</option>}</select></label><label><span>{t('source')}</span><input value={draft.interpretationStandard} onChange={e=>setDraft(d=>({...d,interpretationStandard:e.target.value}))}/></label><label><span>{t('version')}</span><input value={draft.interpretationVersion} onChange={e=>setDraft(d=>({...d,interpretationVersion:e.target.value}))}/></label></SimpleDialog>}
function AstDialog({t,onClose,onSave}){const [draft,setDraft]=useState({drug:'',method:'MIC',sir:'S',standard:'EUCAST',version:'',mic:'',operator:'',zone:'',notes:''});return <SimpleDialog title={t('laboratoryRecords.antimicrobialSusceptibility')} t={t} onClose={onClose} onSave={()=>onSave(draft)} disabled={!draft.drug||!draft.version}><label><span>{t('antibiotic')}</span><input value={draft.drug} onChange={e=>setDraft(d=>({...d,drug:e.target.value}))}/></label><label><span>S/I/R</span><select value={draft.sir} onChange={e=>setDraft(d=>({...d,sir:e.target.value}))}><option>S</option><option>I</option><option>R</option></select></label><label><span>{t('method')}</span><input value={draft.method} onChange={e=>setDraft(d=>({...d,method:e.target.value}))}/></label><label><span>{t('source')}</span><input value={draft.standard} onChange={e=>setDraft(d=>({...d,standard:e.target.value}))}/></label><label><span>{t('version')}</span><input value={draft.version} onChange={e=>setDraft(d=>({...d,version:e.target.value}))}/></label><label><span>MIC</span><input value={draft.mic} onChange={e=>setDraft(d=>({...d,mic:e.target.value}))}/></label></SimpleDialog>}
function CommunicationDialog({t,onClose,onSave}){const [draft,setDraft]=useState({recipientName:'',recipientRole:'',method:'phone',readBack:true,notes:''});return <SimpleDialog title={t('laboratoryRecords.criticalCommunication')} t={t} onClose={onClose} onSave={()=>onSave(draft)} disabled={!draft.recipientName}><label><span>{t('recipient')}</span><input value={draft.recipientName} onChange={e=>setDraft(d=>({...d,recipientName:e.target.value}))}/></label><label><span>{t('role')}</span><input value={draft.recipientRole} onChange={e=>setDraft(d=>({...d,recipientRole:e.target.value}))}/></label><label><span>{t('method')}</span><select value={draft.method} onChange={e=>setDraft(d=>({...d,method:e.target.value}))}><option value="phone">{t('phone')}</option><option value="in_person">{t('inPerson')}</option><option value="secure_message">{t('secureMessage')}</option><option value="other">{t('other')}</option></select></label><label><span>{t('confirmed')}</span><select value={draft.readBack?'yes':'no'} onChange={e=>setDraft(d=>({...d,readBack:e.target.value==='yes'}))}><option value="yes">{t('yes')}</option><option value="no">{t('no')}</option></select></label><label className="entry-span-2"><span>{t('notes')}</span><textarea rows={3} value={draft.notes} onChange={e=>setDraft(d=>({...d,notes:e.target.value}))}/></label></SimpleDialog>}
function SimpleDialog({title,t,onClose,onSave,disabled,children}){return <div className="modal-backdrop"><div className="entry-card"><header><div><h3>{title}</h3></div><button className="icon-close" onClick={onClose}>×</button></header><div className="entry-grid">{children}</div><footer><Button variant="secondary" onClick={onClose}>{t('cancel')}</Button><SaveButton disabled={disabled} onClick={onSave}>{t('save')}</SaveButton></footer></div></div>}
function Detail({label,value}){return <div className="detail-item"><span>{label}</span><strong>{value||'—'}</strong></div>}
function Timeline({at,title,fmt}){return <article><div className="timeline-rail"><span/></div><div><header><strong>{title}</strong><time>{fmt(at)}</time></header></div></article>}
