import {buildScaleReportRows,clinicalScaleExtraFields,clinicalScaleFields,clinicalScaleOptions,fieldReference,isChoiceScale,scaleReference,scoreBand,valueStatus} from './clinicalScaleForms'
import './clinicalScales.css'

const bandText=(band,en)=>band?(en?band[2].en:band[2].el):''
export const bandBadgeTone=band=>band?({good:'active',low:'',warning:'warning',danger:'danger'}[band[3]]??''):''
export const scoreBandLabel=(scale,score,en)=>{const band=scoreBand(scale,score);return band?{label:bandText(band,en).split(' · ').slice(1).join(' · ')||bandText(band,en),tone:bandBadgeTone(band)}:null}
const refHeading=(scale,en)=>scale==='gcs'||scale==='pediatric-gcs'?(en?'Normal':'Φυσιολογικό'):isChoiceScale(scale)?(en?'Lowest risk':'Χωρίς κίνδυνο'):(en?'Normal range':'Φυσιολογικά όρια')
const statusLabel=(status,en)=>status==='high'?(en?'Above range':'Πάνω από τα όρια'):status==='low'?(en?'Below range':'Κάτω από τα όρια'):''

export function ScaleBands({scale,score,en}){const {bands}=scaleReference(scale);const current=scoreBand(scale,score);if(!bands.length)return null;return <ol className="cs-bands">{bands.map(band=><li key={band[0]} className={`cs-band tone-${band[3]}${band===current?' is-current':''}`}><span className="cs-band-dot"/><span>{bandText(band,en)}</span>{band===current&&<strong>{en?'Current':'Τρέχουσα'}</strong>}</li>)}</ol>}

export function ScaleFieldHint({scale,fieldKey,value,en}){const reference=fieldReference(scale,fieldKey,en);const status=valueStatus(scale,fieldKey,value);if(!reference)return null;return <small className={`cs-field-hint${status==='high'||status==='low'?' is-out':''}`}>{refHeading(scale,en)}: {reference}{statusLabel(status,en)&&<b> · {statusLabel(status,en)}</b>}</small>}

export function ScaleLiveResult({scale,result,en}){const band=result?.complete?scoreBand(scale,result.score):null;return <div className={`cs-live tone-${band?.[3]||'none'}`}><div className="cs-live-score"><span>{en?'Score':'Βαθμολογία'}</span><strong>{result?.complete?result.score:'—'}</strong></div><div className="cs-live-text">{result?.complete?<strong>{bandText(band,en)||(en?'Calculated':'Υπολογίστηκε')}</strong>:<strong>{en?'Complete all parameters to calculate':'Συμπληρώστε όλες τις παραμέτρους για τον υπολογισμό'}</strong>}<ScaleBands scale={scale} score={result?.complete?result.score:null} en={en}/></div></div>}

export function ScaleReport({report,scaleKey,title,date,en}){
 const {rows,components}=buildScaleReportRows(scaleKey,report.answers||{},report.score_parts||{},en)
 const band=scoreBand(scaleKey,report.score)
 const hasPoints=rows.some(r=>r.points!=null)
 return <div className="cs-report">
  <section className={`cs-report-hero tone-${band?.[3]||'none'}`}><div className="cs-report-score"><span>{en?'Total score':'Συνολική βαθμολογία'}</span><strong>{report.score??'—'}</strong></div><div className="cs-report-hero-text"><small>{title}</small><h3>{bandText(band,en)||(en?'Recorded assessment':'Καταχωρισμένη αξιολόγηση')}</h3><dl className="cs-meta"><div><dt>{en?'Date / time':'Ημερομηνία / ώρα'}</dt><dd>{date}</dd></div><div><dt>{en?'Assessed by':'Αξιολόγηση από'}</dt><dd>{report.assessor_name||'—'}{report.assessor_job_title&&<small>{report.assessor_job_title}</small>}</dd></div><div><dt>{en?'Version':'Έκδοση'}</dt><dd>{report.scale_version||'—'}</dd></div></dl></div></section>
  <section className="cs-card"><h4>{en?'Parameters':'Παράμετροι'}</h4><div className="cs-table-wrap"><table className="cs-table"><thead><tr><th>{en?'Parameter':'Παράμετρος'}</th><th>{en?'Recorded value':'Καταχωρισμένη τιμή'}</th>{hasPoints&&<th className="num">{en?'Points':'Βαθμοί'}</th>}<th>{refHeading(scaleKey,en)}</th></tr></thead><tbody>{rows.map(r=><tr key={r.key} className={r.status==='high'||r.status==='low'?'is-out':''}><td>{r.label}</td><td><strong>{r.value}</strong>{statusLabel(r.status,en)&&<span className="cs-flag">{statusLabel(r.status,en)}</span>}</td>{hasPoints&&<td className="num"><span className={`cs-points${Number(r.points)>0&&!isChoiceScale(scaleKey)?' is-scored':''}`}>{r.points??'—'}</span></td>}<td className="cs-muted">{r.reference||'—'}</td></tr>)}</tbody></table></div></section>
  {components.length>0&&<section className="cs-card"><h4>{en?'Component scores':'Βαθμολογία ανά σύστημα'}</h4><div className="cs-components">{components.map(c=><div key={c.key} className={Number(c.points)>0?'is-scored':''}><span>{c.label}</span><strong>{c.points??'—'}</strong></div>)}</div></section>}
  <section className="cs-card"><h4>{en?'Interpretation':'Ερμηνεία'}</h4><ScaleBands scale={scaleKey} score={report.score} en={en}/></section>
  <section className="cs-card cs-source"><h4>{en?'Source':'Τεκμηρίωση'}</h4><p>{report.report_snapshot?.sourceAuthority||'—'}</p><small>{report.report_snapshot?.sourceReference||''}</small></section>
 </div>}

export function ScaleFormPreview({scale,en}){const fields=clinicalScaleFields(scale);return <div className="cs-preview"><div className="cs-table-wrap"><table className="cs-table"><thead><tr><th>{en?'Parameter':'Παράμετρος'}</th><th>{en?'Entry':'Καταχώριση'}</th><th>{refHeading(scale,en)}</th></tr></thead><tbody>{fields.map(([key,el,enLabel])=>{const options=clinicalScaleOptions(scale,key,en);return <tr key={key}><td>{en?enLabel:el}</td><td className="cs-muted">{options.length?(en?`Choice · ${options.length} options`:`Επιλογή · ${options.length} επιλογές`):(en?'Number':'Αριθμός')}</td><td>{fieldReference(scale,key,en)||'—'}</td></tr>})}{clinicalScaleExtraFields(scale).map(([key,el,enLabel])=><tr key={key}><td>{en?enLabel:el}</td><td className="cs-muted">{key==='chronicHealthPoints'?(en?'Number':'Αριθμός'):(en?'Yes / No':'Ναι / Όχι')}</td><td>{fieldReference(scale,key,en)||'—'}</td></tr>)}</tbody></table></div><h5>{en?'Score interpretation':'Ερμηνεία βαθμολογίας'}</h5><ScaleBands scale={scale} score={null} en={en}/></div>}
