export const CLINICAL_SCALE_FIELDS={
 sofa:[['pao2Fio2','PaO₂/FiO₂','PaO₂/FiO₂'],['platelets','Αιμοπετάλια','Platelets'],['bilirubin','Χολερυθρίνη','Bilirubin'],['map','Μέση αρτηριακή πίεση (MAP)','Mean arterial pressure (MAP)'],['dopamine','Ντοπαμίνη (μg/kg/min)','Dopamine (μg/kg/min)'],['epinephrine','Επινεφρίνη (μg/kg/min)','Epinephrine (μg/kg/min)'],['norepinephrine','Νορεπινεφρίνη (μg/kg/min)','Norepinephrine (μg/kg/min)'],['gcs','Κλίμακα Γλασκώβης (GCS)','Glasgow Coma Scale (GCS)'],['creatinine','Κρεατινίνη (mg/dL)','Creatinine (mg/dL)'],['urineOutput24h','Διούρηση 24ώρου (mL)','24-hour urine output (mL)']],
 'apache-ii':[['temperature','Θερμοκρασία (°C)','Temperature (°C)'],['map','Μέση αρτηριακή πίεση (MAP, mmHg)','Mean arterial pressure (MAP, mmHg)'],['heartRate','Καρδιακή συχνότητα (/λεπτό)','Heart rate (/min)'],['respiratoryRate','Αναπνευστική συχνότητα (/λεπτό)','Respiratory rate (/min)'],['fio2','FiO₂','FiO₂'],['pao2','PaO₂ (mmHg)','PaO₂ (mmHg)'],['aado2','A–aDO₂ (mmHg)','A–aDO₂ (mmHg)'],['ph','Αρτηριακό pH','Arterial pH'],['sodium','Νάτριο (mmol/L)','Sodium (mmol/L)'],['potassium','Κάλιο (mmol/L)','Potassium (mmol/L)'],['creatinine','Κρεατινίνη (mg/dL)','Creatinine (mg/dL)'],['hematocrit','Αιματοκρίτης (%)','Hematocrit (%)'],['wbc','Λευκά αιμοσφαίρια (×10³/μL)','White blood cells (×10³/μL)'],['gcs','Κλίμακα Γλασκώβης (GCS)','Glasgow Coma Scale (GCS)']],
 news2:[['respiratoryRate','Αναπνευστική συχνότητα (/λεπτό)','Respiratory rate (/min)'],['spo2','SpO₂ (%)','SpO₂ (%)'],['systolicBp','Συστολική αρτηριακή πίεση (mmHg)','Systolic blood pressure (mmHg)'],['pulse','Σφύξεις (/λεπτό)','Pulse (/min)'],['temperature','Θερμοκρασία (°C)','Temperature (°C)']],
 gcs:[['eye','Οφθαλμική απόκριση (1–4)','Eye response (1–4)'],['verbal','Λεκτική απόκριση (1–5)','Verbal response (1–5)'],['motor','Κινητική απόκριση (1–6)','Motor response (1–6)']],
 'pediatric-gcs':[['eye','Οφθαλμική απόκριση (1–4)','Eye response (1–4)'],['verbal','Παιδιατρική λεκτική απόκριση (1–5)','Paediatric verbal response (1–5)'],['motor','Παιδιατρική κινητική απόκριση (1–6)','Paediatric motor response (1–6)']],
 morse:[['fallHistory','Ιστορικό πτώσης: Όχι 0 / Ναι 25','History of falling: No 0 / Yes 25'],['secondaryDiagnosis','Δεύτερη διάγνωση: Όχι 0 / Ναι 15','Secondary diagnosis: No 0 / Yes 15'],['ambulatoryAid','Βοήθημα βάδισης: κανένα 0 / βακτηρίες-μπαστούνι-περιπατητήρας 15 / έπιπλα 30','Ambulatory aid: none 0 / crutches-cane-walker 15 / furniture 30'],['ivTherapy','Ενδοφλέβια θεραπεία / φλεβική πρόσβαση: Όχι 0 / Ναι 20','IV therapy / IV access: No 0 / Yes 20'],['gait','Βάδιση: φυσιολογική 0 / αδύναμη 10 / διαταραγμένη 20','Gait: normal 0 / weak 10 / impaired 20'],['mentalStatus','Νοητική κατάσταση: προσανατολισμένος 0 / υπερεκτιμά ή ξεχνά περιορισμούς 15','Mental status: oriented 0 / overestimates or forgets limitations 15']],
 braden:[['sensoryPerception','Αισθητηριακή αντίληψη (1–4)','Sensory perception (1–4)'],['moisture','Υγρασία (1–4)','Moisture (1–4)'],['activity','Δραστηριότητα (1–4)','Activity (1–4)'],['mobility','Κινητικότητα (1–4)','Mobility (1–4)'],['nutrition','Θρέψη (1–4)','Nutrition (1–4)'],['frictionShear','Τριβή και διάτμηση (1–3)','Friction and shear (1–3)']],
 'humpty-dumpty':[['age','Ηλικία — βαθμός','Age score'],['diagnosis','Διάγνωση — βαθμός','Diagnosis score'],['cognitiveImpairment','Γνωστική κατάσταση — βαθμός','Cognitive impairment score'],['environmentalFactors','Περιβαλλοντικοί παράγοντες — βαθμός','Environmental factors score'],['surgerySedationAnesthesia','Χειρουργείο / καταστολή / αναισθησία — βαθμός','Surgery / sedation / anesthesia score']]
}
export const clinicalScaleFields=key=>CLINICAL_SCALE_FIELDS[key]||[]
export const clinicalScaleReady=row=>row?.status==='approved'&&row?.definition?.scoringStatus==='ready'&&clinicalScaleFields(row.scale_key).length>0
