// Demo copy of the clinical scale catalogue seeded by the supabase migrations
// (clinical_scales_registry, morse_fall_scale, age_aware_glasgow_forms,
// clinical_scales_population_catalogue). Only the tools the scoring engine
// supports are included. The demo never reaches Supabase, so without this
// list the Clinical assessments tab had no tools and no "New assessment" action.
const ready={engine:'deterministic',scoringStatus:'ready',engineVersion:'1.0',inputPolicy:'explicit_values_only'}

export const demoClinicalScaleDefinitions=Object.freeze([
  {id:'demo-scale-news2',scale_key:'news2',version:'NEWS2-2017',name_el:'NEWS2 — Εθνική Βαθμολογία Έγκαιρης Προειδοποίησης',name_en:'NEWS2 — National Early Warning Score 2',category:'deterioration',population:['adult'],min_age_years:16,max_age_years:null,settings:['ward','ed','acute_care'],definition:ready,source_authority:'Royal College of Physicians',source_reference:'NEWS2, 2017 και οδηγίες εφαρμογής',status:'approved',orgSetting:null},
  {id:'demo-scale-gcs',scale_key:'gcs',version:'GCS-STRUCTURED',name_el:'Glasgow Coma Scale — Δομημένη αξιολόγηση',name_en:'Glasgow Coma Scale — Structured Assessment',category:'neurology',population:['adult','pediatric'],min_age_years:null,max_age_years:null,settings:['ward','icu','ed'],definition:ready,source_authority:'University of Glasgow',source_reference:'Glasgow Coma Scale — δομημένη προσέγγιση',status:'approved',orgSetting:null},
  {id:'demo-scale-pediatric-gcs',scale_key:'pediatric-gcs',version:'PGCS-ADELAIDE',name_el:'Παιδιατρική Κλίμακα Γλασκώβης — Adelaide',name_en:'Paediatric Glasgow Coma Scale — Adelaide',category:'neurology',population:['neonatal','pediatric'],min_age_years:0,max_age_years:5.999,settings:['nicu','neonatal','pediatric_ward','pediatric_ed','picu','ward','icu','ed'],definition:{...ready,scoreRange:[3,15]},source_authority:'University of Glasgow / Glasgow Coma Scale',source_reference:'Παιδιατρική τροποποίηση Adelaide',status:'approved',orgSetting:null},
  {id:'demo-scale-sofa',scale_key:'sofa',version:'SOFA-1',name_el:'SOFA — Διαδοχική Αξιολόγηση Οργανικής Ανεπάρκειας',name_en:'SOFA — Sequential Organ Failure Assessment',category:'organ_dysfunction',population:['adult'],min_age_years:18,max_age_years:null,settings:['icu'],definition:{...ready,scoreRange:[0,24]},source_authority:'ESICM / Vincent et al.',source_reference:'Intensive Care Med. 1996;22:707–710',status:'approved',orgSetting:null},
  {id:'demo-scale-apache-ii',scale_key:'apache-ii',version:'APACHE-II',name_el:'APACHE II — Βαρύτητα νόσου ΜΕΘ',name_en:'APACHE II — Acute Physiology and Chronic Health Evaluation II',category:'severity',population:['adult'],min_age_years:18,max_age_years:null,settings:['icu'],definition:{...ready,scoreRange:[0,71]},source_authority:'Knaus et al.',source_reference:'Crit Care Med. 1985;13:818–829. PMID 3928249',status:'approved',orgSetting:null},
  {id:'demo-scale-braden',scale_key:'braden',version:'BRADEN-1988',name_el:'Braden — Κίνδυνος βλάβης από πίεση',name_en:'Braden Scale — Pressure Injury Risk',category:'pressure_injury',population:['adult'],min_age_years:18,max_age_years:null,settings:['ward','icu','ed'],definition:{...ready,scoreRange:[6,23]},source_authority:'Braden & Bergstrom / AHRQ',source_reference:'Braden Scale for Predicting Pressure Sore Risk',status:'approved',orgSetting:null},
  {id:'demo-scale-morse',scale_key:'morse',version:'MFS-1989',name_el:'Morse Fall Scale — Κίνδυνος πτώσης ενηλίκων',name_en:'Morse Fall Scale — Adult Fall Risk',category:'fall_risk',population:['adult'],min_age_years:18,max_age_years:null,settings:['ward','icu','ed','acute_care'],definition:ready,source_authority:'Morse et al.',source_reference:'Morse Fall Scale, 1989',status:'approved',orgSetting:null},
  {id:'demo-scale-humpty-dumpty',scale_key:'humpty-dumpty',version:'HDFS-2.0',name_el:'Humpty Dumpty 2.0 — Παιδιατρικός κίνδυνος πτώσης',name_en:'Humpty Dumpty Falls Scale 2.0 — Pediatric Fall Risk',category:'falls',population:['pediatric'],min_age_years:0,max_age_years:null,settings:['pediatric_ward'],definition:{...ready,scoreRange:[5,20]},source_authority:"Nicklaus Children's Health System",source_reference:'Updated HDFS; J Pediatr Nurs. 2026',status:'approved',orgSetting:null},
])
