const AVAILABILITY_ORDER={required:0,recommended:1,available:2}
const normalized=x=>String(x||'').trim().toLowerCase()
export function patientAgeDays(dateOfBirth,now=new Date()){if(!dateOfBirth)return null;const birth=new Date(`${dateOfBirth}T12:00:00`);if(Number.isNaN(birth.getTime())||birth>now)return null;return Math.max(0,Math.floor((now.getTime()-birth.getTime())/86400000))}
export function patientAgeYears(dateOfBirth,now=new Date()){const days=patientAgeDays(dateOfBirth,now);return days==null?null:Math.floor(days/365.2425)}
export function patientAgeExactYears(dateOfBirth,now=new Date()){const days=patientAgeDays(dateOfBirth,now);return days==null?null:days/365.2425}
export function patientAgeLabel(dateOfBirth,language='el',now=new Date()){const days=patientAgeDays(dateOfBirth,now);if(days==null)return null;if(days<28)return language==='en'?`${days} days`:`${days} ημέρες`;if(days<730){const months=Math.floor(days/30.4375),rest=Math.floor(days%30.4375);return language==='en'?`${months} months, ${rest} days`:`${months} μήνες, ${rest} ημέρες`}const years=Math.floor(days/365.2425);return language==='en'?`${years} years`:`${years} έτη`}
const populationForAge=age=>age==null?null:age<0.083?'neonatal':age<18?'pediatric':'adult'
const settingAliases={icu:['icu','intensive care','μεθ'],picu:['picu','pediatric intensive care','paediatric intensive care','παιδιατρικη μεθ','παιδιατρική μεθ'],nicu:['nicu','neonatal intensive care','μενν'],ward:['ward','acute_care','general','clinic','general ward','κλινικη','κλινική','γενικη','γενική'],ed:['ed','emergency','τεπ'],pediatric_ward:['pediatric_ward','pediatric ward','pediatric','paediatric','παιδιατρικη','παιδιατρική'],pediatric_ed:['pediatric_ed','pediatric emergency','παιδιατρικο τεπ','παιδιατρικό τεπ'],maternity:['maternity','μαιευτικη','μαιευτική'],postnatal:['postnatal','λοχεια','λοχεία'],neonatal:['neonatal','nicu','μενν']}
const admissionValues=a=>[a?.care_setting,a?.setting,a?.department_type,a?.department_name,a?.department?.name,a?.department?.type].map(normalized).filter(Boolean)
const matchesSetting=(d,a)=>{const settings=(d.settings||[]).map(normalized).filter(Boolean);if(!settings.length)return true;const values=admissionValues(a);return !values.length||settings.some(s=>(settingAliases[s]||[s]).some(alias=>values.includes(alias)))}
export function isClinicalScaleEligible(d,{age,admission}={}){if(!d||d.status==='retired'||d.status==='draft')return false;if(d.orgSetting?.enabled===false||d.orgSetting?.availability==='disabled')return false;const population=populationForAge(age);if(population&&(d.population||[]).length&&!d.population.map(normalized).includes(population))return false;if(age!=null&&d.min_age_years!=null&&age<Number(d.min_age_years))return false;if(age!=null&&d.max_age_years!=null&&age>Number(d.max_age_years))return false;return matchesSetting(d,admission)}
const recommendation=(d,{age,admission}={})=>{const values=admissionValues(admission),pop=populationForAge(age),settings=(d.settings||[]).map(normalized);const exact=settings.some(s=>(settingAliases[s]||[s]).some(a=>values.includes(a)));const policy=d.orgSetting?.availability==='recommended'||d.orgSetting?.availability==='required';const recommended=policy||exact;return {recommended,reason:recommended?(exact?'care_setting':policy?'hospital_policy':pop==='neonatal'?'age_neonatal':pop==='pediatric'?'age_pediatric':null):null}}
export function buildClinicalScaleContext(definitions=[],assessments=[],context={},now=new Date()){return definitions.filter(d=>isClinicalScaleEligible(d,context)).map(d=>{const history=assessments.filter(r=>r.scale_definition_id===d.id).sort((a,b)=>new Date(b.assessed_at)-new Date(a.assessed_at));const latest=history[0]||null,previous=history[1]||null,hours=Number(d.orgSetting?.reassessment_hours)||null,dueAt=latest&&hours?new Date(new Date(latest.assessed_at).getTime()+hours*3600000):null,availability=d.orgSetting?.availability||'available',state=!latest?(availability==='required'?'due':'not-recorded'):(dueAt&&dueAt<=now?'overdue':dueAt?'current':'completed'),delta=latest&&previous?Number(latest.score)-Number(previous.score):null,rec=recommendation(d,context);return {...d,...rec,availability,latest,previous,dueAt:dueAt?.toISOString()||null,state,delta:Number.isFinite(delta)?delta:null}}).sort((a,b)=>(b.recommended?1:0)-(a.recommended?1:0)-(AVAILABILITY_ORDER[a.availability]??9)+(AVAILABILITY_ORDER[b.availability]??9)||(a.name_el||'').localeCompare(b.name_el||'','el'))}
