const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null}
const band=(v,rules)=>{for(const r of rules){if(r.test(v))return r.points}return 0}
export function scoreSofa(v={}){const parts={};const pf=num(v.pao2Fio2),platelets=num(v.platelets),bilirubin=num(v.bilirubin),gcs=num(v.gcs),creatinine=num(v.creatinine),urine=num(v.urineOutput24h),map=num(v.map),dopamine=num(v.dopamine),epinephrine=num(v.epinephrine),norepinephrine=num(v.norepinephrine)
 parts.respiratory=pf==null?null:band(pf,[{test:x=>x<100&&v.respiratorySupport,points:4},{test:x=>x<200&&v.respiratorySupport,points:3},{test:x=>x<300,points:2},{test:x=>x<400,points:1},{test:()=>true,points:0}])
 parts.coagulation=platelets==null?null:band(platelets,[{test:x=>x<20,points:4},{test:x=>x<50,points:3},{test:x=>x<100,points:2},{test:x=>x<150,points:1},{test:()=>true,points:0}])
 parts.liver=bilirubin==null?null:band(bilirubin,[{test:x=>x>=12,points:4},{test:x=>x>=6,points:3},{test:x=>x>=2,points:2},{test:x=>x>=1.2,points:1},{test:()=>true,points:0}])
 parts.cardiovascular=(map==null&&dopamine==null&&epinephrine==null&&norepinephrine==null)?null:(dopamine>15||epinephrine>0.1||norepinephrine>0.1?4:dopamine>5||epinephrine>0||norepinephrine>0?3:dopamine>0?2:map<70?1:0)
 parts.cns=gcs==null?null:band(gcs,[{test:x=>x<6,points:4},{test:x=>x<=9,points:3},{test:x=>x<=12,points:2},{test:x=>x<=14,points:1},{test:()=>true,points:0}])
 parts.renal=(creatinine==null&&urine==null)?null:(urine!=null&&urine<200?4:creatinine!=null&&creatinine>=5?4:urine!=null&&urine<500?3:creatinine!=null&&creatinine>=3.5?3:creatinine!=null&&creatinine>=2?2:creatinine!=null&&creatinine>=1.2?1:0)
 const complete=Object.values(parts).every(x=>x!=null);return {score:complete?Object.values(parts).reduce((a,b)=>a+b,0):null,parts,complete}}
const apacheRules={temperature:[[41,4],[39,3],[38.5,1],[36,0],[34,1],[32,2],[30,3],[-Infinity,4]],map:[[160,4],[130,3],[110,2],[70,0],[50,2],[-Infinity,4]],heartRate:[[180,4],[140,3],[110,2],[70,0],[55,2],[40,3],[-Infinity,4]],respiratoryRate:[[50,4],[35,3],[25,1],[12,0],[10,1],[6,2],[-Infinity,4]],ph:[[7.7,4],[7.6,3],[7.5,1],[7.33,0],[7.25,2],[7.15,3],[-Infinity,4]],sodium:[[180,4],[160,3],[155,2],[150,1],[130,0],[120,2],[111,3],[-Infinity,4]],potassium:[[7,4],[6,3],[5.5,1],[3.5,0],[3,1],[2.5,2],[-Infinity,4]],hematocrit:[[60,4],[50,2],[46,1],[30,0],[20,2],[-Infinity,4]],wbc:[[40,4],[15,1],[3,0],[1,2],[-Infinity,4]]}
const table=(v,r)=>{const n=num(v);if(n==null)return null;return r.find(([min])=>n>=min)?.[1]??0}
export function scoreApacheII(v={}){const p={};for(const k of Object.keys(apacheRules))p[k]=table(v[k],apacheRules[k]);const fio2=num(v.fio2),pao2=num(v.pao2),aado2=num(v.aado2);p.oxygenation=fio2==null?null:fio2>=.5?(aado2==null?null:table(aado2,[[500,4],[350,3],[200,2],[-Infinity,0]])):(pao2==null?null:table(pao2,[[71,0],[61,1],[55,3],[-Infinity,4]]));const cr=num(v.creatinine);p.creatinine=cr==null?null:table(cr,[[3.5,4],[2,3],[1.5,2],[.6,0],[-Infinity,2]])*(v.acuteRenalFailure?2:1);const g=num(v.gcs);p.gcs=g==null?null:15-g;const age=num(v.age);const agePoints=age==null?null:(age>=75?6:age>=65?5:age>=55?3:age>=45?2:0);const chronic=v.chronicHealthPoints==null?null:num(v.chronicHealthPoints);const complete=Object.values(p).every(x=>x!=null)&&agePoints!=null&&chronic!=null;return {score:complete?Object.values(p).reduce((a,b)=>a+b,0)+agePoints+chronic:null,parts:p,agePoints,chronicHealthPoints:chronic,complete}}
export function scoreBraden(v={}){const keys=['sensoryPerception','moisture','activity','mobility','nutrition','frictionShear'];const vals=keys.map(k=>num(v[k]));const valid=vals.every((x,i)=>x!=null&&x>=1&&x<=(i===5?3:4));return {score:valid?vals.reduce((a,b)=>a+b,0):null,parts:Object.fromEntries(keys.map((k,i)=>[k,vals[i]])),complete:valid}}
export function scoreHumptyDumpty20(v={}){const keys=['age','diagnosis','cognitiveImpairment','environmentalFactors','surgerySedationAnesthesia'];const vals=keys.map(k=>num(v[k]));const valid=vals.every(x=>x!=null&&x>=1&&x<=4);const score=valid?vals.reduce((a,b)=>a+b,0):null;return {score,parts:Object.fromEntries(keys.map((k,i)=>[k,vals[i]])),risk:score==null?null:score>=12?'high':'low',complete:valid}}
export function scoreNews2(v={}){const rr=num(v.respiratoryRate),spo2=num(v.spo2),sbp=num(v.systolicBp),pulse=num(v.pulse),temp=num(v.temperature),oxygen=Boolean(v.supplementalOxygen),confusion=Boolean(v.newConfusion);const scale2=Boolean(v.spo2Scale2);const parts={};parts.respiratory=rr==null?null:(rr<=8?3:rr<=11?1:rr<=20?0:rr<=24?2:3);parts.oxygenSaturation=spo2==null?null:(scale2?(spo2<=83?3:spo2<=85?2:spo2<=87?1:spo2<=92?0:spo2<=94?1:spo2<=96?2:3):(spo2<=91?3:spo2<=93?2:spo2<=95?1:0));parts.supplementalOxygen=oxygen?2:0;parts.systolicBp=sbp==null?null:(sbp<=90?3:sbp<=100?2:sbp<=110?1:sbp<=219?0:3);parts.pulse=pulse==null?null:(pulse<=40?3:pulse<=50?1:pulse<=90?0:pulse<=110?1:pulse<=130?2:3);parts.consciousness=confusion?3:0;parts.temperature=temp==null?null:(temp<=35?3:temp<=36?1:temp<=38?0:temp<=39?1:2);const complete=Object.values(parts).every(x=>x!=null);const score=complete?Object.values(parts).reduce((a,b)=>a+b,0):null;return {score,parts,risk:score==null?null:score>=7?'high':score>=5?'medium':score>=1?'low':'baseline',complete}}
export function scoreGcs(v={}){const eye=num(v.eye),verbal=num(v.verbal),motor=num(v.motor);const complete=eye!=null&&eye>=1&&eye<=4&&verbal!=null&&verbal>=1&&verbal<=5&&motor!=null&&motor>=1&&motor<=6;const score=complete?eye+verbal+motor:null;return {score,parts:{eye,verbal,motor},risk:score==null?null:score<=8?'severe':score<=12?'moderate':'mild_or_normal_range',complete}}
export function calculateClinicalScale(key,values){if(key==='sofa')return scoreSofa(values);if(key==='apache-ii')return scoreApacheII(values);if(key==='braden')return scoreBraden(values);if(key==='humpty-dumpty')return scoreHumptyDumpty20(values);if(key==='news2')return scoreNews2(values);if(key==='gcs')return scoreGcs(values);throw new Error('Unsupported clinical scale: '+key)}
