import {supabase} from '../../core/supabase/client'
import {buildDemoScaleAssessments} from './clinicalScaleDemoSeed'
// Demo session store: assessments recorded in the demo are kept for the
// session so they show up again in the record and as registry risk flags.
const demoAssessments=buildDemoScaleAssessments()
export function demoPatientScaleAssessments(){return demoAssessments}
export async function loadPatientScaleAssessments(organizationId,patientRecordId,admissionId,{isDemo=false}={}){if(isDemo||!supabase)return demoAssessments.filter(r=>String(r.patient_id)===String(patientRecordId)&&(!admissionId||String(r.admission_id||'')===String(admissionId))).sort((a,b)=>new Date(b.assessed_at)-new Date(a.assessed_at));let q=supabase.from('patient_clinical_scale_assessments').select('*,scale:clinical_scale_definitions(name_el,name_en,category)').eq('organization_id',organizationId).eq('patient_id',patientRecordId).order('assessed_at',{ascending:false});if(admissionId)q=q.eq('admission_id',admissionId);const {data,error}=await q;if(error)throw error;return data||[]}
export async function createPatientScaleAssessment(organizationId,patientRecordId,admissionId,definition,result,answers,{isDemo=false,assessor=null}={}){const row={id:crypto.randomUUID(),organization_id:organizationId,patient_id:patientRecordId,admission_id:admissionId||null,scale_definition_id:definition.id,scale_key:definition.scale_key,scale_version:definition.version,assessed_at:new Date().toISOString(),answers,score:result.score,score_parts:result.parts||{},interpretation:result.risk||null,status:'final',assessor_name:assessor?.fullName||assessor?.email||null,assessor_job_title:assessor?.jobTitle||null,assessor_email:assessor?.email||null,report_snapshot:{scaleNameEl:definition.name_el,scaleNameEn:definition.name_en,sourceAuthority:definition.source_authority,sourceReference:definition.source_reference,version:definition.version,score:result.score,parts:result.parts||{},interpretation:result.risk||null,answers,generatedAt:new Date().toISOString()}};if(isDemo||!supabase){const demoRow={...row,scale:{name_el:definition.name_el,name_en:definition.name_en,category:definition.category}};demoAssessments.push(demoRow);return demoRow}const {data,error}=await supabase.from('patient_clinical_scale_assessments').insert(row).select('*,scale:clinical_scale_definitions(name_el,name_en,category)').single();if(error)throw error;return data}

export async function updatePatientScaleAssessment(id,organizationId,definition,result,answers,{isDemo=false,assessor=null}={}){const patch={scale_definition_id:definition.id,scale_key:definition.scale_key,scale_version:definition.version,answers,score:result.score,score_parts:result.parts||{},interpretation:result.risk||null,status:'amended',amended_at:new Date().toISOString(),assessor_name:assessor?.fullName||assessor?.email||null,assessor_job_title:assessor?.jobTitle||null,assessor_email:assessor?.email||null,report_snapshot:{scaleNameEl:definition.name_el,scaleNameEn:definition.name_en,sourceAuthority:definition.source_authority,sourceReference:definition.source_reference,version:definition.version,score:result.score,parts:result.parts||{},interpretation:result.risk||null,answers,generatedAt:new Date().toISOString()}};if(isDemo||!supabase){const index=demoAssessments.findIndex(r=>r.id===id);const next={...(demoAssessments[index]||{}),id,...patch,assessed_at:demoAssessments[index]?.assessed_at||new Date().toISOString()};if(index>=0)demoAssessments[index]=next;return next}const {data,error}=await supabase.from('patient_clinical_scale_assessments').update(patch).eq('id',id).eq('organization_id',organizationId).select('*,scale:clinical_scale_definitions(name_el,name_en,category)').single();if(error)throw error;return data}
export async function deletePatientScaleAssessment(id,organizationId,{isDemo=false,language='el'}={}){if(isDemo||!supabase){if(!window.confirm(language==='en'?'Delete this clinical assessment?':'Να διαγραφεί η κλινική αξιολόγηση;'))return false;const index=demoAssessments.findIndex(r=>r.id===id);if(index>=0)demoAssessments.splice(index,1);return true}if(!window.confirm(language==='en'?'Delete this clinical assessment?':'Να διαγραφεί η κλινική αξιολόγηση;'))return false;const {error}=await supabase.from('patient_clinical_scale_assessments').delete().eq('id',id).eq('organization_id',organizationId);if(error)throw error;return true}
