import {useEffect,useMemo,useState} from 'react'
import {Activity,FileText,Pencil,Plus,Printer,Trash2} from 'lucide-react'
import {Button} from '../../design-system/Button'
import {useAuth} from '../../core/auth/AuthContext'
import {ObserverDialog,DialogActions} from '../../design-system/ObserverDialog'
import {RegistryTable} from '../../design-system/RegistryTable'
import {RegistryPagination} from '../../design-system/RegistryPagination'
import {OverflowMenu} from '../../design-system/OverflowMenu'
import {loadClinicalScales} from '../management/clinicalScalesService'
import {calculateClinicalScale} from './clinicalScaleEngine'
import {buildClinicalScaleContext,patientAgeYears,patientAgeLabel} from './clinicalScaleContext'
import {clinicalScalePrefill,mergeClinicalScalePrefill} from './clinicalScalePrefill'
import {createPatientScaleAssessment,deletePatientScaleAssessment,loadPatientScaleAssessments,updatePatientScaleAssessment} from './patientClinicalScalesService'

const FIELD_DEFINITIONS={
 sofa:[['pao2Fio2','PaO₂/FiO₂','PaO₂/FiO₂'],['platelets','Αιμοπετάλια','Platelets'],['bilirubin','Χολερυθρίνη','Bilirubin'],['map','Μέση αρτηριακή πίεση (MAP)','Mean arterial pressure (MAP)'],['dopamine','Ντοπαμίνη (μg/kg/min)','Dopamine (μg/kg/min)'],['epinephrine','Επινεφρίνη (μg/kg/min)','Epinephrine (μg/kg/min)'],['norepinephrine','Νορεπινεφρίνη (μg/kg/min)','Norepinephrine (μg/kg/min)'],['gcs','Κλίμακα Γλασκώβης (GCS)','Glasgow Coma Scale (GCS)'],['creatinine','Κρεατινίνη (mg/dL)','Creatinine (mg/dL)'],['urineOutput24h','Διούρηση 24ώρου (mL)','24-hour urine output (mL)']],
 'apache-ii':[['temperature','Θερμοκρασία (°C)','Temperature (°C)'],['map','Μέση αρτηριακή πίεση (MAP, mmHg)','Mean arterial pressure (MAP, mmHg)'],['heartRate','Καρδιακή συχνότητα (/λεπτό)','Heart rate (/min)'],['respiratoryRate','Αναπνευστική συχνότητα (/λεπτό)','Respiratory rate (/min)'],['fio2','FiO₂','FiO₂'],['pao2','PaO₂ (mmHg)','PaO₂ (mmHg)'],['aado2','A–aDO₂ (mmHg)','A–aDO₂ (mmHg)'],['ph','Αρτηριακό pH','Arterial pH'],['sodium','Νάτριο (mmol/L)','Sodium (mmol/L)'],['potassium','Κάλιο (mmol/L)','Potassium (mmol/L)'],['creatinine','Κρεατινίνη (mg/dL)','Creatinine (mg/dL)'],['hematocrit','Αιματοκρίτης (%)','Hematocrit (%)'],['wbc','Λευκά αιμοσφαίρια (×10³/μL)','White blood cells (×10³/μL)'],['gcs','Κλίμακα Γλασκώβης (GCS)','Glasgow Coma Scale (GCS)']],
 news2:[['respiratoryRate','Αναπνευστική συχνότητα (/λεπτό)','Respiratory rate (/min)'],['spo2','SpO₂ (%)','SpO₂ (%)'],['systolicBp','Συστολική αρτηριακή πίεση (mmHg)','Systolic blood pressure (mmHg)'],['pulse','Σφύξεις (/λεπτό)','Pulse (/min)'],['temperature','Θερμοκρασία (°C)','Temperature (°C)']],
 gcs:[['eye','Οφθαλμική απόκριση (1–4)','Eye response (1–4)'],['verbal','Λεκτική απόκριση (1–5)','Verbal response (1–5)'],['motor','Κινητική απόκριση (1–6)','Motor response (1–6)']],
 braden:[['sensoryPerception','Αισθητηριακή αντίληψη (1–4)','Sensory perception (1–4)'],['moisture','Υγρασία (1–4)','Moisture (1–4)'],['activity','Δραστηριότητα (1–4)','Activity (1–4)'],['mobility','Κινητικότητα (1–4)','Mobility (1–4)'],['nutrition','Θρέψη (1–4)','Nutrition (1–4)'],['frictionShear','Τριβή και διάτμηση (1–3)','Friction and shear (1–3)']],
 'humpty-dumpty':[['age','Ηλικία — βαθμός','Age score'],['diagnosis','Διάγνωση — βαθμός','Diagnosis score'],['cognitiveImpairment','Γνωστική κατάσταση — βαθμός','Cognitive impairment score'],['environmentalFactors','Περιβαλλοντικοί παράγοντες — βαθμός','Environmental factors score'],['surgerySedationAnesthesia','Χειρουργείο / καταστολή / αναισθησία — βαθμός','Surgery / sedation / anesthesia score']]
}
const formatDate=(value,en)=>new Intl.DateTimeFormat(en?'en-GB':'el-GR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value))
const scaleName=(row,en)=>en?(row.scale?.name_en||row.name_en||row.scale_key):(row.scale?.name_el||row.name_el||row.scale_key)
const trendLabel=(row,en)=>{if(row.delta==null)return '';if(row.delta===0)return en?'No change':'Χωρίς μεταβολή';return `${row.delta>0?'▲':'▼'} ${Math.abs(row.delta)}`}
const riskMeta=(row,en)=>{const risk=row?.risk||row?.interpretation;if(!risk)return null;const key=String(risk).toLowerCase();if(['high','severe'].some(x=>key.includes(x)))return {label:en?'High':'Υψηλό',tone:'danger'};if(['medium','moderate'].some(x=>key.includes(x)))return {label:en?'Moderate':'Μέτριο',tone:'warning'};if(['low','baseline','mild','normal'].some(x=>key.includes(x)))return {label:en?'Low / normal':'Χαμηλό / φυσιολογικό',tone:'active'};return {label:String(risk),tone:''}}
const reasonLabel=(x,en)=>({age_neonatal:en?'Recommended for neonatal age':'Προτείνεται λόγω νεογνικής ηλικίας',age_pediatric:en?'Recommended for pediatric age':'Προτείνεται λόγω παιδιατρικής ηλικίας',care_setting:en?'Recommended for this care setting':'Προτείνεται για το συγκεκριμένο τμήμα/περιβάλλον',hospital_policy:en?'Recommended by hospital policy':'Προτείνεται από την πολιτική νοσοκομείου'}[x.recommendationReason||x.reason]||'')
const dueLabel=(x,en)=>{if(x.state==='overdue')return en?'Reassessment overdue':'Εκπρόθεσμη επανεκτίμηση';if(x.state==='due')return en?'Assessment due':'Απαιτείται αξιολόγηση';if(!x.latest)return en?'Not recorded':'Δεν έχει καταγραφεί';if(x.dueAt){const ms=new Date(x.dueAt)-new Date();const h=Math.max(0,Math.ceil(ms/3600000));return en?`Reassess in ${h} h`:`Επανεκτίμηση σε ${h} ώρ.`}return en?'Completed':'Ολοκληρωμένη'}
const dueTone=x=>x.state==='overdue'?'danger':x.state==='due'?'warning':x.state==='current'?'active':''
const assessmentSignal=(r,en)=>{const m=riskMeta(r,en);if(m)return m;const key=r.scale_key||r.scale?.scale_key;if(key==='braden'&&Number.isFinite(Number(r.score)))return {label:Number(r.score)<=18?(en?'At risk':'Κίνδυνος'):(en?'No current risk flag':'Χωρίς ένδειξη κινδύνου'),tone:Number(r.score)<=18?'warning':'active'};if(key==='humpty-dumpty'&&Number.isFinite(Number(r.score)))return {label:Number(r.score)>=12?(en?'High fall risk':'Υψηλός κίνδυνος πτώσης'):(en?'Low fall risk':'Χαμηλός κίνδυνος πτώσης'),tone:Number(r.score)>=12?'danger':'active'};return null}
export function PatientClinicalScalesPanel({organizationId,patient,admission,clinicalData=null,latestLabs=null,latestVitals=null,isDemo=false,language='el',canRecord=true}){const {profile,user}=useAuth();const assessor=profile||user;const en=language==='en',[defs,setDefs]=useState([]),[rows,setRows]=useState([]),[selected,setSelected]=useState(null),[answers,setAnswers]=useState({}),[error,setError]=useState(''),[report,setReport]=useState(null)
 async function load(){if(!patient?.recordId)return;const [d,r]=await Promise.all([isDemo?Promise.resolve([]):loadClinicalScales(organizationId),loadPatientScaleAssessments(organizationId,patient.recordId,admission?.id,{isDemo})]);setDefs(d);setRows(r)}
 useEffect(()=>{void load()},[organizationId,patient?.recordId,admission?.id,isDemo])
 const age=patientAgeYears(patient?.dateOfBirth)
 const ageDisplay=patientAgeLabel(patient?.dateOfBirth,language)
 const scaleContext=useMemo(()=>buildClinicalScaleContext(defs,rows,{age,admission}),[defs,rows,age,admission])
 const available=useMemo(()=>scaleContext,[scaleContext])
 const recommended=useMemo(()=>available.filter(x=>x.recommended),[available])
 const otherAvailable=useMemo(()=>available.filter(x=>!x.recommended),[available])
 const contextByDefinition=useMemo(()=>new Map(scaleContext.map(x=>[x.id,x])),[scaleContext])
 const [pickerOpen,setPickerOpen]=useState(false)
 const [page,setPage]=useState(1),[pageSize,setPageSize]=useState(15)
 const totalPages=Math.max(1,Math.ceil(rows.length/pageSize)),safePage=Math.min(page,totalPages)
 const pagedRows=rows.slice((safePage-1)*pageSize,safePage*pageSize)
 useEffect(()=>{if(page!==safePage)setPage(safePage)},[page,safePage])
 function open(definition,row=null){setSelected({...definition,_assessmentId:row?.id||null});setError('');const base=row?.answers||((definition.scale_key==='apache-ii')?{age:age??'',chronicHealthPoints:0}:{});const prefill=row?{}:clinicalScalePrefill(definition.scale_key,{patient,admission,clinicalData,latestLabs,latestVitals});setAnswers(mergeClinicalScalePrefill(base,prefill))}
 function edit(row){const definition=defs.find(d=>d.id===row.scale_definition_id);if(definition)open(definition,row)}
 async function remove(row){try{const deleted=await deletePatientScaleAssessment(row.id,organizationId,{isDemo,language});if(deleted!==false)setRows(x=>x.filter(r=>r.id!==row.id))}catch(e){setError(e.message)}}
 async function save(){try{const result=calculateClinicalScale(selected.scale_key,answers);if(!result.complete||result.score==null){setError(en?'Complete all required parameters before calculation.':'Συμπληρώστε όλες τις απαιτούμενες παραμέτρους πριν από τον υπολογισμό.');return}const row=selected._assessmentId?await updatePatientScaleAssessment(selected._assessmentId,organizationId,selected,result,answers,{isDemo,assessor}):await createPatientScaleAssessment(organizationId,patient.recordId,admission?.id,selected,result,answers,{isDemo,assessor});setRows(x=>selected._assessmentId?x.map(r=>r.id===selected._assessmentId?row:r):[row,...x]);setSelected(null)}catch(e){setError(e.message)}}
 const fields=selected?FIELD_DEFINITIONS[selected.scale_key]||[]:[]
 return <>
  <section className="surface registry-workspace workspace-column workspace-fill clinical-assessment-registry">
   <div className="section-toolbar"><div><h3>{en?'Clinical assessments':'Κλινικές αξιολογήσεις'}</h3>{ageDisplay&&<small className="entry-detail-note">{en?'Patient age: ':'Ηλικία ασθενούς: '}{ageDisplay}</small>}{recommended.length>0&&<small className="entry-detail-note">{en?`${recommended.length} recommended for this patient`:`${recommended.length} προτεινόμενες για τον συγκεκριμένο ασθενή`} · {recommended.filter(x=>x.state==='overdue'||x.state==='due').length>0&&(en?`${recommended.filter(x=>x.state==='overdue'||x.state==='due').length} need attention`:`${recommended.filter(x=>x.state==='overdue'||x.state==='due').length} χρειάζονται ενέργεια`)}</small>}</div>{canRecord&&available.length>0&&<Button onClick={()=>setPickerOpen(true)}><Plus size={15}/>{en?'New assessment':'Νέα αξιολόγηση'}</Button>}</div>
    <div className="scroll-table"><RegistryTable bare columns={[{key:'date',label:en?'Date / time':'Ημερομηνία / ώρα'},{key:'scale',label:en?'Assessment tool':'Εργαλείο αξιολόγησης'},{key:'score',label:en?'Score':'Βαθμολογία'},{key:'result',label:en?'Result':'Ένδειξη'},{key:'version',label:en?'Version':'Έκδοση'},{key:'actions',label:''}]} rows={pagedRows} rowKey={r=>r.id} emptyTitle={en?'No clinical assessments':'Δεν υπάρχουν κλινικές αξιολογήσεις'} emptyText={en?'Create the first assessment for this admission.':'Δημιουργήστε την πρώτη αξιολόγηση για τη συγκεκριμένη νοσηλεία.'} renderRow={r=><><td>{formatDate(r.assessed_at,en)}</td><td><strong>{scaleName(r,en)}</strong></td><td><strong>{r.score}</strong>{contextByDefinition.get(r.scale_definition_id)?.latest?.id===r.id&&contextByDefinition.get(r.scale_definition_id)?.delta!=null&&<small className="entry-detail-note">{trendLabel(contextByDefinition.get(r.scale_definition_id),en)}</small>}</td><td>{assessmentSignal(r,en)?<span className={'status-badge '+assessmentSignal(r,en).tone}>{assessmentSignal(r,en).label}</span>:'—'}</td><td>{r.scale_version}</td><td className="open-record-cell"><OverflowMenu label={en?'Assessment actions':'Ενέργειες αξιολόγησης'} items={[{id:'report',label:en?'Full report':'Πλήρης αναφορά',icon:FileText,onClick:()=>setReport(r)},{id:'edit',label:en?'Edit':'Επεξεργασία',icon:Pencil,onClick:()=>edit(r)},{id:'delete',label:en?'Delete':'Διαγραφή',icon:Trash2,tone:'danger',separatorBefore:true,onClick:()=>remove(r)}]}/></td></>}/></div>
    <RegistryPagination language={language} page={safePage} totalPages={totalPages} totalItems={rows.length} pageSize={pageSize} onPageChange={setPage} onPageSizeChange={size=>{setPageSize(size);setPage(1)}}/>
  </section>
  {pickerOpen&&<ObserverDialog width="standard" title={en?'Choose assessment':'Επιλογή αξιολόγησης'} subtitle={en?'Suggestions use the patient age, care setting and hospital policy.':'Οι προτάσεις βασίζονται στην ηλικία, το περιβάλλον νοσηλείας και την πολιτική του νοσοκομείου.'} onClose={()=>setPickerOpen(false)}><div className="clinical-scale-picker-list">{recommended.length>0&&<><div className="clinical-scale-picker-heading"><strong>{en?'Suggested for this patient':'Προτεινόμενες για τον ασθενή'}</strong><small>{en?'Clinical decision support — the clinician remains responsible for tool selection.':'Υποστήριξη κλινικής απόφασης — η τελική επιλογή του εργαλείου παραμένει στον επαγγελματία υγείας.'}</small></div>{recommended.map(x=><button type="button" className="clinical-scale-picker-row" key={x.id} onClick={()=>{setPickerOpen(false);open(x)}}><strong>{scaleName(x,en)} <span className="status-badge active">{en?'Recommended':'Προτεινόμενη'}</span></strong><small>{reasonLabel(x,en)} · <span className={'status-badge '+dueTone(x)}>{dueLabel(x,en)}</span>{x.latest&&<> · {en?'Last score: ':'Τελευταία βαθμολογία: '}{x.latest.score}</>}</small></button>)}</>}{otherAvailable.length>0&&<><div className="clinical-scale-picker-heading"><strong>{en?'Other available tools':'Άλλα διαθέσιμα εργαλεία'}</strong></div>{otherAvailable.map(x=><button type="button" className="clinical-scale-picker-row" key={x.id} onClick={()=>{setPickerOpen(false);open(x)}}><strong>{scaleName(x,en)}</strong><small>{x.availability==='required'?(en?'Required':'Υποχρεωτική'):(en?'Available':'Διαθέσιμη')} · <span className={'status-badge '+dueTone(x)}>{dueLabel(x,en)}</span>{x.latest&&<> · {en?'Last score: ':'Τελευταία βαθμολογία: '}{x.latest.score}</>}</small></button>)}</>}</div></ObserverDialog>}
  {report&&<ObserverDialog width="large" title={en?'Clinical assessment report':'Αναφορά κλινικής αξιολόγησης'} subtitle={scaleName(report,en)} onClose={()=>setReport(null)} footer={<DialogActions onCancel={()=>setReport(null)} cancelLabel={en?'Close':'Κλείσιμο'} extra={<Button variant="secondary" onClick={()=>window.print()}><Printer size={15}/>{en?'Print':'Εκτύπωση'}</Button>}/>}><div className="clinical-score-report"><div className="entry-grid"><div><span>{en?'Date / time':'Ημερομηνία / ώρα'}</span><strong>{formatDate(report.assessed_at,en)}</strong></div><div><span>{en?'Score':'Βαθμολογία'}</span><strong>{report.score}</strong></div><div><span>{en?'Version':'Έκδοση'}</span><strong>{report.scale_version}</strong></div><div><span>{en?'Assessed by':'Αξιολόγηση από'}</span><strong>{report.assessor_name||'—'}</strong><small>{report.assessor_job_title||''}</small></div></div><div className="record-section"><h4>{en?'Recorded parameters':'Καταχωρισμένες παράμετροι'}</h4><div className="entry-grid">{Object.entries(report.answers||{}).map(([key,value])=><div key={key}><span>{key}</span><strong>{typeof value==='boolean'?(value?(en?'Yes':'Ναι'):(en?'No':'Όχι')):String(value??'—')}</strong></div>)}</div></div><div className="record-section"><h4>{en?'Calculated components':'Υπολογισμένα επιμέρους'}</h4><div className="entry-grid">{Object.entries(report.score_parts||{}).map(([key,value])=><div key={key}><span>{key}</span><strong>{String(value??'—')}</strong></div>)}</div></div>{report.interpretation&&<div className="record-section"><h4>{en?'Interpretation':'Ερμηνεία'}</h4><strong>{report.interpretation}</strong></div>}<div className="record-section"><h4>{en?'Governance':'Τεκμηρίωση'}</h4><p>{report.report_snapshot?.sourceAuthority||'—'}</p><small>{report.report_snapshot?.sourceReference||'—'}</small></div></div></ObserverDialog>}
  {selected&&<ObserverDialog width="large" title={scaleName(selected,en)} subtitle={selected.source_reference||selected.version} onClose={()=>setSelected(null)} footer={<DialogActions onCancel={()=>setSelected(null)} onSave={save} saveLabel={en?'Calculate & save':'Υπολογισμός & αποθήκευση'}/>}>
   <div className="record-section"><label className="field"><span>{en?'Assessment tool':'Εργαλείο αξιολόγησης'}</span><select value={selected.id} onChange={e=>open(available.find(x=>x.id===e.target.value))}>{available.map(x=><option key={x.id} value={x.id}>{scaleName(x,en)}</option>)}</select></label></div>
   {selected.scale_key==='apache-ii'&&<div className="record-section"><div className="record-section-header"><div><h4>{en?'Patient factors':'Στοιχεία ασθενούς'}</h4><p>{en?'Age is calculated from the recorded date of birth.':'Η ηλικία υπολογίζεται από την καταχωρισμένη ημερομηνία γέννησης.'}</p></div></div><div className="entry-grid"><label><span>{en?'Age (years)':'Ηλικία (έτη)'}</span><input value={age??''} readOnly/></label><label><span>{en?'Chronic health points':'Βαθμοί χρόνιας κατάστασης υγείας'}</span><input type="number" min="0" value={answers.chronicHealthPoints??0} onChange={e=>setAnswers(a=>({...a,chronicHealthPoints:e.target.value}))}/></label></div><label className="checkbox-row" style={{display:'flex',alignItems:'center',gap:8,flexDirection:'row',marginTop:14}}><input type="checkbox" checked={Boolean(answers.acuteRenalFailure)} onChange={e=>setAnswers(a=>({...a,acuteRenalFailure:e.target.checked}))}/><span>{en?'Acute renal failure':'Οξεία νεφρική ανεπάρκεια'}</span></label></div>}
   <div className="record-section"><div className="record-section-header"><div><h4>{en?'Assessment parameters':'Παράμετροι αξιολόγησης'}</h4>{selected.scale_key==='apache-ii'&&<p>{en?'Enter the worst values from the first 24 hours in ICU.':'Καταχωρίστε τις δυσμενέστερες τιμές των πρώτων 24 ωρών στη ΜΕΘ.'}</p>}</div></div><div className="entry-grid">{fields.map(([key,elLabel,enLabel])=><label key={key}><span>{en?enLabel:elLabel}</span><input type="number" step="any" value={answers[key]??''} onChange={e=>setAnswers(a=>({...a,[key]:e.target.value}))}/></label>)}</div>
   {selected.scale_key==='news2'&&<><label className="checkbox-row" style={{display:'flex',alignItems:'center',gap:8,flexDirection:'row',marginTop:14}}><input type="checkbox" checked={Boolean(answers.supplementalOxygen)} onChange={e=>setAnswers(a=>({...a,supplementalOxygen:e.target.checked}))}/><span>{en?'Supplemental oxygen':'Συμπληρωματικό οξυγόνο'}</span></label><label className="checkbox-row" style={{display:'flex',alignItems:'center',gap:8,flexDirection:'row',marginTop:10}}><input type="checkbox" checked={Boolean(answers.spo2Scale2)} onChange={e=>setAnswers(a=>({...a,spo2Scale2:e.target.checked}))}/><span>{en?'NEWS2 SpO₂ Scale 2 (confirmed hypercapnic respiratory failure)':'NEWS2 SpO₂ Scale 2 (επιβεβαιωμένη υπερκαπνική αναπνευστική ανεπάρκεια)'}</span></label><label className="checkbox-row" style={{display:'flex',alignItems:'center',gap:8,flexDirection:'row',marginTop:10}}><input type="checkbox" checked={Boolean(answers.newConfusion)} onChange={e=>setAnswers(a=>({...a,newConfusion:e.target.checked}))}/><span>{en?'New confusion':'Νέα σύγχυση'}</span></label></>}
   {selected.scale_key==='sofa'&&<label className="checkbox-row" style={{display:'flex',alignItems:'center',gap:8,flexDirection:'row',marginTop:14}}><input type="checkbox" checked={Boolean(answers.respiratorySupport)} onChange={e=>setAnswers(a=>({...a,respiratorySupport:e.target.checked}))}/><span>{en?'Respiratory support':'Αναπνευστική υποστήριξη'}</span></label>}</div>
   {error&&<div className="entry-detail-note"><Activity size={14}/>{error}</div>}
   <p className="entry-detail-note">{en?'The score is calculated automatically from the entered values using the governed deterministic scoring engine.':'Η βαθμολογία υπολογίζεται αυτόματα από τις καταχωρισμένες τιμές μέσω της εγκεκριμένης, καθορισμένης μηχανής υπολογισμού.'}</p>
  </ObserverDialog>}
 </>}
