import {useEffect,useMemo,useState} from 'react'
import {Activity,Pencil,Plus,Trash2} from 'lucide-react'
import {Button} from '../../design-system/Button'
import {ObserverDialog,DialogActions} from '../../design-system/ObserverDialog'
import {RegistryTable} from '../../design-system/RegistryTable'
import {OverflowMenu} from '../../design-system/OverflowMenu'
import {loadClinicalScales} from '../management/clinicalScalesService'
import {calculateClinicalScale} from './clinicalScaleEngine'
import {buildClinicalScaleContext,patientAgeYears} from './clinicalScaleContext'
import {clinicalScalePrefill,mergeClinicalScalePrefill} from './clinicalScalePrefill'
import {createPatientScaleAssessment,deletePatientScaleAssessment,loadPatientScaleAssessments,updatePatientScaleAssessment} from './patientClinicalScalesService'

const FIELD_DEFINITIONS={
 sofa:[['pao2Fio2','PaO₂/FiO₂','PaO₂/FiO₂'],['platelets','Αιμοπετάλια','Platelets'],['bilirubin','Χολερυθρίνη','Bilirubin'],['map','Μέση αρτηριακή πίεση (MAP)','Mean arterial pressure (MAP)'],['dopamine','Ντοπαμίνη (μg/kg/min)','Dopamine (μg/kg/min)'],['epinephrine','Επινεφρίνη (μg/kg/min)','Epinephrine (μg/kg/min)'],['norepinephrine','Νορεπινεφρίνη (μg/kg/min)','Norepinephrine (μg/kg/min)'],['gcs','Κλίμακα Γλασκώβης (GCS)','Glasgow Coma Scale (GCS)'],['creatinine','Κρεατινίνη (mg/dL)','Creatinine (mg/dL)'],['urineOutput24h','Διούρηση 24ώρου (mL)','24-hour urine output (mL)']],
 'apache-ii':[['temperature','Θερμοκρασία (°C)','Temperature (°C)'],['map','Μέση αρτηριακή πίεση (MAP, mmHg)','Mean arterial pressure (MAP, mmHg)'],['heartRate','Καρδιακή συχνότητα (/λεπτό)','Heart rate (/min)'],['respiratoryRate','Αναπνευστική συχνότητα (/λεπτό)','Respiratory rate (/min)'],['fio2','FiO₂','FiO₂'],['pao2','PaO₂ (mmHg)','PaO₂ (mmHg)'],['aado2','A–aDO₂ (mmHg)','A–aDO₂ (mmHg)'],['ph','Αρτηριακό pH','Arterial pH'],['sodium','Νάτριο (mmol/L)','Sodium (mmol/L)'],['potassium','Κάλιο (mmol/L)','Potassium (mmol/L)'],['creatinine','Κρεατινίνη (mg/dL)','Creatinine (mg/dL)'],['hematocrit','Αιματοκρίτης (%)','Hematocrit (%)'],['wbc','Λευκά αιμοσφαίρια (×10³/μL)','White blood cells (×10³/μL)'],['gcs','Κλίμακα Γλασκώβης (GCS)','Glasgow Coma Scale (GCS)']],
 braden:[['sensoryPerception','Αισθητηριακή αντίληψη (1–4)','Sensory perception (1–4)'],['moisture','Υγρασία (1–4)','Moisture (1–4)'],['activity','Δραστηριότητα (1–4)','Activity (1–4)'],['mobility','Κινητικότητα (1–4)','Mobility (1–4)'],['nutrition','Θρέψη (1–4)','Nutrition (1–4)'],['frictionShear','Τριβή και διάτμηση (1–3)','Friction and shear (1–3)']],
 'humpty-dumpty':[['age','Ηλικία — βαθμός','Age score'],['diagnosis','Διάγνωση — βαθμός','Diagnosis score'],['cognitiveImpairment','Γνωστική κατάσταση — βαθμός','Cognitive impairment score'],['environmentalFactors','Περιβαλλοντικοί παράγοντες — βαθμός','Environmental factors score'],['surgerySedationAnesthesia','Χειρουργείο / καταστολή / αναισθησία — βαθμός','Surgery / sedation / anesthesia score']]
}
const formatDate=(value,en)=>new Intl.DateTimeFormat(en?'en-GB':'el-GR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value))
const scaleName=(row,en)=>en?(row.scale?.name_en||row.name_en||row.scale_key):(row.scale?.name_el||row.name_el||row.scale_key)
const trendLabel=(row,en)=>{if(row.delta==null)return '';if(row.delta===0)return en?'No change':'Χωρίς μεταβολή';return `${row.delta>0?'▲':'▼'} ${Math.abs(row.delta)}`}
export function PatientClinicalScalesPanel({organizationId,patient,admission,clinicalData=null,latestLabs=null,latestVitals=null,isDemo=false,language='el',canRecord=true}){const en=language==='en',[defs,setDefs]=useState([]),[rows,setRows]=useState([]),[selected,setSelected]=useState(null),[answers,setAnswers]=useState({}),[error,setError]=useState('')
 async function load(){if(!patient?.recordId)return;const [d,r]=await Promise.all([isDemo?Promise.resolve([]):loadClinicalScales(organizationId),loadPatientScaleAssessments(organizationId,patient.recordId,admission?.id,{isDemo})]);setDefs(d);setRows(r)}
 useEffect(()=>{void load()},[organizationId,patient?.recordId,admission?.id,isDemo])
 const age=patientAgeYears(patient?.dateOfBirth)
 const scaleContext=useMemo(()=>buildClinicalScaleContext(defs,rows,{age,admission}),[defs,rows,age,admission])
 const available=useMemo(()=>scaleContext,[scaleContext])
 const contextByDefinition=useMemo(()=>new Map(scaleContext.map(x=>[x.id,x])),[scaleContext])
 const [pickerOpen,setPickerOpen]=useState(false)
 function open(definition,row=null){setSelected({...definition,_assessmentId:row?.id||null});setError('');const base=row?.answers||((definition.scale_key==='apache-ii')?{age:age??'',chronicHealthPoints:0}:{});const prefill=row?{}:clinicalScalePrefill(definition.scale_key,{patient,admission,clinicalData,latestLabs,latestVitals});setAnswers(mergeClinicalScalePrefill(base,prefill))}
 function edit(row){const definition=defs.find(d=>d.id===row.scale_definition_id);if(definition)open(definition,row)}
 async function remove(row){try{const deleted=await deletePatientScaleAssessment(row.id,organizationId,{isDemo});if(deleted!==false)setRows(x=>x.filter(r=>r.id!==row.id))}catch(e){setError(e.message)}}
 async function save(){try{const result=calculateClinicalScale(selected.scale_key,answers);if(!result.complete||result.score==null){setError(en?'Complete all required parameters before calculation.':'Συμπληρώστε όλες τις απαιτούμενες παραμέτρους πριν από τον υπολογισμό.');return}const row=selected._assessmentId?await updatePatientScaleAssessment(selected._assessmentId,organizationId,selected,result,answers,{isDemo}):await createPatientScaleAssessment(organizationId,patient.recordId,admission?.id,selected,result,answers,{isDemo});setRows(x=>selected._assessmentId?x.map(r=>r.id===selected._assessmentId?row:r):[row,...x]);setSelected(null)}catch(e){setError(e.message)}}
 const fields=selected?FIELD_DEFINITIONS[selected.scale_key]||[]:[]
 return <div className="workspace-column workspace-fill clinical-scales-panel">
  <div className="record-section-header"><div><h3>{en?'Clinical assessments':'Κλινικές αξιολογήσεις'}</h3><p>{en?'Validated clinical assessments for this admission.':'Επικυρωμένες κλινικές αξιολογήσεις για τη συγκεκριμένη νοσηλεία.'}</p></div>{canRecord&&available.length>0&&<Button onClick={()=>setPickerOpen(true)}><Plus size={15}/>{en?'New assessment':'Νέα αξιολόγηση'}</Button>}</div>
  <RegistryTable columns={[{key:'date',label:en?'Date / time':'Ημερομηνία / ώρα'},{key:'scale',label:en?'Assessment tool':'Εργαλείο αξιολόγησης'},{key:'score',label:'Score'},{key:'version',label:en?'Version':'Έκδοση'},{key:'actions',label:''}]} rows={rows} rowKey={r=>r.id} wrapperClassName="table-wrap scroll-table" emptyTitle={en?'No clinical assessments':'Δεν υπάρχουν κλινικές αξιολογήσεις'} emptyText={en?'Create the first assessment for this admission.':'Δημιουργήστε την πρώτη αξιολόγηση για τη συγκεκριμένη νοσηλεία.'} renderRow={r=><><td>{formatDate(r.assessed_at,en)}</td><td><strong>{scaleName(r,en)}</strong></td><td><strong>{r.score}</strong>{contextByDefinition.get(r.scale_definition_id)?.latest?.id===r.id&&contextByDefinition.get(r.scale_definition_id)?.delta!=null&&<small className="entry-detail-note">{trendLabel(contextByDefinition.get(r.scale_definition_id),en)}</small>}</td><td>{r.scale_version}</td><td className="open-record-cell"><OverflowMenu label={en?'Assessment actions':'Ενέργειες αξιολόγησης'} items={[{id:'edit',label:en?'Edit':'Επεξεργασία',icon:Pencil,onClick:()=>edit(r)},{id:'delete',label:en?'Delete':'Διαγραφή',icon:Trash2,tone:'danger',separatorBefore:true,onClick:()=>remove(r)}]}/></td></>}/>
  {pickerOpen&&<ObserverDialog width="standard" title={en?'Choose assessment':'Επιλογή αξιολόγησης'} subtitle={en?'Only tools applicable to this patient and admission are shown.':'Εμφανίζονται μόνο τα εργαλεία που αντιστοιχούν στον ασθενή και στη συγκεκριμένη νοσηλεία.'} onClose={()=>setPickerOpen(false)}><div className="clinical-scale-picker-list">{available.map(x=><button type="button" className="clinical-scale-picker-row" key={x.id} onClick={()=>{setPickerOpen(false);open(x)}}><strong>{scaleName(x,en)}</strong><small>{x.availability==='required'?(en?'Required':'Υποχρεωτική'):x.availability==='recommended'?(en?'Recommended':'Προτεινόμενη'):(en?'Available':'Διαθέσιμη')} · {x.state==='overdue'?(en?'Overdue':'Εκπρόθεσμη'):x.state==='due'?(en?'Due':'Σε εκκρεμότητα'):x.latest?(en?'Last score: ':'Τελευταίο score: ')+x.latest.score:(en?'Not recorded':'Δεν έχει καταγραφεί')}</small></button>)}</div></ObserverDialog>}
  {selected&&<ObserverDialog width="large" title={scaleName(selected,en)} subtitle={selected.source_reference||selected.version} onClose={()=>setSelected(null)} footer={<DialogActions onCancel={()=>setSelected(null)} onSave={save} saveLabel={en?'Calculate & save':'Υπολογισμός & αποθήκευση'}/>}>
   <div className="record-section"><label className="field"><span>{en?'Assessment tool':'Εργαλείο αξιολόγησης'}</span><select value={selected.id} onChange={e=>open(available.find(x=>x.id===e.target.value))}>{available.map(x=><option key={x.id} value={x.id}>{scaleName(x,en)}</option>)}</select></label></div>
   {selected.scale_key==='apache-ii'&&<div className="record-section"><div className="record-section-header"><div><h4>{en?'Patient factors':'Στοιχεία ασθενούς'}</h4><p>{en?'Age is calculated from the recorded date of birth.':'Η ηλικία υπολογίζεται από την καταχωρισμένη ημερομηνία γέννησης.'}</p></div></div><div className="entry-grid"><label><span>{en?'Age (years)':'Ηλικία (έτη)'}</span><input value={age??''} readOnly/></label><label><span>{en?'Chronic health points':'Βαθμοί χρόνιας κατάστασης υγείας'}</span><input type="number" min="0" value={answers.chronicHealthPoints??0} onChange={e=>setAnswers(a=>({...a,chronicHealthPoints:e.target.value}))}/></label></div><label className="checkbox-row" style={{display:'flex',alignItems:'center',gap:8,flexDirection:'row',marginTop:14}}><input type="checkbox" checked={Boolean(answers.acuteRenalFailure)} onChange={e=>setAnswers(a=>({...a,acuteRenalFailure:e.target.checked}))}/><span>{en?'Acute renal failure':'Οξεία νεφρική ανεπάρκεια'}</span></label></div>}
   <div className="record-section"><div className="record-section-header"><div><h4>{en?'Assessment parameters':'Παράμετροι αξιολόγησης'}</h4>{selected.scale_key==='apache-ii'&&<p>{en?'Enter the worst values from the first 24 hours in ICU.':'Καταχωρίστε τις δυσμενέστερες τιμές των πρώτων 24 ωρών στη ΜΕΘ.'}</p>}</div></div><div className="entry-grid">{fields.map(([key,elLabel,enLabel])=><label key={key}><span>{en?enLabel:elLabel}</span><input type="number" step="any" value={answers[key]??''} onChange={e=>setAnswers(a=>({...a,[key]:e.target.value}))}/></label>)}</div>
   {selected.scale_key==='sofa'&&<label className="checkbox-row" style={{display:'flex',alignItems:'center',gap:8,flexDirection:'row',marginTop:14}}><input type="checkbox" checked={Boolean(answers.respiratorySupport)} onChange={e=>setAnswers(a=>({...a,respiratorySupport:e.target.checked}))}/><span>{en?'Respiratory support':'Αναπνευστική υποστήριξη'}</span></label>}</div>
   {error&&<div className="entry-detail-note"><Activity size={14}/>{error}</div>}
   <p className="entry-detail-note">{en?'The score is calculated automatically from the entered values using the governed deterministic scoring engine.':'Το score υπολογίζεται αυτόματα από τις καταχωρισμένες τιμές μέσω της εγκεκριμένης deterministic μηχανής υπολογισμού.'}</p>
  </ObserverDialog>}
 </div>}
