import { Bell, Check, CheckCheck, ChevronRight, Gift, Megaphone, PartyPopper, ShieldAlert, Users, X } from 'lucide-react'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useNotifications } from './NotificationContext'
import { useLanguage } from '../i18n/LanguageContext'
import { useFeedback } from '../feedback/FeedbackContext'
import { Button } from '../../design-system/Button'
import './notificationCenter.css'

const notificationText={el:{notifications:'Ειδοποιήσεις',unread:'μη αναγνωσμένες',todayBriefing:'Σημερινή ενημέρωση',todayWish:'Σημερινή ευχή',markAll:'Όλα αναγνωσμένα',attentionItems:'στοιχεία χρειάζονται προσοχή',allCaughtUp:'Είστε ενημερωμένοι',noUnread:'Δεν υπάρχουν μη αναγνωσμένες ειδοποιήσεις.',birthdayKicker:'ΜΙΑ ΟΜΟΡΦΗ ΣΤΙΓΜΗ ΓΙΑ ΤΗΝ ΟΜΑΔΑ ΜΑΣ',birthdayTitle:'Χρόνια πολλά!',birthdaySingle:'για τα γενέθλιά σου!',birthdayMany:'για τα γενέθλιά σας!',birthdayWish:'Με υγεία, χαρά και όμορφες στιγμές.',thanks:'Ευχαριστώ',approve:'Αποδοχή',reject:'Απόρριψη',acknowledge:'Έλαβα γνώση',acknowledged:'Η γνώση καταγράφηκε.',ackFailed:'Δεν ήταν δυνατή η καταγραφή γνώσης.',membershipAccepted:'Η συμμετοχή στην επιτροπή έγινε αποδεκτή.',membershipRejected:'Η συμμετοχή στην επιτροπή απορρίφθηκε.',membershipDecision:'Επιβεβαιώστε την επιλογή σας για τη συμμετοχή στην επιτροπή.'},en:{notifications:'Notifications',unread:'unread',todayBriefing:'Today’s briefing',todayWish:'Today’s birthday wish',markAll:'Mark all read',attentionItems:'items need attention',allCaughtUp:'You are up to date',noUnread:'There are no unread notifications.',birthdayKicker:'A SPECIAL MOMENT FOR OUR TEAM',birthdayTitle:'Happy birthday!',birthdaySingle:'— wishing you a very happy birthday!',birthdayMany:'— wishing you all a very happy birthday!',birthdayWish:'Wishing you health, happiness and many wonderful moments.',thanks:'Thank you',approve:'Accept',reject:'Reject',acknowledge:'Acknowledge',acknowledged:'Acknowledgement recorded.',ackFailed:'Acknowledgement could not be recorded.',membershipAccepted:'Committee membership accepted.',membershipRejected:'Committee membership rejected.',membershipDecision:'Confirm your decision for this committee membership.'}}

export function NotificationCenter({open,onClose,onOpenBriefing,onOpenBirthday}){
 const n=useNotifications();const navigate=useNavigate();const {language}=useLanguage();const {confirm,notify,notifyError}=useFeedback();const [busyId,setBusyId]=useState(null);const tx=notificationText[language==='en'?'en':'el']
 if(!open)return null
 const go=item=>{if(item.type==='committee_membership'||(item.type==='announcement'&&item.requiresAck&&!item.acknowledged))return;n.markRead(item.id);if(item.to){onClose();navigate(item.to)}}
 async function answer(item,status){const ok=await confirm({title:status==='approved'?tx.approve:tx.reject,message:tx.membershipDecision,confirmLabel:status==='approved'?tx.approve:tx.reject,danger:status==='rejected'});if(!ok)return;setBusyId(item.id);try{await n.answerCommitteeMembership(item,status);notify(status==='approved'?tx.membershipAccepted:tx.membershipRejected,'success',{operation:'committee_membership'})}catch(err){notifyError(err,'save',{operation:'committee_membership'})}finally{setBusyId(null)}}
 async function acknowledge(item){setBusyId(item.id);try{await n.acknowledgeAnnouncement(item.id);notify(tx.acknowledged,'success',{operation:'announcement_acknowledgement'})}catch(err){notifyError(err,tx.ackFailed,{operation:'announcement_acknowledgement'})}finally{setBusyId(null)}}
 return <div className="notification-popover notification-popover-v2"><header className="notification-header-v2"><div><Bell size={18}/><strong>{tx.notifications}</strong><span>{n.unreadCount} {tx.unread}</span></div><button type="button" className="notification-close-v2" aria-label={language==='en'?'Close':'Κλείσιμο'} onClick={onClose}><X size={18}/></button></header><div className="notification-shortcuts-v2"><button onClick={onOpenBriefing}><Bell size={15}/><span>{tx.todayBriefing}</span></button>{n.birthday.length>0&&<button onClick={onOpenBirthday}><Gift size={15}/><span>{tx.todayWish}</span></button>}{n.unreadCount>0&&<button onClick={n.markAllRead}><CheckCheck size={16}/><span>{tx.markAll}</span></button>}</div><div className="notification-list notification-list-v2">{n.unreadItems.length?n.unreadItems.map(item=>item.type==='committee_membership'?<div key={item.id} className="notification-row notification-row-v2 unread committee-membership-notification"><span className="notification-type notification-type-v2 task"><Users size={16}/></span><span className="notification-copy-v2"><strong>{item.title}</strong><small>{item.message}</small><span className="notification-inline-actions"><Button variant="secondary" loading={busyId===item.id} onClick={()=>answer(item,'approved')}><Check size={14}/>{tx.approve}</Button><Button variant="secondary" className="button-destructive" disabled={busyId===item.id} onClick={()=>answer(item,'rejected')}><X size={14}/>{tx.reject}</Button></span></span></div>:item.type==='announcement'&&item.requiresAck&&!item.acknowledged?<div key={item.id} className="notification-row notification-row-v2 unread committee-membership-notification"><span className="notification-type notification-type-v2 announcement"><Megaphone size={16}/></span><span className="notification-copy-v2"><strong>{item.title}</strong><small>{item.message}</small><span className="notification-inline-actions"><Button variant="secondary" loading={busyId===item.id} onClick={()=>acknowledge(item)}><Check size={14}/>{tx.acknowledge}</Button></span></span></div>:<button key={item.id} className="notification-row notification-row-v2 unread" onClick={()=>go(item)}><span className={`notification-type notification-type-v2 ${item.type}`}>{item.type==='announcement'?<Megaphone size={16}/>:item.type==='cluster'?<ShieldAlert size={16}/>:<Bell size={16}/>}</span><span className="notification-copy-v2"><strong>{item.title}</strong><small>{item.message||`${item.count} ${tx.attentionItems}`}</small></span><ChevronRight className="notification-chevron-v2" size={16}/></button>):<div className="notification-empty notification-empty-v2"><CheckCheck size={22}/><strong>{tx.allCaughtUp}</strong><span>{tx.noUnread}</span></div>}</div></div>
}
export function BirthdayGreeting({open,onClose}){const n=useNotifications();const {language}=useLanguage();const tx=notificationText[language==='en'?'en':'el'];if(!open||!n.birthday.length)return null;return <div className="modal-backdrop birthday-popup-backdrop"><section className="birthday-popup" role="dialog" aria-modal="true"><div className="birthday-confetti">✦ · ✧ · ✦</div><span className="birthday-icon"><PartyPopper size={28}/></span><small>{tx.birthdayKicker}</small><h2>{tx.birthdayTitle}</h2><p>{n.birthday.map(e=>`${e.firstName} ${e.lastName}`).join(', ')} {n.birthday.length===1?tx.birthdaySingle:tx.birthdayMany}</p><span className="birthday-wish">{tx.birthdayWish}</span><button className="button primary" onClick={onClose}>{tx.thanks}</button></section></div>}
