import { loadSnapshot, saveSnapshot } from '../../core/data/repository'
const seed=[
 {id:'COM-001',templateId:'enl',name:'Επιτροπή Νοσοκομειακών Λοιμώξεων',shortName:'ΕΝΛ',type:'infection_control',status:'active',chair:'Δρ. Ελένη Παπαδοπούλου',secretary:'Μαρία Κωνσταντίνου',termStart:'2026-01-01',termEnd:'2027-12-31',committeeRole:'Κεντρικό θεσμικό όργανο του νοσοκομείου για την επιτήρηση, πρόληψη και τον έλεγχο των λοιμώξεων που συνδέονται με τη φροντίδα υγείας.',legalBasis:'ΥΑ Υ1.Γ.Π.114971/2014 · ισχύουσα πράξη συγκρότησης φορέα · WHO IPC Core Components',mandate:'Επιτήρηση, πρόληψη και έλεγχος λοιμώξεων, εφαρμογή μέτρων IPC και παρακολούθηση σχετικών δεικτών.',members:['Δρ. Ελένη Παπαδοπούλου','Μαρία Κωνσταντίνου','Γ. Νικολάου','Α. Δημητρίου'],memberRefs:[
  {id:'CM-SEED-1',employeeId:'',name:'Δρ. Ελένη Παπαδοπούλου',department:'Ιατρική Υπηρεσία',profession:'Ιατρός',committeeTitle:'Πρόεδρος',responsibilities:'Συντονισμός της ΕΝΛ, έγκριση ημερήσιας διάταξης και εποπτεία εφαρμογής αποφάσεων.',voting:true,memberType:'regular',approvalRequired:false,approvalStatus:'not_required',active:true,startedAt:'2026-01-01T00:00:00Z'},
  {id:'CM-SEED-2',employeeId:'',name:'Μαρία Κωνσταντίνου',department:'Επιτήρηση Λοιμώξεων',profession:'Νοσηλεύτρια',committeeTitle:'ΝΕΛ / Γραμματέας',responsibilities:'Επιτήρηση HAI, συλλογή και ανατροφοδότηση δεικτών, πρακτικά και παρακολούθηση ενεργειών.',voting:true,memberType:'regular',approvalRequired:false,approvalStatus:'not_required',active:true,startedAt:'2026-01-01T00:00:00Z'},
  {id:'CM-SEED-3',employeeId:'',name:'Γ. Νικολάου',department:'Μικροβιολογικό',profession:'Μικροβιολόγος',committeeTitle:'Μικροβιολογία / Εργαστήριο',responsibilities:'Παρουσίαση μικροβιολογικών δεδομένων και μικροβιακής αντοχής.',voting:true,memberType:'regular',approvalRequired:false,approvalStatus:'not_required',active:true,startedAt:'2026-01-01T00:00:00Z'},
  {id:'CM-SEED-4',employeeId:'',name:'Α. Δημητρίου',department:'Ποιότητα',profession:'Στέλεχος Ποιότητας',committeeTitle:'Ποιότητα & Ασφάλεια',responsibilities:'Παρακολούθηση διορθωτικών ενεργειών και τεκμηρίωση βελτίωσης.',voting:true,memberType:'regular',approvalRequired:false,approvalStatus:'not_required',active:true,startedAt:'2026-01-01T00:00:00Z'}
 ],meetings:[
  {id:'MTG-2026-08',date:'2026-08-18',title:'Τακτική συνεδρίαση Αυγούστου',status:'finalized',attendance:4,quorum:true,minutesNo:'ΠΡ-08/2026',agenda:['Δείκτες λοιμώξεων','Κατανάλωση αντιμικροβιακών','Εκκρεμείς διορθωτικές ενέργειες'],notes:'Εγκρίθηκαν τα πρακτικά και οι σχετικές ενέργειες.',finalizedAt:'2026-08-19T09:20:00Z'},
  {id:'MTG-2026-09',date:'2026-09-15',title:'Τακτική συνεδρίαση Σεπτεμβρίου',status:'planned',attendance:0,quorum:null,minutesNo:'',agenda:['Ανασκόπηση CLABSI/CAUTI','Εκπαίδευση προσωπικού'],notes:''}
 ],decisions:[
  {id:'DEC-024',meetingId:'MTG-2026-08',title:'Ενίσχυση συμμόρφωσης υγιεινής χεριών στη ΜΕΘ',owner:'Προϊσταμένη ΜΕΘ',dueDate:'2026-09-10',priority:'high',status:'in_progress',action:'Επαναληπτική εκπαίδευση και στοχευμένες παρατηρήσεις WHO 5 Moments.'},
  {id:'DEC-025',meetingId:'MTG-2026-08',title:'Ανασκόπηση bundle κεντρικών γραμμών',owner:'Υπεύθυνος Λοιμώξεων',dueDate:'2026-09-05',priority:'medium',status:'open',action:'Έλεγχος συμμόρφωσης και παρουσίαση αποτελεσμάτων στην επόμενη συνεδρίαση.'}
 ],annualPlan:[
  {id:'OBJ-001',title:'Βελτίωση συμμόρφωσης υγιεινής χεριών',indicator:'Συμμόρφωση WHO 5 Moments',baseline:'78%',target:'≥ 90%',owner:'Ομάδα IPC / Κλινικοί Σύνδεσμοι',dueDate:'2026-12-31',status:'in_progress'},
  {id:'OBJ-002',title:'Μείωση CLABSI στη ΜΕΘ',indicator:'CLABSI / 1.000 device-days',baseline:'2,4',target:'< 1,5',owner:'ΕΝΛ / ΜΕΘ',dueDate:'2026-12-31',status:'in_progress'},
  {id:'OBJ-003',title:'Ετήσια εκπαίδευση IPC προσωπικού',indicator:'Κάλυψη ενεργού προσωπικού',baseline:'62%',target:'≥ 95%',owner:'Ομάδα Εκπαίδευσης IPC',dueDate:'2026-11-30',status:'open'}
 ],history:[{at:'2026-08-19T09:20:00Z',actor:'Demo seed',action:'Πρακτικά οριστικοποιήθηκαν',reason:'Εγκεκριμένα από τη συνεδρίαση'}]},
 {id:'COM-002',templateId:'oekocha',name:'Επιτροπή Αντιμικροβιακής Επιτήρησης',shortName:'ΕΑΕ',type:'antimicrobial',status:'active',chair:'Δρ. Ν. Γεωργίου',secretary:'Ι. Σταύρου',termStart:'2026-01-01',termEnd:'2027-12-31',committeeRole:'Παρακολουθεί την ορθολογική χρήση αντιμικροβιακών, την κατανάλωση (DDD) και τις τάσεις αντοχής, σε συνεργασία με την ΕΝΛ, το Μικροβιολογικό και το Φαρμακείο.',legalBasis:'ΕΟΔΥ Εθνικό Πρόγραμμα Antimicrobial Stewardship · WHO AWaRe Framework',mandate:'Παρακολούθηση ορθολογικής χρήσης αντιμικροβιακών, κατανάλωσης και αντοχής.',members:['Δρ. Ν. Γεωργίου','Ι. Σταύρου','Κλινικός Φαρμακοποιός','Γ. Νικολάου'],memberRefs:[
  {id:'CM-SEED-5',employeeId:'',name:'Δρ. Ν. Γεωργίου',department:'Παθολογική Κλινική',profession:'Ιατρός Λοιμωξιολόγος',committeeTitle:'Πρόεδρος',responsibilities:'Συντονισμός ΕΑΕ, κλινική έγκριση περιοριστικών πρωτοκόλλων συνταγογράφησης.',voting:true,memberType:'regular',approvalRequired:false,approvalStatus:'not_required',active:true,startedAt:'2026-01-01T00:00:00Z'},
  {id:'CM-SEED-6',employeeId:'',name:'Ι. Σταύρου',department:'Φαρμακείο',profession:'Κλινικός Φαρμακοποιός',committeeTitle:'Γραμματέας',responsibilities:'Ανάλυση κατανάλωσης (DDD/100 ημέρες νοσηλείας), κατηγοριοποίηση AWaRe, πρακτικά.',voting:true,memberType:'regular',approvalRequired:false,approvalStatus:'not_required',active:true,startedAt:'2026-01-01T00:00:00Z'},
  {id:'CM-SEED-7',employeeId:'',name:'Γ. Νικολάου',department:'Μικροβιολογικό',profession:'Μικροβιολόγος',committeeTitle:'Μικροβιολογία / Αντοχή',responsibilities:'Παρουσίαση τάσεων MDR/XDR και δεδομένων ευαισθησίας.',voting:true,memberType:'regular',approvalRequired:false,approvalStatus:'not_required',active:true,startedAt:'2026-01-01T00:00:00Z'}
 ],meetings:[
  {id:'MTG-2026-07-AMS',date:'2026-07-21',title:'Τακτική συνεδρίαση Ιουλίου',status:'finalized',attendance:3,quorum:true,minutesNo:'ΠΡ-ΕΑΕ-07/2026',agenda:['Κατανάλωση αντιμικροβιακών (DDD/100 ημέρες νοσηλείας)','Κατηγοριοποίηση WHO AWaRe','Περιοριστική συνταγογράφηση καρβαπενεμών'],notes:'Εγκρίθηκε περιοριστικό πρωτόκολλο για καρβαπενέμες με υποχρεωτική γνωμάτευση λοιμωξιολόγου.',finalizedAt:'2026-07-22T10:00:00Z'},
  {id:'MTG-2026-10-AMS',date:'2026-10-06',title:'Τακτική συνεδρίαση Οκτωβρίου',status:'planned',attendance:0,quorum:null,minutesNo:'',agenda:['Ανασκόπηση συμμόρφωσης περιοριστικού πρωτοκόλλου','Τάσεις αντοχής 3ου τριμήνου'],notes:''}
 ],decisions:[
  {id:'DEC-AMS-001',meetingId:'MTG-2026-07-AMS',title:'Περιοριστική συνταγογράφηση καρβαπενεμών',owner:'Δρ. Ν. Γεωργίου',dueDate:'2026-08-15',priority:'high',status:'in_progress',action:'Υποχρεωτική γνωμάτευση λοιμωξιολόγου πριν την έναρξη καρβαπενέμης πλην επειγόντων.'},
  {id:'DEC-AMS-002',meetingId:'MTG-2026-07-AMS',title:'Έλεγχος δοσολογίας βανκομυκίνης',owner:'Ι. Σταύρου',dueDate:'2026-09-01',priority:'medium',status:'open',action:'Οπτικός έλεγχος επιπέδων και προσαρμογή δοσολογικού σχήματος σε νεφρική δυσλειτουργία.'}
 ],annualPlan:[
  {id:'OBJ-AMS-001',title:'Αύξηση ποσοστού αντιμικροβιακών κατηγορίας Access (WHO AWaRe)',indicator:'% κατανάλωσης Access',baseline:'52%',target:'≥ 60%',owner:'Ομάδα Antimicrobial Stewardship',dueDate:'2026-12-31',status:'in_progress'},
  {id:'OBJ-AMS-002',title:'Μείωση κατανάλωσης καρβαπενεμών',indicator:'DDD καρβαπενεμών / 100 ημέρες νοσηλείας',baseline:'3,1',target:'< 2,0',owner:'ΕΑΕ / Φαρμακείο',dueDate:'2026-12-31',status:'in_progress'}
 ],history:[{at:'2026-07-22T10:00:00Z',actor:'Demo seed',action:'Πρακτικά οριστικοποιήθηκαν',reason:'Εγκεκριμένα από τη συνεδρίαση'}]}
]
export function inferTemplate(r){if(r.templateId)return r.templateId;const n=`${r.shortName||''} ${r.name||''}`.toLowerCase();if(n.includes('ενλ')||n.includes('νοσοκομειακών λοιμ'))return'enl';if(n.includes('αντιμικροβ')||n.includes('αντιβιο'))return'oekocha';return'custom'}
function normalizeMeeting(meeting){
 const topics=Array.isArray(meeting.topics)&&meeting.topics.length?meeting.topics:(meeting.agenda||[]).map((subject,i)=>({id:`LEG-${meeting.id}-${i}`,subject,decision:i===0?(meeting.notes||''):'',followUp:false,action:'',owner:'',dueDate:'',priority:'medium'}))
 return {...meeting,topics,attendanceRecords:Array.isArray(meeting.attendanceRecords)?meeting.attendanceRecords:[],generalNotes:meeting.generalNotes??'',approvalState:meeting.approvalState??(meeting.status==='finalized'?'completed':'not_started')}
}
function normalizeRecord(r){
 const memberRefs=Array.isArray(r.memberRefs)&&r.memberRefs.length?r.memberRefs:(r.members||[]).map((name,i)=>({id:`LEGACY-${r.id}-${i}`,employeeId:'',name,department:'',profession:'',committeeTitle:name===r.chair?'Πρόεδρος':name===r.secretary?'Γραμματέας':'Μέλος',responsibilities:'',voting:true,memberType:'regular',approvalRequired:false,approvalStatus:'not_required',active:true,startedAt:r.termStart?`${r.termStart}T00:00:00Z`:null}))
 return {...r,templateId:inferTemplate(r),memberRefs,meetings:(Array.isArray(r.meetings)?r.meetings:[]).map(normalizeMeeting),decisions:Array.isArray(r.decisions)?r.decisions:[],annualPlan:Array.isArray(r.annualPlan)?r.annualPlan:[],history:Array.isArray(r.history)?r.history:[]}
}
export function loadCommittees(){const v=loadSnapshot('committees',structuredClone(seed));return (Array.isArray(v)?v:structuredClone(seed)).map(normalizeRecord)}
export function saveCommittees(rows){return saveSnapshot('committees',rows)}
export function nextCommitteeId(rows){return `COM-${String(rows.length+1).padStart(3,'0')}`}
