import { useMemo,useState } from 'react'
import { BookOpenCheck,Plus,Trash2 } from 'lucide-react'
import { useLocation,useNavigate } from 'react-router-dom'
import { Page } from '../../design-system/Page'
import { EntityRecordShell } from '../../design-system/EntityRecordShell'
import { Button } from '../../design-system/Button'
import { SaveButton } from '../../design-system/SaveButton'
import { ManualDateField } from '../../design-system/ManualDateField'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { useAuditActor } from '../../core/audit/useAuditActor'
import { useContextualNavigation } from '../../core/navigation/useContextualNavigation'
import { useEmployeesData } from '../employees/useEmployeesData'
import { useTenant } from '../../core/tenant/TenantContext'
import { loadCommittees,nextCommitteeId,saveCommittees } from './committeeData'
import { createCommitteeAsync,getNextCommitteeCodeAsync } from './committeeService'
import { IPC_COMMITTEE_CATALOG,ipcCommitteeById } from './ipcCommitteeCatalog'
import { requestCommitteeApproval } from './committeeApprovals'
import { useLanguage } from '../../core/i18n/LanguageContext'

const frequencies=[['monthly','Μηνιαία','Monthly'],['bimonthly','Ανά δίμηνο','Every two months'],['quarterly','Τριμηνιαία','Quarterly'],['semiannual','Εξαμηνιαία','Semiannual'],['annual','Ετήσια','Annual'],['as_needed','Όποτε απαιτείται','As needed']]

export function CommitteeCreatePage(){
 const navigate=useNavigate(),location=useLocation(),actor=useAuditActor(),{notify,confirm}=useFeedback(),{goBack}=useContextualNavigation('/committees'),{language}=useLanguage(),en=language==='en',{tenant}=useTenant(),{data:staffRows}=useEmployeesData()
 const [saving,setSaving]=useState(false),first=IPC_COMMITTEE_CATALOG.find(x=>x.id==='custom')||IPC_COMMITTEE_CATALOG[0]
 const [draft,setDraft]=useState({templateId:first.id,name:'',shortName:'',committeeRole:'',mandate:'',legalBasis:'',decisionNumber:'',termStart:'',termEnd:'',meetingFrequency:'quarterly',quorumRule:'simple_majority',notes:'',members:[]})
 const staff=useMemo(()=>staffRows.filter(x=>x.employmentStatus==='active').map(x=>({id:x.id,dbId:x.dbId,name:`${x.firstName} ${x.lastName}`,department:x.department,profession:x.profession,email:x.email||''})),[staffRows])
 const set=(k,v)=>setDraft(x=>({...x,[k]:v})),template=ipcCommitteeById(draft.templateId),datesValid=!draft.termStart||!draft.termEnd||new Date(draft.termEnd)>=new Date(draft.termStart),ids=draft.members.map(x=>x.employeeId).filter(Boolean),membersValid=draft.members.length>0&&draft.members.every(x=>x.employeeId&&x.title.trim()&&x.responsibilities.trim())&&new Set(ids).size===ids.length,valid=draft.name.trim()&&draft.committeeRole.trim()&&draft.mandate.trim()&&draft.termStart&&draft.termEnd&&datesValid&&membersValid
 function chooseTemplate(id){const t=ipcCommitteeById(id);setDraft(x=>({...x,templateId:id,name:t.id==='custom'?x.name:t.name,shortName:t.id==='custom'?x.shortName:t.code,committeeRole:t.id==='custom'?'':t.role,mandate:t.id==='custom'?'':t.duties.join('\n'),legalBasis:t.id==='custom'?'':t.source}))}
 function addMember(){setDraft(x=>({...x,members:[...x.members,{id:`m-${Date.now()}`,employeeId:'',title:'',responsibilities:'',voting:true,approvalRequired:false,memberType:'regular'}]}))}
 function patchMember(id,k,v){setDraft(x=>({...x,members:x.members.map(m=>m.id===id?{...m,[k]:v}:m)}))}
 async function removeMember(id){if(await confirm({title:en?'Remove member':'Αφαίρεση μέλους',message:en?'Remove this member?':'Να αφαιρεθεί το μέλος;',confirmLabel:en?'Remove':'Αφαίρεση',danger:true}))setDraft(x=>({...x,members:x.members.filter(m=>m.id!==id)}))}
 async function save(){if(!valid||saving)return;setSaving(true);try{const rows=loadCommittees(),id=(await getNextCommitteeCodeAsync(tenant?.id??null))||nextCommitteeId(rows),now=new Date().toISOString(),memberRefs=draft.members.map((m,i)=>{const p=staff.find(x=>x.id===m.employeeId);return {id:`CM-${Date.now()}-${i}`,employeeId:m.employeeId,employeeDbId:p?.dbId||null,name:p?.name||'',email:p?.email||'',department:p?.department||'',profession:p?.profession||'',committeeTitle:m.title.trim(),responsibilities:m.responsibilities.trim(),voting:m.voting,memberType:m.memberType||'regular',approvalRequired:m.approvalRequired,approvalStatus:m.approvalRequired?'pending':'not_required',active:true,startedAt:now,endedAt:null}}),chair=memberRefs.find(x=>/πρόεδ|συντον/i.test(x.committeeTitle)),secretary=memberRefs.find(x=>/γραμματ/i.test(x.committeeTitle)),localRecord={id,name:draft.name.trim(),shortName:draft.shortName.trim(),status:'active',templateId:draft.templateId,structureKind:template.kind,isCoreCommittee:template.core,committeeRole:draft.committeeRole.trim(),mandate:draft.mandate.trim(),legalBasis:draft.legalBasis.trim(),officialRelation:template.relation,roleGuidance:template.roleGuidance||[],requiredFunctions:template.requiredFunctions,decisionNumber:draft.decisionNumber.trim(),termStart:draft.termStart,termEnd:draft.termEnd,meetingFrequency:draft.meetingFrequency,quorumRule:draft.quorumRule,notes:draft.notes.trim(),chair:chair?.name||'',secretary:secretary?.name||'',memberRefs,members:memberRefs.map(x=>x.name),meetings:[],decisions:[],annualPlan:[],createdAt:now,createdBy:actor.name,createdById:actor.id,updatedAt:now,updatedBy:actor.name,updatedById:actor.id,history:[{at:now,actor:actor.name,actorId:actor.id,action:'Δημιουργία',reason:draft.name}]};let record=localRecord;const cloud=await createCommitteeAsync(tenant?.id??null,{...localRecord,memberRefs});if(cloud)record=cloud;else saveCommittees([localRecord,...rows]);memberRefs.filter(x=>x.approvalRequired).forEach(m=>requestCommitteeApproval({committeeId:record.id,committeeName:record.name,employeeId:m.employeeId,memberName:m.name,committeeTitle:m.committeeTitle,responsibilities:m.responsibilities,requestedBy:actor.name,requestedById:actor.id}));notify(en?'Committee created.':'Η επιτροπή δημιουργήθηκε.','success');navigate(`/committees/${record.id}`,{replace:true,state:{limoxisFrom:location.state?.limoxisFrom}})}catch(err){notify(err.message==='DUPLICATE_COMMITTEE_CODE'?(en?'This committee code is already in use.':'Αυτός ο κωδικός επιτροπής χρησιμοποιείται ήδη.'):(en?'Could not save the committee.':'Δεν ήταν δυνατή η αποθήκευση της επιτροπής.'),'danger')}finally{setSaving(false)}}
 return <Page fill><EntityRecordShell className="committee-create-shell workspace-fill" avatar={<BookOpenCheck size={19}/>} eyebrow={en?'Committees':'Επιτροπές'} title={en?'New committee / group':'Νέα επιτροπή / ομάδα'} subtitle={en?'Create committee record':'Δημιουργία καρτέλας επιτροπής'} tabs={[]} activeTab="" onTabChange={()=>{}} onBack={goBack}>
  <div className="record-section committee-create-form"><div className="entry-grid">
   <label><span>{en?'Committee / group type *':'Τύπος επιτροπής / ομάδας *'}</span><select value={draft.templateId} onChange={e=>chooseTemplate(e.target.value)}>{IPC_COMMITTEE_CATALOG.map(x=><option key={x.id} value={x.id}>{x.code?`${x.code} — `:''}{x.name}</option>)}</select></label><label><span>{en?'Short name':'Σύντομη ονομασία'}</span><input value={draft.shortName} onChange={e=>set('shortName',e.target.value)}/></label><label className="entry-span-2"><span>{en?'Name *':'Ονομασία *'}</span><input autoFocus value={draft.name} onChange={e=>set('name',e.target.value)}/></label><label><span>{en?'Decision no.':'Αρ. απόφασης'}</span><input value={draft.decisionNumber} onChange={e=>set('decisionNumber',e.target.value)}/></label><label><span>{en?'Institutional basis':'Θεσμική βάση'}</span><input value={draft.legalBasis} onChange={e=>set('legalBasis',e.target.value)}/></label><label className="entry-span-2"><span>{en?'Committee role *':'Ρόλος επιτροπής *'}</span><textarea rows="2" value={draft.committeeRole} onChange={e=>set('committeeRole',e.target.value)}/></label><label className="entry-span-2"><span>{en?'Responsibilities *':'Αρμοδιότητες *'}</span><textarea rows="3" value={draft.mandate} onChange={e=>set('mandate',e.target.value)}/></label><ManualDateField label={en?'Term start *':'Έναρξη θητείας *'} value={draft.termStart} onChange={v=>set('termStart',v)}/><ManualDateField label={en?'Term end *':'Λήξη θητείας *'} value={draft.termEnd} onChange={v=>set('termEnd',v)}/><label><span>{en?'Meeting frequency':'Συχνότητα συνεδριάσεων'}</span><select value={draft.meetingFrequency} onChange={e=>set('meetingFrequency',e.target.value)}>{frequencies.map(([v,l,lEn])=><option key={v} value={v}>{en?lEn:l}</option>)}</select></label><label><span>{en?'Quorum':'Απαρτία'}</span><select value={draft.quorumRule} onChange={e=>set('quorumRule',e.target.value)}><option value="simple_majority">{en?'Simple majority':'Απλή πλειοψηφία ενεργών μελών'}</option><option value="two_thirds">2/3</option><option value="custom">{en?'According to regulations':'Σύμφωνα με τον κανονισμό'}</option></select></label><label className="entry-span-2"><span>{en?'Notes':'Σημειώσεις'}</span><textarea rows="2" value={draft.notes} onChange={e=>set('notes',e.target.value)}/></label>
  </div><div className="record-subsection-header"><div><strong>{en?'Committee members':'Μέλη επιτροπής'}</strong><small>{en?'At least one complete member is required.':'Απαιτείται τουλάχιστον ένα πλήρες μέλος.'}</small></div><Button variant="secondary" onClick={addMember}><Plus size={15}/>{en?'Add member':'Προσθήκη μέλους'}</Button></div><div className="committee-member-list">{draft.members.map((m,i)=><div className="committee-member" key={m.id}><div className="committee-member-head"><strong>{staff.find(x=>x.id===m.employeeId)?.name||(en?`Member ${i+1}`:`Μέλος ${i+1}`)}</strong><button type="button" className="entity-record-icon-button danger" onClick={()=>removeMember(m.id)}><Trash2 size={15}/></button></div><div className="entry-grid compact"><label><span>{en?'Employee *':'Εργαζόμενος *'}</span><select value={m.employeeId} onChange={e=>patchMember(m.id,'employeeId',e.target.value)}><option value="">{en?'Select':'Επιλογή'}</option>{staff.map(x=><option key={x.id} value={x.id}>{x.name} · {x.department}</option>)}</select></label><label><span>{en?'Role *':'Ιδιότητα *'}</span><input value={m.title} onChange={e=>patchMember(m.id,'title',e.target.value)}/></label><label><span>{en?'Responsibility *':'Αρμοδιότητα *'}</span><input value={m.responsibilities} onChange={e=>patchMember(m.id,'responsibilities',e.target.value)}/></label><label><span>{en?'Membership':'Συμμετοχή'}</span><select value={m.memberType||'regular'} onChange={e=>patchMember(m.id,'memberType',e.target.value)}><option value="regular">{en?'Regular':'Τακτικό'}</option><option value="alternate">{en?'Alternate':'Αναπληρωματικό'}</option></select></label></div></div>)}</div>{!draft.members.length&&<div className="inline-empty">{en?'No members added.':'Δεν έχουν προστεθεί μέλη.'}</div>}{!datesValid&&<div className="source-truth-note">{en?'Term end must be after term start.':'Η λήξη θητείας πρέπει να είναι μετά την έναρξη.'}</div>}<div className="inline-edit-footer"><Button variant="secondary" onClick={goBack}>{en?'Cancel':'Ακύρωση'}</Button><SaveButton loading={saving} disabled={!valid||saving} onClick={save}>{en?'Save':'Αποθήκευση'}</SaveButton></div></div>
 </EntityRecordShell></Page>
}
