import { useEffect,useState } from 'react'
import { Navigate,useLocation,useParams } from 'react-router-dom'
import { AlertTriangle,CheckSquare2,ClipboardCheck,ShieldCheck } from 'lucide-react'
import { Page } from '../../design-system/Page'
import { Button } from '../../design-system/Button'
import { SaveButton } from '../../design-system/SaveButton'
import { EntityRecordShell } from '../../design-system/EntityRecordShell'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { useAuth } from '../../core/auth/AuthContext'
import { useTenant } from '../../core/tenant/TenantContext'
import { can,CAPABILITIES,ROLES } from '../../core/permissions/roles'
import { ManualDateField } from '../../design-system/ManualDateField'
import { useContextualNavigation } from '../../core/navigation/useContextualNavigation'
import { createQualityRecord } from './qualityService'
import { loadDepartments } from '../management/departmentsService'
import { demoLibrarySeed } from '../management/managementData'

const config={incidents:{icon:AlertTriangle,title:'newIncident'},findings:{icon:ShieldCheck,title:'newFinding'},capas:{icon:CheckSquare2,title:'newCapa'},audits:{icon:ClipboardCheck,title:'newAudit'}}

export function QualityCreatePage(){
  const {recordType}=useParams();useLocation();const {goBack}=useContextualNavigation('/quality');const {t,language}=useLanguage();const {notify}=useFeedback();const {user}=useAuth();const {role,membership,tenant,actualRole,isRolePreview,isDemo}=useTenant();const c=config[recordType]||config.incidents;const Icon=c.icon
  const [saving,setSaving]=useState(false);const [departments,setDepartments]=useState([])
  const [draft,setDraft]=useState({title:'',titleEn:'',departmentId:'',status:recordType==='incidents'?'reported':recordType==='findings'?'open':recordType==='capas'?'open':'planned',severity:'medium',category:'clinical',eventTime:'',owner:'',immediateActions:'',immediateActionsEn:'',impact:'none',description:'',descriptionEn:'',date:new Date().toISOString().slice(0,10),source:'manual',sourceId:'',actionType:'corrective',priority:'medium',dueDate:'',effectivenessDue:'',effectivenessStatus:'pending',auditType:'internal',plannedDate:'',scope:'',scopeEn:''})
  useEffect(()=>{let active=true;const request=isDemo?Promise.resolve(demoLibrarySeed.departments.map(([name,nameEn])=>({id:name,name,nameEn,is_active:true}))):loadDepartments(tenant?.id);request.then(rows=>{if(active)setDepartments(rows.filter(x=>x.is_active!==false))}).catch(()=>{if(active)setDepartments([])});return()=>{active=false}},[tenant?.id,isDemo])
  const addOns=membership?.capabilities??[],custom=membership?.customCapabilities??[];const ownerFullAccess=!isRolePreview&&actualRole===ROLES.PLATFORM_OWNER;const canManage=ownerFullAccess||can(role,CAPABILITIES.MANAGE_QUALITY,addOns,custom);const canReportIncident=ownerFullAccess||can(role,CAPABILITIES.REPORT_INCIDENT,addOns,custom);const canCreate=canManage||(recordType==='incidents'&&canReportIncident)
  const set=(k,v)=>setDraft(x=>({...x,[k]:v}));const titleValue=language==='el'?draft.title:draft.titleEn;const descriptionValue=language==='el'?(recordType==='audits'?draft.scope:draft.description):(recordType==='audits'?draft.scopeEn:draft.descriptionEn)
  async function save(){if(!canCreate||!titleValue.trim()||saving)return;setSaving(true);try{await createQualityRecord(recordType,tenant?.id,{...draft,title:draft.title||draft.titleEn,titleEn:draft.titleEn||draft.title},user?.id);notify(t('recordCreated'),'success');goBack()}catch(error){console.error(error);notify(language==='en'?'The quality record could not be saved.':'Δεν ήταν δυνατή η αποθήκευση της εγγραφής ποιότητας.','error')}finally{setSaving(false)}}
  if(!canCreate)return <Navigate to="/quality" replace/>
  return <Page fill><EntityRecordShell className="quality-record-shell workspace-fill" avatar={<Icon size={19}/>} eyebrow={t('quality')} title={t(c.title)} subtitle={t('qualityRecords.newQualityRecord')} tabs={[]} activeTab="" onTabChange={()=>{}} onBack={goBack}>
    <div className="record-section quality-create-form"><div className="entry-grid">
      <label className="entry-span-2"><span>{t('title')}</span><input value={titleValue} onChange={e=>set(language==='el'?'title':'titleEn',e.target.value)}/></label>
      <label><span>{t('department')}</span><select value={draft.departmentId} onChange={e=>set('departmentId',e.target.value)}><option value="">{language==='en'?'Select department…':'Επιλέξτε τμήμα…'}</option>{departments.map(dep=><option key={dep.id} value={dep.id}>{dep.name}</option>)}</select></label>
      {recordType==='incidents'&&<><ManualDateField label={t('date')} value={draft.date} onChange={v=>set('date',v)}/><label><span>{language==='en'?'Time':'Ώρα'}</span><input type="time" value={draft.eventTime} onChange={e=>set('eventTime',e.target.value)}/></label><label><span>{language==='en'?'Category':'Κατηγορία συμβάντος'}</span><select value={draft.category} onChange={e=>set('category',e.target.value)}><option value="clinical">{language==='en'?'Clinical / patient safety':'Κλινικό / ασφάλεια ασθενούς'}</option><option value="medication">{language==='en'?'Medication':'Φάρμακο'}</option><option value="equipment">{language==='en'?'Equipment / device':'Εξοπλισμός / ιατροτεχνολογικό'}</option><option value="process">{language==='en'?'Process / operational':'Διαδικασία / λειτουργικό'}</option><option value="staff">{language==='en'?'Staff / occupational safety':'Προσωπικό / επαγγελματική ασφάλεια'}</option><option value="facility">{language==='en'?'Facility / infrastructure':'Εγκαταστάσεις / υποδομές'}</option><option value="security">{language==='en'?'Security':'Ασφάλεια'}</option><option value="other">{language==='en'?'Other':'Άλλο'}</option></select></label><label><span>{t('severity')}</span><select value={draft.severity} onChange={e=>set('severity',e.target.value)}>{['low','medium','high','critical'].map(x=><option key={x} value={x}>{t(x)}</option>)}</select></label><label><span>{t('owner')}</span><input value={draft.owner} onChange={e=>set('owner',e.target.value)} placeholder={language==='en'?'Person responsible for follow-up':'Υπεύθυνος παρακολούθησης'}/></label></>}
      {recordType==='findings'&&<><label><span>{t('severity')}</span><select value={draft.severity} onChange={e=>set('severity',e.target.value)}>{['low','medium','high','critical'].map(x=><option key={x} value={x}>{t(x)}</option>)}</select></label><label><span>{t('source')}</span><select value={draft.source} onChange={e=>set('source',e.target.value)}><option value="manual">{t('qualityRecords.manualSource')}</option><option value="audit">{t('audit')}</option><option value="incident">{t('incident')}</option><option value="control">{language==='en'?'Control':'Έλεγχος'}</option></select></label><label><span>{t('qualityRecords.sourceId')}</span><input value={draft.sourceId} onChange={e=>set('sourceId',e.target.value)}/></label></>}
      {recordType==='capas'&&<><label><span>{t('actionType')}</span><select value={draft.actionType} onChange={e=>set('actionType',e.target.value)}><option value="corrective">{t('corrective')}</option><option value="preventive">{t('preventive')}</option></select></label><label><span>{t('priority')}</span><select value={draft.priority} onChange={e=>set('priority',e.target.value)}>{['low','medium','high','critical'].map(x=><option key={x} value={x}>{t(x)}</option>)}</select></label><ManualDateField label={t('dueDate')} value={draft.dueDate} onChange={v=>set('dueDate',v)}/><label><span>{t('qualityRecords.sourceId')}</span><input value={draft.sourceId} onChange={e=>set('sourceId',e.target.value)}/></label></>}
      {recordType==='audits'&&<><label><span>{t('auditType')}</span><select value={draft.auditType} onChange={e=>set('auditType',e.target.value)}><option value="internal">{t('internal')}</option><option value="external">{t('external')}</option></select></label><ManualDateField label={t('plannedDate')} value={draft.plannedDate} onChange={v=>set('plannedDate',v)}/></>}
      <label className="entry-span-2"><span>{t(recordType==='audits'?'qualityRecords.auditScope':'description')}</span><textarea rows={5} value={descriptionValue} onChange={e=>set(language==='el'?(recordType==='audits'?'scope':'description'):(recordType==='audits'?'scopeEn':'descriptionEn'),e.target.value)}/></label>{recordType==='incidents'&&<><label className="entry-span-2"><span>{language==='en'?'Immediate actions taken':'Άμεσες ενέργειες που πραγματοποιήθηκαν'}</span><textarea rows={3} value={language==='el'?draft.immediateActions:draft.immediateActionsEn} onChange={e=>set(language==='el'?'immediateActions':'immediateActionsEn',e.target.value)} placeholder={language==='en'?'Containment, first response or other immediate measures…':'Περιορισμός, πρώτη αντιμετώπιση ή άλλα άμεσα μέτρα…'}/></label><label><span>{language==='en'?'Actual / potential impact':'Πραγματική / δυνητική επίπτωση'}</span><select value={draft.impact} onChange={e=>set('impact',e.target.value)}><option value="none">{language==='en'?'No harm / impact':'Χωρίς βλάβη / επίπτωση'}</option><option value="minor">{language==='en'?'Minor':'Μικρή'}</option><option value="moderate">{language==='en'?'Moderate':'Μέτρια'}</option><option value="major">{language==='en'?'Major':'Σημαντική'}</option><option value="severe">{language==='en'?'Severe':'Σοβαρή'}</option></select></label></>}
    </div><div className="inline-edit-footer"><Button variant="secondary" onClick={goBack}>{t('cancel')}</Button><SaveButton loading={saving} disabled={!titleValue.trim()||saving} onClick={save}>{t('save')}</SaveButton></div></div>
  </EntityRecordShell></Page>
}
