export const qualityIncidents=[
  {id:'INC-260827-004',title:'Καθυστέρηση εφαρμογής isolation precautions',titleEn:'Delay in applying isolation precautions',department:'ΜΕΘ',departmentEn:'ICU',date:'2026-08-27',severity:'high',status:'underReview',reportedBy:'Ν. Παπαδόπουλος',owner:'Υπεύθυνος Ποιότητας',description:'Καταγράφηκε καθυστέρηση στην εφαρμογή των απαιτούμενων μέτρων μετά από κρίσιμο εργαστηριακό αποτέλεσμα.',descriptionEn:'A delay was recorded in applying required precautions after a critical laboratory result.',linkedPatient:'PT-260184',linkedSurveillance:'SUR-260041',attachments:[],history:[{at:'2026-08-27T06:20:00+03:00',action:'incidentReported',actor:'Ν. Παπαδόπουλος'}]},
  {id:'INC-260826-009',title:'Αστοχία σήμανσης περιέκτη αποβλήτων',titleEn:'Waste container labelling failure',department:'Χειρουργική',departmentEn:'Surgery',date:'2026-08-26',severity:'medium',status:'closed',reportedBy:'Μ. Ιωάννου',owner:'Υπεύθυνος Ποιότητας',description:'Εντοπίστηκε λανθασμένη σήμανση σε περιέκτη αποβλήτων.',descriptionEn:'Incorrect labelling was identified on a waste container.',attachments:[],history:[{at:'2026-08-26T15:40:00+03:00',action:'incidentClosed',actor:'Υπεύθυνος Ποιότητας'}]},
]
export const qualityFindings=[
  {id:'FND-2608-012',title:'Μη πλήρης τεκμηρίωση read-back',titleEn:'Incomplete read-back documentation',source:'audit',sourceId:'AUD-2608-003',department:'ΜΕΘ',departmentEn:'ICU',date:'2026-08-25',severity:'medium',status:'open',owner:'Υπεύθυνος ΜΕΘ',description:'Σε δείγμα κρίσιμης επικοινωνίας δεν τεκμηριώθηκε πλήρως η επιβεβαίωση read-back.',descriptionEn:'Read-back confirmation was not fully documented in a sampled critical communication.',attachments:[],history:[{at:'2026-08-25T12:10:00+03:00',action:'findingCreated',actor:'Υπεύθυνος Ποιότητας'}]},
]
export const qualityCapas=[
  {id:'CAPA-2608-006',title:'Επανεκπαίδευση στη διαχείριση κρίσιμων αποτελεσμάτων',titleEn:'Retraining on critical result management',sourceType:'finding',sourceId:'FND-2608-012',department:'ΜΕΘ',departmentEn:'ICU',owner:'Προϊστάμενος Εργαστηρίου',dueDate:'2026-09-10',status:'inProgress',priority:'high',actionType:'corrective',description:'Στοχευμένη επανεκπαίδευση και έλεγχος τεκμηρίωσης read-back.',descriptionEn:'Targeted retraining and verification of read-back documentation.',effectivenessDue:'2026-10-10',effectivenessStatus:'pending',attachments:[],history:[{at:'2026-08-26T09:30:00+03:00',action:'capaAssigned',actor:'Υπεύθυνος Ποιότητας'}]},
]
export const qualityAudits=[
  {id:'AUD-2608-003',title:'Audit κρίσιμων εργαστηριακών επικοινωνιών',titleEn:'Critical laboratory communication audit',department:'ΜΕΘ',departmentEn:'ICU',auditType:'internal',plannedDate:'2026-08-25',completedDate:'2026-08-25',status:'completed',leadAuditor:'Υπεύθυνος Ποιότητας',scope:'Δειγματοληπτικός έλεγχος critical-result communications.',scopeEn:'Sample audit of critical-result communications.',findingIds:['FND-2608-012'],attachments:[],history:[{at:'2026-08-25T13:00:00+03:00',action:'auditCompleted',actor:'Υπεύθυνος Ποιότητας'}]},
  {id:'AUD-2609-001',title:'Audit συμμόρφωσης isolation precautions',titleEn:'Isolation precautions compliance audit',department:'ΜΕΘ',departmentEn:'ICU',auditType:'internal',plannedDate:'2026-09-05',completedDate:null,status:'planned',leadAuditor:'Υπεύθυνος Ποιότητας',scope:'Έλεγχος εφαρμογής isolation precautions σε ενεργές επιτηρήσεις.',scopeEn:'Review of isolation precautions in active surveillance episodes.',findingIds:[],attachments:[],history:[]},
]


qualityIncidents.push(
 {id:'INC-260612-003',title:'Παράλειψη υγιεινής χεριών πριν άσηπτη πράξη',titleEn:'Missed hand hygiene before aseptic task',department:'Παθολογική',departmentEn:'Internal Medicine',date:'2026-06-12',severity:'medium',status:'closed',reportedBy:'Demo Link Nurse',owner:'Υπεύθυνος Ποιότητας',description:'Παρατήρηση στο πλαίσιο ενεργού επιτήρησης συμμόρφωσης.',descriptionEn:'Observation during active compliance surveillance.',attachments:[],history:[]},
 {id:'INC-260403-002',title:'Απόκλιση θερμοκρασίας ψυγείου φαρμάκων',titleEn:'Medication refrigerator temperature deviation',department:'ΜΕΘ',departmentEn:'ICU',date:'2026-04-03',severity:'high',status:'closed',reportedBy:'Demo ICU Nurse',owner:'Υπεύθυνος ΜΕΘ',description:'Καταγράφηκε θερμοκρασία εκτός ορίων και ενεργοποιήθηκε διορθωτική ενέργεια.',descriptionEn:'Out-of-range temperature triggered corrective action.',attachments:[],history:[]}
)
qualityFindings.push(
 {id:'FND-2606-008',title:'Χαμηλή συμμόρφωση WHO Moment 2',titleEn:'Low compliance with WHO Moment 2',source:'audit',sourceId:'AUD-2606-002',department:'Παθολογική',departmentEn:'Internal Medicine',date:'2026-06-15',severity:'medium',status:'closed',owner:'Προϊστάμενος Παθολογικής',description:'Η συμμόρφωση πριν από άσηπτη πράξη ήταν κάτω από τον εσωτερικό στόχο.',descriptionEn:'Compliance before aseptic tasks was below the internal target.',attachments:[],history:[]}
)
qualityCapas.push(
 {id:'CAPA-2606-004',title:'Στοχευμένη επανεκπαίδευση WHO 5 Moments',titleEn:'Targeted WHO 5 Moments retraining',sourceType:'finding',sourceId:'FND-2606-008',department:'Παθολογική',departmentEn:'Internal Medicine',owner:'Link Nurse Παθολογικής',dueDate:'2026-07-05',status:'completed',priority:'medium',actionType:'corrective',description:'Μικροεκπαίδευση και επαναληπτικές παρατηρήσεις.',descriptionEn:'Micro-training and repeat observations.',effectivenessDue:'2026-08-05',effectivenessStatus:'effective',attachments:[],history:[]}
)
qualityAudits.push(
 {id:'AUD-2606-002',title:'Audit Υγιεινής Χεριών',titleEn:'Hand Hygiene Audit',department:'Παθολογική',departmentEn:'Internal Medicine',auditType:'internal',plannedDate:'2026-06-15',completedDate:'2026-06-15',status:'completed',leadAuditor:'Υπεύθυνος Ποιότητας',scope:'WHO 5 Moments και διαθεσιμότητα ABHR.',scopeEn:'WHO 5 Moments and ABHR availability.',findingIds:['FND-2606-008'],attachments:[],history:[]}
)
