const def=(id,fields)=>({
 id,
 organization_id:null,
 indicator_key:id,
 version:'2026.3',
 title_en:'',
 numerator_definition:{},
 denominator_definition:{},
 numerator_metric:null,
 denominator_metric:null,
 multiplier:1,
 unit_en:'',
 effective_from:'2026-01-01',
 effective_to:null,
 status:'active',
 calculation_type:'manual',
 target_value:null,
 direction:'context',
 approved_by:null,
 approved_at:'2026-01-01T00:00:00Z',
 created_by:null,
 ...fields,
})

export const indicatorDefinitionRows=[
 def('hai-prevalence-pps',{category:'surveillance',title_el:'Επιπολασμός νοσοκομειακών λοιμώξεων (PPS)',title_en:'HAI prevalence (PPS)',unit:'%',unit_en:'%',source_authority:'ΕΟΔΥ / ECDC PPS',direction:'lower'}),
 def('mdr-introduction-index',{category:'surveillance',title_el:'Δείκτης εισαγωγής MDR',title_en:'MDR introduction index',unit:'%',unit_en:'%',source_authority:'Επιτήρηση · ΕΟΔΥ',direction:'lower'}),
 def('antibiotic-ddd-1000',{category:'prevention',title_el:'Κατανάλωση αντιβιοτικών DDD / 1.000 κλινοημέρες',title_en:'Antibiotic consumption DDD / 1,000 patient-days',unit:'DDD/1.000 κλινοημέρες',unit_en:'DDD/1,000 patient-days',source_authority:'Φαρμακείο · ΕΟΔΥ / WHO',direction:'lower'}),
 def('mdro-bsi-per-1000',{category:'surveillance',title_el:'Βακτηριαιμίες από πολυανθεκτικά παθογόνα / 1.000 κλινοημέρες',title_en:'MDRO bloodstream infections / 1,000 patient-days',unit:'/1.000 κλινοημέρες',unit_en:'/1,000 patient-days',calculation_type:'auto',numerator_metric:'mdro_bsi',denominator_metric:'patient_days',multiplier:1000,source_authority:'Εργαστήριο · Επιτήρηση · ΕΟΔΥ',direction:'lower',version:'2026.3'}),
 def('bacteremia-incidence-rate',{category:'laboratory',title_el:'Επίπτωση βακτηριαιμιών ανά 1.000 ασθενοημέρες',title_en:'Bacteremia incidence per 1,000 patient-days',unit:'ανά 1.000 ασθενοημέρες',unit_en:'per 1,000 patient-days',calculation_type:'auto',numerator_metric:'bacteremia_total',denominator_metric:'patient_days',multiplier:1000,source_authority:'Εργαστήριο · ΕΟΔΥ (Πρόγραμμα Προκρούστης) · ΥΑ Υ1.Γ.Π.114971/ΦΕΚ Β 388/2014',direction:'lower',version:'1.0'}),
 def('bacteremia-ecoli-rate',{category:'laboratory',title_el:'Βακτηριαιμίες από E. coli ανά 1.000 ασθενοημέρες',title_en:'E. coli bacteremia per 1,000 patient-days',unit:'ανά 1.000 ασθενοημέρες',unit_en:'per 1,000 patient-days',calculation_type:'auto',numerator_metric:'bacteremia_ecoli',denominator_metric:'patient_days',multiplier:1000,source_authority:'Εργαστήριο · ΕΟΔΥ (Πρόγραμμα Προκρούστης) · ΥΑ Υ1.Γ.Π.114971/ΦΕΚ Β 388/2014',direction:'lower',version:'1.0'}),
 def('bacteremia-proteus-rate',{category:'laboratory',title_el:'Βακτηριαιμίες από Proteus spp. ανά 1.000 ασθενοημέρες',title_en:'Proteus spp. bacteremia per 1,000 patient-days',unit:'ανά 1.000 ασθενοημέρες',unit_en:'per 1,000 patient-days',calculation_type:'auto',numerator_metric:'bacteremia_proteus',denominator_metric:'patient_days',multiplier:1000,source_authority:'Εργαστήριο · ΕΟΔΥ (Πρόγραμμα Προκρούστης) · ΥΑ Υ1.Γ.Π.114971/ΦΕΚ Β 388/2014',direction:'lower',version:'1.0'}),
 def('bacteremia-acinetobacter-rate',{category:'laboratory',title_el:'Βακτηριαιμίες από Acinetobacter spp. ανά 1.000 ασθενοημέρες',title_en:'Acinetobacter spp. bacteremia per 1,000 patient-days',unit:'ανά 1.000 ασθενοημέρες',unit_en:'per 1,000 patient-days',calculation_type:'auto',numerator_metric:'bacteremia_acinetobacter',denominator_metric:'patient_days',multiplier:1000,source_authority:'Εργαστήριο · ΕΟΔΥ (Πρόγραμμα Προκρούστης) · ΥΑ Υ1.Γ.Π.114971/ΦΕΚ Β 388/2014',direction:'lower',version:'1.0'}),
 def('bacteremia-klebsiella-rate',{category:'laboratory',title_el:'Βακτηριαιμίες από Klebsiella spp. ανά 1.000 ασθενοημέρες',title_en:'Klebsiella spp. bacteremia per 1,000 patient-days',unit:'ανά 1.000 ασθενοημέρες',unit_en:'per 1,000 patient-days',calculation_type:'auto',numerator_metric:'bacteremia_klebsiella',denominator_metric:'patient_days',multiplier:1000,source_authority:'Εργαστήριο · ΕΟΔΥ (Πρόγραμμα Προκρούστης) · ΥΑ Υ1.Γ.Π.114971/ΦΕΚ Β 388/2014',direction:'lower',version:'1.0'}),
 def('bacteremia-enterobacter-rate',{category:'laboratory',title_el:'Βακτηριαιμίες από Enterobacter spp. ανά 1.000 ασθενοημέρες',title_en:'Enterobacter spp. bacteremia per 1,000 patient-days',unit:'ανά 1.000 ασθενοημέρες',unit_en:'per 1,000 patient-days',calculation_type:'auto',numerator_metric:'bacteremia_enterobacter',denominator_metric:'patient_days',multiplier:1000,source_authority:'Εργαστήριο · ΕΟΔΥ (Πρόγραμμα Προκρούστης) · ΥΑ Υ1.Γ.Π.114971/ΦΕΚ Β 388/2014',direction:'lower',version:'1.0'}),
 def('bacteremia-pseudomonas-rate',{category:'laboratory',title_el:'Βακτηριαιμίες από Pseudomonas spp. ανά 1.000 ασθενοημέρες',title_en:'Pseudomonas spp. bacteremia per 1,000 patient-days',unit:'ανά 1.000 ασθενοημέρες',unit_en:'per 1,000 patient-days',calculation_type:'auto',numerator_metric:'bacteremia_pseudomonas',denominator_metric:'patient_days',multiplier:1000,source_authority:'Εργαστήριο · ΕΟΔΥ (Πρόγραμμα Προκρούστης) · ΥΑ Υ1.Γ.Π.114971/ΦΕΚ Β 388/2014',direction:'lower',version:'1.0'}),
 def('bacteremia-saureus-rate',{category:'laboratory',title_el:'Βακτηριαιμίες από S. aureus ανά 1.000 ασθενοημέρες',title_en:'S. aureus bacteremia per 1,000 patient-days',unit:'ανά 1.000 ασθενοημέρες',unit_en:'per 1,000 patient-days',calculation_type:'auto',numerator_metric:'bacteremia_saureus',denominator_metric:'patient_days',multiplier:1000,source_authority:'Εργαστήριο · ΕΟΔΥ (Πρόγραμμα Προκρούστης) · ΥΑ Υ1.Γ.Π.114971/ΦΕΚ Β 388/2014',direction:'lower',version:'1.0'}),
 def('bacteremia-enterococcus-rate',{category:'laboratory',title_el:'Βακτηριαιμίες από Enterococcus spp. ανά 1.000 ασθενοημέρες',title_en:'Enterococcus spp. bacteremia per 1,000 patient-days',unit:'ανά 1.000 ασθενοημέρες',unit_en:'per 1,000 patient-days',calculation_type:'auto',numerator_metric:'bacteremia_enterococcus',denominator_metric:'patient_days',multiplier:1000,source_authority:'Εργαστήριο · ΕΟΔΥ (Πρόγραμμα Προκρούστης) · ΥΑ Υ1.Γ.Π.114971/ΦΕΚ Β 388/2014',direction:'lower',version:'1.0'}),
 def('outbreak-response-hours',{category:'quality',title_el:'Χρόνος ανίχνευσης & αντίδρασης σε έξαρση',title_en:'Outbreak detection & response time',unit:'ώρες',unit_en:'hours',target_value:24,source_authority:'Επιτήρηση · Audit',direction:'lower'}),
 def('administrative-recording-time',{category:'quality',title_el:'Χρόνος διαχείρισης / καταγραφής λοιμώξεων',title_en:'Infection management / recording time',unit:'λεπτά/περιστατικό',unit_en:'min/case',source_authority:'Operational telemetry / audit',direction:'lower'}),
 def('eody-reporting-completeness',{category:'quality',title_el:'Πληρότητα αναφοράς δεικτών ΕΟΔΥ',title_en:'EODY indicator reporting completeness',unit:'%',unit_en:'%',target_value:100,source_authority:'Governance · ΕΟΔΥ',direction:'higher'}),
 def('eody-reporting-timeliness',{category:'quality',title_el:'Εγκαιρότητα αναφοράς δεικτών ΕΟΔΥ',title_en:'EODY indicator reporting timeliness',unit:'%',unit_en:'%',target_value:100,source_authority:'Governance · ΕΟΔΥ',direction:'higher'}),
 def('active-surveillance',{category:'surveillance',title_el:'Ενεργές επιτηρήσεις',title_en:'Active surveillance episodes',unit:'περιστατικά',unit_en:'episodes',calculation_type:'auto',numerator_metric:'active_surveillance',source_authority:'Επιτήρηση',version:'2026.2'}),
 def('amr-rate',{category:'surveillance',title_el:'Ποσοστό AMR / MDR-XDR',title_en:'AMR / MDR-XDR rate',unit:'%',unit_en:'%',calculation_type:'auto',numerator_metric:'resistant_active_surveillance',denominator_metric:'active_surveillance',multiplier:100,target_value:25,direction:'lower',source_authority:'Επιτήρηση',version:'2026.2'}),
 def('who-hh',{category:'prevention',title_el:'Συμμόρφωση Υγιεινής Χεριών WHO',title_en:'WHO hand hygiene compliance',unit:'%',unit_en:'%',calculation_type:'auto',numerator_metric:'hh_compliant_actions',denominator_metric:'hh_opportunities',multiplier:100,target_value:85,direction:'higher',source_authority:'Πρόληψη · WHO',version:'2026.2'}),
 def('bundle-all-or-none',{category:'prevention',title_el:'Bundle all-or-none compliance',title_en:'Bundle all-or-none compliance',unit:'%',unit_en:'%',calculation_type:'auto',numerator_metric:'bundle_all_or_none_pass',denominator_metric:'bundle_executions',multiplier:100,target_value:90,direction:'higher',source_authority:'Πρόληψη · Bundles',version:'2026.2'}),
 def('abhr',{category:'prevention',title_el:'Κατανάλωση αλκοολούχου αντισηπτικού',title_en:'Alcohol-based hand rub consumption',unit:'L/1.000 ασθενείς-ημέρες',unit_en:'L/1,000 patient-days',calculation_type:'auto',numerator_metric:'abhr_litres',denominator_metric:'patient_days',multiplier:1000,source_authority:'Πρόληψη · Αντισηπτικά',version:'2026.2'}),
 def('training',{category:'workforce',title_el:'Συμμόρφωση εκπαίδευσης',title_en:'Training compliance',unit:'%',unit_en:'%',calculation_type:'auto',numerator_metric:'training_completed',denominator_metric:'training_assignments',multiplier:100,target_value:90,direction:'higher',source_authority:'Εκπαίδευση',version:'2026.2'}),
 def('staff-vaccination',{category:'workforce',title_el:'Εμβολιαστική κάλυψη προσωπικού',title_en:'Staff vaccination coverage',unit:'%',unit_en:'%',calculation_type:'auto',numerator_metric:'active_staff_with_vaccination',denominator_metric:'active_staff',multiplier:100,source_authority:'Εργαζόμενοι',version:'2026.2'}),
 def('open-high-incidents',{category:'quality',title_el:'Ανοιχτά συμβάντα υψηλής σοβαρότητας',title_en:'Open high-severity incidents',unit:'συμβάντα',unit_en:'incidents',calculation_type:'auto',numerator_metric:'open_high_incidents',target_value:0,direction:'lower',source_authority:'Ποιότητα',version:'2026.2'}),
]

export const indicatorSnapshotRows=[]
