import { useMemo, useState } from 'react'
import { Info, TrendingUp } from 'lucide-react'
import { Page } from '../../design-system/Page'
import { RecordActions } from '../../design-system/RecordActions'
import { FilterBar, FilterSelect } from '../../design-system/FilterBar'
import { UI_ACTIONS } from '../../core/actions/actionPolicy'
import { CAPABILITIES } from '../../core/permissions/roles'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { indicatorDefinitions, indicatorDemoValues } from './indicatorDefinitions'

export function IndicatorsPage(){const {language,t}=useLanguage();const {notify}=useFeedback();const [query,setQuery]=useState('');const [category,setCategory]=useState('all');const greek=language==='el';const categories=[...new Set(indicatorDefinitions.map(x=>x.category))];const rows=useMemo(()=>indicatorDefinitions.filter(x=>`${x.titleEl} ${x.titleEn}`.toLowerCase().includes(query.toLowerCase())).filter(x=>category==='all'||x.category===category),[query,category]);function action(value){if(value===UI_ACTIONS.PRINT){window.print();return}notify(t('actionCompleted'),'success')}return <Page fill title={t('indicators')} subtitle={t('indicatorsSubtitle')} actions={<RecordActions actions={[UI_ACTIONS.PRINT,UI_ACTIONS.EXPORT]} resourceCapability={CAPABILITIES.VIEW_INDICATORS} onAction={action}/>}><div className="workspace-summary"><div className="governance-banner"><Info size={17}/><span>{t('indicatorGovernance')}</span></div></div><div className="workspace-fill indicator-workspace"><FilterBar query={query} onQueryChange={setQuery} placeholder={t('searchIndicators')} activeAdvancedCount={category!=='all'?1:0} onClear={()=>{setQuery('');setCategory('all')}}><FilterSelect label={t('category')} value={category} onChange={setCategory}><option value="all">{t('all')}</option>{categories.map(x=><option key={x} value={x}>{t(x)}</option>)}</FilterSelect></FilterBar><div className="scroll-list indicator-scroll"><div className="indicator-grid">{rows.map(item=><article className="indicator-card" key={item.id}><header><div><span>{greek?item.titleEl:item.titleEn}</span><small>{t(item.category)}</small></div><TrendingUp size={18}/></header><strong>{indicatorDemoValues[item.id]}</strong><div className="indicator-unit">{greek?item.unit:item.unitEn}</div><footer><span>{t('definitionVersion')}: {item.version}</span><button onClick={()=>notify(`${t('drillDown')}: ${greek?item.titleEl:item.titleEn}`,'info')}>{t('drillDown')}</button></footer></article>)}</div><section className="surface indicator-method"><h2>{t('indicatorMethod')}</h2><p>{t('indicatorMethodText')}</p><div className="method-grid"><div><span>{t('numerator')}</span><strong>{t('traceableRecords')}</strong></div><div><span>{t('denominator')}</span><strong>{t('patientDaysAndSources')}</strong></div><div><span>{t('period')}</span><strong>{t('definedReportingPeriod')}</strong></div><div><span>{t('export')}</span><strong>{t('auditedExport')}</strong></div></div></section></div></div></Page>}
