import { useCallback,useEffect,useMemo,useState } from 'react'
import { Activity,CheckCircle2,Database,RefreshCcw,Save,Target,TrendingUp } from 'lucide-react'
import { Page } from '../../design-system/Page'
import { Button } from '../../design-system/Button'
import { MetricCard } from '../../design-system/MetricCard'
import { FilterBar,FilterDate,FilterSelect } from '../../design-system/FilterBar'
import { ObserverDialog,DialogActions } from '../../design-system/ObserverDialog'
import { useTenant } from '../../core/tenant/TenantContext'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { CAPABILITIES,can } from '../../core/permissions/roles'
import { loadDepartments } from '../management/departmentsService'
import { collectCloudIndicatorMetrics,calculateCloudDefinition,loadOperationalIndicatorDefinitions,loadIndicatorSnapshots,saveIndicatorSnapshots,approveIndicatorSnapshot } from './indicatorCloudService'
import { downloadCsv } from '../../core/export/csvExport'

const today=()=>new Date().toISOString().slice(0,10)
const monthStart=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`}
const categoryLabel=(category,el)=>({surveillance:el?'Επιτήρηση':'Surveillance',prevention:el?'Πρόληψη':'Prevention',workforce:el?'Προσωπικό':'Workforce',laboratory:el?'Εργαστήριο':'Laboratory',quality:el?'Ποιότητα':'Quality'}[category]||category)
const statusText=(status,el)=>status==='onTarget'?(el?'Εντός στόχου':'On target'):status==='attention'?(el?'Χρειάζεται προσοχή':'Needs attention'):(el?'Πληροφοριακό':'Context')

export function IndicatorsCloudPage(){
 const {tenant,membership,role}=useTenant();const {language,locale}=useLanguage();const {notify}=useFeedback();const el=language==='el'
 const addOns=membership?.capabilities||[],customCapabilities=membership?.customCapabilities||[];const canManage=can(role,CAPABILITIES.MANAGE_INDICATORS,addOns,customCapabilities)
 const scopedDepartmentIds=membership?.departmentIds||[],departmentScoped=scopedDepartmentIds.length>0
 const [from,setFrom]=useState(monthStart);const [to,setTo]=useState(today);const [department,setDepartment]=useState('');const [departments,setDepartments]=useState([]);const [definitions,setDefinitions]=useState([]);const [manualValues,setManualValues]=useState({});const [rows,setRows]=useState([]);const [snapshots,setSnapshots]=useState([]);const [loading,setLoading]=useState(false);const [selected,setSelected]=useState(null);const [query,setQuery]=useState('');const [category,setCategory]=useState('all')
 const allowedDepartments=useMemo(()=>departmentScoped?departments.filter(d=>scopedDepartmentIds.includes(d.id)):departments,[departments,departmentScoped,scopedDepartmentIds]);const effectiveDepartment=departmentScoped?(department||allowedDepartments[0]?.id||''):department
 useEffect(()=>{if(!tenant?.id)return;loadDepartments(tenant.id).then(data=>setDepartments((data||[]).filter(x=>x.is_active!==false))).catch(()=>setDepartments([]))},[tenant?.id])
 useEffect(()=>{if(!departmentScoped)return;if(!allowedDepartments.length){setDepartment('');return}if(!department||!allowedDepartments.some(d=>d.id===department))setDepartment(allowedDepartments[0].id)},[departmentScoped,allowedDepartments,department])
 const calculate=useCallback(async()=>{if(!tenant?.id||!from||!to||to<from)return;if(departmentScoped&&!effectiveDepartment)return;setLoading(true);try{const [metrics,defs,history]=await Promise.all([collectCloudIndicatorMetrics(tenant.id,{from,to,departmentId:effectiveDepartment||null}),loadOperationalIndicatorDefinitions(tenant.id,{from,to}),loadIndicatorSnapshots(tenant.id,{departmentId:effectiveDepartment||null})]);setDefinitions(defs);setSnapshots(history);const currentManual={...manualValues};for(const snap of history.filter(s=>s.period_start===from&&s.period_end===to&&s.calculation_type==='manual'))currentManual[snap.indicator_key]=String(snap.value??'');setManualValues(currentManual);setRows(defs.map(def=>calculateCloudDefinition({...def,manualValue:currentManual[def.id]},metrics)))}catch(error){notify(error?.message||(el?'Αποτυχία υπολογισμού δεικτών.':'Indicator calculation failed.'),'error')}finally{setLoading(false)}},[tenant?.id,from,to,effectiveDepartment,departmentScoped,notify,el,manualValues])
 useEffect(()=>{calculate()},[tenant?.id,from,to,effectiveDepartment,departmentScoped])
 function recalcWithManual(next){setManualValues(next);setRows(current=>current.map(row=>row.calculation==='manual'?calculateCloudDefinition({...row,manualValue:next[row.id]},{}):row))}
 const filtered=useMemo(()=>rows.filter(r=>(category==='all'||r.category===category)&&`${r.titleEl} ${r.titleEn} ${r.source}`.toLowerCase().includes(query.toLowerCase())),[rows,category,query]);const onTarget=rows.filter(r=>r.status==='onTarget').length,attention=rows.filter(r=>r.status==='attention').length
 async function snapshot(){if(!canManage)return;try{await saveIndicatorSnapshots(tenant.id,rows,{from,to,departmentId:effectiveDepartment||null});const history=await loadIndicatorSnapshots(tenant.id,{departmentId:effectiveDepartment||null});setSnapshots(history);notify(el?'Το στιγμιότυπο δεικτών αποθηκεύτηκε.':'Indicator snapshot saved.','success')}catch(error){notify(error?.message||(el?'Αποτυχία αποθήκευσης στιγμιοτύπου.':'Snapshot save failed.'),'error')}}
 async function approve(id){if(!canManage)return;try{await approveIndicatorSnapshot(tenant.id,id);const history=await loadIndicatorSnapshots(tenant.id,{departmentId:effectiveDepartment||null});setSnapshots(history);notify(el?'Το στιγμιότυπο εγκρίθηκε.':'Snapshot approved.','success')}catch(error){notify(error?.message||(el?'Αποτυχία έγκρισης.':'Approval failed.'),'error')}}
 function exportRows(){const departmentName=allowedDepartments.find(d=>d.id===effectiveDepartment)?.name||(el?'Όλο το νοσοκομείο':'Whole hospital');downloadCsv('limoxis-operational-indicators.csv',[el?'Δείκτης':'Indicator',el?'Περίοδος':'Period',el?'Τμήμα':'Department',el?'Αριθμητής':'Numerator',el?'Παρονομαστής':'Denominator',el?'Τιμή':'Value',el?'Μονάδα':'Unit',el?'Έκδοση':'Version'],filtered.map(r=>[el?r.titleEl:r.titleEn,`${from} – ${to}`,departmentName,r.numerator??'',r.denominator??'',r.value??'',el?r.unit:(r.unitEn||r.unit),r.version]));notify(el?'Η λίστα εξήχθη.':'List exported.','success')}
 const trendFor=useCallback(indicatorKey=>snapshots.filter(s=>s.indicator_key===indicatorKey).slice(-8).reverse(),[snapshots])
 return <Page fill title={el?'Δείκτες':'Indicators'} subtitle={el?'Λειτουργικοί δείκτες από εγκεκριμένους ορισμούς, πραγματικά δεδομένα και ιστορικό στιγμιοτύπων.':'Operational indicators from approved definitions, live data and snapshot history.'} actions={<div className="row-actions"><Button variant="secondary" onClick={calculate} disabled={loading}><RefreshCcw size={15}/>{el?'Επανυπολογισμός':'Recalculate'}</Button><Button variant="secondary" onClick={exportRows}>{el?'Εξαγωγή':'Export'}</Button>{canManage&&<Button onClick={snapshot} disabled={loading||!rows.some(r=>r.value!=null)}><Save size={15}/>{el?'Αποθήκευση στιγμιοτύπου':'Save snapshot'}</Button>}</div>}>
  <div className="indicator-summary-strip module-summary-strip"><MetricCard icon={Activity} value={definitions.length} label={el?'Ενεργοί ορισμοί':'Active definitions'}/><MetricCard icon={CheckCircle2} value={onTarget} label={el?'Εντός στόχου':'On target'} tone="active"/><MetricCard icon={Target} value={attention} label={el?'Χρειάζονται προσοχή':'Need attention'} tone={attention?'warning':'neutral'}/><MetricCard icon={TrendingUp} value={snapshots.filter(s=>s.status==='approved').length} label={el?'Εγκεκριμένα snapshots':'Approved snapshots'}/></div>
  {departmentScoped&&<div className="governance-banner"><Database size={16}/><span>{el?'Οι δείκτες περιορίζονται στα τμήματα που έχουν ανατεθεί στον ρόλο σας.':'Indicators are limited to departments assigned to your role.'}</span></div>}
  <div className="workspace-fill indicator-workspace indicator-registry"><FilterBar query={query} onQueryChange={setQuery} placeholder={el?'Αναζήτηση δείκτη…':'Search indicator…'} activeAdvancedCount={(category!=='all'?1:0)+(effectiveDepartment?1:0)+2} onClear={()=>{setQuery('');setCategory('all');if(!departmentScoped)setDepartment('');setFrom(monthStart());setTo(today())}} advanced={<><FilterDate label={el?'Από':'From'} value={from} onChange={setFrom}/><FilterDate label={el?'Έως':'To'} value={to} onChange={setTo}/></>}><FilterSelect label={el?'Κατηγορία':'Category'} value={category} onChange={setCategory}><option value="all">{el?'Όλες':'All'}</option>{[...new Set(rows.map(r=>r.category))].map(x=><option key={x} value={x}>{categoryLabel(x,el)}</option>)}</FilterSelect><FilterSelect label={el?'Τμήμα':'Department'} value={effectiveDepartment} onChange={setDepartment}>{!departmentScoped&&<option value="">{el?'Όλο το νοσοκομείο':'Whole hospital'}</option>}{allowedDepartments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</FilterSelect></FilterBar>
   {to<from&&<div className="inline-empty">{el?'Η τελική ημερομηνία πρέπει να είναι μετά την αρχική.':'End date must be after start date.'}</div>}{loading&&<div className="inline-empty">{el?'Υπολογισμός από Supabase…':'Calculating from Supabase…'}</div>}<div className="surface indicator-table-surface"><div className="scroll-table"><table className="data-table sticky-table indicator-click-table"><thead><tr><th>{el?'Δείκτης':'Indicator'}</th><th>{el?'Κατηγορία':'Category'}</th><th>{el?'Αποτέλεσμα':'Result'}</th><th>{el?'Αριθμητής / Παρονομαστής':'Numerator / denominator'}</th><th>{el?'Πηγή / Έκδοση':'Source / Version'}</th><th>{el?'Κατάσταση':'Status'}</th></tr></thead><tbody>{filtered.map(r=><tr key={r.definitionId||r.id} tabIndex="0" role="button" onClick={()=>setSelected(r)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(r)}}}><td><strong>{el?r.titleEl:r.titleEn}</strong><small>{from} – {to}{r.calculation==='manual'?' · manual':''}</small></td><td>{categoryLabel(r.category,el)}</td><td className="indicator-result-cell"><strong>{r.value??'—'}</strong><small>{el?r.unit:(r.unitEn||r.unit)}</small></td><td>{r.evidence}</td><td>{r.source}<small>{r.version}</small></td><td><span className={`indicator-status ${r.status}`}>{statusText(r.status,el)}</span></td></tr>)}</tbody></table></div>{!loading&&!filtered.length&&<div className="inline-empty">{el?'Δεν υπάρχουν ενεργοί δείκτες για τα φίλτρα.':'No active indicators for the selected filters.'}</div>}</div>
  </div>
  {selected&&<IndicatorEvidenceDialog item={selected} history={trendFor(selected.id)} from={from} to={to} locale={locale} el={el} canManage={canManage} manualValue={manualValues[selected.id]??''} onManual={value=>{const next={...manualValues,[selected.id]:value};recalcWithManual(next);setSelected(current=>calculateCloudDefinition({...current,manualValue:value},{}))}} onApprove={approve} onClose={()=>setSelected(null)}/>} 
 </Page>
}

function IndicatorEvidenceDialog({item,history,from,to,locale,el,canManage,manualValue,onManual,onApprove,onClose}){
 return <ObserverDialog eyebrow={el?'Λειτουργικός δείκτης':'Operational indicator'} title={el?item.titleEl:item.titleEn} subtitle={`${from} – ${to} · ${item.version}`} width="wide" onClose={onClose}>
  {item.calculation==='manual'&&<label className="field"><span>{el?'Χειροκίνητη τιμή περιόδου':'Manual period value'}</span><input type="number" step="any" value={manualValue} disabled={!canManage} onChange={e=>onManual(e.target.value)}/></label>}
  <div className="indicator-view-grid"><div className="indicator-view-field"><span>{el?'Τιμή':'Value'}</span><strong>{item.value??'—'} {el?item.unit:(item.unitEn||item.unit)}</strong></div><div className="indicator-view-field"><span>{el?'Στόχος':'Target'}</span><strong>{item.target==null?'—':`${item.direction==='higher'?'≥':item.direction==='lower'?'≤':''} ${item.target}`}</strong></div><div className="indicator-view-field"><span>{el?'Αριθμητής':'Numerator'}</span><strong>{item.numerator??'—'}</strong></div><div className="indicator-view-field"><span>{el?'Παρονομαστής':'Denominator'}</span><strong>{item.denominator??'—'}</strong></div></div>
  <div className="indicator-view-note"><Database size={15}/><div><strong>{el?'Τεκμηρίωση δεδομένων':'Data evidence'}</strong><span>{item.source} · {item.evidence} · {new Intl.DateTimeFormat(locale).format(new Date())}</span></div></div>
  <div className="table-wrap"><table className="data-table"><thead><tr><th>{el?'Περίοδος':'Period'}</th><th>{el?'Τιμή':'Value'}</th><th>{el?'Κατάσταση':'Status'}</th><th/></tr></thead><tbody>{history.map(s=><tr key={s.id}><td>{s.period_start} – {s.period_end}</td><td>{s.value} {s.unit||''}</td><td><span className={`status-badge ${s.status==='approved'?'active':'temporary'}`}>{s.status}</span></td><td>{canManage&&s.status==='calculated'&&<Button variant="secondary" onClick={()=>onApprove(s.id)}>{el?'Έγκριση':'Approve'}</Button>}</td></tr>)}</tbody></table>{!history.length&&<div className="inline-empty">{el?'Δεν υπάρχει ιστορικό.':'No history yet.'}</div>}</div>
  <DialogActions><Button variant="secondary" onClick={onClose}>{el?'Κλείσιμο':'Close'}</Button></DialogActions>
 </ObserverDialog>
}
