export const indicatorDefinitions = [
  {id:'hai-prevalence-pps',category:'surveillance',titleEl:'Επιπολασμός νοσοκομειακών λοιμώξεων (PPS)',titleEn:'HAI prevalence (PPS)',unit:'%',unitEn:'%',numerator:null,denominator:null,multiplier:1,version:'2026.3',source:'ΕΟΔΥ / ECDC PPS',calculation:'manual',manualValue:null,target:null,direction:'lower'},
  {id:'mdr-introduction-index',category:'surveillance',titleEl:'Δείκτης εισαγωγής MDR',titleEn:'MDR introduction index',unit:'%',unitEn:'%',numerator:null,denominator:null,multiplier:1,version:'2026.3',source:'Επιτήρηση · ΕΟΔΥ',calculation:'manual',manualValue:null,target:null,direction:'lower'},
  {id:'antibiotic-ddd-1000',category:'prevention',titleEl:'Κατανάλωση αντιβιοτικών DDD / 1.000 κλινοημέρες',titleEn:'Antibiotic consumption DDD / 1,000 patient-days',unit:'DDD/1.000 κλινοημέρες',unitEn:'DDD/1,000 patient-days',numerator:null,denominator:null,multiplier:1,version:'2026.3',source:'Φαρμακείο · ΕΟΔΥ / WHO',calculation:'manual',manualValue:null,target:null,direction:'lower'},
  {id:'mdro-bsi-per-1000',category:'surveillance',titleEl:'Βακτηριαιμίες από πολυανθεκτικά παθογόνα / 1.000 κλινοημέρες',titleEn:'MDRO bloodstream infections / 1,000 patient-days',unit:'/1.000 κλινοημέρες',unitEn:'/1,000 patient-days',numerator:'mdro_bsi',denominator:'patient_days',multiplier:1000,version:'2026.3',source:'Εργαστήριο · Επιτήρηση · ΕΟΔΥ',calculation:'auto',target:null,direction:'lower'},
  {id:'outbreak-response-hours',category:'quality',titleEl:'Χρόνος ανίχνευσης & αντίδρασης σε έξαρση',titleEn:'Outbreak detection & response time',unit:'ώρες',unitEn:'hours',numerator:null,denominator:null,multiplier:1,version:'2026.3',source:'Επιτήρηση · Audit',calculation:'manual',manualValue:null,target:24,direction:'lower'},
  {id:'administrative-recording-time',category:'quality',titleEl:'Χρόνος διαχείρισης / καταγραφής λοιμώξεων',titleEn:'Infection management / recording time',unit:'λεπτά/περιστατικό',unitEn:'min/case',numerator:null,denominator:null,multiplier:1,version:'2026.3',source:'Operational telemetry / audit',calculation:'manual',manualValue:null,target:null,direction:'lower'},
  {id:'eody-reporting-completeness',category:'quality',titleEl:'Πληρότητα αναφοράς δεικτών ΕΟΔΥ',titleEn:'EODY indicator reporting completeness',unit:'%',unitEn:'%',numerator:null,denominator:null,multiplier:1,version:'2026.3',source:'Governance · ΕΟΔΥ',calculation:'manual',manualValue:null,target:100,direction:'higher'},
  {id:'eody-reporting-timeliness',category:'quality',titleEl:'Εγκαιρότητα αναφοράς δεικτών ΕΟΔΥ',titleEn:'EODY indicator reporting timeliness',unit:'%',unitEn:'%',numerator:null,denominator:null,multiplier:1,version:'2026.3',source:'Governance · ΕΟΔΥ',calculation:'manual',manualValue:null,target:100,direction:'higher'},
  {id:'active-surveillance',category:'surveillance',titleEl:'Ενεργές επιτηρήσεις',titleEn:'Active surveillance episodes',unit:'περιστατικά',unitEn:'episodes',numerator:'active_surveillance',denominator:null,multiplier:1,version:'2026.2',source:'Επιτήρηση',calculation:'auto',target:null,direction:'context'},
  {id:'amr-rate',category:'surveillance',titleEl:'Ποσοστό AMR / MDR-XDR',titleEn:'AMR / MDR-XDR rate',unit:'%',unitEn:'%',numerator:'resistant_active_surveillance',denominator:'active_surveillance',multiplier:100,version:'2026.2',source:'Επιτήρηση',calculation:'auto',target:25,direction:'lower'},
  {id:'who-hh',category:'prevention',titleEl:'Συμμόρφωση Υγιεινής Χεριών WHO',titleEn:'WHO hand hygiene compliance',unit:'%',unitEn:'%',numerator:'compliant_hh_actions',denominator:'hh_opportunities',multiplier:100,version:'2026.2',source:'Πρόληψη · WHO',calculation:'auto',target:85,direction:'higher'},
  {id:'bundle-all-or-none',category:'prevention',titleEl:'Bundle all-or-none compliance',titleEn:'Bundle all-or-none compliance',unit:'%',unitEn:'%',numerator:'bundle_all_or_none_pass',denominator:'bundle_executions',multiplier:100,version:'2026.2',source:'Πρόληψη · Bundles',calculation:'auto',target:90,direction:'higher'},
  {id:'abhr',category:'prevention',titleEl:'Κατανάλωση αλκοολούχου αντισηπτικού',titleEn:'Alcohol-based hand rub consumption',unit:'L/1.000 ασθενείς-ημέρες',unitEn:'L/1,000 patient-days',numerator:'abhr_litres',denominator:'patient_days',multiplier:1000,version:'2026.2',source:'Πρόληψη · Αντισηπτικά',calculation:'auto',target:null,direction:'context'},
  {id:'training',category:'workforce',titleEl:'Συμμόρφωση εκπαίδευσης',titleEn:'Training compliance',unit:'%',unitEn:'%',numerator:'completed_training_assignments',denominator:'training_assignments',multiplier:100,version:'2026.2',source:'Εκπαίδευση',calculation:'auto',target:90,direction:'higher'},
  {id:'staff-vaccination',category:'workforce',titleEl:'Εμβολιαστική κάλυψη προσωπικού',titleEn:'Staff vaccination coverage',unit:'%',unitEn:'%',numerator:'active_staff_with_vaccination_record',denominator:'active_staff',multiplier:100,version:'2026.2',source:'Εργαζόμενοι',calculation:'auto',target:null,direction:'context'},
  {id:'open-high-incidents',category:'quality',titleEl:'Ανοιχτά συμβάντα υψηλής σοβαρότητας',titleEn:'Open high-severity incidents',unit:'συμβάντα',unitEn:'incidents',numerator:'open_high_incidents',denominator:null,multiplier:1,version:'2026.2',source:'Ποιότητα',calculation:'auto',target:0,direction:'lower'},
]

export const indicatorCategoryLabels={
 surveillance:'Επιτήρηση',prevention:'Πρόληψη',workforce:'Προσωπικό',quality:'Ποιότητα'
}
