import { useCallback,useEffect,useMemo,useState } from 'react'
import { Activity,CheckCircle2,Database,RefreshCcw,Save,Target,TrendingUp } from 'lucide-react'
import { Page } from '../../design-system/Page'
import { Button } from '../../design-system/Button'
import { MetricCard } from '../../design-system/MetricCard'
import { FilterBar,FilterDate,FilterSelect } from '../../design-system/FilterBar'
import { ObserverDialog } from '../../design-system/ObserverDialog'
import { useTenant } from '../../core/tenant/TenantContext'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { loadDepartments } from '../management/departmentsService'
import { collectCloudIndicatorMetrics,calculateCloudDefinition,loadIndicatorSnapshots,saveIndicatorSnapshots } from './indicatorCloudService'
import { downloadCsv } from '../../core/export/csvExport'

const today=()=>new Date().toISOString().slice(0,10)
const monthStart=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`}
const coreDefinitions=[
 {id:'hai-per-1000',titleEl:'Ενεργή επιτήρηση ανά 1.000 ασθενοημέρες',titleEn:'Active surveillance per 1,000 patient-days',category:'surveillance',numerator:'active_surveillance',denominator:'patient_days',multiplier:1000,unit:'‰',source:'Surveillance / Patient days',calculation:'auto',target:null,direction:'lower'},
 {id:'mdr-active-share',titleEl:'Ενεργή επιτήρηση με αντοχή',titleEn:'Active surveillance with resistance',category:'surveillance',numerator:'resistant_active_surveillance',denominator:'active_surveillance',multiplier:100,unit:'%',source:'Surveillance',calculation:'auto',target:null,direction:'lower'},
 {id:'hh-compliance',titleEl:'Συμμόρφωση υγιεινής χεριών',titleEn:'Hand hygiene compliance',category:'prevention',numerator:'hh_compliant_actions',denominator:'hh_opportunities',multiplier:100,unit:'%',source:'WHO Hand Hygiene',calculation:'auto',target:80,direction:'higher'},
 {id:'bundle-compliance',titleEl:'Συμμόρφωση bundles',titleEn:'Bundle compliance',category:'prevention',numerator:'bundle_all_or_none_pass',denominator:'bundle_executions',multiplier:100,unit:'%',source:'Prevention bundles',calculation:'auto',target:95,direction:'higher'},
 {id:'vaccination-coverage',titleEl:'Εμβολιαστική κάλυψη προσωπικού',titleEn:'Staff vaccination coverage',category:'workforce',numerator:'active_staff_with_vaccination',denominator:'active_staff',multiplier:100,unit:'%',source:'Employee health',calculation:'auto',target:null,direction:'higher'},
 {id:'training-completion',titleEl:'Ολοκλήρωση εκπαίδευσης',titleEn:'Training completion',category:'workforce',numerator:'training_completed',denominator:'training_assignments',multiplier:100,unit:'%',source:'Training',calculation:'auto',target:90,direction:'higher'},
 {id:'mdro-bsi-rate',titleEl:'MDR/XDR/PDR θετικές καλλιέργειες ανά 1.000 ασθενοημέρες',titleEn:'MDR/XDR/PDR positive cultures per 1,000 patient-days',category:'laboratory',numerator:'mdro_bsi',denominator:'patient_days',multiplier:1000,unit:'‰',source:'Laboratory / AMR',calculation:'auto',target:null,direction:'lower'},
 {id:'abhr-use',titleEl:'Κατανάλωση αλκοολούχου αντισηπτικού ανά 1.000 ασθενοημέρες',titleEn:'Alcohol hand-rub use per 1,000 patient-days',category:'prevention',numerator:'abhr_litres',denominator:'abhr_patient_days',multiplier:1000,unit:'L/1.000',source:'Antiseptic consumption',calculation:'auto',target:null,direction:'context'},
]
const statusText=(status,el)=>status==='onTarget'?(el?'Εντός στόχου':'On target'):status==='attention'?(el?'Χρειάζεται προσοχή':'Needs attention'):(el?'Πληροφοριακό':'Context')

export function IndicatorsCloudPage(){
 const {tenant,membership}=useTenant();const {language,locale}=useLanguage();const {notify}=useFeedback();const el=language==='el'
 const [from,setFrom]=useState(monthStart);const [to,setTo]=useState(today);const [department,setDepartment]=useState('');const [departments,setDepartments]=useState([]);const [rows,setRows]=useState([]);const [snapshots,setSnapshots]=useState([]);const [loading,setLoading]=useState(false);const [selected,setSelected]=useState(null);const [query,setQuery]=useState('');const [category,setCategory]=useState('all')
 const allowedDepartments=useMemo(()=>{const scoped=membership?.departmentIds||[];return scoped.length?departments.filter(d=>scoped.includes(d.id)):departments},[departments,membership?.departmentIds])
 useEffect(()=>{if(!tenant?.id)return;loadDepartments(tenant.id).then(data=>setDepartments((data||[]).filter(x=>x.is_active!==false))).catch(()=>setDepartments([]))},[tenant?.id])
 const calculate=useCallback(async()=>{if(!tenant?.id||!from||!to)return;setLoading(true);try{const metrics=await collectCloudIndicatorMetrics(tenant.id,{from,to,departmentId:department||null});const calculated=coreDefinitions.map(def=>calculateCloudDefinition(def,metrics));setRows(calculated);const history=await loadIndicatorSnapshots(tenant.id,{departmentId:department||null});setSnapshots(history)}catch(error){notify(error?.message||(el?'Αποτυχία υπολογισμού δεικτών.':'Indicator calculation failed.'),'error')}finally{setLoading(false)}},[tenant?.id,from,to,department,notify,el])
 useEffect(()=>{calculate()},[calculate])
 const filtered=useMemo(()=>rows.filter(r=>(category==='all'||r.category===category)&&`${r.titleEl} ${r.titleEn} ${r.source}`.toLowerCase().includes(query.toLowerCase())),[rows,category,query])
 const onTarget=rows.filter(r=>r.status==='onTarget').length,attention=rows.filter(r=>r.status==='attention').length
 async function snapshot(){try{await saveIndicatorSnapshots(tenant.id,rows,{from,to,departmentId:department||null});const history=await loadIndicatorSnapshots(tenant.id,{departmentId:department||null});setSnapshots(history);notify(el?'Το στιγμιότυπο δεικτών αποθηκεύτηκε.':'Indicator snapshot saved.','success')}catch(error){notify(error?.message||(el?'Αποτυχία αποθήκευσης στιγμιότυπου.':'Snapshot save failed.'),'error')}}
 function exportRows(){downloadCsv('limoxis-operational-indicators.csv',[el?'Δείκτης':'Indicator',el?'Περίοδος':'Period',el?'Τμήμα':'Department',el?'Αριθμητής':'Numerator',el?'Παρονομαστής':'Denominator',el?'Τιμή':'Value',el?'Μονάδα':'Unit'],filtered.map(r=>[el?r.titleEl:r.titleEn,`${from} – ${to}`,allowedDepartments.find(d=>d.id===department)?.name||(el?'Όλο το νοσοκομείο':'Whole hospital'),r.numerator??'',r.denominator??'',r.value??'',r.unit]));notify(el?'Η λίστα εξήχθη.':'List exported.','success')}
 return <Page fill title={el?'Δείκτες':'Indicators'} subtitle={el?'Λειτουργικοί δείκτες από πραγματικά δεδομένα του νοσοκομείου, με περίοδο, τμήμα και ιστορικό στιγμιοτύπων.':'Operational indicators from live hospital data, with period, department and snapshot history.'} actions={<div className="row-actions"><Button variant="secondary" onClick={calculate} disabled={loading}><RefreshCcw size={15}/>{el?'Επανυπολογισμός':'Recalculate'}</Button><Button variant="secondary" onClick={exportRows}>{el?'Εξαγωγή':'Export'}</Button><Button onClick={snapshot} disabled={loading||!rows.length}><Save size={15}/>{el?'Αποθήκευση στιγμιοτύπου':'Save snapshot'}</Button></div>}>
  <div className="indicator-summary-strip module-summary-strip"><MetricCard icon={Activity} value={rows.length} label={el?'Ενεργοί δείκτες':'Active indicators'}/><MetricCard icon={CheckCircle2} value={onTarget} label={el?'Εντός στόχου':'On target'} tone="active"/><MetricCard icon={Target} value={attention} label={el?'Χρειάζονται προσοχή':'Need attention'} tone={attention?'warning':'neutral'}/><MetricCard icon={TrendingUp} value={snapshots.length} label={el?'Ιστορικά στιγμιότυπα':'Historical snapshots'}/></div>
  <div className="workspace-fill indicator-workspace indicator-registry"><FilterBar query={query} onQueryChange={setQuery} placeholder={el?'Αναζήτηση δείκτη…':'Search indicator…'} activeAdvancedCount={(category!=='all'?1:0)+(department?1:0)+2} onClear={()=>{setQuery('');setCategory('all');setDepartment('');setFrom(monthStart());setTo(today())}} advanced={<><FilterDate label={el?'Από':'From'} value={from} onChange={setFrom}/><FilterDate label={el?'Έως':'To'} value={to} onChange={setTo}/></>}><FilterSelect label={el?'Κατηγορία':'Category'} value={category} onChange={setCategory}><option value="all">{el?'Όλες':'All'}</option>{[...new Set(rows.map(r=>r.category))].map(x=><option key={x} value={x}>{x}</option>)}</FilterSelect><FilterSelect label={el?'Τμήμα':'Department'} value={department} onChange={setDepartment}><option value="">{el?'Όλο το νοσοκομείο':'Whole hospital'}</option>{allowedDepartments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</FilterSelect></FilterBar>
   {loading&&<div className="inline-empty">{el?'Υπολογισμός από Supabase…':'Calculating from Supabase…'}</div>}<div className="surface indicator-table-surface"><div className="scroll-table"><table className="data-table sticky-table indicator-click-table"><thead><tr><th>{el?'Δείκτης':'Indicator'}</th><th>{el?'Κατηγορία':'Category'}</th><th>{el?'Αποτέλεσμα':'Result'}</th><th>{el?'Αριθμητής / Παρονομαστής':'Numerator / denominator'}</th><th>{el?'Πηγή':'Source'}</th><th>{el?'Κατάσταση':'Status'}</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} tabIndex="0" role="button" onClick={()=>setSelected(r)} onKeyDown={e=>{if(e.key==='Enter'){setSelected(r)}}}><td><strong>{el?r.titleEl:r.titleEn}</strong><small>{from} – {to}</small></td><td>{r.category}</td><td className="indicator-result-cell"><strong>{r.value??'—'}</strong><small>{r.unit}</small></td><td>{r.evidence}</td><td>{r.source}</td><td><span className={`indicator-status ${r.status}`}>{statusText(r.status,el)}</span></td></tr>)}</tbody></table></div>{!loading&&!filtered.length&&<div className="inline-empty">{el?'Δεν υπάρχουν υπολογίσιμα δεδομένα για τα φίλτρα.':'No calculable data for the selected filters.'}</div>}</div>
  </div>
  {selected&&<ObserverDialog eyebrow={el?'Λειτουργικός δείκτης':'Operational indicator'} title={el?selected.titleEl:selected.titleEn} subtitle={`${from} – ${to}`} width="wide" onClose={()=>setSelected(null)}><div className="indicator-view-grid"><div className="indicator-view-field"><span>{el?'Τιμή':'Value'}</span><strong>{selected.value??'—'} {selected.unit}</strong></div><div className="indicator-view-field"><span>{el?'Κατάσταση':'Status'}</span><strong>{statusText(selected.status,el)}</strong></div><div className="indicator-view-field"><span>{el?'Αριθμητής':'Numerator'}</span><strong>{selected.numerator??'—'}</strong></div><div className="indicator-view-field"><span>{el?'Παρονομαστής':'Denominator'}</span><strong>{selected.denominator??'—'}</strong></div></div><div className="indicator-view-note"><Database size={15}/><div><strong>{el?'Τεκμηρίωση δεδομένων':'Data evidence'}</strong><span>{selected.source} · {selected.evidence} · {new Intl.DateTimeFormat(locale).format(new Date())}</span></div></div></ObserverDialog>}
 </Page>
}
