import { ManualDateField } from '../../design-system/ManualDateField'
import { INDICATOR_METRICS,allowedIndicatorDenominators,indicatorMetricCombinationIsValid,indicatorMetricRule } from './indicatorDefinitionService'

const metricLabels={patient_days:['Νοσηλευτικές ημέρες','Patient days'],active_surveillance:['Ενεργές επιτηρήσεις','Active surveillance'],resistant_active_surveillance:['Ενεργές επιτηρήσεις με MDR/XDR/PDR','Active surveillance with MDR/XDR/PDR'],hh_compliant_actions:['Συμμορφούμενες ενέργειες υγιεινής χεριών','Compliant hand-hygiene actions'],hh_opportunities:['Ευκαιρίες υγιεινής χεριών','Hand-hygiene opportunities'],bundle_all_or_none_pass:['Πλήρως συμμορφούμενα bundles','All-or-none bundle passes'],bundle_executions:['Εκτελέσεις bundles','Bundle executions'],abhr_litres:['Λίτρα αντισηπτικού','Antiseptic litres'],active_staff:['Ενεργοί εργαζόμενοι','Active staff'],active_staff_with_vaccination:['Εργαζόμενοι με εμβολιασμό','Staff with vaccination'],training_completed:['Ολοκληρωμένες εκπαιδεύσεις','Completed training'],training_assignments:['Αναθέσεις εκπαίδευσης','Training assignments'],open_high_incidents:['Ανοιχτά συμβάντα υψηλής σοβαρότητας','Open high-severity incidents'],mdro_bsi:['MDRO θετικές καλλιέργειες','MDRO positive cultures']}

export const createEmptyIndicatorDefinition=()=>({id:null,system:false,key:'',version:'1.0',titleEl:'',category:'surveillance',calculationType:'auto',numeratorMetric:'',denominatorMetric:'',numeratorDefinition:{description:''},denominatorDefinition:{description:''},multiplier:1,unit:'',targetValue:'',direction:'context',sourceAuthority:'',effectiveFrom:new Date().toISOString().slice(0,10),effectiveTo:'',status:'draft'})

export function indicatorDefinitionIsValid(v){return Boolean(v?.key?.trim()&&v?.titleEl?.trim()&&v?.version?.trim()&&(v.calculationType!=='auto'||(v?.numeratorMetric?.trim()&&indicatorMetricCombinationIsValid(v.numeratorMetric,v.denominatorMetric||'')))&&(!v?.effectiveFrom||!v?.effectiveTo||v.effectiveTo>=v.effectiveFrom))}

export function IndicatorDefinitionForm({value,onChange,language='el',readOnly=false,showSystem=false,lockKey=false}){
 const el=language==='el',v=value||createEmptyIndicatorDefinition(),set=(key,next)=>onChange({...v,[key]:next}),automatic=v.calculationType==='auto'
 const denominatorOptions=automatic?allowedIndicatorDenominators(v.numeratorMetric):[]
 const ratioRule=automatic&&v.denominatorMetric?indicatorMetricRule(v.numeratorMetric):null
 const ratioLocked=Boolean(ratioRule&&ratioRule.denominator===v.denominatorMetric)
 const combinationValid=!automatic||!v.numeratorMetric||indicatorMetricCombinationIsValid(v.numeratorMetric,v.denominatorMetric||'')
 const setNumerator=next=>{
  const allowed=allowedIndicatorDenominators(next)
  const denominator=allowed.includes(v.denominatorMetric)?v.denominatorMetric:''
  onChange({...v,numeratorMetric:next,denominatorMetric:denominator,multiplier:denominator?indicatorMetricRule(next)?.multiplier??v.multiplier:v.multiplier,unit:denominator?indicatorMetricRule(next)?.unit??v.unit:v.unit})
 }
 const setDenominator=next=>{
  const rule=indicatorMetricRule(v.numeratorMetric)
  onChange({...v,denominatorMetric:next,multiplier:next&&rule?.denominator===next?rule.multiplier:v.multiplier,unit:next&&rule?.denominator===next?rule.unit:v.unit})
 }
 return <div className="entry-grid">
  <label className="entry-span-2"><span>{el?'Τίτλος *':'Title *'}</span><input autoFocus value={v.titleEl||''} disabled={readOnly} onChange={e=>set('titleEl',e.target.value)}/></label>
  <label><span>{el?'Κωδικός δείκτη *':'Indicator key *'}</span><input value={v.key||''} disabled={readOnly||lockKey} onChange={e=>set('key',e.target.value)} placeholder="custom_indicator"/></label>
  <label><span>{el?'Έκδοση *':'Version *'}</span><input value={v.version||''} disabled={readOnly} onChange={e=>set('version',e.target.value)}/></label>
  <label><span>{el?'Κατηγορία':'Category'}</span><select value={v.category||'surveillance'} disabled={readOnly} onChange={e=>set('category',e.target.value)}><option value="surveillance">{el?'Επιτήρηση':'Surveillance'}</option><option value="prevention">{el?'Πρόληψη':'Prevention'}</option><option value="laboratory">{el?'Εργαστήριο':'Laboratory'}</option><option value="workforce">{el?'Προσωπικό':'Workforce'}</option><option value="quality">{el?'Ποιότητα':'Quality'}</option></select></label>
  <label><span>{el?'Τύπος υπολογισμού':'Calculation type'}</span><select value={v.calculationType||'auto'} disabled={readOnly} onChange={e=>set('calculationType',e.target.value)}><option value="auto">{el?'Αυτόματος από δεδομένα':'Automatic from data'}</option><option value="manual">{el?'Χειροκίνητος':'Manual'}</option></select></label>
  {automatic&&<><label><span>{el?'Metric αριθμητή *':'Numerator metric *'}</span><select value={v.numeratorMetric||''} disabled={readOnly} onChange={e=>setNumerator(e.target.value)}><option value="">{el?'Επιλέξτε μετρική…':'Select metric…'}</option>{INDICATOR_METRICS.map(x=><option key={x} value={x}>{metricLabels[x]?.[el?0:1]||x}</option>)}</select></label><label><span>{el?'Metric παρονομαστή':'Denominator metric'}</span><select value={v.denominatorMetric||''} disabled={readOnly||!v.numeratorMetric} onChange={e=>setDenominator(e.target.value)}><option value="">{el?'Χωρίς παρονομαστή · απλή μέτρηση':'No denominator · raw measure'}</option>{denominatorOptions.map(x=><option key={x} value={x}>{metricLabels[x]?.[el?0:1]||x}</option>)}</select></label><label className="entry-span-2"><span>{el?'Ορισμός αριθμητή':'Numerator definition'}</span><textarea rows="3" value={v.numeratorDefinition?.description||''} disabled={readOnly} onChange={e=>set('numeratorDefinition',{...(v.numeratorDefinition||{}),description:e.target.value})}/></label><label className="entry-span-2"><span>{el?'Ορισμός παρονομαστή':'Denominator definition'}</span><textarea rows="3" value={v.denominatorDefinition?.description||''} disabled={readOnly} onChange={e=>set('denominatorDefinition',{...(v.denominatorDefinition||{}),description:e.target.value})}/></label><label><span>{el?'Πολλαπλασιαστής':'Multiplier'}{ratioLocked?' · AUTO':''}</span><input type="number" step="any" value={v.multiplier??1} disabled={readOnly||ratioLocked} onChange={e=>set('multiplier',e.target.value)}/></label><label><span>{el?'Μονάδα':'Unit'}{ratioLocked?' · AUTO':''}</span><input value={v.unit||''} disabled={readOnly||ratioLocked} onChange={e=>set('unit',e.target.value)} placeholder="%, /1.000, L"/></label></>}
  <label><span>{el?'Στόχος':'Target'}</span><input type="number" step="any" value={v.targetValue??''} disabled={readOnly} onChange={e=>set('targetValue',e.target.value)}/></label>
  <label><span>{el?'Κατεύθυνση στόχου':'Target direction'}</span><select value={v.direction||'context'} disabled={readOnly} onChange={e=>set('direction',e.target.value)}><option value="context">{el?'Πληροφοριακός':'Context only'}</option><option value="higher">{el?'Υψηλότερα είναι καλύτερα':'Higher is better'}</option><option value="lower">{el?'Χαμηλότερα είναι καλύτερα':'Lower is better'}</option></select></label>
  <label><span>{el?'Πηγή / Αρχή':'Source / authority'}</span><input value={v.sourceAuthority||''} disabled={readOnly} onChange={e=>set('sourceAuthority',e.target.value)}/></label>
  <label><span>{el?'Κατάσταση':'Status'}</span><select value={v.status||'draft'} disabled={readOnly} onChange={e=>set('status',e.target.value)}><option value="draft">{el?'Πρόχειρο':'Draft'}</option><option value="review">{el?'Σε έλεγχο':'In review'}</option><option value="active">{el?'Ενεργό':'Active'}</option><option value="retired">{el?'Αποσυρμένο':'Retired'}</option></select></label>
  <ManualDateField label={el?'Ισχύει από':'Effective from'} value={v.effectiveFrom||''} onChange={x=>set('effectiveFrom',x)} optional/>
  <ManualDateField label={el?'Ισχύει έως':'Effective to'} value={v.effectiveTo||''} onChange={x=>set('effectiveTo',x)} optional/>
  {showSystem&&<label className="check-option"><input type="checkbox" checked={Boolean(v.system)} disabled={readOnly} onChange={e=>set('system',e.target.checked)}/><span>{el?'System definition · διαχείριση Platform Owner':'System definition · Platform Owner managed'}</span></label>}
  {automatic&&v.numeratorMetric&&denominatorOptions.length>0&&!v.denominatorMetric&&<div className="source-truth-note entry-span-2">{el?`Για αναλογικό δείκτη, ο συμβατός παρονομαστής είναι «${metricLabels[denominatorOptions[0]]?.[0]||denominatorOptions[0]}». Χωρίς παρονομαστή ο δείκτης αποθηκεύεται ως απλή μέτρηση.`:`For a ratio indicator, the compatible denominator is “${metricLabels[denominatorOptions[0]]?.[1]||denominatorOptions[0]}”. Without a denominator the indicator is stored as a raw measure.`}</div>}
  {!combinationValid&&<div className="source-truth-note entry-span-2">{el?'Ο επιλεγμένος αριθμητής και παρονομαστής δεν αποτελούν υποστηριζόμενο συνδυασμό.':'The selected numerator and denominator are not a supported combination.'}</div>}
  {v.effectiveFrom&&v.effectiveTo&&v.effectiveTo<v.effectiveFrom&&<div className="source-truth-note entry-span-2">{el?'Η ημερομηνία λήξης δεν μπορεί να προηγείται της έναρξης.':'Effective-to cannot be before effective-from.'}</div>}
 </div>
}
