import { useEffect,useMemo,useState } from 'react'
import { ClipboardCheck,Gauge,Pencil,Trash2 } from 'lucide-react'
import { useLocation,useNavigate,useParams } from 'react-router-dom'
import { Page } from '../../design-system/Page'
import { EntityRecordShell } from '../../design-system/EntityRecordShell'
import { PrintExportActions } from '../../design-system/PrintExportActions'
import { downloadRecordJson } from '../../core/export/recordExport'
import { Button } from '../../design-system/Button'
import { SaveButton } from '../../design-system/SaveButton'
import { RouteLoading } from '../../design-system/RouteLoading'
import { useRecordSequenceNavigation } from '../../core/navigation/useRecordSequenceNavigation'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useTenant } from '../../core/tenant/TenantContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { CAPABILITIES,can } from '../../core/permissions/roles'
import { IndicatorDefinitionForm,indicatorDefinitionIsValid } from './IndicatorDefinitionForm'
import { deleteIndicatorDefinition,loadIndicatorDefinition,saveIndicatorDefinition } from './indicatorDefinitionService'
import { calculateCloudDefinition,collectCloudIndicatorMetrics,loadIndicatorSnapshots,saveIndicatorSnapshots } from './indicatorCloudService'
import { loadCommitteeObjectivesForIndicator } from './indicatorCommitteeService'

const statusLabel=(status,el)=>({draft:el?'Πρόχειρο':'Draft',review:el?'Σε έλεγχο':'In review',active:el?'Ενεργό':'Active',retired:el?'Αποσυρμένο':'Retired'}[status]||status)
const workflowStatusLabel=(status,el)=>({open:el?'Ανοιχτός':'Open',in_progress:el?'Σε εξέλιξη':'In progress',completed:el?'Ολοκληρωμένος':'Completed',cancelled:el?'Ακυρωμένος':'Cancelled'}[status]||status||'—')
const fmtDate=value=>value?new Date(`${String(value).slice(0,10)}T12:00:00`).toLocaleDateString('el-GR'):'—'
const today=()=>new Date().toISOString().slice(0,10)
const monthStart=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`}

export function IndicatorRecordPage(){
 const {indicatorId}=useParams(),navigate=useNavigate(),location=useLocation(),{language}=useLanguage(),el=language==='el', {tenant,role,membership}=useTenant(),{notify,confirm}=useFeedback()
 const [record,setRecord]=useState(null),[draft,setDraft]=useState(null),[loading,setLoading]=useState(true),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[committeeObjectives,setCommitteeObjectives]=useState([])
 const [periodResult,setPeriodResult]=useState(null),[periodSnapshot,setPeriodSnapshot]=useState(null),[manualValue,setManualValue]=useState(''),[periodLoading,setPeriodLoading]=useState(false),[periodSaving,setPeriodSaving]=useState(false)
 const addOns=membership?.capabilities||[],custom=membership?.customCapabilities||[],canManage=can(role,CAPABILITIES.MANAGE_INDICATORS,addOns,custom)
 const recordNavigation=useRecordSequenceNavigation({registry:'indicators',currentId:indicatorId,pathForId:id=>`/indicators/${id}`})
 const period=useMemo(()=>({from:location.state?.indicatorPeriod?.from||monthStart(),to:location.state?.indicatorPeriod?.to||today(),departmentId:location.state?.indicatorPeriod?.departmentId||null}),[location.state])
 useEffect(()=>{let active=true;if(!tenant?.id||!indicatorId)return;setLoading(true);loadIndicatorDefinition(tenant.id,indicatorId).then(row=>{if(!active)return;setRecord(row);setDraft(row);setError('')}).catch(err=>{if(active)setError(err?.message||'load_failed')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[tenant?.id,indicatorId])
 useEffect(()=>{let active=true;if(!tenant?.id||!record){setCommitteeObjectives([]);return()=>{active=false}};loadCommitteeObjectivesForIndicator(tenant.id,record).then(rows=>{if(active)setCommitteeObjectives(rows||[])}).catch(()=>{if(active)setCommitteeObjectives([])});return()=>{active=false}},[tenant?.id,record])
 const operationalDefinition=useMemo(()=>record?{definitionId:record.id,id:record.key,version:record.version,titleEl:record.titleEl,titleEn:record.titleEn||record.titleEl,category:record.category,numerator:record.numeratorMetric,denominator:record.denominatorMetric,multiplier:Number(record.multiplier||1),unit:record.unit||'',unitEn:record.unit||'',source:record.sourceAuthority||'',calculation:record.calculationType||'auto',target:record.targetValue===''||record.targetValue==null?null:Number(record.targetValue),direction:record.direction||'context',numeratorDefinition:record.numeratorDefinition||{},denominatorDefinition:record.denominatorDefinition||{}}:null,[record])
 useEffect(()=>{let active=true;if(!tenant?.id||!operationalDefinition)return;setPeriodLoading(true);Promise.all([collectCloudIndicatorMetrics(tenant.id,{from:period.from,to:period.to,departmentId:period.departmentId}),loadIndicatorSnapshots(tenant.id,{from:period.from,to:period.to,departmentId:period.departmentId})]).then(([metrics,snapshots])=>{if(!active)return;const snapshot=(snapshots||[]).find(item=>item.indicator_key===operationalDefinition.id&&item.period_start===period.from&&item.period_end===period.to)||null;const storedManual=snapshot?.calculation_type==='manual'&&snapshot?.value!=null?String(snapshot.value):'';setPeriodSnapshot(snapshot);setManualValue(storedManual);setPeriodResult(calculateCloudDefinition({...operationalDefinition,manualValue:storedManual},metrics||{}))}).catch(()=>{if(active){setPeriodSnapshot(null);setPeriodResult(null)}}).finally(()=>{if(active)setPeriodLoading(false)});return()=>{active=false}},[tenant?.id,operationalDefinition,period])
 if(loading)return <RouteLoading/>
 if(error)return <Page title={el?'Δείκτες':'Indicators'}><div className="data-access-state error" role="alert">{el?'Δεν ήταν δυνατή η φόρτωση του δείκτη.':'Could not load the indicator.'}</div></Page>
 if(!record)return <Page title={el?'Δείκτες':'Indicators'}><div className="inline-empty">{el?'Ο δείκτης δεν βρέθηκε.':'Indicator not found.'}</div></Page>
 const valid=indicatorDefinitionIsValid(draft)
 async function save(){if(!canManage||!editing||!valid||busy)return;setBusy(true);try{const saved=await saveIndicatorDefinition(tenant.id,draft);setRecord(saved);setDraft(saved);setEditing(false);notify(el?'Ο δείκτης ενημερώθηκε.':'Indicator updated.','success')}catch(err){notify(err?.message||(el?'Δεν ήταν δυνατή η αποθήκευση.':'Could not save indicator.'),'danger')}finally{setBusy(false)}}
 async function remove(){if(!canManage||record.system||busy)return;const ok=await confirm({title:el?'Διαγραφή δείκτη':'Delete indicator',message:el?'Ο δείκτης θα διαγραφεί οριστικά. Τα ήδη αποθηκευμένα αποτελέσματα θα παραμείνουν στο ιστορικό χωρίς σύνδεση με τον ορισμό. Θέλετε να συνεχίσετε;':'The indicator definition will be permanently deleted. Existing saved results will remain in history without the definition link. Continue?',confirmLabel:el?'Διαγραφή':'Delete',danger:true});if(!ok)return;setBusy(true);try{await deleteIndicatorDefinition(tenant.id,record);notify(el?'Ο δείκτης διαγράφηκε.':'Indicator deleted.','success');navigate('/indicators',{replace:true})}catch(err){notify(err?.message||(el?'Δεν ήταν δυνατή η διαγραφή.':'Could not delete indicator.'),'danger');setBusy(false)}}
 function cancel(){setDraft(record);setEditing(false)}
 async function savePeriodResult(){if(!canManage||!operationalDefinition||periodSaving)return;const next=record.calculationType==='manual'?calculateCloudDefinition({...operationalDefinition,manualValue},{}):periodResult;if(!next||next.value==null){notify(el?'Καταχωρήστε πρώτα τιμή για τον δείκτη.':'Enter a value for the indicator first.','warning');return}setPeriodSaving(true);try{const saved=await saveIndicatorSnapshots(tenant.id,[next],{from:period.from,to:period.to,departmentId:period.departmentId});const snapshot=saved?.[0]||null;setPeriodSnapshot(snapshot);setPeriodResult(next);notify(el?'Το αποτέλεσμα του δείκτη αποθηκεύτηκε.':'Indicator result saved.','success')}catch(err){notify(err?.message||(el?'Δεν ήταν δυνατή η αποθήκευση του αποτελέσματος.':'Could not save indicator result.'),'danger')}finally{setPeriodSaving(false)}}
 const resultValue=record.calculationType==='manual'&&manualValue!==''?manualValue:periodResult?.value
 return <Page fill><EntityRecordShell className="indicator-record-shell workspace-fill" avatar={<Gauge size={19}/>} eyebrow={el?'ΔΕΙΚΤΗΣ':'INDICATOR'} title={el?record.titleEl:(record.titleEn||record.titleEl||record.key)} subtitle={`${record.key} · ${el?'Έκδοση':'Version'} ${record.version}`} status={<span className={`status-badge ${record.status==='active'?'active':record.status==='draft'?'temporary':''}`}>{statusLabel(record.status,el)}</span>} recordNavigation={recordNavigation} onBack={()=>navigate('/indicators')} headerActions={<>{canManage&&!editing&&<><button type="button" className="lo-icon-button lo-icon-button-edit lo-icon-button-sm" onClick={()=>setEditing(true)} title={el?'Επεξεργασία':'Edit'} aria-label={el?'Επεξεργασία':'Edit'}><Pencil size={16}/></button>{!record.system&&<button type="button" className="lo-icon-button lo-icon-button-danger lo-icon-button-sm" onClick={remove} disabled={busy} title={el?'Διαγραφή':'Delete'} aria-label={el?'Διαγραφή':'Delete'}><Trash2 size={16}/></button>}</>}<PrintExportActions onExport={()=>downloadRecordJson(record,{filename:record?.key})}/></>} tabs={[]} activeTab="" onTabChange={()=>{}}>
  <div className="workspace-column workspace-fill">
   <section className="record-section indicator-period-result">
    <div className="record-section-header"><div><span className="eyebrow">{el?'ΑΠΟΤΕΛΕΣΜΑ':'RESULT'}</span><h3>{el?'Αποτέλεσμα επιλεγμένης περιόδου':'Selected period result'}</h3><p>{fmtDate(period.from)} – {fmtDate(period.to)}</p></div></div>
    {periodLoading?<div className="inline-empty">{el?'Υπολογισμός…':'Calculating…'}</div>:<div className="details-grid"><div><span>{el?'Τιμή':'Value'}</span>{record.calculationType==='manual'&&canManage&&periodSnapshot?.status!=='approved'?<input type="number" step="any" inputMode="decimal" value={manualValue} onChange={event=>setManualValue(event.target.value)} placeholder="—"/>:<strong>{resultValue??'—'} {record.unit||''}</strong>}</div><div><span>{el?'Τρόπος υπολογισμού':'Calculation'}</span><strong>{record.calculationType==='manual'?(el?'Χειροκίνητη καταχώρηση':'Manual entry'):(periodResult?.evidence||'—')}</strong></div><div><span>{el?'Πηγή':'Source'}</span><strong>{record.sourceAuthority||'—'}</strong></div><div><span>{el?'Κατάσταση καταχώρησης':'Saved status'}</span><strong>{periodSnapshot?.status==='approved'?(el?'Εγκεκριμένο':'Approved'):periodSnapshot?(el?'Αποθηκευμένο · προς έγκριση':'Saved · pending approval'):(el?'Μη καταχωρημένο':'Not saved')}</strong></div></div>}
    {canManage&&periodSnapshot?.status!=='approved'&&<div className="inline-edit-footer"><SaveButton loading={periodSaving} disabled={periodSaving||periodLoading||(record.calculationType==='manual'&&manualValue==='')} onClick={savePeriodResult}>{el?'Αποθήκευση αποτελέσματος':'Save result'}</SaveButton></div>}
    {periodSnapshot?.status==='approved'&&<div className="governance-banner"><ClipboardCheck size={16}/><span>{el?'Το αποτέλεσμα της περιόδου έχει εγκριθεί και δεν μεταβάλλεται.':'This period result is approved and locked.'}</span></div>}
   </section>
   <section className="record-section indicator-record-form">
    <IndicatorDefinitionForm value={draft} onChange={setDraft} language={language} readOnly={!editing} lockKey={Boolean(record.system)}/>
    {editing&&<div className="inline-edit-footer"><Button variant="secondary" onClick={cancel} disabled={busy}>{el?'Ακύρωση':'Cancel'}</Button><SaveButton loading={busy} disabled={!valid||busy} onClick={save}>{el?'Αποθήκευση':'Save'}</SaveButton></div>}
   </section>
   <section className="record-section indicator-committee-objectives">
    <div className="record-section-header"><div><span className="eyebrow">{el?'ΔΙΑΚΥΒΕΡΝΗΣΗ':'GOVERNANCE'}</span><h3>{el?'Στόχοι επιτροπών που χρησιμοποιούν τον δείκτη':'Committee objectives using this indicator'}</h3><p>{el?'Η σύνδεση προέρχεται από το ετήσιο σχέδιο δράσης των επιτροπών.':'Links come from committee annual action plans.'}</p></div></div>
    {committeeObjectives.length?<div className="scroll-table"><table className="data-table"><thead><tr><th>{el?'Επιτροπή':'Committee'}</th><th>{el?'Στόχος':'Objective'}</th><th>{el?'Baseline → στόχος':'Baseline → target'}</th><th>{el?'Υπεύθυνος':'Owner'}</th><th>{el?'Προθεσμία':'Due'}</th><th>{el?'Κατάσταση':'Status'}</th></tr></thead><tbody>{committeeObjectives.map(item=><tr key={item.id} className={item.committee?.code?'clickable-row':''} onClick={()=>item.committee?.code&&navigate(`/committees/${item.committee.code}`)}><td><strong>{item.committee?.name||'—'}</strong></td><td>{item.title||'—'}</td><td>{item.baseline||'—'} → {item.target||'—'}</td><td>{item.owner_label||'—'}</td><td>{fmtDate(item.due_date)}</td><td><span className={`status-badge ${item.status==='completed'?'active':item.status==='in_progress'?'temporary':''}`}>{workflowStatusLabel(item.status,el)}</span></td></tr>)}</tbody></table></div>:<div className="inline-empty">{el?'Δεν υπάρχουν στόχοι επιτροπών συνδεδεμένοι με αυτόν τον δείκτη.':'No committee objectives are linked to this indicator.'}</div>}
   </section>
  </div>
 </EntityRecordShell></Page>
}
