import { useCallback,useEffect,useMemo,useState } from 'react'
import { Activity,CheckCircle2,Database,Plus,RefreshCcw,Target,TrendingUp } from 'lucide-react'
import { Page } from '../../design-system/Page'
import { Button } from '../../design-system/Button'
import { MetricCard } from '../../design-system/MetricCard'
import { FilterBar,FilterDate,FilterSelect } from '../../design-system/FilterBar'
import { ObserverDialog,DialogActions } from '../../design-system/ObserverDialog'
import { RegistryPagination } from '../../design-system/RegistryPagination'
import { ManualDateField } from '../../design-system/ManualDateField'
import { useTenant } from '../../core/tenant/TenantContext'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { CAPABILITIES,can,scopeFor } from '../../core/permissions/roles'
import { DATA_SCOPES } from '../../core/permissions/scopeTypes'
import { loadDepartments } from '../management/departmentsService'
import { collectCloudIndicatorMetrics,calculateCloudDefinition,loadOperationalIndicatorDefinitions,loadIndicatorSnapshots,approveIndicatorSnapshot,createIndicatorDefinition,INDICATOR_METRICS } from './indicatorCloudService'

const today=()=>new Date().toISOString().slice(0,10)
const monthStart=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`}
const categoryLabel=(category,el)=>({surveillance:el?'Επιτήρηση':'Surveillance',prevention:el?'Πρόληψη':'Prevention',workforce:el?'Προσωπικό':'Workforce',laboratory:el?'Εργαστήριο':'Laboratory',quality:el?'Ποιότητα':'Quality'}[category]||category)
const statusText=(status,el)=>status==='onTarget'?(el?'Εντός στόχου':'On target'):status==='attention'?(el?'Χρειάζεται προσοχή':'Needs attention'):(el?'Πληροφοριακό':'Context')
const metricLabels={patient_days:['Νοσηλευτικές ημέρες','Patient days'],active_surveillance:['Ενεργές επιτηρήσεις','Active surveillance'],resistant_active_surveillance:['Ενεργές επιτηρήσεις με MDR/XDR/PDR','Active surveillance with MDR/XDR/PDR'],hh_compliant_actions:['Συμμορφούμενες ενέργειες υγιεινής χεριών','Compliant hand-hygiene actions'],hh_opportunities:['Ευκαιρίες υγιεινής χεριών','Hand-hygiene opportunities'],bundle_all_or_none_pass:['Πλήρως συμμορφούμενα bundles','All-or-none bundle passes'],bundle_executions:['Εκτελέσεις bundles','Bundle executions'],abhr_litres:['Λίτρα αντισηπτικού','Antiseptic litres'],active_staff:['Ενεργοί εργαζόμενοι','Active staff'],active_staff_with_vaccination:['Εργαζόμενοι με εμβολιασμό','Staff with vaccination'],training_completed:['Ολοκληρωμένες εκπαιδεύσεις','Completed training'],training_assignments:['Αναθέσεις εκπαίδευσης','Training assignments'],open_high_incidents:['Ανοιχτά συμβάντα υψηλής σοβαρότητας','Open high-severity incidents'],mdro_bsi:['MDRO θετικές καλλιέργειες','MDRO positive cultures']}

export function IndicatorsCloudPage(){
 const {tenant,membership,role}=useTenant();const {language,locale}=useLanguage();const {notify}=useFeedback();const el=language==='el'
 const addOns=membership?.capabilities||[],customCapabilities=membership?.customCapabilities||[];const canManage=can(role,CAPABILITIES.MANAGE_INDICATORS,addOns,customCapabilities)
 const indicatorScope=scopeFor(CAPABILITIES.VIEW_INDICATORS,{role,scopeOverrides:membership?.scopeOverrides||{}})
 const scopedDepartmentIds=membership?.previewDepartment?[membership.previewDepartment]:(membership?.departmentIds||[]),departmentScoped=indicatorScope===DATA_SCOPES.DEPARTMENT
 const defaultFrom=monthStart(),defaultTo=today()
 const [from,setFrom]=useState(defaultFrom);const [to,setTo]=useState(defaultTo);const [department,setDepartment]=useState('');const [departments,setDepartments]=useState([]);const [definitions,setDefinitions]=useState([]);const [manualValues,setManualValues]=useState({});const [rows,setRows]=useState([]);const [snapshots,setSnapshots]=useState([]);const [loading,setLoading]=useState(false);const [selected,setSelected]=useState(null);const [query,setQuery]=useState('');const [category,setCategory]=useState('all');const [page,setPage]=useState(1);const [pageSize,setPageSize]=useState(15);const [createOpen,setCreateOpen]=useState(false)
 const allowedDepartments=useMemo(()=>departmentScoped?departments.filter(d=>scopedDepartmentIds.includes(d.id)):departments,[departments,departmentScoped,scopedDepartmentIds]);const effectiveDepartment=departmentScoped?(department||allowedDepartments[0]?.id||''):department
 useEffect(()=>{if(!tenant?.id)return;loadDepartments(tenant.id).then(data=>setDepartments((data||[]).filter(x=>x.is_active!==false))).catch(()=>setDepartments([]))},[tenant?.id])
 useEffect(()=>{if(!departmentScoped)return;if(!allowedDepartments.length){setDepartment('');return}if(!department||!allowedDepartments.some(d=>d.id===department))setDepartment(allowedDepartments[0].id)},[departmentScoped,allowedDepartments,department])
 const calculate=useCallback(async()=>{if(!tenant?.id||!from||!to||to<from)return;if(departmentScoped&&!effectiveDepartment)return;setLoading(true);try{const [metrics,defs,history]=await Promise.all([collectCloudIndicatorMetrics(tenant.id,{from,to,departmentId:effectiveDepartment||null}),loadOperationalIndicatorDefinitions(tenant.id,{from,to}),loadIndicatorSnapshots(tenant.id,{departmentId:effectiveDepartment||null})]);setDefinitions(defs);setSnapshots(history);const currentManual={...manualValues};for(const snap of history.filter(s=>s.period_start===from&&s.period_end===to&&s.calculation_type==='manual'))currentManual[snap.indicator_key]=String(snap.value??'');setManualValues(currentManual);setRows(defs.map(def=>calculateCloudDefinition({...def,manualValue:currentManual[def.id]},metrics)))}catch(error){notify(error?.message||(el?'Αποτυχία υπολογισμού δεικτών.':'Indicator calculation failed.'),'error')}finally{setLoading(false)}},[tenant?.id,from,to,effectiveDepartment,departmentScoped,notify,el,manualValues])
 useEffect(()=>{void calculate()},[tenant?.id,from,to,effectiveDepartment,departmentScoped])
 function recalcWithManual(next){setManualValues(next);setRows(current=>current.map(row=>row.calculation==='manual'?calculateCloudDefinition({...row,manualValue:next[row.id]},{}):row))}
 const filtered=useMemo(()=>rows.filter(r=>(category==='all'||r.category===category)&&`${r.titleEl} ${r.titleEn} ${r.source}`.toLowerCase().includes(query.toLowerCase())),[rows,category,query]);const onTarget=rows.filter(r=>r.status==='onTarget').length,attention=rows.filter(r=>r.status==='attention').length
 useEffect(()=>setPage(1),[query,category,effectiveDepartment,from,to,pageSize])
 const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)),safePage=Math.min(page,totalPages),pagedRows=filtered.slice((safePage-1)*pageSize,safePage*pageSize)
 const activeFilterCount=(category!=='all'?1:0)+(!departmentScoped&&department?1:0)+(from!==defaultFrom?1:0)+(to!==defaultTo?1:0)
 function clearFilters(){setQuery('');setCategory('all');if(!departmentScoped)setDepartment('');setFrom(defaultFrom);setTo(defaultTo);setPage(1)}
 async function approve(id){if(!canManage)return;try{await approveIndicatorSnapshot(tenant.id,id);const history=await loadIndicatorSnapshots(tenant.id,{departmentId:effectiveDepartment||null});setSnapshots(history);notify(el?'Το αποθηκευμένο αποτέλεσμα εγκρίθηκε.':'Saved result approved.','success')}catch(error){notify(error?.message||(el?'Αποτυχία έγκρισης.':'Approval failed.'),'error')}}
 const trendFor=useCallback(indicatorKey=>snapshots.filter(s=>s.indicator_key===indicatorKey).slice(-8).reverse(),[snapshots])
 async function createDefinition(draft){try{await createIndicatorDefinition(tenant.id,draft);setCreateOpen(false);notify(el?'Ο νέος δείκτης δημιουργήθηκε.':'Indicator created.','success');await calculate()}catch(error){notify(error?.message||(el?'Δεν ήταν δυνατή η δημιουργία του δείκτη.':'Could not create indicator.'),'error')}}
 return <Page fill title={el?'Δείκτες':'Indicators'} subtitle={el?'Λειτουργικοί δείκτες από εγκεκριμένους ορισμούς και πραγματικά δεδομένα.':'Operational indicators from approved definitions and live data.'} actions={<div className="row-actions"><Button variant="secondary" onClick={calculate} disabled={loading}><RefreshCcw size={15}/>{el?'Επανυπολογισμός':'Recalculate'}</Button>{canManage&&<Button onClick={()=>setCreateOpen(true)}><Plus size={16}/>{el?'Νέος δείκτης':'New indicator'}</Button>}</div>}>
  <div className="indicator-summary-strip module-summary-strip"><MetricCard icon={Activity} value={definitions.length} label={el?'Ενεργοί ορισμοί':'Active definitions'}/><MetricCard icon={CheckCircle2} value={onTarget} label={el?'Εντός στόχου':'On target'} tone="active"/><MetricCard icon={Target} value={attention} label={el?'Χρειάζονται προσοχή':'Need attention'} tone={attention?'warning':'neutral'}/><MetricCard icon={TrendingUp} value={snapshots.filter(s=>s.status==='approved').length} label={el?'Εγκεκριμένα αποτελέσματα':'Approved results'}/></div>
  {departmentScoped&&<div className="governance-banner"><Database size={16}/><span>{el?'Οι δείκτες περιορίζονται στα τμήματα που έχουν ανατεθεί στον ρόλο σας.':'Indicators are limited to departments assigned to your role.'}</span></div>}
  <section className="surface registry-workspace workspace-column workspace-fill indicator-registry">
   <FilterBar query={query} onQueryChange={setQuery} placeholder={el?'Αναζήτηση δείκτη…':'Search indicator…'} activeAdvancedCount={activeFilterCount} onClear={clearFilters} advanced={<><FilterDate label={el?'Από':'From'} value={from} onChange={setFrom}/><FilterDate label={el?'Έως':'To'} value={to} onChange={setTo}/></>}><FilterSelect label={el?'Κατηγορία':'Category'} value={category} onChange={setCategory}><option value="all">{el?'Όλες':'All'}</option>{[...new Set(rows.map(r=>r.category))].map(x=><option key={x} value={x}>{categoryLabel(x,el)}</option>)}</FilterSelect><FilterSelect label={el?'Τμήμα':'Department'} value={effectiveDepartment} onChange={setDepartment}>{!departmentScoped&&<option value="">{el?'Όλο το νοσοκομείο':'Whole hospital'}</option>}{allowedDepartments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</FilterSelect></FilterBar>
   {to<from&&<div className="inline-empty">{el?'Η τελική ημερομηνία πρέπει να είναι μετά την αρχική.':'End date must be after start date.'}</div>}
   {loading&&<div className="inline-empty">{el?'Υπολογισμός από Supabase…':'Calculating from Supabase…'}</div>}
   <div className="scroll-table"><table className="data-table sticky-table indicator-click-table"><thead><tr><th>{el?'Δείκτης':'Indicator'}</th><th>{el?'Κατηγορία':'Category'}</th><th>{el?'Αποτέλεσμα':'Result'}</th><th>{el?'Αριθμητής / Παρονομαστής':'Numerator / denominator'}</th><th>{el?'Πηγή / Έκδοση':'Source / Version'}</th><th>{el?'Κατάσταση':'Status'}</th></tr></thead><tbody>{pagedRows.map(r=><tr key={r.definitionId||r.id} tabIndex="0" role="button" onClick={()=>setSelected(r)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(r)}}}><td><strong>{el?r.titleEl:r.titleEn}</strong><small>{from} – {to}{r.calculation==='manual'?' · manual':''}</small></td><td>{categoryLabel(r.category,el)}</td><td className="indicator-result-cell"><strong>{r.value??'—'}</strong><small>{el?r.unit:(r.unitEn||r.unit)}</small></td><td>{r.evidence}</td><td>{r.source}<small>{r.version}</small></td><td><span className={`indicator-status ${r.status}`}>{statusText(r.status,el)}</span></td></tr>)}</tbody></table>{!loading&&!filtered.length&&<div className="registry-empty-state"><strong>{el?'Δεν υπάρχουν ενεργοί δείκτες':'No active indicators'}</strong><span>{el?'Δεν υπάρχουν δείκτες για τα ενεργά φίλτρα.':'No indicators match the active filters.'}</span></div>}</div>
   <RegistryPagination language={language} page={safePage} totalPages={totalPages} totalItems={filtered.length} pageSize={pageSize} onPageChange={setPage} onPageSizeChange={setPageSize}/>
  </section>
  {selected&&<IndicatorEvidenceDialog item={selected} history={trendFor(selected.id)} from={from} to={to} locale={locale} el={el} canManage={canManage} manualValue={manualValues[selected.id]??''} onManual={value=>{const next={...manualValues,[selected.id]:value};recalcWithManual(next);setSelected(current=>calculateCloudDefinition({...current,manualValue:value},{}))}} onApprove={approve} onClose={()=>setSelected(null)}/>} 
  {createOpen&&<IndicatorCreateDialog el={el} onClose={()=>setCreateOpen(false)} onSave={createDefinition}/>} 
 </Page>
}

function IndicatorCreateDialog({el,onClose,onSave}){
 const [v,setV]=useState({titleEl:'',titleEn:'',category:'quality',calculationType:'manual',numeratorMetric:'active_surveillance',denominatorMetric:'',multiplier:'1',unit:'',unitEn:'',targetValue:'',direction:'context',sourceAuthority:'Hospital-defined',effectiveFrom:today()});const [saving,setSaving]=useState(false);const set=(k,x)=>setV(s=>({...s,[k]:x}));const automatic=v.calculationType==='auto'
 async function save(){if(!v.titleEl.trim()||saving)return;setSaving(true);try{await onSave(v)}finally{setSaving(false)}}
 return <ObserverDialog width="wide" eyebrow={el?'Δείκτες':'Indicators'} title={el?'Νέος δείκτης':'New indicator'} subtitle={el?'Ορισμός οργανωτικού δείκτη για το συγκεκριμένο νοσοκομείο.':'Hospital-specific operational indicator definition.'} onClose={onClose} footer={<DialogActions onCancel={onClose} disabled={saving||!v.titleEl.trim()||(automatic&&!v.numeratorMetric)} onSave={save} saveLabel={saving?(el?'Αποθήκευση…':'Saving…'):(el?'Αποθήκευση':'Save')}/>}>
  <div className="entry-grid compact"><label className="field"><span>{el?'Τίτλος':'Title'} *</span><input value={v.titleEl} onChange={e=>set('titleEl',e.target.value)}/></label><label className="field"><span>{el?'Αγγλικός τίτλος':'English title'}</span><input value={v.titleEn} onChange={e=>set('titleEn',e.target.value)}/></label><label className="field"><span>{el?'Κατηγορία':'Category'}</span><select value={v.category} onChange={e=>set('category',e.target.value)}>{['surveillance','prevention','workforce','laboratory','quality'].map(x=><option key={x} value={x}>{categoryLabel(x,el)}</option>)}</select></label><label className="field"><span>{el?'Υπολογισμός':'Calculation'}</span><select value={v.calculationType} onChange={e=>set('calculationType',e.target.value)}><option value="manual">{el?'Χειροκίνητη τιμή':'Manual value'}</option><option value="auto">{el?'Αυτόματος από δεδομένα Limoxis':'Automatic from Limoxis data'}</option></select></label>{automatic&&<><label className="field"><span>{el?'Αριθμητής':'Numerator'}</span><select value={v.numeratorMetric} onChange={e=>set('numeratorMetric',e.target.value)}>{INDICATOR_METRICS.map(x=><option key={x} value={x}>{metricLabels[x]?.[el?0:1]||x}</option>)}</select></label><label className="field"><span>{el?'Παρονομαστής':'Denominator'}</span><select value={v.denominatorMetric} onChange={e=>set('denominatorMetric',e.target.value)}><option value="">{el?'Χωρίς παρονομαστή':'No denominator'}</option>{INDICATOR_METRICS.map(x=><option key={x} value={x}>{metricLabels[x]?.[el?0:1]||x}</option>)}</select></label><label className="field"><span>{el?'Πολλαπλασιαστής':'Multiplier'}</span><input type="number" step="any" value={v.multiplier} onChange={e=>set('multiplier',e.target.value)}/></label></>}<label className="field"><span>{el?'Μονάδα':'Unit'}</span><input value={v.unit} onChange={e=>set('unit',e.target.value)} placeholder="%, /1.000 patient-days…"/></label><label className="field"><span>{el?'Στόχος':'Target'}</span><input type="number" step="any" value={v.targetValue} onChange={e=>set('targetValue',e.target.value)} placeholder={el?'Προαιρετικό':'Optional'}/></label><label className="field"><span>{el?'Κατεύθυνση στόχου':'Target direction'}</span><select value={v.direction} onChange={e=>set('direction',e.target.value)}><option value="context">{el?'Πληροφοριακός':'Context only'}</option><option value="higher">{el?'Υψηλότερο είναι καλύτερο':'Higher is better'}</option><option value="lower">{el?'Χαμηλότερο είναι καλύτερο':'Lower is better'}</option></select></label><label className="field"><span>{el?'Πηγή / πρότυπο':'Source / standard'}</span><input value={v.sourceAuthority} onChange={e=>set('sourceAuthority',e.target.value)}/></label><ManualDateField className="field" label={el?'Ισχύει από':'Effective from'} value={v.effectiveFrom} onChange={x=>set('effectiveFrom',x)}/></div>
 </ObserverDialog>
}

function IndicatorEvidenceDialog({item,history,from,to,locale,el,canManage,manualValue,onManual,onApprove,onClose}){
 return <ObserverDialog eyebrow={el?'Λειτουργικός δείκτης':'Operational indicator'} title={el?item.titleEl:item.titleEn} subtitle={`${from} – ${to} · ${item.version}`} width="wide" onClose={onClose}>
  {item.calculation==='manual'&&<label className="field"><span>{el?'Χειροκίνητη τιμή περιόδου':'Manual period value'}</span><input type="number" step="any" value={manualValue} disabled={!canManage} onChange={e=>onManual(e.target.value)}/></label>}
  <div className="indicator-view-grid"><div className="indicator-view-field"><span>{el?'Τιμή':'Value'}</span><strong>{item.value??'—'} {el?item.unit:(item.unitEn||item.unit)}</strong></div><div className="indicator-view-field"><span>{el?'Στόχος':'Target'}</span><strong>{item.target==null?'—':`${item.direction==='higher'?'≥':item.direction==='lower'?'≤':''} ${item.target}`}</strong></div><div className="indicator-view-field"><span>{el?'Αριθμητής':'Numerator'}</span><strong>{item.numerator??'—'}</strong></div><div className="indicator-view-field"><span>{el?'Παρονομαστής':'Denominator'}</span><strong>{item.denominator??'—'}</strong></div></div>
  <div className="indicator-view-note"><Database size={15}/><div><strong>{el?'Τεκμηρίωση δεδομένων':'Data evidence'}</strong><span>{item.source} · {item.evidence} · {new Intl.DateTimeFormat(locale).format(new Date())}</span></div></div>
  <div className="table-wrap"><table className="data-table"><thead><tr><th>{el?'Αποθηκευμένη περίοδος':'Saved period'}</th><th>{el?'Τιμή':'Value'}</th><th>{el?'Κατάσταση':'Status'}</th><th/></tr></thead><tbody>{history.map(s=><tr key={s.id}><td>{s.period_start} – {s.period_end}</td><td>{s.value} {s.unit||''}</td><td><span className={`status-badge ${s.status==='approved'?'active':'temporary'}`}>{s.status}</span></td><td>{canManage&&s.status==='calculated'&&<Button variant="secondary" onClick={()=>onApprove(s.id)}>{el?'Έγκριση':'Approve'}</Button>}</td></tr>)}</tbody></table>{!history.length&&<div className="inline-empty">{el?'Δεν υπάρχουν αποθηκευμένα αποτελέσματα για αυτόν τον δείκτη.':'No saved results for this indicator.'}</div>}</div>
  <DialogActions><Button variant="secondary" onClick={onClose}>{el?'Κλείσιμο':'Close'}</Button></DialogActions>
 </ObserverDialog>
}