import { Activity, BarChart3, Beaker, BookOpenCheck, Building2, ClipboardCheck,  FileText, GraduationCap, HeartPulse, Home, LayoutDashboard, Pill, ShieldCheck, Sparkles, Stethoscope, Users } from 'lucide-react'
import { CAPABILITIES, MANAGEMENT_CAPABILITIES, ROLES, can, canAny } from '../core/permissions/roles'

export const navigation=[
  {to:'/',key:'dashboard',icon:LayoutDashboard,capability:CAPABILITIES.VIEW_DASHBOARD,excludeRoles:[ROLES.DEPARTMENT_MANAGER,ROLES.DEPARTMENT_USER]},{to:'/my-department',key:'myDepartment',icon:Home,capability:CAPABILITIES.VIEW_MY_DEPARTMENT,roles:[ROLES.DEPARTMENT_MANAGER,ROLES.DEPARTMENT_USER]},{to:'/my-profile',key:'myProfile',icon:Stethoscope,capability:CAPABILITIES.VIEW_MY_PROFILE},{to:'/surveillance',key:'surveillance',icon:Activity,capability:CAPABILITIES.VIEW_SURVEILLANCE},{to:'/laboratory',key:'laboratory',icon:Beaker,capability:CAPABILITIES.VIEW_LAB},{to:'/prevention',key:'prevention',icon:ShieldCheck,capability:CAPABILITIES.VIEW_PREVENTION},{to:'/controls',key:'controls',icon:ClipboardCheck,capability:CAPABILITIES.VIEW_CONTROLS},{to:'/quality',key:'quality',icon:HeartPulse,capability:CAPABILITIES.VIEW_QUALITY},{to:'/indicators',key:'indicators',group:'more',icon:BarChart3,capability:CAPABILITIES.VIEW_INDICATORS},{to:'/training',key:'training',group:'more',icon:GraduationCap,capability:CAPABILITIES.VIEW_TRAINING},{to:'/committees',key:'committees',group:'more',icon:BookOpenCheck,capability:CAPABILITIES.VIEW_COMMITTEES},{to:'/documents',key:'documents',group:'more',icon:FileText,capability:CAPABILITIES.VIEW_DOCUMENTS},{to:'/patients',key:'patients',icon:HeartPulse,capability:CAPABILITIES.VIEW_PATIENTS},{to:'/employees',key:'employees',icon:Users,capability:CAPABILITIES.VIEW_STAFF},{to:'/pharmacy',key:'pharmacy',group:'more',icon:Pill,capability:CAPABILITIES.VIEW_PHARMACY},{to:'/occupational-health',key:'occupationalHealth',group:'more',icon:Stethoscope,capability:CAPABILITIES.VIEW_OCCUPATIONAL_HEALTH},{to:'/lira',key:'lira',group:'more',icon:Sparkles,capability:CAPABILITIES.VIEW_LIRA},{to:'/management',key:'management',icon:Building2,capability:CAPABILITIES.MANAGE_ORGANIZATION,anyCapabilities:MANAGEMENT_CAPABILITIES},
]
<<<<<<< HEAD
export function navigationFor({role,addOns=[],customCapabilities=[],hasAssignments=false}={}){
  const allowed=navigation.filter(item=>item.excludeRoles&&item.excludeRoles.includes(role)?false:item.roles&&!item.roles.includes(role)?false:item.key==='controls'&&hasAssignments?true:item.anyCapabilities?canAny(role,item.anyCapabilities,addOns,customCapabilities):can(role,item.capability,addOns,customCapabilities))
  if(role===ROLES.PLATFORM_OWNER)return allowed
  return allowed
}
=======
export function navigationFor({role,addOns=[],customCapabilities=[],hasAssignments=false}={}){if(role===ROLES.PLATFORM_OWNER)return[{to:'/',key:'platformCenter',icon:LayoutDashboard,capability:CAPABILITIES.VIEW_DASHBOARD},{to:'/management',key:'management',icon:Building2,capability:CAPABILITIES.MANAGE_ORGANIZATION}];return navigation.filter(item=>item.excludeRoles&&item.excludeRoles.includes(role)?false:item.roles&&!item.roles.includes(role)?false:item.key==='controls'&&hasAssignments?true:item.anyCapabilities?canAny(role,item.anyCapabilities,addOns,customCapabilities):can(role,item.capability,addOns,customCapabilities))}
>>>>>>> 7e60ed2bd6d8c8868f98759981a67d58cd251ea7
