import { useState } from 'react'
import { CheckCircle2, Eye, EyeOff, ShieldCheck } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../../core/supabase/client'
import { Button } from '../../design-system/Button'

export function ActivateAccountPage(){
 const nav=useNavigate(),[password,setPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[show,setShow]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(null),[saving,setSaving]=useState(false)
 const rules={length:password.length>=12,upper:/[A-Z]/.test(password),lower:/[a-z]/.test(password),number:/\d/.test(password),symbol:/[^A-Za-z0-9]/.test(password),match:password===confirmPassword&&password.length>0},valid=Object.values(rules).every(Boolean)
 async function submit(e){e.preventDefault();if(!valid||saving)return;setSaving(true);setError('');try{const {data:sessionData}=await supabase.auth.getSession();if(!sessionData?.session)throw new Error('Η πρόσκληση δεν είναι πλέον έγκυρη. Ανοίξτε ξανά τον σύνδεσμο από το email.');const {data,error}=await supabase.functions.invoke('accept-account-invitation',{body:{password}});if(error||data?.error)throw new Error(data?.error||error?.message);await supabase.auth.signOut();setDone(data)}catch(err){setError(err.message||'Η ενεργοποίηση απέτυχε.')}finally{setSaving(false)}}
 return <div className="auth-layout activation-layout"><section className="auth-brand-panel"><div className="auth-brand"><span className="auth-logo">L+</span><div><strong>Limoxis Observer</strong><span>Secure account activation</span></div></div><div className="auth-value"><span className="eyebrow">ΑΣΦΑΛΗΣ ΕΝΕΡΓΟΠΟΙΗΣΗ</span><h1>Ο λογαριασμός σας ενεργοποιείται από εσάς.</h1><p>Ορίστε προσωπικό κωδικό πρόσβασης. Ο Platform Owner και ο Hospital Admin δεν βλέπουν τον κωδικό σας.</p></div></section><section className="auth-form-panel"><form className="login-card" onSubmit={submit}>{done?<><CheckCircle2 size={34}/><div className="login-heading"><h2>Ο λογαριασμός ενεργοποιήθηκε</h2><p>Όνομα χρήστη: <strong>{done.username}</strong></p></div><Button type="button" onClick={()=>nav('/login')}>Μετάβαση στη σύνδεση</Button></>:<><div className="login-heading"><span>Αποδοχή πρόσκλησης</span><h2>Ορισμός κωδικού πρόσβασης</h2><p>Ο κωδικός πρέπει να πληροί όλες τις απαιτήσεις ασφαλείας.</p></div><label className="field"><span>Νέος κωδικός</span><div className="password-input-wrap"><input className="input" type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/><button type="button" className="password-visibility" onClick={()=>setShow(v=>!v)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label><label className="field"><span>Επιβεβαίωση κωδικού</span><input className="input" type={show?'text':'password'} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} autoComplete="new-password"/></label><div className="password-policy"><ShieldCheck size={17}/><div><strong>Πολιτική κωδικού</strong><span className={rules.length?'ok':''}>12+ χαρακτήρες</span><span className={rules.upper&&rules.lower?'ok':''}>Κεφαλαίο και πεζό γράμμα</span><span className={rules.number?'ok':''}>Τουλάχιστον ένας αριθμός</span><span className={rules.symbol?'ok':''}>Τουλάχιστον ένα σύμβολο</span><span className={rules.match?'ok':''}>Οι κωδικοί ταιριάζουν</span></div></div>{error&&<div className="form-error">{error}</div>}<Button type="submit" disabled={!valid||saving}>{saving?'Ενεργοποίηση…':'Ενεργοποίηση λογαριασμού'}</Button></>}</form></section></div>
}
