import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Languages, ShieldCheck } from 'lucide-react'
import { Button } from '../../design-system/Button'
import { supabase } from '../../core/supabase/client'
import { useLanguage } from '../../core/i18n/LanguageContext'

export function ForgotAccessPage(){
 const {language,setLanguage}=useLanguage(),greek=language==='el'
 const [email,setEmail]=useState(''),[done,setDone]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(false)
 async function submit(e){e.preventDefault();if(loading)return;setLoading(true);setError('');setDone(false);try{const {data,error:invokeError}=await supabase.functions.invoke('request-account-recovery',{body:{email:email.trim()}});if(invokeError||data?.error)throw new Error(data?.error||invokeError?.message);setDone(true)}catch{setError(greek?'Δεν ήταν δυνατή η αποστολή αυτή τη στιγμή. Δοκιμάστε ξανά σε λίγο.':'The request could not be sent right now. Please try again shortly.')}finally{setLoading(false)}}
 return <div className="auth-layout"><section className="auth-brand-panel"><div className="auth-brand"><span className="auth-logo">L</span><div><strong>Limoxis Observer</strong><span>{greek?'Ασφαλής ανάκτηση πρόσβασης':'Secure account recovery'}</span></div></div><div className="auth-value"><span className="eyebrow">{greek?'ΑΣΦΑΛΗΣ ΑΝΑΚΤΗΣΗ':'SECURE RECOVERY'}</span><h1>{greek?'Ανάκτηση πρόσβασης.':'Recover access.'}</h1><p>{greek?'Οι οδηγίες αποστέλλονται μόνο στο email που είναι δηλωμένο στον λογαριασμό. Για λόγους ασφάλειας, η οθόνη δεν αποκαλύπτει αν ένα email είναι καταχωρημένο.':'Instructions are sent only to the email registered to the account. For security, this screen never reveals whether an email is registered.'}</p></div><div className="auth-trust"><span><ShieldCheck size={17}/>{greek?'Ασφαλής διαδικασία επαναφοράς':'Secure reset workflow'}</span></div></section><section className="auth-form-panel"><button type="button" className="auth-language" onClick={()=>setLanguage(greek?'en':'el')}><Languages size={16}/>{greek?'EN':'EL'}</button><form className="login-card" onSubmit={submit}><div className="login-heading"><span>{greek?'Ανάκτηση λογαριασμού':'Account recovery'}</span><h2>{greek?'Επαναφορά κωδικού πρόσβασης':'Reset your password'}</h2><p>{greek?'Αν δεν θυμάστε το username, μπορείτε επίσης να συνδεθείτε με το δηλωμένο email σας αφού ολοκληρώσετε την επαναφορά.':'If you do not remember your username, you can also sign in with your registered email after completing the reset.'}</p></div><label className="field"><span>{greek?'Email λογαριασμού':'Account email'}</span><input className="input" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label>{error&&<div className="form-error" role="alert">{error}</div>}{done&&<div className="setup-note" role="status">{greek?'Αν το email είναι καταχωρημένο, έχει σταλεί μήνυμα με οδηγίες επαναφοράς.':'If the email is registered, a password reset message has been sent.'}</div>}<Button type="submit" disabled={loading}>{loading?(greek?'Αποστολή…':'Sending…'):(greek?'Αποστολή οδηγιών':'Send reset instructions')}</Button><Link className="auth-back-link" to="/login">{greek?'Επιστροφή στη σύνδεση':'Back to sign in'}</Link></form></section></div>
}
