import { useState } from 'react'
import { Eye, EyeOff, Languages, ShieldCheck } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { Button } from '../../design-system/Button'
import { supabase } from '../../core/supabase/client'
import { useLanguage } from '../../core/i18n/LanguageContext'

export function ResetPasswordPage(){
 const nav=useNavigate(),{language,setLanguage}=useLanguage(),greek=language==='el'
 const [password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[show,setShow]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false)
 const rules={length:password.length>=12&&password.length<=128,upper:/[A-Z]/.test(password),lower:/[a-z]/.test(password),number:/\d/.test(password),symbol:/[^A-Za-z0-9]/.test(password),match:password===confirm&&password.length>0},valid=Object.values(rules).every(Boolean)
 async function submit(e){e.preventDefault();if(!valid||saving)return;setSaving(true);setError('');try{const {data:sessionData}=await supabase.auth.getSession();if(!sessionData?.session)throw new Error('RECOVERY_SESSION_MISSING');const {error:updateError}=await supabase.auth.updateUser({password});if(updateError)throw updateError;await supabase.auth.signOut();nav('/login',{replace:true})}catch(err){const missing=String(err?.message||'').includes('RECOVERY_SESSION_MISSING');setError(missing?(greek?'Ο σύνδεσμος επαναφοράς δεν είναι πλέον ενεργός. Ζητήστε νέο email επαναφοράς.':'This reset link is no longer active. Request a new password reset email.'):(greek?'Δεν ήταν δυνατή η αλλαγή του κωδικού. Ζητήστε νέο σύνδεσμο επαναφοράς και δοκιμάστε ξανά.':'The password could not be changed. Request a new reset link and try again.'))}finally{setSaving(false)}}
 return <div className="auth-layout"><section className="auth-brand-panel"><div className="auth-brand"><span className="auth-logo">L</span><div><strong>Limoxis Observer</strong><span>{greek?'Ασφαλής επαναφορά κωδικού':'Secure password reset'}</span></div></div><div className="auth-value"><span className="eyebrow">{greek?'ΝΕΟΣ ΚΩΔΙΚΟΣ':'NEW PASSWORD'}</span><h1>{greek?'Ορισμός νέου κωδικού πρόσβασης.':'Set a new password.'}</h1><p>{greek?'Ο νέος κωδικός αποθηκεύεται απευθείας στον λογαριασμό σας και δεν είναι ορατός στους διαχειριστές.':'Your new password is stored directly on your account and is never visible to administrators.'}</p></div></section><section className="auth-form-panel"><button type="button" className="auth-language" onClick={()=>setLanguage(greek?'en':'el')}><Languages size={16}/>{greek?'EN':'EL'}</button><form className="login-card" onSubmit={submit}><div className="login-heading"><span>{greek?'Επαναφορά πρόσβασης':'Access recovery'}</span><h2>{greek?'Νέος κωδικός πρόσβασης':'New password'}</h2><p>{greek?'Ο κωδικός πρέπει να πληροί όλες τις απαιτήσεις ασφαλείας.':'Your password must meet all security requirements.'}</p></div><label className="field"><span>{greek?'Νέος κωδικός':'New password'}</span><div className="password-input-wrap"><input className="input" type={show?'text':'password'} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" className="password-visibility" onClick={()=>setShow(v=>!v)} aria-label={show?(greek?'Απόκρυψη κωδικού':'Hide password'):(greek?'Εμφάνιση κωδικού':'Show password')}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label><label className="field"><span>{greek?'Επιβεβαίωση κωδικού':'Confirm password'}</span><input className="input" type={show?'text':'password'} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><div className="password-policy"><ShieldCheck size={17}/><div><strong>{greek?'Πολιτική κωδικού':'Password policy'}</strong><span className={rules.length?'ok':''}>{greek?'12–128 χαρακτήρες':'12–128 characters'}</span><span className={rules.upper&&rules.lower?'ok':''}>{greek?'Κεφαλαίο και πεζό γράμμα':'Uppercase and lowercase letter'}</span><span className={rules.number?'ok':''}>{greek?'Τουλάχιστον ένας αριθμός':'At least one number'}</span><span className={rules.symbol?'ok':''}>{greek?'Τουλάχιστον ένα σύμβολο':'At least one symbol'}</span><span className={rules.match?'ok':''}>{greek?'Οι κωδικοί ταιριάζουν':'Passwords match'}</span></div></div>{error&&<div className="form-error" role="alert">{error}</div>}<Button type="submit" disabled={!valid||saving}>{saving?(greek?'Αποθήκευση…':'Saving…'):(greek?'Αλλαγή κωδικού':'Change password')}</Button><Link className="auth-back-link" to="/forgot-access">{greek?'Ζητήστε νέο σύνδεσμο επαναφοράς':'Request a new reset link'}</Link></form></section></div>
}
