const day=value=>value?String(value).slice(0,10):null
const norm=value=>String(value||'').trim().toLocaleLowerCase('en-US')
const inRange=(value,from,to)=>{const d=day(value);return Boolean(d)&&(!from||d>=from)&&(!to||d<=to)}
const overlap=(start,end,point)=>{const d=day(point);return Boolean(d)&&(!start||day(start)<=d)&&(!end||day(end)>=d)}

export function buildOutbreakLineList(data={}, {from=null,to=null,department='all',organism=null}={}){
 const labs=(data.laboratory||[]).filter(x=>inRange(x.collectedAt||x.resultedAt,from,to)&&(!department||department==='all'||x.department===department)&&(!organism||norm(x.organism).includes(norm(organism))))
 const hai=data.haiClassifications||[],devices=data.devices||[],isolations=data.isolations||[]
 const rows=labs.map(lab=>{const eventDate=lab.collectedAt||lab.resultedAt;const patientHai=hai.filter(x=>x.patientId&&x.patientId===lab.patientId&&inRange(x.classifiedAt||x.signalDate,from,to));const exposure=devices.filter(x=>x.patientId&&x.patientId===lab.patientId&&overlap(x.insertedAt,x.removedAt,eventDate));const isolation=isolations.filter(x=>x.patientId&&x.patientId===lab.patientId&&overlap(x.startedAt,x.endedAt,eventDate));return {recordKey:lab.resultId||lab.id,patientKey:lab.patientId||null,eventDate:day(eventDate),department:lab.department,organism:lab.organism||null,specimenType:lab.specimenType||null,resistanceClass:lab.resistance||null,hai:patientHai.map(x=>({id:x.id,type:x.haiType,date:day(x.classifiedAt||x.signalDate),definitionSet:x.definitionSet||null,definitionVersion:x.definitionVersion||null})),devices:exposure.map(x=>({id:x.id,type:x.deviceType,insertedAt:day(x.insertedAt),removedAt:day(x.removedAt)})),isolation:isolation.map(x=>({id:x.id,status:x.status,startedAt:day(x.startedAt),endedAt:day(x.endedAt)})),facts:{person:Boolean(lab.patientId),place:Boolean(lab.department&&lab.department!=='—'),time:Boolean(eventDate)},hypothesis:null,transmissionConfirmed:false,outbreakConfirmed:false}})
 return {method:'deterministic_outbreak_line_list',scope:{from,to,department,organism},rows,summary:{records:rows.length,uniquePatients:new Set(rows.map(x=>x.patientKey).filter(Boolean)).size,departments:[...new Set(rows.map(x=>x.department).filter(Boolean))],firstEvent:rows.map(x=>x.eventDate).filter(Boolean).sort()[0]||null,lastEvent:rows.map(x=>x.eventDate).filter(Boolean).sort().at(-1)||null},guardrails:{outbreakDeclaration:false,transmissionInference:false,missingExposureInference:false,hypothesisAsFact:false,note:'Line-list organizes observed person-place-time facts and linked records; epidemiological review is required.'}}
}

export function buildOutbreakEvidenceTrail(lineList){return (lineList?.rows||[]).map(row=>({recordKey:row.recordKey,evidence:[{source:'microbiology_results',id:row.recordKey,date:row.eventDate},...row.hai.map(x=>({source:'hai_classifications',id:x.id,date:x.date})),...row.devices.map(x=>({source:'surveillance_devices',id:x.id,date:x.insertedAt})),...row.isolation.map(x=>({source:'isolation_episodes',id:x.id,date:x.startedAt}))]}))}


export function buildOutbreakTimeline(lineList){const events=[];for(const row of lineList?.rows||[]){events.push({date:row.eventDate,type:'microbiology',recordKey:row.recordKey,patientKey:row.patientKey,department:row.department,label:[row.organism,row.specimenType].filter(Boolean).join(' · ')});for(const h of row.hai)events.push({date:h.date,type:'hai',recordKey:h.id,patientKey:row.patientKey,department:row.department,label:h.type,definitionSet:h.definitionSet,definitionVersion:h.definitionVersion});for(const d of row.devices)events.push({date:d.insertedAt,type:'device',recordKey:d.id,patientKey:row.patientKey,department:row.department,label:d.type});for(const i of row.isolation)events.push({date:i.startedAt,type:'isolation',recordKey:i.id,patientKey:row.patientKey,department:row.department,label:i.status})}return events.filter(x=>x.date).sort((a,b)=>a.date.localeCompare(b.date)||a.type.localeCompare(b.type))}

export function evaluateOutbreakCaseDefinition(lineList,definition={}){const version=definition.version||null,definitionId=definition.id||null;return {definition:{id:definitionId,version,label:definition.label||null},cases:(lineList?.rows||[]).map(row=>{const checks={organism:definition.organism?norm(row.organism)===norm(definition.organism):null,department:definition.department?row.department===definition.department:null,specimen:definition.specimen?norm(row.specimenType)===norm(definition.specimen):null,from:definition.from?row.eventDate>=definition.from:null,to:definition.to?row.eventDate<=definition.to:null};const required=Object.values(checks).filter(x=>x!==null);const complete=Boolean(definitionId&&version&&required.length);return {recordKey:row.recordKey,patientKey:row.patientKey,checks,classification:complete&&required.every(Boolean)?'meets_machine_readable_criteria':'unclassified',humanValidationRequired:true,finalClassification:null}}),guardrails:{requiresVersionedDefinition:true,humanValidationRequired:true,autonomousConfirmedCase:false,clinicalDiagnosis:false,note:'Machine-readable criteria may identify records meeting explicit investigation criteria; suspected/probable/confirmed status remains a governed human decision.'}}
}
