import {forwardRef} from 'react'
import {buildOutbreakClosureReadiness,latestCaseReviews} from './liraOutbreakClosure'
const statusLabel=(s,en)=>({draft:en?'Draft':'Πρόχειρη',active:en?'Active':'Ενεργή',closed:en?'Closed':'Κλειστή'}[s]||s)
const actionStatusLabel=(s,en)=>({open:en?'Open':'Ανοικτή',in_progress:en?'In progress':'Σε εξέλιξη',verification:en?'Verification':'Σε επαλήθευση',closed:en?'Closed':'Κλειστή'}[s]||s)
const classificationLabel=(c,en)=>({suspected:en?'Suspected':'Πιθανό',probable:en?'Probable':'Πιθανολογούμενο',confirmed:en?'Confirmed':'Επιβεβαιωμένο',excluded:en?'Excluded':'Αποκλεισμένο'}[c]||c)
export const LiraOutbreakReport=forwardRef(function LiraOutbreakReport({investigation,lineList,timeline,reviews,actions,events,language='el'},ref){
 const en=language==='en',closure=buildOutbreakClosureReadiness({lineList,caseReviews:reviews,actions,events}),latest=latestCaseReviews(reviews),closureEvent=[...events].reverse().find(e=>e.event_type==='decision'&&e.payload?.action==='closure_review')
 return <article ref={ref} className="analysis-print-frame"><div className="analysis-report"><div className="analysis-section-title"><div><h2>{en?'Outbreak Investigation Report':'Αναφορά Διερεύνησης Πιθανής Έξαρσης'}</h2><p>{investigation.title} · {investigation.organism||'—'} · {investigation.scope_from||'—'} → {investigation.scope_to||'—'}</p></div><div className="analysis-report-badges"><span className="status-badge">{statusLabel(investigation.status,en)}</span></div></div>
 <section className="analysis-chart-card"><header><strong>{en?'Governance & scope':'Διακυβέρνηση & πεδίο'}</strong></header><div className="analysis-summary-grid"><div><span>{en?'Case definition':'Ορισμός περιστατικού'}</span><strong>{investigation.definition_id?investigation.definition_id+' · '+investigation.definition_version:'—'}</strong></div><div><span>{en?'Candidates':'Υποψήφια'}</span><strong>{closure.counts.candidates}</strong></div><div><span>{en?'Human reviewed':'Ανθρώπινα αξιολογημένα'}</span><strong>{closure.counts.reviewed}</strong></div><div><span>{en?'Evidence events':'Συμβάντα τεκμηρίωσης'}</span><strong>{closure.counts.evidenceEvents}</strong></div></div></section>
 <section className="analysis-chart-card"><header><strong>{en?'Case classifications':'Ταξινομήσεις περιστατικών'}</strong></header><table><thead><tr><th>{en?'Record':'Εγγραφή'}</th><th>{en?'Classification':'Ταξινόμηση'}</th><th>{en?'Reviewed at':'Ημ. αξιολόγησης'}</th><th>{en?'Rationale':'Αιτιολόγηση'}</th></tr></thead><tbody>{latest.map(r=><tr key={r.id}><td>{r.record_key}</td><td>{classificationLabel(r.classification,en)}</td><td>{r.reviewed_at}</td><td>{r.rationale}</td></tr>)}</tbody></table></section>
 <section className="analysis-chart-card"><header><strong>{en?'Person–place–time timeline':'Χρονογραμμή person–place–time'}</strong></header><table><thead><tr><th>{en?'Date':'Ημερομηνία'}</th><th>{en?'Type':'Τύπος'}</th><th>{en?'Department':'Τμήμα'}</th><th>{en?'Evidence':'Τεκμηρίωση'}</th></tr></thead><tbody>{timeline.map((x,i)=><tr key={x.type+'-'+i}><td>{x.date}</td><td>{x.type}</td><td>{x.department||'—'}</td><td>{x.label||'—'}</td></tr>)}</tbody></table></section>
 <section className="analysis-chart-card"><header><strong>{en?'IPC / CAPA actions':'Ενέργειες IPC / CAPA'}</strong></header><table><thead><tr><th>{en?'Action':'Ενέργεια'}</th><th>{en?'Owner':'Υπεύθυνος'}</th><th>{en?'Due':'Προθεσμία'}</th><th>{en?'Status':'Κατάσταση'}</th></tr></thead><tbody>{actions.map(a=><tr key={a.id}><td>{a.code} · {a.title}</td><td>{a.owner_label||'—'}</td><td>{a.due_date||'—'}</td><td>{actionStatusLabel(a.status,en)}</td></tr>)}</tbody></table></section>
 <section className="analysis-chart-card"><header><strong>{en?'Evidence & decisions':'Τεκμηρίωση & αποφάσεις'}</strong></header>{events.map(e=><div key={e.id}><strong>{e.event_type}</strong> · <span>{e.created_at}</span><p>{e.payload?.text||e.payload?.action||e.payload?.to||'—'}</p></div>)}</section>
 <section className="analysis-chart-card"><header><strong>{en?'Closure':'Κλείσιμο'}</strong></header><p>{closureEvent?.payload?.text|| (en?'No closure rationale recorded.':'Δεν έχει καταγραφεί αιτιολόγηση κλεισίματος.')}</p><p><strong>{en?'Readiness at report time:':'Ετοιμότητα κατά την αναφορά:'}</strong> {closure.ready?(en?'complete':'πλήρης'):(en?'open items remain':'υπάρχουν εκκρεμότητες')}</p></section>
 <p className="muted">{en?'This report summarizes governed investigation records. It does not independently establish causality or transmission.':'Η αναφορά συνοψίζει τις ελεγχόμενες εγγραφές της διερεύνησης. Δεν τεκμηριώνει αυτοτελώς αιτιότητα ή μετάδοση.'}</p></div></article>
})
