import {supabase} from '../../core/supabase/client'
export async function listOutbreakInvestigations(organizationId){const {data,error}=await supabase.from('lira_outbreak_investigations').select('*').eq('organization_id',organizationId).order('updated_at',{ascending:false});if(error)throw error;return data||[]}
export async function createOutbreakInvestigation(organizationId,input){const row={organization_id:organizationId,title:input.title,organism:input.organism||null,department_id:input.departmentId||null,status:'draft',definition_id:input.definition?.id||null,definition_version:input.definition?.version||null,definition_json:input.definition||{},scope_from:input.from||null,scope_to:input.to||null};const {data,error}=await supabase.from('lira_outbreak_investigations').insert(row).select().single();if(error)throw error;return data}
export async function updateOutbreakInvestigation(id,patch){const row={...patch,updated_at:new Date().toISOString()};const {data,error}=await supabase.from('lira_outbreak_investigations').update(row).eq('id',id).select().single();if(error)throw error;return data}
export async function appendOutbreakInvestigationEvent(organizationId,investigationId,eventType,payload){const {data,error}=await supabase.from('lira_outbreak_investigation_events').insert({organization_id:organizationId,investigation_id:investigationId,event_type:eventType,payload}).select().single();if(error)throw error;return data}
export async function loadOutbreakInvestigationEvents(investigationId){const {data,error}=await supabase.from('lira_outbreak_investigation_events').select('*').eq('investigation_id',investigationId).order('created_at',{ascending:true});if(error)throw error;return data||[]}

export async function loadOutbreakCaseReviews(investigationId){const {data,error}=await supabase.from('lira_outbreak_case_reviews').select('*').eq('investigation_id',investigationId).order('reviewed_at',{ascending:true});if(error)throw error;return data||[]}
export async function createOutbreakCaseReview(organizationId,investigationId,input){const {data,error}=await supabase.from('lira_outbreak_case_reviews').insert({organization_id:organizationId,investigation_id:investigationId,record_key:input.recordKey,patient_id:input.patientId||null,classification:input.classification,rationale:input.rationale,supersedes_review_id:input.supersedesReviewId||null}).select().single();if(error)throw error;return data}

function outbreakCapaCode(){return 'CAPA-OUT-'+new Date().toISOString().replace(/\D/g,'').slice(2,14)}
export async function loadOutbreakActions(organizationId,investigationId){const {data,error}=await supabase.from('quality_capa_actions').select('id,code,title,action_type,priority,status,description,owner_id,owner_label,due_date,effectiveness_due,effectiveness_status,created_at,updated_at').eq('organization_id',organizationId).eq('source_type','outbreak_investigation').eq('source_id',investigationId).order('due_date',{ascending:true,nullsFirst:false});if(error)throw error;return data||[]}
export async function createOutbreakAction(organizationId,investigationId,input){const {data,error}=await supabase.from('quality_capa_actions').insert({organization_id:organizationId,code:outbreakCapaCode(),title:input.title.trim(),source_type:'outbreak_investigation',source_id:investigationId,action_type:input.actionType||'corrective',priority:input.priority||'medium',status:'open',description:input.description?.trim()||null,owner_label:input.owner?.trim()||null,due_date:input.dueDate||null,effectiveness_status:'pending'}).select().single();if(error)throw error;return data}
export async function updateOutbreakActionStatus(organizationId,actionId,status){const {data,error}=await supabase.from('quality_capa_actions').update({status,updated_at:new Date().toISOString()}).eq('organization_id',organizationId).eq('id',actionId).eq('source_type','outbreak_investigation').select().single();if(error)throw error;return data}
