import { useEffect,useMemo,useState } from 'react'
import { ClipboardCheck,Droplets,Recycle,ShieldCheck,Trash2 } from 'lucide-react'
import { useNavigate,useParams } from 'react-router-dom'
import { Page } from '../../design-system/Page'
import { EntityRecordShell } from '../../design-system/EntityRecordShell'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { bundleRows,wasteRows } from './preventionDemoData'
import { WHO_MOMENTS } from './WhoHandHygieneModal'
import { loadHandHygieneSessions } from './handHygieneCloudService'
import { loadAntisepticRecords } from './antisepticCloudService'
import { useTenant } from '../../core/tenant/TenantContext'
import { useRecordSequenceNavigation } from '../../core/navigation/useRecordSequenceNavigation'
import { CAPABILITIES,can } from '../../core/permissions/roles'
import { wasteCategoryTone } from './wasteVisuals'
import { antisepticMethodLabel,isAbhrProduct } from './AntisepticEntryModal'
import { getBundleTemplate } from './bundleTemplates'
import { GovernedReasonDialog } from '../../design-system/GovernedReasonDialog'
import { useAuth } from '../../core/auth/AuthContext'
import { auditActorFromAuth } from '../../core/audit/actor'
import { voidRecord as applyGovernedVoid } from '../../core/audit/governedLifecycle'
import { PrintExportActions } from '../../design-system/PrintExportActions'
import { downloadRecordJson } from '../../core/export/recordExport'

const sources={waste:wasteRows,bundles:bundleRows}
const icons={handHygiene:ShieldCheck,waste:Recycle,antiseptics:Droplets,bundles:ClipboardCheck}
const labels={handHygiene:['Υγιεινή Χεριών','Hand Hygiene'],waste:['Απόβλητα','Waste'],antiseptics:['Κατανάλωση αντισηπτικών','Antiseptic consumption'],bundles:['Bundles πρόληψης','Prevention Bundles']}

export function PreventionRecordPage(){
 const {recordType,recordId}=useParams();const navigate=useNavigate();const {locale,t,language}=useLanguage();const en=language==='en';const {notify,notifyError}=useFeedback();const {role,membership,canAccessRecord,tenant}=useTenant();const {profile,user}=useAuth();const actor=useMemo(()=>auditActorFromAuth({profile,user}),[profile,user]);const [voidOpen,setVoidOpen]=useState(false);const [cloudRecord,setCloudRecord]=useState(null);const cloudType=recordType==='handHygiene'||recordType==='antiseptics';const [loading,setLoading]=useState(cloudType)
 useEffect(()=>{
  if(!cloudType){setLoading(false);setCloudRecord(null);return}
  if(!tenant?.id){setCloudRecord(null);setLoading(false);return}
  let active=true
  setLoading(true)
  const loader=recordType==='handHygiene'?loadHandHygieneSessions:loadAntisepticRecords
  loader(tenant.id).then(rows=>{if(active)setCloudRecord(rows.find(x=>x.id===recordId)||null)}).catch(error=>{if(active){setCloudRecord(null);notifyError(error,'load',{operation:recordType==='handHygiene'?'hand_hygiene_record_load':'antiseptic_record_load'})}}).finally(()=>{if(active)setLoading(false)})
  return()=>{active=false}
 },[recordType,recordId,tenant?.id])
 const record=cloudType?cloudRecord:(sources[recordType]||[]).find(x=>x.id===recordId)
 const recordNavigation=useRecordSequenceNavigation({registry:`prevention-${recordType}`,currentId:recordId,pathForId:id=>`/prevention/${recordType}/${id}?fromTab=${recordType}`})
 const recordInScope=!record||canAccessRecord({...record,department:record.departmentEl||record.department})
 if(loading)return <Page title={en?'Prevention Center':'Κέντρο Πρόληψης'}><div className="inline-empty">{en?'Loading record…':'Φόρτωση εγγραφής…'}</div></Page>
 if(!record)return <Page title={en?'Prevention Center':'Κέντρο Πρόληψης'}><div className="inline-empty">{en?'Record not found.':'Δεν βρέθηκε η εγγραφή.'}</div></Page>
 if(!recordInScope)return <Page title={en?'Prevention Center':'Κέντρο Πρόληψης'}><div className="inline-empty">{en?'You do not have access to this record.':'Δεν έχετε πρόσβαση σε αυτή την εγγραφή.'}</div></Page>
 const addOns=membership?.capabilities??[],custom=membership?.customCapabilities??[]
 const cap=recordType==='handHygiene'?CAPABILITIES.RECORD_HAND_HYGIENE:recordType==='waste'?CAPABILITIES.RECORD_WASTE:recordType==='antiseptics'?CAPABILITIES.RECORD_ANTISEPTIC:CAPABILITIES.RECORD_PREVENTION_BUNDLE
 const canDelete=!cloudType&&can(role,cap,addOns,custom)
 function voidRecord(reason){
  const source=sources[recordType]||[]
  const index=source.findIndex(x=>x.id===recordId)
  if(index<0)return
  source[index]=applyGovernedVoid(source[index],{actor,reason,historyKey:'revisionHistory'})
  setVoidOpen(false)
  notify(en?'Record voided and retained in history.':'Η εγγραφή ακυρώθηκε και διατηρήθηκε στο ιστορικό.','success')
  navigate(`/prevention?tab=${recordType}`)
 }
 const Icon=icons[recordType]||ShieldCheck
 const fmtDate=v=>v?new Intl.DateTimeFormat(locale).format(new Date(`${v}T12:00:00`)):'—'
 const isWaste=recordType==='waste'
 const isAntiseptic=recordType==='antiseptics'
 const wasteCategory=record.wasteType||record.type
 const recordTitle=recordType==='handHygiene'?`WHO Observation · ${fmtDate(record.date)}`:isWaste?`${en?'Waste measurement':'Μέτρηση αποβλήτων'} · ${fmtDate(record.date)}`:isAntiseptic?`${en?'Antiseptic consumption':'Κατανάλωση αντισηπτικού'} · ${record.period||''}`:recordType==='bundles'?`${record.templateName||record.bundle} · ${record.date||record.period||''}`:record.id
 const recordSubtitle=isWaste?`${record.departmentEl||''} · ${wasteCategory||''}`:isAntiseptic?`${record.departmentEl||''} · ${record.product||''}`:recordType==='bundles'?`${record.departmentEl||''} · v${record.templateVersion||'1.0'}`:(record.departmentEl||'')
 const recordStatus=isWaste?<span className={`waste-category-badge ${wasteCategoryTone(wasteCategory)}`}>{wasteCategory}</span>:isAntiseptic?<span className={`antiseptic-abhr-badge ${record.indicatorEligible!==false&&isAbhrProduct(record.product)?'active':'informative'}`}>{record.indicatorEligible!==false&&isAbhrProduct(record.product)?(en?'ABHR · included in indicator':'ABHR · στον δείκτη'):(en?'Outside ABHR indicator':'Εκτός δείκτη ABHR')}</span>:null
 return <Page fill><EntityRecordShell className="prevention-record-shell workspace-fill" avatar={<Icon size={19}/>} eyebrow={(labels[recordType]?.[en?1:0])||(en?'Prevention':'Πρόληψη')} title={recordTitle} subtitle={recordSubtitle} status={recordStatus} recordNavigation={recordNavigation} headerActions={<>{canDelete&&<button type="button" className="entity-record-icon-button danger" title={en?'Void record':'Ακύρωση εγγραφής'} aria-label={en?'Void record':'Ακύρωση εγγραφής'} onClick={()=>setVoidOpen(true)}><Trash2 size={15}/></button>}<PrintExportActions onExport={()=>downloadRecordJson(record,{filename:record.id})}/></>} tabs={[]} activeTab="" onTabChange={()=>{}}>
   <div className="record-section">{recordType==='handHygiene'?<HandHygieneDetails record={record} fmtDate={fmtDate} language={language}/>:recordType==='waste'?<WasteDetails record={record} fmtDate={fmtDate} language={language} locale={locale}/>:recordType==='antiseptics'?<AntisepticDetails record={record} language={language} locale={locale}/>:<BundleDetails record={record} t={t} language={language}/>}</div>
  <GovernedReasonDialog open={voidOpen} title={en?'Void record':'Ακύρωση εγγραφής'} description={en?'The record will not be physically deleted. It will be retained for traceability and removed from the active list.':'Η εγγραφή δεν θα διαγραφεί φυσικά. Θα διατηρηθεί για ιχνηλασιμότητα και θα αφαιρεθεί από την ενεργή λίστα.'} confirmLabel={en?'Void record':'Ακύρωση εγγραφής'} danger onCancel={()=>setVoidOpen(false)} onConfirm={voidRecord}/>
  </EntityRecordShell></Page>
}

function HandHygieneDetails({record,fmtDate,language}){
 const en=language==='en'
 const stats=record.whoStats||{opportunities:record.whoObservations?.length||record.observations||0,compliant:(record.whoObservations||[]).filter(x=>x.action==='HR'||x.action==='HW').length||record.compliant||0,compliance:record.rate||0,handRub:(record.whoObservations||[]).filter(x=>x.action==='HR').length,handWash:(record.whoObservations||[]).filter(x=>x.action==='HW').length,missed:(record.whoObservations||[]).filter(x=>x.action==='MISSED').length,professionals:(record.whoObservations||[]).reduce((sum,x)=>sum+(Number(x.professionalsCount)||1),0)}
 return <><div className="detail-grid quality-detail-grid"><D l={en?'Date':'Ημερομηνία'} v={fmtDate(record.date)}/><D l={en?'Department':'Τμήμα'} v={record.departmentEl}/><D l={en?'Observer':'Παρατηρητής'} v={record.observer}/><D l={en?'Time':'Ώρα'} v={`${record.session?.startTime||'—'} – ${record.session?.endTime||'—'}`}/></div><div className="who-live-summary record-who-summary"><div><span>{en?'Opportunities':'Ευκαιρίες'}</span><strong>{stats.opportunities}</strong></div><div><span>{en?'Professionals':'Επαγγελματίες'}</span><strong>{stats.professionals||'—'}</strong></div><div><span>HR</span><strong>{stats.handRub||0}</strong></div><div><span>HW</span><strong>{stats.handWash||0}</strong></div><div><span>Missed</span><strong>{stats.missed||0}</strong></div><div className="who-compliance"><span>{en?'Compliance':'Συμμόρφωση'}</span><strong>{stats.compliance}%</strong></div></div><div className="scroll-table"><table className="data-table sticky-table"><thead><tr><th>#</th><th>{en?'Professionals':'Επαγγελματίες'}</th><th>{en?'Category':'Κατηγορία'}</th><th>WHO Moment</th><th>{en?'Action':'Ενέργεια'}</th><th>{en?'Gloves':'Γάντια'}</th><th>{en?'Note':'Σημείωση'}</th></tr></thead><tbody>{(record.whoObservations||[]).map((x,i)=><tr key={x.id}><td>{i+1}</td><td><strong>{x.professionalsCount||1}</strong></td><td>{x.professionalCategory}</td><td>{(en?WHO_MOMENTS.find(m=>m.id===x.moment)?.labelEn:WHO_MOMENTS.find(m=>m.id===x.moment)?.label)||x.moment}</td><td><span className={`status-badge ${x.action==='MISSED'?'danger':'active'}`}>{x.action}</span></td><td>{x.gloves?(en?'Yes':'Ναι'):(en?'No':'Όχι')}</td><td>{x.notes||'—'}</td></tr>)}</tbody></table></div></>
}
function WasteDetails({record,fmtDate,language,locale}){
 const en=language==='en';const category=record.wasteType||record.type
 return <div className="waste-record-view"><section className="waste-record-primary"><div className="waste-record-section-heading"><div><span>{en?'MEASUREMENT':'ΜΕΤΡΗΣΗ'}</span><strong>{en?'Record details':'Στοιχεία καταγραφής'}</strong></div><span className={`waste-category-badge ${wasteCategoryTone(category)}`}>{category}</span></div><div className="waste-record-measurements"><div><span>{en?'Weight':'Βάρος'}</span><strong>{Number(record.weight).toLocaleString(locale)} <small>kg</small></strong></div><div><span>{en?'Containers':'Περιέκτες'}</span><strong>{record.containers}</strong></div><div><span>{en?'Patient-days':'Νοσηλευτικές ημέρες'}</span><strong>{record.patientDays||'—'}</strong></div><div className="waste-record-indicator"><span>{en?'Indicator':'Δείκτης'}</span><strong>{record.indicator!=null?Number(record.indicator).toLocaleString(locale):'—'}</strong><small>{en?'kg / 1,000 patient-days':'kg / 1.000 νοσηλευτικές ημέρες'}</small></div></div><div className="waste-record-meta-line"><span><b>{en?'Date':'Ημερομηνία'}</b>{fmtDate(record.date)}</span><span><b>{en?'Department':'Τμήμα'}</b>{record.departmentEl}</span><span><b>{en?'Responsible':'Υπεύθυνος'}</b>{record.responsible||record.createdBy||'—'}</span></div></section><section className="waste-record-trace"><div className="waste-record-section-heading"><div><span>{en?'TRACEABILITY':'ΙΧΝΗΛΑΣΙΜΟΤΗΤΑ'}</span><strong>{en?'Document & collection':'Παραστατικό & συλλογή'}</strong></div></div><div className="waste-trace-grid"><div><span>{en?'Document number':'Αριθμός παραστατικού'}</span><strong>{record.documentNumber||'—'}</strong></div><div><span>{en?'Collection company':'Εταιρεία συλλογής'}</span><strong>{record.collectionCompany||'—'}</strong></div>{record.patientDaysSource==='library'&&<div><span>{en?'Patient-days source':'Πηγή νοσηλευτικών ημερών'}</span><strong>{en?'Library':'Βιβλιοθήκη'}</strong></div>}</div></section>{record.notes&&<div className="record-note-card"><span>{en?'NOTES':'ΣΗΜΕΙΩΣΕΙΣ'}</span><p>{record.notes}</p></div>}</div>
}
function AntisepticDetails({record,language,locale}){
 const en=language==='en';const eligible=record.indicatorEligible!==false&&isAbhrProduct(`${record.product} ${record.productEn||''}`)
 return <div className="antiseptic-record-view"><section className="antiseptic-record-primary"><div className="antiseptic-record-heading"><div><span>{en?'CONSUMPTION':'ΚΑΤΑΝΑΛΩΣΗ'}</span><strong>{en?'Period details':'Στοιχεία περιόδου'}</strong></div><span className={`antiseptic-abhr-badge ${eligible?'active':'informative'}`}>{eligible?(en?'ABHR · Indicator active':'ABHR · Δείκτης ενεργός'):(en?'Outside ABHR indicator':'Εκτός δείκτη ABHR')}</span></div><div className="antiseptic-record-measurements"><div><span>{en?'Consumption':'Κατανάλωση'}</span><strong>{Number(record.litres).toLocaleString(locale)} <small>L</small></strong></div><div><span>{en?'Patient-days':'Νοσηλευτικές ημέρες'}</span><strong>{record.patientDays||'—'}</strong>{record.patientDaysSource==='library'&&<small>{en?'from Library':'από Βιβλιοθήκη'}</small>}</div><div className="antiseptic-record-indicator"><span>{en?'ABHR indicator':'Δείκτης ABHR'}</span><strong>{record.indicator!=null?Number(record.indicator).toLocaleString(locale):'—'}</strong><small>{en?'L / 1,000 patient-days':'L / 1.000 νοσηλευτικές ημέρες'}</small></div></div><div className="antiseptic-record-meta-line"><span><b>{en?'Period':'Περίοδος'}</b>{record.period||'—'}</span><span><b>{en?'Department':'Τμήμα'}</b>{record.departmentEl||'—'}</span><span><b>{en?'Product':'Προϊόν'}</b>{en?(record.productEn||record.product):record.product}</span></div></section><section className="antiseptic-record-trace"><div className="antiseptic-record-heading"><div><span>{en?'DOCUMENTATION':'ΤΕΚΜΗΡΙΩΣΗ'}</span><strong>{en?'Data source & traceability':'Πηγή δεδομένων & ιχνηλασιμότητα'}</strong></div></div><div className="antiseptic-trace-grid"><div><span>{en?'Source / method':'Πηγή / μέθοδος'}</span><strong>{antisepticMethodLabel(record.method,language)}</strong></div><div><span>{en?'Reference / document':'Αναφορά / παραστατικό'}</span><strong>{record.referenceNumber||'—'}</strong></div><div><span>{en?'Responsible':'Υπεύθυνος'}</span><strong>{record.responsible||record.createdBy||'—'}</strong></div></div><div className="antiseptic-governance-note"><strong>{eligible?(en?'Prevention indicator':'Δείκτης πρόληψης'):(en?'Consumption monitoring':'Παρακολούθηση κατανάλωσης')}</strong><span>{eligible?(en?'The value can be compared by period and department and correlated with hand-hygiene compliance.':'Η τιμή μπορεί να χρησιμοποιηθεί σε συγκρίσεις ανά περίοδο/τμήμα και σε συσχέτιση με τη συμμόρφωση Υγιεινής Χεριών.'):(en?'The value remains available for operational monitoring without being mixed into the ABHR indicator.':'Η τιμή παραμένει διαθέσιμη για λειτουργική παρακολούθηση, χωρίς να αναμιγνύεται με τον δείκτη ABHR.')}</span></div></section>{record.notes&&<div className="record-note-card"><span>{en?'NOTES':'ΣΗΜΕΙΩΣΕΙΣ'}</span><p>{record.notes}</p></div>}</div>
}
function BundleDetails({record,language}){
 const en=language==='en';const template=record.templateSnapshot||getBundleTemplate(record.templateId||record.bundle);const findings=record.findings||template.elements.filter(([id])=>record.answers?.[id]==='no').map(([id,label])=>({id,label,note:record.answerNotes?.[id]||''}))
 return <div className="bundle-record-view"><section className="bundle-record-summary"><div className="bundle-record-heading"><div><span>BUNDLE EXECUTION</span><strong>{record.templateName||template.name} · {record.templateTitle||template.title}</strong><small>{record.templateSource||template.source} · template v{record.templateVersion||template.version}</small></div><span className={`bundle-all-badge ${record.allOrNone?'passed':'failed'}`}>{record.allOrNone?'All-or-none ✓':'All-or-none ✕'}</span></div><div className="bundle-record-kpis"><div><span>Score</span><strong>{record.score}%</strong></div><div><span>{en?'Applicable':'Εφαρμόσιμα'}</span><strong>{record.applicableCount??'—'}</strong></div><div><span>{en?'Deviations':'Αποκλίσεις'}</span><strong>{record.failedCount??findings.length}</strong></div><div><span>{en?'Date':'Ημερομηνία'}</span><strong>{record.date||record.period||'—'}</strong></div></div><div className="bundle-record-meta"><span><b>{en?'Department':'Τμήμα'}</b>{record.departmentEl||'—'}</span><span><b>{en?'Shift':'Βάρδια'}</b>{record.shift||'—'}</span><span><b>{en?'Patient':'Ασθενής'}</b>{record.patientRef||'—'}</span><span><b>{en?'Device':'Συσκευή'}</b>{record.deviceRef||'—'}</span><span><b>{en?'Responsible':'Υπεύθυνος'}</b>{record.owner||record.createdBy||'—'}</span></div></section><section className="bundle-record-elements"><div className="bundle-record-heading"><div><span>{en?'ELEMENTS':'ΣΤΟΙΧΕΙΑ'}</span><strong>{en?'Bundle results':'Αποτελέσματα Bundle'}</strong></div></div><div className="bundle-detail-list">{template.elements.map(([id,label],i)=>{const value=record.answers?.[id];return <div className={`bundle-detail-row ${value==='no'?'failed':value==='yes'?'passed':'na'}`} key={id}><span className="bundle-detail-index">{i+1}</span><strong>{label}</strong><span className="bundle-detail-answer">{value==='yes'?(en?'Yes':'Ναι'):value==='no'?(en?'No':'Όχι'):value==='na'?(en?'N/A':'Μ/Ε'):'—'}</span>{value==='no'&&record.answerNotes?.[id]&&<small>{record.answerNotes[id]}</small>}</div>})}</div></section>{findings.length>0&&<section className="bundle-record-findings"><div className="bundle-record-heading"><div><span>{en?'DEVIATIONS':'ΑΠΟΚΛΙΣΕΙΣ'}</span><strong>{en?'Items for follow-up':'Σημεία για follow-up'}</strong></div></div>{findings.map(x=><div className="bundle-record-finding" key={x.id}><strong>{x.label}</strong><span>{x.note||(en?'Investigation / corrective action required.':'Απαιτείται διερεύνηση / διορθωτική ενέργεια.')}</span></div>)}</section>}{record.generalNotes&&<div className="record-note-card"><span>{en?'NOTES':'ΣΗΜΕΙΩΣΕΙΣ'}</span><p>{record.generalNotes}</p></div>}</div>
}
function D({l,v}){return <div className="detail-item"><span>{l}</span><strong>{v}</strong></div>}
