import { useMemo, useState } from 'react'
import { ClipboardCheck, Droplets, Recycle, ShieldCheck } from 'lucide-react'
import { Page } from '../../design-system/Page'
import { RecordActions } from '../../design-system/RecordActions'
import { FilterBar, FilterSelect } from '../../design-system/FilterBar'
import { UI_ACTIONS } from '../../core/actions/actionPolicy'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { CAPABILITIES } from '../../core/permissions/roles'
import { antisepticRows, bundleRows, handHygieneRows, wasteRows } from './preventionDemoData'

const tabs=[['handHygiene','handHygiene'],['waste','wasteManagement'],['antiseptics','antisepticConsumption'],['bundles','preventionBundles']]
export function PreventionPage(){
 const {t,language,locale}=useLanguage(); const {notify}=useFeedback(); const [tab,setTab]=useState('handHygiene'); const [query,setQuery]=useState(''); const [department,setDepartment]=useState('all'); const [period,setPeriod]=useState('all'); const createCapability=tab==='handHygiene'?CAPABILITIES.RECORD_HAND_HYGIENE:tab==='waste'?CAPABILITIES.RECORD_WASTE:tab==='antiseptics'?CAPABILITIES.RECORD_ANTISEPTIC:CAPABILITIES.RECORD_PREVENTION_BUNDLE
 const source=tab==='handHygiene'?handHygieneRows:tab==='waste'?wasteRows:tab==='antiseptics'?antisepticRows:bundleRows; const departments=useMemo(()=>[...new Set(source.map(x=>language==='el'?x.departmentEl:x.departmentEn))],[source,language]); const rows=useMemo(()=>source.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase())).filter(x=>department==='all'||(language==='el'?x.departmentEl:x.departmentEn)===department).filter(x=>period==='all'||x.period===period),[source,query,department,period,language]); const avg=handHygieneRows.reduce((s,x)=>s+x.rate,0)/handHygieneRows.length; const fmtDate=v=>v?new Intl.DateTimeFormat(locale).format(new Date(`${v}T12:00:00`)):'—'
 function action(a){if(a===UI_ACTIONS.CREATE)notify(t(tab==='handHygiene'?'newHandHygieneObservation':tab==='waste'?'newWasteRecord':tab==='antiseptics'?'newAntisepticRecord':'newBundleAssessment'),'info');else if(a===UI_ACTIONS.PRINT)window.print();else notify(t('actionCompleted'),'success')}
 return <Page fill title={t('preventionCenter')} subtitle={t('preventionSubtitle')} actions={<RecordActions actions={[UI_ACTIONS.CREATE,UI_ACTIONS.PRINT,UI_ACTIONS.EXPORT]} actionCapabilities={{[UI_ACTIONS.CREATE]:createCapability}} onAction={action}/>}>
  <div className="workspace-summary"><div className="prevention-kpis"><Kpi icon={ShieldCheck} value={`${avg.toFixed(1)}%`} label={t('whoCompliance')}/><Kpi icon={ClipboardCheck} value={bundleRows.length} label={t('activeBundles')}/><Kpi icon={Recycle} value={`${wasteRows.reduce((s,x)=>s+x.weight,0).toFixed(1)} kg`} label={t('wasteRecorded')}/><Kpi icon={Droplets} value={`${antisepticRows.reduce((s,x)=>s+x.litres,0).toFixed(1)} L`} label={t('antisepticRecorded')}/></div><div className="governance-banner"><ShieldCheck size={17}/><span>{t('preventionGovernance')}</span></div></div>
  <div className="surface prevention-workspace workspace-fill"><div className="tabs prevention-tabs">{tabs.map(([id,key])=><button key={id} className={`tab ${tab===id?'active':''}`} onClick={()=>{setTab(id);setQuery('');setDepartment('all');setPeriod('all')}}>{t(key)}</button>)}</div><FilterBar query={query} onQueryChange={setQuery} placeholder={t('searchPrevention')} onClear={()=>{setQuery('');setDepartment('all');setPeriod('all')}} advanced={tab==='antiseptics'||tab==='bundles'?<FilterSelect label={t('period')} value={period} onChange={setPeriod}><option value="all">{t('all')}</option><option value="2026-08">08/2026</option></FilterSelect>:null} activeAdvancedCount={(department!=='all'?1:0)+(period!=='all'?1:0)}><FilterSelect label={t('department')} value={department} onChange={setDepartment}><option value="all">{t('allDepartments')}</option>{departments.map(x=><option key={x}>{x}</option>)}</FilterSelect></FilterBar><div className="scroll-table">{tab==='handHygiene'&&<HandTable rows={rows} t={t} language={language} fmtDate={fmtDate}/>} {tab==='waste'&&<WasteTable rows={rows} t={t} language={language} fmtDate={fmtDate}/>} {tab==='antiseptics'&&<AntisepticTable rows={rows} t={t} language={language}/>} {tab==='bundles'&&<BundleTable rows={rows} t={t} language={language}/>}</div></div>
 </Page>
}
function Kpi({icon:Icon,value,label}){return <div className="prevention-kpi"><Icon size={18}/><div><strong>{value}</strong><span>{label}</span></div></div>}
function HandTable({rows,t,language,fmtDate}){return <table className="data-table sticky-table"><thead><tr><th>{t('date')}</th><th>{t('department')}</th><th>{t('professionalCategory')}</th><th>{t('observations')}</th><th>{t('compliant')}</th><th>{t('compliance')}</th><th>{t('observer')}</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{fmtDate(x.date)}</td><td>{language==='el'?x.departmentEl:x.departmentEn}</td><td>{t(x.profession)}</td><td>{x.observations}</td><td>{x.compliant}</td><td><strong>{x.rate}%</strong></td><td>{x.observer}</td></tr>)}</tbody></table>}
function WasteTable({rows,t,language,fmtDate}){return <table className="data-table sticky-table"><thead><tr><th>{t('date')}</th><th>{t('department')}</th><th>{t('wasteType')}</th><th>{t('weightKg')}</th><th>{t('containers')}</th><th>{t('status')}</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{fmtDate(x.date)}</td><td>{language==='el'?x.departmentEl:x.departmentEn}</td><td>{t(x.type)}</td><td>{x.weight}</td><td>{x.containers}</td><td><span className="status-badge active">{t(x.status)}</span></td></tr>)}</tbody></table>}
function AntisepticTable({rows,t,language}){return <table className="data-table sticky-table"><thead><tr><th>{t('period')}</th><th>{t('department')}</th><th>{t('product')}</th><th>{t('consumptionLitres')}</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.period}</td><td>{language==='el'?x.departmentEl:x.departmentEn}</td><td>{x.product}</td><td><strong>{x.litres}</strong></td></tr>)}</tbody></table>}
function BundleTable({rows,t,language}){return <table className="data-table sticky-table"><thead><tr><th>{t('bundle')}</th><th>{t('department')}</th><th>{t('period')}</th><th>{t('score')}</th><th>{t('status')}</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{t(x.bundle)}</td><td>{language==='el'?x.departmentEl:x.departmentEn}</td><td>{x.period}</td><td><strong>{x.score}%</strong></td><td><span className="status-badge active">{t(x.status)}</span></td></tr>)}</tbody></table>}
