import { useState } from 'react'
import { UserRoundCheck,Users } from 'lucide-react'
import { ObserverDialog,DialogActions } from '../../design-system/ObserverDialog'
import { ManualDateField } from '../../design-system/ManualDateField'
import { Button } from '../../design-system/Button'
import '../occupational-health/OccupationalHealthPage.css'

export const EMPTY_VACCINATION={vaccine:'',dose:'',date:'',lotNumber:'',validUntil:'',status:'complete',clinicalNotes:''}

const VACCINES=['Εποχική γρίπη','Ηπατίτιδα Β','COVID-19','MMR','Ανεμευλογιά','Td/Tdap','Ηπατίτιδα Α','Μηνιγγιτιδόκοκκος','Άλλο']

export function StaffVaccinationEditor({language,employees,value,onChange,onClose,onSave}){
 const en=language==='en';const {mode,draft,selectedEmployeeIds}=value;const [search,setSearch]=useState('');const [dept,setDept]=useState('all');const departments=[...new Set(employees.map(x=>en?x.departmentEn:x.department).filter(Boolean))];const filtered=employees.filter(x=>{const label=`${x.id} ${x.firstName} ${x.lastName} ${x.firstNameEn} ${x.lastNameEn}`.toLowerCase();const d=en?x.departmentEn:x.department;return label.includes(search.toLowerCase())&&(dept==='all'||d===dept)});const valid=selectedEmployeeIds.length>0&&draft.vaccine.trim()&&draft.date
 const patchDraft=patch=>onChange({...value,draft:{...draft,...patch}});const setMode=next=>onChange({...value,mode:next,selectedEmployeeIds:[]});const toggle=id=>onChange({...value,selectedEmployeeIds:selectedEmployeeIds.includes(id)?selectedEmployeeIds.filter(x=>x!==id):[...selectedEmployeeIds,id]});const selectVisible=()=>onChange({...value,selectedEmployeeIds:[...new Set([...selectedEmployeeIds,...filtered.map(x=>x.id)])]});const clearVisible=()=>onChange({...value,selectedEmployeeIds:selectedEmployeeIds.filter(id=>!filtered.some(x=>x.id===id))})
 const toggleFromKeyboard=(event,id)=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();toggle(id)}}
 return <ObserverDialog width="workspace" eyebrow={en?'Staff vaccination':'Εμβολιασμός προσωπικού'} title={en?'Vaccination entry':'Καταχώρηση εμβολιασμού'} subtitle={en?'Choose one employee or register the same vaccine for several selected employees.':'Επιλέξτε έναν εργαζόμενο ή καταχωρήστε το ίδιο εμβόλιο σε πολλούς επιλεγμένους εργαζομένους.'} onClose={onClose} footer={<DialogActions showCancel onCancel={onClose} onSave={()=>onSave(value)} disabled={!valid} saveLabel={en?(mode==='bulk'?`Save ${selectedEmployeeIds.length} vaccinations`:'Save vaccination'):(mode==='bulk'?`Αποθήκευση ${selectedEmployeeIds.length} εμβολιασμών`:'Αποθήκευση εμβολιασμού')}/>}>
  <div className="vaccination-editor"><div className="vaccination-entry-mode" role="group" aria-label={en?'Entry mode':'Τρόπος καταχώρησης'}><Button variant={mode==='individual'?'primary':'secondary'} onClick={()=>setMode('individual')}><UserRoundCheck size={17}/>{en?'Individual':'Μεμονωμένα'}</Button><Button variant={mode==='bulk'?'primary':'secondary'} onClick={()=>setMode('bulk')}><Users size={17}/>{en?'Bulk vaccination':'Μαζικός εμβολιασμός'}</Button></div>
   <section className="vaccination-editor-card"><h4>{en?'Vaccine details':'Στοιχεία εμβολίου'}</h4><div className="vaccination-fields"><label><span>{en?'Vaccine':'Εμβόλιο'} *</span><select value={draft.vaccine} onChange={e=>patchDraft({vaccine:e.target.value})}><option value="">{en?'Select vaccine':'Επιλέξτε εμβόλιο'}</option>{VACCINES.map(v=><option key={v} value={v}>{v}</option>)}</select></label><label><span>{en?'Dose':'Δόση'}</span><input value={draft.dose} onChange={e=>patchDraft({dose:e.target.value})} placeholder={en?'e.g. 1, 2, booster':'π.χ. 1, 2, αναμνηστική'}/></label><ManualDateField label={en?'Vaccination date *':'Ημερομηνία εμβολιασμού *'} value={draft.date} onChange={date=>patchDraft({date})}/><label><span>{en?'Lot number':'Παρτίδα'}</span><input value={draft.lotNumber} onChange={e=>patchDraft({lotNumber:e.target.value})}/></label><ManualDateField label={en?'Valid until':'Ισχύει έως'} value={draft.validUntil} onChange={validUntil=>patchDraft({validUntil})} optional/><label className="vaccination-notes"><span>{en?'Notes':'Σημειώσεις'}</span><input value={draft.clinicalNotes} onChange={e=>patchDraft({clinicalNotes:e.target.value})}/></label></div></section>
   <section className="vaccination-editor-card vaccination-employee-picker"><div className="vaccination-picker-heading"><div><h4>{mode==='bulk'?(en?'Employees to vaccinate':'Εργαζόμενοι προς εμβολιασμό'):(en?'Employee':'Εργαζόμενος')}</h4><small>{en?`${selectedEmployeeIds.length} selected`:`${selectedEmployeeIds.length} επιλεγμένοι`}</small></div>{mode==='bulk'&&<div className="vaccination-picker-actions"><Button variant="secondary" onClick={selectVisible}>{en?'Select visible':'Επιλογή εμφανιζόμενων'}</Button><Button variant="secondary" onClick={clearVisible}>{en?'Clear visible':'Καθαρισμός εμφανιζόμενων'}</Button></div>}</div>
    {mode==='individual'?<label><span>{en?'Select employee':'Επιλέξτε εργαζόμενο'}</span><select value={selectedEmployeeIds[0]||''} onChange={e=>onChange({...value,selectedEmployeeIds:e.target.value?[e.target.value]:[]})}><option value="">{en?'Select employee':'Επιλέξτε εργαζόμενο'}</option>{employees.map(e=><option key={e.id} value={e.id}>{en?`${e.firstNameEn||e.firstName} ${e.lastNameEn||e.lastName}`:`${e.lastName} ${e.firstName}`} · {en?e.departmentEn:e.department}</option>)}</select></label>:<><div className="vaccination-picker-filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={en?'Search employees…':'Αναζήτηση εργαζομένων…'}/><select value={dept} onChange={e=>setDept(e.target.value)}><option value="all">{en?'All departments':'Όλα τα τμήματα'}</option>{departments.map(d=><option key={d}>{d}</option>)}</select></div><div className="vaccination-employee-list">{filtered.map(e=>{const selected=selectedEmployeeIds.includes(e.id);return <div key={e.id} className={`vaccination-employee-row${selected?' selected':''}`} tabIndex={0} onClick={()=>toggle(e.id)} onKeyDown={event=>toggleFromKeyboard(event,e.id)}><input type="checkbox" aria-label={en?`Select ${e.firstNameEn||e.firstName} ${e.lastNameEn||e.lastName}`:`Επιλογή ${e.lastName} ${e.firstName}`} checked={selected} onClick={event=>event.stopPropagation()} onChange={()=>toggle(e.id)}/><div className="vaccination-employee-copy"><strong>{en?`${e.firstNameEn||e.firstName} ${e.lastNameEn||e.lastName}`:`${e.lastName} ${e.firstName}`}</strong><small>{e.id} · {en?e.departmentEn:e.department} · {en?e.professionEn:e.profession}</small></div></div>})}</div></>}
   </section>
  </div>
 </ObserverDialog>
}