from pathlib import Path
p=Path('src/features/surveillance/PatientClinicalCanonicalPage.jsx')
s=p.read_text()
# Child samples use a stable sample-code lineage: PARENT-R1, PARENT-R1-R1, etc.
# This persists in both demo and cloud without overloading clinical fields.
s=s.replace("const created=await laboratory.createSample({patientRecordId:patient.recordId||null,draft:{...draft,patient:patient.name", "const created=await laboratory.createSample({patientRecordId:patient.recordId||null,draft:{...draft,patient:patient.name",1)
start=s.index('function SurveillanceWorkspace(')
end=s.index('\nfunction CanonicalJourney',start)
block=s[start:end]
# Add selected parent state and create follow-up payload.
block=block.replace("[samplePrompt,setSamplePrompt]=useState(null),[detailId,setDetailId]=useState('')", "[samplePrompt,setSamplePrompt]=useState(null),[followUpParent,setFollowUpParent]=useState(null),[detailId,setDetailId]=useState('')",1)
block=block.replace("async function saveSample(draft){if(!onCreateSample)return;const created=await onCreateSample(draft);setSampleOpen(false);if(created)setSamplePrompt(created)}", "async function saveSample(draft){if(!onCreateSample)return;const parent=followUpParent;const siblings=parent?samples.filter(x=>String(x.id||'').startsWith(`${parent.id}-R`)).length:0;const payload=parent?{...draft,type:draft.type||parent.type,sampleCode:`${parent.id}-R${siblings+1}`,surveillanceCaseId:parent.surveillanceCase||null}:draft;const created=await onCreateSample(payload);setSampleOpen(false);setFollowUpParent(null);if(created&&!parent)setSamplePrompt(created)}",1)
# General new sample always starts a root sample.
block=block.replace("onClick={()=>setSampleOpen(true)}>+ {language==='el'?'Νέο δείγμα':'New sample'}", "onClick={()=>{setFollowUpParent(null);setSampleOpen(true)}}>+ {language==='el'?'Νέο δείγμα':'New sample'}",1)
# Replace the flat tree body render with recursive sample lineage.
body_start=block.index('{episodes.map(ep=>{const linked=samples.filter')
body_end=block.index("{!episodes.length&&!samples.length",body_start)
new_body="""{episodes.map(ep=>{const linked=samples.filter(sample=>String(sample.surveillanceCase||sample.surveillanceCaseId||sample.surveillance_case_id||'')===String(ep.id)||String(sample.surveillanceCase||'')===String(ep.recordId||''));return <div className=\"surveillance-tree-group\" key={ep.id}><button type=\"button\" className={`surveillance-tree-episode ${String(selectedId)===String(ep.id)?'is-selected':''}`} onClick={()=>openEpisode(ep.id)}><span><strong>{fmtDate(ep.startedAt)}</strong><small>{language==='el'?'Επιτήρηση':'Surveillance'} · {ep.suspectedSource||ep.reason||'—'}</small></span><span><b className={`status-badge ${ep.status==='active'?'active':''}`}>{t(ep.status)}</b></span><span>{ep.samples?.find(x=>x.organism)?.organism||'—'}</span><span>{ep.resistance||'—'}</span><span>{ep.reviewDue?`${language==='el'?'Επανεκτίμηση':'Review'} ${fmtDate(ep.reviewDue)}`:'—'}</span></button><SampleTree samples={linked} linked onFollowUp={sample=>{setFollowUpParent(sample);setSampleOpen(true)}} onCreateFromSample={onCreateFromSample} canCreate={canCreate} canCreateSample={canCreateSample} t={t} language={language} fmtDate={fmtDate}/></div>})}{(()=>{const unlinked=samples.filter(sample=>!episodes.some(ep=>String(sample.surveillanceCase||sample.surveillanceCaseId||sample.surveillance_case_id||'')===String(ep.id)||String(sample.surveillanceCase||'')===String(ep.recordId||'')));return <SampleTree samples={unlinked} linked={false} onFollowUp={sample=>{setFollowUpParent(sample);setSampleOpen(true)}} onCreateFromSample={onCreateFromSample} canCreate={canCreate} canCreateSample={canCreateSample} t={t} language={language} fmtDate={fmtDate}/>})()}"""
block=block[:body_start]+new_body+block[body_end:]
# Follow-up dialog identifies the parent action and preselects the same specimen type.
block=block.replace("{sampleOpen&&<SampleDialog t={t} onClose={()=>setSampleOpen(false)} onSave={saveSample}/>} ", "{sampleOpen&&<SampleDialog t={t} title={followUpParent?(language==='el'?'Επανέλεγχος δείγματος':'Sample follow-up'):null} initialType={followUpParent?.type||followUpParent?.sampleType||''} onClose={()=>{setSampleOpen(false);setFollowUpParent(null)}} onSave={saveSample}/>} ",1)
# Replace row helper with recursive renderer. Direct parent is encoded by removing the final -R<number> suffix.
row_start=block.index('function SampleTreeRow(')
helpers="""function sampleParentCode(sample){const code=String(sample?.id||'');return /-R\\d+$/.test(code)?code.replace(/-R\\d+$/,''):''}
function SampleTree({samples=[],linked,onFollowUp,onCreateFromSample,canCreate,canCreateSample,t,language,fmtDate}){const codes=new Set(samples.map(x=>String(x.id||'')));const roots=samples.filter(x=>!sampleParentCode(x)||!codes.has(sampleParentCode(x)));const render=(sample,depth=0)=><div key={sample.recordId||sample.id}><SampleTreeRow sample={sample} linked={linked} depth={depth} onFollowUp={onFollowUp} onCreateFromSample={onCreateFromSample} canCreate={canCreate} canCreateSample={canCreateSample} t={t} language={language} fmtDate={fmtDate}/>{samples.filter(x=>sampleParentCode(x)===String(sample.id||'')).map(child=>render(child,depth+1))}</div>;return <>{roots.map(x=>render(x,0))}</>}
function SampleTreeRow({sample,linked,depth=0,onFollowUp,onCreateFromSample,canCreate,canCreateSample,t,language,fmtDate}){const type=t(sample.sampleType||sample.type)||(sample.sampleType||sample.type||'—');const status=t(sample.result||sample.status||'pending');const organism=sample.organism||sample.microorganism||sample.microbiologyResults?.find(x=>x.organism)?.organism||'—';const amr=sample.resistance||sample.amr||sample.microbiologyResults?.find(x=>x.amr)?.amr||'—';return <div className={`surveillance-tree-sample ${linked?'is-linked':'is-unlinked'} ${depth?'is-followup':''}`} style={{paddingLeft:`${32+depth*28}px`}}><span><i aria-hidden=\"true\">↳</i><span><strong>{fmtDate(sample.collectedAt||sample.requestedAt)}</strong><small>{depth?(language==='el'?`Επανέλεγχος ${depth}`:`Follow-up ${depth}`):type} · {type}{sample.id?` · ${sample.id}`:''}</small></span></span><span>{status}</span><span>{organism}</span><span>{amr}</span><span style={{display:'flex',gap:5,alignItems:'center',overflow:'visible'}}>{linked?<em>{language==='el'?'Συνδεδεμένο':'Linked'}</em>:(canCreate?<Button variant=\"ghost\" onClick={()=>onCreateFromSample?.(sample)}><PlayCircle size={14}/>{language==='el'?'Έναρξη επιτήρησης':'Start surveillance'}</Button>:null)}{canCreateSample&&<Button variant=\"ghost\" onClick={()=>onFollowUp?.(sample)}><RefreshCcw size={14}/>{language==='el'?'Επανέλεγχος':'Follow-up'}</Button>}</span></div>}
"""
block=block[:row_start]+helpers
s=s[:start]+block+s[end:]
# Sample dialog supports follow-up title and inherited specimen type.
s=s.replace("function SampleDialog({t,onClose,onSave}){const [d,setD]=useState({type:'bloodCulture'", "function SampleDialog({t,title,initialType='',onClose,onSave}){const [d,setD]=useState({type:initialType||'bloodCulture'",1)
s=s.replace("return <SimpleDialog title={t('laboratoryRecords.newSample')} t={t}", "return <SimpleDialog title={title||t('laboratoryRecords.newSample')} t={t}",1)
p.write_text(s)
