export const ROLES = Object.freeze({
  PLATFORM_OWNER: 'platform_owner',
  HOSPITAL_ADMIN: 'hospital_admin',
  INFECTION_CONTROL_LEAD: 'infection_control_lead',
  INFECTION_CONTROL_MEMBER: 'infection_control_member',
  DEPARTMENT_MANAGER: 'department_manager',
  DEPARTMENT_USER: 'department_user',
  LABORATORY: 'laboratory',
  COMMITTEE_SECRETARIAT: 'committee_secretariat',
  HR_OFFICE: 'hr_office',
  PHARMACY: 'pharmacy',
  OCCUPATIONAL_PHYSICIAN: 'occupational_physician',
  DOCTOR_REVIEWER: 'doctor_reviewer',
  QUALITY_MANAGER: 'quality_manager',
  DEMO: 'demo',
})

export const CAPABILITIES = Object.freeze({
  VIEW_PLATFORM: 'view_platform', VIEW_DASHBOARD: 'view_dashboard', VIEW_MY_DEPARTMENT: 'view_my_department', VIEW_MY_PROFILE: 'view_my_profile',
  VIEW_SURVEILLANCE: 'view_surveillance', VIEW_LAB: 'view_lab', VIEW_PREVENTION: 'view_prevention', VIEW_RECORDS: 'view_records', VIEW_QUALITY: 'view_quality', VIEW_CONTROLS: 'view_controls', VIEW_TRAINING: 'view_training', VIEW_COMMITTEES: 'view_committees', VIEW_DOCUMENTS: 'view_documents', VIEW_PATIENTS: 'view_patients', VIEW_STAFF: 'view_staff', VIEW_LIRA: 'view_lira', VIEW_PHARMACY: 'view_pharmacy', VIEW_OCCUPATIONAL_HEALTH: 'view_occupational_health', VIEW_INDICATORS: 'view_indicators',
  REPORT_INCIDENT: 'report_incident', MANAGE_USERS: 'manage_users', MANAGE_ORGANIZATION: 'manage_organization', MANAGE_PLATFORM: 'manage_platform', MANAGE_CONTROLS: 'manage_controls', MANAGE_QUALITY: 'manage_quality', MANAGE_STAFF_ADMIN: 'manage_staff_admin', MANAGE_OCCUPATIONAL_HEALTH: 'manage_occupational_health', MANAGE_COMMITTEES: 'manage_committees', MANAGE_TRAINING: 'manage_training', MANAGE_PHARMACY: 'manage_pharmacy', MANAGE_INDICATORS: 'manage_indicators', MANAGE_BED_DAYS: 'manage_bed_days', MANAGE_ROLES: 'manage_roles', MANAGE_EXTERNAL_REFERENCES: 'manage_external_references', MANAGE_LIBRARIES: 'manage_libraries', MANAGE_ANNOUNCEMENTS: 'manage_announcements',
  REVIEW_CLINICAL: 'review_clinical', CLOSE_SURVEILLANCE: 'close_surveillance', RECORD_CLINICAL_ASSESSMENT: 'record_clinical_assessment', MANAGE_LAB_SAMPLES: 'manage_lab_samples', VALIDATE_LAB_RESULTS: 'validate_lab_results', COMMUNICATE_CRITICAL_RESULTS: 'communicate_critical_results', CLASSIFY_RESISTANCE: 'classify_resistance', REOPEN_LAB_RECORD: 'reopen_lab_record', MANAGE_ANTIMICROBIAL_THERAPY: 'manage_antimicrobial_therapy', MANAGE_ISOLATION: 'manage_isolation', REASSESS_SURVEILLANCE: 'reassess_surveillance', RECORD_SURVEILLANCE_OUTCOME: 'record_surveillance_outcome', REOPEN_SURVEILLANCE: 'reopen_surveillance',
  CREATE_RECORDS: 'create_records', EDIT_RECORDS: 'edit_records', DELETE_RECORDS: 'delete_records', COMPLETE_RECORDS: 'complete_records', APPROVE_RECORDS: 'approve_records', ATTACH_FILES: 'attach_files', PRINT_RECORDS: 'print_records', EXPORT_RECORDS: 'export_records', ASSIGN_RECORDS: 'assign_records',
  CREATE_PATIENT: 'create_patient', EDIT_PATIENT: 'edit_patient', DELETE_PATIENT: 'delete_patient', CREATE_SURVEILLANCE: 'create_surveillance', EDIT_SURVEILLANCE: 'edit_surveillance', DELETE_SURVEILLANCE: 'delete_surveillance', RECORD_HAND_HYGIENE: 'record_hand_hygiene', RECORD_WASTE: 'record_waste', RECORD_ANTISEPTIC: 'record_antiseptic', RECORD_PREVENTION_BUNDLE: 'record_prevention_bundle',
})

export const MANAGEMENT_CAPABILITIES = Object.freeze([
  CAPABILITIES.MANAGE_ORGANIZATION,
  CAPABILITIES.MANAGE_USERS,
  CAPABILITIES.MANAGE_ROLES,
  CAPABILITIES.MANAGE_LIBRARIES,
  CAPABILITIES.MANAGE_BED_DAYS,
  CAPABILITIES.MANAGE_EXTERNAL_REFERENCES,
  CAPABILITIES.MANAGE_PLATFORM,
])

export const ADD_ON_CAPABILITIES = Object.freeze({ HAND_HYGIENE_OBSERVER:'hand_hygiene_observer', WASTE_MANAGEMENT:'waste_management', COMMITTEE_MEMBER:'committee_member', LIRA_ACCESS:'lira_access', LAB_ACCESS:'lab_access', QUALITY_ACCESS:'quality_access' })

const commonEmployee=[CAPABILITIES.VIEW_DASHBOARD,CAPABILITIES.VIEW_MY_DEPARTMENT,CAPABILITIES.VIEW_MY_PROFILE,CAPABILITIES.REPORT_INCIDENT,CAPABILITIES.VIEW_CONTROLS,CAPABILITIES.VIEW_TRAINING,CAPABILITIES.VIEW_DOCUMENTS]
const hospitalWide=[CAPABILITIES.VIEW_DASHBOARD,CAPABILITIES.VIEW_SURVEILLANCE,CAPABILITIES.VIEW_LAB,CAPABILITIES.VIEW_PREVENTION,CAPABILITIES.VIEW_RECORDS,CAPABILITIES.VIEW_QUALITY,CAPABILITIES.VIEW_CONTROLS,CAPABILITIES.VIEW_TRAINING,CAPABILITIES.VIEW_COMMITTEES,CAPABILITIES.VIEW_DOCUMENTS,CAPABILITIES.VIEW_PATIENTS,CAPABILITIES.VIEW_STAFF,CAPABILITIES.VIEW_LIRA,CAPABILITIES.VIEW_INDICATORS,CAPABILITIES.PRINT_RECORDS,CAPABILITIES.EXPORT_RECORDS]
const allCapabilities=Object.values(CAPABILITIES)
const hospitalAdminCapabilities=allCapabilities.filter(cap=>![CAPABILITIES.VIEW_PLATFORM,CAPABILITIES.MANAGE_PLATFORM].includes(cap))
const recordWorker=[CAPABILITIES.CREATE_RECORDS,CAPABILITIES.EDIT_RECORDS,CAPABILITIES.ATTACH_FILES,CAPABILITIES.PRINT_RECORDS]
const recordManager=[...recordWorker,CAPABILITIES.DELETE_RECORDS,CAPABILITIES.COMPLETE_RECORDS,CAPABILITIES.APPROVE_RECORDS,CAPABILITIES.EXPORT_RECORDS,CAPABILITIES.ASSIGN_RECORDS]

export const roleCapabilities=Object.freeze({
  [ROLES.PLATFORM_OWNER]:allCapabilities,
  [ROLES.HOSPITAL_ADMIN]:hospitalAdminCapabilities,
  [ROLES.INFECTION_CONTROL_LEAD]:[...hospitalWide,...recordManager,CAPABILITIES.MANAGE_CONTROLS,CAPABILITIES.CLOSE_SURVEILLANCE,CAPABILITIES.REVIEW_CLINICAL,CAPABILITIES.RECORD_CLINICAL_ASSESSMENT,CAPABILITIES.CLASSIFY_RESISTANCE,CAPABILITIES.MANAGE_ANTIMICROBIAL_THERAPY,CAPABILITIES.MANAGE_ISOLATION,CAPABILITIES.REASSESS_SURVEILLANCE,CAPABILITIES.RECORD_SURVEILLANCE_OUTCOME,CAPABILITIES.MANAGE_BED_DAYS,CAPABILITIES.MANAGE_LIBRARIES,CAPABILITIES.MANAGE_ANNOUNCEMENTS,CAPABILITIES.MANAGE_INDICATORS,CAPABILITIES.CREATE_PATIENT,CAPABILITIES.EDIT_PATIENT,CAPABILITIES.CREATE_SURVEILLANCE,CAPABILITIES.EDIT_SURVEILLANCE,CAPABILITIES.RECORD_HAND_HYGIENE,CAPABILITIES.RECORD_WASTE,CAPABILITIES.RECORD_ANTISEPTIC,CAPABILITIES.RECORD_PREVENTION_BUNDLE],
  [ROLES.INFECTION_CONTROL_MEMBER]:[CAPABILITIES.VIEW_DASHBOARD,CAPABILITIES.VIEW_SURVEILLANCE,CAPABILITIES.VIEW_LAB,CAPABILITIES.VIEW_PREVENTION,CAPABILITIES.VIEW_RECORDS,CAPABILITIES.VIEW_CONTROLS,CAPABILITIES.VIEW_TRAINING,CAPABILITIES.VIEW_DOCUMENTS,CAPABILITIES.VIEW_PATIENTS,CAPABILITIES.VIEW_INDICATORS,CAPABILITIES.RECORD_CLINICAL_ASSESSMENT,CAPABILITIES.CLASSIFY_RESISTANCE,CAPABILITIES.MANAGE_ISOLATION,CAPABILITIES.REASSESS_SURVEILLANCE,CAPABILITIES.RECORD_HAND_HYGIENE,CAPABILITIES.RECORD_WASTE,CAPABILITIES.RECORD_ANTISEPTIC,CAPABILITIES.RECORD_PREVENTION_BUNDLE,...recordWorker],
  [ROLES.DEPARTMENT_MANAGER]:[...commonEmployee,CAPABILITIES.VIEW_SURVEILLANCE,CAPABILITIES.VIEW_PATIENTS,CAPABILITIES.VIEW_INDICATORS,...recordWorker],
  [ROLES.DEPARTMENT_USER]:[...commonEmployee,CAPABILITIES.ATTACH_FILES,CAPABILITIES.PRINT_RECORDS],
  [ROLES.LABORATORY]:[CAPABILITIES.VIEW_DASHBOARD,CAPABILITIES.VIEW_LAB,CAPABILITIES.VIEW_CONTROLS,CAPABILITIES.VIEW_DOCUMENTS,CAPABILITIES.MANAGE_LAB_SAMPLES,CAPABILITIES.VALIDATE_LAB_RESULTS,CAPABILITIES.COMMUNICATE_CRITICAL_RESULTS,CAPABILITIES.CLASSIFY_RESISTANCE,CAPABILITIES.REOPEN_LAB_RECORD,...recordWorker,CAPABILITIES.EXPORT_RECORDS],
  [ROLES.COMMITTEE_SECRETARIAT]:[CAPABILITIES.VIEW_DASHBOARD,CAPABILITIES.VIEW_COMMITTEES,CAPABILITIES.VIEW_DOCUMENTS,CAPABILITIES.MANAGE_COMMITTEES,CAPABILITIES.CREATE_RECORDS,CAPABILITIES.EDIT_RECORDS,CAPABILITIES.ATTACH_FILES,CAPABILITIES.PRINT_RECORDS],
  [ROLES.HR_OFFICE]:[CAPABILITIES.VIEW_DASHBOARD,CAPABILITIES.VIEW_STAFF,CAPABILITIES.VIEW_TRAINING,CAPABILITIES.VIEW_DOCUMENTS,CAPABILITIES.MANAGE_STAFF_ADMIN,CAPABILITIES.CREATE_RECORDS,CAPABILITIES.EDIT_RECORDS,CAPABILITIES.ATTACH_FILES,CAPABILITIES.PRINT_RECORDS],
  [ROLES.PHARMACY]:[CAPABILITIES.VIEW_DASHBOARD,CAPABILITIES.VIEW_PHARMACY,CAPABILITIES.VIEW_DOCUMENTS,CAPABILITIES.VIEW_INDICATORS,CAPABILITIES.MANAGE_PHARMACY,CAPABILITIES.MANAGE_ANTIMICROBIAL_THERAPY,...recordWorker,CAPABILITIES.EXPORT_RECORDS],
  [ROLES.OCCUPATIONAL_PHYSICIAN]:[CAPABILITIES.VIEW_DASHBOARD,CAPABILITIES.VIEW_OCCUPATIONAL_HEALTH,CAPABILITIES.VIEW_STAFF,CAPABILITIES.VIEW_DOCUMENTS,CAPABILITIES.MANAGE_OCCUPATIONAL_HEALTH,...recordWorker,CAPABILITIES.EXPORT_RECORDS],
  [ROLES.DOCTOR_REVIEWER]:[CAPABILITIES.VIEW_DASHBOARD,CAPABILITIES.VIEW_PATIENTS,CAPABILITIES.VIEW_SURVEILLANCE,CAPABILITIES.VIEW_LAB,CAPABILITIES.VIEW_INDICATORS,CAPABILITIES.REVIEW_CLINICAL,CAPABILITIES.RECORD_CLINICAL_ASSESSMENT,CAPABILITIES.MANAGE_ANTIMICROBIAL_THERAPY,CAPABILITIES.REASSESS_SURVEILLANCE,CAPABILITIES.RECORD_SURVEILLANCE_OUTCOME,...recordManager],
  [ROLES.QUALITY_MANAGER]:[CAPABILITIES.VIEW_DASHBOARD,CAPABILITIES.VIEW_QUALITY,CAPABILITIES.VIEW_CONTROLS,CAPABILITIES.VIEW_COMMITTEES,CAPABILITIES.VIEW_DOCUMENTS,CAPABILITIES.VIEW_INDICATORS,CAPABILITIES.MANAGE_QUALITY,CAPABILITIES.MANAGE_CONTROLS,CAPABILITIES.MANAGE_INDICATORS,...recordManager],
  [ROLES.DEMO]:hospitalAdminCapabilities,
})

export const addonCapabilityMap=Object.freeze({
  [ADD_ON_CAPABILITIES.HAND_HYGIENE_OBSERVER]:[CAPABILITIES.VIEW_PREVENTION,CAPABILITIES.RECORD_HAND_HYGIENE], [ADD_ON_CAPABILITIES.WASTE_MANAGEMENT]:[CAPABILITIES.VIEW_PREVENTION,CAPABILITIES.VIEW_RECORDS,CAPABILITIES.RECORD_WASTE], [ADD_ON_CAPABILITIES.COMMITTEE_MEMBER]:[CAPABILITIES.VIEW_COMMITTEES], [ADD_ON_CAPABILITIES.LIRA_ACCESS]:[CAPABILITIES.VIEW_LIRA], [ADD_ON_CAPABILITIES.LAB_ACCESS]:[CAPABILITIES.VIEW_LAB], [ADD_ON_CAPABILITIES.QUALITY_ACCESS]:[CAPABILITIES.VIEW_QUALITY],
})

export function capabilitiesFor(role,addOns=[],customCapabilities=[]){const base=roleCapabilities[role]??[];const supplemental=addOns.flatMap(item=>addonCapabilityMap[item]??[]);return [...new Set([...base,...supplemental,...customCapabilities])]}
export const can=(role,capability,addOns=[],customCapabilities=[])=>capabilitiesFor(role,addOns,customCapabilities).includes(capability)
export const canAny=(role,capabilities=[],addOns=[],customCapabilities=[])=>capabilities.some(capability=>can(role,capability,addOns,customCapabilities))
