import { CAPABILITIES } from './capabilityCatalogue.js'
import { DATA_SCOPES } from './scopeTypes.js'
export const ROLES = Object.freeze({
  PLATFORM_OWNER: 'platform_owner',
  HOSPITAL_ADMIN: 'hospital_admin',
  INFECTION_CONTROL_LEAD: 'infection_control_lead',
  INFECTION_CONTROL_MEMBER: 'infection_control_member',
  LINK_NURSE: 'link_nurse',
  DEPARTMENT_MANAGER: 'department_manager',
  DEPARTMENT_USER: 'department_user',
  LABORATORY: 'laboratory',
  COMMITTEE_SECRETARIAT: 'committee_secretariat',
  HR_OFFICE: 'hr_office',
  PHARMACY: 'pharmacy',
  OCCUPATIONAL_PHYSICIAN: 'occupational_physician',
  DOCTOR_REVIEWER: 'doctor_reviewer',
  QUALITY_MANAGER: 'quality_manager',
  DEMO: 'demo',
})

export const PREVIEWABLE_ROLES = Object.freeze([
  ROLES.HOSPITAL_ADMIN, ROLES.INFECTION_CONTROL_LEAD, ROLES.INFECTION_CONTROL_MEMBER,
  ROLES.DEPARTMENT_MANAGER, ROLES.LINK_NURSE, ROLES.DEPARTMENT_USER, ROLES.LABORATORY,
  ROLES.COMMITTEE_SECRETARIAT, ROLES.HR_OFFICE, ROLES.PHARMACY, ROLES.OCCUPATIONAL_PHYSICIAN,
  ROLES.DOCTOR_REVIEWER, ROLES.QUALITY_MANAGER,
])
export const isPreviewableRole = (role) => PREVIEWABLE_ROLES.includes(role)

export const MANAGEMENT_CAPABILITIES = Object.freeze([
  CAPABILITIES.MANAGE_ORGANIZATION, CAPABILITIES.MANAGE_USERS, CAPABILITIES.MANAGE_ROLES,
  CAPABILITIES.MANAGE_LIBRARIES, CAPABILITIES.MANAGE_BED_DAYS, CAPABILITIES.MANAGE_EXTERNAL_REFERENCES,
  CAPABILITIES.MANAGE_ANNOUNCEMENTS, CAPABILITIES.MANAGE_INDICATORS, CAPABILITIES.MANAGE_PLATFORM,
])

export const ADD_ON_CAPABILITIES = Object.freeze({ HAND_HYGIENE_OBSERVER:'hand_hygiene_observer', WASTE_MANAGEMENT:'waste_management', COMMITTEE_MEMBER:'committee_member', LIRA_ACCESS:'lira_access', LAB_ACCESS:'lab_access', QUALITY_ACCESS:'quality_access' })

const commonEmployee=[CAPABILITIES.VIEW_DASHBOARD,CAPABILITIES.VIEW_MY_DEPARTMENT,CAPABILITIES.VIEW_MY_PROFILE,CAPABILITIES.REPORT_INCIDENT,CAPABILITIES.VIEW_CONTROLS,CAPABILITIES.VIEW_TRAINING,CAPABILITIES.VIEW_DOCUMENTS]
const hospitalWide=[CAPABILITIES.VIEW_DASHBOARD,CAPABILITIES.VIEW_SURVEILLANCE,CAPABILITIES.VIEW_LAB,CAPABILITIES.VIEW_PREVENTION,CAPABILITIES.VIEW_RECORDS,CAPABILITIES.VIEW_QUALITY,CAPABILITIES.VIEW_CONTROLS,CAPABILITIES.VIEW_TRAINING,CAPABILITIES.VIEW_COMMITTEES,CAPABILITIES.VIEW_DOCUMENTS,CAPABILITIES.VIEW_PATIENTS,CAPABILITIES.VIEW_STAFF,CAPABILITIES.VIEW_LIRA,CAPABILITIES.VIEW_INDICATORS,CAPABILITIES.VIEW_ANALYSIS,CAPABILITIES.PRINT_RECORDS,CAPABILITIES.EXPORT_RECORDS]
const allCapabilities=Object.values(CAPABILITIES)
const hospitalAdminExcluded=new Set([CAPABILITIES.VIEW_PLATFORM,CAPABILITIES.MANAGE_PLATFORM,CAPABILITIES.VIEW_OCCUPATIONAL_HEALTH,CAPABILITIES.VIEW_PHARMACY,CAPABILITIES.MANAGE_PHARMACY,CAPABILITIES.MANAGE_OCCUPATIONAL_HEALTH,CAPABILITIES.REVIEW_CLINICAL,CAPABILITIES.RECORD_CLINICAL_ASSESSMENT,CAPABILITIES.MANAGE_ANTIMICROBIAL_THERAPY,CAPABILITIES.MANAGE_ISOLATION,CAPABILITIES.REASSESS_SURVEILLANCE,CAPABILITIES.RECORD_SURVEILLANCE_OUTCOME,CAPABILITIES.REOPEN_SURVEILLANCE,CAPABILITIES.CREATE_PATIENT,CAPABILITIES.EDIT_PATIENT,CAPABILITIES.DELETE_PATIENT,CAPABILITIES.CREATE_SURVEILLANCE,CAPABILITIES.EDIT_SURVEILLANCE,CAPABILITIES.DELETE_SURVEILLANCE])
const hospitalAdminCapabilities=allCapabilities.filter(cap=>!hospitalAdminExcluded.has(cap))
const demoCapabilities=allCapabilities.filter(cap=>![CAPABILITIES.VIEW_PLATFORM,CAPABILITIES.MANAGE_PLATFORM].includes(cap))
const recordWorker=[CAPABILITIES.CREATE_RECORDS,CAPABILITIES.EDIT_RECORDS,CAPABILITIES.ATTACH_FILES,CAPABILITIES.PRINT_RECORDS]
const recordManager=[...recordWorker,CAPABILITIES.DELETE_RECORDS,CAPABILITIES.COMPLETE_RECORDS,CAPABILITIES.APPROVE_RECORDS,CAPABILITIES.EXPORT_RECORDS,CAPABILITIES.ASSIGN_RECORDS]

export const roleCapabilities=Object.freeze({
  [ROLES.PLATFORM_OWNER]:allCapabilities,
  [ROLES.HOSPITAL_ADMIN]:hospitalAdminCapabilities,
  [ROLES.INFECTION_CONTROL_LEAD]:[...hospitalWide,...recordManager,CAPABILITIES.MANAGE_CONTROLS,CAPABILITIES.MANAGE_TRAINING,CAPABILITIES.EXECUTE_CONTROL,CAPABILITIES.EDIT_CONTROL_DEFINITION,CAPABILITIES.EDIT_CONTROL_EXECUTION,CAPABILITIES.VOID_CONTROL_EXECUTION,CAPABILITIES.ARCHIVE_CONTROL_DEFINITION,CAPABILITIES.DELETE_CONTROL_DRAFT,CAPABILITIES.CLOSE_SURVEILLANCE,CAPABILITIES.REVIEW_CLINICAL,CAPABILITIES.RECORD_CLINICAL_ASSESSMENT,CAPABILITIES.CLASSIFY_RESISTANCE,CAPABILITIES.MANAGE_ANTIMICROBIAL_THERAPY,CAPABILITIES.MANAGE_ISOLATION,CAPABILITIES.REASSESS_SURVEILLANCE,CAPABILITIES.RECORD_SURVEILLANCE_OUTCOME,CAPABILITIES.MANAGE_BED_DAYS,CAPABILITIES.MANAGE_LIBRARIES,CAPABILITIES.MANAGE_ANNOUNCEMENTS,CAPABILITIES.MANAGE_INDICATORS,CAPABILITIES.CREATE_PATIENT,CAPABILITIES.EDIT_PATIENT,CAPABILITIES.CREATE_SURVEILLANCE,CAPABILITIES.EDIT_SURVEILLANCE,CAPABILITIES.RECORD_HAND_HYGIENE,CAPABILITIES.RECORD_WASTE,CAPABILITIES.RECORD_ANTISEPTIC,CAPABILITIES.RECORD_PREVENTION_BUNDLE,CAPABILITIES.CREATE_COMMITTEE,CAPABILITIES.MANAGE_COMMITTEE_MEMBERS,CAPABILITIES.CREATE_COMMITTEE_MEETING,CAPABILITIES.EDIT_COMMITTEE_MINUTES,CAPABILITIES.FINALIZE_COMMITTEE_MINUTES,CAPABILITIES.MANAGE_COMMITTEE_DECISIONS,CAPABILITIES.MANAGE_COMMITTEE_DOCUMENTS,CAPABILITIES.ARCHIVE_COMMITTEE],
  [ROLES.INFECTION_CONTROL_MEMBER]:[CAPABILITIES.VIEW_DASHBOARD,CAPABILITIES.VIEW_SURVEILLANCE,CAPABILITIES.VIEW_LAB,CAPABILITIES.VIEW_PREVENTION,CAPABILITIES.VIEW_RECORDS,CAPABILITIES.VIEW_CONTROLS,CAPABILITIES.VIEW_TRAINING,CAPABILITIES.VIEW_DOCUMENTS,CAPABILITIES.VIEW_PATIENTS,CAPABILITIES.VIEW_INDICATORS,CAPABILITIES.EXECUTE_CONTROL,CAPABILITIES.EDIT_CONTROL_EXECUTION,CAPABILITIES.RECORD_CLINICAL_ASSESSMENT,CAPABILITIES.CLASSIFY_RESISTANCE,CAPABILITIES.MANAGE_ISOLATION,CAPABILITIES.REASSESS_SURVEILLANCE,CAPABILITIES.RECORD_HAND_HYGIENE,CAPABILITIES.RECORD_WASTE,CAPABILITIES.RECORD_ANTISEPTIC,CAPABILITIES.RECORD_PREVENTION_BUNDLE,...recordWorker],
  [ROLES.LINK_NURSE]:[...commonEmployee,CAPABILITIES.VIEW_STAFF,CAPABILITIES.VIEW_SURVEILLANCE,CAPABILITIES.VIEW_PREVENTION,CAPABILITIES.VIEW_PATIENTS,CAPABILITIES.VIEW_INDICATORS,CAPABILITIES.EXECUTE_CONTROL,CAPABILITIES.EDIT_CONTROL_EXECUTION,CAPABILITIES.RECORD_HAND_HYGIENE,CAPABILITIES.RECORD_WASTE,CAPABILITIES.RECORD_ANTISEPTIC,CAPABILITIES.RECORD_PREVENTION_BUNDLE,CAPABILITIES.ATTACH_FILES,CAPABILITIES.PRINT_RECORDS],
  [ROLES.DEPARTMENT_MANAGER]:[...commonEmployee,CAPABILITIES.VIEW_STAFF,CAPABILITIES.VIEW_SURVEILLANCE,CAPABILITIES.VIEW_PATIENTS,CAPABILITIES.VIEW_INDICATORS,CAPABILITIES.EXECUTE_CONTROL,CAPABILITIES.EDIT_CONTROL_DEFINITION,CAPABILITIES.EDIT_CONTROL_EXECUTION,CAPABILITIES.VOID_CONTROL_EXECUTION,...recordWorker],
  [ROLES.DEPARTMENT_USER]:[...commonEmployee,CAPABILITIES.EXECUTE_CONTROL,CAPABILITIES.EDIT_CONTROL_EXECUTION,CAPABILITIES.ATTACH_FILES,CAPABILITIES.PRINT_RECORDS],
  [ROLES.LABORATORY]:[CAPABILITIES.VIEW_DASHBOARD,CAPABILITIES.VIEW_LAB,CAPABILITIES.VIEW_STAFF,CAPABILITIES.VIEW_CONTROLS,CAPABILITIES.VIEW_DOCUMENTS,CAPABILITIES.EXECUTE_CONTROL,CAPABILITIES.EDIT_CONTROL_EXECUTION,CAPABILITIES.MANAGE_LAB_SAMPLES,CAPABILITIES.VALIDATE_LAB_RESULTS,CAPABILITIES.COMMUNICATE_CRITICAL_RESULTS,CAPABILITIES.CLASSIFY_RESISTANCE,CAPABILITIES.REOPEN_LAB_RECORD,...recordWorker,CAPABILITIES.EXPORT_RECORDS],
  [ROLES.COMMITTEE_SECRETARIAT]:[CAPABILITIES.VIEW_DASHBOARD,CAPABILITIES.VIEW_COMMITTEES,CAPABILITIES.VIEW_DOCUMENTS,CAPABILITIES.MANAGE_COMMITTEE_MEMBERS,CAPABILITIES.CREATE_COMMITTEE_MEETING,CAPABILITIES.EDIT_COMMITTEE_MINUTES,CAPABILITIES.FINALIZE_COMMITTEE_MINUTES,CAPABILITIES.MANAGE_COMMITTEE_DECISIONS,CAPABILITIES.MANAGE_COMMITTEE_DOCUMENTS,CAPABILITIES.CREATE_RECORDS,CAPABILITIES.EDIT_RECORDS,CAPABILITIES.ATTACH_FILES,CAPABILITIES.PRINT_RECORDS],
  [ROLES.HR_OFFICE]:[CAPABILITIES.VIEW_DASHBOARD,CAPABILITIES.VIEW_STAFF,CAPABILITIES.VIEW_TRAINING,CAPABILITIES.VIEW_DOCUMENTS,CAPABILITIES.MANAGE_STAFF_ADMIN,CAPABILITIES.CREATE_RECORDS,CAPABILITIES.EDIT_RECORDS,CAPABILITIES.ATTACH_FILES,CAPABILITIES.PRINT_RECORDS],
  [ROLES.PHARMACY]:[CAPABILITIES.VIEW_DASHBOARD,CAPABILITIES.VIEW_PHARMACY,CAPABILITIES.VIEW_DOCUMENTS,CAPABILITIES.VIEW_INDICATORS,CAPABILITIES.MANAGE_PHARMACY,CAPABILITIES.MANAGE_ANTIMICROBIAL_THERAPY,...recordWorker,CAPABILITIES.EXPORT_RECORDS],
  [ROLES.OCCUPATIONAL_PHYSICIAN]:[CAPABILITIES.VIEW_DASHBOARD,CAPABILITIES.VIEW_OCCUPATIONAL_HEALTH,CAPABILITIES.VIEW_STAFF,CAPABILITIES.VIEW_DOCUMENTS,CAPABILITIES.MANAGE_OCCUPATIONAL_HEALTH,...recordWorker,CAPABILITIES.EXPORT_RECORDS],
  [ROLES.DOCTOR_REVIEWER]:[CAPABILITIES.VIEW_DASHBOARD,CAPABILITIES.VIEW_PATIENTS,CAPABILITIES.VIEW_SURVEILLANCE,CAPABILITIES.VIEW_LAB,CAPABILITIES.VIEW_INDICATORS,CAPABILITIES.REVIEW_CLINICAL,CAPABILITIES.RECORD_CLINICAL_ASSESSMENT,CAPABILITIES.MANAGE_ANTIMICROBIAL_THERAPY,CAPABILITIES.REASSESS_SURVEILLANCE,CAPABILITIES.RECORD_SURVEILLANCE_OUTCOME,...recordManager],
  [ROLES.QUALITY_MANAGER]:[CAPABILITIES.VIEW_DASHBOARD,CAPABILITIES.VIEW_QUALITY,CAPABILITIES.VIEW_CONTROLS,CAPABILITIES.VIEW_COMMITTEES,CAPABILITIES.VIEW_DOCUMENTS,CAPABILITIES.VIEW_INDICATORS,CAPABILITIES.MANAGE_QUALITY,CAPABILITIES.MANAGE_CONTROLS,CAPABILITIES.EXECUTE_CONTROL,CAPABILITIES.EDIT_CONTROL_DEFINITION,CAPABILITIES.EDIT_CONTROL_EXECUTION,CAPABILITIES.VOID_CONTROL_EXECUTION,CAPABILITIES.ARCHIVE_CONTROL_DEFINITION,CAPABILITIES.DELETE_CONTROL_DRAFT,CAPABILITIES.MANAGE_DOCUMENTS,CAPABILITIES.SUBMIT_DOCUMENT_REVIEW,CAPABILITIES.APPROVE_DOCUMENT,CAPABILITIES.PUBLISH_DOCUMENT,CAPABILITIES.SUPERSEDE_DOCUMENT,CAPABILITIES.ARCHIVE_DOCUMENT,CAPABILITIES.DELETE_DOCUMENT_DRAFT,CAPABILITIES.MANAGE_INDICATORS,...recordManager],
  [ROLES.DEMO]:demoCapabilities,
})

export const addonCapabilityMap=Object.freeze({
  [ADD_ON_CAPABILITIES.HAND_HYGIENE_OBSERVER]:[CAPABILITIES.VIEW_PREVENTION,CAPABILITIES.RECORD_HAND_HYGIENE], [ADD_ON_CAPABILITIES.WASTE_MANAGEMENT]:[CAPABILITIES.VIEW_PREVENTION,CAPABILITIES.VIEW_RECORDS,CAPABILITIES.RECORD_WASTE], [ADD_ON_CAPABILITIES.COMMITTEE_MEMBER]:[CAPABILITIES.VIEW_COMMITTEES], [ADD_ON_CAPABILITIES.LIRA_ACCESS]:[CAPABILITIES.VIEW_LIRA], [ADD_ON_CAPABILITIES.LAB_ACCESS]:[CAPABILITIES.VIEW_LAB], [ADD_ON_CAPABILITIES.QUALITY_ACCESS]:[CAPABILITIES.VIEW_QUALITY],
})

const departmentRoles=new Set([ROLES.LINK_NURSE,ROLES.DEPARTMENT_MANAGER,ROLES.DEPARTMENT_USER,ROLES.LABORATORY])
const assignmentRoles=new Set([ROLES.DOCTOR_REVIEWER,ROLES.COMMITTEE_SECRETARIAT])
const laboratoryOrganizationCapabilities=new Set([CAPABILITIES.VIEW_LAB,CAPABILITIES.MANAGE_LAB_SAMPLES,CAPABILITIES.VALIDATE_LAB_RESULTS,CAPABILITIES.COMMUNICATE_CRITICAL_RESULTS,CAPABILITIES.CLASSIFY_RESISTANCE,CAPABILITIES.REOPEN_LAB_RECORD])
const scopeForSystemRole=(role,capability)=>{
  if(capability===CAPABILITIES.VIEW_MY_PROFILE)return DATA_SCOPES.SELF
  if(role===ROLES.PLATFORM_OWNER&&capability.includes('platform'))return DATA_SCOPES.PLATFORM
  if(role===ROLES.LABORATORY&&laboratoryOrganizationCapabilities.has(capability))return DATA_SCOPES.ORGANIZATION
  if(departmentRoles.has(role))return DATA_SCOPES.DEPARTMENT
  return DATA_SCOPES.ORGANIZATION
}
export const systemRoleMatrix=Object.freeze(Object.entries(roleCapabilities).flatMap(([role,capabilities])=>capabilities.map(capability=>Object.freeze({role,capability,defaultScope:scopeForSystemRole(role,capability),maximumScope:scopeForSystemRole(role,capability),requiresAssignment:assignmentRoles.has(role)}))))
export const roleCapabilityRule=(role,capability)=>systemRoleMatrix.find(row=>row.role===role&&row.capability===capability)??null
