import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, Database, Pencil, Plus, Trash2, X } from 'lucide-react'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { useTenant } from '../../core/tenant/TenantContext'
import { Button } from '../../design-system/Button'
import { SaveButton } from '../../design-system/SaveButton'
import { IconButton } from '../../design-system/IconButton'
import { OverflowMenu } from '../../design-system/OverflowMenu'
import { RegistryTable } from '../../design-system/RegistryTable'
import { FilterBar, FilterDate, FilterSelect } from '../../design-system/FilterBar'
import { EntityRecordShell } from '../../design-system/EntityRecordShell'
import { demoLibrarySeed, demoPatientDayPeriods } from './managementData'
import { ManualDateField } from '../../design-system/ManualDateField'
import { loadDepartments } from './departmentsService'
import { createPatientDayPeriod, loadPatientDayPeriods, removePatientDayPeriod, updatePatientDayPeriod } from './patientDayPeriodsCloudService'
import '../../styles/bed-days.css'

const emptyDraft={from:'',to:'',scope:'department',departmentId:'',value:''}
export function BedDaysPanel(){
  const {language,locale,t}=useLanguage(); const {notify,confirm}=useFeedback(); const {tenant,isDemo}=useTenant();
  const [rows,setRows]=useState(isDemo?demoPatientDayPeriods:[]); const [departments,setDepartments]=useState(isDemo?demoLibrarySeed.departments.map(([el,en])=>({id:el,name:el,nameEn:en})):[]); const [loading,setLoading]=useState(!isDemo); const [editor,setEditor]=useState(null); const [selectedId,setSelectedId]=useState(null); const [draft,setDraft]=useState(emptyDraft); const [filters,setFilters]=useState({from:'',to:'',scope:'all',department:'all'});
  const fmt=v=>v?new Intl.DateTimeFormat(locale).format(new Date(`${v}T12:00:00`)):'—';
  const filteredRows=useMemo(()=>rows.filter(row=>{if(filters.from&&row.to<filters.from)return false;if(filters.to&&row.from>filters.to)return false;if(filters.scope!=='all'&&row.scope!==filters.scope)return false;if(filters.department!=='all'&&row.scope==='department'&&row.departmentId!==filters.department)return false;if(filters.department!=='all'&&row.scope==='hospital')return false;return true}),[rows,filters]);
  const filteredTotal=useMemo(()=>filteredRows.reduce((s,r)=>s+Number(r.value||0),0),[filteredRows]);
  const selected=useMemo(()=>rows.find(row=>row.id===selectedId)||null,[rows,selectedId])
  useEffect(()=>{if(isDemo){setRows(demoPatientDayPeriods);setDepartments(demoLibrarySeed.departments.map(([el,en])=>({id:el,name:el,nameEn:en})));setLoading(false);return}if(!tenant?.id)return;let active=true;setLoading(true);Promise.all([loadPatientDayPeriods(tenant.id),loadDepartments(tenant.id)]).then(([periods,depts])=>{if(active){setRows(periods);setDepartments(depts.map(d=>({id:d.id,name:d.name,nameEn:d.name})))}}).catch(error=>{if(active)notify(error?.message||t('managementPanel.loadFailed'),'error')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[isDemo,tenant?.id,notify,t])
  function openCreate(){setDraft(emptyDraft);setEditor({mode:'create'})}
  function openEdit(row){setDraft({from:row.from,to:row.to,scope:row.scope,departmentId:row.departmentId||'',value:String(row.value??'')});setEditor({mode:'edit',id:row.id})}
  function closeEditor(){setEditor(null);setDraft(emptyDraft)}
  async function save(){if(!draft.from||!draft.to||draft.value===''||(draft.scope==='department'&&!draft.departmentId)){notify(t('completeRequiredFields'),'danger');return}if(draft.to<draft.from){notify(t('completeRequiredFields'),'danger');return}try{const dept=departments.find(d=>d.id===draft.departmentId);const record={...draft,departmentEl:draft.scope==='department'?(dept?.name||''):'',departmentEn:draft.scope==='department'?(dept?.nameEn||dept?.name||''):'',source:'manual'};if(editor?.mode==='edit'){const saved=isDemo?{id:editor.id,...record}:await updatePatientDayPeriod(tenant.id,editor.id,record);setRows(current=>current.map(row=>row.id===editor.id?saved:row));setSelectedId(saved.id);notify(t('patientDaysUpdated'),'success')}else{const saved=isDemo?{id:`pd-${Date.now()}`,...record}:await createPatientDayPeriod(tenant.id,record);setRows(current=>[saved,...current]);setSelectedId(saved.id);notify(t('patientDaysSaved'),'success')}closeEditor()}catch(error){notify(error?.message||t('managementPanel.saveFailed'),'error')}}
  async function remove(id){const ok=await confirm({message:t('confirmDelete'),danger:true,confirmLabel:t('delete')});if(!ok)return;try{if(!isDemo)await removePatientDayPeriod(tenant.id,id);setRows(current=>current.filter(x=>x.id!==id));if(selectedId===id)setSelectedId(null);notify(t('actionCompleted'),'success')}catch(error){notify(error?.message||t('managementPanel.saveFailed'),'error')}}
  const advancedCount=(filters.from?1:0)+(filters.to?1:0)+(filters.scope!=='all'?1:0)+(filters.department!=='all'?1:0)

  if(selected)return <section className="management-section management-scroll-section"><EntityRecordShell className="bed-days-record-shell workspace-fill" avatar={<CalendarDays size={19}/>} eyebrow={t('patientDays')} title={`${fmt(selected.from)} – ${fmt(selected.to)}`} subtitle={selected.scope==='hospital'?t('wholeHospital'):(language==='el'?selected.departmentEl:selected.departmentEn)} onBack={()=>setSelectedId(null)} backLabel={t('patientDays')}>
    <section className="record-section bed-days-record-section"><div className="record-section-header"><div><span className="eyebrow">{t('details')}</span><h3>{t('patientDays')}</h3></div><div className="bed-days-record-actions"><IconButton tone="edit" label={t('edit')} onClick={()=>openEdit(selected)}><Pencil size={16}/></IconButton><IconButton tone="danger" label={t('delete')} onClick={()=>remove(selected.id)}><Trash2 size={16}/></IconButton></div></div><div className="bed-days-details-grid"><div className="bed-days-detail"><span>{t('period')}</span><strong>{fmt(selected.from)} – {fmt(selected.to)}</strong></div><div className="bed-days-detail"><span>{t('scope')}</span><strong>{selected.scope==='hospital'?t('wholeHospital'):t('perDepartment')}</strong></div><div className="bed-days-detail"><span>{t('department')}</span><strong>{selected.scope==='hospital'?'—':(language==='el'?selected.departmentEl:selected.departmentEn)}</strong></div><div className="bed-days-detail"><span>{t('patientDays')}</span><strong>{Number(selected.value).toLocaleString(locale)}</strong></div><div className="bed-days-detail"><span>{t('source')}</span><strong>{t(selected.source)}</strong></div></div></section>
    {editor&&<EntryEditor t={t} language={language} departments={departments} draft={draft} setDraft={setDraft} mode={editor.mode} onClose={closeEditor} onSave={save}/>} 
  </EntityRecordShell></section>

  return <section className="management-section management-scroll-section"><div className="bed-days-panel workspace-fill"><div className="section-toolbar"><div><h2>{t('patientDays')}</h2><p>{t('patientDaysManualSubtitle')}</p></div><Button onClick={openCreate}><Plus size={15}/>{t('newPatientDaysEntry')}</Button></div><div className="bed-days-tools"><FilterBar activeAdvancedCount={advancedCount} onClear={()=>setFilters({from:'',to:'',scope:'all',department:'all'})} advanced={<><FilterDate label={t('periodFrom')} value={filters.from} onChange={value=>setFilters(c=>({...c,from:value}))}/><FilterDate label={t('periodTo')} value={filters.to} onChange={value=>setFilters(c=>({...c,to:value}))}/></>}><FilterSelect label={t('scope')} value={filters.scope} onChange={value=>setFilters(c=>({...c,scope:value}))}><option value="all">{t('allScopes')}</option><option value="department">{t('perDepartment')}</option><option value="hospital">{t('wholeHospital')}</option></FilterSelect><FilterSelect label={t('department')} value={filters.department} onChange={value=>setFilters(c=>({...c,department:value}))}><option value="all">{t('allDepartments')}</option>{departments.map(d=><option key={d.id} value={d.id}>{language==='el'?d.name:(d.nameEn||d.name)}</option>)}</FilterSelect></FilterBar><div className="bed-days-summary" aria-label={t('patientDays')}><div><CalendarDays/><span>{t('records')}</span><strong>{filteredRows.length}</strong></div><div><Database/><span>{t('totalPatientDays')}</span><strong>{filteredTotal.toLocaleString(locale)}</strong></div></div></div>{loading&&<div className="inline-empty">{t('loading')}</div>}<RegistryTable
  wrapperClassName="bed-days-table-wrap"
  columns={[{key:'period',label:t('period')},{key:'scope',label:t('scope')},{key:'value',label:t('patientDays')},{key:'source',label:t('source')},{key:'actions',label:t('actions')}]}
  rows={filteredRows}
  rowKey={row=>row.id}
  rowProps={row=>({className:'clickable-row',onClick:()=>setSelectedId(row.id)})}
  renderRow={row=><><td>{fmt(row.from)} – {fmt(row.to)}</td><td>{row.scope==='hospital'?t('wholeHospital'):(language==='el'?row.departmentEl:row.departmentEn)}</td><td><strong>{Number(row.value).toLocaleString(locale)}</strong></td><td>{t(row.source)}</td><td onClick={e=>e.stopPropagation()}><OverflowMenu items={[
    {id:'edit',label:t('edit'),icon:Pencil,onClick:()=>openEdit(row)},
    {id:'delete',label:t('delete'),icon:Trash2,tone:'danger',separatorBefore:true,onClick:()=>remove(row.id)},
  ]}/></td></>}
/>{!loading&&filteredRows.length===0&&<div className="inline-empty">{t('noPatientDaysFound')}</div>}{editor&&<EntryEditor t={t} language={language} departments={departments} draft={draft} setDraft={setDraft} mode={editor.mode} onClose={closeEditor} onSave={save}/>}</div></section>
}

function EntryEditor({t,language,departments,draft,setDraft,mode,onClose,onSave}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="entry-editor" role="dialog" aria-modal="true"><header><div><h3>{t(mode==='edit'?'editPatientDaysEntry':'newPatientDaysEntry')}</h3><p>{t('patientDaysEntryHint')}</p></div><button className="icon-button" onClick={onClose}><X size={17}/></button></header><div className="entry-form-grid"><ManualDateField className="field" label={t('periodFrom')} value={draft.from} onChange={v=>setDraft(c=>({...c,from:v}))}/><ManualDateField className="field" label={t('periodTo')} value={draft.to} onChange={v=>setDraft(c=>({...c,to:v}))}/><label className="field"><span>{t('scope')}</span><select className="input" value={draft.scope} onChange={e=>setDraft(c=>({...c,scope:e.target.value,departmentId:''}))}><option value="department">{t('perDepartment')}</option><option value="hospital">{t('wholeHospital')}</option></select></label>{draft.scope==='department'&&<label className="field"><span>{t('department')}</span><select className="input" value={draft.departmentId} onChange={e=>setDraft(c=>({...c,departmentId:e.target.value}))}><option value="">—</option>{departments.map(d=><option key={d.id} value={d.id}>{language==='el'?d.name:(d.nameEn||d.name)}</option>)}</select></label>}<label className="field"><span>{t('patientDays')}</span><input className="input" type="number" min="0" value={draft.value} onChange={e=>setDraft(c=>({...c,value:e.target.value}))}/></label></div><footer><Button variant="secondary" onClick={onClose}>{t('cancel')}</Button><SaveButton onClick={onSave}>{t('save')}</SaveButton></footer></div></div>}
