import {useEffect,useMemo,useState} from 'react'
import {Activity,BookOpen,RefreshCcw,Settings2} from 'lucide-react'
import {Button} from '../../design-system/Button'
import {RegistryTable} from '../../design-system/RegistryTable'
import {ObserverDialog,DialogActions} from '../../design-system/ObserverDialog'
import {useAuth} from '../../core/auth/AuthContext'
import {useLanguage} from '../../core/i18n/LanguageContext'
import {useTenant} from '../../core/tenant/TenantContext'
import {useFeedback} from '../../core/feedback/FeedbackContext'
import {loadClinicalScales,saveClinicalScaleSetting} from './clinicalScalesService'
import {loadClinicalContentSources,refreshClinicalContentSources} from './clinicalContentSourceService'
const popLabel=(p,en)=>(p||[]).map(x=>({adult:en?'Adult':'Ενήλικες',pediatric:en?'Pediatric':'Παιδιατρικοί',neonatal:en?'Neonatal':'Νεογνά'}[x]||x)).join(', ')
const availabilityLabel=(x,en)=>({available:en?'Available':'Διαθέσιμη',recommended:en?'Recommended':'Προτεινόμενη',required:en?'Required':'Υποχρεωτική',disabled:en?'Disabled':'Ανενεργή'}[x]||x)
export function ClinicalScalesPanel(){const {profile}=useAuth();const {language}=useLanguage(),en=language==='en';const {tenant,isDemo}=useTenant();const {notify}=useFeedback();const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[editor,setEditor]=useState(null),[sourceUpdate,setSourceUpdate]=useState(null),[sources,setSources]=useState([])
 useEffect(()=>{let live=true;if(isDemo){setRows([]);setLoading(false);return}setLoading(true);loadClinicalScales(tenant?.id).then(x=>live&&setRows(x)).catch(e=>live&&notify(e.message,'error')).finally(()=>live&&setLoading(false));return()=>{live=false}},[tenant?.id,isDemo,notify])
 const visible=useMemo(()=>rows.filter(x=>x.status!=='retired'),[rows])
 function open(row){const x=row.orgSetting||{};setEditor({row,availability:x.availability||'available',enabled:x.enabled!==false,reassessmentHours:x.reassessment_hours||''})}
 async function updateSources(){if(!profile?.isPlatformOwner)return;try{const initial=await loadClinicalContentSources();setSources(initial);setSourceUpdate({current:0,total:initial.length,source:null});await refreshClinicalContentSources(setSourceUpdate);setSources(await loadClinicalContentSources());notify(en?'Official sources checked. Review any detected changes before changing clinical logic.':'Ο έλεγχος των επίσημων πηγών ολοκληρώθηκε. Ελέγξτε κάθε αλλαγή πριν τροποποιηθεί κλινική λογική.','success')}catch(e){notify(e.message,'error')}finally{setSourceUpdate(null)}}
 async function save(){try{await saveClinicalScaleSetting(tenant.id,editor.row.id,editor);setRows(await loadClinicalScales(tenant.id));setEditor(null);notify(en?'Clinical scale settings saved.':'Οι ρυθμίσεις της κλινικής κλίμακας αποθηκεύτηκαν.','success')}catch(e){notify(e.message,'error')}}
 return <div className="workspace-column workspace-fill"><div className="section-toolbar"><div><h2>{en?'Clinical scales':'Κλινικές κλίμακες'}</h2><p>{en?'Governed registry of validated clinical assessment tools. Scoring definitions are versioned and calculated deterministically.':'Governed μητρώο επικυρωμένων εργαλείων κλινικής αξιολόγησης. Οι ορισμοί scoring είναι versioned και υπολογίζονται deterministic.'}</p></div></div>
 {loading?<div className="inline-empty">{en?'Loading…':'Φόρτωση…'}</div>:<RegistryTable wrapperClassName="table-wrap scroll-table" columns={[{key:'scale',label:en?'Scale':'Κλίμακα'},{key:'population',label:en?'Population':'Πληθυσμός'},{key:'setting',label:en?'Setting':'Περιβάλλον'},{key:'version',label:en?'Version':'Έκδοση'},{key:'availability',label:en?'Hospital use':'Χρήση νοσοκομείου'}]} rows={visible} rowKey={x=>x.id} rowProps={row=>({className:'clickable-row',onClick:()=>open(row)})} renderRow={row=><><td><strong>{en?row.name_en:row.name_el}</strong><small>{row.category} · {row.source_authority||'—'}</small></td><td>{popLabel(row.population,en)}</td><td>{(row.settings||[]).join(', ')||'—'}</td><td>{row.version}</td><td><span className={'status-badge '+(row.orgSetting?.enabled===false?'':'active')}>{availabilityLabel(row.orgSetting?.enabled===false?'disabled':row.orgSetting?.availability||'available',en)}</span></td></>}/>}
 {!loading&&!visible.length&&<div className="inline-empty">{isDemo?(en?'Clinical scale configuration is available in a hospital workspace.':'Η ρύθμιση κλινικών κλιμάκων είναι διαθέσιμη σε νοσοκομειακό workspace.'):(en?'No clinical scales available.':'Δεν υπάρχουν διαθέσιμες κλινικές κλίμακες.')}</div>}
 {editor&&<ObserverDialog width="standard" title={en?editor.row.name_en:editor.row.name_el} subtitle={editor.row.source_reference||''} onClose={()=>setEditor(null)} footer={<DialogActions onCancel={()=>setEditor(null)} onSave={save}/>}>
  <div className="entry-grid"><label><span>{en?'Hospital use':'Χρήση στο νοσοκομείο'}</span><select value={editor.availability} onChange={e=>setEditor(x=>({...x,availability:e.target.value,enabled:e.target.value!=='disabled'}))}><option value="available">{availabilityLabel('available',en)}</option><option value="recommended">{availabilityLabel('recommended',en)}</option><option value="required">{availabilityLabel('required',en)}</option><option value="disabled">{availabilityLabel('disabled',en)}</option></select></label><label><span>{en?'Reassessment interval (hours)':'Διάστημα επανεκτίμησης (ώρες)'}</span><input type="number" min="1" value={editor.reassessmentHours} onChange={e=>setEditor(x=>({...x,reassessmentHours:e.target.value}))} placeholder={en?'Hospital policy':'Πολιτική νοσοκομείου'}/></label></div>
  <div className="record-section"><span className="eyebrow"><BookOpen size={13}/> {en?'GOVERNANCE':'GOVERNANCE'}</span><p>{en?'Source: ':'Πηγή: '}{editor.row.source_authority||'—'} · {editor.row.source_reference||'—'}</p><p><Activity size={14}/> {en?'Scoring engine: ':'Μηχανή scoring: '}{editor.row.definition?.engine||'deterministic'} · {editor.row.definition?.scoringStatus==='ready'?(en?'ready · deterministic':'έτοιμο · deterministic'):(en?'governed definition pending':'εκκρεμεί governed ορισμός')}</p><p><Settings2 size={14}/> {en?'This setting controls availability only; it does not change the validated scoring rules.':'Η ρύθμιση ελέγχει μόνο τη διαθεσιμότητα και δεν αλλάζει τους επικυρωμένους κανόνες scoring.'}</p></div>
 </ObserverDialog>}</div>}
