import {useEffect,useMemo,useState} from 'react'
import {Activity,BookOpen,Settings2} from 'lucide-react'
import {RegistryTable} from '../../design-system/RegistryTable'
import {ObserverDialog,DialogActions} from '../../design-system/ObserverDialog'
import {useAuth} from '../../core/auth/AuthContext'
import {useLanguage} from '../../core/i18n/LanguageContext'
import {useTenant} from '../../core/tenant/TenantContext'
import {useFeedback} from '../../core/feedback/FeedbackContext'
import {loadClinicalScales,saveClinicalScaleSetting} from './clinicalScalesService'
import {clinicalScaleFields,clinicalScaleReady} from '../clinical-scales/clinicalScaleForms'
import {ScaleFormPreview} from '../clinical-scales/ClinicalScaleViews'
import {demoClinicalScaleDefinitions} from '../clinical-scales/clinicalScaleDemoDefinitions'
const popLabel=(p,en)=>(p||[]).map(x=>({adult:en?'Adult':'Ενήλικες',pediatric:en?'Pediatric':'Παιδιατρικοί',neonatal:en?'Neonatal':'Νεογνά'}[x]||x)).join(', ')
const settingLabel=(x,en)=>({ward:en?'Ward':'Θάλαμος',ed:en?'ED':'ΤΕΠ',icu:en?'ICU':'ΜΕΘ',acute_care:en?'Acute care':'Οξεία νοσηλεία',nicu:en?'NICU':'ΜΕΝΝ',neonatal:en?'Neonatal':'Νεογνική',pediatric_ward:en?'Pediatric ward':'Παιδιατρική κλινική',pediatric_ed:en?'Pediatric ED':'Παιδιατρικό ΤΕΠ',picu:en?'PICU':'ΜΕΘ παίδων'}[x]||x)
const categoryLabel=(x,en)=>({deterioration:en?'Clinical deterioration':'Κλινική επιδείνωση',neurology:en?'Neurology':'Νευρολογική',organ_dysfunction:en?'Organ dysfunction':'Οργανική δυσλειτουργία',severity:en?'Severity':'Βαρύτητα',pressure_injury:en?'Pressure injury':'Κατακλίσεις',fall_risk:en?'Fall risk':'Κίνδυνος πτώσης',falls:en?'Fall risk':'Κίνδυνος πτώσης'}[x]||x)
const availabilityLabel=(x,en)=>({available:en?'Available':'Διαθέσιμη',recommended:en?'Recommended':'Προτεινόμενη',required:en?'Required':'Υποχρεωτική',disabled:en?'Disabled':'Ανενεργή'}[x]||x)
export function ClinicalScalesPanel(){const {profile}=useAuth();const {language}=useLanguage(),en=language==='en';const {tenant,isDemo}=useTenant();const {notify}=useFeedback();const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[editor,setEditor]=useState(null)
 useEffect(()=>{let live=true;if(isDemo){setRows(demoClinicalScaleDefinitions.map(x=>({...x})));setLoading(false);return}setLoading(true);loadClinicalScales(tenant?.id).then(x=>live&&setRows(x)).catch(e=>live&&notify(e.message,'error')).finally(()=>live&&setLoading(false));return()=>{live=false}},[tenant?.id,isDemo,notify])
 const visible=useMemo(()=>rows.filter(x=>profile?.isPlatformOwner||x.status!=='draft').filter(x=>x.status!=='retired'),[rows,profile?.isPlatformOwner])
 function open(row){const x=row.orgSetting||{};setEditor({row,availability:x.availability||'available',enabled:x.enabled!==false,reassessmentHours:x.reassessment_hours||''})}
 async function save(){if(isDemo){setRows(v=>v.map(x=>x.id===editor.row.id?{...x,orgSetting:{availability:editor.availability,enabled:editor.enabled,reassessment_hours:editor.reassessmentHours}}:x));setEditor(null);notify(en?'Saved locally in the demo.':'Αποθηκεύτηκε τοπικά στο demo.','success');return}try{await saveClinicalScaleSetting(tenant.id,editor.row.id,editor);setRows(await loadClinicalScales(tenant.id));setEditor(null);notify(en?'Clinical scale settings saved.':'Οι ρυθμίσεις της κλινικής κλίμακας αποθηκεύτηκαν.','success')}catch(e){notify(e.message,'error')}}
 return <div className="workspace-column workspace-fill"><div className="section-toolbar"><div><h2>{en?'Clinical scales':'Κλινικές κλίμακες'}</h2><p>{en?'Governed registry of validated clinical assessment tools. Scoring definitions are versioned and calculated deterministically.':'Ελεγχόμενο μητρώο επικυρωμένων εργαλείων κλινικής αξιολόγησης. Οι κανόνες βαθμολόγησης τηρούν εκδόσεις και υπολογίζονται με καθορισμένο, αναπαραγώγιμο τρόπο.'}</p></div></div>
 {loading?<div className="inline-empty">{en?'Loading…':'Φόρτωση…'}</div>:<RegistryTable wrapperClassName="table-wrap scroll-table" columns={[{key:'scale',label:en?'Scale':'Κλίμακα'},{key:'population',label:en?'Population':'Πληθυσμός'},{key:'setting',label:en?'Setting':'Περιβάλλον'},{key:'version',label:en?'Version':'Έκδοση'},{key:'status',label:en?'Governance':'Κατάσταση'},{key:'availability',label:en?'Hospital use':'Χρήση νοσοκομείου'}]} rows={visible} rowKey={x=>x.id} rowProps={row=>({className:'clickable-row',onClick:()=>open(row)})} renderRow={row=><><td><strong>{en?row.name_en:row.name_el}</strong><small>{categoryLabel(row.category,en)} · {row.source_authority||'—'}</small></td><td>{popLabel(row.population,en)}</td><td>{[...new Set((row.settings||[]).map(x=>settingLabel(x,en)))].join(', ')||'—'}</td><td>{row.version}</td><td><span className={'status-badge '+(row.status==='approved'?'active':'')}>{row.status==='approved'?(en?'Approved':'Εγκεκριμένη'):(en?'Draft · review':'Προσχέδιο · προς έλεγχο')}</span></td><td><span className={'status-badge '+(row.orgSetting?.enabled===false?'':'active')}>{availabilityLabel(row.orgSetting?.enabled===false?'disabled':row.orgSetting?.availability||'available',en)}</span></td></>}/>}
 {!loading&&!visible.length&&<div className="inline-empty">{isDemo?(en?'Clinical scale configuration is available in a hospital workspace.':'Η ρύθμιση κλινικών κλιμάκων είναι διαθέσιμη στο περιβάλλον του νοσοκομείου.'):(en?'No clinical scales available.':'Δεν υπάρχουν διαθέσιμες κλινικές κλίμακες.')}</div>}
 {editor&&<ObserverDialog width="standard" title={en?editor.row.name_en:editor.row.name_el} subtitle={editor.row.source_reference||''} onClose={()=>setEditor(null)} footer={<DialogActions onCancel={()=>setEditor(null)} onSave={save}/>}>
  <div className="entry-grid"><label><span>{en?'Hospital use':'Χρήση στο νοσοκομείο'}</span><select value={editor.availability} onChange={e=>setEditor(x=>({...x,availability:e.target.value,enabled:e.target.value!=='disabled'}))}><option value="available">{availabilityLabel('available',en)}</option><option value="recommended">{availabilityLabel('recommended',en)}</option><option value="required">{availabilityLabel('required',en)}</option><option value="disabled">{availabilityLabel('disabled',en)}</option></select></label><label><span>{en?'Reassessment interval (hours)':'Διάστημα επανεκτίμησης (ώρες)'}</span><input type="number" min="1" value={editor.reassessmentHours} onChange={e=>setEditor(x=>({...x,reassessmentHours:e.target.value}))} placeholder={en?'Hospital policy':'Πολιτική νοσοκομείου'}/></label></div>
  <div className="record-section"><div className="record-section-header"><div><h4>{en?'Assessment form preview':'Προεπισκόπηση φόρμας αξιολόγησης'}</h4><p>{clinicalScaleReady(editor.row)?(en?'This is the governed form available to eligible patients.':'Αυτή είναι η ελεγχόμενη φόρμα που διατίθεται στους κατάλληλους ασθενείς.'):(en?'This definition is not activatable yet. Formula/form implementation review is still required.':'Ο ορισμός δεν μπορεί ακόμη να ενεργοποιηθεί. Εκκρεμεί έλεγχος υλοποίησης φόρμας/τύπου υπολογισμού.')}</p></div><span className={'status-badge '+(clinicalScaleReady(editor.row)?'active':'')}>{clinicalScaleReady(editor.row)?(en?'Ready':'Έτοιμη'):(en?'Review required':'Απαιτείται έλεγχος')}</span></div>{clinicalScaleFields(editor.row.scale_key).length?<ScaleFormPreview scale={editor.row.scale_key} en={en}/>:<div className="inline-empty">{en?'No approved calculator form yet. The scale remains draft and hidden from patient use.':'Δεν υπάρχει ακόμη εγκεκριμένη φόρμα υπολογισμού. Η κλίμακα παραμένει προσχέδιο και δεν εμφανίζεται στους ασθενείς.'}</div>}</div>
  <div className="record-section"><span className="eyebrow"><BookOpen size={13}/> {en?'GOVERNANCE':'ΤΕΚΜΗΡΙΩΣΗ'}</span><p>{en?'Source: ':'Πηγή: '}{editor.row.source_authority||'—'} · {editor.row.source_reference||'—'}</p><p><Activity size={14}/> {en?'Scoring engine: ':'Μηχανή βαθμολόγησης: '}{editor.row.definition?.scoringStatus==='ready'?(en?'ready · deterministic':'έτοιμη · καθορισμένη'):(en?'governed definition pending':'εκκρεμεί ελεγχόμενος ορισμός')}</p><p><Settings2 size={14}/> {en?'This setting controls availability only; it does not change the validated scoring rules.':'Η ρύθμιση ελέγχει μόνο τη διαθεσιμότητα και δεν αλλάζει τους επικυρωμένους κανόνες βαθμολόγησης.'}</p></div>
 </ObserverDialog>}</div>}
