import {supabase} from '../../core/supabase/client'
export async function loadClinicalContentSources(){if(!supabase)return [];const {data,error}=await supabase.from('clinical_content_sources').select('*').order('authority');if(error)throw error;return data||[]}
export async function loadClinicalContentSourceHistory(sourceId){if(!supabase)return [];const {data,error}=await supabase.from('clinical_content_source_history').select('*').eq('source_id',sourceId).order('checked_at',{ascending:false}).limit(50);if(error)throw error;return data||[]}
export async function refreshClinicalContentSources(onProgress){if(!supabase)throw new Error('Supabase is not configured.');const sources=await loadClinicalContentSources();const results=[];for(let i=0;i<sources.length;i+=1){onProgress?.({current:i,total:sources.length,source:sources[i]});const {data,error}=await supabase.functions.invoke('refresh-clinical-source',{body:{sourceId:sources[i].id}});if(error)throw error;results.push(data);onProgress?.({current:i+1,total:sources.length,source:sources[i]})}return results}

// A postponed change returns to the review list after this many days.
export const DEFER_DAYS=7
export async function loadPendingClinicalUpdates(){if(!supabase)return [];const {data,error}=await supabase.from('clinical_content_source_history').select('*,source:clinical_content_sources(*)').eq('change_detected',true).or(`review_status.eq.pending,and(review_status.eq.deferred,reviewed_at.lt.${new Date(Date.now()-DEFER_DAYS*86400000).toISOString()})`).order('checked_at',{ascending:false});if(error)throw error;return data||[]}
export async function reviewClinicalUpdate(id,status,note=''){if(!supabase)throw new Error('Supabase is not configured.');const {data:{user}}=await supabase.auth.getUser();const {data,error}=await supabase.from('clinical_content_source_history').update({review_status:status,reviewed_at:new Date().toISOString(),reviewed_by:user?.id||null,review_note:note}).eq('id',id).select('id');if(error)throw error;if(!data?.length)throw new Error('The update review could not be saved (no permission or record not found).')}
export async function loadPlatformUpdateHistory(){if(!supabase)return [];const {data,error}=await supabase.from('platform_update_runs').select('*').order('started_at',{ascending:false}).limit(50);if(error)throw error;return data||[]}
export async function startPlatformUpdateRun(trigger='manual'){if(!supabase)throw new Error('Supabase is not configured.');const {data:{user}}=await supabase.auth.getUser();const {data,error}=await supabase.from('platform_update_runs').insert({started_by:user?.id||null,trigger}).select().single();if(error)throw error;return data}
export async function finishPlatformUpdateRun(id,{checked=0,changed=0,errors=0,summary={}}={}){if(!supabase)return;const {error}=await supabase.from('platform_update_runs').update({completed_at:new Date().toISOString(),status:errors?'failed':'completed',checked_count:checked,changed_count:changed,error_count:errors,summary}).eq('id',id);if(error)throw error}
