import { useMemo, useState } from 'react'
import { BookOpen, Edit3, Plus, Trash2 } from 'lucide-react'
import { Button } from '../../design-system/Button'
import { FilterBar } from '../../design-system/FilterBar'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { demoLibrarySeed } from './managementData'
import { BundleLibraryPanel } from './BundleLibraryPanel'
const categories=[['departments','libraryDepartments'],['microorganisms','libraryMicroorganisms'],['antibiotics','libraryAntibiotics'],['notifiableDiseases','libraryNotifiableDiseases'],['sampleTypes','librarySampleTypes'],['professionalCategories','libraryProfessionalCategories'],['vaccines','libraryVaccines'],['wasteTypes','libraryWasteTypes'],['antiseptics','libraryAntiseptics'],['isolationTypes','libraryIsolationTypes'],['controlTypes','libraryControlTypes'],['documentCategories','libraryDocumentCategories'],['bundles','Bundles Πρόληψης']]
export function LibrariesPanel(){const {language,t}=useLanguage();const {notify}=useFeedback();const [active,setActive]=useState('departments');const [query,setQuery]=useState('');const [rows,setRows]=useState(demoLibrarySeed);const filtered=useMemo(()=>(rows[active]||[]).filter(x=>x.join(' ').toLowerCase().includes(query.toLowerCase())),[active,query,rows]);function add(){const value=prompt(t('libraryNewItemPrompt'));if(!value?.trim())return;setRows(c=>({...c,[active]:[...c[active],[value.trim(),value.trim()]]}));notify(t('libraryItemCreated'),'success')}function edit(index){const original=filtered[index];const value=prompt(t('libraryEditItemPrompt'),original[language==='el'?0:1]);if(!value?.trim())return;setRows(c=>({...c,[active]:c[active].map(x=>x===original?(language==='el'?[value.trim(),x[1]]:[x[0],value.trim()]):x)}));notify(t('libraryItemUpdated'),'success')}function remove(index){const original=filtered[index];if(!confirm(t('confirmLibraryDelete')))return;setRows(c=>({...c,[active]:c[active].filter(x=>x!==original)}));notify(t('libraryItemDeleted'),'success')}return <section className="management-section management-scroll-section"><div className="section-toolbar"><div><h2>{t('libraries')}</h2><p>{t('librariesSubtitle')}</p></div>{active!=='bundles'&&<Button onClick={add}><Plus size={15}/>{t('newLibraryItem')}</Button>}</div><div className="library-layout workspace-fill"><aside className="library-categories scroll-list">{categories.map(([id,key])=><button key={id} className={active===id?'active':''} onClick={()=>{setActive(id);setQuery('')}}><BookOpen size={15}/><span>{key==='Bundles Πρόληψης'?'Bundles Πρόληψης':t(key)}</span><small>{id==='bundles'?'6':(rows[id]?.length||0)}</small></button>)}</aside><div className="library-content workspace-column">{active==='bundles'?<BundleLibraryPanel/>:<><FilterBar compact query={query} onQueryChange={setQuery} placeholder={t('searchLibrary')} onClear={()=>setQuery('')}/>{active==='notifiableDiseases'&&<div className="governance-banner"><span>{t('notifiableLibraryGovernance')}</span></div>}<div className="table-wrap scroll-table"><table className="data-table sticky-table"><thead><tr><th>{t('name')}</th><th>{t('status')}</th><th>{t('actions')}</th></tr></thead><tbody>{filtered.map((row,index)=><tr key={`${active}-${row[0]}`}><td><strong>{row[language==='el'?0:1]}</strong>{row[0]!==row[1]&&<small>{row[language==='el'?1:0]}</small>}</td><td><span className="status-badge active">{t('active')}</span></td><td><div className="row-actions"><button className="icon-button" title={t('edit')} onClick={()=>edit(index)}><Edit3 size={15}/></button><button className="icon-button danger" title={t('delete')} onClick={()=>remove(index)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div></>}</div></div></section>}
