import { useEffect,useMemo,useState } from 'react'
import { BookOpen,CheckCircle2,FilePlus2,Pencil,RotateCcw,Search,X } from 'lucide-react'
import { Button } from '../../design-system/Button'
import { ObserverDialog,DialogActions } from '../../design-system/ObserverDialog'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useTenant } from '../../core/tenant/TenantContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { supabase } from '../../core/supabase/client'

const statusLabel=(value,en)=>({review:en?'In review':'Προς έλεγχο',approved:en?'Approved':'Εγκεκριμένη',retired:en?'Retired':'Αποσυρμένη'}[value]||value)
const ingestionLabel=(value,en)=>({ingested:en?'Ready':'Έτοιμη',pending:en?'Pending':'Εκκρεμεί',failed:en?'Failed':'Αποτυχία'}[value]||value)
const badgeClass=value=>value==='approved'||value==='ingested'?'success':value==='retired'||value==='failed'?'danger':'warning'

export function LiraKnowledgePanel(){
 const {language}=useLanguage();const en=language==='en';const {tenant}=useTenant();const {notify}=useFeedback()
 const [rows,setRows]=useState([]);const [loading,setLoading]=useState(true);const [selected,setSelected]=useState(null);const [chunks,setChunks]=useState([]);const [edit,setEdit]=useState(null);const [version,setVersion]=useState('');const [query,setQuery]=useState('');const [authority,setAuthority]=useState('all');const [status,setStatus]=useState('all')
 async function load(){setLoading(true);const {data,error}=await supabase.from('lira_knowledge_sources').select('id,title,authority,source_version,source_url,status,ingestion_status,effective_from,effective_to,approved_at,review_notes').order('authority').order('title');if(error)notify(error.message,'error');else setRows(data||[]);setLoading(false)}
 useEffect(()=>{load()},[tenant?.id])
 const authorities=useMemo(()=>[...new Set(rows.map(x=>x.authority).filter(Boolean))].sort(),[rows])
 const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase();return rows.filter(x=>(authority==='all'||x.authority===authority)&&(status==='all'||x.status===status)&&(!q||[x.authority,x.title,x.source_version].some(v=>String(v||'').toLocaleLowerCase().includes(q))))},[rows,query,authority,status])
 async function open(row){setSelected(row);setVersion('');const {data,error}=await supabase.from('lira_knowledge_chunks').select('id,chunk_index,heading,content,citation_label,page_start,page_end').eq('source_id',row.id).order('chunk_index');if(error)notify(error.message,'error');setChunks(data||[])}
 async function approve(){const {error}=await supabase.rpc('approve_lira_knowledge_source',{p_source_id:selected.id,p_review_notes:'Approved from LIRA Knowledge Center'});if(error)return notify(error.message,'error');notify(en?'Knowledge source approved.':'Η πηγή γνώσης εγκρίθηκε.','success');setSelected(null);load()}
 async function retire(){const {error}=await supabase.rpc('retire_lira_knowledge_source',{p_source_id:selected.id,p_review_notes:'Retired from LIRA Knowledge Center'});if(error)return notify(error.message,'error');notify(en?'Source retired.':'Η πηγή αποσύρθηκε.','success');setSelected(null);load()}
 async function saveEdit(){const {error}=await supabase.rpc('revise_lira_knowledge_source',{p_source_id:selected.id,p_title:edit.title,p_source_version:edit.source_version,p_source_url:edit.source_url||'',p_review_notes:edit.review_notes||''});if(error)return notify(error.message,'error');notify(en?'Source updated.':'Η πηγή ενημερώθηκε.','success');setEdit(null);setSelected(null);load()}
 async function newVersion(){if(!version.trim())return;const {error}=await supabase.rpc('create_lira_knowledge_source_version',{p_source_id:selected.id,p_source_version:version.trim(),p_review_notes:'New version created from approved source'});if(error)return notify(error.message,'error');notify(en?'New review version created.':'Δημιουργήθηκε νέα έκδοση προς έλεγχο.','success');setSelected(null);load()}
 return <section className="management-section management-scroll-section">
  <div className="section-toolbar"><div><h2>{en?'LIRA Knowledge':'Γνώση LIRA'}</h2><p>{en?'Governed clinical knowledge used by LIRA. Open a source to review its evidence and lifecycle.':'Ελεγχόμενη κλινική γνώση που χρησιμοποιεί η LIRA. Άνοιξε μια πηγή για έλεγχο τεκμηρίωσης και διαχείριση έκδοσης.'}</p></div><BookOpen size={22}/></div>
  <div className="registry-toolbar"><label className="search-field"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={en?'Search sources…':'Αναζήτηση πηγών…'}/>{query&&<button type="button" onClick={()=>setQuery('')} aria-label={en?'Clear':'Καθαρισμός'}><X size={14}/></button>}</label><select value={authority} onChange={e=>setAuthority(e.target.value)}><option value="all">{en?'All authorities':'Όλοι οι φορείς'}</option>{authorities.map(x=><option key={x} value={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">{en?'All statuses':'Όλες οι καταστάσεις'}</option><option value="review">{en?'In review':'Προς έλεγχο'}</option><option value="approved">{en?'Approved':'Εγκεκριμένες'}</option><option value="retired">{en?'Retired':'Αποσυρμένες'}</option></select><span className="muted">{filtered.length} / {rows.length}</span></div>
  {loading?<div className="inline-empty">{en?'Loading…':'Φόρτωση…'}</div>:filtered.length===0?<div className="inline-empty">{en?'No sources match the filters.':'Δεν βρέθηκαν πηγές με αυτά τα φίλτρα.'}</div>:<div className="management-table-wrap scroll-table"><table className="management-table"><thead><tr><th>{en?'Authority':'Φορέας'}</th><th>{en?'Source':'Πηγή'}</th><th>{en?'Version':'Έκδοση'}</th><th>{en?'Governance':'Διακυβέρνηση'}</th><th>{en?'Knowledge':'Γνώση'}</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id} className={selected?.id===x.id?'is-selected':''} onClick={()=>open(x)} tabIndex={0} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(x)}}}><td><strong>{x.authority}</strong></td><td>{x.title}</td><td>{x.source_version||'—'}</td><td><span className={`status-badge ${badgeClass(x.status)}`}>{statusLabel(x.status,en)}</span></td><td><span className={`status-badge ${badgeClass(x.ingestion_status)}`}>{ingestionLabel(x.ingestion_status,en)}</span></td></tr>)}</tbody></table></div>}
  <ObserverDialog open={Boolean(selected)} onClose={()=>setSelected(null)} title={selected?.title||''} size="large">
   {selected&&<div className="stack"><div className="detail-summary-grid"><div><span>{en?'Authority':'Φορέας'}</span><strong>{selected.authority}</strong></div><div><span>{en?'Version':'Έκδοση'}</span><strong>{selected.source_version||'—'}</strong></div><div><span>{en?'Governance':'Διακυβέρνηση'}</span><strong>{statusLabel(selected.status,en)}</strong></div><div><span>{en?'Knowledge':'Γνώση'}</span><strong>{ingestionLabel(selected.ingestion_status,en)}</strong></div></div>{selected.source_url&&<div><strong>{en?'Official source':'Επίσημη πηγή'}</strong><p className="muted">{selected.source_url}</p></div>}{selected.review_notes&&<div><strong>{en?'Review notes':'Σημειώσεις ελέγχου'}</strong><p>{selected.review_notes}</p></div>}<div><div className="section-toolbar"><div><h3>{en?'Knowledge content':'Περιεχόμενο γνώσης'}</h3><p>{chunks.length} {en?'sections':'ενότητες'}</p></div></div><div className="stack knowledge-chunk-list">{chunks.map(x=><article key={x.id} className="card"><strong>{x.heading||`#${x.chunk_index+1}`}</strong><p>{x.content}</p>{x.citation_label&&<small>{x.citation_label}{x.page_start!=null?` · p. ${x.page_start}${x.page_end&&x.page_end!==x.page_start?`–${x.page_end}`:''}`:''}</small>}</article>)}</div></div></div>}
   <DialogActions>{selected?.status==='review'&&<><Button variant="secondary" onClick={()=>setEdit({...selected})}><Pencil size={15}/>{en?'Edit metadata':'Επεξεργασία'}</Button><Button onClick={approve}><CheckCircle2 size={15}/>{en?'Approve':'Έγκριση'}</Button></>}{selected?.status==='approved'&&<><input value={version} onChange={e=>setVersion(e.target.value)} placeholder={en?'New version':'Νέα έκδοση'}/><Button variant="secondary" onClick={newVersion}><FilePlus2 size={15}/>{en?'Create version':'Νέα έκδοση'}</Button><Button variant="danger" onClick={retire}><RotateCcw size={15}/>{en?'Retire':'Απόσυρση'}</Button></>}<Button variant="secondary" onClick={()=>setSelected(null)}>{en?'Close':'Κλείσιμο'}</Button></DialogActions>
  </ObserverDialog>
  <ObserverDialog open={Boolean(edit)} onClose={()=>setEdit(null)} title={en?'Edit review source':'Επεξεργασία πηγής υπό έλεγχο'}>
   {edit&&<div className="form-grid"><label>{en?'Title':'Τίτλος'}<input value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})}/></label><label>{en?'Version':'Έκδοση'}<input value={edit.source_version||''} onChange={e=>setEdit({...edit,source_version:e.target.value})}/></label><label>{en?'Source URL':'URL πηγής'}<input value={edit.source_url||''} onChange={e=>setEdit({...edit,source_url:e.target.value})}/></label><label>{en?'Review notes':'Σημειώσεις ελέγχου'}<textarea value={edit.review_notes||''} onChange={e=>setEdit({...edit,review_notes:e.target.value})}/></label></div>}
   <DialogActions><Button variant="secondary" onClick={()=>setEdit(null)}>{en?'Cancel':'Ακύρωση'}</Button><Button onClick={saveEdit}>{en?'Save':'Αποθήκευση'}</Button></DialogActions>
  </ObserverDialog>
 </section>
}
