import {useEffect,useMemo,useState} from 'react'
import {Plus,Search} from 'lucide-react'
import {Button} from '../../design-system/Button'
import {ManualDateField} from '../../design-system/ManualDateField'
import {ObserverDialog,DialogActions} from '../../design-system/ObserverDialog'
import {useLanguage} from '../../core/i18n/LanguageContext'
import {useTenant} from '../../core/tenant/TenantContext'
import {useFeedback} from '../../core/feedback/FeedbackContext'
import {listOutbreakInvestigations,createOutbreakInvestigation,updateOutbreakInvestigation,appendOutbreakInvestigationEvent,loadOutbreakInvestigationEvents} from '../lira/liraOutbreakWorkspace'
const statusLabel=(s,en)=>({draft:en?'Draft':'Πρόχειρη',active:en?'Active':'Ενεργή',closed:en?'Closed':'Κλειστή'}[s]||s)
export function LiraOutbreakInvestigationsPanel(){
 const {language}=useLanguage(),en=language==='en';const {tenant}=useTenant();const {notify}=useFeedback()
 const [rows,setRows]=useState([]),[selected,setSelected]=useState(null),[events,setEvents]=useState([]),[query,setQuery]=useState(''),[creating,setCreating]=useState(false),[note,setNote]=useState('')
 const [form,setForm]=useState({title:'',organism:'',from:'',to:'',definitionId:'',definitionVersion:''})
 async function load(){if(!tenant?.id)return;try{setRows(await listOutbreakInvestigations(tenant.id))}catch(e){notify(e.message,'error')}}
 useEffect(()=>{load()},[tenant?.id])
 const filtered=useMemo(()=>rows.filter(x=>!query||[x.title,x.organism,x.status].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase()))),[rows,query])
 async function open(row){setSelected(row);try{setEvents(await loadOutbreakInvestigationEvents(row.id))}catch(e){notify(e.message,'error')}}
 async function create(){if(!form.title.trim())return;try{const definition=form.definitionId&&form.definitionVersion?{id:form.definitionId,version:form.definitionVersion}:null;const row=await createOutbreakInvestigation(tenant.id,{title:form.title.trim(),organism:form.organism.trim()||null,from:form.from||null,to:form.to||null,definition});await appendOutbreakInvestigationEvent(tenant.id,row.id,'status',{status:'draft',action:'created'});setCreating(false);setForm({title:'',organism:'',from:'',to:'',definitionId:'',definitionVersion:''});await load();await open(row);notify(en?'Investigation created.':'Η διερεύνηση δημιουργήθηκε.','success')}catch(e){notify(e.message,'error')}}
 async function changeStatus(status){try{const patch={status};if(status==='closed')patch.closed_at=new Date().toISOString();const row=await updateOutbreakInvestigation(selected.id,patch);await appendOutbreakInvestigationEvent(tenant.id,selected.id,'status',{from:selected.status,to:status});setSelected(row);setEvents(await loadOutbreakInvestigationEvents(row.id));load()}catch(e){notify(e.message,'error')}}
 async function addEvidence(type){if(!note.trim())return;try{await appendOutbreakInvestigationEvent(tenant.id,selected.id,type,{text:note.trim()});setNote('');setEvents(await loadOutbreakInvestigationEvents(selected.id));notify(en?'Recorded.':'Καταγράφηκε.','success')}catch(e){notify(e.message,'error')}}
 return <section className="management-section management-scroll-section">
  <div className="section-toolbar"><div><h2>{en?'Outbreak investigations':'Διερευνήσεις πιθανής έξαρσης'}</h2><p>{en?'Governed investigation workspace with versioned definitions and append-only evidence.':'Ελεγχόμενος χώρος διερεύνησης με versioned case definitions και append-only τεκμηρίωση.'}</p></div><Button onClick={()=>setCreating(true)}><Plus size={16}/>{en?'New investigation':'Νέα διερεύνηση'}</Button></div>
  <div className="registry-toolbar"><div className="search-field"><Search size={16}/><input aria-label={en?'Search investigations':'Αναζήτηση διερευνήσεων'} value={query} onChange={e=>setQuery(e.target.value)} placeholder={en?'Search…':'Αναζήτηση…'}/></div><span className="muted">{filtered.length}</span></div>
  {!filtered.length?<div className="inline-empty">{en?'No investigations.':'Δεν υπάρχουν διερευνήσεις.'}</div>:<div className="management-table-wrap scroll-table"><table className="management-table"><thead><tr><th>{en?'Investigation':'Διερεύνηση'}</th><th>{en?'Organism':'Μικροοργανισμός'}</th><th>{en?'Period':'Περίοδος'}</th><th>Case definition</th><th>{en?'Status':'Κατάσταση'}</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id} tabIndex={0} onClick={()=>open(x)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(x)}}}><td><strong>{x.title}</strong></td><td>{x.organism||'—'}</td><td>{x.scope_from||'—'} → {x.scope_to||'—'}</td><td>{x.definition_id?x.definition_id+' · '+x.definition_version:'—'}</td><td><span className={'status-badge '+(x.status==='active'?'success':x.status==='closed'?'danger':'warning')}>{statusLabel(x.status,en)}</span></td></tr>)}</tbody></table></div>}
  {selected&&<ObserverDialog presentation="workspace" width="workspace" title={selected.title} subtitle={[selected.organism,statusLabel(selected.status,en)].filter(Boolean).join(' · ')} onClose={()=>setSelected(null)} footer={<DialogActions><Button variant="secondary" onClick={()=>setSelected(null)}>{en?'Close':'Κλείσιμο'}</Button>{selected.status==='draft'&&<Button onClick={()=>changeStatus('active')}>{en?'Start investigation':'Έναρξη διερεύνησης'}</Button>}{selected.status==='active'&&<Button variant="danger" onClick={()=>changeStatus('closed')}>{en?'Close investigation':'Κλείσιμο διερεύνησης'}</Button>}</DialogActions>}><div className="stack"><div className="detail-summary-grid"><div><span>{en?'Period':'Περίοδος'}</span><strong>{selected.scope_from||'—'} → {selected.scope_to||'—'}</strong></div><div><span>Case definition</span><strong>{selected.definition_id?selected.definition_id+' · '+selected.definition_version:'—'}</strong></div><div><span>{en?'Status':'Κατάσταση'}</span><strong>{statusLabel(selected.status,en)}</strong></div><div><span>{en?'Evidence events':'Συμβάντα τεκμηρίωσης'}</span><strong>{events.length}</strong></div></div><div className="card"><h3>{en?'Hypotheses / decisions':'Υποθέσεις / αποφάσεις'}</h3><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder={en?'Record a hypothesis or decision…':'Καταγραφή υπόθεσης ή απόφασης…'}/><div className="row-actions"><Button variant="secondary" onClick={()=>addEvidence('hypothesis')}>{en?'Add hypothesis':'Προσθήκη υπόθεσης'}</Button><Button onClick={()=>addEvidence('decision')}>{en?'Record decision':'Καταγραφή απόφασης'}</Button></div></div><div><h3>{en?'Evidence trail':'Ιστορικό τεκμηρίωσης'}</h3><div className="stack">{events.map(e=><article className="card" key={e.id}><strong>{e.event_type}</strong><small>{new Date(e.created_at).toLocaleString(language==='el'?'el-GR':'en-GB')}</small><p>{e.payload?.text||e.payload?.action||e.payload?.to||'—'}</p></article>)}</div></div></div></ObserverDialog>}
  {creating&&<ObserverDialog width="wide" title={en?'New outbreak investigation':'Νέα διερεύνηση πιθανής έξαρσης'} onClose={()=>setCreating(false)} footer={<DialogActions showCancel onCancel={()=>setCreating(false)} onSave={create} disabled={!form.title.trim()}/>}><div className="form-grid"><label>{en?'Title':'Τίτλος'}<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>{en?'Organism':'Μικροοργανισμός'}<input value={form.organism} onChange={e=>setForm({...form,organism:e.target.value})}/></label><ManualDateField label={en?'From':'Από'} value={form.from} onChange={value=>setForm({...form,from:value})}/><ManualDateField label={en?'To':'Έως'} value={form.to} onChange={value=>setForm({...form,to:value})}/><label>Case definition ID<input value={form.definitionId} onChange={e=>setForm({...form,definitionId:e.target.value})}/></label><label>{en?'Definition version':'Έκδοση definition'}<input value={form.definitionVersion} onChange={e=>setForm({...form,definitionVersion:e.target.value})}/></label></div></ObserverDialog>}
 </section>
}
