import {useEffect,useMemo,useRef,useState} from 'react'
import {BrainCircuit,Plus,Sparkles} from 'lucide-react'
import {Button} from '../../design-system/Button'
import {FilterBar} from '../../design-system/FilterBar'
import {RegistryTable} from '../../design-system/RegistryTable'
import {RecordDetailsGrid} from '../../design-system/RecordDetailsGrid'
import {PrintExportActions} from '../../design-system/PrintExportActions'
import {exportElementAsPdf} from '../../core/export/pdfReportExport'
import {LiraOutbreakReport} from '../lira/LiraOutbreakReport'
import {ManualDateField} from '../../design-system/ManualDateField'
import {ObserverDialog,DialogActions} from '../../design-system/ObserverDialog'
import {useLanguage} from '../../core/i18n/LanguageContext'
import {useTenant} from '../../core/tenant/TenantContext'
import {useFeedback} from '../../core/feedback/FeedbackContext'
import {loadLiraData} from '../lira/liraDataLayer'
import {buildOutbreakClosureReadiness} from '../lira/liraOutbreakClosure'
import {buildInvestigationCopilot} from '../lira/liraInvestigationCopilot'
import {buildOutbreakLineList,buildOutbreakTimeline,evaluateOutbreakCaseDefinition} from '../lira/liraOutbreakInvestigation'
import {listOutbreakInvestigations,createOutbreakInvestigation,updateOutbreakInvestigation,appendOutbreakInvestigationEvent,loadOutbreakInvestigationEvents,loadOutbreakCaseReviews,createOutbreakCaseReview,loadOutbreakActions,createOutbreakAction,updateOutbreakActionStatus} from '../lira/liraOutbreakWorkspace'
const statusLabel=(s,en)=>({draft:en?'Draft':'Πρόχειρη',active:en?'Active':'Ενεργή',closed:en?'Closed':'Κλειστή'}[s]||s)
const caseDefinitionLabel=en=>en?'Case definition':'Ορισμός περιστατικού'
const actionStatusLabel=(s,en)=>({open:en?'Open':'Ανοικτή',in_progress:en?'In progress':'Σε εξέλιξη',verification:en?'Verification':'Σε επαλήθευση',closed:en?'Closed':'Κλειστή'}[s]||s)
const priorityLabel=(p,en)=>({low:en?'Low':'Χαμηλή',medium:en?'Medium':'Μέτρια',high:en?'High':'Υψηλή',critical:en?'Critical':'Κρίσιμη'}[p]||p)
const actionTypeLabel=(t,en)=>({corrective:en?'Corrective':'Διορθωτική',preventive:en?'Preventive':'Προληπτική'}[t]||t)
const classificationLabel=(c,en)=>({suspected:en?'Suspected':'Πιθανό',probable:en?'Probable':'Πιθανολογούμενο',confirmed:en?'Confirmed':'Επιβεβαιωμένο',excluded:en?'Excluded':'Αποκλεισμένο'}[c]||c)
const fmtDay=(value,en)=>value?new Intl.DateTimeFormat(en?'en-GB':'el-GR').format(new Date(`${String(value).slice(0,10)}T12:00:00`)):'—'
const statusTone=s=>s==='active'?'active':s==='closed'?'danger':'temporary'
const blockerLabel=(code,en)=>({unreviewed_candidates:en?'Unreviewed candidates':'Μη αξιολογημένα υποψήφια',open_actions:en?'Open actions':'Ανοικτές ενέργειες',unresolved_hypotheses:en?'Unresolved hypotheses':'Ανεπίλυτες υποθέσεις'}[code]||code)
const timelineTypeLabel=(t,en)=>({microbiology:en?'Microbiology':'Μικροβιολογία',hai:'HAI',device:en?'Device':'Συσκευή',isolation:en?'Isolation':'Απομόνωση'}[t]||t)
const eventTypeLabel=(t,en)=>({status:en?'Status':'Κατάσταση',note:en?'Note':'Σημείωση',hypothesis:en?'Hypothesis':'Υπόθεση',decision:en?'Decision':'Απόφαση',case_review:en?'Case review':'Αξιολόγηση περιστατικού',evidence:en?'Evidence':'Τεκμήριο'}[t]||t)
function eventText(e,en){const p=e.payload||{};if(p.text)return p.text;if(p.action==='created')return en?'Investigation created':'Δημιουργία διερεύνησης';if(p.action==='capa_created')return `${en?'CAPA created':'Δημιουργία CAPA'}${p.title?`: ${p.title}`:''}`;if(p.action==='capa_status')return `${en?'CAPA status':'Κατάσταση CAPA'} → ${actionStatusLabel(p.status,en)}`;if(p.action==='lira_signal_handoff')return en?'Started from a LIRA signal':'Έναρξη από σήμα της LIRA';if(e.event_type==='status'&&p.to)return `${statusLabel(p.from,en)} → ${statusLabel(p.to,en)}`;if(e.event_type==='case_review')return `${p.recordKey||''} · ${classificationLabel(p.classification,en)}`;return '—'}
export function LiraOutbreakInvestigationsPanel(){
 const reportRef=useRef(null)
 const {language}=useLanguage(),en=language==='en';const {tenant,isDemo}=useTenant();const {notify}=useFeedback()
 const [rows,setRows]=useState([]),[selected,setSelected]=useState(null),[events,setEvents]=useState([]),[query,setQuery]=useState(''),[creating,setCreating]=useState(false),[note,setNote]=useState(''),[lineList,setLineList]=useState(null),[timeline,setTimeline]=useState([]),[caseReview,setCaseReview]=useState(null),[evidenceLoading,setEvidenceLoading]=useState(false),[reviews,setReviews]=useState([]),[reviewing,setReviewing]=useState(null),[reviewForm,setReviewForm]=useState({classification:'suspected',rationale:''}),[actions,setActions]=useState([]),[actionForm,setActionForm]=useState({title:'',owner:'',dueDate:'',priority:'medium',actionType:'corrective',description:''}),[addingAction,setAddingAction]=useState(false),[closing,setClosing]=useState(false),[closureNote,setClosureNote]=useState('')
 const [form,setForm]=useState({title:'',organism:'',from:'',to:'',definitionId:'',definitionVersion:''})
 async function load(){if(!tenant?.id||isDemo)return;try{setRows(await listOutbreakInvestigations(tenant.id))}catch(e){notify(e.message,'error')}}
 useEffect(()=>{load()},[tenant?.id,isDemo])
 const closure=useMemo(()=>buildOutbreakClosureReadiness({lineList,caseReviews:reviews,actions,events}),[lineList,reviews,actions,events])
 const copilot=useMemo(()=>buildInvestigationCopilot({investigation:selected,lineList,caseReviews:reviews,actions,events,closure,language}),[selected,lineList,reviews,actions,events,closure,language])
 function runCopilotSuggestion(item){if(item.target==='closure'){setClosing(true);return}const ids={'line-list':'lira-investigation-line-list',capa:'lira-investigation-capa',hypotheses:'lira-investigation-hypotheses',evidence:'lira-investigation-evidence'};document.getElementById(ids[item.target])?.scrollIntoView({behavior:'smooth',block:'start'})}
 const filtered=useMemo(()=>rows.filter(x=>!query||[x.title,x.organism,x.status].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase()))),[rows,query])
 async function open(row){setSelected(row);setEvidenceLoading(true);try{const [history,data,caseReviews,ipcActions]=await Promise.all([loadOutbreakInvestigationEvents(row.id),loadLiraData({organizationId:tenant.id}),loadOutbreakCaseReviews(row.id),loadOutbreakActions(tenant.id,row.id)]);setEvents(history);setReviews(caseReviews);setActions(ipcActions);const list=buildOutbreakLineList(data,{from:row.scope_from,to:row.scope_to,organism:row.organism||null});setLineList(list);setTimeline(buildOutbreakTimeline(list));setCaseReview(evaluateOutbreakCaseDefinition(list,{...(row.definition_json||{}),id:row.definition_id,version:row.definition_version,organism:row.definition_json?.organism||row.organism||null,from:row.definition_json?.from||row.scope_from||null,to:row.definition_json?.to||row.scope_to||null}))}catch(e){notify(e.message,'error');setLineList(null);setTimeline([]);setCaseReview(null)}finally{setEvidenceLoading(false)}}
 async function create(){if(!form.title.trim())return;try{const definition=form.definitionId&&form.definitionVersion?{id:form.definitionId,version:form.definitionVersion}:null;const row=await createOutbreakInvestigation(tenant.id,{title:form.title.trim(),organism:form.organism.trim()||null,from:form.from||null,to:form.to||null,definition});await appendOutbreakInvestigationEvent(tenant.id,row.id,'status',{status:'draft',action:'created'});setCreating(false);setForm({title:'',organism:'',from:'',to:'',definitionId:'',definitionVersion:''});await load();await open(row);notify(en?'Investigation created.':'Η διερεύνηση δημιουργήθηκε.','success')}catch(e){notify(e.message,'error')}}
 async function changeStatus(status){try{const patch={status};if(status==='closed')patch.closed_at=new Date().toISOString();const row=await updateOutbreakInvestigation(selected.id,patch);await appendOutbreakInvestigationEvent(tenant.id,selected.id,'status',{from:selected.status,to:status});setSelected(row);setEvents(await loadOutbreakInvestigationEvents(row.id));load()}catch(e){notify(e.message,'error')}}
 async function closeInvestigation(){if(!closure.ready||!closureNote.trim())return;try{await appendOutbreakInvestigationEvent(tenant.id,selected.id,'decision',{action:'closure_review',text:closureNote.trim(),readiness:closure.counts});setClosing(false);setClosureNote('');await changeStatus('closed');notify(en?'Investigation closed after human readiness review.':'Η διερεύνηση έκλεισε μετά από ανθρώπινο έλεγχο ετοιμότητας.','success')}catch(e){notify(e.message,'error')}}
 async function saveCaseReview(){if(!reviewing||!reviewForm.rationale.trim())return;try{const prior=[...reviews].reverse().find(x=>x.record_key===reviewing.recordKey);await createOutbreakCaseReview(tenant.id,selected.id,{recordKey:reviewing.recordKey,patientId:reviewing.patientKey,classification:reviewForm.classification,rationale:reviewForm.rationale.trim(),supersedesReviewId:prior?.id||null});await appendOutbreakInvestigationEvent(tenant.id,selected.id,'case_review',{recordKey:reviewing.recordKey,classification:reviewForm.classification});setReviews(await loadOutbreakCaseReviews(selected.id));setEvents(await loadOutbreakInvestigationEvents(selected.id));setReviewing(null);setReviewForm({classification:'suspected',rationale:''});notify(en?'Case review recorded.':'Η αξιολόγηση περιστατικού καταγράφηκε.','success')}catch(e){notify(e.message,'error')}}
 async function saveAction(){if(!selected||!actionForm.title.trim())return;try{const action=await createOutbreakAction(tenant.id,selected.id,actionForm);await appendOutbreakInvestigationEvent(tenant.id,selected.id,'decision',{action:'capa_created',capaId:action.id,title:action.title});setActions(await loadOutbreakActions(tenant.id,selected.id));setAddingAction(false);setActionForm({title:'',owner:'',dueDate:'',priority:'medium',actionType:'corrective',description:''});notify(en?'IPC/CAPA action created.':'Η ενέργεια IPC/CAPA δημιουργήθηκε.','success')}catch(e){notify(e.message,'error')}}
 async function changeActionStatus(action,status){try{await updateOutbreakActionStatus(tenant.id,action.id,status);await appendOutbreakInvestigationEvent(tenant.id,selected.id,'decision',{action:'capa_status',capaId:action.id,status});setActions(await loadOutbreakActions(tenant.id,selected.id));setEvents(await loadOutbreakInvestigationEvents(selected.id))}catch(e){notify(e.message,'error')}}
 async function addEvidence(type){if(!note.trim())return;try{await appendOutbreakInvestigationEvent(tenant.id,selected.id,type,{text:note.trim()});setNote('');setEvents(await loadOutbreakInvestigationEvents(selected.id));notify(en?'Recorded.':'Καταγράφηκε.','success')}catch(e){notify(e.message,'error')}}
 return <section className="management-section management-scroll-section">
  <div className="section-toolbar"><div><h2>{en?'Outbreak investigations':'Διερευνήσεις πιθανής έξαρσης'}</h2><p>{en?'Investigate a possible outbreak with a fixed case definition and a complete, unalterable evidence trail.':'Διερεύνηση πιθανής έξαρσης με σταθερό ορισμό περιστατικού και πλήρες, αμετάβλητο ιστορικό τεκμηρίωσης.'}</p></div><Button disabled={isDemo} onClick={()=>setCreating(true)}><Plus size={16}/>{en?'New investigation':'Νέα διερεύνηση'}</Button></div>
  <FilterBar compact query={query} onQueryChange={setQuery} placeholder={en?'Search investigations…':'Αναζήτηση διερευνήσεων…'} onClear={()=>setQuery('')}/>
  <RegistryTable
   wrapperClassName="table-wrap scroll-table"
   columns={[{key:'title',label:en?'Investigation':'Διερεύνηση'},{key:'organism',label:en?'Organism':'Μικροοργανισμός'},{key:'period',label:en?'Period':'Περίοδος'},{key:'definition',label:caseDefinitionLabel(en)},{key:'status',label:en?'Status':'Κατάσταση'}]}
   rows={filtered}
   rowKey={x=>x.id}
   rowProps={x=>({className:'clickable-row',tabIndex:0,onClick:()=>open(x),onKeyDown:e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(x)}}})}
   renderRow={x=><><td><strong>{x.title}</strong></td><td>{x.organism||'—'}</td><td>{x.scope_from||'—'} → {x.scope_to||'—'}</td><td>{x.definition_id?x.definition_id+' · '+x.definition_version:'—'}</td><td><span className={'status-badge '+(x.status==='active'?'active':x.status==='closed'?'danger':'temporary')}>{statusLabel(x.status,en)}</span></td></>}
   emptyTitle={en?'No investigations yet':'Δεν υπάρχουν διερευνήσεις'}
   emptyText={isDemo?(en?'Outbreak investigations are recorded in the hospital workspace; the demo is read-only.':'Οι διερευνήσεις καταγράφονται στο περιβάλλον του νοσοκομείου· το demo είναι μόνο για προβολή.'):(en?'Start one with “New investigation”.':'Ξεκινήστε με «Νέα διερεύνηση».')}
  />
  {selected&&<ObserverDialog presentation="workspace" width="workspace" className="outbreak-workspace-dialog" eyebrow={en?'OUTBREAK INVESTIGATION':'ΔΙΕΡΕΥΝΗΣΗ ΕΞΑΡΣΗΣ'} title={selected.title} subtitle={[selected.organism,statusLabel(selected.status,en)].filter(Boolean).join(' · ')} onClose={()=>setSelected(null)} footer={<DialogActions><Button variant="secondary" onClick={()=>setSelected(null)}>{en?'Close':'Κλείσιμο'}</Button>{selected.status==='draft'&&<Button onClick={()=>changeStatus('active')}>{en?'Start investigation':'Έναρξη διερεύνησης'}</Button>}{selected.status==='active'&&<Button variant="danger" onClick={()=>setClosing(true)}>{en?'Review closure':'Έλεγχος κλεισίματος'}</Button>}</DialogActions>}>
   <div className="outbreak-workspace">
    <section className="record-section outbreak-summary"><div className="record-section-header"><div><span className="eyebrow">{en?'SCOPE':'ΕΥΡΟΣ'}</span><h3>{en?'Investigation details':'Στοιχεία διερεύνησης'}</h3></div><PrintExportActions onPrint={()=>window.print()} onExport={()=>exportElementAsPdf({element:reportRef.current,filename:'outbreak-investigation-'+selected.id,orientation:'landscape'})}/></div>
     <RecordDetailsGrid fields={[{id:'period',label:en?'Period':'Περίοδος',value:`${fmtDay(selected.scope_from,en)} → ${fmtDay(selected.scope_to,en)}`},{id:'definition',label:caseDefinitionLabel(en),value:selected.definition_id?selected.definition_id+' · v'+selected.definition_version:'—'},{id:'status',label:en?'Status':'Κατάσταση',value:<span className={'status-badge '+statusTone(selected.status)}>{statusLabel(selected.status,en)}</span>},{id:'events',label:en?'Evidence entries':'Εγγραφές τεκμηρίωσης',value:events.length}]}/>
    </section>
    <section className="record-section outbreak-copilot"><div className="record-section-header"><div><span className="eyebrow">LIRA</span><h3><BrainCircuit size={16}/> {en?'LIRA investigation assistant':'Βοηθός διερεύνησης LIRA'}</h3><p>{copilot.summary}</p></div><span className="status-badge"><Sparkles size={13}/> {en?'Bound to this investigation':'Συνδεδεμένη με αυτή τη διερεύνηση'}</span></div>
     {copilot.suggestions.length>0&&<div className="outbreak-chip-row">{copilot.suggestions.map(item=><Button key={item.id} variant="secondary" onClick={()=>runCopilotSuggestion(item)}>{item.label}</Button>)}</div>}
     <small className="muted">{en?'Suggestions navigate governed work only. LIRA does not classify cases, change CAPA, or close an investigation autonomously.':'Οι προτάσεις οδηγούν μόνο σε ελεγχόμενες εργασίες. Η LIRA δεν ταξινομεί περιστατικά, δεν αλλάζει CAPA και δεν κλείνει διερεύνηση αυτόνομα.'}</small>
    </section>
    <section className="record-section outbreak-readiness"><div className="record-section-header"><div><span className="eyebrow">{en?'READINESS':'ΕΤΟΙΜΟΤΗΤΑ'}</span><h3>{en?'Investigation dashboard':'Πίνακας διερεύνησης'}</h3><p>{en?'Automatic readiness indicators; closure always requires human review.':'Αυτόματοι δείκτες ετοιμότητας· το κλείσιμο απαιτεί πάντα ανθρώπινο έλεγχο.'}</p></div><span className={'status-badge '+(closure.ready?'active':'temporary')}>{closure.ready?(en?'Ready for closure review':'Έτοιμη για έλεγχο κλεισίματος'):(en?'Open items remain':'Υπάρχουν εκκρεμότητες')}</span></div>
     <div className="outbreak-metrics">{[[en?'Candidates':'Υποψήφια',closure.counts.candidates],[en?'Reviewed':'Αξιολογημένα',closure.counts.reviewed],[en?'Confirmed':'Επιβεβαιωμένα',closure.counts.confirmed],[en?'Open CAPA':'Ανοικτά CAPA',closure.counts.openActions,closure.counts.openActions>0],[en?'Overdue CAPA':'Εκπρόθεσμα CAPA',closure.counts.overdueActions,closure.counts.overdueActions>0],[en?'Unresolved hypotheses':'Ανεπίλυτες υποθέσεις',closure.counts.unresolvedHypotheses,closure.counts.unresolvedHypotheses>0]].map(([label,value,warn])=><div key={label} className={`outbreak-metric ${warn?'is-warning':''}`}><span>{label}</span><strong>{value}</strong></div>)}</div>
     {!closure.ready&&closure.blockers.length>0&&<div className="outbreak-blockers">{closure.blockers.map(b=><span key={b.code} className="status-badge temporary">{blockerLabel(b.code,en)}: {b.count}</span>)}</div>}
    </section>
    <section id="lira-investigation-line-list" className="record-section"><div className="record-section-header"><div><span className="eyebrow">{en?'CASES':'ΠΕΡΙΣΤΑΤΙΚΑ'}</span><h3>{en?'Case line list':'Κατάλογος περιστατικών'}</h3><p>{en?'Candidate criteria never confirm an outbreak case automatically.':'Τα αυτόματα κριτήρια δεν επιβεβαιώνουν αυτόματα περιστατικό έξαρσης.'}</p></div></div>
     {evidenceLoading?<div className="inline-empty">{en?'Loading authorized evidence…':'Φόρτωση εξουσιοδοτημένων δεδομένων…'}</div>:<RegistryTable wrapperClassName="table-wrap" columns={[{key:'date',label:en?'Date':'Ημερομηνία'},{key:'patient',label:en?'Patient':'Ασθενής'},{key:'department',label:en?'Department':'Τμήμα'},{key:'organism',label:en?'Organism / specimen':'Μικροοργανισμός / δείγμα'},{key:'hai',label:'HAI'},{key:'devices',label:en?'Devices / isolation':'Συσκευές / απομόνωση'},{key:'review',label:en?'Case review':'Αξιολόγηση περιστατικού'}]} rows={lineList?.rows||[]} rowKey={row=>row.recordKey} renderRow={row=>{const review=caseReview?.cases?.find(x=>x.recordKey===row.recordKey);const human=[...reviews].reverse().find(x=>x.record_key===row.recordKey);return <><td>{fmtDay(row.eventDate,en)}</td><td>{row.patientKey||'—'}</td><td>{row.department||'—'}</td><td><strong>{row.organism||'—'}</strong><small>{row.specimenType||'—'}</small></td><td>{row.hai.map(x=>x.type).join(', ')||'—'}</td><td>{[...row.devices.map(x=>x.type),...row.isolation.map(()=>en?'Isolation':'Απομόνωση')].join(', ')||'—'}</td><td><button type="button" className={`status-badge ${human?'active':'temporary'}`} disabled={selected.status==='closed'} onClick={()=>{setReviewing(row);setReviewForm({classification:human?.classification||'suspected',rationale:''})}}>{human?classificationLabel(human.classification,en):(review?.classification==='meets_machine_readable_criteria'?(en?'Criteria met · review required':'Πληροί κριτήρια · απαιτείται έλεγχος'):(en?'Unclassified':'Μη ταξινομημένο'))}</button></td></>}} emptyTitle={en?'No matching microbiology records in scope.':'Δεν βρέθηκαν αντίστοιχες μικροβιολογικές εγγραφές.'}/>}
    </section>
    <section className="record-section"><div className="record-section-header"><div><span className="eyebrow">{en?'TIMELINE':'ΧΡΟΝΟΓΡΑΜΜΗ'}</span><h3>{en?'Person–place–time timeline':'Χρονογραμμή πρόσωπο–τόπος–χρόνος'}</h3></div></div>
     {!timeline.length?<div className="inline-empty">{en?'No events in scope yet.':'Δεν υπάρχουν ακόμη συμβάντα στο εύρος.'}</div>:<ol className="outbreak-timeline">{timeline.map((item,index)=><li key={item.type+'-'+item.recordKey+'-'+index}><time>{fmtDay(item.date,en)}</time><span className="status-badge">{timelineTypeLabel(item.type,en)}</span><span>{item.department||'—'} · {item.label||'—'}</span></li>)}</ol>}
    </section>
    <section id="lira-investigation-capa" className="record-section"><div className="record-section-header"><div><span className="eyebrow">CAPA</span><h3>{en?'Investigation actions / CAPA':'Ενέργειες διερεύνησης / CAPA'}</h3><p>{en?'Actions are linked to the Quality CAPA registry.':'Οι ενέργειες συνδέονται με το μητρώο CAPA της Ποιότητας.'}</p></div>{selected.status==='active'&&<Button onClick={()=>setAddingAction(true)}><Plus size={16}/>{en?'New action':'Νέα ενέργεια'}</Button>}</div>
     <RegistryTable wrapperClassName="table-wrap" columns={[{key:'action',label:en?'Action':'Ενέργεια'},{key:'owner',label:en?'Owner':'Υπεύθυνος'},{key:'due',label:en?'Due':'Προθεσμία'},{key:'priority',label:en?'Priority':'Προτεραιότητα'},{key:'status',label:en?'Status':'Κατάσταση'}]} rows={actions} rowKey={a=>a.id} renderRow={a=><><td><strong>{a.title}</strong>{a.code&&<small>{a.code}</small>}</td><td>{a.owner_label||a.owner||'—'}</td><td>{fmtDay(a.due_date,en)}</td><td><span className={`status-badge ${['high','critical'].includes(a.priority)?'danger':'temporary'}`}>{priorityLabel(a.priority,en)}</span></td><td><select className="outbreak-status-select" disabled={selected.status==='closed'} aria-label={en?'Action status':'Κατάσταση ενέργειας'} value={a.status} onChange={e=>changeActionStatus(a,e.target.value)}><option value="open">{actionStatusLabel('open',en)}</option><option value="in_progress">{actionStatusLabel('in_progress',en)}</option><option value="verification">{actionStatusLabel('verification',en)}</option><option value="closed">{actionStatusLabel('closed',en)}</option></select></td></>} emptyTitle={en?'No linked actions.':'Δεν υπάρχουν συνδεδεμένες ενέργειες.'}/>
    </section>
    <section id="lira-investigation-hypotheses" className="record-section"><div className="record-section-header"><div><span className="eyebrow">{en?'REASONING':'ΣΚΕΠΤΙΚΟ'}</span><h3>{en?'Hypotheses / decisions':'Υποθέσεις / αποφάσεις'}</h3></div></div>
     <textarea className="outbreak-note" rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder={en?'Record a hypothesis or decision…':'Καταγραφή υπόθεσης ή απόφασης…'}/>
     <div className="outbreak-note-actions"><Button variant="secondary" disabled={!note.trim()} onClick={()=>addEvidence('hypothesis')}>{en?'Add hypothesis':'Προσθήκη υπόθεσης'}</Button><Button disabled={!note.trim()} onClick={()=>addEvidence('decision')}>{en?'Record decision':'Καταγραφή απόφασης'}</Button></div>
    </section>
    <section id="lira-investigation-evidence" className="record-section"><div className="record-section-header"><div><span className="eyebrow">{en?'AUDIT':'ΙΣΤΟΡΙΚΟ'}</span><h3>{en?'Evidence trail':'Ιστορικό τεκμηρίωσης'}</h3><p>{en?'Append-only: entries cannot be edited or removed.':'Οι εγγραφές δεν τροποποιούνται ούτε διαγράφονται.'}</p></div></div>
     {!events.length?<div className="inline-empty">{en?'No entries yet.':'Δεν υπάρχουν ακόμη εγγραφές.'}</div>:<ol className="outbreak-evidence">{events.map(e=><li key={e.id}><span className="status-badge">{eventTypeLabel(e.event_type,en)}</span><div><strong>{eventText(e,en)}</strong><time>{new Date(e.created_at).toLocaleString(en?'en-GB':'el-GR')}</time></div></li>)}</ol>}
    </section>
    <div style={{position:'fixed',left:'-20000px',top:0,pointerEvents:'none'}}><LiraOutbreakReport ref={reportRef} investigation={selected} lineList={lineList} timeline={timeline} reviews={reviews} actions={actions} events={events} language={language}/></div>
   </div>
  </ObserverDialog>}
  {closing&&<ObserverDialog width="wide" title={en?'Closure readiness review':'Έλεγχος ετοιμότητας κλεισίματος'} onClose={()=>setClosing(false)} footer={<DialogActions showCancel onCancel={()=>setClosing(false)} onSave={closeInvestigation} disabled={!closure.ready||!closureNote.trim()}/>}><div className="detail-summary-grid"><div><span>{en?'Unreviewed candidates':'Μη αξιολογημένα πιθανά περιστατικά'}</span><strong>{closure.counts.candidates-closure.counts.reviewed}</strong></div><div><span>{en?'Open actions':'Ανοικτές ενέργειες'}</span><strong>{closure.counts.openActions}</strong></div><div><span>{en?'Unresolved hypotheses':'Ανεπίλυτες υποθέσεις'}</span><strong>{closure.counts.unresolvedHypotheses}</strong></div></div>{closure.ready?<p>{en?'Deterministic checks are complete. A human closure rationale is still required.':'Οι αυτόματοι έλεγχοι ολοκληρώθηκαν. Απαιτείται ακόμη ανθρώπινη αιτιολόγηση κλεισίματος.'}</p>:<p className="muted">{en?'Resolve all blockers before closure.':'Επιλύστε όλες τις εκκρεμότητες πριν από το κλείσιμο.'}</p>}<label>{en?'Closure rationale':'Αιτιολόγηση κλεισίματος'}<textarea value={closureNote} onChange={e=>setClosureNote(e.target.value)}/></label></ObserverDialog>}
  {addingAction&&<ObserverDialog width="wide" title={en?'New IPC / CAPA action':'Νέα ενέργεια IPC / CAPA'} onClose={()=>setAddingAction(false)} footer={<DialogActions showCancel onCancel={()=>setAddingAction(false)} onSave={saveAction} disabled={!actionForm.title.trim()}/>}><div className="form-grid"><label>{en?'Title':'Τίτλος'}<input value={actionForm.title} onChange={e=>setActionForm({...actionForm,title:e.target.value})}/></label><label>{en?'Owner':'Υπεύθυνος'}<input value={actionForm.owner} onChange={e=>setActionForm({...actionForm,owner:e.target.value})}/></label><ManualDateField label={en?'Due date':'Προθεσμία'} value={actionForm.dueDate} onChange={value=>setActionForm({...actionForm,dueDate:value})}/><label>{en?'Priority':'Προτεραιότητα'}<select value={actionForm.priority} onChange={e=>setActionForm({...actionForm,priority:e.target.value})}><option value="low">{priorityLabel('low',en)}</option><option value="medium">{priorityLabel('medium',en)}</option><option value="high">{priorityLabel('high',en)}</option><option value="critical">{priorityLabel('critical',en)}</option></select></label><label>{en?'Type':'Τύπος'}<select value={actionForm.actionType} onChange={e=>setActionForm({...actionForm,actionType:e.target.value})}><option value="corrective">{actionTypeLabel('corrective',en)}</option><option value="preventive">{actionTypeLabel('preventive',en)}</option></select></label><label className="form-span-2">{en?'Description':'Περιγραφή'}<textarea value={actionForm.description} onChange={e=>setActionForm({...actionForm,description:e.target.value})}/></label></div></ObserverDialog>}
  {reviewing&&<ObserverDialog width="wide" title={en?'Human case review':'Ανθρώπινη αξιολόγηση περιστατικού'} subtitle={[reviewing.eventDate,reviewing.organism,reviewing.department].filter(Boolean).join(' · ')} onClose={()=>setReviewing(null)} footer={<DialogActions showCancel onCancel={()=>setReviewing(null)} onSave={saveCaseReview} disabled={!reviewForm.rationale.trim()}/>}><div className="form-grid"><label>{en?'Classification':'Ταξινόμηση'}<select value={reviewForm.classification} onChange={e=>setReviewForm({...reviewForm,classification:e.target.value})}><option value="suspected">{classificationLabel('suspected',en)}</option><option value="probable">{classificationLabel('probable',en)}</option><option value="confirmed">{classificationLabel('confirmed',en)}</option><option value="excluded">{classificationLabel('excluded',en)}</option></select></label><label className="form-span-2">{en?'Rationale':'Αιτιολόγηση'}<textarea value={reviewForm.rationale} onChange={e=>setReviewForm({...reviewForm,rationale:e.target.value})} placeholder={en?'Required clinical/epidemiological rationale…':'Υποχρεωτική κλινική/επιδημιολογική αιτιολόγηση…'}/></label></div><p className="muted">{en?'Classification is a human-reviewed investigation decision and does not alter the source clinical record.':'Η ταξινόμηση αποτελεί ανθρώπινη απόφαση της διερεύνησης και δεν μεταβάλλει την αρχική κλινική εγγραφή.'}</p></ObserverDialog>}
  {creating&&<ObserverDialog width="wide" title={en?'New outbreak investigation':'Νέα διερεύνηση πιθανής έξαρσης'} onClose={()=>setCreating(false)} footer={<DialogActions showCancel onCancel={()=>setCreating(false)} onSave={create} disabled={!form.title.trim()}/>}><div className="form-grid"><label>{en?'Title':'Τίτλος'}<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>{en?'Organism':'Μικροοργανισμός'}<input value={form.organism} onChange={e=>setForm({...form,organism:e.target.value})}/></label><ManualDateField label={en?'From':'Από'} value={form.from} onChange={value=>setForm({...form,from:value})}/><ManualDateField label={en?'To':'Έως'} value={form.to} onChange={value=>setForm({...form,to:value})}/><label>{en?'Case definition ID':'Κωδικός ορισμού περιστατικού'}<input value={form.definitionId} onChange={e=>setForm({...form,definitionId:e.target.value})}/></label><label>{en?'Definition version':'Έκδοση ορισμού'}<input value={form.definitionVersion} onChange={e=>setForm({...form,definitionVersion:e.target.value})}/></label></div></ObserverDialog>}
 </section>
}
