import { useEffect,useState } from 'react'
import { CirclePause,KeyRound,Link2,Plus,RotateCcw,ShieldCheck,Trash2,UserPlus,UserRound,UsersRound } from 'lucide-react'
import { Button } from '../../design-system/Button'
import { SaveButton } from '../../design-system/SaveButton'
import { ObserverDialog,DialogActions } from '../../design-system/ObserverDialog'
import { useAuth } from '../../core/auth/AuthContext'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useTenant } from '../../core/tenant/TenantContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { CAPABILITIES,ROLES,can } from '../../core/permissions/roles'
import { supabase,invokeAuthenticatedFunction } from '../../core/supabase/client'
import { creatableManagementRoles,managementMemberStatusLabel,managementRoleNames } from './managementRoles'
import '../../styles/management-users.css'

export function ManagementUsersPanel(){
 const {language,t}=useLanguage(),{tenant,role,membership,isDemo,isRolePreview}=useTenant(),{user:authUser}=useAuth(),{notify,confirm}=useFeedback()
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(false),[createOpen,setCreateOpen]=useState(false),[createdUser,setCreatedUser]=useState(null),[selectedUser,setSelectedUser]=useState(null),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0)
 const currentUserId=authUser?.id||'',isPlatformOwner=role===ROLES.PLATFORM_OWNER,previewingHospitalAdmin=Boolean(isRolePreview&&role===ROLES.HOSPITAL_ADMIN)
 const canManageUsers=can(role,CAPABILITIES.MANAGE_USERS,membership?.capabilities??[],membership?.customCapabilities??[])
 const isSelfRow=u=>Boolean(!isPlatformOwner&&u?.userId===currentUserId)
 const isPreviewProtectedRow=u=>Boolean(previewingHospitalAdmin&&u?.role===ROLES.HOSPITAL_ADMIN)
 const canManageRow=u=>isPlatformOwner||!isPreviewProtectedRow(u)
 useEffect(()=>{if(isDemo||!supabase||!tenant?.id)return;let active=true;setLoading(true);(async()=>{try{const {data:members,error}=await supabase.from('organization_members').select('id,user_id,role,status').eq('organization_id',tenant.id);if(error)throw error;const ids=[...new Set((members||[]).map(x=>x.user_id).filter(Boolean))];let profiles=[];if(ids.length){const r=await supabase.from('profiles').select('id,full_name,username,contact_email,phone,job_title').in('id',ids);if(r.error)throw r.error;profiles=r.data||[]}if(!active)return;const byId=new Map(profiles.map(x=>[x.id,x]));setRows((members||[]).map(row=>{const p=byId.get(row.user_id)||{};return{id:row.id,userId:row.user_id,role:row.role,status:row.status,username:p.username||'—',name:p.full_name||'—',email:p.contact_email||''}}))}catch(e){if(active)notify(e?.message||'Αποτυχία φόρτωσης χρηστών.','error')}finally{if(active)setLoading(false)}})();return()=>{active=false}},[isDemo,tenant?.id,revision,notify])
 async function createUser(payload){try{setBusy(true);const data=await invokeAuthenticatedFunction('create-organization-user',{organizationId:tenant.id,...payload});setCreateOpen(false);setCreatedUser({...data,employeeLinked:Boolean(data?.employeeId)});setRevision(x=>x+1);notify(data?.emailSent===false?'Ο υπάρχων λογαριασμός συνδέθηκε με τον οργανισμό.':'Η πρόσκληση στάλθηκε.','success')}catch(e){notify(e?.message||'Η δημιουργία χρήστη απέτυχε.','error')}finally{setBusy(false)}}
 async function runAction(user,action,payload={}){
  if(!canManageRow(user)){notify('Η διαχείριση αυτού του λογαριασμού είναι κλειδωμένη στην προεπισκόπηση ρόλου.','warning');return}
  const self=isSelfRow(user)
  if(self&&action==='update'&&payload.role){notify('Δεν μπορείτε να αλλάξετε τον δικό σας ρόλο ή τα δικαιώματα πρόσβασης.','warning');return}
  if(self&&['suspend','reactivate','delete','resend_invitation'].includes(action)){notify('Δεν μπορείτε να αλλάξετε την κατάσταση πρόσβασης ή να διαγράψετε τον δικό σας λογαριασμό.','warning');return}
  if(action==='suspend'&&!await confirm({title:'Παύση πρόσβασης',message:`Να τεθεί σε παύση η πρόσβαση του «${user.name}»; Η καρτέλα εργαζομένου παραμένει.`,confirmLabel:'Παύση πρόσβασης'}))return
  if(action==='delete'&&!await confirm({title:'Διαγραφή λογαριασμού σύνδεσης',message:`Θα διαγραφεί μόνο ο λογαριασμός σύνδεσης του «${user.name}». Η καρτέλα εργαζομένου και το ιστορικό του διατηρούνται.`,confirmLabel:'Διαγραφή λογαριασμού',danger:true}))return
  try{setBusy(true);const result=await invokeAuthenticatedFunction('manage-organization-user',{organizationId:tenant.id,userId:user.userId,action,...payload});if(action==='delete'){setRows(v=>v.filter(x=>x.userId!==user.userId));setSelectedUser(null);return notify(result?.accountDeleted===false?'Η πρόσβαση στον οργανισμό αφαιρέθηκε. Ο λογαριασμός παραμένει ενεργός σε άλλον οργανισμό.':'Ο λογαριασμός σύνδεσης διαγράφηκε.','success')}if(action==='reset_password')return notify('Στάλθηκε email επαναφοράς κωδικού.','success');const patch={status:action==='suspend'?'disabled':action==='reactivate'?'active':user.status,role:action==='update'&&payload.role?payload.role:user.role};setRows(v=>v.map(x=>x.userId===user.userId?{...x,...patch}:x));setSelectedUser(v=>v?.userId===user.userId?{...v,...patch}:v);notify('Η πρόσβαση ενημερώθηκε.','success')}catch(e){notify(e?.message||'Η ενέργεια απέτυχε.','error')}finally{setBusy(false)}
 }
 return <section className="management-section management-scroll-section"><div className="section-toolbar"><div><h2>{t('organizationUsers')}</h2><p>{tenant?.name} · Λογαριασμοί, ρόλοι και κύκλος ζωής πρόσβασης</p></div>{canManageUsers&&!isDemo&&<Button onClick={()=>setCreateOpen(true)}><Plus size={15}/>Νέος χρήστης</Button>}</div><div className="table-wrap scroll-table"><table className="data-table sticky-table"><thead><tr><th>{t('users')}</th><th>Username</th><th>{t('roleLabel')}</th><th>{t('status')}</th><th/></tr></thead><tbody>{rows.map(u=>{const self=isSelfRow(u),previewProtected=isPreviewProtectedRow(u);return <tr key={u.id}><td><strong>{u.name}</strong><small>{u.email||'—'}</small></td><td>{u.username}</td><td><span className="role-badge">{t(managementRoleNames[u.role]??u.role)}</span></td><td><span className={`status-badge ${u.status==='active'?'active':u.status==='disabled'?'danger':'temporary'}`}>{managementMemberStatusLabel(u.status,language)}</span></td><td><button className="text-button" onClick={()=>setSelectedUser(u)}>{previewProtected?'Προβολή':t('manageUserAction')}</button>{self&&<span className="management-self-account"><ShieldCheck size={13}/>Ο λογαριασμός σας</span>}{previewProtected&&!self&&<span className="management-self-account"><ShieldCheck size={13}/>Λογαριασμός Διαχειριστή</span>}</td></tr>})}</tbody></table>{loading&&<div className="inline-empty">{t('loading')}</div>}</div>{createOpen&&<CreateUserDialog tenantId={tenant?.id} t={t} busy={busy} onClose={()=>setCreateOpen(false)} onCreate={createUser}/>} {createdUser&&<CreatedUserDialog data={createdUser} onClose={()=>setCreatedUser(null)}/>} {selectedUser&&<UserAccessDialog user={selectedUser} t={t} busy={busy} readOnly={!canManageRow(selectedUser)} selfProtected={isSelfRow(selectedUser)} previewProtected={isPreviewProtectedRow(selectedUser)} onClose={()=>setSelectedUser(null)} onAction={(a,p)=>runAction(selectedUser,a,p)}/>}</section>
}

function CreateUserDialog({tenantId,t,busy,onClose,onCreate}){
 const [mode,setMode]=useState('existing'),[employees,setEmployees]=useState([]),[employeesLoading,setEmployeesLoading]=useState(false),[form,setForm]=useState({fullName:'',role:'staff_user',email:'',phone:'',jobTitle:'',employeeDbId:'',employeeCode:'',employmentStatus:'active'})
 const set=(k,v)=>setForm(x=>({...x,[k]:v}))
 useEffect(()=>{if(!supabase||!tenantId)return;let alive=true;setEmployeesLoading(true);supabase.from('employees').select('id,user_id,employee_code,first_name,last_name,email,phone,profession_name,employment_status').eq('organization_id',tenantId).order('last_name').then(({data,error})=>{if(alive){if(!error)setEmployees((data||[]).filter(x=>!x.user_id));setEmployeesLoading(false)}});return()=>{alive=false}},[tenantId])
 const selectEmployee=id=>{const e=employees.find(x=>x.id===id);setForm(x=>({...x,employeeDbId:id,fullName:e?`${e.first_name||''} ${e.last_name||''}`.trim():x.fullName,email:e?.email||x.email,phone:e?.phone||x.phone,jobTitle:e?.profession_name||x.jobTitle}))}
 const parts=form.fullName.trim().split(/\s+/),valid=Boolean(form.fullName.trim()&&form.email.trim()&&form.role&&(mode!=='existing'||form.employeeDbId)&&(mode!=='new'||(form.employeeCode.trim()&&parts.length>1)))
 const payload={fullName:form.fullName.trim(),role:form.role,email:form.email.trim(),phone:form.phone.trim(),jobTitle:form.jobTitle.trim(),employeeDbId:mode==='existing'?form.employeeDbId||null:null,employee:mode==='new'?{create:true,employeeCode:form.employeeCode.trim(),firstName:parts[0]||'',lastName:parts.slice(1).join(' '),employmentStatus:form.employmentStatus}:undefined}
 return <ObserverDialog open width="wide" className="management-create-user-dialog" title="Νέος χρήστης" subtitle="Δημιουργία πρόσβασης και σύνδεση με το μητρώο εργαζομένων." onClose={onClose}><div className="management-create-modes"><Mode active={mode==='existing'} onClick={()=>setMode('existing')} icon={<Link2 size={18}/>} title="Σύνδεση με υπάρχοντα εργαζόμενο" text="Για εργαζόμενο που υπάρχει ήδη στο μητρώο."/><Mode active={mode==='new'} onClick={()=>setMode('new')} icon={<UserPlus size={18}/>} title="Νέα καρτέλα εργαζομένου" text="Δημιουργία εργαζομένου και πρόσβασης μαζί."/><Mode active={mode==='none'} onClick={()=>setMode('none')} icon={<UsersRound size={18}/>} title="Χωρίς καρτέλα εργαζομένου" text="Δημιουργία μόνο λογαριασμού συστήματος."/></div>{mode==='existing'&&<div className="management-create-employee-picker"><label className="field"><span>Εργαζόμενος</span><select value={form.employeeDbId} onChange={e=>selectEmployee(e.target.value)}><option value="">{employeesLoading?'Φόρτωση…':'Επιλέξτε εργαζόμενο…'}</option>{employees.map(e=><option key={e.id} value={e.id}>{e.last_name} {e.first_name} · {e.employee_code}</option>)}</select></label></div>}<CreateSection title="Στοιχεία λογαριασμού" hint="Το username δημιουργείται αυτόματα."><div className="entry-form-grid"><Field label={t('name')} value={form.fullName} disabled={mode==='existing'&&!!form.employeeDbId} onChange={v=>set('fullName',v)}/><Field label="Email" type="email" value={form.email} onChange={v=>set('email',v)}/><label className="field"><span>{t('roleLabel')}</span><select value={form.role} onChange={e=>set('role',e.target.value)}>{creatableManagementRoles.map(r=><option key={r} value={r}>{t(managementRoleNames[r]??r)}</option>)}</select></label><Field label="Τηλέφωνο" value={form.phone} onChange={v=>set('phone',v)}/><Field label="Θέση / Ιδιότητα" value={form.jobTitle} onChange={v=>set('jobTitle',v)}/></div></CreateSection>{mode==='new'&&<CreateSection title="Καρτέλα εργαζομένου" hint="Μόνο τα στοιχεία που αφορούν το μητρώο προσωπικού."><div className="entry-form-grid"><Field label="Κωδικός εργαζομένου" value={form.employeeCode} onChange={v=>set('employeeCode',v)}/><label className="field"><span>Κατάσταση εργασίας</span><select value={form.employmentStatus} onChange={e=>set('employmentStatus',e.target.value)}><option value="active">Ενεργός</option><option value="inactive">Ανενεργός</option></select></label></div></CreateSection>}<div className="management-create-invite-note"><KeyRound size={16}/><span>Ο χρήστης θα λάβει πρόσκληση ενεργοποίησης στο email του. Ο διαχειριστής δεν βλέπει ούτε διαμοιράζει κωδικό πρόσβασης.</span></div><div className="management-create-dialog-actions"><Button variant="secondary" onClick={onClose}>{t('cancel')}</Button><SaveButton disabled={busy||!valid} onClick={()=>onCreate(payload)}>{busy?'Αποστολή…':'Αποστολή πρόσκλησης'}</SaveButton></div></ObserverDialog>
}
function Mode({active,onClick,icon,title,text}){return <button type="button" className={active?'active':''} onClick={onClick}>{icon}<span><strong>{title}</strong><small>{text}</small></span></button>}
function CreateSection({title,hint,children}){return <div className="management-create-section"><div className="management-create-section-title"><strong>{title}</strong><span>{hint}</span></div>{children}</div>}
function Field({label,value,onChange,type='text',disabled=false}){return <label className="field"><span>{label}</span><input type={type} value={value} disabled={disabled} onChange={e=>onChange(e.target.value)}/></label>}
function CreatedUserDialog({data,onClose}){return <ObserverDialog open width="compact" title="Η πρόσκληση ολοκληρώθηκε" onClose={onClose}><div className="management-invite-result"><ShieldCheck size={28}/><strong>{data.emailSent===false?'Ο λογαριασμός συνδέθηκε':'Η πρόσκληση στάλθηκε'}</strong><p>{data.emailSent===false?'Υπάρχων λογαριασμός συνδέθηκε με τον οργανισμό.':'Ο χρήστης θα ενεργοποιήσει την πρόσβασή του από την πρόσκληση που έλαβε στο email.'}</p><small>Username: {data.username||'—'}</small>{data.employeeLinked&&<small>Η καρτέλα εργαζομένου συνδέθηκε.</small>}</div><DialogActions><Button onClick={onClose}>Κλείσιμο</Button></DialogActions></ObserverDialog>}
function UserAccessDialog({user,t,busy,readOnly=false,selfProtected=false,previewProtected=false,onClose,onAction}){const [role,setRole]=useState(user.role),changed=role!==user.role,active=user.status==='active',rightsLocked=readOnly||selfProtected;return <ObserverDialog open width="standard" className="management-user-dialog" title="Πρόσβαση χρήστη" subtitle={user.name} onClose={onClose}><div className="management-user-summary"><div className="management-user-identity"><div className="management-user-avatar"><UserRound size={20}/></div><div><strong>{user.name}</strong><div className="management-user-identity-meta"><span>{user.username}</span><span>·</span><span>{user.email||'—'}</span></div></div></div><span className={`status-badge ${active?'active':'danger'}`}>{managementMemberStatusLabel(user.status,'el')}</span></div>{(readOnly||selfProtected)&&<div className="management-user-preserve-note"><ShieldCheck size={15}/><span>{previewProtected?'Βλέπετε την εφαρμογή ως Διαχειριστής Νοσοκομείου. Ο λογαριασμός του Διαχειριστή είναι μόνο για προβολή στην προεπισκόπηση ρόλου.':'Ο δικός σας ρόλος και τα δικαιώματα πρόσβασης είναι κλειδωμένα. Μπορούν να αλλάξουν μόνο από άλλον εξουσιοδοτημένο διαχειριστή ή τον Platform Owner.'}</span></div>}<div className="management-user-section"><div className="management-user-section-heading"><div><strong>Ρόλος & δικαιώματα</strong><p>Καθορίζει τι μπορεί να βλέπει και να διαχειρίζεται ο χρήστης.</p></div></div><div className="management-user-role-row"><label className="field"><span>{t('roleLabel')}</span><select value={role} disabled={rightsLocked} onChange={e=>setRole(e.target.value)}>{creatableManagementRoles.map(r=><option key={r} value={r}>{t(managementRoleNames[r]??r)}</option>)}</select></label>{!rightsLocked&&<SaveButton disabled={busy||!changed} onClick={()=>onAction('update',{role})}>Αποθήκευση ρόλου</SaveButton>}</div></div>{!readOnly&&<div className="management-user-actions"><Action icon={<KeyRound size={15}/>} title="Επαναφορά κωδικού" text="Αποστολή email επαναφοράς κωδικού." action={<Button variant="secondary" disabled={busy} onClick={()=>onAction('reset_password')}>Αποστολή</Button>}/>{!selfProtected&&<><Action icon={active?<CirclePause size={15}/>:<RotateCcw size={15}/>} title={active?'Παύση πρόσβασης':'Ενεργοποίηση πρόσβασης'} text="Δεν επηρεάζει την καρτέλα εργαζομένου." action={<Button variant="secondary" disabled={busy} onClick={()=>onAction(active?'suspend':'reactivate')}>{active?'Παύση':'Ενεργοποίηση'}</Button>}/><Action danger icon={<Trash2 size={15}/>} title="Διαγραφή λογαριασμού σύνδεσης" text="Η καρτέλα και το ιστορικό εργαζομένου διατηρούνται." action={<Button variant="danger" disabled={busy} onClick={()=>onAction('delete')}>Διαγραφή</Button>}/></>}</div>}<div className="management-user-dialog-actions"><Button variant="secondary" onClick={onClose}>Κλείσιμο</Button></div></ObserverDialog>}
function Action({icon,title,text,action,danger=false}){return <div className={`management-user-action-row${danger?' danger':''}`}><div className="management-user-action-copy"><span className="management-user-action-icon">{icon}</span><div><strong>{title}</strong><span>{text}</span></div></div>{action}</div>}
