import { useEffect,useMemo,useState } from 'react'
import { Activity,Bell,Building2,Database,FileCheck2,Globe2,KeyRound,Layers3,Pencil,Plus,ShieldCheck,Trash2,Users,X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Page } from '../../design-system/Page'
import { Button } from '../../design-system/Button'
import { SaveButton } from '../../design-system/SaveButton'
import { ObserverDialog,DialogActions } from '../../design-system/ObserverDialog'
import { BedDaysPanel } from './BedDaysPanel'
import { LibrariesPanel } from './LibrariesPanel'
import { BundleLibraryPanel } from './BundleLibraryPanel'
import { AnnouncementsPanel } from './AnnouncementsPanel'
import { OrganizationProfilePanel } from './OrganizationProfilePanel'
import { IndicatorsPanel } from './IndicatorsPanel'
import { capabilityLabel } from '../../core/permissions/capabilityLabels'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useTenant } from '../../core/tenant/TenantContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { CAPABILITIES,ROLES,can } from '../../core/permissions/roles'
import { capabilityCatalogue,isCustomRoleEligible } from '../../core/permissions/capabilityCatalogue'
import { demoUsers,externalSources } from './managementData'
import { supabase,invokeAuthenticatedFunction } from '../../core/supabase/client'
import { createCustomRole,deactivateCustomRole,loadCustomRoles,loadExternalReferences,removeExternalReference,updateCustomRole,updateExternalReference } from './managementCloudService'

const roleNames={platform_owner:'platformOwnerRole',hospital_admin:'hospitalAdminRole',infection_control_lead:'infectionControlLeadRole',infection_control_member:'infectionControlMemberRole',department_manager:'departmentManagerRole',department_user:'departmentUserRole',laboratory:'laboratoryRole',committee_secretariat:'committeeSecretariatRole',hr_office:'hrOfficeRole',pharmacy:'pharmacyRole',occupational_physician:'occupationalPhysicianRole',doctor_reviewer:'doctorReviewerRole',quality_manager:'qualityManagerRole',link_nurse:'linkNurseRole',staff_user:'staffUserRole',demo:'demoRole'}
const creatableRoles=['hospital_admin','infection_control_lead','infection_control_member','department_manager','department_user','laboratory','committee_secretariat','hr_office','pharmacy','occupational_physician','doctor_reviewer','quality_manager','link_nurse','staff_user']

export function ManagementPage(){
 const {language,t}=useLanguage();const {tenant,role,membership,isDemo}=useTenant();const {notify,confirm}=useFeedback();const navigate=useNavigate();const isPlatformOwner=role===ROLES.PLATFORM_OWNER
 const [tab,setTab]=useState('overview');const [roleModal,setRoleModal]=useState(false);const [roleEditingId,setRoleEditingId]=useState(null);const [references,setReferences]=useState(isDemo?externalSources:[]);const [referenceEditor,setReferenceEditor]=useState(null);const [customRoles,setCustomRoles]=useState([]);const [roleName,setRoleName]=useState('');const [selectedCaps,setSelectedCaps]=useState([]);const [managementLoading,setManagementLoading]=useState(false)
 const [orgUsers,setOrgUsers]=useState([]);const [orgUsersLoading,setOrgUsersLoading]=useState(false);const [createUserOpen,setCreateUserOpen]=useState(false);const [createdUser,setCreatedUser]=useState(null);const [selectedUser,setSelectedUser]=useState(null)
 useEffect(()=>{if(isDemo){setReferences(externalSources);setCustomRoles([]);return}if(!tenant?.id||!['roles','references'].includes(tab))return;let active=true;setManagementLoading(true);(async()=>{try{const rows=tab==='roles'?await loadCustomRoles(tenant.id):await loadExternalReferences(tenant.id);if(active)(tab==='roles'?setCustomRoles:setReferences)(rows)}catch(error){if(active)notify(error?.message||t('managementPanel.loadFailed'),'error')}finally{if(active)setManagementLoading(false)}})();return()=>{active=false}},[isDemo,tenant?.id,tab,notify,t])
 useEffect(()=>{if(isDemo||!supabase||!tenant?.id||tab!=='users')return;let active=true;setOrgUsersLoading(true);(async()=>{const {data:memberRows,error}=await supabase.from('organization_members').select('id,user_id,role,status').eq('organization_id',tenant.id);if(!active)return;if(error){setOrgUsersLoading(false);return}const ids=[...new Set((memberRows||[]).map(x=>x.user_id).filter(Boolean))];let profiles=[];if(ids.length){const result=await supabase.from('profiles').select('id,full_name,username,contact_email,phone,job_title').in('id',ids);profiles=result.data||[]}const byId=new Map(profiles.map(x=>[x.id,x]));setOrgUsers((memberRows||[]).map(row=>{const p=byId.get(row.user_id)||{};return{id:row.id,userId:row.user_id,role:row.role,status:row.status,username:p.username||'—',name:p.full_name||'—',email:p.contact_email||'',phone:p.phone||'',jobTitle:p.job_title||''}}));setOrgUsersLoading(false)})();return()=>{active=false}},[isDemo,tenant?.id,tab,createdUser])
 async function createUser({fullName,role:newRole,email,phone,jobTitle,employee}){if(!supabase||!tenant?.id)return;try{const data=await invokeAuthenticatedFunction('create-organization-user',{organizationId:tenant.id,fullName,role:newRole,email,phone,jobTitle,employee});setCreatedUser({...data,employeeCreated:Boolean(data?.employeeId)});setCreateUserOpen(false);notify(employee?.create?(language==='en'?'Employee and user account created.':'Ο εργαζόμενος και ο λογαριασμός χρήστη δημιουργήθηκαν.'):(language==='en'?'User account created.':'Ο λογαριασμός χρήστη δημιουργήθηκε.'),'success')}catch(error){notify(error?.message||t('managementPanel.userCreationFailed'),'error')}}
 const addOns=useMemo(()=>membership?.capabilities??[],[membership]);const customCaps=useMemo(()=>membership?.customCapabilities??[],[membership]);const customRoleCapabilities=useMemo(()=>Object.values(capabilityCatalogue).filter(item=>isCustomRoleEligible(item.id)),[]);const allowed=cap=>can(role,cap,addOns,customCaps)
 const tabs=useMemo(()=>{const ok=cap=>can(role,cap,addOns,customCaps);return[{id:'overview',label:t('managementPanel.overviewTab'),icon:FileCheck2},...(ok(CAPABILITIES.MANAGE_ORGANIZATION)?[{id:'organization',label:t('organization'),icon:Building2}]:[]),...(ok(CAPABILITIES.MANAGE_USERS)?[{id:'users',label:t('users'),icon:Users}]:[]),...(ok(CAPABILITIES.MANAGE_ANNOUNCEMENTS)?[{id:'announcements',label:t('announcements'),icon:Bell}]:[]),...(ok(CAPABILITIES.MANAGE_LIBRARIES)?[{id:'libraries',label:t('libraries'),icon:Database},{id:'bundles',label:t('managementPanel.preventionBundlesLabel'),icon:Layers3},{id:'indicators',label:language==='en'?'Indicators':'Δείκτες',icon:Activity}]:[]),...(ok(CAPABILITIES.MANAGE_BED_DAYS)?[{id:'patientDays',label:t('patientDays'),icon:Database}]:[]),...(ok(CAPABILITIES.MANAGE_EXTERNAL_REFERENCES)?[{id:'references',label:t('externalReferences'),icon:Globe2}]:[]),...(ok(CAPABILITIES.MANAGE_ROLES)?[{id:'roles',label:t('rolesPermissions'),icon:ShieldCheck}]:[]),...(isPlatformOwner?[{id:'platform',label:language==='en'?'Platform Center':'Κέντρο Πλατφόρμας',icon:KeyRound}]:[])]},[role,addOns,customCaps,t,isPlatformOwner,language])
 useEffect(()=>{if(tabs.length&&!tabs.some(item=>item.id===tab))setTab(tabs[0].id)},[tabs,tab])
 function openTab(id){if(id==='platform'){navigate('/platform');return}setTab(id)}
 function toggleCap(cap){setSelectedCaps(current=>current.includes(cap)?current.filter(x=>x!==cap):[...current,cap])}
 function openNewCustomRole(){setRoleEditingId(null);setRoleName('');setSelectedCaps([]);setRoleModal(true)}
 function openCustomRole(item){setRoleEditingId(item.id);setRoleName(item.name||'');setSelectedCaps((item.capabilities||[]).filter(isCustomRoleEligible));setRoleModal(true)}
 function closeRoleEditor(){setRoleModal(false);setRoleEditingId(null);setRoleName('');setSelectedCaps([])}
 async function saveCustomRole(){const capabilities=selectedCaps.filter(isCustomRoleEligible);if(!roleName.trim()||!capabilities.length)return;try{let item;if(isDemo)item={id:roleEditingId||`custom-${Date.now()}`,name:roleName.trim(),capabilities};else item=roleEditingId?await updateCustomRole(tenant.id,roleEditingId,{name:roleName.trim(),capabilities}):await createCustomRole(tenant.id,{name:roleName.trim(),capabilities});setCustomRoles(current=>roleEditingId?current.map(row=>row.id===item.id?item:row):[...current,item]);const edited=Boolean(roleEditingId);closeRoleEditor();notify(edited?(language==='en'?'Custom role updated.':'Ο προσαρμοσμένος ρόλος ενημερώθηκε.'):t('customRoleCreated'),'success')}catch(error){notify(error?.message||t('managementPanel.saveFailed'),'error')}}
 async function deleteCustomRole(item){const ok=await confirm({title:t('rolesPermissions'),message:`${t('delete')} «${item.name}»`,confirmLabel:t('delete'),danger:true});if(!ok)return;try{if(!isDemo)await deactivateCustomRole(tenant.id,item.id);setCustomRoles(rows=>rows.filter(row=>row.id!==item.id));notify(t('actionCompleted'),'success')}catch(error){notify(error?.message||t('managementPanel.saveFailed'),'error')}}
 async function saveReference(){if(referenceEditor?.isGlobal&&!isPlatformOwner){notify(language==='en'?'System references can only be changed by the Platform Owner.':'Οι αναφορές συστήματος μπορούν να αλλάξουν μόνο από τον Platform Owner.','warning');return}try{const saved=isDemo?referenceEditor:await updateExternalReference(tenant.id,referenceEditor);setReferences(rows=>rows.some(row=>row.id===referenceEditor.id)?rows.map(row=>row.id===referenceEditor.id?saved:row):[...rows,saved]);setReferenceEditor(null);notify(t('managementPanel.externalSourceUpdated'),'success')}catch(error){notify(error?.message||t('managementPanel.saveFailed'),'error')}}
 async function deleteReference(item){if(item?.isGlobal&&!isPlatformOwner)return;const ok=await confirm({title:t('managementPanel.deleteExternalSourceTitle'),message:`${t('managementPanel.deleteExternalSourceMessagePrefix')} «${item.authority}» ${t('managementPanel.deleteExternalSourceMessageSuffix')}`,confirmLabel:t('delete'),danger:true});if(!ok)return;try{if(!isDemo)await removeExternalReference(tenant.id,item);setReferences(rows=>rows.filter(row=>row.id!==item.id));notify(t('managementPanel.externalSourceRemoved'),'success')}catch(error){notify(error?.message||t('managementPanel.saveFailed'),'error')}}
 async function refreshReferences(){if(isDemo){notify(t('actionCompleted'),'success');return}try{setManagementLoading(true);setReferences(await loadExternalReferences(tenant.id));notify(t('actionCompleted'),'success')}catch(error){notify(error?.message||t('managementPanel.loadFailed'),'error')}finally{setManagementLoading(false)}}
 return <Page fill title={t('management')} subtitle={t('managementSubtitle')}><div className="management-shell workspace-fill"><div className="tabs canonical-module-tabs management-tabs">{tabs.map(({id,label,icon:Icon})=><button key={id} className={`tab ${tab===id?'active':''}`} onClick={()=>openTab(id)}><Icon size={16}/>{label}</button>)}</div>
 {tab==='overview'&&<ManagementOverview tenant={tenant} isDemo={isDemo} allowed={allowed} onOpen={openTab} t={t}/>} 
 {tab==='organization'&&<OrganizationProfilePanel tenant={tenant} isDemo={isDemo}/>} 
 {tab==='users'&&<section className="management-section"><div className="section-toolbar"><div><h2>{t('organizationUsers')}</h2><p>{tenant?.name} · {t('organizationUsersLifecycle')}</p></div>{allowed(CAPABILITIES.MANAGE_USERS)&&!isDemo&&<Button onClick={()=>setCreateUserOpen(true)}><Plus size={15}/>{t('managementPanel.createUser')}</Button>}</div><div className="table-wrap scroll-table"><table className="data-table sticky-table"><thead><tr><th>{t('users')}</th><th>Username</th><th>{t('roleLabel')}</th><th>{t('status')}</th><th/></tr></thead><tbody>{isDemo?demoUsers.map(user=><tr key={user.id}><td><strong>{user.name}</strong><small>{user.email}</small></td><td>DEMO</td><td>{user.role}</td><td><span className="status-badge active">active</span></td><td/></tr>):orgUsers.map(user=><tr key={user.id}><td><strong>{user.name}</strong><small>{user.email||'—'}</small></td><td>{user.username}</td><td><span className="role-badge">{t(roleNames[user.role]??user.role)}</span></td><td><span className={`status-badge ${user.status==='active'?'active':'temporary'}`}>{user.status}</span></td><td><button className="text-button" onClick={()=>setSelectedUser(user)}>{t('manageUserAction')}</button></td></tr>)}</tbody></table>{!isDemo&&!orgUsersLoading&&orgUsers.length===0&&<div className="inline-empty">{t('noConnectedUsers')}</div>}</div></section>}
 {tab==='announcements'&&<AnnouncementsPanel/>}
 {tab==='roles'&&<section className="management-section"><div className="section-toolbar"><div><h2>{t('rolesPermissions')}</h2><p>{t('roleManagementNote')}</p></div><Button onClick={openNewCustomRole}><Plus size={15}/>{t('createRole')}</Button></div>{managementLoading&&<div className="inline-empty">{t('loading')}</div>}<div className="role-grid">{Object.entries(roleNames).filter(([key])=>key!=='demo').map(([key,labelKey])=><div className="role-card" key={key}><ShieldCheck size={18}/><strong>{t(labelKey)}</strong><span>{t('capabilityBasedAccess')}</span></div>)}{customRoles.map(item=><div className="role-card custom" key={item.id}><ShieldCheck size={18}/><strong>{item.name}</strong><span>{item.capabilities.length} {t('permissions')}</span><div className="record-inline-actions"><button className="edit" title={t('edit')} onClick={()=>openCustomRole(item)}><Pencil size={15}/></button><button className="danger" title={t('delete')} onClick={()=>deleteCustomRole(item)}><Trash2 size={15}/></button></div></div>)}</div></section>}
 {tab==='libraries'&&<LibrariesPanel/>}{tab==='bundles'&&<section className="management-section management-scroll-section"><BundleLibraryPanel/></section>}{tab==='indicators'&&<IndicatorsPanel/>}{tab==='patientDays'&&<BedDaysPanel/>}
 {tab==='references'&&<section className="management-section management-scroll-section"><div className="section-toolbar"><div><h2>{t('externalReferences')}</h2><p>{t('externalReferenceNote')}</p></div><Button variant="secondary" onClick={refreshReferences}>{language==='en'?'Reload':'Επαναφόρτωση'}</Button></div>{managementLoading&&<div className="inline-empty">{t('loading')}</div>}<div className="table-wrap scroll-table"><table className="data-table sticky-table"><thead><tr><th>{t('officialSource')}</th><th>{t('source')}</th><th>{t('managementPanel.scopeLabel')}</th><th>{t('referenceVersion')}</th><th>{t('reviewStatusLabel')}</th><th/></tr></thead><tbody>{references.map(item=><tr key={item.id}><td><strong>{item.label||'—'}</strong>{item.isGlobal&&<small>{isPlatformOwner?'System · Owner':'System · Read only'}</small>}</td><td>{item.authority}</td><td>{language==='el'?item.scope:(item.scopeEn||item.scope)}</td><td>{language==='el'?item.version:(item.versionEn||item.version)}</td><td><span className="status-badge active">{t(item.status)}</span></td><td>{(!item.isGlobal||isPlatformOwner)&&<div className="record-inline-actions"><button title={t('edit')} onClick={()=>setReferenceEditor({...item})}><Pencil size={15}/></button><button className="danger" title={t('delete')} onClick={()=>deleteReference(item)}><X size={15}/></button></div>}</td></tr>)}</tbody></table>{!managementLoading&&!references.length&&<div className="inline-empty">{t('noData')}</div>}</div></section>}
 {roleModal&&<ObserverDialog open title={roleEditingId?(language==='en'?'Edit custom role':'Επεξεργασία προσαρμοσμένου ρόλου'):t('createRole')} onClose={closeRoleEditor}><label className="field"><span>{t('roleName')}</span><input value={roleName} onChange={e=>setRoleName(e.target.value)}/></label><div className="capability-grid">{customRoleCapabilities.map(item=><label key={item.id} className="capability-option"><input type="checkbox" checked={selectedCaps.includes(item.id)} onChange={()=>toggleCap(item.id)}/><span><strong>{capabilityLabel(item.id,language)}</strong><small>{item.group}</small></span></label>)}</div><DialogActions><Button variant="secondary" onClick={closeRoleEditor}>{t('cancel')}</Button><SaveButton onClick={saveCustomRole} disabled={!roleName.trim()||!selectedCaps.length}>{t('save')}</SaveButton></DialogActions></ObserverDialog>}
 {referenceEditor&&<ObserverDialog open title={t('externalReferences')} onClose={()=>setReferenceEditor(null)}><div className="entry-form-grid"><label className="field"><span>{t('officialSource')}</span><input value={referenceEditor.label||''} disabled={referenceEditor.isGlobal&&!isPlatformOwner} onChange={e=>setReferenceEditor(v=>({...v,label:e.target.value}))}/></label><label className="field"><span>{t('source')}</span><input value={referenceEditor.authority||''} disabled={referenceEditor.isGlobal&&!isPlatformOwner} onChange={e=>setReferenceEditor(v=>({...v,authority:e.target.value}))}/></label><label className="field"><span>{t('managementPanel.scopeLabel')}</span><input value={referenceEditor.scope||''} disabled={referenceEditor.isGlobal&&!isPlatformOwner} onChange={e=>setReferenceEditor(v=>({...v,scope:e.target.value}))}/></label><label className="field"><span>{t('referenceVersion')}</span><input value={referenceEditor.version||''} disabled={referenceEditor.isGlobal&&!isPlatformOwner} onChange={e=>setReferenceEditor(v=>({...v,version:e.target.value}))}/></label></div><DialogActions><Button variant="secondary" onClick={()=>setReferenceEditor(null)}>{t('cancel')}</Button>{(!referenceEditor.isGlobal||isPlatformOwner)&&<SaveButton onClick={saveReference}>{t('save')}</SaveButton>}</DialogActions></ObserverDialog>}
 {createUserOpen&&<CreateUserDialog t={t} language={language} onClose={()=>setCreateUserOpen(false)} onCreate={createUser}/>} {createdUser&&<CreatedUserDialog data={createdUser} t={t} language={language} onClose={()=>setCreatedUser(null)}/>} {selectedUser&&<UserDetailDialog user={selectedUser} t={t} onClose={()=>setSelectedUser(null)}/>} </div></Page>
}

function ManagementOverview({tenant,isDemo,allowed,onOpen,t}){const items=[{cap:CAPABILITIES.MANAGE_ORGANIZATION,id:'organization',title:t('organization'),text:t('managementPanel.organizationCard')},{cap:CAPABILITIES.MANAGE_USERS,id:'users',title:t('users'),text:t('managementPanel.usersCard')},{cap:CAPABILITIES.MANAGE_ANNOUNCEMENTS,id:'announcements',title:t('announcements'),text:t('managementPanel.announcementsCard')},{cap:CAPABILITIES.MANAGE_LIBRARIES,id:'libraries',title:t('libraries'),text:t('managementPanel.librariesCard')},{cap:CAPABILITIES.MANAGE_LIBRARIES,id:'bundles',title:t('managementPanel.preventionBundlesLabel'),text:t('managementPanel.preventionBundlesDescription')},{cap:CAPABILITIES.MANAGE_LIBRARIES,id:'indicators',title:'Indicators',text:'Governed indicator definitions and calculation semantics.'},{cap:CAPABILITIES.MANAGE_BED_DAYS,id:'patientDays',title:t('patientDays'),text:t('managementPanel.patientDaysCard')},{cap:CAPABILITIES.MANAGE_EXTERNAL_REFERENCES,id:'references',title:t('externalReferences'),text:t('managementPanel.referencesCard')},{cap:CAPABILITIES.MANAGE_ROLES,id:'roles',title:t('rolesPermissions'),text:t('managementPanel.rolesCard')}].filter(item=>allowed(item.cap));return <section className="management-section"><div className="management-hero"><div><span className="eyebrow">{t('managementPanel.eyebrow')}</span><h2>{tenant?.name}</h2><p>{isDemo?t('managementPanel.demoModeText'):t('managementPanel.productionModeText')}</p></div><ShieldCheck size={34}/></div><div className="management-card-grid">{items.map(item=><button key={item.id} className="management-card" onClick={()=>onOpen(item.id)}><strong>{item.title}</strong><span>{item.text}</span></button>)}</div></section>}

function CreateUserDialog({t,language,onClose,onCreate}){const [form,setForm]=useState({fullName:'',role:'staff_user',email:'',phone:'',jobTitle:'',createEmployee:true,employeeCode:'',departmentId:'',employmentStatus:'active'});const valid=form.fullName.trim()&&form.email.trim()&&form.role;const set=(k,v)=>setForm(x=>({...x,[k]:v}));return <ObserverDialog open title={t('managementPanel.createUser')} onClose={onClose}><div className="entry-form-grid"><label className="field"><span>{t('name')}</span><input value={form.fullName} onChange={e=>set('fullName',e.target.value)}/></label><label className="field"><span>Email</span><input type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></label><label className="field"><span>{t('roleLabel')}</span><select value={form.role} onChange={e=>set('role',e.target.value)}>{creatableRoles.map(role=><option key={role} value={role}>{t(roleNames[role]??role)}</option>)}</select></label><label className="field"><span>{t('phone')}</span><input value={form.phone} onChange={e=>set('phone',e.target.value)}/></label><label className="field"><span>{t('jobTitle')}</span><input value={form.jobTitle} onChange={e=>set('jobTitle',e.target.value)}/></label><label className="field checkbox-field"><input type="checkbox" checked={form.createEmployee} onChange={e=>set('createEmployee',e.target.checked)}/><span>{language==='en'?'Also create employee record':'Δημιουργία και καρτέλας εργαζομένου'}</span></label>{form.createEmployee&&<><label className="field"><span>{language==='en'?'Employee code':'Κωδικός εργαζομένου'}</span><input value={form.employeeCode} onChange={e=>set('employeeCode',e.target.value)}/></label><label className="field"><span>{language==='en'?'Employment status':'Κατάσταση εργασίας'}</span><select value={form.employmentStatus} onChange={e=>set('employmentStatus',e.target.value)}><option value="active">active</option><option value="inactive">inactive</option></select></label></>}</div><DialogActions><Button variant="secondary" onClick={onClose}>{t('cancel')}</Button><SaveButton disabled={!valid} onClick={()=>onCreate({fullName:form.fullName,role:form.role,email:form.email,phone:form.phone,jobTitle:form.jobTitle,employee:{create:form.createEmployee,employeeCode:form.employeeCode,departmentId:form.departmentId||null,employmentStatus:form.employmentStatus}})}>{t('managementPanel.createUser')}</SaveButton></DialogActions></ObserverDialog>}
function CreatedUserDialog({data,t,language,onClose}){return <ObserverDialog open title={t('managementPanel.credentialsTitle')} onClose={onClose}><div className="credential-box"><strong>{data.username}</strong><code>{data.temporaryPassword}</code><p>{language==='en'?'Share the temporary password securely. The user must change it at first sign-in.':'Δώστε τον προσωρινό κωδικό με ασφαλή τρόπο. Ο χρήστης πρέπει να τον αλλάξει στην πρώτη σύνδεση.'}</p>{data.employeeCreated&&<p>{language==='en'?'Employee record created and linked.':'Δημιουργήθηκε και συνδέθηκε καρτέλα εργαζομένου.'}</p>}</div><DialogActions><Button onClick={onClose}>{t('close')}</Button></DialogActions></ObserverDialog>}
function UserDetailDialog({user,t,onClose}){return <ObserverDialog open title={t('manageUserAction')} onClose={onClose}><div className="entry-form-grid"><label className="field"><span>{t('name')}</span><input value={user.name} readOnly/></label><label className="field"><span>Email</span><input value={user.email} readOnly/></label><label className="field"><span>{t('roleLabel')}</span><input value={user.role} readOnly/></label><label className="field"><span>{t('status')}</span><input value={user.status} readOnly/></label></div><DialogActions><Button onClick={onClose}>{t('close')}</Button></DialogActions></ObserverDialog>}
