const SYS=(source,version='current')=>({system:true,locked:true,source,version})
const LOCAL=()=>({system:false,locked:false,source:'Hospital',version:'local'})

export const demoUsers = [
  { id: 'u1', name: 'Demo Administrator', email: 'admin@demo.hospital', role: 'hospital_admin', status: 'active' },
  { id: 'u2', name: 'Ελένη Παπαδοπούλου', email: 'infection@demo.hospital', role: 'infection_control_lead', status: 'active' },
  { id: 'u3', name: 'Νίκος Δημητρίου', email: 'laboratory@demo.hospital', role: 'laboratory', status: 'active' },
]

export const demoOrganizations = [
  { id: 'demo-hospital', name: 'Demo Hospital', code: 'DEMO', type: 'hospital', status: 'active', members: 3 },
]

export const demoLibrarySeed = {
  departments:[
    ['ΜΕΘ','ICU',SYS('Limoxis core hospital structure')],
    ['Χειρουργική','Surgery',SYS('Limoxis core hospital structure')],
    ['Παθολογική','Internal Medicine',SYS('Limoxis core hospital structure')],
    ['ΤΕΠ','Emergency Department',SYS('Limoxis core hospital structure')],
    ['Μαιευτική','Obstetrics',SYS('Limoxis core hospital structure')],
    ['Γυναικολογική','Gynecology',SYS('Limoxis core hospital structure')],
    ['Παιδιατρική','Pediatrics',SYS('Limoxis core hospital structure')],
    ['Νεογνολογική / ΜΕΝΝ','Neonatal / NICU',SYS('Limoxis core hospital structure')],
    ['Αιμοκάθαρση','Hemodialysis',SYS('Limoxis core hospital structure')],
    ['Εργαστήριο','Laboratory',SYS('Limoxis core hospital structure')],
    ['Ακτινοδιαγνωστικό','Radiology',SYS('Limoxis core hospital structure')],
    ['Κεντρική Αποστείρωση','Central Sterile Services',SYS('Limoxis core hospital structure')],
  ],
  microorganisms:[
    ['Acinetobacter baumannii','Acinetobacter baumannii',SYS('WHO BPPL 2024','2024')],
    ['Escherichia coli','Escherichia coli',SYS('WHO BPPL 2024','2024')],
    ['Klebsiella pneumoniae','Klebsiella pneumoniae',SYS('WHO BPPL 2024','2024')],
    ['Enterobacter cloacae complex','Enterobacter cloacae complex',SYS('WHO BPPL 2024','2024')],
    ['Pseudomonas aeruginosa','Pseudomonas aeruginosa',SYS('WHO BPPL 2024','2024')],
    ['Staphylococcus aureus','Staphylococcus aureus',SYS('WHO BPPL 2024','2024')],
    ['Enterococcus faecium','Enterococcus faecium',SYS('WHO BPPL 2024','2024')],
    ['Enterococcus faecalis','Enterococcus faecalis',SYS('Clinical microbiology core')],
    ['Streptococcus pneumoniae','Streptococcus pneumoniae',SYS('WHO BPPL 2024','2024')],
    ['Streptococcus pyogenes','Streptococcus pyogenes',SYS('WHO BPPL 2024','2024')],
    ['Streptococcus agalactiae','Streptococcus agalactiae',SYS('WHO BPPL 2024','2024')],
    ['Haemophilus influenzae','Haemophilus influenzae',SYS('WHO BPPL 2024','2024')],
    ['Neisseria gonorrhoeae','Neisseria gonorrhoeae',SYS('WHO BPPL 2024','2024')],
    ['Salmonella spp.','Salmonella spp.',SYS('WHO BPPL 2024','2024')],
    ['Shigella spp.','Shigella spp.',SYS('WHO BPPL 2024','2024')],
    ['Clostridioides difficile','Clostridioides difficile',SYS('IPC clinical core')],
    ['Mycobacterium tuberculosis','Mycobacterium tuberculosis',SYS('WHO BPPL 2024','2024')],
    ['Candida auris','Candida auris',SYS('IPC emerging pathogen core')],
  ],
  antibiotics:[
    ['Αμοξικιλλίνη','Amoxicillin',SYS('WHO AWaRe','2022')],
    ['Αμοξικιλλίνη/Κλαβουλανικό','Amoxicillin/clavulanic acid',SYS('WHO AWaRe','2022')],
    ['Αμπικιλλίνη','Ampicillin',SYS('WHO AWaRe','2022')],
    ['Κεφαζολίνη','Cefazolin',SYS('WHO AWaRe','2022')],
    ['Κεφουροξίμη','Cefuroxime',SYS('WHO AWaRe','2022')],
    ['Κεφτριαξόνη','Ceftriaxone',SYS('WHO AWaRe','2022')],
    ['Κεφοταξίμη','Cefotaxime',SYS('WHO AWaRe','2022')],
    ['Κεφταζιδίμη','Ceftazidime',SYS('WHO AWaRe','2022')],
    ['Κεφεπίμη','Cefepime',SYS('WHO AWaRe','2022')],
    ['Πιπερακιλλίνη/Ταζομπακτάμη','Piperacillin/Tazobactam',SYS('WHO AWaRe','2022')],
    ['Ερταπενέμη','Ertapenem',SYS('WHO AWaRe','2022')],
    ['Ιμιπενέμη','Imipenem',SYS('WHO AWaRe','2022')],
    ['Μεροπενέμη','Meropenem',SYS('WHO AWaRe','2022')],
    ['Αζτρεονάμη','Aztreonam',SYS('Clinical antimicrobial core')],
    ['Γενταμικίνη','Gentamicin',SYS('WHO AWaRe','2022')],
    ['Αμικασίνη','Amikacin',SYS('WHO AWaRe','2022')],
    ['Σιπροφλοξασίνη','Ciprofloxacin',SYS('WHO AWaRe','2022')],
    ['Λεβοφλοξασίνη','Levofloxacin',SYS('WHO AWaRe','2022')],
    ['Βανκομυκίνη','Vancomycin',SYS('WHO AWaRe','2022')],
    ['Τεϊκοπλανίνη','Teicoplanin',SYS('Clinical antimicrobial core')],
    ['Λινεζολίδη','Linezolid',SYS('WHO AWaRe','2022')],
    ['Δαπτομυκίνη','Daptomycin',SYS('Clinical antimicrobial core')],
    ['Κολιστίνη','Colistin',SYS('WHO AWaRe','2022')],
    ['Τιγεκυκλίνη','Tigecycline',SYS('WHO AWaRe','2022')],
    ['Κεφταζιδίμη/Αβιμπακτάμη','Ceftazidime/avibactam',SYS('WHO AWaRe / Reserve','2022')],
    ['Κεφτολοζάνη/Ταζομπακτάμη','Ceftolozane/tazobactam',SYS('WHO AWaRe / Reserve','2022')],
  ],
  advancedAntibiotics:[
    ['Μεροπενέμη','Meropenem',SYS('Hospital stewardship core')],
    ['Ιμιπενέμη','Imipenem',SYS('Hospital stewardship core')],
    ['Κολιστίνη','Colistin',SYS('WHO AWaRe / Reserve','2022')],
    ['Λινεζολίδη','Linezolid',SYS('WHO AWaRe','2022')],
    ['Δαπτομυκίνη','Daptomycin',SYS('Hospital stewardship core')],
    ['Τιγεκυκλίνη','Tigecycline',SYS('Hospital stewardship core')],
    ['Κεφταζιδίμη/Αβιμπακτάμη','Ceftazidime/avibactam',SYS('WHO AWaRe / Reserve','2022')],
    ['Κεφτολοζάνη/Ταζομπακτάμη','Ceftolozane/tazobactam',SYS('WHO AWaRe / Reserve','2022')],
  ],
  notifiableDiseases:[
    ['Ιλαρά','Measles',SYS('ΕΟΔΥ · υποχρεωτική δήλωση')],
    ['Ερυθρά','Rubella',SYS('ΕΟΔΥ · υποχρεωτική δήλωση')],
    ['Παρωτίτιδα','Mumps',SYS('ΕΟΔΥ · υποχρεωτική δήλωση')],
    ['Μηνιγγιτιδοκοκκική νόσος','Meningococcal disease',SYS('ΕΟΔΥ · υποχρεωτική δήλωση')],
    ['Διφθερίτιδα','Diphtheria',SYS('ΕΟΔΥ · υποχρεωτική δήλωση')],
    ['Κοκκύτης','Pertussis',SYS('ΕΟΔΥ · υποχρεωτική δήλωση')],
    ['Φυματίωση','Tuberculosis',SYS('ΕΟΔΥ · υποχρεωτική δήλωση')],
    ['Λεγιονέλλωση','Legionellosis',SYS('ΕΟΔΥ · υποχρεωτική δήλωση')],
    ['Ιογενής ηπατίτιδα Α','Viral hepatitis A',SYS('ΕΟΔΥ · υποχρεωτική δήλωση')],
    ['Ιογενής ηπατίτιδα Β','Viral hepatitis B',SYS('ΕΟΔΥ · επιτήρηση')],
    ['Ιογενής ηπατίτιδα C','Viral hepatitis C',SYS('ΕΟΔΥ · επιτήρηση')],
    ['Σαλμονέλλωση','Salmonellosis',SYS('ΕΟΔΥ · επιτήρηση')],
    ['Σιγκέλλωση','Shigellosis',SYS('ΕΟΔΥ · επιτήρηση')],
    ['Λοίμωξη από ιό Δυτικού Νείλου','West Nile virus infection',SYS('ΕΟΔΥ · υποχρεωτική δήλωση')],
  ],
  sampleTypes:[
    ['Αίμα','Blood',SYS('Clinical microbiology core')],
    ['Ούρα','Urine',SYS('Clinical microbiology core')],
    ['ΕΝΥ','CSF',SYS('Clinical microbiology core')],
    ['Πτύελα','Sputum',SYS('Clinical microbiology core')],
    ['Τραχειακό αναρρόφημα','Tracheal aspirate',SYS('Clinical microbiology core')],
    ['BAL','BAL',SYS('Clinical microbiology core')],
    ['Τραύμα / επίχρισμα','Wound / swab',SYS('Clinical microbiology core')],
    ['Βαθύς ιστός','Deep tissue',SYS('Clinical microbiology core')],
    ['Κόπρανα','Stool',SYS('Clinical microbiology core')],
    ['Επιφάνεια','Surface',SYS('Environmental surveillance core')],
    ['Αέρας','Air',SYS('Environmental surveillance core')],
    ['Νερό','Water',SYS('Environmental surveillance core')],
    ['Περιβάλλον χώρου','Room environment',SYS('Environmental surveillance core')],
  ],
  environmentalLocations:[
    ['Θάλαμος','Patient room',SYS('Environmental surveillance core')],
    ['Σταθμός νοσηλευτών','Nurses station',SYS('Environmental surveillance core')],
    ['Χειρουργική αίθουσα','Operating room',SYS('Environmental surveillance core')],
    ['ΜΕΘ','ICU',SYS('Environmental surveillance core')],
    ['Αποδυτήρια','Changing room',SYS('Environmental surveillance core')],
  ],
  surfacePoints:[
    ['Κομοδίνο','Bedside table',SYS('Environmental surveillance core')],
    ['Πόμολο πόρτας','Door handle',SYS('Environmental surveillance core')],
    ['Κλίνη','Bed rail',SYS('Environmental surveillance core')],
    ['Πληκτρολόγιο','Keyboard',SYS('Environmental surveillance core')],
    ['Ιατροτεχνολογικός εξοπλισμός','Medical equipment',SYS('Environmental surveillance core')],
  ],
  environmentalStandards:[
    {id:'ENV-SURF-SWAB',subjectType:'surface',sourceCode:'surfaceSwab',protocolCode:'ENV-SURF-SWAB',unit:'CFU',limitCfu:null,active:true},
    {id:'ENV-SURF-PLATE',subjectType:'surface',sourceCode:'contactPlate',protocolCode:'ENV-SURF-PLATE',unit:'CFU',limitCfu:null,active:true},
    {id:'ENV-ROOM',subjectType:'room',sourceCode:'roomSampling',protocolCode:'ENV-ROOM',unit:'CFU/m³',limitCfu:null,active:true},
    {id:'ENV-WATER',subjectType:'water',sourceCode:'waterSampling',protocolCode:'ENV-WATER',unit:'CFU/100mL',limitCfu:null,active:true},
  ],
  documentTypes:[
    ['Πολιτική','Policy',SYS('QMS documented information core')],
    ['Διαδικασία','Procedure',SYS('QMS documented information core')],
    ['Οδηγία εργασίας','Work instruction',SYS('QMS documented information core')],
    ['Έντυπο','Form',SYS('QMS documented information core')],
    ['Check-list','Checklist',SYS('QMS documented information core')],
    ['Εκπαιδευτικό υλικό','Training material',SYS('QMS documented information core')],
    ['Εξωτερικό έγγραφο','External document',SYS('QMS documented information core')],
  ],
}

export function newLocalLibraryItem(el,en=el){return [el,en,LOCAL()]}

export const demoPatientDayPeriods = [
 {id:'pd1',from:'2026-08-01',to:'2026-08-31',scope:'department',departmentEl:'ΜΕΘ',departmentEn:'ICU',value:372,source:'manual'},
 {id:'pd2',from:'2026-08-01',to:'2026-08-31',scope:'department',departmentEl:'Χειρουργική',departmentEn:'Surgery',value:318,source:'manual'},
 {id:'pd3',from:'2026-08-01',to:'2026-08-31',scope:'department',departmentEl:'Παθολογική',departmentEn:'Internal Medicine',value:441,source:'manual'},
 {id:'pd4',from:'2026-07-01',to:'2026-07-31',scope:'hospital',departmentEl:'',departmentEn:'',value:5214,source:'manual'},
]
export const externalSources=[
  {id:'eody',label:'ΕΟΔΥ — Επιτήρηση λοιμωδών νοσημάτων',authority:'ΕΟΔΥ',version:'Εθνική επιτήρηση και υποχρεωτική δήλωση',versionEn:'National surveillance and mandatory notification',status:'approved',scope:'Δηλούμενα νοσήματα, επιδημιολογική επιτήρηση και εθνικές οδηγίες',scopeEn:'Notifiable diseases, epidemiological surveillance and national guidance'},
  {id:'eucast',label:'EUCAST — Αντιμικροβιακή ευαισθησία',authority:'EUCAST',version:'Clinical breakpoints / τρέχουσα έκδοση',versionEn:'Clinical breakpoints / current version',status:'approved',scope:'Breakpoints, MIC και ερμηνεία αντιμικροβιακής ευαισθησίας',scopeEn:'Breakpoints, MIC and antimicrobial susceptibility interpretation'},
  {id:'who',label:'WHO — Infection Prevention & Control',authority:'WHO',version:'IPC Core Components / BPPL / AWaRe',versionEn:'IPC Core Components / BPPL / AWaRe',status:'approved',scope:'IPC, AMR, υγιεινή χεριών και antimicrobial stewardship',scopeEn:'IPC, AMR, hand hygiene and antimicrobial stewardship'},
  {id:'cdc',label:'CDC — Infection Control',authority:'CDC',version:'Infection Control / Isolation Precautions',versionEn:'Infection Control / Isolation Precautions',status:'approved',scope:'Προφυλάξεις μετάδοσης, απομόνωση, HAI και πρακτικές πρόληψης',scopeEn:'Transmission precautions, isolation, HAI and prevention practices'},
  {id:'ecdc',label:'ECDC — Healthcare-associated infections & AMR',authority:'ECDC',version:'HAI-Net / EARS-Net / surveillance guidance',versionEn:'HAI-Net / EARS-Net / surveillance guidance',status:'approved',scope:'Ευρωπαϊκή επιτήρηση HAI, AMR, PPS και επιδημιολογικοί ορισμοί',scopeEn:'European HAI and AMR surveillance, PPS and epidemiological definitions'},
  {id:'shea',label:'SHEA — Healthcare Epidemiology',authority:'SHEA',version:'Compendium / practice recommendations',versionEn:'Compendium / practice recommendations',status:'approved',scope:'Πρόληψη HAI, bundles και στρατηγικές εφαρμογής',scopeEn:'HAI prevention, bundles and implementation strategies'},
  {id:'idsa',label:'IDSA — Infectious Diseases',authority:'IDSA',version:'Clinical practice guidelines',versionEn:'Clinical practice guidelines',status:'approved',scope:'Λοιμώξεις, αντιμικροβιακή θεραπεία και antimicrobial stewardship',scopeEn:'Infectious diseases, antimicrobial treatment and antimicrobial stewardship'},
  {id:'apic',label:'APIC — Infection Prevention',authority:'APIC',version:'Practice resources / implementation guidance',versionEn:'Practice resources / implementation guidance',status:'approved',scope:'Πρακτικές infection prevention, εκπαίδευση και εφαρμογή προγραμμάτων IPC',scopeEn:'Infection prevention practice, education and IPC program implementation'},
  {id:'nice',label:'NICE — Infection prevention & antimicrobial guidance',authority:'NICE',version:'Clinical guidance / quality standards',versionEn:'Clinical guidance / quality standards',status:'approved',scope:'Πρόληψη λοιμώξεων, antimicrobial prescribing και quality standards',scopeEn:'Infection prevention, antimicrobial prescribing and quality standards'},
  {id:'jci',label:'JCI — Accreditation standards',authority:'JCI',version:'Hospital accreditation standards',versionEn:'Hospital accreditation standards',status:'approved',scope:'PCI, ποιότητα, ασφάλεια ασθενών και οργανωτική διακυβέρνηση',scopeEn:'PCI, quality, patient safety and organizational governance'},
  {id:'iso',label:'ISO — Healthcare quality & safety standards',authority:'ISO',version:'ISO 9001 / EN 15224 και συναφή πρότυπα',versionEn:'ISO 9001 / EN 15224 and related standards',status:'approved',scope:'Συστήματα ποιότητας, κλινικές διεργασίες, τεκμηρίωση και διακυβέρνηση',scopeEn:'Quality systems, clinical processes, documentation and governance'},
  {id:'european-commission',label:'Ευρωπαϊκή Επιτροπή — Δημόσια υγεία',authority:'European Commission',version:'EU public-health framework',versionEn:'EU public-health framework',status:'approved',scope:'Ευρωπαϊκή πολιτική δημόσιας υγείας, AMR και κανονιστικό πλαίσιο',scopeEn:'EU public-health policy, AMR and regulatory framework'},
]
