import { useEffect,useMemo,useState } from 'react'
import { LockKeyhole,Pencil,Plus,Search,ShieldCheck,Trash2 } from 'lucide-react'
import { Button } from '../../design-system/Button'
import { EntityRecordShell } from '../../design-system/EntityRecordShell'
import { SaveButton } from '../../design-system/SaveButton'
import { IconButton } from '../../design-system/IconButton'
import { RegistryTable } from '../../design-system/RegistryTable'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useTenant } from '../../core/tenant/TenantContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { capabilityLabel } from '../../core/permissions/capabilityLabels'
import { capabilityCatalogue,isCustomRoleEligible } from '../../core/permissions/capabilityCatalogue'
import { roleCapabilities,roleCapabilityRule } from '../../core/permissions/systemRoleMatrix'
import { managementRoleNames } from './managementRoles'
import { createCustomRole,deactivateCustomRole,loadCustomRoles,updateCustomRole } from './managementCloudService'
const domainLabels={
 administration:['Διαχείριση','Administration'],platform:['Πλατφόρμα','Platform'],clinical:['Κλινική φροντίδα','Clinical'],laboratory:['Εργαστήριο','Laboratory'],quality:['Ποιότητα','Quality'],committees:['Επιτροπές','Committees'],documents:['Έγγραφα','Documents'],controls:['Έλεγχοι','Controls'],training:['Εκπαίδευση','Training'],workforce:['Προσωπικό','Workforce'],occupational_health:['Ιατρός Εργασίας','Occupational health'],general:['Γενικά','General'],
}
const scopeLabels={self:['Μόνο ο ίδιος','Self'],department:['Τμήμα','Department'],organization:['Οργανισμός','Organization'],platform:['Πλατφόρμα','Platform']}
const sensitivityLabels={standard:['Κανονικό','Standard'],sensitive:['Ευαίσθητο','Sensitive'],security:['Ασφάλεια','Security']}
const actionLabels={view:['Προβολή','View'],create:['Δημιουργία','Create'],edit:['Επεξεργασία','Edit'],delete:['Διαγραφή','Delete'],manage:['Διαχείριση','Manage'],record:['Καταχώριση','Record'],execute:['Εκτέλεση','Execute'],approve:['Έγκριση','Approve'],publish:['Δημοσίευση','Publish'],archive:['Αρχειοθέτηση','Archive'],close:['Κλείσιμο','Close'],reopen:['Επαναφορά','Reopen'],validate:['Επικύρωση','Validate'],communicate:['Επικοινωνία','Communicate'],classify:['Ταξινόμηση','Classify'],submit:['Υποβολή','Submit'],supersede:['Αντικατάσταση','Supersede'],attach:['Επισύναψη','Attach'],print:['Εκτύπωση','Print'],export:['Εξαγωγή','Export'],assign:['Ανάθεση','Assign'],complete:['Ολοκλήρωση','Complete'],report:['Αναφορά','Report'],void:['Ακύρωση','Void']}
const groupLabel=(value,en)=>domainLabels[value]?.[en?1:0]||value
const scopeLabel=(value,en)=>scopeLabels[value]?.[en?1:0]||value||'—'
const sensitivityLabel=(value,en)=>sensitivityLabels[value]?.[en?1:0]||value||'—'
const actionLabel=(item,en)=>actionLabels[item?.actionType]?.[en?1:0]||(en?'Other':'Άλλο')

export function ManagementRolesPanel(){
 const {language,t}=useLanguage();const en=language==='en';const {tenant,isDemo}=useTenant();const {notify,confirm}=useFeedback()
 const [customRoles,setCustomRoles]=useState([]);const [loading,setLoading]=useState(false);const [selected,setSelected]=useState(null);const [editor,setEditor]=useState(null)
 const customPermissions=useMemo(()=>Object.values(capabilityCatalogue).filter(item=>item.customRoleClass!=='system_only'),[])
 const systemRoles=useMemo(()=>Object.entries(managementRoleNames).filter(([key])=>key!=='demo').map(([key,labelKey])=>({id:key,name:t(labelKey),system:true,capabilities:roleCapabilities[key]||[]})),[t])
 useEffect(()=>{if(isDemo){setCustomRoles([]);return}if(!tenant?.id)return;let active=true;setLoading(true);loadCustomRoles(tenant.id).then(rows=>active&&setCustomRoles(rows)).catch(error=>active&&notify(error?.message||(en?'Failed to load roles.':'Αποτυχία φόρτωσης ρόλων.'),'error')).finally(()=>active&&setLoading(false));return()=>{active=false}},[isDemo,tenant?.id,notify,en])
 const selectedRole=useMemo(()=>selected?.system?systemRoles.find(x=>x.id===selected.id)||null:customRoles.find(x=>x.id===selected?.id)||null,[selected,systemRoles,customRoles])
 function openNew(){setSelected(null);setEditor({mode:'new',id:null,name:'',capabilities:[]})}
 function openEdit(role){if(role?.system)return;setEditor({mode:'edit',id:role.id,name:role.name||'',capabilities:[...(role.capabilities||[])]})}
 function closeEditor(){setEditor(null)}
 async function save(){if(!editor?.name.trim()||!editor.capabilities.length)return;try{const payload={name:editor.name.trim(),capabilities:editor.capabilities.filter(isCustomRoleEligible)};const saved=isDemo?{id:editor.id||`custom-${Date.now()}`,...payload}:editor.mode==='edit'?await updateCustomRole(tenant.id,editor.id,payload):await createCustomRole(tenant.id,payload);setCustomRoles(rows=>editor.mode==='edit'?rows.map(r=>r.id===saved.id?saved:r):[...rows,saved]);setSelected({id:saved.id,system:false});setEditor(null);notify(en?'Role saved.':'Ο ρόλος αποθηκεύτηκε.','success')}catch(error){notify(error?.message||(en?'Save failed.':'Αποτυχία αποθήκευσης.'),'error')}}
 async function remove(role){if(!role||role.system)return;const ok=await confirm({title:en?'Delete role':'Διαγραφή ρόλου',message:en?`Delete “${role.name}”?`:`Να διαγραφεί ο ρόλος «${role.name}»;`,confirmLabel:en?'Delete':'Διαγραφή',danger:true});if(!ok)return;try{if(!isDemo)await deactivateCustomRole(tenant.id,role.id);setCustomRoles(rows=>rows.filter(r=>r.id!==role.id));setSelected(null);notify(en?'Role deleted.':'Ο ρόλος διαγράφηκε.','success')}catch(error){notify(error?.message||(en?'Delete failed.':'Αποτυχία διαγραφής.'),'error')}}

 if(editor)return <RoleEditor en={en} value={editor} permissions={customPermissions} onChange={setEditor} onClose={closeEditor} onSave={save}/>

 if(selectedRole)return <section className="management-section management-scroll-section"><EntityRecordShell className="management-role-record workspace-fill" avatar={<ShieldCheck size={19}/>} eyebrow={selectedRole.system?(en?'SYSTEM ROLE':'ΡΟΛΟΣ ΣΥΣΤΗΜΑΤΟΣ'):(en?'CUSTOM ROLE':'ΠΡΟΣΑΡΜΟΣΜΕΝΟΣ ΡΟΛΟΣ')} title={selectedRole.name} subtitle={`${selectedRole.capabilities.length} ${en?'permissions':'δικαιώματα'}`} status={<span className="status-badge active">{selectedRole.system?'System':'Custom'}</span>} onBack={()=>setSelected(null)} backLabel={en?'Back to roles':'Επιστροφή στους ρόλους'}>
   <section className="record-section management-role-detail"><div className="record-section-header"><div><span className="eyebrow">{en?'ACCESS':'ΠΡΟΣΒΑΣΗ'}</span><h3>{en?'Permissions and scope':'Δικαιώματα και εύρος πρόσβασης'}</h3><p>{selectedRole.system?(en?'System roles are defined centrally and cannot be modified here.':'Οι ρόλοι συστήματος ορίζονται κεντρικά και δεν τροποποιούνται από εδώ.'):(en?'These permissions are saved on the custom role and applied by the authorization layer.':'Τα δικαιώματα αποθηκεύονται στον προσαρμοσμένο ρόλο και εφαρμόζονται από το σύστημα εξουσιοδότησης.')}</p></div><div className="management-role-record-actions">{selectedRole.system?<span className="management-role-lock"><LockKeyhole size={15}/>{en?'Read only':'Μόνο προβολή'}</span>:<><IconButton tone="edit" label={t('edit')} onClick={()=>openEdit(selectedRole)}><Pencil size={16}/></IconButton><IconButton tone="danger" label={t('delete')} onClick={()=>remove(selectedRole)}><Trash2 size={16}/></IconButton></>}</div></div>
    <RolePermissionTable role={selectedRole} en={en}/>
   </section>
  </EntityRecordShell></section>

 return <section className="management-section management-scroll-section"><div className="management-roles-panel workspace-fill"><div className="section-toolbar"><div><h2>{t('rolesPermissions')}</h2><p>{en?'Select a role to inspect its exact permissions and access scope. Custom roles can be edited.':'Επιλέξτε έναν ρόλο για να δείτε αναλυτικά τα δικαιώματα και το εύρος πρόσβασής του. Οι προσαρμοσμένοι ρόλοι μπορούν να τροποποιηθούν.'}</p></div><Button onClick={openNew}><Plus size={15}/>{en?'New role':'Νέος ρόλος'}</Button></div>{loading&&<div className="inline-empty">{t('loading')}</div>}<div className="management-role-grid">{systemRoles.map(role=><button key={role.id} className="management-role-card" onClick={()=>setSelected({id:role.id,system:true})}><span className="management-role-card-icon"><ShieldCheck size={18}/></span><span className="management-role-card-copy"><strong>{role.name}</strong><small>{role.capabilities.length} {en?'permissions':'δικαιώματα'}</small></span><span className="management-role-card-kind">System</span></button>)}{customRoles.map(role=><button key={role.id} className="management-role-card custom" onClick={()=>setSelected({id:role.id,system:false})}><span className="management-role-card-icon"><ShieldCheck size={18}/></span><span className="management-role-card-copy"><strong>{role.name}</strong><small>{(role.capabilities||[]).length} {en?'permissions':'δικαιώματα'}</small></span><span className="management-role-card-kind">Custom</span></button>)}</div></div></section>
}

function RolePermissionTable({role,en}){const rows=(role.capabilities||[]).map(id=>{const def=capabilityCatalogue[id];const rule=role.system?roleCapabilityRule(role.id,id):null;return {id,label:capabilityLabel(id,en?'en':'el'),domain:def?.domain||'general',action:def?.actionType||'',scope:rule?.defaultScope||def?.defaultScope||'organization',sensitivity:def?.sensitivity||'standard'}});return <RegistryTable
  wrapperClassName="management-role-table-wrap"
  columns={[{key:'permission',label:en?'Permission':'Δικαίωμα'},{key:'action',label:en?'Action':'Ενέργεια'},{key:'area',label:en?'Area':'Ενότητα'},{key:'scope',label:en?'Scope':'Εύρος'},{key:'level',label:en?'Level':'Επίπεδο'}]}
  rows={rows}
  rowKey={row=>row.id}
  renderRow={row=><><td><strong>{row.label}</strong><small>{row.id}</small></td><td><span className={`role-action-badge action-${row.action}`}>{actionLabels[row.action]?.[en?1:0]||row.action}</span></td><td>{groupLabel(row.domain,en)}</td><td><span className="role-scope-badge">{scopeLabel(row.scope,en)}</span></td><td>{sensitivityLabel(row.sensitivity,en)}</td></>}
  empty={!rows.length}
  emptyTitle={en?'No permissions.':'Δεν υπάρχουν δικαιώματα.'}
/>}

function RoleEditor({en,value,permissions,onChange,onClose,onSave}){
 const [query,setQuery]=useState('');const [mode,setMode]=useState('all');
 const selected=new Set(value.capabilities||[])
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return permissions.filter(item=>{if(mode==='selected'&&!selected.has(item.id))return false;const text=`${capabilityLabel(item.id,en?'en':'el')} ${item.id} ${groupLabel(item.domain,en)} ${actionLabel(item,en)}`.toLowerCase();return !q||text.includes(q)})},[permissions,query,mode,en,value.capabilities])
 const grouped=useMemo(()=>filtered.reduce((acc,item)=>{(acc[item.domain]??=[]).push(item);return acc},{}),[filtered])
 const toggle=id=>{if(!isCustomRoleEligible(id))return;onChange(v=>({...v,capabilities:selected.has(id)?v.capabilities.filter(x=>x!==id):[...v.capabilities,id]}))}
 const title=value.mode==='edit'?(en?'Edit role':'Επεξεργασία ρόλου'):(en?'New role':'Νέος ρόλος')
 return <section className="management-section management-scroll-section management-role-editor-screen"><EntityRecordShell className="management-role-editor-record workspace-fill" avatar={<ShieldCheck size={19}/>} eyebrow={en?'ROLE SETTINGS':'ΡΥΘΜΙΣΕΙΣ ΡΟΛΟΥ'} title={title} subtitle={en?'Define exactly what this role can do.':'Ορίστε ακριβώς τι μπορεί να κάνει ο ρόλος.'} onBack={onClose} backLabel={en?'Back to roles':'Επιστροφή στους ρόλους'}>
   <section className="record-section management-role-editor-basics"><div className="record-section-header"><div><span className="eyebrow">{en?'IDENTITY':'ΣΤΟΙΧΕΙΑ'}</span><h3>{en?'Role details':'Στοιχεία ρόλου'}</h3><p>{en?'Give the role a clear name and then choose its permissions.':'Δώστε σαφές όνομα στον ρόλο και στη συνέχεια επιλέξτε τα δικαιώματά του.'}</p></div><div className="management-role-editor-count"><strong>{value.capabilities.length}</strong><span>{en?'selected permissions':'επιλεγμένα δικαιώματα'}</span></div></div><label className="field management-role-name-field"><span>{en?'Role name':'Όνομα ρόλου'}</span><input autoFocus value={value.name} onChange={e=>onChange(v=>({...v,name:e.target.value}))} placeholder={en?'e.g. Ward Infection Link':'π.χ. Σύνδεσμος Λοιμώξεων Κλινικής'}/></label></section>
   <section className="record-section management-role-editor-permissions"><div className="record-section-header"><div><span className="eyebrow">{en?'PERMISSIONS':'ΔΙΚΑΙΩΜΑΤΑ'}</span><h3>{en?'Permissions':'Δικαιώματα πρόσβασης'}</h3><p>{en?'Search and select the exact view, create, edit, delete and management actions this role needs.':'Αναζητήστε και επιλέξτε ακριβώς τις ενέργειες προβολής, δημιουργίας, επεξεργασίας, διαγραφής και διαχείρισης που χρειάζεται ο ρόλος.'}</p></div></div>
    <div className="management-role-permission-toolbar"><label className="management-role-permission-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={en?'Search by permission, area or action…':'Αναζήτηση με δικαίωμα, ενότητα ή ενέργεια…'}/></label><div className="management-role-view-toggle"><button type="button" className={mode==='all'?'active':''} onClick={()=>setMode('all')}>{en?'All':'Όλα'}</button><button type="button" className={mode==='selected'?'active':''} onClick={()=>setMode('selected')}>{en?'Selected':'Επιλεγμένα'} <span>{value.capabilities.length}</span></button></div></div>
    <div className="management-role-capability-groups">{Object.entries(grouped).map(([domain,items])=><section key={domain} className="management-role-capability-group"><header><strong>{groupLabel(domain,en)}</strong><span>{items.filter(item=>selected.has(item.id)).length}/{items.length}</span></header><div className="management-role-capability-list">{items.map(item=>{const selectable=isCustomRoleEligible(item.id);return <label key={item.id} className={`management-role-capability ${selected.has(item.id)?'selected':''} ${!selectable?'restricted':''}`} title={!selectable?(en?'Reserved for governed system roles':'Διατίθεται μόνο μέσω ελεγχόμενων ρόλων συστήματος'):''}><input type="checkbox" checked={selected.has(item.id)} disabled={!selectable} onChange={()=>toggle(item.id)}/><span className="management-role-capability-copy"><strong>{capabilityLabel(item.id,en?'en':'el')}</strong><small>{scopeLabel(item.defaultScope,en)}</small></span><span className={`role-action-badge action-${item.actionType}`}>{actionLabel(item,en)}</span>{!selectable&&<span className="management-role-restricted"><LockKeyhole size={12}/>System</span>}</label>})}</div></section>)}{!Object.keys(grouped).length&&<div className="inline-empty management-role-no-results">{en?'No permissions match this search.':'Δεν βρέθηκαν δικαιώματα με αυτά τα κριτήρια.'}</div>}</div>
   </section>
   <div className="management-role-editor-footer"><Button variant="secondary" onClick={onClose}>{en?'Cancel':'Ακύρωση'}</Button><SaveButton onClick={onSave} disabled={!value.name.trim()||!value.capabilities.length}>{en?'Save role':'Αποθήκευση ρόλου'}</SaveButton></div>
  </EntityRecordShell></section>
}
