import { useEffect,useState } from 'react'
import { Building2,Save } from 'lucide-react'
import { Button } from '../../design-system/Button'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { supabase } from '../../core/supabase/client'

const empty={name:'',code:'',type:'',region:'',healthRegion:'',city:'',country:'GR',contactEmail:'',contactPhone:'',bedCapacity:''}

export function OrganizationProfilePanel({tenant,isDemo=false}){
 const {language}=useLanguage();const {notify}=useFeedback();const [form,setForm]=useState(empty);const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false)
 const el=language==='el'
 useEffect(()=>{let active=true;if(!tenant?.id)return;setForm(v=>({...v,name:tenant.name||'',code:tenant.code||'',type:tenant.type||''}));if(isDemo||!supabase)return;setLoading(true);supabase.from('organizations').select('name,code,type,region,health_region,city,country,contact_email,contact_phone,bed_capacity').eq('id',tenant.id).single().then(({data,error})=>{if(!active)return;if(error){notify(error.message,'error');return}setForm({name:data.name||'',code:data.code||'',type:data.type||'',region:data.region||'',healthRegion:data.health_region||'',city:data.city||'',country:data.country||'GR',contactEmail:data.contact_email||'',contactPhone:data.contact_phone||'',bedCapacity:data.bed_capacity??''})}).finally(()=>active&&setLoading(false));return()=>{active=false}},[tenant?.id,tenant?.name,tenant?.code,tenant?.type,isDemo,notify])
 function field(key,value){setForm(v=>({...v,[key]:value}))}
 async function save(){if(isDemo){notify(el?'Η λειτουργία είναι μόνο για πραγματικό οργανισμό.':'This action is available for live organizations only.','info');return}if(!form.name.trim())return;setSaving(true);try{const {error}=await supabase.rpc('update_organization_profile',{p_organization_id:tenant.id,p_name:form.name,p_region:form.region||null,p_health_region:form.healthRegion||null,p_city:form.city||null,p_country:form.country||'GR',p_contact_email:form.contactEmail||null,p_contact_phone:form.contactPhone||null,p_bed_capacity:form.bedCapacity===''?null:Number(form.bedCapacity)});if(error)throw error;notify(el?'Τα στοιχεία του οργανισμού αποθηκεύτηκαν.':'Organization profile saved.','success')}catch(error){notify(error?.message||(el?'Αποτυχία αποθήκευσης.':'Save failed.'),'error')}finally{setSaving(false)}}
 return <section className="management-section"><div className="section-toolbar"><div><h2><Building2 size={18}/> {el?'Στοιχεία οργανισμού':'Organization profile'}</h2><p>{el?'Κεντρικά στοιχεία του νοσοκομείου. Οι αλλαγές καταγράφονται στο audit trail.':'Core hospital details. Changes are recorded in the audit trail.'}</p></div><Button disabled={loading||saving||isDemo||!form.name.trim()} onClick={save}><Save size={15}/>{saving?(el?'Αποθήκευση…':'Saving…'):(el?'Αποθήκευση':'Save')}</Button></div><div className="entry-form-grid"><label className="field"><span>{el?'Επωνυμία':'Name'}</span><input value={form.name} onChange={e=>field('name',e.target.value)}/></label><label className="field"><span>{el?'Κωδικός':'Code'}</span><input value={form.code} disabled/></label><label className="field"><span>{el?'Τύπος':'Type'}</span><input value={form.type} disabled/></label><label className="field"><span>{el?'Περιφέρεια':'Region'}</span><input value={form.region} onChange={e=>field('region',e.target.value)}/></label><label className="field"><span>{el?'Υγειονομική Περιφέρεια':'Health region'}</span><input value={form.healthRegion} onChange={e=>field('healthRegion',e.target.value)}/></label><label className="field"><span>{el?'Πόλη':'City'}</span><input value={form.city} onChange={e=>field('city',e.target.value)}/></label><label className="field"><span>{el?'Χώρα':'Country'}</span><input value={form.country} onChange={e=>field('country',e.target.value.toUpperCase())}/></label><label className="field"><span>Email</span><input type="email" value={form.contactEmail} onChange={e=>field('contactEmail',e.target.value)}/></label><label className="field"><span>{el?'Τηλέφωνο':'Phone'}</span><input value={form.contactPhone} onChange={e=>field('contactPhone',e.target.value)}/></label><label className="field"><span>{el?'Δυναμικότητα κλινών':'Bed capacity'}</span><input type="number" min="0" value={form.bedCapacity} onChange={e=>field('bedCapacity',e.target.value)}/></label></div>{loading&&<div className="inline-empty">{el?'Φόρτωση…':'Loading…'}</div>}</section>
}
