import { useMemo,useState } from 'react'
import { ArrowDown,ArrowUp,ClipboardList,Pencil,Plus,Trash2 } from 'lucide-react'
import { Button } from '../../design-system/Button'
import { EntityRecordShell } from '../../design-system/EntityRecordShell'
import { ObserverDialog,DialogActions } from '../../design-system/ObserverDialog'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { loadSnapshot,saveSnapshot } from '../../core/data/repository'
import { DEFAULT_TRAINER_FEEDBACK_TEMPLATE } from '../training/trainingFeedbackTemplate'
import '../../styles/questionnaires.css'

const STORE='management_questionnaires_v1'
const types={rating:{el:'Κλίμακα 1–5',en:'Rating 1–5'},yesno:{el:'Ναι / Όχι',en:'Yes / No'},single:{el:'Μία επιλογή',en:'Single choice'},multiple:{el:'Πολλαπλή επιλογή',en:'Multiple choice'},text:{el:'Ελεύθερο κείμενο',en:'Free text'}}
const id=prefix=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`
const seed=()=>[{id:'trainer-evaluation',title:'Αξιολόγηση εκπαιδευτή',category:'training',status:'active',questions:(DEFAULT_TRAINER_FEEDBACK_TEMPLATE.questions||[]).map(q=>({id:q.id,label:q.labelEl,type:'rating',required:true,options:[]}))}]
function normalizeRow(row){return {...row,title:row.title||row.titleEl||row.titleEn||'',questions:(row.questions||[]).map(q=>({...q,label:q.label||q.labelEl||q.labelEn||'',options:Array.isArray(q.options)?q.options:[]}))}}
function load(){const rows=loadSnapshot(STORE,null);return Array.isArray(rows)&&rows.length?rows.map(normalizeRow):seed()}
function categoryLabel(value,en){if(value==='training')return en?'Training':'Εκπαίδευση';if(value==='audit')return 'Audit';if(value==='quality')return en?'Quality':'Ποιότητα';return en?'General':'Γενικό'}

export function QuestionnairesPanel(){
 const {language}=useLanguage(),en=language==='en';const {confirm}=useFeedback();const [rows,setRows]=useState(load);const [selectedId,setSelectedId]=useState(null);const [editor,setEditor]=useState(null);const selected=useMemo(()=>rows.find(x=>x.id===selectedId)||null,[rows,selectedId])
 function persist(next){setRows(next);saveSnapshot(STORE,next)}
 function newQuestionnaire(){setEditor({kind:'questionnaire',mode:'new',draft:{id:id('questionnaire'),title:'',category:'general',status:'active',questions:[]}})}
 function editQuestionnaire(){if(selected)setEditor({kind:'questionnaire',mode:'edit',draft:{...selected}})}
 function saveQuestionnaire(draft){const normalized={...draft,title:draft.title.trim()};if(!normalized.title)return;persist(editor.mode==='new'?[...rows,normalized]:rows.map(x=>x.id===normalized.id?normalized:x));setSelectedId(normalized.id);setEditor(null)}
 async function removeQuestionnaire(row){const ok=await confirm({title:en?'Delete questionnaire':'Διαγραφή ερωτηματολογίου',message:en?'Delete this questionnaire template? Existing completed forms are not affected.':'Να διαγραφεί αυτό το πρότυπο ερωτηματολογίου; Οι ήδη συμπληρωμένες φόρμες δεν επηρεάζονται.',confirmLabel:en?'Delete':'Διαγραφή',danger:true});if(!ok)return;persist(rows.filter(x=>x.id!==row.id));if(selectedId===row.id)setSelectedId(null)}
 function newQuestion(){setEditor({kind:'question',mode:'new',questionnaireId:selected.id,draft:{id:id('question'),label:'',type:'rating',required:true,options:[]}})}
 function editQuestion(question){setEditor({kind:'question',mode:'edit',questionnaireId:selected.id,draft:{...question,options:Array.isArray(question.options)?question.options:[]}})}
 function saveQuestion(draft){const q={...draft,label:draft.label.trim(),options:(draft.options||[]).map(x=>String(x).trim()).filter(Boolean)};if(!q.label)return;persist(rows.map(row=>row.id!==editor.questionnaireId?row:{...row,questions:editor.mode==='new'?[...row.questions,q]:row.questions.map(x=>x.id===q.id?q:x)}));setEditor(null)}
 async function removeQuestion(question){const ok=await confirm({title:en?'Delete question':'Διαγραφή ερώτησης',message:en?'Remove this question from the questionnaire?':'Να αφαιρεθεί η ερώτηση από το ερωτηματολόγιο;',confirmLabel:en?'Delete':'Διαγραφή',danger:true});if(ok)persist(rows.map(row=>row.id!==selected.id?row:{...row,questions:row.questions.filter(x=>x.id!==question.id)}))}
 function move(index,delta){const target=index+delta;if(target<0||target>=selected.questions.length)return;const questions=[...selected.questions];[questions[index],questions[target]]=[questions[target],questions[index]];persist(rows.map(row=>row.id===selected.id?{...row,questions}:row))}

 return <div className="questionnaires-panel workspace-column workspace-fill">
  {!selected?<><div className="section-toolbar"><div><h2>{en?'Questionnaires':'Ερωτηματολόγια'}</h2><p>{en?'Reusable questionnaires for training, audits, evaluations and other workflows.':'Επαναχρησιμοποιήσιμα ερωτηματολόγια για εκπαίδευση, audits, αξιολογήσεις και άλλες ροές.'}</p></div><Button onClick={newQuestionnaire}><Plus size={15}/>{en?'New questionnaire':'Νέο ερωτηματολόγιο'}</Button></div><div className="table-wrap scroll-table questionnaires-registry"><table className="data-table sticky-table"><thead><tr><th>{en?'Questionnaire':'Ερωτηματολόγιο'}</th><th>{en?'Category':'Κατηγορία'}</th><th>{en?'Questions':'Ερωτήσεις'}</th><th>{en?'Status':'Κατάσταση'}</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="clickable-row" onClick={()=>setSelectedId(row.id)}><td><strong>{row.title}</strong></td><td>{categoryLabel(row.category,en)}</td><td>{row.questions.length}</td><td><span className={`status-badge ${row.status==='active'?'active':''}`}>{row.status==='active'?(en?'Active':'Ενεργό'):(en?'Inactive':'Ανενεργό')}</span></td></tr>)}</tbody></table></div></>:<EntityRecordShell className="questionnaire-record-shell workspace-fill" avatar={<ClipboardList size={19}/>} eyebrow={en?'QUESTIONNAIRE':'ΕΡΩΤΗΜΑΤΟΛΟΓΙΟ'} title={selected.title} subtitle={`${selected.questions.length} ${en?'questions':'ερωτήσεις'} · ${categoryLabel(selected.category,en)}`} status={<span className={`status-badge ${selected.status==='active'?'active':''}`}>{selected.status==='active'?(en?'Active':'Ενεργό'):(en?'Inactive':'Ανενεργό')}</span>} onBack={()=>setSelectedId(null)} backLabel={en?'Back to questionnaires':'Επιστροφή στα ερωτηματολόγια'}>
    <div className="record-section workspace-column workspace-fill questionnaire-questions-section"><div className="record-section-header"><div><span className="eyebrow">{en?'QUESTIONS':'ΕΡΩΤΗΣΕΙΣ'}</span><h3>{en?'Questionnaire questions':'Ερωτήσεις ερωτηματολογίου'}</h3><p>{en?'Select the answer type, required status and order for each question.':'Ορίστε τον τύπο απάντησης, αν είναι υποχρεωτική και τη σειρά κάθε ερώτησης.'}</p></div><div className="questionnaire-record-actions"><Button onClick={newQuestion}><Plus size={15}/>{en?'New question':'Νέα ερώτηση'}</Button><button type="button" className="lo-icon-button lo-icon-button-edit" title={en?'Edit questionnaire':'Επεξεργασία ερωτηματολογίου'} aria-label={en?'Edit questionnaire':'Επεξεργασία ερωτηματολογίου'} onClick={editQuestionnaire}><Pencil size={16}/></button><button type="button" className="lo-icon-button lo-icon-button-danger" title={en?'Delete questionnaire':'Διαγραφή ερωτηματολογίου'} aria-label={en?'Delete questionnaire':'Διαγραφή ερωτηματολογίου'} onClick={()=>removeQuestionnaire(selected)}><Trash2 size={16}/></button></div></div><div className="table-wrap scroll-table questionnaire-questions-table"><table className="data-table sticky-table"><thead><tr><th>#</th><th>{en?'Question':'Ερώτηση'}</th><th>{en?'Type':'Τύπος'}</th><th>{en?'Required':'Υποχρεωτική'}</th><th>{en?'Actions':'Ενέργειες'}</th></tr></thead><tbody>{selected.questions.map((q,index)=><tr key={q.id}><td>{index+1}</td><td><strong>{q.label}</strong></td><td>{types[q.type]?.[en?'en':'el']||q.type}</td><td>{q.required?(en?'Yes':'Ναι'):(en?'No':'Όχι')}</td><td className="open-record-cell"><div className="record-inline-actions questionnaire-question-actions"><button className="lo-icon-button lo-icon-button-neutral lo-icon-button-sm" title={en?'Move up':'Μετακίνηση πάνω'} aria-label={en?'Move question up':'Μετακίνηση ερώτησης πάνω'} disabled={index===0} onClick={()=>move(index,-1)}><ArrowUp size={15}/></button><button className="lo-icon-button lo-icon-button-neutral lo-icon-button-sm" title={en?'Move down':'Μετακίνηση κάτω'} aria-label={en?'Move question down':'Μετακίνηση ερώτησης κάτω'} disabled={index===selected.questions.length-1} onClick={()=>move(index,1)}><ArrowDown size={15}/></button><button className="lo-icon-button lo-icon-button-edit lo-icon-button-sm" title={en?'Edit question':'Επεξεργασία ερώτησης'} aria-label={en?'Edit question':'Επεξεργασία ερώτησης'} onClick={()=>editQuestion(q)}><Pencil size={15}/></button><button className="lo-icon-button lo-icon-button-danger lo-icon-button-sm" title={en?'Delete question':'Διαγραφή ερώτησης'} aria-label={en?'Delete question':'Διαγραφή ερώτησης'} onClick={()=>removeQuestion(q)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table>{!selected.questions.length&&<div className="inline-empty">{en?'No questions yet.':'Δεν υπάρχουν ακόμη ερωτήσεις.'}</div>}</div></div>
   </EntityRecordShell>}
  {editor?.kind==='questionnaire'&&<QuestionnaireDialog en={en} value={editor.draft} onClose={()=>setEditor(null)} onSave={saveQuestionnaire}/>} {editor?.kind==='question'&&<QuestionDialog en={en} value={editor.draft} onClose={()=>setEditor(null)} onSave={saveQuestion}/>} 
 </div>
}
function QuestionnaireDialog({en,value,onClose,onSave}){const [d,setD]=useState(value);return <ObserverDialog width="standard" title={en?'Questionnaire':'Ερωτηματολόγιο'} onClose={onClose} footer={<DialogActions onCancel={onClose} onSave={()=>onSave(d)} disabled={!d.title.trim()}/>}><div className="entry-grid"><label><span>{en?'Title *':'Τίτλος *'}</span><input autoFocus value={d.title} onChange={e=>setD(x=>({...x,title:e.target.value}))}/></label><label><span>{en?'Category':'Κατηγορία'}</span><select value={d.category} onChange={e=>setD(x=>({...x,category:e.target.value}))}><option value="general">{en?'General':'Γενικό'}</option><option value="training">{en?'Training':'Εκπαίδευση'}</option><option value="audit">Audit</option><option value="quality">{en?'Quality':'Ποιότητα'}</option></select></label><label><span>{en?'Status':'Κατάσταση'}</span><select value={d.status} onChange={e=>setD(x=>({...x,status:e.target.value}))}><option value="active">{en?'Active':'Ενεργό'}</option><option value="inactive">{en?'Inactive':'Ανενεργό'}</option></select></label></div></ObserverDialog>}
function QuestionDialog({en,value,onClose,onSave}){const [d,setD]=useState({...value,options:Array.isArray(value.options)?value.options:[]});const choice=d.type==='single'||d.type==='multiple';function addOption(){setD(x=>({...x,options:[...(x.options||[]),'']}))}function updateOption(index,text){setD(x=>({...x,options:x.options.map((item,i)=>i===index?text:item)}))}function removeOption(index){setD(x=>({...x,options:x.options.filter((_,i)=>i!==index)}))}return <ObserverDialog width="standard" title={en?'Question':'Ερώτηση'} subtitle={en?'Define the question and how it will be answered.':'Ορίστε την ερώτηση και τον τρόπο με τον οποίο θα απαντάται.'} onClose={onClose} footer={<DialogActions onCancel={onClose} onSave={()=>onSave(d)} disabled={!d.label.trim()||(choice&&!d.options.some(x=>x.trim()))}/>}><div className="question-editor"><label className="question-editor-main"><span>{en?'Question *':'Ερώτηση *'}</span><textarea autoFocus rows={3} value={d.label} onChange={e=>setD(x=>({...x,label:e.target.value}))} placeholder={en?'Write the question…':'Γράψτε την ερώτηση…'}/></label><div className="question-editor-settings"><label><span>{en?'Answer type':'Τύπος απάντησης'}</span><select value={d.type} onChange={e=>setD(x=>({...x,type:e.target.value,options:(e.target.value==='single'||e.target.value==='multiple')?(x.options?.length?x.options:['','']):[]}))}>{Object.entries(types).map(([key,label])=><option key={key} value={key}>{label[en?'en':'el']}</option>)}</select></label><label className="question-required-toggle"><input type="checkbox" checked={d.required} onChange={e=>setD(x=>({...x,required:e.target.checked}))}/><span>{en?'Required question':'Υποχρεωτική ερώτηση'}</span></label></div>{choice&&<section className="question-options-editor"><div className="question-options-heading"><div><strong>{en?'Answer options':'Επιλογές απάντησης'}</strong><small>{en?'Add the choices that will be available to the user.':'Προσθέστε τις επιλογές που θα εμφανίζονται στον χρήστη.'}</small></div><Button variant="secondary" onClick={addOption}><Plus size={14}/>{en?'Option':'Επιλογή'}</Button></div><div className="question-options-list">{d.options.map((option,index)=><div className="question-option-row" key={index}><span>{index+1}</span><input value={option} onChange={e=>updateOption(index,e.target.value)} placeholder={`${en?'Option':'Επιλογή'} ${index+1}`}/><button type="button" className="lo-icon-button lo-icon-button-danger lo-icon-button-sm" onClick={()=>removeOption(index)} title={en?'Remove option':'Αφαίρεση επιλογής'} aria-label={en?'Remove option':'Αφαίρεση επιλογής'}><Trash2 size={15}/></button></div>)}{!d.options.length&&<div className="inline-empty">{en?'No options yet.':'Δεν υπάρχουν ακόμη επιλογές.'}</div>}</div></section>}</div></ObserverDialog>}
