import { useEffect,useState } from 'react'
import { ArrowDown,ArrowUp,ClipboardCheck,Plus,Trash2 } from 'lucide-react'
import { Button } from '../../design-system/Button'
import { SaveButton } from '../../design-system/SaveButton'
import { useLanguage } from '../../core/i18n/LanguageContext'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { useTenant } from '../../core/tenant/TenantContext'
import { loadTrainerFeedbackTemplateAsync,saveTrainerFeedbackTemplateAsync } from '../training/trainingService'
import { DEFAULT_TRAINER_FEEDBACK_TEMPLATE,normalizeTrainerFeedbackTemplate } from '../training/trainingFeedbackTemplate'

const newQuestion=()=>({id:`feedback-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,labelEl:'',labelEn:''})

export function TrainingFeedbackTemplatePanel(){
 const {language}=useLanguage(),en=language==='en', {tenant}=useTenant(),{notify,notifyError}=useFeedback()
 const [value,setValue]=useState(()=>normalizeTrainerFeedbackTemplate(DEFAULT_TRAINER_FEEDBACK_TEMPLATE)),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false)
 useEffect(()=>{let active=true;if(!tenant?.id){setLoading(false);return};setLoading(true);loadTrainerFeedbackTemplateAsync(tenant.id).then(data=>{if(active)setValue(data)}).catch(error=>{if(active)notifyError(error,'load',{operation:'training_feedback_template_load'})}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[tenant?.id,notifyError])
 function updateQuestion(id,patch){setValue(current=>({...current,questions:current.questions.map(q=>q.id===id?{...q,...patch}:q)}))}
 function removeQuestion(id){setValue(current=>({...current,questions:current.questions.filter(q=>q.id!==id)}))}
 function move(index,direction){const target=index+direction;if(target<0||target>=value.questions.length)return;setValue(current=>{const questions=[...current.questions];[questions[index],questions[target]]=[questions[target],questions[index]];return {...current,questions}})}
 async function save(){if(!tenant?.id||saving||!value.questions.length||value.questions.some(q=>!q.labelEl.trim()))return;setSaving(true);try{const saved=await saveTrainerFeedbackTemplateAsync(tenant.id,value);setValue(saved);notify(en?'Trainer evaluation template saved.':'Το πρότυπο αξιολόγησης εκπαιδευτή αποθηκεύτηκε.','success')}catch(error){notifyError(error,'save',{operation:'training_feedback_template_save'})}finally{setSaving(false)}}
 return <div className="workspace-column workspace-fill training-feedback-template-panel">
  <div className="section-toolbar"><div><span className="eyebrow">{en?'Training':'Εκπαίδευση'}</span><h2>{en?'Trainer evaluation template':'Πρότυπο αξιολόγησης εκπαιδευτή'}</h2><p>{en?'This template is copied into each new training program so historical evaluations remain stable.':'Το πρότυπο αντιγράφεται σε κάθε νέο πρόγραμμα ώστε οι παλιές αξιολογήσεις να παραμένουν αμετάβλητες.'}</p></div><Button onClick={()=>setValue(current=>({...current,questions:[...current.questions,newQuestion()]}))}><Plus size={15}/>{en?'Question':'Ερώτηση'}</Button></div>
  {loading?<div className="inline-empty">{en?'Loading template...':'Φόρτωση προτύπου...'}</div>:<><div className="record-section"><div className="entry-grid"><label><span>{en?'Title EL':'Τίτλος EL'}</span><input value={value.titleEl} onChange={e=>setValue(x=>({...x,titleEl:e.target.value}))}/></label><label><span>{en?'Title EN':'Τίτλος EN'}</span><input value={value.titleEn} onChange={e=>setValue(x=>({...x,titleEn:e.target.value}))}/></label></div></div><div className="training-feedback-question-list">{value.questions.map((q,index)=><div key={q.id} className="training-feedback-question-row"><span className="training-question-index">{index+1}</span><div className="entry-grid"><label><span>EL</span><input value={q.labelEl} onChange={e=>updateQuestion(q.id,{labelEl:e.target.value})}/></label><label><span>EN</span><input value={q.labelEn} onChange={e=>updateQuestion(q.id,{labelEn:e.target.value})}/></label></div><div className="record-actions"><button className="lo-icon-button lo-icon-button-sm" disabled={index===0} onClick={()=>move(index,-1)}><ArrowUp size={14}/></button><button className="lo-icon-button lo-icon-button-sm" disabled={index===value.questions.length-1} onClick={()=>move(index,1)}><ArrowDown size={14}/></button><button className="lo-icon-button lo-icon-button-danger lo-icon-button-sm" disabled={value.questions.length<=1} onClick={()=>removeQuestion(q.id)}><Trash2 size={14}/></button></div></div>)}</div><div className="inline-edit-footer"><div className="source-truth-note"><ClipboardCheck size={15}/><span>{en?'Scale: 1–5. A free comment is included automatically in the participant form.':'Κλίμακα: 1–5. Στη φόρμα συμμετέχοντα περιλαμβάνεται αυτόματα και ελεύθερο σχόλιο.'}</span></div><SaveButton loading={saving} disabled={saving||!value.questions.length||value.questions.some(q=>!q.labelEl.trim())} onClick={save}>{en?'Save template':'Αποθήκευση προτύπου'}</SaveButton></div></>}
 </div>
}
