-- Phase 4B: reviewed clinical knowledge expansion. Nothing here is auto-approved.
with chunks(authority,title,chunk_index,heading,content,citation_label) as (values
('CDC/NHSN','2026 NHSN Patient Safety Component Manual',1,'Device-associated HAI denominators','For device-associated HAI surveillance, LIRA must use the denominator required by the applicable NHSN protocol, such as central-line days for CLABSI and urinary-catheter days for CAUTI. Patient-days are not interchangeable with device-days. A rate per 1,000 device-days is the event count divided by the relevant device-days multiplied by 1,000.','CDC/NHSN 2026 · device-associated surveillance'),
('CDC/NHSN','2026 NHSN Patient Safety Component Manual',2,'CLABSI surveillance guardrail','A bloodstream infection must satisfy the applicable NHSN laboratory-confirmed bloodstream infection criteria and central-line attribution rules before it is counted as CLABSI. A positive blood culture by itself is not sufficient for LIRA to declare a CLABSI.','CDC/NHSN 2026 · CLABSI'),
('CDC/NHSN','2026 NHSN Patient Safety Component Manual',3,'CAUTI surveillance guardrail','A urinary event must satisfy the applicable NHSN UTI criteria and urinary-catheter attribution rules before it is counted as CAUTI. LIRA must not classify bacteriuria or a positive urine culture alone as CAUTI.','CDC/NHSN 2026 · CAUTI'),
('CDC/NHSN','2026 NHSN Patient Safety Component Manual',4,'Ventilator-associated events','Adult NHSN VAE surveillance is a surveillance algorithm for eligible adult locations. Pediatric and neonatal surveillance use their applicable protocols. LIRA must not equate VAE automatically with ventilator-associated pneumonia and must preserve the age/location-specific surveillance framework.','CDC/NHSN 2026 · VAE'),
('ECDC','HAI-Net ICU protocol',1,'ICU HAI standardisation','ECDC HAI-Net ICU version 2.3 standardises definitions, data collection and reporting for ICU HAI surveillance across Europe. LIRA should preserve ICU context, exposure denominators and the protocol event definitions when comparing departments or periods.','ECDC HAI-Net ICU v2.3 · surveillance'),
('ECDC','HAI-Net ICU protocol',2,'Surveillance signal versus confirmed event','A statistical increase, cluster signal or temporal concentration is a surveillance signal requiring assessment; it is not by itself confirmation of an outbreak or proof of transmission. LIRA should describe such findings as signals requiring investigation and epidemiological review.','ECDC HAI-Net ICU v2.3 · interpretation'),
('EUCAST','Clinical breakpoint tables',1,'EUCAST S I R categories','EUCAST defines S as susceptible with a standard dosing regimen, I as susceptible with increased exposure, and R as resistant. Both S and I are susceptible categories under the current terminology; LIRA must not automatically combine I with R as non-susceptible.','EUCAST · definitions of S, I and R'),
('EUCAST','Clinical breakpoint tables',2,'Breakpoint version control','Clinical breakpoints are organism-agent specific and versioned. Interpretation must use the breakpoint table and notes valid for the relevant organism, antimicrobial and testing context. If required breakpoint information is unavailable, LIRA should report that interpretation cannot be completed rather than infer susceptibility.','EUCAST v16.1 · breakpoint governance'),
('WHO','WHO hand hygiene in health care resources',1,'Five Moments','The WHO Five Moments are: before touching a patient; before a clean or aseptic procedure; after body-fluid exposure risk; after touching a patient; and after touching patient surroundings. LIRA should analyse compliance by opportunity and moment when those data are available.','WHO · Five Moments for Hand Hygiene'),
('WHO','WHO hand hygiene in health care resources',2,'Gloves and hand hygiene','Glove use does not replace hand hygiene when a hand-hygiene indication is present. LIRA should therefore keep glove-use observations separate from whether the indicated hand-hygiene action occurred.','WHO · hand hygiene and glove use'),
('WHO','Minimum requirements for infection prevention and control programmes',1,'IPC programme interpretation','WHO minimum requirements operationalise the IPC core-components framework at national and healthcare-facility level. LIRA should use them to identify programme-level gaps and improvement opportunities, while avoiding patient-specific diagnostic conclusions from programme indicators.','WHO 2019 · IPC minimum requirements')
)
insert into public.lira_knowledge_chunks(source_id,chunk_index,heading,content,citation_label,token_count,content_hash,metadata,embedding_status)
select s.id,x.chunk_index,x.heading,x.content,x.citation_label,ceil(length(x.content)/4.0)::integer,md5(x.content),jsonb_build_object('curation','official-source-summary','review_required',true,'phase','4B'),'not_required'
from chunks x join public.lira_knowledge_sources s on s.authority=x.authority and s.title=x.title
where s.status in ('review','approved')
on conflict(source_id,chunk_index) do update set heading=excluded.heading,content=excluded.content,citation_label=excluded.citation_label,token_count=excluded.token_count,content_hash=excluded.content_hash,metadata=excluded.metadata,embedding_status=excluded.embedding_status;
