-- Phase 4H: ESBL-producing Enterobacterales and AMR interpretation.
insert into public.lira_knowledge_sources(organization_id,source_type,title,authority,source_url,source_version,language,status,metadata,ingestion_status)
values
(null,'guidance','About ESBL-producing Enterobacterales','CDC','https://www.cdc.gov/esbl-producing-enterobacterales/about/index.html','2025-06','en','review',jsonb_build_object('official',true,'topic','esbl-enterobacterales','review_required',true,'phase','4H'),'pending'),
(null,'standard','EUCAST Clinical Breakpoint Tables','EUCAST','https://www.eucast.org/clinical_breakpoints','v16.0 (2026)','en','review',jsonb_build_object('official',true,'topic','antimicrobial-breakpoints','review_required',true,'phase','4H','version_sensitive',true),'pending')
on conflict do nothing;

with x(authority,title,chunk_index,heading,content,citation_label) as (values
('CDC','About ESBL-producing Enterobacterales',0,'ESBL-producing Enterobacterales','Extended-spectrum beta-lactamase-producing Enterobacterales are Gram-negative bacteria with enzymes that can inactivate important beta-lactam antimicrobials. LIRA must distinguish organism identification, resistance phenotype and clinical infection rather than treating them as interchangeable findings.','CDC 2025 · ESBL-producing Enterobacterales'),
('CDC','About ESBL-producing Enterobacterales',1,'ESBL — colonization and transmission','People can carry ESBL-producing Enterobacterales without symptoms. In healthcare, transmission can occur through contact, including contaminated hands, surfaces or equipment. Colonization alone must not be represented as active infection.','CDC 2025 · ESBL colonization and transmission'),
('CDC','About ESBL-producing Enterobacterales',2,'ESBL — treatment guardrail','Antimicrobial treatment decisions require the clinical syndrome, specimen context and susceptibility results. LIRA must not prescribe or select therapy solely from an ESBL label and must not infer susceptibility to an untested agent.','CDC 2025 · ESBL treatment guardrail'),
('EUCAST','EUCAST Clinical Breakpoint Tables',0,'Breakpoint version control','Antimicrobial susceptibility categories depend on the applicable EUCAST breakpoint table and methodology. LIRA must preserve the breakpoint version used by the laboratory and must not reinterpret historical susceptibility results with a newer breakpoint version without explicitly stating that recalculation.','EUCAST v16.0 · breakpoint version control'),
('EUCAST','EUCAST Clinical Breakpoint Tables',1,'S/I/R interpretation','EUCAST susceptibility categories and breakpoint definitions must be interpreted using the version applicable to the laboratory result. LIRA must not convert MIC or inhibition-zone values into S, I or R unless the organism, antimicrobial, method and applicable breakpoint are known.','EUCAST v16.0 · susceptibility interpretation'),
('EUCAST','EUCAST Clinical Breakpoint Tables',2,'MDR/XDR guardrail','A resistance phenotype such as ESBL or carbapenem resistance is not by itself equivalent to a complete MDR/XDR classification. LIRA must apply the explicitly adopted MDR/XDR definition and sufficient tested antimicrobial categories before assigning such a classification.','EUCAST context · MDR/XDR guardrail')
)
insert into public.lira_knowledge_chunks(source_id,chunk_index,heading,content,citation_label,token_count,content_hash,metadata,embedding_status)
select s.id,x.chunk_index,x.heading,x.content,x.citation_label,ceil(length(x.content)/4.0)::integer,md5(x.content),jsonb_build_object('curation','official-source-summary','review_required',true,'phase','4H'),'not_required'
from x join public.lira_knowledge_sources s on s.authority=x.authority and s.title=x.title where s.status='review'
on conflict(source_id,chunk_index) do update set heading=excluded.heading,content=excluded.content,citation_label=excluded.citation_label,token_count=excluded.token_count,content_hash=excluded.content_hash,metadata=excluded.metadata,embedding_status=excluded.embedding_status;
update public.lira_knowledge_sources s set ingestion_status='ingested',updated_at=now() where s.status='review' and s.metadata->>'phase'='4H' and exists(select 1 from public.lira_knowledge_chunks c where c.source_id=s.id);
