-- Phase 4L: C. difficile prevention, diagnostic stewardship and surveillance.
insert into public.lira_knowledge_sources(organization_id,source_type,title,authority,source_url,source_version,language,status,metadata,ingestion_status)
values
(null,'guidance','Clinical Guidance for C. diff Infection Prevention in Acute Care Facilities','CDC','https://www.cdc.gov/c-diff/hcp/clinical-guidance/index.html','2026-05','en','review',jsonb_build_object('official',true,'topic','cdiff-prevention','review_required',true,'phase','4L'),'pending'),
(null,'surveillance','NHSN Patient Safety Component Manual — Multidrug-Resistant Organism & Clostridioides difficile Infection Module','CDC/NHSN','https://www.cdc.gov/nhsn/pdfs/pscmanual/12pscmdro_cdadcurrent.pdf','2026','en','review',jsonb_build_object('official',true,'topic','cdiff-surveillance','review_required',true,'phase','4L','version_sensitive',true),'pending')
on conflict do nothing;

with x(authority,title,chunk_index,heading,content,citation_label) as (values
('CDC','Clinical Guidance for C. diff Infection Prevention in Acute Care Facilities',0,'C. difficile diagnostic stewardship','Testing should be limited to patients whose clinical presentation is compatible with C. difficile infection and interpreted in the clinical context. LIRA must not classify colonization or a laboratory result alone as symptomatic CDI and should flag missing symptom context rather than invent it.','CDC 2026 · C. difficile diagnostic stewardship'),
('CDC','Clinical Guidance for C. diff Infection Prevention in Acute Care Facilities',1,'C. difficile IPC','Prompt isolation or appropriate precautions for suspected or confirmed CDI, hand hygiene, environmental cleaning and antimicrobial stewardship are components of prevention. LIRA should present these as coordinated IPC actions and respect the facility protocol.','CDC 2026 · C. difficile IPC'),
('CDC','Clinical Guidance for C. diff Infection Prevention in Acute Care Facilities',2,'Repeat testing guardrail','LIRA should not recommend indiscriminate repeat testing or testing to document cure. Recommendations must follow the applicable diagnostic protocol and clinical context.','CDC 2026 · C. difficile testing guardrail'),
('CDC/NHSN','NHSN Patient Safety Component Manual — Multidrug-Resistant Organism & Clostridioides difficile Infection Module',0,'CDI surveillance is definition-based','NHSN CDI surveillance uses defined laboratory-identified event rules, locations, time windows and attribution logic. LIRA must preserve the applicable surveillance version and must not substitute a bedside diagnosis for the surveillance definition or vice versa.','CDC/NHSN 2026 · CDI surveillance'),
('CDC/NHSN','NHSN Patient Safety Component Manual — Multidrug-Resistant Organism & Clostridioides difficile Infection Module',1,'CDI duplicate and attribution logic','Duplicate-event and attribution rules depend on the applicable NHSN protocol and event timing. LIRA must use recorded dates and locations and must not infer missing exposure or attribution data.','CDC/NHSN 2026 · CDI attribution guardrail'),
('CDC/NHSN','NHSN Patient Safety Component Manual — Multidrug-Resistant Organism & Clostridioides difficile Infection Module',2,'CDI denominator integrity','Facility- and location-level CDI metrics require the denominator specified by the surveillance protocol for the same population and period. LIRA must not substitute an unrelated denominator or mix periods when calculating rates.','CDC/NHSN 2026 · CDI denominator guardrail')
)
insert into public.lira_knowledge_chunks(source_id,chunk_index,heading,content,citation_label,token_count,content_hash,metadata,embedding_status)
select s.id,x.chunk_index,x.heading,x.content,x.citation_label,ceil(length(x.content)/4.0)::integer,md5(x.content),jsonb_build_object('curation','official-source-summary','review_required',true,'phase','4L'),'not_required'
from x join public.lira_knowledge_sources s on s.authority=x.authority and s.title=x.title where s.status='review'
on conflict(source_id,chunk_index) do update set heading=excluded.heading,content=excluded.content,citation_label=excluded.citation_label,token_count=excluded.token_count,content_hash=excluded.content_hash,metadata=excluded.metadata,embedding_status=excluded.embedding_status;
update public.lira_knowledge_sources s set ingestion_status='ingested',updated_at=now() where s.status='review' and s.metadata->>'phase'='4L' and exists(select 1 from public.lira_knowledge_chunks c where c.source_id=s.id);
