alter table public.indicator_definitions disable trigger trg_audit_indicator_definitions;
insert into public.indicator_definitions (organization_id,indicator_key,version,title_el,title_en,category,numerator_definition,denominator_definition,multiplier,unit,unit_en,source_authority,status,calculation_type,numerator_metric,denominator_metric,target_value,direction,effective_from,approved_at)
values
(null,'hai-per-1000','2026.1','Ενεργή επιτήρηση ανά 1.000 ασθενοημέρες','Active surveillance per 1,000 patient-days','surveillance','{"description":"Active surveillance episodes started in period"}'::jsonb,'{"description":"Patient-days in period"}'::jsonb,1000,'ανά 1.000 ασθενοημέρες','per 1,000 patient-days','Limoxis · Surveillance / Patient Days','active','auto','active_surveillance','patient_days',null,'context','2026-01-01',now()),
(null,'mdr-active-share','2026.1','Ενεργή επιτήρηση με αντοχή','Active surveillance with resistance','surveillance','{"description":"Active surveillance episodes with resistance status"}'::jsonb,'{"description":"Active surveillance episodes"}'::jsonb,100,'%','%','Limoxis · Surveillance','active','auto','resistant_active_surveillance','active_surveillance',null,'context','2026-01-01',now()),
(null,'hh-compliance','2026.1','Συμμόρφωση υγιεινής χεριών','Hand hygiene compliance','prevention','{"description":"Compliant WHO hand-hygiene actions"}'::jsonb,'{"description":"Observed opportunities"}'::jsonb,100,'%','%','WHO Hand Hygiene','active','auto','hh_compliant_actions','hh_opportunities',80,'higher','2026-01-01',now()),
(null,'bundle-compliance','2026.1','Συμμόρφωση bundles','Bundle compliance','prevention','{"description":"All-or-none bundle passes"}'::jsonb,'{"description":"Completed bundle assessments"}'::jsonb,100,'%','%','Limoxis · Prevention Bundles','active','auto','bundle_all_or_none_pass','bundle_executions',95,'higher','2026-01-01',now()),
(null,'vaccination-coverage','2026.1','Εμβολιαστική κάλυψη προσωπικού','Staff vaccination coverage','workforce','{"description":"Active staff with vaccination record in period"}'::jsonb,'{"description":"Active staff"}'::jsonb,100,'%','%','Limoxis · Employee Health','active','auto','active_staff_with_vaccination','active_staff',null,'context','2026-01-01',now()),
(null,'training-completion','2026.1','Ολοκλήρωση εκπαίδευσης','Training completion','workforce','{"description":"Completed training assignments"}'::jsonb,'{"description":"Training assignments"}'::jsonb,100,'%','%','Limoxis · Training','active','auto','training_completed','training_assignments',90,'higher','2026-01-01',now()),
(null,'mdro-bsi-rate','2026.1','MDR/XDR/PDR θετικές καλλιέργειες ανά 1.000 ασθενοημέρες','MDR/XDR/PDR positive cultures per 1,000 patient-days','laboratory','{"description":"MDR/XDR/PDR positive microbiology results"}'::jsonb,'{"description":"Patient-days in period"}'::jsonb,1000,'ανά 1.000 ασθενοημέρες','per 1,000 patient-days','Limoxis · Laboratory / AMR','active','auto','mdro_bsi','patient_days',null,'context','2026-01-01',now()),
(null,'abhr-use','2026.1','Κατανάλωση αλκοολούχου αντισηπτικού ανά 1.000 ασθενοημέρες','Alcohol hand-rub use per 1,000 patient-days','prevention','{"description":"Alcohol hand-rub litres"}'::jsonb,'{"description":"Patient-days in period"}'::jsonb,1000,'L/1.000 ασθενοημέρες','L/1,000 patient-days','Limoxis · Antiseptic Consumption','active','auto','abhr_litres','patient_days',null,'context','2026-01-01',now()),
(null,'eody-reporting-completeness','2026.1','Πληρότητα αναφοράς δεικτών ΕΟΔΥ','EODY indicator reporting completeness','quality','{"description":"Manual reporting completeness percentage"}'::jsonb,'{}'::jsonb,1,'%','%','ΕΟΔΥ / Governance','active','manual',null,null,100,'higher','2026-01-01',now())
on conflict do nothing;
alter table public.indicator_definitions enable trigger trg_audit_indicator_definitions;
