-- Phase 4C: governed summaries for outbreak response, AMR, precautions and stewardship. REVIEW only.
insert into public.lira_knowledge_sources(authority,title,source_type,source_version,status,ingestion_status,source_url,metadata)
values
('WHO','IPC outbreak preparedness, readiness and response toolkit','guideline','2022','review','pending','https://www.who.int/publications/i/item/9789240051027',jsonb_build_object('scope','global','official',true,'curriculum_category','outbreak-response','safety_flags',jsonb_build_array('assistive_only','no_autonomous_outbreak_declaration'))),
('CDC','Transmission-Based Precautions','guideline','2024','review','pending','https://www.cdc.gov/infection-control/hcp/basics/transmission-based-precautions.html',jsonb_build_object('scope','healthcare','official',true,'curriculum_category','isolation-precautions','safety_flags',jsonb_build_array('assistive_only'))),
('CDC','Core Elements of Hospital Antibiotic Stewardship Programs','guideline','2025-web','review','pending','https://www.cdc.gov/antibiotic-use/hcp/core-elements/hospital.html',jsonb_build_object('scope','hospital','official',true,'curriculum_category','antimicrobial-stewardship','safety_flags',jsonb_build_array('assistive_only','no_prescribing')))
on conflict do nothing;

with chunks(authority,title,chunk_index,heading,content,citation_label) as (values
('WHO','IPC outbreak preparedness, readiness and response toolkit',0,'Outbreak preparedness and response','Healthcare facilities can amplify transmission of emerging infections and multidrug-resistant organisms. IPC preparedness, readiness and response should support prevention and containment while maintaining safe care. LIRA may identify epidemiological signals and response tasks, but a signal is not an autonomous outbreak declaration.','WHO 2022 · IPC outbreak preparedness and response'),
('WHO','IPC outbreak preparedness, readiness and response toolkit',1,'Cluster investigation workflow','When an unusual temporal, spatial or organism pattern is detected, LIRA should support structured verification: confirm the event definition and laboratory information, define the affected population and time/place pattern, review patient links and exposures, assess IPC practice and environment, and escalate to the responsible IPC team. Conclusions must distinguish observed data from hypotheses.','WHO 2022 · outbreak investigation support'),
('WHO','IPC outbreak preparedness, readiness and response toolkit',2,'AMR containment','IPC is central to limiting healthcare transmission of antimicrobial-resistant organisms. LIRA should combine organism/resistance patterns with epidemiological context and IPC findings; resistance alone does not prove patient-to-patient transmission.','WHO · IPC and AMR containment'),
('CDC','Transmission-Based Precautions',0,'Two-tier precautions framework','Standard Precautions apply to all patient care. Transmission-Based Precautions are additional measures for patients known or suspected to be infected or colonized with agents requiring extra controls to prevent transmission.','CDC · Standard and Transmission-Based Precautions'),
('CDC','Transmission-Based Precautions',1,'Contact Precautions','For infections or colonization posing increased contact-transmission risk, Contact Precautions include appropriate patient placement, gown and gloves for relevant room interactions, limiting unnecessary transport, dedicated or disposable equipment when feasible, and enhanced attention to environmental cleaning and disinfection.','CDC 2024 · Contact Precautions'),
('CDC','Transmission-Based Precautions',2,'Droplet Precautions','Droplet Precautions are used for pathogens transmitted by respiratory droplets. Measures include source control, appropriate placement, masking for healthcare personnel on room entry as indicated, and limiting unnecessary transport; they are used in addition to Standard Precautions.','CDC 2024 · Droplet Precautions'),
('CDC','Transmission-Based Precautions',3,'Airborne Precautions','Airborne Precautions are used for infections transmitted by the airborne route. Appropriate placement is an airborne infection isolation room when available and healthcare personnel use a fit-tested NIOSH-approved N95 or higher-level respirator as indicated. These precautions are additional to Standard Precautions.','CDC 2024 · Airborne Precautions'),
('CDC','Transmission-Based Precautions',4,'Precaution duration guardrail','Duration and discontinuation of Transmission-Based Precautions depend on the infectious agent, clinical context, persistence of transmission risk and applicable disease-specific recommendations. LIRA must not infer a universal isolation duration from the precaution category alone.','CDC · duration of Transmission-Based Precautions'),
('CDC','Core Elements of Hospital Antibiotic Stewardship Programs',0,'Hospital stewardship purpose','Hospital antibiotic stewardship programmes measure and improve antibiotic prescribing and use to improve patient care and address antimicrobial resistance. LIRA should support stewardship workflows and monitoring, not independently prescribe, stop or change antimicrobial treatment.','CDC 2025 · Hospital Antibiotic Stewardship'),
('CDC','Core Elements of Hospital Antibiotic Stewardship Programs',1,'Core stewardship structure','Hospital stewardship programmes include leadership commitment, accountability, pharmacy expertise, action, tracking, reporting and education. LIRA can map programme evidence and gaps to these elements while keeping local governance and clinical accountability explicit.','CDC · Hospital Stewardship Core Elements'),
('CDC','Core Elements of Hospital Antibiotic Stewardship Programs',2,'Stewardship interventions','Prospective audit and feedback and preauthorization are examples of stewardship interventions. LIRA may identify cases or patterns for review using configured rules, but final antimicrobial decisions remain with authorized clinicians and the local stewardship process.','CDC · stewardship action'),
('CDC','Core Elements of Hospital Antibiotic Stewardship Programs',3,'Stewardship reporting','Stewardship programmes should track and regularly report antibiotic use and resistance information to relevant clinicians and leadership. LIRA should present numerator, denominator, time window, department scope and data provenance when producing stewardship trends.','CDC · stewardship tracking and reporting')
)
insert into public.lira_knowledge_chunks(source_id,chunk_index,heading,content,citation_label,token_count,content_hash,metadata,embedding_status)
select s.id,x.chunk_index,x.heading,x.content,x.citation_label,ceil(length(x.content)/4.0)::integer,md5(x.content),jsonb_build_object('curation','official-source-summary','review_required',true,'phase','4C'),'not_required'
from chunks x join public.lira_knowledge_sources s on s.authority=x.authority and s.title=x.title
where s.status='review'
on conflict(source_id,chunk_index) do update set heading=excluded.heading,content=excluded.content,citation_label=excluded.citation_label,token_count=excluded.token_count,content_hash=excluded.content_hash,metadata=excluded.metadata,embedding_status=excluded.embedding_status;
update public.lira_knowledge_sources s set ingestion_status='ingested',updated_at=now() where status='review' and exists(select 1 from public.lira_knowledge_chunks c where c.source_id=s.id and c.metadata->>'phase'='4C');
