-- Move the CDC/NHSN HAI surveillance criteria checklists (CLABSI/CAUTI/VAP/
-- SSI + the neonatal CLABSI variant) out of hardcoded JS
-- (src/features/surveillance/haiCriteriaDefinitions.js) into the same
-- Platform-Owner-governed central library used for antibiotics/
-- microorganisms, so they can be versioned/edited centrally instead of
-- requiring a code deploy. Uses the existing generic master_library_items
-- infrastructure (fan-out propagation trigger, per-org seeding on org
-- creation) with a new library_key — no schema/trigger changes needed;
-- the checklist's nested {groups:[{id,rule,items:[{id,textEl,textEn}]}]}
-- structure is carried in the existing metadata jsonb column, alongside
-- the system/locked flags every other system library item already sets.

alter table public.master_library_items disable trigger trg_audit_master_library_items;

insert into public.master_library_items (
  organization_id, library_key, code, name_el, name_en, metadata, source_authority, is_active
)
select null, 'hai_criteria', v.code, v.name_el, v.name_en, v.metadata::jsonb, v.source_authority, true
from (values
  ('clabsi', 'CLABSI – Λοίμωξη αιματικής ροής σχετιζόμενη με κεντρικό φλεβικό καθετήρα', 'CLABSI – Central line-associated bloodstream infection', 'CDC/NHSN (simplified)', '{"system":true,"locked":true,"groups":[{"id":"device","rule":"all","items":[{"id":"centralLine48h","textEl":"Κεντρικός φλεβικός καθετήρας in situ για >2 ημερολογιακές ημέρες πριν την ημερομηνία έναρξης","textEn":"Central line in place for >2 calendar days before the date of event"}]},{"id":"micro","rule":"any","items":[{"id":"recognizedPathogen","textEl":"Αναγνωρισμένο παθογόνο σε ≥1 καλλιέργεια αίματος, χωρίς σχέση με λοίμωξη άλλης εντόπισης","textEn":"A recognized pathogen from ≥1 blood culture, unrelated to infection at another site"},{"id":"commonCommensalTwice","textEl":"Κοινός δερματικός κομμενσαλιστής σε ≥2 καλλιέργειες αίματος σε διαφορετικές λήψεις + κλινικά σημεία (πυρετός >38°C, ρίγος ή υπόταση)","textEn":"A common skin commensal from ≥2 separate blood cultures + a clinical sign (fever >38°C, chills, or hypotension)"}]}]}'),
  ('clabsi_neonatal', 'CLABSI (νεογνική/βρεφική) – Λοίμωξη αιματικής ροής σχετιζόμενη με κεντρικό καθετήρα σε ασθενή ≤1 έτους', 'CLABSI (neonatal/infant) – Central line-associated bloodstream infection in a patient ≤1 year', 'CDC/NHSN (simplified, age ≤1 year LCBI criteria)', '{"system":true,"locked":true,"groups":[{"id":"device","rule":"all","items":[{"id":"centralLine48h","textEl":"Κεντρικός φλεβικός καθετήρας in situ για >2 ημερολογιακές ημέρες πριν την ημερομηνία έναρξης","textEn":"Central line in place for >2 calendar days before the date of event"}]},{"id":"micro","rule":"any","items":[{"id":"recognizedPathogen","textEl":"Αναγνωρισμένο παθογόνο σε ≥1 καλλιέργεια αίματος, χωρίς σχέση με λοίμωξη άλλης εντόπισης","textEn":"A recognized pathogen from ≥1 blood culture, unrelated to infection at another site"},{"id":"commonCommensalTwiceInfant","textEl":"Κοινός δερματικός κομμενσαλιστής σε ≥2 καλλιέργειες αίματος σε διαφορετικές λήψεις + ένα από: πυρετός (>38°C), υποθερμία (<36°C πυρήνα), άπνοια ή βραδυκαρδία","textEn":"A common skin commensal from ≥2 separate blood cultures + one of: fever (>38°C core), hypothermia (<36°C core), apnea, or bradycardia"}]}]}'),
  ('cauti', 'CAUTI – Ουρολοίμωξη σχετιζόμενη με ουροκαθετήρα', 'CAUTI – Catheter-associated urinary tract infection', 'CDC/NHSN (simplified)', '{"system":true,"locked":true,"groups":[{"id":"device","rule":"all","items":[{"id":"catheter48h","textEl":"Ουροκαθετήρας in situ για >2 ημερολογιακές ημέρες πριν την ημερομηνία έναρξης","textEn":"Indwelling urinary catheter in place for >2 calendar days before the date of event"}]},{"id":"clinical","rule":"any","items":[{"id":"fever","textEl":"Πυρετός (>38°C)","textEn":"Fever (>38°C)"},{"id":"suprapubicTenderness","textEl":"Υπερηβική ευαισθησία","textEn":"Suprapubic tenderness"},{"id":"urgencyFrequencyDysuria","textEl":"Επιτακτική ούρηση, συχνουρία ή δυσουρία (μετά την αφαίρεση καθετήρα)","textEn":"Urinary urgency, frequency or dysuria (after catheter removal)"}]},{"id":"micro","rule":"all","items":[{"id":"positiveUrineCulture","textEl":"Θετική καλλιέργεια ούρων ≥10⁵ CFU/mL, με ≤2 είδη μικροοργανισμών","textEn":"Positive urine culture ≥10⁵ CFU/mL, with ≤2 species of organisms"}]}]}'),
  ('vap', 'VAP – Πνευμονία σχετιζόμενη με μηχανικό αερισμό', 'VAP – Ventilator-associated pneumonia', 'CDC/NHSN (simplified)', '{"system":true,"locked":true,"groups":[{"id":"device","rule":"all","items":[{"id":"ventilator48h","textEl":"Μηχανικός αερισμός για >2 ημερολογιακές ημέρες πριν την ημερομηνία έναρξης","textEn":"Mechanical ventilation for >2 calendar days before the date of event"},{"id":"newInfiltrate","textEl":"Νέο, προϊόν ή επίμονο διήθημα στην απεικόνιση θώρακος","textEn":"New, progressive or persistent infiltrate on chest imaging"}]},{"id":"clinical","rule":"atLeastTwo","items":[{"id":"temperatureAbnormal","textEl":"Πυρετός ή υποθερμία","textEn":"Fever or hypothermia"},{"id":"wbcAbnormal","textEl":"Λευκοπενία ή λευκοκυττάρωση","textEn":"Leukopenia or leukocytosis"},{"id":"mentalStatusChange","textEl":"Νέα διαταραχή επιπέδου συνείδησης (ηλικιακά προσαρμοσμένη)","textEn":"New onset of altered mental status (age-adjusted)"},{"id":"purulentSecretions","textEl":"Νέα πυώδης τραχειοβρογχική έκκριση","textEn":"New onset of purulent tracheobronchial secretions"}]},{"id":"micro","rule":"any","items":[{"id":"respiratoryCulturePositive","textEl":"Θετική καλλιέργεια αναπνευστικού δείγματος (τραχειοβρογχικές εκκρίσεις / BAL) πάνω από το ποσοτικό κατώφλι","textEn":"Positive quantitative respiratory culture (tracheal aspirate / BAL) above the diagnostic threshold"}]}]}'),
  ('ssi', 'SSI – Λοίμωξη χειρουργικού πεδίου', 'SSI – Surgical site infection', 'CDC/NHSN (simplified)', '{"system":true,"locked":true,"groups":[{"id":"timing","rule":"all","items":[{"id":"withinWindow","textEl":"Εντός 30 ημερών από την επέμβαση (ή 90 ημερών εφόσον υπάρχει εμφύτευμα)","textEn":"Within 30 days of the procedure (or 90 days if an implant is present)"}]},{"id":"depth","rule":"any","items":[{"id":"superficialPurulent","textEl":"Επιπολής τομή: πυώδης έκκριση ή θετική καλλιέργεια από το δέρμα/υποδόριο","textEn":"Superficial incisional: purulent drainage or organism isolated from skin/subcutaneous tissue"},{"id":"deepPurulentOrDehiscence","textEl":"Εν τω βάθει τομή: πυώδης έκκριση από εν τω βάθει τομή, ή αυτόματη/σκόπιμη διάνοιξη με πυρετό ή εντοπισμένο πόνο","textEn":"Deep incisional: purulent drainage from the deep incision, or spontaneous/deliberate dehiscence with fever or localized pain"},{"id":"organSpaceAbscess","textEl":"Όργανο/κοιλότητα: πυώδης έκκριση από παροχέτευση, θετική καλλιέργεια ή απόστημα σε όργανο/κοιλότητα που χειρουργήθηκε","textEn":"Organ/space: purulent drainage from a drain, organism from culture, or an abscess involving the operated organ/space"}]}]}')
) as v(code, name_el, name_en, source_authority, metadata)
on conflict (organization_id, library_key, name_el) do nothing;

alter table public.master_library_items enable trigger trg_audit_master_library_items;
