-- Phase 4P: antibiogram methodology and interpretation governance.
insert into public.lira_knowledge_sources(organization_id,source_type,title,authority,source_url,source_version,language,status,metadata,ingestion_status)
values
(null,'standard','Antimicrobial susceptibility testing — EUCAST guidance and breakpoint resources','EUCAST','https://www.eucast.org/ast_of_bacteria','current-reviewed-2026','en','review',jsonb_build_object('official',true,'topic','antibiogram-methodology','review_required',true,'phase','4P','version_sensitive',true),'pending'),
(null,'surveillance','GLASS manual for antimicrobial resistance surveillance in common bacteria causing human infection','WHO','https://www.who.int/publications/i/item/9789240076600','2023','en','review',jsonb_build_object('official',true,'topic','amr-surveillance-methodology','review_required',true,'phase','4P'),'pending')
on conflict do nothing;

with x(authority,title,chunk_index,heading,content,citation_label) as (values
('EUCAST','Antimicrobial susceptibility testing — EUCAST guidance and breakpoint resources',0,'AST interpretation requires method and version','Antimicrobial susceptibility interpretation must retain the organism identification, antimicrobial, testing method, measured result where available, interpretation and the applicable EUCAST breakpoint/version. LIRA must not silently reinterpret historical AST using a different breakpoint version.','EUCAST · AST version governance'),
('EUCAST','Antimicrobial susceptibility testing — EUCAST guidance and breakpoint resources',1,'No invented susceptibility','LIRA must not infer susceptibility for an antimicrobial that was not tested or validly derived under the applicable laboratory rules, and must not infer a resistance mechanism solely from an S, I or R pattern.','EUCAST · susceptibility guardrail'),
('EUCAST','Antimicrobial susceptibility testing — EUCAST guidance and breakpoint resources',2,'Local antibiogram provenance','An antibiogram output should expose its analysis period, included organisms, specimen scope, patient/isolate deduplication rule, minimum-count or suppression rule, breakpoint version and data provenance. LIRA should show when these inputs are incomplete rather than produce false precision.','EUCAST context · antibiogram provenance'),
('WHO','GLASS manual for antimicrobial resistance surveillance in common bacteria causing human infection',0,'AMR surveillance population','AMR surveillance estimates depend on the surveillance population, specimen type, organism, antimicrobial, laboratory methods and reporting period. LIRA must preserve these dimensions when presenting or comparing resistance percentages.','WHO GLASS 2023 · AMR surveillance context'),
('WHO','GLASS manual for antimicrobial resistance surveillance in common bacteria causing human infection',1,'Deduplication must be explicit','Repeated isolates from the same patient can bias resistance estimates if handled inconsistently. LIRA must use an explicitly configured deduplication methodology for local antibiogram or surveillance calculations and report that methodology with the result.','WHO GLASS 2023 · deduplication guardrail'),
('WHO','GLASS manual for antimicrobial resistance surveillance in common bacteria causing human infection',2,'External versus local resistance','National or international surveillance data provide epidemiologic context but are not the current susceptibility profile of an individual hospital. LIRA must use authorized local microbiology data for hospital-specific resistance estimates and label external surveillance separately.','WHO GLASS 2023 · local versus external AMR')
)
insert into public.lira_knowledge_chunks(source_id,chunk_index,heading,content,citation_label,token_count,content_hash,metadata,embedding_status)
select s.id,x.chunk_index,x.heading,x.content,x.citation_label,ceil(length(x.content)/4.0)::integer,md5(x.content),jsonb_build_object('curation','official-source-summary','review_required',true,'phase','4P'),'not_required'
from x join public.lira_knowledge_sources s on s.authority=x.authority and s.title=x.title where s.status='review'
on conflict(source_id,chunk_index) do update set heading=excluded.heading,content=excluded.content,citation_label=excluded.citation_label,token_count=excluded.token_count,content_hash=excluded.content_hash,metadata=excluded.metadata,embedding_status=excluded.embedding_status;
update public.lira_knowledge_sources s set ingestion_status='ingested',updated_at=now() where s.status='review' and s.metadata->>'phase'='4P' and exists(select 1 from public.lira_knowledge_chunks c where c.source_id=s.id);
