-- Phase 4O: antimicrobial stewardship governance.
insert into public.lira_knowledge_sources(organization_id,source_type,title,authority,source_url,source_version,language,status,metadata,ingestion_status)
values
(null,'guideline','WHO policy guidance on integrated antimicrobial stewardship activities','WHO','https://www.who.int/publications/i/item/9789240025530','2021','en','review',jsonb_build_object('official',true,'topic','antimicrobial-stewardship','review_required',true,'phase','4O'),'pending'),
(null,'framework','The Core Elements of Hospital Antibiotic Stewardship Programs','CDC','https://www.cdc.gov/antibiotic-use/hcp/core-elements/hospital.html','current-reviewed-2026','en','review',jsonb_build_object('official',true,'topic','hospital-antibiotic-stewardship','review_required',true,'phase','4O'),'pending')
on conflict do nothing;

with x(authority,title,chunk_index,heading,content,citation_label) as (values
('WHO','WHO policy guidance on integrated antimicrobial stewardship activities',0,'Stewardship is a governed program','Antimicrobial stewardship is a coordinated program to improve and measure antimicrobial use and outcomes. LIRA should support governance, measurement, review and feedback, but must not autonomously prescribe, stop or change an individual patient antimicrobial regimen.','WHO 2021 · antimicrobial stewardship'),
('WHO','WHO policy guidance on integrated antimicrobial stewardship activities',1,'Clinical context and microbiology','Stewardship decisions should integrate indication, clinical syndrome, microbiology, susceptibility information, patient factors and applicable local guidance. LIRA must not infer an antimicrobial choice solely from organism identity or a resistance label.','WHO 2021 · stewardship decision guardrail'),
('WHO','WHO policy guidance on integrated antimicrobial stewardship activities',2,'Measurement context','Antimicrobial-use metrics must retain the population, unit, time period, numerator, denominator and data source. LIRA must not compare consumption values across departments or periods when denominators or measurement methods are not comparable.','WHO 2021 · stewardship measurement'),
('CDC','The Core Elements of Hospital Antibiotic Stewardship Programs',0,'Hospital stewardship core elements','Hospital antibiotic stewardship programs require leadership commitment, accountability, pharmacy expertise, action, tracking, reporting and education. LIRA may organize these program elements and identify documented gaps without presenting an automated score as a clinical judgment.','CDC · hospital stewardship core elements'),
('CDC','The Core Elements of Hospital Antibiotic Stewardship Programs',1,'Prospective audit and feedback','Prospective audit and feedback and preauthorization are stewardship interventions that require defined local governance and responsible clinicians. LIRA may surface cases meeting configured review criteria but must not represent the flag as proof that therapy is inappropriate.','CDC · stewardship review guardrail'),
('CDC','The Core Elements of Hospital Antibiotic Stewardship Programs',2,'Antibiogram context','Local susceptibility data and antibiograms can support empiric-policy review when generated with a defined methodology. LIRA must preserve organism, specimen, patient-deduplication, time-period and isolate-count rules and must not substitute external surveillance percentages for the hospital antibiogram.','CDC · antibiogram context guardrail')
)
insert into public.lira_knowledge_chunks(source_id,chunk_index,heading,content,citation_label,token_count,content_hash,metadata,embedding_status)
select s.id,x.chunk_index,x.heading,x.content,x.citation_label,ceil(length(x.content)/4.0)::integer,md5(x.content),jsonb_build_object('curation','official-source-summary','review_required',true,'phase','4O'),'not_required'
from x join public.lira_knowledge_sources s on s.authority=x.authority and s.title=x.title where s.status='review'
on conflict(source_id,chunk_index) do update set heading=excluded.heading,content=excluded.content,citation_label=excluded.citation_label,token_count=excluded.token_count,content_hash=excluded.content_hash,metadata=excluded.metadata,embedding_status=excluded.embedding_status;
update public.lira_knowledge_sources s set ingestion_status='ingested',updated_at=now() where s.status='review' and s.metadata->>'phase'='4O' and exists(select 1 from public.lira_knowledge_chunks c where c.source_id=s.id);
