-- Phase 4M: hand hygiene observation and environmental cleaning governance.
insert into public.lira_knowledge_sources(organization_id,source_type,title,authority,source_url,source_version,language,status,metadata,ingestion_status)
values
(null,'guideline','WHO Guidelines on Hand Hygiene in Health Care','WHO','https://www.who.int/publications/i/item/9789241597906','2009','en','review',jsonb_build_object('official',true,'topic','hand-hygiene','review_required',true,'phase','4M','dated_guidance',true),'pending'),
(null,'manual','Hand Hygiene Technical Reference Manual','WHO','https://www.who.int/publications/m/item/hand-hygiene-technical-reference-manual','2009','en','review',jsonb_build_object('official',true,'topic','hand-hygiene-observation','review_required',true,'phase','4M','dated_guidance',true),'pending'),
(null,'guideline','Best Practices for Environmental Cleaning in Healthcare Facilities','CDC','https://www.cdc.gov/healthcare-associated-infections/hcp/cleaning-global/index.html','current-reviewed-2026','en','review',jsonb_build_object('official',true,'topic','environmental-cleaning','review_required',true,'phase','4M'),'pending')
on conflict do nothing;

with x(authority,title,chunk_index,heading,content,citation_label) as (values
('WHO','WHO Guidelines on Hand Hygiene in Health Care',0,'WHO Five Moments','Hand-hygiene opportunities should be interpreted using the WHO Five Moments framework and the clinical care sequence. LIRA must not treat the number of observed staff members as the denominator for compliance when the observation method uses hand-hygiene opportunities.','WHO 2009 · Five Moments'),
('WHO','WHO Guidelines on Hand Hygiene in Health Care',1,'Hand hygiene compliance denominator','Observed hand-hygiene compliance is based on performed hand-hygiene actions relative to observed opportunities under the defined observation method. LIRA must preserve numerator, denominator, observation period, unit and professional category when comparing compliance.','WHO 2009 · hand hygiene compliance'),
('WHO','Hand Hygiene Technical Reference Manual',0,'Observation integrity','Direct observation data are samples of observed care and can be affected by observer, selection and Hawthorne effects. LIRA should describe the observed sample and period and must not present a limited observation session as the exact behavior of all staff or all shifts.','WHO · hand hygiene observation guardrail'),
('WHO','Hand Hygiene Technical Reference Manual',1,'Glove use and hand hygiene','Glove use does not replace hand hygiene. LIRA should treat glove-use observations and hand-hygiene indications as related but distinct audit elements and must not count glove use alone as a performed hand-hygiene action.','WHO · gloves and hand hygiene'),
('CDC','Best Practices for Environmental Cleaning in Healthcare Facilities',0,'Environmental cleaning program','Environmental cleaning is a structured IPC program involving defined responsibilities, appropriate products and procedures, staff training, monitoring and feedback. LIRA should distinguish a documented cleaning process from evidence that cleaning effectiveness was verified.','CDC · environmental cleaning program'),
('CDC','Best Practices for Environmental Cleaning in Healthcare Facilities',1,'Cleaning monitoring','Environmental cleaning monitoring may use more than one method depending on the setting and objective. LIRA must identify the monitoring method and sampling context and must not equate a single environmental result with overall cleaning performance or a transmission event.','CDC · environmental cleaning monitoring')
)
insert into public.lira_knowledge_chunks(source_id,chunk_index,heading,content,citation_label,token_count,content_hash,metadata,embedding_status)
select s.id,x.chunk_index,x.heading,x.content,x.citation_label,ceil(length(x.content)/4.0)::integer,md5(x.content),jsonb_build_object('curation','official-source-summary','review_required',true,'phase','4M'),'not_required'
from x join public.lira_knowledge_sources s on s.authority=x.authority and s.title=x.title where s.status='review'
on conflict(source_id,chunk_index) do update set heading=excluded.heading,content=excluded.content,citation_label=excluded.citation_label,token_count=excluded.token_count,content_hash=excluded.content_hash,metadata=excluded.metadata,embedding_status=excluded.embedding_status;
update public.lira_knowledge_sources s set ingestion_status='ingested',updated_at=now() where s.status='review' and s.metadata->>'phase'='4M' and exists(select 1 from public.lira_knowledge_chunks c where c.source_id=s.id);
