-- Curated starter knowledge summaries from official authorities. Sources remain in REVIEW until a Platform Owner approves them.
with seed(authority,title,heading,content,citation_label) as (
 values
 ('CDC/NHSN','2026 NHSN Patient Safety Component Manual','NHSN surveillance framework','Use the current NHSN Patient Safety Component definitions and reporting rules when interpreting device-associated and other healthcare-associated infection surveillance. Device-associated rates require the relevant device-day denominator; definitions, location attribution and event criteria must follow the applicable current NHSN chapter rather than being inferred from a positive culture alone.','CDC/NHSN 2026 Patient Safety Component Manual'),
 ('ECDC','HAI-Net ICU protocol','European ICU HAI surveillance','The ECDC HAI-Net ICU protocol version 2.3 standardises definitions, data collection and reporting for healthcare-associated infection surveillance in intensive care units across Europe. LIRA should distinguish surveillance signals from confirmed events and use the protocol-compatible denominator and ICU context when interpreting trends.','ECDC HAI-Net ICU protocol v2.3'),
 ('EUCAST','Clinical breakpoint tables','Antimicrobial susceptibility interpretation','Interpret antimicrobial susceptibility categories using the currently valid EUCAST breakpoint tables and their notes. EUCAST categories are Susceptible, Susceptible increased exposure, and Resistant. Breakpoints are versioned and organism-agent specific; LIRA must not infer susceptibility when the relevant breakpoint or required test information is absent.','EUCAST Clinical Breakpoints v16.1'),
 ('WHO','Minimum requirements for infection prevention and control programmes','IPC programme minimum requirements','WHO minimum requirements describe the IPC standards that should be present at national and healthcare-facility level to provide minimum protection and safety for patients, health workers and visitors, within the WHO core-components framework. LIRA should use these requirements as programme-level guidance, not as patient-specific diagnostic criteria.','WHO Minimum requirements for IPC programmes'),
 ('WHO','WHO hand hygiene in health care resources','WHO Five Moments for Hand Hygiene','WHO identifies five key moments for hand hygiene in patient care: before touching a patient; before a clean or aseptic procedure; after body-fluid exposure risk; after touching a patient; and after touching patient surroundings. Hand-hygiene compliance interpretation should preserve the observed opportunity/action context and should not treat glove use as a substitute for indicated hand hygiene.','WHO Five Moments for Hand Hygiene')
)
insert into public.lira_knowledge_chunks(source_id,chunk_index,heading,content,citation_label,token_count,content_hash,metadata,embedding_status)
select s.id,0,x.heading,x.content,x.citation_label,ceil(length(x.content)/4.0)::integer,md5(x.content),jsonb_build_object('curation','official-source-summary','review_required',true),'not_required'
from seed x join public.lira_knowledge_sources s on s.authority=x.authority and s.title=x.title
where s.status='review'
on conflict(source_id,chunk_index) do update set heading=excluded.heading,content=excluded.content,citation_label=excluded.citation_label,token_count=excluded.token_count,content_hash=excluded.content_hash,metadata=excluded.metadata,embedding_status=excluded.embedding_status;

update public.lira_knowledge_sources s set ingestion_status='ingested',updated_at=now()
where status='review' and exists(select 1 from public.lira_knowledge_chunks c where c.source_id=s.id and c.metadata->>'curation'='official-source-summary');
