-- Phase 4I: MRSA/VRE screening, colonization and decolonization governance.
insert into public.lira_knowledge_sources(organization_id,source_type,title,authority,source_url,source_version,language,status,metadata,ingestion_status)
values
(null,'guidance','Strategies to Prevent Hospital-onset Staphylococcus aureus Bloodstream Infections in Acute Care Facilities','CDC','https://www.cdc.gov/staphylococcus-aureus/hcp/infection-control/index.html','2025-06','en','review',jsonb_build_object('official',true,'topic','mrsa-screening-decolonization','review_required',true,'phase','4I'),'pending'),
(null,'guidance','Recommendations for Preventing the Spread of Vancomycin Resistance','CDC','https://www.cdc.gov/infection-control/hcp/mdro-management/summary-recommendations.html','current-reviewed-2026','en','review',jsonb_build_object('official',true,'topic','vre-mdro-control','review_required',true,'phase','4I'),'pending')
on conflict do nothing;

with x(authority,title,chunk_index,heading,content,citation_label) as (values
('CDC','Strategies to Prevent Hospital-onset Staphylococcus aureus Bloodstream Infections in Acute Care Facilities',0,'MRSA screening is strategy-dependent','MRSA screening should be interpreted as part of a defined infection-prevention strategy and target population. LIRA must not recommend universal screening merely because MRSA is detected elsewhere in the facility; local policy, unit risk, epidemiology and the applicable guidance must be considered.','CDC · S. aureus acute-care prevention'),
('CDC','Strategies to Prevent Hospital-onset Staphylococcus aureus Bloodstream Infections in Acute Care Facilities',1,'MRSA colonization versus infection','A positive MRSA colonization screen identifies carriage and is not, by itself, a diagnosis of active infection. LIRA must keep screening/colonization results distinct from diagnostic cultures and clinical infection.','CDC · MRSA colonization guardrail'),
('CDC','Strategies to Prevent Hospital-onset Staphylococcus aureus Bloodstream Infections in Acute Care Facilities',2,'MRSA decolonization governance','Decolonization can be used in defined populations or prevention strategies. LIRA must not autonomously prescribe a decolonization regimen; it should identify the applicable protocol, indication, contraindications and required clinical oversight.','CDC · MRSA decolonization guardrail'),
('CDC','Recommendations for Preventing the Spread of Vancomycin Resistance',0,'VRE control strategy','VRE prevention and control relies on coordinated MDRO practices including hand hygiene, appropriate precautions, environmental cleaning, communication and surveillance according to the healthcare setting and local epidemiology.','CDC · VRE MDRO control'),
('CDC','Recommendations for Preventing the Spread of Vancomycin Resistance',1,'VRE screening and colonization','VRE colonization is distinct from infection. Screening or active surveillance should be driven by the facility prevention strategy, epidemiology or outbreak investigation rather than interpreted as a treatment indication.','CDC · VRE screening guardrail'),
('CDC','Recommendations for Preventing the Spread of Vancomycin Resistance',2,'Transfer communication','When a patient known to be colonized or infected with a multidrug-resistant organism is transferred, relevant MDRO status and required precautions should be communicated to the receiving care team according to policy and applicable privacy requirements.','CDC · MDRO transfer communication')
)
insert into public.lira_knowledge_chunks(source_id,chunk_index,heading,content,citation_label,token_count,content_hash,metadata,embedding_status)
select s.id,x.chunk_index,x.heading,x.content,x.citation_label,ceil(length(x.content)/4.0)::integer,md5(x.content),jsonb_build_object('curation','official-source-summary','review_required',true,'phase','4I'),'not_required'
from x join public.lira_knowledge_sources s on s.authority=x.authority and s.title=x.title where s.status='review'
on conflict(source_id,chunk_index) do update set heading=excluded.heading,content=excluded.content,citation_label=excluded.citation_label,token_count=excluded.token_count,content_hash=excluded.content_hash,metadata=excluded.metadata,embedding_status=excluded.embedding_status;
update public.lira_knowledge_sources s set ingestion_status='ingested',updated_at=now() where s.status='review' and s.metadata->>'phase'='4I' and exists(select 1 from public.lira_knowledge_chunks c where c.source_id=s.id);
