-- Governed population catalogue: pediatric and neonatal severity/risk instruments.
-- Catalogue metadata only. Calculation remains disabled until formula, licensing and implementation review are complete.
insert into public.clinical_scale_definitions
(scale_key,version,name_el,name_en,category,population,min_age_years,max_age_years,settings,definition,source_authority,source_reference,status)
values
('pim3','PIM3-2013','PIM3 — Δείκτης Παιδιατρικής Θνητότητας','PIM3 — Paediatric Index of Mortality 3','severity',array['pediatric'],0,17.999,array['picu'],jsonb_build_object('engine','governed','scoringStatus','implementation_review_required','purpose','PICU mortality risk adjustment','measurementWindow','first hour of PICU admission'),'ANZICS / ANZPIC Registry; PICANet','Straney L et al. Paediatric Index of Mortality 3. Pediatr Crit Care Med. 2013.','draft'),
('pelod-2','PELOD-2','PELOD-2 — Παιδιατρική Οργανική Δυσλειτουργία','PELOD-2 — Pediatric Logistic Organ Dysfunction 2','organ_dysfunction',array['pediatric'],0,17.999,array['picu'],jsonb_build_object('engine','governed','scoringStatus','implementation_review_required','purpose','PICU organ dysfunction severity'),'Leteurtre et al.','PELOD-2 published validation; Lancet Respir Med. 2013.','draft'),
('crib-ii','CRIB-II-2003','CRIB II — Κλινικός Δείκτης Κινδύνου Νεογνών','CRIB II — Clinical Risk Index for Babies II','severity',array['neonatal'],0,0.083,array['nicu'],jsonb_build_object('engine','governed','scoringStatus','implementation_review_required','purpose','Early mortality risk stratification in preterm/low-birth-weight neonates'),'UK Neonatal Staffing Study Collaborative Group','Parry G, Tucker J, Tarnow-Mordi W. Lancet. 2003;361:1789–1791.','draft'),
('snappe-ii','SNAPPE-II-2001','SNAPPE-II — Νεογνική Βαρύτητα Νόσου','SNAPPE-II — Score for Neonatal Acute Physiology with Perinatal Extension II','severity',array['neonatal'],0,0.083,array['nicu'],jsonb_build_object('engine','governed','scoringStatus','implementation_review_required','purpose','Neonatal illness severity and mortality risk'),'Richardson et al.','J Pediatr. 2001;138:92–100.','draft')
on conflict(scale_key,version) do nothing;
