-- Phase 4J: device-associated infection prevention knowledge.
insert into public.lira_knowledge_sources(organization_id,source_type,title,authority,source_url,source_version,language,status,metadata,ingestion_status)
values
(null,'guideline','Guidelines for the Prevention of Intravascular Catheter-Related Infections','CDC','https://www.cdc.gov/infection-control/hcp/intravascular-catheter-related-infection/index.html','current-reviewed-2026','en','review',jsonb_build_object('official',true,'topic','clabsi-prevention','review_required',true,'phase','4J'),'pending'),
(null,'guideline','Summary of Recommendations: CAUTI','CDC','https://www.cdc.gov/infection-control/hcp/cauti/summary-of-recommendations.html','current-reviewed-2026','en','review',jsonb_build_object('official',true,'topic','cauti-prevention','review_required',true,'phase','4J'),'pending'),
(null,'guideline','Strategies to prevent ventilator-associated pneumonia, ventilator-associated events, and nonventilator hospital-acquired pneumonia','SHEA/IDSA/APIC','https://www.cambridge.org/core/journals/infection-control-and-hospital-epidemiology/article/strategies-to-prevent-ventilatorassociated-pneumonia-ventilatorassociated-events-and-nonventilator-hospitalacquired-pneumonia-in-acute-care-hospitals-2022-update/','2022 update','en','review',jsonb_build_object('official',false,'expert_guidance',true,'topic','vap-vae-prevention','review_required',true,'phase','4J'),'pending')
on conflict do nothing;

with x(authority,title,chunk_index,heading,content,citation_label) as (values
('CDC','Guidelines for the Prevention of Intravascular Catheter-Related Infections',0,'Central-line prevention principles','Central-line infection prevention requires a bundle of evidence-based insertion and maintenance practices, including hand hygiene, aseptic technique, appropriate skin antisepsis and ongoing assessment of line necessity. LIRA should evaluate bundle adherence as separate measurable components rather than infer compliance from a single action.','CDC · intravascular catheter infection prevention'),
('CDC','Guidelines for the Prevention of Intravascular Catheter-Related Infections',1,'Line necessity and removal','The clinical need for an intravascular catheter should be reviewed and catheters that are no longer essential should be removed promptly. LIRA may flag overdue necessity review from recorded workflow data but must not autonomously order device removal.','CDC · catheter necessity guardrail'),
('CDC','Summary of Recommendations: CAUTI',0,'Urinary catheter indication','Indwelling urinary catheters should be used only for appropriate indications and left in place only as long as needed. LIRA should distinguish documented indication, insertion practice, maintenance and timely removal as separate prevention elements.','CDC · CAUTI appropriate use'),
('CDC','Summary of Recommendations: CAUTI',1,'CAUTI maintenance','Aseptic insertion by trained personnel and maintenance of a closed drainage system are core CAUTI prevention practices. Breaks in technique or disconnection should be treated as prevention findings, not automatically as evidence that a CAUTI occurred.','CDC · CAUTI maintenance guardrail'),
('SHEA/IDSA/APIC','Strategies to prevent ventilator-associated pneumonia, ventilator-associated events, and nonventilator hospital-acquired pneumonia',0,'Ventilator pneumonia prevention','Prevention of ventilator-associated pneumonia and ventilator-associated events is multimodal. LIRA should use documented preventive practices and device exposure data to support quality surveillance and should not diagnose VAP from a missing bundle element.','SHEA/IDSA/APIC 2022 · VAP/VAE prevention'),
('SHEA/IDSA/APIC','Strategies to prevent ventilator-associated pneumonia, ventilator-associated events, and nonventilator hospital-acquired pneumonia',1,'Device-day denominator guardrail','Rates for device-associated infections require the appropriate device-day denominator for the same population and surveillance period. Patient-days are not a substitute for central-line days, urinary-catheter days or ventilator days when calculating device-associated rates.','Device-associated denominator guardrail')
)
insert into public.lira_knowledge_chunks(source_id,chunk_index,heading,content,citation_label,token_count,content_hash,metadata,embedding_status)
select s.id,x.chunk_index,x.heading,x.content,x.citation_label,ceil(length(x.content)/4.0)::integer,md5(x.content),jsonb_build_object('curation','official-source-summary','review_required',true,'phase','4J'),'not_required'
from x join public.lira_knowledge_sources s on s.authority=x.authority and s.title=x.title where s.status='review'
on conflict(source_id,chunk_index) do update set heading=excluded.heading,content=excluded.content,citation_label=excluded.citation_label,token_count=excluded.token_count,content_hash=excluded.content_hash,metadata=excluded.metadata,embedding_status=excluded.embedding_status;
update public.lira_knowledge_sources s set ingestion_status='ingested',updated_at=now() where s.status='review' and s.metadata->>'phase'='4J' and exists(select 1 from public.lira_knowledge_chunks c where c.source_id=s.id);
