-- Phase 4Q: AMR phenotype/mechanism and MDR/XDR governance.
insert into public.lira_knowledge_sources(organization_id,source_type,title,authority,source_url,source_version,language,status,metadata,ingestion_status)
values
(null,'expert-definition','Interim standard definitions for acquired resistance — MDR, XDR and PDR','ECDC/CDC expert proposal','https://pubmed.ncbi.nlm.nih.gov/21793988/','2012 publication','en','review',jsonb_build_object('official',false,'expert_proposal',true,'topic','mdr-xdr-pdr-definitions','review_required',true,'phase','4Q','dated_guidance',true),'pending'),
(null,'guidance','EUCAST guidance documents in susceptibility testing','EUCAST','https://www.eucast.org/ast_of_bacteria/guidance_documents','current-reviewed-2026','en','review',jsonb_build_object('official',true,'topic','amr-phenotype-interpretation','review_required',true,'phase','4Q','version_sensitive',true),'pending')
on conflict do nothing;

with x(authority,title,chunk_index,heading,content,citation_label) as (values
('ECDC/CDC expert proposal','Interim standard definitions for acquired resistance — MDR, XDR and PDR',0,'MDR/XDR/PDR definitions are dated expert definitions','The widely cited MDR, XDR and PDR definitions originate from an international expert proposal published in 2012. LIRA must identify the adopted definition and version when classifying isolates and must not present this historical proposal as a universally current legal or clinical standard.','ECDC/CDC expert proposal · 2012'),
('ECDC/CDC expert proposal','Interim standard definitions for acquired resistance — MDR, XDR and PDR',1,'Classification requires adequate testing','MDR/XDR/PDR classification depends on antimicrobial categories and sufficiently complete susceptibility testing under the adopted definition. LIRA must not assign XDR or PDR when the tested panel is insufficient to establish the required category-level resistance or susceptibility.','MDR/XDR/PDR completeness guardrail'),
('EUCAST','EUCAST guidance documents in susceptibility testing',0,'Phenotype is not mechanism','A susceptibility phenotype does not by itself prove a specific molecular resistance mechanism. LIRA must not infer ESBL, AmpC, carbapenemase type or other mechanism solely from a resistance pattern unless the applicable validated laboratory rule or confirmatory result supports that inference.','EUCAST · phenotype/mechanism guardrail'),
('EUCAST','EUCAST guidance documents in susceptibility testing',1,'Carbapenem resistance versus carbapenemase','Carbapenem non-susceptibility and carbapenemase production are related but not interchangeable concepts. LIRA should preserve the laboratory evidence used for a carbapenemase designation and distinguish phenotypic suspicion from confirmed mechanism.','EUCAST · carbapenemase interpretation'),
('EUCAST','EUCAST guidance documents in susceptibility testing',2,'Intrinsic and acquired resistance','Interpretation should account for organism-specific expected or intrinsic resistance and applicable expert rules. LIRA must not count intrinsic resistance as acquired resistance for an MDR/XDR classification when the adopted definition excludes it.','EUCAST · intrinsic resistance guardrail'),
('EUCAST','EUCAST guidance documents in susceptibility testing',3,'Genotype and phenotype provenance','When molecular resistance markers are available, LIRA should display the actual detected marker, method and result separately from phenotypic AST. It must not convert an absent or unperformed molecular test into a negative mechanism finding.','EUCAST context · genotype/phenotype provenance')
)
insert into public.lira_knowledge_chunks(source_id,chunk_index,heading,content,citation_label,token_count,content_hash,metadata,embedding_status)
select s.id,x.chunk_index,x.heading,x.content,x.citation_label,ceil(length(x.content)/4.0)::integer,md5(x.content),jsonb_build_object('curation','official-or-expert-source-summary','review_required',true,'phase','4Q'),'not_required'
from x join public.lira_knowledge_sources s on s.authority=x.authority and s.title=x.title where s.status='review'
on conflict(source_id,chunk_index) do update set heading=excluded.heading,content=excluded.content,citation_label=excluded.citation_label,token_count=excluded.token_count,content_hash=excluded.content_hash,metadata=excluded.metadata,embedding_status=excluded.embedding_status;
update public.lira_knowledge_sources s set ingestion_status='ingested',updated_at=now() where s.status='review' and s.metadata->>'phase'='4Q' and exists(select 1 from public.lira_knowledge_chunks c where c.source_id=s.id);
