-- Phase 4K: surgical-site infection prevention and surveillance knowledge.
insert into public.lira_knowledge_sources(organization_id,source_type,title,authority,source_url,source_version,language,status,metadata,ingestion_status)
values
(null,'guideline','Global guidelines for the prevention of surgical site infection','WHO','https://www.who.int/publications/i/item/9789241550475','2nd ed. 2018','en','review',jsonb_build_object('official',true,'topic','ssi-prevention','review_required',true,'phase','4K'),'pending'),
(null,'guideline','Guideline for the Prevention of Surgical Site Infection','CDC','https://www.cdc.gov/infection-control/hcp/surgical-site-infection/index.html','2017/current page','en','review',jsonb_build_object('official',true,'topic','ssi-prevention-cdc','review_required',true,'phase','4K','dated_guidance',true),'pending'),
(null,'surveillance','NHSN Patient Safety Component Manual — Surgical Site Infection Event','CDC/NHSN','https://www.cdc.gov/nhsn/pdfs/pscmanual/9pscssicurrent.pdf','2026','en','review',jsonb_build_object('official',true,'topic','ssi-surveillance','review_required',true,'phase','4K','version_sensitive',true),'pending')
on conflict do nothing;

with x(authority,title,chunk_index,heading,content,citation_label) as (values
('WHO','Global guidelines for the prevention of surgical site infection',0,'SSI prevention is perioperative and multimodal','Surgical-site infection prevention spans preoperative, intraoperative and postoperative practices. LIRA should evaluate recorded prevention elements individually and as a bundle, and must not infer that an SSI occurred solely because a prevention element was missed.','WHO 2018 · SSI prevention'),
('WHO','Global guidelines for the prevention of surgical site infection',1,'Antimicrobial prophylaxis governance','Surgical antimicrobial prophylaxis should follow the applicable procedure-specific protocol, timing and stewardship rules. LIRA may identify documented timing or protocol deviations but must not autonomously select an antimicrobial, dose or duration for an individual patient.','WHO 2018 · surgical prophylaxis guardrail'),
('CDC','Guideline for the Prevention of Surgical Site Infection',0,'SSI prevention context','CDC SSI prevention guidance supports evidence-based perioperative infection-prevention practices. LIRA should distinguish prevention-process compliance from surveillance case determination and from clinical diagnosis.','CDC 2017 · SSI prevention'),
('CDC/NHSN','NHSN Patient Safety Component Manual — Surgical Site Infection Event',0,'SSI surveillance definition is versioned','SSI surveillance classification must use the applicable NHSN definition, operative procedure category, surveillance period and required criteria for the event date. LIRA must preserve the surveillance-definition version used and must not silently reclassify historical events under a newer version.','CDC/NHSN 2026 · SSI surveillance'),
('CDC/NHSN','NHSN Patient Safety Component Manual — Surgical Site Infection Event',1,'SSI surveillance versus clinical diagnosis','A clinical diagnosis, positive culture, wound finding or antibiotic treatment alone does not automatically establish an NHSN SSI unless the applicable surveillance criteria are satisfied. Conversely, surveillance classification is not a substitute for bedside clinical diagnosis or treatment decisions.','CDC/NHSN 2026 · SSI classification guardrail'),
('CDC/NHSN','NHSN Patient Safety Component Manual — Surgical Site Infection Event',2,'SSI denominator integrity','SSI rates and standardized measures require the appropriate eligible operative-procedure denominator and risk-adjustment inputs where applicable. Patient-days or total admissions are not interchangeable with the procedure denominator.','CDC/NHSN 2026 · SSI denominator guardrail')
)
insert into public.lira_knowledge_chunks(source_id,chunk_index,heading,content,citation_label,token_count,content_hash,metadata,embedding_status)
select s.id,x.chunk_index,x.heading,x.content,x.citation_label,ceil(length(x.content)/4.0)::integer,md5(x.content),jsonb_build_object('curation','official-source-summary','review_required',true,'phase','4K'),'not_required'
from x join public.lira_knowledge_sources s on s.authority=x.authority and s.title=x.title where s.status='review'
on conflict(source_id,chunk_index) do update set heading=excluded.heading,content=excluded.content,citation_label=excluded.citation_label,token_count=excluded.token_count,content_hash=excluded.content_hash,metadata=excluded.metadata,embedding_status=excluded.embedding_status;
update public.lira_knowledge_sources s set ingestion_status='ingested',updated_at=now() where s.status='review' and s.metadata->>'phase'='4K' and exists(select 1 from public.lira_knowledge_chunks c where c.source_id=s.id);
