-- Phase 4N: outbreak investigation and cluster-signal governance.
insert into public.lira_knowledge_sources(organization_id,source_type,title,authority,source_url,source_version,language,status,metadata,ingestion_status)
values
(null,'toolkit','Disease Outbreak Toolboxes — Healthcare-associated infections','WHO','https://www.who.int/emergencies/outbreak-toolkit','current-reviewed-2026','en','review',jsonb_build_object('official',true,'topic','outbreak-investigation','review_required',true,'phase','4N'),'pending'),
(null,'guidance','Steps of an Investigation','CDC','https://www.cdc.gov/field-epi-manual/php/chapters/investigating-acute-enteric-disease-outbreaks.html','current-reviewed-2026','en','review',jsonb_build_object('official',true,'topic','outbreak-epidemiology','review_required',true,'phase','4N'),'pending')
on conflict do nothing;

with x(authority,title,chunk_index,heading,content,citation_label) as (values
('WHO','Disease Outbreak Toolboxes — Healthcare-associated infections',0,'Cluster signal versus outbreak declaration','An unusual concentration of healthcare-associated events can be a signal requiring verification and investigation. LIRA may surface a cluster signal from authorized data, but must not autonomously declare an outbreak or transmission chain. Confirmation requires epidemiologic assessment under the facility response process.','WHO · outbreak investigation guardrail'),
('WHO','Disease Outbreak Toolboxes — Healthcare-associated infections',1,'Initial investigation','Outbreak response should establish the event definition, verify data and diagnoses, characterize cases by person place and time, identify relevant exposures and implement proportionate control measures while the investigation proceeds. LIRA should clearly distinguish observed facts, missing data, hypotheses and confirmed findings.','WHO · outbreak investigation'),
('WHO','Disease Outbreak Toolboxes — Healthcare-associated infections',2,'Line-list integrity','A line list should use a consistent case definition and relevant dates, locations, exposures and microbiology fields. LIRA must not fill missing epidemiologic links or exposure dates by inference and should label incomplete records.','WHO · line-list integrity'),
('CDC','Steps of an Investigation',0,'Descriptive epidemiology','Descriptive epidemiology by person, place and time supports hypothesis generation and assessment of whether observed events are unusual. Temporal or spatial proximity alone does not prove a common source or person-to-person transmission.','CDC · descriptive epidemiology'),
('CDC','Steps of an Investigation',1,'Hypotheses and evidence','Investigation hypotheses should be tested against epidemiologic, laboratory and environmental evidence. LIRA must label hypotheses as hypotheses and must not present an association, shared resistance phenotype or shared ward exposure as proof of transmission.','CDC · outbreak evidence guardrail'),
('CDC','Steps of an Investigation',2,'Control actions and uncertainty','Immediate IPC actions may be warranted before every uncertainty is resolved, depending on the hazard and setting. LIRA may organize recommended response steps from approved guidance but should show the evidence basis, uncertainty and responsible human decision point.','CDC · outbreak response governance')
)
insert into public.lira_knowledge_chunks(source_id,chunk_index,heading,content,citation_label,token_count,content_hash,metadata,embedding_status)
select s.id,x.chunk_index,x.heading,x.content,x.citation_label,ceil(length(x.content)/4.0)::integer,md5(x.content),jsonb_build_object('curation','official-source-summary','review_required',true,'phase','4N'),'not_required'
from x join public.lira_knowledge_sources s on s.authority=x.authority and s.title=x.title where s.status='review'
on conflict(source_id,chunk_index) do update set heading=excluded.heading,content=excluded.content,citation_label=excluded.citation_label,token_count=excluded.token_count,content_hash=excluded.content_hash,metadata=excluded.metadata,embedding_status=excluded.embedding_status;
update public.lira_knowledge_sources s set ingestion_status='ingested',updated_at=now() where s.status='review' and s.metadata->>'phase'='4N' and exists(select 1 from public.lira_knowledge_chunks c where c.source_id=s.id);
