-- Phase 4F: Greece-aware MDRO and carbapenem-resistant organism knowledge.
insert into public.lira_knowledge_sources(organization_id,source_type,title,authority,source_url,source_version,language,status,metadata,ingestion_status)
values
(null,'guideline','Οδηγίες για τη διάγνωση, την πρόληψη και τον έλεγχο της διασποράς στελεχών Candida auris στο νοσοκομειακό περιβάλλον','ΕΟΔΥ','https://eody.gov.gr/wp-content/uploads/2024/03/Candida-auris-2023.pdf','2023','el','review',jsonb_build_object('official',true,'topic','candida-auris-greece','jurisdiction','Greece','review_required',true,'phase','4F'),'pending'),
(null,'guideline','Guidelines for prevention and control of CRE, CRAB and CRPsA in health care facilities','WHO','https://www.who.int/publications/i/item/9789241550178','2017','en','review',jsonb_build_object('official',true,'topic','carbapenem-resistant-organisms','review_required',true,'phase','4F','dated_guidance',true),'pending'),
(null,'manual','Implementation manual to prevent and control the spread of carbapenem-resistant organisms','WHO','https://www.who.int/publications/i/item/WHO-UHC-SDS-2019-6','2019','en','review',jsonb_build_object('official',true,'topic','cro-implementation','review_required',true,'phase','4F'),'pending'),
(null,'guidance','Vancomycin-resistant Enterococci (VRE) Basics','CDC','https://www.cdc.gov/vre/about/index.html','2024-01','en','review',jsonb_build_object('official',true,'topic','vre','review_required',true,'phase','4F'),'pending')
on conflict do nothing;

with x(authority,title,chunk_index,heading,content,citation_label) as (values
('ΕΟΔΥ','Οδηγίες για τη διάγνωση, την πρόληψη και τον έλεγχο της διασποράς στελεχών Candida auris στο νοσοκομειακό περιβάλλον',0,'C. auris — ελληνικό πλαίσιο','Στο ελληνικό νοσοκομειακό πλαίσιο, η έγκαιρη αναγνώριση λοίμωξης ή αποικισμού από Candida auris πρέπει να ενεργοποιεί οργανωμένα μέτρα πρόληψης διασποράς, ενημέρωση των εμπλεκόμενων επαγγελματιών και εφαρμογή των ισχυουσών οδηγιών του ΕΟΔΥ. Η LIRA πρέπει να προτιμά την ελληνική οδηγία όταν η ερώτηση αφορά εφαρμογή σε ελληνική μονάδα υγείας.','ΕΟΔΥ 2023 · Candida auris'),
('ΕΟΔΥ','Οδηγίες για τη διάγνωση, την πρόληψη και τον έλεγχο της διασποράς στελεχών Candida auris στο νοσοκομειακό περιβάλλον',1,'C. auris — μεταφορά ασθενούς','Σε μεταφορά ή μετακίνηση ασθενούς με λοίμωξη ή φορεία Candida auris, απαιτείται έγκαιρη ενημέρωση των επαγγελματιών που πραγματοποιούν τη μεταφορά και της μονάδας που θα υποδεχθεί τον ασθενή, ώστε να εφαρμοστούν τα απαραίτητα μέτρα πρόληψης.','ΕΟΔΥ 2023 · ενημέρωση κατά τη μεταφορά'),
('ΕΟΔΥ','Οδηγίες για τη διάγνωση, την πρόληψη και τον έλεγχο της διασποράς στελεχών Candida auris στο νοσοκομειακό περιβάλλον',2,'C. auris — περιβάλλον','Η περιβαλλοντική απολύμανση για Candida auris πρέπει να ακολουθεί τις ειδικές οδηγίες και τον χρόνο επαφής του κατάλληλου προϊόντος. Ενώσεις τεταρτοταγούς αμμωνίου μπορεί να μην είναι αποτελεσματικές και δεν πρέπει να θεωρούνται επαρκής επιλογή μόνο λόγω γενικής νοσοκομειακής χρήσης.','ΕΟΔΥ 2023 · περιβαλλοντική απολύμανση C. auris'),
('WHO','Guidelines for prevention and control of CRE, CRAB and CRPsA in health care facilities',0,'CRE / CRAB / CRPsA IPC','Οι κατευθυντήριες οδηγίες του WHO καλύπτουν την πρόληψη και τον έλεγχο των carbapenem-resistant Enterobacteriaceae, Acinetobacter baumannii και Pseudomonas aeruginosa σε μονάδες υγείας. Η LIRA πρέπει να αντιμετωπίζει το έγγραφο ως ειδική, χρονολογημένη οδηγία του 2017 και όχι ως αυτόματα επικαιροποιημένο breakpoint ή θεραπευτικό πρότυπο.','WHO 2017 · CRE/CRAB/CRPsA IPC'),
('WHO','Guidelines for prevention and control of CRE, CRAB and CRPsA in health care facilities',1,'Multimodal CRO control','Η πρόληψη διασποράς carbapenem-resistant οργανισμών απαιτεί συνδυασμό μέτρων IPC και όχι ένα μεμονωμένο μέτρο. Η ερμηνεία πρέπει να συνδυάζει επιτήρηση, προφυλάξεις, υγιεινή χεριών, περιβαλλοντικό έλεγχο και τοπική επιδημιολογία σύμφωνα με το εφαρμοζόμενο πρωτόκολλο.','WHO 2017 · multimodal CRO control'),
('WHO','Implementation manual to prevent and control the spread of carbapenem-resistant organisms',0,'CRO implementation','Το WHO implementation manual μετατρέπει τις συστάσεις για carbapenem-resistant οργανισμούς σε σταδιακή προσέγγιση εφαρμογής σε εθνικό επίπεδο και επίπεδο μονάδας υγείας. Η LIRA μπορεί να το χρησιμοποιεί για οργανωτικές προτάσεις IPC, όχι για αυτόνομες κλινικές αποφάσεις ή επιλογή θεραπείας.','WHO 2019 · CRO implementation'),
('CDC','Vancomycin-resistant Enterococci (VRE) Basics',0,'VRE transmission and colonization','VRE μεταδίδεται σε χώρους υγείας κυρίως μέσω επαφής με μολυσμένα χέρια, επιφάνειες ή εξοπλισμό και όχι μέσω του αέρα. Αποικισμός και ενεργός λοίμωξη είναι διαφορετικές καταστάσεις· ο αποικισμός από μόνος του δεν αποτελεί ένδειξη αντιβιοτικής θεραπείας.','CDC 2024 · VRE transmission and colonization'),
('CDC','Vancomycin-resistant Enterococci (VRE) Basics',1,'VRE IPC guardrail','Η ανίχνευση VRE πρέπει να οδηγεί σε ερμηνεία με βάση το κλινικό πλαίσιο και τις εφαρμοζόμενες πρακτικές IPC. Η LIRA δεν πρέπει να μετατρέπει αποτέλεσμα αποικισμού σε διάγνωση λοίμωξης ούτε να προτείνει αντιμικροβιακή θεραπεία χωρίς κλινική αξιολόγηση.','CDC 2024 · VRE guardrail')
)
insert into public.lira_knowledge_chunks(source_id,chunk_index,heading,content,citation_label,token_count,content_hash,metadata,embedding_status)
select s.id,x.chunk_index,x.heading,x.content,x.citation_label,ceil(length(x.content)/4.0)::integer,md5(x.content),jsonb_build_object('curation','official-source-summary','review_required',true,'phase','4F'),'not_required'
from x join public.lira_knowledge_sources s on s.authority=x.authority and s.title=x.title where s.status='review'
on conflict(source_id,chunk_index) do update set heading=excluded.heading,content=excluded.content,citation_label=excluded.citation_label,token_count=excluded.token_count,content_hash=excluded.content_hash,metadata=excluded.metadata,embedding_status=excluded.embedding_status;
update public.lira_knowledge_sources s set ingestion_status='ingested',updated_at=now() where s.status='review' and s.metadata->>'phase'='4F' and exists(select 1 from public.lira_knowledge_chunks c where c.source_id=s.id);
