-- Phase 4G: Gram-negative AMR organism knowledge.
insert into public.lira_knowledge_sources(organization_id,source_type,title,authority,source_url,source_version,language,status,metadata,ingestion_status)
values
(null,'guidance','About Acinetobacter','CDC','https://www.cdc.gov/acinetobacter/about/index.html','2025-06','en','review',jsonb_build_object('official',true,'topic','acinetobacter','review_required',true,'phase','4G'),'pending'),
(null,'guidance','About Pseudomonas aeruginosa','CDC','https://www.cdc.gov/pseudomonas-aeruginosa/about/index.html','2025-06','en','review',jsonb_build_object('official',true,'topic','pseudomonas-aeruginosa','review_required',true,'phase','4G'),'pending'),
(null,'surveillance','Antimicrobial resistance in the EU/EEA (EARS-Net) – Annual Epidemiological Report for 2024','ECDC','https://www.ecdc.europa.eu/en/antimicrobial-resistance/surveillance-and-disease-data','2024-data/2025-report','en','review',jsonb_build_object('official',true,'topic','amr-europe','scope','EU/EEA surveillance','review_required',true,'phase','4G'),'pending')
on conflict do nothing;

with x(authority,title,chunk_index,heading,content,citation_label) as (values
('CDC','About Acinetobacter',0,'Acinetobacter — colonization versus infection','Acinetobacter can cause bloodstream, urinary tract, pulmonary and wound infections in healthcare settings, while some people may carry the organism without infection. LIRA must keep colonization separate from clinical infection and must not infer infection from organism detection alone.','CDC 2025 · Acinetobacter'),
('CDC','About Acinetobacter',1,'Acinetobacter — transmission and IPC','Acinetobacter can spread through contaminated surfaces and equipment and through person-to-person contact, including contaminated hands. Core infection prevention practices, hand hygiene and appropriate environmental and equipment cleaning are relevant controls.','CDC 2025 · Acinetobacter transmission'),
('CDC','About Acinetobacter',2,'Acinetobacter — resistance interpretation','Acinetobacter may be resistant to multiple antimicrobials. Susceptibility results are required for treatment selection; LIRA must not infer a treatment regimen from the organism name or a resistance label alone.','CDC 2025 · Acinetobacter resistance guardrail'),
('CDC','About Pseudomonas aeruginosa',0,'P. aeruginosa — healthcare risk','Pseudomonas aeruginosa infections commonly occur in healthcare settings and can involve blood, lungs, urinary tract or postoperative sites. Patients with ventilators, invasive devices, wounds or burns can be at increased risk.','CDC 2025 · P. aeruginosa'),
('CDC','About Pseudomonas aeruginosa',1,'P. aeruginosa — environment and water','P. aeruginosa can spread through contaminated surfaces or equipment, contaminated hands and environmental water sources. Healthcare IPC should include core infection-control practices and appropriate water-management measures where relevant.','CDC 2025 · P. aeruginosa transmission'),
('CDC','About Pseudomonas aeruginosa',2,'P. aeruginosa — AMR guardrail','Some P. aeruginosa are resistant to multiple antimicrobial classes, including carbapenems. LIRA must use the actual susceptibility result and applicable breakpoint version and must not equate the species name with MDR status.','CDC 2025 · P. aeruginosa AMR guardrail'),
('ECDC','Antimicrobial resistance in the EU/EEA (EARS-Net) – Annual Epidemiological Report for 2024',0,'EU/EEA AMR surveillance context','EARS-Net provides population-level surveillance of antimicrobial resistance in invasive bacterial isolates across the EU/EEA. LIRA may use these data as epidemiological context, but European surveillance percentages must not be presented as the current resistance prevalence of an individual hospital.','ECDC · EARS-Net 2024 data'),
('ECDC','Antimicrobial resistance in the EU/EEA (EARS-Net) – Annual Epidemiological Report for 2024',1,'Local versus external AMR data','For hospital-specific AMR questions, local authorized microbiology data are the primary factual source. External ECDC surveillance provides comparison and context only; differences in population, specimen selection, geography and reporting period must be stated when relevant.','ECDC · AMR context guardrail')
)
insert into public.lira_knowledge_chunks(source_id,chunk_index,heading,content,citation_label,token_count,content_hash,metadata,embedding_status)
select s.id,x.chunk_index,x.heading,x.content,x.citation_label,ceil(length(x.content)/4.0)::integer,md5(x.content),jsonb_build_object('curation','official-source-summary','review_required',true,'phase','4G'),'not_required'
from x join public.lira_knowledge_sources s on s.authority=x.authority and s.title=x.title where s.status='review'
on conflict(source_id,chunk_index) do update set heading=excluded.heading,content=excluded.content,citation_label=excluded.citation_label,token_count=excluded.token_count,content_hash=excluded.content_hash,metadata=excluded.metadata,embedding_status=excluded.embedding_status;
update public.lira_knowledge_sources s set ingestion_status='ingested',updated_at=now() where s.status='review' and s.metadata->>'phase'='4G' and exists(select 1 from public.lira_knowledge_chunks c where c.source_id=s.id);
