import { useEffect,useState } from 'react'
import { Plus,Trash2 } from 'lucide-react'
import { ActionButton } from '../../design-system/ActionButton'
import { Button } from '../../design-system/Button'
import { RegistryPagination } from '../../design-system/RegistryPagination'
import { ObserverDialog,DialogActions } from '../../design-system/ObserverDialog'
import { ManualDateField } from '../../design-system/ManualDateField'
import { AttachmentField } from '../../design-system/AttachmentField'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { useContextualNavigation } from '../../core/navigation/useContextualNavigation'
import { useEmployeeSubRecords } from './useEmployeeSubRecords'
import {
  loadOccupationalVisitsAsync,loadVaccinationsAsync,loadEmployeeTrainingAsync,loadEvaluationsAsync,loadCertificatesAsync,
  createCertificateAsync,updateCertificateAsync,deleteCertificateAsync,saveCertificatesLocalFallback,
} from './employeeSubRecordsService'
import { loadCertificates } from './employeeRecordsService'
import { getEmployeeSurveillanceForEmployee,updateEmployeeSurveillanceRecord } from '../surveillance/employeeSurveillanceData'
import { EmployeeSurveillanceRecordDialog } from '../surveillance/EmployeeSurveillanceRecordDialog'
import { loadEmployeeSurveillanceRecords } from '../surveillance/employeeSurveillanceCloudService'
import { loadLaboratorySamples } from '../laboratory/laboratoryCloudService'
import { laboratorySamples as demoLaboratorySamples } from '../laboratory/laboratoryDemoData'
import './employeeRecordTabsRefinements.css'

function SectionTitle({title,subtitle,action}){return <div className="record-section-header"><div><span className="eyebrow">Limoxis Observer</span><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}
function Empty({language,title}){return <div className="registry-empty-state employee-registry-empty"><strong>{title||(language==='en'?'No records':'Δεν υπάρχουν εγγραφές')}</strong></div>}
function State({loading,error,language,onRetry}){if(loading)return <div className="inline-empty">{language==='en'?'Loading…':'Φόρτωση…'}</div>;if(error)return <div className="data-access-state error"><span>{language==='en'?'Could not load this employee data.':'Δεν ήταν δυνατή η φόρτωση των δεδομένων του εργαζομένου.'}</span><Button variant="secondary" onClick={()=>onRetry?.().catch(()=>{})}>{language==='en'?'Retry':'Επανάληψη'}</Button></div>;return null}
function usePaged(rows){const [page,setPage]=useState(1),[pageSize,setPageSize]=useState(15);const totalPages=Math.max(1,Math.ceil(rows.length/pageSize)),safePage=Math.min(page,totalPages),paged=rows.slice((safePage-1)*pageSize,safePage*pageSize);useEffect(()=>{if(page!==safePage)setPage(safePage)},[page,safePage]);return {page:safePage,pageSize,totalPages,paged,setPage,setPageSize}}
function Pager({paging,total,language}){if(!total)return null;return <RegistryPagination language={language} page={paging.page} totalPages={paging.totalPages} totalItems={total} pageSize={paging.pageSize} onPageChange={paging.setPage} onPageSizeChange={size=>{paging.setPageSize(size);paging.setPage(1)}}/>}
function statusClass(status){return ['complete','completed','fit','active','approved'].includes(status)?'active':['renew_soon','pending','scheduled','assigned','in_progress'].includes(status)?'temporary':['overdue','unfit','cancelled','declined'].includes(status)?'danger':''}
function label(value,t){if(!value)return '—';const translated=t?.(value);return translated&&translated!==value?translated:value}
function compactEpisodeCode(value){const code=String(value||'');if(code.startsWith('ESUR-')){const parts=code.split('-');if(parts.length>=3)return `ES-${parts[1]}-${parts.at(-1).slice(-4)}`}return code}

export function EmployeeOccupationalTab({employee,t,language,fmt,organizationId}){
  const state=useEmployeeSubRecords(loadOccupationalVisitsAsync,organizationId,employee.dbId,employee.id)
  const [selected,setSelected]=useState(null)
  const paging=usePaged(state.data)
  return <section className="record-section employee-secondary-registry">
    <SectionTitle title={language==='en'?'Occupational Health':'Ιατρός Εργασίας'} subtitle={language==='en'?'Visits are read from the Occupational Health clinical record.':'Οι επισκέψεις αντλούνται από το κλινικό αρχείο Ιατρού Εργασίας.'}/>
    <State {...state} language={language} onRetry={state.reload}/>
    {!state.loading&&!state.error&&(state.data.length?<><div className="scroll-table"><table className="data-table sticky-table record-table-clickable"><thead><tr><th>{language==='en'?'Visit date':'Ημερομηνία'}</th><th>{language==='en'?'Visit type':'Τύπος επίσκεψης'}</th><th>{language==='en'?'Fitness':'Καταλληλότητα'}</th><th>{language==='en'?'Follow-up':'Επανέλεγχος'}</th><th>{language==='en'?'Status':'Κατάσταση'}</th></tr></thead><tbody>{paging.paged.map(row=><tr key={row.id} tabIndex={0} onClick={()=>setSelected(row)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(row)}}}><td>{fmt(row.date)}</td><td><strong>{label(row.type,t)}</strong></td><td>{label(row.fitStatus,t)}</td><td>{fmt(row.followUpDate)}</td><td><span className={`status-badge ${statusClass(row.status)}`}>{label(row.status,t)}</span></td></tr>)}</tbody></table></div><Pager paging={paging} total={state.data.length} language={language}/></>:<Empty language={language} title={language==='en'?'No occupational-health visits':'Δεν υπάρχουν επισκέψεις Ιατρού Εργασίας'}/>) }
    {selected&&<ObserverDialog width="wide" eyebrow={language==='en'?'Occupational Health':'Ιατρός Εργασίας'} title={`${fmt(selected.date)} · ${label(selected.type,t)}`} onClose={()=>setSelected(null)}><div className="detail-grid"><div className="detail-item"><span>{language==='en'?'Status':'Κατάσταση'}</span><strong>{label(selected.status,t)}</strong></div><div className="detail-item"><span>{language==='en'?'Fitness status':'Καταλληλότητα'}</span><strong>{label(selected.fitStatus,t)}</strong></div><div className="detail-item"><span>{language==='en'?'Follow-up date':'Ημερομηνία επανελέγχου'}</span><strong>{fmt(selected.followUpDate)}</strong></div></div><div className="source-truth-note"><div><strong>{language==='en'?'Notes / treatment':'Σημειώσεις / αντιμετώπιση'}</strong><span>{selected.clinicalNotes||'—'}</span></div></div></ObserverDialog>}
  </section>
}

export function EmployeeVaccinationsTab({employee,t,language,fmt,organizationId}){
  const state=useEmployeeSubRecords(loadVaccinationsAsync,organizationId,employee.dbId,employee.id)
  const [selected,setSelected]=useState(null)
  const paging=usePaged(state.data)
  return <section className="record-section employee-secondary-registry">
    <SectionTitle title={language==='en'?'Vaccinations':'Εμβολιασμοί'} subtitle={language==='en'?'Vaccination records come from the staff vaccination register.':'Τα στοιχεία αντλούνται από το μητρώο εμβολιασμών προσωπικού.'}/>
    <State {...state} language={language} onRetry={state.reload}/>
    {!state.loading&&!state.error&&(state.data.length?<><div className="scroll-table"><table className="data-table sticky-table record-table-clickable"><thead><tr><th>{language==='en'?'Vaccine':'Εμβόλιο'}</th><th>{language==='en'?'Dose':'Δόση'}</th><th>{language==='en'?'Date':'Ημερομηνία'}</th><th>{language==='en'?'Valid until':'Ισχύει έως'}</th><th>{language==='en'?'Status':'Κατάσταση'}</th></tr></thead><tbody>{paging.paged.map(row=><tr key={row.id} tabIndex={0} onClick={()=>setSelected(row)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(row)}}}><td><strong>{row.vaccine||'—'}</strong></td><td>{row.dose||'—'}</td><td>{fmt(row.date)}</td><td>{fmt(row.validUntil)}</td><td><span className={`status-badge ${statusClass(row.status)}`}>{label(row.status,t)}</span></td></tr>)}</tbody></table></div><Pager paging={paging} total={state.data.length} language={language}/></>:<Empty language={language} title={language==='en'?'No vaccination records':'Δεν υπάρχουν εμβολιασμοί'}/>) }
    {selected&&<ObserverDialog width="wide" eyebrow={language==='en'?'Staff vaccination':'Εμβολιασμός προσωπικού'} title={selected.vaccine||'—'} subtitle={fmt(selected.date)} onClose={()=>setSelected(null)}><div className="detail-grid"><div className="detail-item"><span>{language==='en'?'Dose':'Δόση'}</span><strong>{selected.dose||'—'}</strong></div><div className="detail-item"><span>{language==='en'?'Lot number':'Αριθμός παρτίδας'}</span><strong>{selected.lotNumber||'—'}</strong></div><div className="detail-item"><span>{language==='en'?'Valid until':'Ισχύει έως'}</span><strong>{fmt(selected.validUntil)}</strong></div><div className="detail-item"><span>{language==='en'?'Status':'Κατάσταση'}</span><strong>{label(selected.status,t)}</strong></div></div>{selected.clinicalNotes&&<div className="source-truth-note"><div><strong>{language==='en'?'Notes':'Σημειώσεις'}</strong><span>{selected.clinicalNotes}</span></div></div>}</ObserverDialog>}
  </section>
}

export function EmployeeTrainingTab({employee,t,language,fmt,organizationId,canOpenProgram=false}){
  const {goTo}=useContextualNavigation('/training')
  const state=useEmployeeSubRecords(loadEmployeeTrainingAsync,organizationId,employee.dbId,employee.id)
  const [selected,setSelected]=useState(null)
  const paging=usePaged(state.data)
  return <section className="record-section employee-secondary-registry">
    <SectionTitle title={language==='en'?'Training':'Εκπαίδευση'} subtitle={language==='en'?'Assignments and completion data come directly from Training programmes.':'Οι αναθέσεις και οι ολοκληρώσεις αντλούνται απευθείας από τα προγράμματα Εκπαίδευσης.'}/>
    <State {...state} language={language} onRetry={state.reload}/>
    {!state.loading&&!state.error&&(state.data.length?<><div className="scroll-table"><table className="data-table sticky-table record-table-clickable"><thead><tr><th>{language==='en'?'Training':'Εκπαίδευση'}</th><th>{language==='en'?'Date':'Ημερομηνία'}</th><th>{language==='en'?'Status':'Κατάσταση'}</th><th>{language==='en'?'Score':'Βαθμολογία'}</th></tr></thead><tbody>{paging.paged.map(row=><tr key={row.id} tabIndex={0} onClick={()=>setSelected(row)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(row)}}}><td><strong>{language==='el'?(row.titleEl||row.titleEn):(row.titleEn||row.titleEl)}</strong></td><td>{fmt(row.date)}</td><td><span className={`status-badge ${statusClass(row.status)}`}>{label(row.status,t)}</span></td><td>{row.score!=null?`${row.score}%`:'—'}</td></tr>)}</tbody></table></div><Pager paging={paging} total={state.data.length} language={language}/></>:<Empty language={language} title={language==='en'?'No training records':'Δεν υπάρχουν εκπαιδεύσεις'}/>) }
    {selected&&<ObserverDialog width="wide" eyebrow={language==='en'?'Employee training':'Εκπαίδευση εργαζομένου'} title={language==='el'?(selected.titleEl||selected.titleEn):(selected.titleEn||selected.titleEl)} subtitle={fmt(selected.date)} onClose={()=>setSelected(null)} footer={canOpenProgram&&selected.programId?<Button onClick={()=>goTo(`/training/${selected.programId}`,{tab:'training'})}>{language==='en'?'Open training programme':'Άνοιγμα εκπαίδευσης'}</Button>:undefined}><div className="detail-grid"><div className="detail-item"><span>{language==='en'?'Status':'Κατάσταση'}</span><strong>{label(selected.status,t)}</strong></div><div className="detail-item"><span>{language==='en'?'Assigned':'Ανάθεση'}</span><strong>{fmt(selected.assignedDate)}</strong></div><div className="detail-item"><span>{language==='en'?'Completed':'Ολοκλήρωση'}</span><strong>{fmt(selected.completedDate)}</strong></div><div className="detail-item"><span>{language==='en'?'Score':'Βαθμολογία'}</span><strong>{selected.score!=null?`${selected.score}%`:'—'}</strong></div></div></ObserverDialog>}
  </section>
}

export function EmployeeEvaluationsTab({employee,t:_t,language,fmt,organizationId}){
  const state=useEmployeeSubRecords(loadEvaluationsAsync,organizationId,employee.dbId,employee.id)
  const [selected,setSelected]=useState(null)
  const paging=usePaged(state.data)
  const titleOf=x=>language==='el'?(x.titleEl||x.titleEn):(x.titleEn||x.titleEl)
  const resultOf=x=>language==='el'?(x.resultEl||x.resultEn):(x.resultEn||x.resultEl)
  return <section className="record-section employee-secondary-registry">
    <SectionTitle title={language==='en'?'Evaluations':'Αξιολογήσεις'} subtitle={language==='en'?'Formal employee evaluations and training knowledge assessments are shown together, without duplicating data.':'Εμφανίζονται μαζί οι επίσημες αξιολογήσεις εργαζομένου και οι αξιολογήσεις γνώσεων από την Εκπαίδευση, χωρίς διπλά δεδομένα.'}/>
    <State {...state} language={language} onRetry={state.reload}/>
    {!state.loading&&!state.error&&(state.data.length?<><div className="scroll-table"><table className="data-table sticky-table record-table-clickable"><thead><tr><th>{language==='en'?'Evaluation':'Αξιολόγηση'}</th><th>{language==='en'?'Date':'Ημερομηνία'}</th><th>{language==='en'?'Result':'Αποτέλεσμα'}</th><th>{language==='en'?'Source':'Πηγή'}</th></tr></thead><tbody>{paging.paged.map(row=><tr key={row.id} tabIndex={0} onClick={()=>setSelected(row)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(row)}}}><td><strong>{titleOf(row)||'—'}</strong></td><td>{fmt(row.date)}</td><td>{resultOf(row)||'—'}</td><td>{row.source==='training'?(language==='en'?'Training':'Εκπαίδευση'):(language==='en'?'Employee evaluation':'Αξιολόγηση εργαζομένου')}</td></tr>)}</tbody></table></div><Pager paging={paging} total={state.data.length} language={language}/></>:<Empty language={language} title={language==='en'?'No evaluations':'Δεν υπάρχουν αξιολογήσεις'}/>) }
    {selected&&<ObserverDialog width="wide" eyebrow={language==='en'?'Employee evaluation':'Αξιολόγηση εργαζομένου'} title={titleOf(selected)||'—'} subtitle={fmt(selected.date)} onClose={()=>setSelected(null)}><div className="detail-grid"><div className="detail-item"><span>{language==='en'?'Result':'Αποτέλεσμα'}</span><strong>{resultOf(selected)||'—'}</strong></div><div className="detail-item"><span>{language==='en'?'Source':'Πηγή'}</span><strong>{selected.source==='training'?(language==='en'?'Training knowledge assessment':'Αξιολόγηση γνώσεων εκπαίδευσης'):(language==='en'?'Employee evaluation':'Αξιολόγηση εργαζομένου')}</strong></div>{selected.score!=null&&<div className="detail-item"><span>{language==='en'?'Score':'Βαθμολογία'}</span><strong>{selected.score}%</strong></div>}</div></ObserverDialog>}
  </section>
}

export function EmployeeCertificatesTab({employee,language,fmt,organizationId,canEdit=false,isDemo=false}){
  const {confirm,notify}=useFeedback()
  const state=useEmployeeSubRecords(loadCertificatesAsync,organizationId,employee.dbId,employee.id)
  const [selected,setSelected]=useState(null)
  const [editing,setEditing]=useState(false)
  const [saving,setSaving]=useState(false)
  const [draft,setDraft]=useState(null)
  const paging=usePaged(state.data)
  const titleOf=x=>language==='el'?(x.titleEl||x.titleEn):(x.titleEn||x.titleEl)
  function open(row){setSelected(row);setDraft({...row});setEditing(false)}
  function create(){const row={id:null,employeeId:employee.id,titleEl:'',titleEn:'',issuer:'',issueDate:'',validUntil:'',certificateNumber:'',attachments:[]};setSelected(row);setDraft(row);setEditing(true)}
  async function persist(){if(!draft?.titleEl?.trim()||saving)return;setSaving(true);try{let saved;if(isDemo){const all=loadCertificates();if(draft.id){saved={...draft};saveCertificatesLocalFallback(all.map(x=>x.id===draft.id?saved:x))}else{saved={...draft,id:`CERT-${Date.now()}`,employeeId:employee.id};saveCertificatesLocalFallback([saved,...all])}}else if(draft.id){saved=await updateCertificateAsync(organizationId,employee.dbId,draft.id,draft)}else{saved=await createCertificateAsync(organizationId,employee.dbId,draft)}await state.reload();setSelected(saved);setDraft(saved);setEditing(false);notify(language==='en'?'Certification saved.':'Η πιστοποίηση αποθηκεύτηκε.','success')}catch(error){notify(error?.message||(language==='en'?'Could not save the certification.':'Δεν ήταν δυνατή η αποθήκευση της πιστοποίησης.'),'danger')}finally{setSaving(false)}}
  async function remove(){if(!selected?.id||saving)return;const ok=await confirm({title:language==='en'?'Delete certification':'Διαγραφή πιστοποίησης',message:language==='en'?'The certification record will be permanently deleted. Attached files should be removed first if they are no longer required.':'Η εγγραφή πιστοποίησης θα διαγραφεί οριστικά. Διαγράψτε πρώτα τα συνημμένα αρχεία εφόσον δεν χρειάζονται πλέον.',confirmLabel:language==='en'?'Delete':'Διαγραφή',danger:true});if(!ok)return;setSaving(true);try{if(isDemo){saveCertificatesLocalFallback(loadCertificates().filter(x=>x.id!==selected.id))}else await deleteCertificateAsync(organizationId,employee.dbId,selected.id);await state.reload();setSelected(null);setDraft(null);notify(language==='en'?'Certification deleted.':'Η πιστοποίηση διαγράφηκε.','success')}catch(error){notify(error?.message||(language==='en'?'Could not delete the certification.':'Δεν ήταν δυνατή η διαγραφή της πιστοποίησης.'),'danger')}finally{setSaving(false)}}
  return <section className="record-section employee-secondary-registry employee-certificates-workspace">
    <SectionTitle title={language==='en'?'Certifications & documents':'Πιστοποιήσεις / Έγγραφα'} subtitle={language==='en'?'Keep structured certifications separate from general employee files.':'Οι πιστοποιήσεις τηρούνται ως δομημένες εγγραφές, χωριστά από τα λοιπά αρχεία εργαζομένου.'}/>
    <div className="employee-certificates-section">
      <div className="employee-certificates-section-header"><div><h4>{language==='en'?'Certifications':'Πιστοποιήσεις'}</h4><p>{language==='en'?'Certificate metadata, validity and supporting evidence.':'Στοιχεία πιστοποίησης, ισχύς και σχετικά τεκμήρια.'}</p></div>{canEdit&&<ActionButton tone="primary" label={language==='en'?'Add certification':'Προσθήκη πιστοποίησης'} onClick={create}><Plus size={15}/><span>{language==='en'?'Add certification':'Προσθήκη πιστοποίησης'}</span></ActionButton>}</div>
      <State {...state} language={language} onRetry={state.reload}/>
      {!state.loading&&!state.error&&(state.data.length?<><div className="scroll-table"><table className="data-table sticky-table record-table-clickable"><thead><tr><th>{language==='en'?'Certification':'Πιστοποίηση'}</th><th>{language==='en'?'Issuer':'Φορέας'}</th><th>{language==='en'?'Issue date':'Ημερομηνία έκδοσης'}</th><th>{language==='en'?'Valid until':'Ισχύει έως'}</th></tr></thead><tbody>{paging.paged.map(row=><tr key={row.id} tabIndex={0} onClick={()=>open(row)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(row)}}}><td><strong>{titleOf(row)||'—'}</strong><small>{row.certificateNumber||''}</small></td><td>{row.issuer||'—'}</td><td>{fmt(row.issueDate)}</td><td>{fmt(row.validUntil)}</td></tr>)}</tbody></table></div><Pager paging={paging} total={state.data.length} language={language}/></>:<div className="employee-certificates-empty"><div><strong>{language==='en'?'No certifications yet':'Δεν υπάρχουν πιστοποιήσεις'}</strong><span>{language==='en'?'Add a structured certification only when there is one to register.':'Προσθέστε δομημένη πιστοποίηση μόνο όταν υπάρχει σχετική εγγραφή.'}</span></div></div>) }
    </div>
    <div className="employee-certificates-section employee-other-documents">
      <div className="employee-certificates-section-header"><div><h4>{language==='en'?'Other employee documents':'Λοιπά έγγραφα εργαζομένου'}</h4><p>{language==='en'?'Files that do not belong to a specific certification.':'Αρχεία που δεν ανήκουν σε συγκεκριμένη πιστοποίηση.'}</p></div></div>
      <AttachmentField disabled={!canEdit} value={[]} onChange={()=>{}} organizationId={organizationId} entityType="employee-certificate" entityId={employee.dbId||employee.id}/>
    </div>
    {selected&&draft&&<ObserverDialog width="wide" eyebrow={language==='en'?'Employee certification':'Πιστοποίηση εργαζομένου'} title={selected.id?(titleOf(draft)||'—'):(language==='en'?'New certification':'Νέα πιστοποίηση')} onClose={()=>{setSelected(null);setDraft(null)}} footer={editing?<DialogActions onCancel={()=>selected.id?setEditing(false):setSelected(null)} disabled={saving||!draft.titleEl.trim()} onSave={persist} saveLabel={saving?(language==='en'?'Saving…':'Αποθήκευση…'):(language==='en'?'Save':'Αποθήκευση')}/>:undefined}><div className="entry-grid compact"><label className="entry-span-2"><span>{language==='en'?'Title':'Τίτλος'} *</span>{editing?<input value={draft.titleEl||''} onChange={e=>setDraft(v=>({...v,titleEl:e.target.value}))}/>:<strong>{titleOf(draft)||'—'}</strong>}</label><label><span>{language==='en'?'Issuer':'Φορέας'}</span>{editing?<input value={draft.issuer||''} onChange={e=>setDraft(v=>({...v,issuer:e.target.value}))}/>:<strong>{draft.issuer||'—'}</strong>}</label><label><span>{language==='en'?'Certificate number':'Αριθμός πιστοποιητικού'}</span>{editing?<input value={draft.certificateNumber||''} onChange={e=>setDraft(v=>({...v,certificateNumber:e.target.value}))}/>:<strong>{draft.certificateNumber||'—'}</strong>}</label>{editing?<ManualDateField label={language==='en'?'Issue date':'Ημερομηνία έκδοσης'} value={draft.issueDate||''} onChange={value=>setDraft(v=>({...v,issueDate:value}))} optional/>:<div className="detail-item"><span>{language==='en'?'Issue date':'Ημερομηνία έκδοσης'}</span><strong>{fmt(draft.issueDate)}</strong></div>}{editing?<ManualDateField label={language==='en'?'Valid until':'Ισχύει έως'} value={draft.validUntil||''} onChange={value=>setDraft(v=>({...v,validUntil:value}))} optional/>:<div className="detail-item"><span>{language==='en'?'Valid until':'Ισχύει έως'}</span><strong>{fmt(draft.validUntil)}</strong></div>}</div>{selected.id&&<><div className="record-section-header"><div><span className="eyebrow">{language==='en'?'FILES':'ΑΡΧΕΙΑ'}</span><h3>{language==='en'?'Supporting files':'Συνημμένα τεκμήρια'}</h3></div>{canEdit&&!editing&&<div className="record-actions"><Button variant="secondary" onClick={()=>setEditing(true)}>{language==='en'?'Edit':'Επεξεργασία'}</Button><Button variant="danger" onClick={remove} disabled={saving}><Trash2 size={15}/>{language==='en'?' Delete':' Διαγραφή'}</Button></div>}</div><AttachmentField disabled={!canEdit} value={draft.attachments||[]} onChange={files=>setDraft(v=>({...v,attachments:files}))} organizationId={organizationId} entityType="employee-certificate" entityId={selected.id}/></>}</ObserverDialog>}
  </section>
}

export function EmployeeSurveillanceTab({employee,t,language,fmt,version,onNew,readOnly=false,isDemo=false,organizationId=null,canManageFollowup=false}){
  const demoRows=isDemo?getEmployeeSurveillanceForEmployee(employee.id):[]
  const [cloudRecords,setCloudRecords]=useState([])
  const [cloudSamples,setCloudSamples]=useState([])
  const [selected,setSelected]=useState(null)
  const [loading,setLoading]=useState(!isDemo)
  useEffect(()=>{if(isDemo||!organizationId||!employee?.dbId){setLoading(false);return}let active=true;setLoading(true);Promise.all([loadEmployeeSurveillanceRecords(organizationId),loadLaboratorySamples(organizationId)]).then(([records,samples])=>{if(!active)return;setCloudRecords(records.filter(row=>row.employeeDbId===employee.dbId));setCloudSamples(samples)}).catch(()=>{if(active){setCloudRecords([]);setCloudSamples([])}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[isDemo,organizationId,employee?.dbId,version])
  const rows=isDemo?demoRows:cloudRecords
  const paging=usePaged(rows)
  const selectedSamples=selected?(isDemo?demoLaboratorySamples.filter(sample=>sample.employeeSurveillanceCase===selected.id):cloudSamples.filter(sample=>sample.employeeSurveillanceId===selected.recordId)):[]
  const saveDemoFollowup=(record,patch)=>Promise.resolve(updateEmployeeSurveillanceRecord(record.id,{...patch,updatedAt:new Date().toISOString()}))
  return <section className="record-section employee-secondary-registry"><SectionTitle title={language==='en'?'Surveillance':'Επιτήρηση'} subtitle={language==='en'?'Employee screening episodes and their linked laboratory samples.':'Επεισόδια επιτήρησης εργαζομένου και τα συνδεδεμένα εργαστηριακά δείγματα.'} action={!readOnly&&<ActionButton tone="primary" label={t('newSurveillance')} onClick={onNew}><Plus size={15}/><span>{t('newSurveillance')}</span></ActionButton>}/>{loading?<div className="inline-empty">{language==='en'?'Loading…':'Φόρτωση…'}</div>:rows.length?<><div className="scroll-table"><table className="data-table sticky-table record-table-clickable"><thead><tr><th>{language==='en'?'Episode':'Επεισόδιο'}</th><th>{language==='en'?'Start date':'Έναρξη'}</th><th>{language==='en'?'Screening':'Έλεγχος'}</th><th>{language==='en'?'Status':'Κατάσταση'}</th></tr></thead><tbody>{paging.paged.map(row=><tr key={row.id} tabIndex={0} onClick={()=>setSelected(row)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(row)}}}><td><strong className="employee-code-compact" title={row.id}>{compactEpisodeCode(row.id)}</strong></td><td>{fmt(row.startedAt)}</td><td>{row.screeningTypes?.map(type=>label(type,t)).join(', ')||'—'}</td><td><span className={`status-badge ${statusClass(row.status)}`}>{label(row.status,t)}</span></td></tr>)}</tbody></table></div><Pager paging={paging} total={rows.length} language={language}/></>:<Empty language={language} title={language==='en'?'No surveillance episodes':'Δεν υπάρχουν επεισόδια επιτήρησης'}/>} {selected&&<EmployeeSurveillanceRecordDialog organizationId={organizationId} record={selected} samples={selectedSamples} canManage={canManageFollowup} t={t} language={language} fmt={fmt} onClose={()=>setSelected(null)} onSaveFollowup={isDemo?saveDemoFollowup:undefined} onUpdated={updated=>{if(!isDemo)setCloudRecords(current=>current.map(row=>row.recordId===updated.recordId?updated:row));setSelected(updated)}}/>}</section>
}

export function EmployeeHistoryTab({employee,language}){const rows=[];if(employee.createdAt)rows.push({id:'created',at:employee.createdAt,event:language==='en'?'Employee record created':'Δημιουργία καρτέλας εργαζομένου'});if(employee.updatedAt&&employee.updatedAt!==employee.createdAt)rows.push({id:'updated',at:employee.updatedAt,event:language==='en'?'Employee record updated':'Τελευταία ενημέρωση καρτέλας'});if(employee.accountLinked)rows.push({id:'account',at:null,event:language==='en'?'Linked user account':'Συνδεδεμένος λογαριασμός χρήστη'});const format=value=>{if(!value)return '—';const d=new Date(value);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat(language==='en'?'en-GB':'el-GR',{dateStyle:'medium',timeStyle:'short'}).format(d)};return <section className="record-section employee-secondary-registry"><SectionTitle title={language==='en'?'History':'Ιστορικό'} subtitle={language==='en'?'Administrative lifecycle of the employee record. Clinical events remain in their own governed tabs.':'Διοικητικό ιστορικό της καρτέλας εργαζομένου. Τα κλινικά συμβάντα παραμένουν στις αντίστοιχες ελεγχόμενες καρτέλες.'}/>{rows.length?<div className="scroll-table"><table className="data-table sticky-table"><thead><tr><th>{language==='en'?'Event':'Ενέργεια'}</th><th>{language==='en'?'Date / time':'Ημερομηνία / ώρα'}</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.event}</strong></td><td>{format(row.at)}</td></tr>)}</tbody></table></div>:<Empty language={language} title={language==='en'?'No lifecycle history is available':'Δεν υπάρχει διαθέσιμο ιστορικό καρτέλας'}/>}</section>}
