import { useEffect,useState } from 'react'
import { normalizeTrainingQuestion } from '../training/trainingAssessment'
import { useFeedback } from '../../core/feedback/FeedbackContext'
import { loadSnapshot } from '../../core/data/repository'
import { PERFORMANCE_EVALUATION_QUESTIONNAIRE } from '../management/QuestionnairesPanel'
import { Download,Plus } from 'lucide-react'
import { downloadCertificatePdf } from '../training/trainingCertificate'
import { ActionButton } from '../../design-system/ActionButton'
import { Button } from '../../design-system/Button'
import { RegistryPagination } from '../../design-system/RegistryPagination'
import { FilterBar } from '../../design-system/FilterBar'
import { ManualDateField } from '../../design-system/ManualDateField'
import { ObserverDialog } from '../../design-system/ObserverDialog'
import { DocumentsWorkspace } from '../../design-system/DocumentsWorkspace'
import { useContextualNavigation } from '../../core/navigation/useContextualNavigation'
import { useEmployeeSubRecords } from './useEmployeeSubRecords'
import { loadOccupationalVisitsAsync,loadVaccinationsAsync,loadEmployeeTrainingAsync,loadEvaluationsAsync,loadExposureIncidentsAsync,createEmployeeEvaluationAsync,updateEmployeeEvaluationWorkflowAsync } from './employeeSubRecordsService'
import { loadEmployeeHistoryAsync } from './employeeHistoryService'
import { getEmployeeSurveillanceForEmployee,updateEmployeeSurveillanceRecord } from '../surveillance/employeeSurveillanceData'
import { EmployeeSurveillanceRecordDialog } from '../surveillance/EmployeeSurveillanceRecordDialog'
import { loadEmployeeSurveillanceRecords } from '../surveillance/employeeSurveillanceCloudService'
import { loadLaboratorySamples } from '../laboratory/laboratoryCloudService'
import { laboratorySamples as demoLaboratorySamples } from '../laboratory/laboratoryDemoData'
import './employeeRecordTabsRefinements.css'

function SectionTitle({title,subtitle,action}){return <div className="record-section-header"><div><span className="eyebrow">Limoxis Observer</span><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}
function Empty({language,title}){return <div className="registry-empty-state employee-registry-empty"><strong>{title||(language==='en'?'No records':'Δεν υπάρχουν εγγραφές')}</strong></div>}
function State({loading,error,language,onRetry}){if(loading)return <div className="inline-empty">{language==='en'?'Loading…':'Φόρτωση…'}</div>;if(error)return <div className="data-access-state error"><span>{language==='en'?'Could not load this employee data.':'Δεν ήταν δυνατή η φόρτωση των δεδομένων του εργαζομένου.'}</span><Button variant="secondary" onClick={()=>onRetry?.().catch(()=>{})}>{language==='en'?'Retry':'Επανάληψη'}</Button></div>;return null}
function usePaged(rows){const [page,setPage]=useState(1),[pageSize,setPageSize]=useState(15);const totalPages=Math.max(1,Math.ceil(rows.length/pageSize)),safePage=Math.min(page,totalPages),paged=rows.slice((safePage-1)*pageSize,safePage*pageSize);useEffect(()=>{if(page!==safePage)setPage(safePage)},[page,safePage]);return {page:safePage,pageSize,totalPages,paged,setPage,setPageSize}}
function Pager({paging,total,language}){if(!total)return null;return <div className="employee-registry-pagination-slot"><RegistryPagination language={language} page={paging.page} totalPages={paging.totalPages} totalItems={total} pageSize={paging.pageSize} onPageChange={paging.setPage} onPageSizeChange={size=>{paging.setPageSize(size);paging.setPage(1)}}/></div>}
function RegistryFilter({query,setQuery,language,count}){return <FilterBar query={query} onQueryChange={setQuery} placeholder={language==='en'?'Search records...':'Αναζήτηση εγγραφών...'} activeAdvancedCount={0} onClear={()=>setQuery('')} resultCount={count}/>}
function useRegistryRows(rows){const [query,setQuery]=useState('');const filtered=query.trim()?rows.filter(row=>JSON.stringify(row).toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())):rows;const paging=usePaged(filtered);return {query,setQuery,filtered,paging}}
function statusClass(status){return ['complete','completed','fit','active','approved'].includes(status)?'active':['renew_soon','pending','scheduled','assigned','in_progress'].includes(status)?'temporary':['overdue','unfit','cancelled','declined'].includes(status)?'danger':''}
function label(value,t){if(!value)return '—';const translated=t?.(value);return translated&&translated!==value?translated:value}
function compactEpisodeCode(value){const code=String(value||'');if(code.startsWith('ESUR-')){const parts=code.split('-');if(parts.length>=3)return `ES-${parts[1]}-${parts.at(-1).slice(-4)}`}return code}

export function EmployeeOccupationalTab({employee,t,language,fmt,organizationId}){
  const state=useEmployeeSubRecords(loadOccupationalVisitsAsync,organizationId,employee.dbId,employee.id)
  const [selected,setSelected]=useState(null)
  const registry=useRegistryRows(state.data)
  const paging=registry.paging
  return <section className="record-section record-secondary-registry">
    <SectionTitle title={language==='en'?'Occupational Health':'Ιατρός Εργασίας'} subtitle={language==='en'?'Visits are read from the Occupational Health clinical record.':'Οι επισκέψεις αντλούνται από το κλινικό αρχείο Ιατρού Εργασίας.'}/>
    <State {...state} language={language} onRetry={state.reload}/>
    {!state.loading&&!state.error&&<RegistryFilter query={registry.query} setQuery={registry.setQuery} language={language} count={registry.filtered.length}/>}
    {!state.loading&&!state.error&&(registry.filtered.length?<><div className="scroll-table"><table className="data-table sticky-table record-table-clickable"><thead><tr><th>{language==='en'?'Visit date':'Ημερομηνία'}</th><th>{language==='en'?'Visit type':'Τύπος επίσκεψης'}</th><th>{language==='en'?'Fitness':'Καταλληλότητα'}</th><th>{language==='en'?'Follow-up':'Επανέλεγχος'}</th><th>{language==='en'?'Status':'Κατάσταση'}</th></tr></thead><tbody>{paging.paged.map(row=><tr key={row.id} tabIndex={0} onClick={()=>setSelected(row)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(row)}}}><td>{fmt(row.date)}</td><td><strong>{label(row.type,t)}</strong></td><td>{label(row.fitStatus,t)}</td><td>{fmt(row.followUpDate)}</td><td><span className={`status-badge ${statusClass(row.status)}`}>{label(row.status,t)}</span></td></tr>)}</tbody></table></div><Pager paging={paging} total={registry.filtered.length} language={language}/></>:<Empty language={language} title={language==='en'?'No occupational-health visits':'Δεν υπάρχουν επισκέψεις Ιατρού Εργασίας'}/>) }
    {selected&&<ObserverDialog width="wide" eyebrow={language==='en'?'Occupational Health':'Ιατρός Εργασίας'} title={`${fmt(selected.date)} · ${label(selected.type,t)}`} onClose={()=>setSelected(null)}><div className="detail-grid"><div className="detail-item"><span>{language==='en'?'Status':'Κατάσταση'}</span><strong>{label(selected.status,t)}</strong></div><div className="detail-item"><span>{language==='en'?'Fitness status':'Καταλληλότητα'}</span><strong>{label(selected.fitStatus,t)}</strong></div><div className="detail-item"><span>{language==='en'?'Follow-up date':'Ημερομηνία επανελέγχου'}</span><strong>{fmt(selected.followUpDate)}</strong></div></div><div className="source-truth-note"><div><strong>{language==='en'?'Notes / treatment':'Σημειώσεις / αντιμετώπιση'}</strong><span>{selected.clinicalNotes||'—'}</span></div></div></ObserverDialog>}
  </section>
}

export function EmployeeVaccinationsTab({employee,t,language,fmt,organizationId}){
  const state=useEmployeeSubRecords(loadVaccinationsAsync,organizationId,employee.dbId,employee.id)
  const [selected,setSelected]=useState(null)
  const registry=useRegistryRows(state.data)
  const paging=registry.paging
  return <section className="record-section record-secondary-registry">
    <SectionTitle title={language==='en'?'Vaccinations':'Εμβολιασμοί'} subtitle={language==='en'?'Vaccination records come from the staff vaccination register.':'Τα στοιχεία αντλούνται από το μητρώο εμβολιασμών προσωπικού.'}/>
    <State {...state} language={language} onRetry={state.reload}/>
    {!state.loading&&!state.error&&<RegistryFilter query={registry.query} setQuery={registry.setQuery} language={language} count={registry.filtered.length}/>}
    {!state.loading&&!state.error&&(registry.filtered.length?<><div className="scroll-table"><table className="data-table sticky-table record-table-clickable"><thead><tr><th>{language==='en'?'Vaccine':'Εμβόλιο'}</th><th>{language==='en'?'Dose':'Δόση'}</th><th>{language==='en'?'Date':'Ημερομηνία'}</th><th>{language==='en'?'Valid until':'Ισχύει έως'}</th><th>{language==='en'?'Status':'Κατάσταση'}</th></tr></thead><tbody>{paging.paged.map(row=><tr key={row.id} tabIndex={0} onClick={()=>setSelected(row)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(row)}}}><td><strong>{row.vaccine||'—'}</strong></td><td>{row.dose||'—'}</td><td>{fmt(row.date)}</td><td>{fmt(row.validUntil)}</td><td><span className={`status-badge ${statusClass(row.status)}`}>{label(row.status,t)}</span></td></tr>)}</tbody></table></div><Pager paging={paging} total={registry.filtered.length} language={language}/></>:<Empty language={language} title={language==='en'?'No vaccination records':'Δεν υπάρχουν εμβολιασμοί'}/>) }
    {selected&&<ObserverDialog width="wide" eyebrow={language==='en'?'Staff vaccination':'Εμβολιασμός προσωπικού'} title={selected.vaccine||'—'} subtitle={fmt(selected.date)} onClose={()=>setSelected(null)}><div className="detail-grid"><div className="detail-item"><span>{language==='en'?'Dose':'Δόση'}</span><strong>{selected.dose||'—'}</strong></div><div className="detail-item"><span>{language==='en'?'Lot number':'Αριθμός παρτίδας'}</span><strong>{selected.lotNumber||'—'}</strong></div><div className="detail-item"><span>{language==='en'?'Valid until':'Ισχύει έως'}</span><strong>{fmt(selected.validUntil)}</strong></div><div className="detail-item"><span>{language==='en'?'Status':'Κατάσταση'}</span><strong>{label(selected.status,t)}</strong></div></div>{selected.clinicalNotes&&<div className="source-truth-note"><div><strong>{language==='en'?'Notes':'Σημειώσεις'}</strong><span>{selected.clinicalNotes}</span></div></div>}</ObserverDialog>}
  </section>
}

export function EmployeeExposureIncidentsTab({employee,language,fmt,organizationId}){
  const en=language==='en'
  const state=useEmployeeSubRecords(loadExposureIncidentsAsync,organizationId,employee.dbId,employee.id)
  const [selected,setSelected]=useState(null)
  const registry=useRegistryRows(state.data)
  const paging=registry.paging
  const typeLabel=value=>({needlestick:['Τρύπημα βελόνας','Needlestick'],sharps_object:['Άλλο αιχμηρό αντικείμενο','Other sharps object'],mucocutaneous:['Έκθεση βλεννογόνου','Mucocutaneous exposure'],non_intact_skin:['Έκθεση μη ακέραιου δέρματος','Non-intact skin exposure'],other:['Άλλο','Other']}[value]?.[en?1:0]||value||'—')
  const followUpLabel=value=>({pending:['Εκκρεμεί','Pending'],scheduled:['Προγραμματισμένη','Scheduled'],completed:['Ολοκληρώθηκε','Completed'],closed:['Έκλεισε','Closed']}[value]?.[en?1:0]||value||'—')
  return <section className="record-section record-secondary-registry">
    <SectionTitle title={en?'Occupational exposure':'Επαγγελματική έκθεση'} subtitle={en?'Needlestick, sharps and mucocutaneous exposure incidents and their follow-up.':'Περιστατικά τρυπήματος βελόνας, αιχμηρών αντικειμένων και έκθεσης βλεννογόνου, με την παρακολούθησή τους.'}/>
    <State {...state} language={language} onRetry={state.reload}/>
    {!state.loading&&!state.error&&<RegistryFilter query={registry.query} setQuery={registry.setQuery} language={language} count={registry.filtered.length}/>}
    {!state.loading&&!state.error&&(registry.filtered.length?<><div className="scroll-table"><table className="data-table sticky-table record-table-clickable"><thead><tr><th>{en?'Date':'Ημερομηνία'}</th><th>{en?'Exposure type':'Τύπος έκθεσης'}</th><th>{en?'Follow-up':'Παρακολούθηση'}</th><th>{en?'Status':'Κατάσταση'}</th></tr></thead><tbody>{paging.paged.map(row=><tr key={row.id} tabIndex={0} onClick={()=>setSelected(row)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(row)}}}><td>{fmt(row.incidentDate)}</td><td><strong>{typeLabel(row.exposureType)}</strong></td><td>{followUpLabel(row.followUpStatus)}</td><td><span className={`status-badge ${row.status==='open'?'temporary':''}`}>{row.status==='open'?(en?'Open':'Ανοικτό'):(en?'Closed':'Κλειστό')}</span></td></tr>)}</tbody></table></div><Pager paging={paging} total={registry.filtered.length} language={language}/></>:<Empty language={language} title={en?'No exposure incidents recorded':'Δεν έχουν καταγραφεί περιστατικά έκθεσης'}/>) }
    {selected&&<ObserverDialog width="wide" eyebrow={en?'Occupational exposure':'Επαγγελματική έκθεση'} title={`${fmt(selected.incidentDate)} · ${typeLabel(selected.exposureType)}`} onClose={()=>setSelected(null)}><div className="detail-grid"><div className="detail-item"><span>{en?'Device / source':'Συσκευή / πηγή'}</span><strong>{selected.deviceOrSource||'—'}</strong></div><div className="detail-item"><span>{en?'Body site':'Σημείο έκθεσης'}</span><strong>{selected.bodySite||'—'}</strong></div><div className="detail-item"><span>{en?'Follow-up status':'Κατάσταση παρακολούθησης'}</span><strong>{followUpLabel(selected.followUpStatus)}</strong></div><div className="detail-item"><span>{en?'Follow-up due':'Επόμενος επανέλεγχος'}</span><strong>{fmt(selected.followUpDueAt)}</strong></div></div><div className="source-truth-note"><div><strong>{en?'Notes':'Σημειώσεις'}</strong><span>{selected.notes||'—'}</span></div></div></ObserverDialog>}
  </section>
}

export function EmployeeTrainingTab({employee,t,language,fmt,organizationId,canOpenProgram=false}){
  const {goTo}=useContextualNavigation('/training')
  const state=useEmployeeSubRecords(loadEmployeeTrainingAsync,organizationId,employee.dbId,employee.id)
  const [selected,setSelected]=useState(null)
  const registry=useRegistryRows(state.data)
  const paging=registry.paging
  return <section className="record-section record-secondary-registry">
    <SectionTitle title={language==='en'?'Training':'Εκπαίδευση'} subtitle={language==='en'?'Assignments and completion data come directly from Training programmes.':'Οι αναθέσεις και οι ολοκληρώσεις αντλούνται απευθείας από τα προγράμματα Εκπαίδευσης.'}/>
    <State {...state} language={language} onRetry={state.reload}/>
    {!state.loading&&!state.error&&<RegistryFilter query={registry.query} setQuery={registry.setQuery} language={language} count={registry.filtered.length}/>}
    {!state.loading&&!state.error&&(registry.filtered.length?<><div className="scroll-table"><table className="data-table sticky-table record-table-clickable"><thead><tr><th>{language==='en'?'Training':'Εκπαίδευση'}</th><th>{language==='en'?'Date':'Ημερομηνία'}</th><th>{language==='en'?'Status':'Κατάσταση'}</th><th>{language==='en'?'Score':'Βαθμολογία'}</th></tr></thead><tbody>{paging.paged.map(row=><tr key={row.id} tabIndex={0} onClick={()=>setSelected(row)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(row)}}}><td><strong>{language==='el'?(row.titleEl||row.titleEn):(row.titleEn||row.titleEl)}</strong></td><td>{fmt(row.date)}</td><td><span className={`status-badge ${statusClass(row.status)}`}>{label(row.status,t)}</span></td><td>{row.score!=null?`${row.score}%`:'—'}</td></tr>)}</tbody></table></div><Pager paging={paging} total={registry.filtered.length} language={language}/></>:<Empty language={language} title={language==='en'?'No training records':'Δεν υπάρχουν εκπαιδεύσεις'}/>) }
    {selected&&<ObserverDialog width="wide" eyebrow={language==='en'?'Employee training':'Εκπαίδευση εργαζομένου'} title={language==='el'?(selected.titleEl||selected.titleEn):(selected.titleEn||selected.titleEl)} subtitle={fmt(selected.date)} onClose={()=>setSelected(null)} footer={canOpenProgram&&selected.programId?<Button onClick={()=>goTo(`/training/${selected.programId}`,{tab:'training',returnTo:`/employees/${encodeURIComponent(employee.id)}`,returnTab:'training'})}>{language==='en'?'Open training programme':'Άνοιγμα εκπαίδευσης'}</Button>:undefined}><div className="detail-grid"><div className="detail-item"><span>{language==='en'?'Status':'Κατάσταση'}</span><strong>{label(selected.status,t)}</strong></div><div className="detail-item"><span>{language==='en'?'Assigned':'Ανάθεση'}</span><strong>{fmt(selected.assignedDate)}</strong></div><div className="detail-item"><span>{language==='en'?'Completed':'Ολοκλήρωση'}</span><strong>{fmt(selected.completedDate)}</strong></div><div className="detail-item"><span>{language==='en'?'Score':'Βαθμολογία'}</span><strong>{selected.score!=null?`${selected.score}%`:'—'}</strong></div></div></ObserverDialog>}
  </section>
}

function trainingAnswerText(question,answer,en){const q=normalizeTrainingQuestion(question);if(answer===undefined||answer===null||answer==='')return '—';if(q.type==='single_choice')return q.options.find(option=>option.id===answer)?.text||String(answer);if(q.type==='multiple_choice')return (Array.isArray(answer)?answer:[]).map(value=>q.options.find(option=>option.id===value)?.text||String(value)).join(', ')||'—';if(q.type==='true_false'){const value=answer===true||answer==='true'||answer===1||answer==='1';return value?(en?'True':'Σωστό'):(en?'False':'Λάθος')}return String(answer)}

export function EmployeeEvaluationsTab({employee,language,fmt,organizationId,canCreate=false,canHrApprove=false,canAdminApprove=false,selfReadOnly=false}){
  const state=useEmployeeSubRecords(loadEvaluationsAsync,organizationId,employee.dbId,employee.id)
  const {notify,notifyError}=useFeedback();const [selected,setSelected]=useState(null),[creating,setCreating]=useState(false),[saving,setSaving]=useState(false),[ackOpen,setAckOpen]=useState(false),[ackAgreement,setAckAgreement]=useState(''),[ackComment,setAckComment]=useState('')
  const registry=useRegistryRows(state.data),paging=registry.paging,en=language==='en'
  const managedQuestionnaires=loadSnapshot('management_questionnaires_v1',null);const performanceTemplate=(Array.isArray(managedQuestionnaires)?managedQuestionnaires.find(x=>x.id==='employee-performance-evaluation'):null)||PERFORMANCE_EVALUATION_QUESTIONNAIRE
  const [draft,setDraft]=useState({period:'',date:new Date().toISOString().slice(0,10),notes:'',criteria:performanceTemplate.questions.map((q,index)=>({id:q.id||String(index+1),name:q.label||q.labelEl||q.labelEn,score:3,weight:1}))})
  const statusLabel=v=>({draft:en?'Draft':'Πρόχειρη',submitted:en?'Submitted':'Υποβλήθηκε',employee_acknowledged:en?'Employee acknowledged':'Έλαβε γνώση',hr_approved:en?'HR approved':'Εγκρίθηκε από HR',finalized:en?'Finalized':'Οριστικοποιημένη'}[v]||v||'—')
  async function create(){setSaving(true);try{await createEmployeeEvaluationAsync(organizationId,employee.dbId,draft);notify(en?'Evaluation saved.':'Η αξιολόγηση αποθηκεύτηκε.','success');setCreating(false);await state.reload()}catch(error){notifyError(error,en?'Could not save evaluation.':'Δεν ήταν δυνατή η αποθήκευση της αξιολόγησης.')}finally{setSaving(false)}}
  async function action(name,comment,agreement=''){setSaving(true);try{const updated=await updateEmployeeEvaluationWorkflowAsync(organizationId,employee.dbId,selected.id,{action:name,comment,agreement});setSelected(updated);await state.reload()}finally{setSaving(false)}}
  return <section className="record-section record-secondary-registry">
    <SectionTitle title={en?'Evaluations':'Αξιολογήσεις'} subtitle={en?'Performance evaluations and training knowledge assessments.':'Αξιολογήσεις απόδοσης και αξιολογήσεις γνώσεων από την Εκπαίδευση.'} action={canCreate&&<ActionButton tone="primary" label={en?'New evaluation':'Νέα αξιολόγηση'} onClick={()=>setCreating(true)}><Plus size={16}/><span>{en?'New evaluation':'Νέα αξιολόγηση'}</span></ActionButton>}/>
    <State {...state} language={language} onRetry={state.reload}/>
    {!state.loading&&!state.error&&<RegistryFilter query={registry.query} setQuery={registry.setQuery} language={language} count={registry.filtered.length}/>}
    {!state.loading&&!state.error&&(registry.filtered.length?<><div className="scroll-table"><table className="data-table sticky-table record-table-clickable"><thead><tr><th>{en?'Evaluation':'Αξιολόγηση'}</th><th>{en?'Period':'Περίοδος'}</th><th>{en?'Evaluator':'Αξιολογητής'}</th><th>{en?'Date':'Ημερομηνία'}</th><th>{en?'Score':'Βαθμολογία'}</th><th>{en?'Status':'Κατάσταση'}</th></tr></thead><tbody>{paging.paged.map(row=><tr key={row.id} tabIndex={0} onClick={()=>setSelected(row)}><td><strong>{en?row.titleEn:row.titleEl}</strong></td><td>{row.period||'—'}</td><td>{row.source==='training'?(en?'Training':'Εκπαίδευση'):(row.evaluatorName||'—')}</td><td>{fmt(row.date)}</td><td>{row.overallScore!=null?`${row.overallScore.toFixed(2)} / 5`:(en?row.resultEn:row.resultEl)||'—'}</td><td><span className={`status-badge ${statusClass(row.status)}`}>{statusLabel(row.status)}</span></td></tr>)}</tbody></table></div><Pager paging={paging} total={registry.filtered.length} language={language}/></>:<Empty language={language}/>)}
    {creating&&<ObserverDialog width="wide" eyebrow={en?'Performance evaluation':'Αξιολόγηση απόδοσης'} title={en?'New employee evaluation':'Νέα αξιολόγηση εργαζομένου'} onClose={()=>setCreating(false)} footer={<div className="dialog-actions"><Button variant="secondary" onClick={()=>setCreating(false)} disabled={saving}>{en?'Cancel':'Ακύρωση'}</Button><Button onClick={create} disabled={saving||!draft.period}>{en?'Save':'Αποθήκευση'}</Button></div>}>
      <div className="entry-grid"><label><span>{en?'Evaluation period':'Περίοδος αξιολόγησης'} *</span><input value={draft.period} onChange={e=>setDraft(v=>({...v,period:e.target.value}))} placeholder="2026"/></label><ManualDateField label={en?'Evaluation date':'Ημερομηνία αξιολόγησης'} value={draft.date} onChange={value=>setDraft(v=>({...v,date:value}))}/></div>
      <div className="evaluation-scale-grid">{[[1,en?'Unsatisfactory':'Ανεπαρκής'],[2,en?'Needs improvement':'Χρειάζεται βελτίωση'],[3,en?'Meets requirements':'Πλήρως επαρκής'],[4,en?'Exceeds requirements':'Υπερβαίνει τις απαιτήσεις'],[5,en?'Outstanding':'Εξαιρετική επίδοση']].map(([n,label])=><div key={n}><strong>{n}</strong><span>{label}</span></div>)}</div>
      <div className="evaluation-criteria evaluation-criteria-edit">{draft.criteria.map((item,index)=><div className="evaluation-criterion" key={item.id}><strong>{item.name}</strong><div className="evaluation-rating">{[1,2,3,4,5].map(n=><button type="button" key={n} className={item.score===n?'is-selected':''} aria-pressed={item.score===n} onClick={()=>setDraft(v=>({...v,criteria:v.criteria.map((x,i)=>i===index?{...x,score:n}:x)}))}>{n}</button>)}</div></div>)}</div>
      <label className="entry-field"><span>{en?'Manager comments':'Σχόλια προϊσταμένου'}</span><textarea value={draft.notes} onChange={e=>setDraft(v=>({...v,notes:e.target.value}))}/></label>
    </ObserverDialog>}
    {selected&&<ObserverDialog width="wide" eyebrow={en?'Employee evaluation':'Αξιολόγηση εργαζομένου'} title={en?selected.titleEn:selected.titleEl} subtitle={`${selected.period||''} · ${fmt(selected.date)}`} onClose={()=>setSelected(null)}>
      {selected.source==='training'&&<div className="training-assessment-review"><div className="training-assessment-summary"><div><span className="eyebrow">{en?'KNOWLEDGE ASSESSMENT':'ΑΞΙΟΛΟΓΗΣΗ ΓΝΩΣΕΩΝ'}</span><strong>{selected.program?.title||selected.titleEl}</strong><small>{fmt(selected.date)}</small></div><div className="training-assessment-score"><strong>{selected.score!=null?`${selected.score}%`:'—'}</strong><span>{selected.competent===true?(en?'Successful':'Επιτυχής'):selected.competent===false?(en?'Retraining required':'Απαιτείται επανεκπαίδευση'):'—'}</span></div></div><section className="training-review-section"><div className="training-review-heading"><div><span className="eyebrow">{en?'ASSESSMENT FORM':'ΦΟΡΜΑ ΑΞΙΟΛΟΓΗΣΗΣ'}</span><h3>{en?'Questions & submitted answers':'Ερωτήσεις & υποβληθείσες απαντήσεις'}</h3><p>{en?'The answers submitted by the employee are shown below.':'Παρακάτω εμφανίζονται οι απαντήσεις που υπέβαλε ο εργαζόμενος.'}</p></div></div><div className="training-answer-list">{(selected.assessmentQuestions||[]).map((question,index)=><article className="training-answer-card" key={question.id||index}><div className="training-answer-question"><span className="training-answer-index">{index+1}</span><strong>{question.text||'—'}</strong></div><div className="training-answer-value"><span className="training-answer-label">{en?'Answer':'Απάντηση'}</span><strong>{Array.isArray(selected.assessmentAnswers?.[question.id])?selected.assessmentAnswers[question.id].join(', '):trainingAnswerText(question,selected.assessmentAnswers?.[question.id],en)}</strong></div></article>)}</div></section>{selected.certificate&&<div className="training-review-certificate-row"><div><strong>{en?'Training certificate':'Πιστοποιητικό εκπαίδευσης'}</strong><small>{en?'Available after successful completion.':'Διαθέσιμο μετά την επιτυχή ολοκλήρωση.'}</small></div><Button onClick={()=>downloadCertificatePdf({certificate:selected.certificate,program:selected.program,participantName:[employee.firstName,employee.lastName].filter(Boolean).join(' ')||employee.id,en})}><Download size={14}/>{en?'Print certificate':'Εκτύπωση πιστοποιητικού'}</Button></div>}</div>}
      {selected.source!=='training'&&<div className="source-truth-note"><div><strong>{en?'Supervisor / evaluator':'Προϊστάμενος / αξιολογητής'}</strong><span>{selected.evaluatorName||'—'}</span></div></div>}{selected.overallScore!=null&&<div className="evaluation-score-hero"><strong>{selected.overallScore.toFixed(2)} / 5</strong><span>{statusLabel(selected.status)}</span></div>}
      <div className="evaluation-criteria">{(selected.criteria||[]).map(item=><div className="evaluation-criterion" key={item.id||item.name}><strong>{item.name}</strong><span className="status-badge">{item.score} / 5</span></div>)}</div>
      {selected.notes&&<div className="source-truth-note"><div><strong>{en?'Manager comments':'Σχόλια προϊσταμένου'}</strong><span>{selected.notes}</span></div></div>}
      {selected.employeeAgreement&&<div className="source-truth-note"><div><strong>{en?'Employee position':'Θέση εργαζομένου'}</strong><span>{selected.employeeAgreement==='agree'?(en?'Agrees with the evaluation':'Συμφωνεί με την αξιολόγηση'):(en?'Disagrees with the evaluation':'Διαφωνεί με την αξιολόγηση')}</span></div></div>}{selected.employeeComment&&<div className="source-truth-note"><div><strong>{en?'Employee comment':'Σχόλιο εργαζομένου'}</strong><span>{selected.employeeComment}</span></div></div>}
      <div className="dialog-actions">{selected.source==='employee_evaluations'&&selected.status==='draft'&&canCreate&&<Button onClick={()=>action('submit')} disabled={saving}>{en?'Submit to employee':'Υποβολή στον εργαζόμενο'}</Button>}{selected.status==='submitted'&&selfReadOnly&&<Button onClick={()=>{setAckAgreement('');setAckComment('');setAckOpen(true)}} disabled={saving}>{en?'Acknowledge receipt':'Έλαβα γνώση'}</Button>}{selected.status==='employee_acknowledged'&&canHrApprove&&<Button onClick={()=>action('hrApprove')} disabled={saving}>{en?'HR approval':'Έγκριση HR'}</Button>}{selected.status==='hr_approved'&&canAdminApprove&&<Button onClick={()=>action('finalize')} disabled={saving}>{en?'Final approval':'Τελική έγκριση'}</Button>}</div>
    </ObserverDialog>}
    {ackOpen&&<ObserverDialog width="medium" eyebrow={en?'Employee acknowledgement':'Γνώση εργαζομένου'} title={en?'Acknowledge evaluation':'Έλαβα γνώση της αξιολόγησης'} onClose={()=>setAckOpen(false)} footer={<div className="dialog-actions"><Button variant="secondary" onClick={()=>setAckOpen(false)}>{en?'Cancel':'Ακύρωση'}</Button><Button disabled={saving||!ackAgreement||(ackAgreement==='disagree'&&!ackComment.trim())} onClick={async()=>{await action('acknowledge',ackComment,ackAgreement);setAckOpen(false)}}>{en?'Confirm':'Επιβεβαίωση'}</Button></div>}><div className="evaluation-acknowledgement"><p>{en?'Your acknowledgement does not change the supervisor score. Select whether you agree or disagree with the evaluation.':'Η δήλωση γνώσης δεν μεταβάλλει τη βαθμολογία του προϊσταμένου. Επιλέξτε αν συμφωνείτε ή διαφωνείτε με την αξιολόγηση.'}</p><label className="evaluation-ack-choice"><input type="radio" name="evaluation-agreement" value="agree" checked={ackAgreement==='agree'} onChange={()=>setAckAgreement('agree')}/><span><strong>{en?'I agree':'Συμφωνώ'}</strong><small>{en?'I agree with the evaluation.':'Συμφωνώ με την αξιολόγηση.'}</small></span></label><label className="evaluation-ack-choice"><input type="radio" name="evaluation-agreement" value="disagree" checked={ackAgreement==='disagree'} onChange={()=>setAckAgreement('disagree')}/><span><strong>{en?'I disagree':'Διαφωνώ'}</strong><small>{en?'My disagreement will be recorded for HR and the administrator.':'Η διαφωνία μου θα καταγραφεί για το HR και τον διαχειριστή.'}</small></span></label><label className="entry-field"><span>{en?'Employee comment':'Σχόλιο εργαζομένου'}{ackAgreement==='disagree'?' *':''}</span><textarea value={ackComment} onChange={e=>setAckComment(e.target.value)} placeholder={en?'Optional when you agree; required when you disagree.':'Προαιρετικό όταν συμφωνείτε · υποχρεωτικό όταν διαφωνείτε.'}/></label></div></ObserverDialog>}
  </section>
}

export function EmployeeCertificatesTab({employee,language,organizationId,canEdit=false}){
  return <DocumentsWorkspace
    title={language==='en'?'Documents & certifications':'Έγγραφα & Πιστοποιήσεις'}
    subtitle={language==='en'?'All employee files are kept in one place. Each attachment is classified by document type when it is added.':'Όλα τα αρχεία του εργαζομένου τηρούνται σε ένα σημείο. Κάθε επισύναψη χαρακτηρίζεται κατά την προσθήκη με τον τύπο του εγγράφου.'}
    disabled={!canEdit}
    organizationId={organizationId}
    entityType="employee-certificate"
    entityId={employee.dbId||employee.id}
  />
}

export function EmployeeSurveillanceTab({employee,t,language,fmt,version,onNew,readOnly=false,isDemo=false,organizationId=null,canManageFollowup=false}){
  const demoRows=isDemo?getEmployeeSurveillanceForEmployee(employee.id):[]
  const [cloudRecords,setCloudRecords]=useState([])
  const [cloudSamples,setCloudSamples]=useState([])
  const [selected,setSelected]=useState(null)
  const [loading,setLoading]=useState(!isDemo)
  useEffect(()=>{if(isDemo||!organizationId||!employee?.dbId){setLoading(false);return}let active=true;setLoading(true);Promise.all([loadEmployeeSurveillanceRecords(organizationId),loadLaboratorySamples(organizationId)]).then(([records,samples])=>{if(!active)return;setCloudRecords(records.filter(row=>row.employeeDbId===employee.dbId));setCloudSamples(samples)}).catch(()=>{if(active){setCloudRecords([]);setCloudSamples([])}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[isDemo,organizationId,employee?.dbId,version])
  const rows=isDemo?demoRows:cloudRecords
  const registry=useRegistryRows(rows)
  const paging=registry.paging
  const selectedSamples=selected?(isDemo?demoLaboratorySamples.filter(sample=>sample.employeeSurveillanceCase===selected.id):cloudSamples.filter(sample=>sample.employeeSurveillanceId===selected.recordId)):[]
  const saveDemoFollowup=(record,patch)=>Promise.resolve(updateEmployeeSurveillanceRecord(record.id,{...patch,updatedAt:new Date().toISOString()}))
  return <section className="record-section record-secondary-registry"><SectionTitle title={language==='en'?'Surveillance':'Επιτήρηση'} subtitle={language==='en'?'Employee screening episodes and their linked laboratory samples.':'Επεισόδια επιτήρησης εργαζομένου και τα συνδεδεμένα εργαστηριακά δείγματα.'} action={!readOnly&&<ActionButton tone="primary" label={t('newSurveillance')} onClick={onNew}><Plus size={15}/><span>{t('newSurveillance')}</span></ActionButton>}/>{!loading&&<RegistryFilter query={registry.query} setQuery={registry.setQuery} language={language} count={registry.filtered.length}/>} {loading?<div className="inline-empty">{language==='en'?'Loading…':'Φόρτωση…'}</div>:registry.filtered.length?<><div className="scroll-table"><table className="data-table sticky-table record-table-clickable"><thead><tr><th>{language==='en'?'Episode':'Επεισόδιο'}</th><th>{language==='en'?'Start date':'Έναρξη'}</th><th>{language==='en'?'Screening':'Έλεγχος'}</th><th>{language==='en'?'Status':'Κατάσταση'}</th></tr></thead><tbody>{paging.paged.map(row=><tr key={row.id} tabIndex={0} onClick={()=>setSelected(row)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(row)}}}><td><strong className="employee-code-compact" title={row.id}>{compactEpisodeCode(row.id)}</strong></td><td>{fmt(row.startedAt)}</td><td>{row.screeningTypes?.map(type=>label(type,t)).join(', ')||'—'}</td><td><span className={`status-badge ${statusClass(row.status)}`}>{label(row.status,t)}</span></td></tr>)}</tbody></table></div><Pager paging={paging} total={registry.filtered.length} language={language}/></>:<Empty language={language} title={language==='en'?'No surveillance episodes':'Δεν υπάρχουν επεισόδια επιτήρησης'}/>} {selected&&<EmployeeSurveillanceRecordDialog organizationId={organizationId} record={selected} samples={selectedSamples} canManage={canManageFollowup} t={t} language={language} fmt={fmt} onClose={()=>setSelected(null)} onSaveFollowup={isDemo?saveDemoFollowup:undefined} onUpdated={updated=>{if(!isDemo)setCloudRecords(current=>current.map(row=>row.recordId===updated.recordId?updated:row));setSelected(updated)}}/>}</section>
}

export function EmployeeHistoryTab({employee,language}){
  const state=useEmployeeSubRecords(loadEmployeeHistoryAsync,employee.organizationId,employee.dbId,employee.id)
  const fallback=[]
  if(employee.createdAt)fallback.push({id:'legacy-created',action:'insert',at:employee.createdAt,actorName:'',actorRole:'',changedFields:[]})
  if(employee.updatedAt&&employee.updatedAt!==employee.createdAt)fallback.push({id:'legacy-updated',action:'update',at:employee.updatedAt,actorName:'',actorRole:'',changedFields:[]})
  const rows=(state.data.length?state.data:fallback).slice().sort((a,b)=>new Date(b.at||0)-new Date(a.at||0))
  const registry=useRegistryRows(rows)
  const paging=registry.paging
  const format=value=>{if(!value)return '—';const d=new Date(value);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat(language==='en'?'en-GB':'el-GR',{dateStyle:'medium',timeStyle:'short'}).format(d)}
  const eventLabel=action=>action==='insert'?(language==='en'?'Employee record created':'Δημιουργία καρτέλας εργαζομένου'):action==='delete'?(language==='en'?'Employee record deleted':'Διαγραφή καρτέλας εργαζομένου'):(language==='en'?'Employee record updated':'Ενημέρωση καρτέλας εργαζομένου')
  const fieldLabels={employee_code:['Κωδικός εργαζομένου','Employee code'],department_id:['Τμήμα','Department'],department_name:['Τμήμα','Department'],department_name_en:['Τμήμα (EN)','Department (EN)'],first_name:['Όνομα','First name'],first_name_en:['Όνομα (EN)','First name (EN)'],last_name:['Επώνυμο','Last name'],last_name_en:['Επώνυμο (EN)','Last name (EN)'],father_name:['Πατρώνυμο','Father name'],profession_name:['Ιδιότητα','Profession'],profession_name_en:['Ιδιότητα (EN)','Profession (EN)'],employment_status:['Κατάσταση εργασίας','Employment status'],email:['Email','Email'],phone:['Τηλέφωνο','Phone'],hire_date:['Ημερομηνία πρόσληψης','Hire date'],birth_date:['Ημερομηνία γέννησης','Birth date'],user_id:['Σύνδεση λογαριασμού','Account link']}
  const changedLabel=fields=>fields?.length?fields.map(key=>fieldLabels[key]?.[language==='en'?1:0]||key).join(' · '):'—'
  const actorLabel=row=>row.actorName?`${row.actorName}${row.actorRole?` · ${row.actorRole.replaceAll('_',' ')}`:''}`:'—'
  return <section className="record-section record-secondary-registry">
    <SectionTitle title={language==='en'?'History':'Ιστορικό'} subtitle={language==='en'?'Administrative lifecycle of the employee record. Clinical events remain in their own governed tabs.':'Διοικητικό ιστορικό της καρτέλας εργαζομένου. Τα κλινικά συμβάντα παραμένουν στις αντίστοιχες ελεγχόμενες καρτέλες.'}/>
    <State {...state} language={language} onRetry={state.reload}/>
    {!state.loading&&!state.error&&<RegistryFilter query={registry.query} setQuery={registry.setQuery} language={language} count={registry.filtered.length}/>}
    {!state.loading&&!state.error&&(registry.filtered.length?<><div className="scroll-table"><table className="data-table sticky-table"><thead><tr><th>{language==='en'?'Event':'Ενέργεια'}</th><th>{language==='en'?'Changes':'Μεταβολές'}</th><th>{language==='en'?'User':'Χρήστης'}</th><th>{language==='en'?'Date / time':'Ημερομηνία / ώρα'}</th></tr></thead><tbody>{paging.paged.map(row=><tr key={row.id}><td><strong>{eventLabel(row.action)}</strong></td><td>{row.action==='update'?changedLabel(row.changedFields):'—'}</td><td>{actorLabel(row)}</td><td>{format(row.at)}</td></tr>)}</tbody></table></div><Pager paging={paging} total={registry.filtered.length} language={language}/></>:<Empty language={language} title={language==='en'?'No lifecycle history is available':'Δεν υπάρχει διαθέσιμο ιστορικό καρτέλας'}/>) }
  </section>
}
